### ISSUE TITLE
dataTable updates do not work after filtering and calling filter() as a workaround changes page

### ISSUE THREAD

**Issue by gkiagia** [primefaces/primefaces#1753] opened 2016-09-08 06:41 UTC
I have a dataTable with sorting and filters, populated from a List of custom objects that are fetched from a database with Hibernate. In this page, I also have a dialog that can edit the data of each row. In the dialog, I have a "Save" button that saves the current entry in the db and reloads the List of objects that populate the dataTable. The button code looks like this:

``` xhtml
<p:commandButton id="btn"
    value="Save" 
    action="#{myBean.save}"
    onsuccess="PF('editDialog').hide();"
    update="myTable"/>
```

Because of the `update="myTable"`, I expect that the table's data will be reloaded from the new List and therefore the updated row will be shown correctly int the table.

This works fine when I have not used any filtering or sorting from the headers since I reloaded the page. But, as soon as I set a filter (and even if I clear it afterwards), or sort by a certain column, updating of the table stops working ! It will continue to show the old data, no matter what the List in the Bean contains.

I have found several reports in forums about this issue and the suggested solution is to call the `filter()` function from javascript to reload the contents of the dataTable with the filters enabled, which brings me to this code in the button:

``` xhtml
<p:commandButton id="btn" 
    value="Save"
    action="#{myBean.save}"
    onsuccess="PF('editDialog').hide(); PF('myTableVar').filter();"/>
```

Now this works even with filters set, the dataTable gets always updated correctly. Yay!

BUT! The filter() call has a side-effect: It will always reset the paginator's current page to 1, so even if I'm editing data in page 20, it will get me back to the first one. This kills productivity in my application. The only workaround I have found so far is this:

``` xhtml
<p:commandButton id="btn" 
    value="Save" 
    action="#{myBean.save}" 
    onsuccess="PF('editDialog').hide();
           var first = PF('myTableVar').paginator.getFirst();
           var rows = PF('myTableVar').paginator.getRows();
           var page = first/rows;
           PF('myTableVar').filter();
           var handler2 = function(e, x, s) {
              PF('myTableVar').paginator.setPage(page);
              $(document).unbind('pfAjaxComplete', handler2);
           };
           var handler = function(e, x, s) {
              $(document).unbind('pfAjaxComplete', handler);
              $(document).on('pfAjaxComplete', handler2);
           };
           $(document).on('pfAjaxComplete', handler);"/>
```

I find this a really bad workaround. I believe PF should update the dataTable correctly in the first place.

PS: the two handlers in the js above are needed because the first one is being called too early for some reason which I don't fully understand.
## 1) Environment
- PrimeFaces version: `6.0`
- Does it work on the newest PrimeFaces version? `no`
- Application server + version: `WildFly 8.1.0`
- Affected browsers: `Firefox 41, haven't tested with others`
## 2) Expected behavior

The dataTable should be updated when a button with `update="myTable"` is clicked, no matter what the state of the filters or sorting is.
## 3) Actual behavior

The dataTable is not updated if a filter or sorting is set.

**Comment by tomlux** [comment] 2016-11-03 14:05
We also have the same problem (PF6.0)

**Comment by jxmai** [comment] 2017-03-13 19:28
related to #1715 comment https://github.com/primefaces/primefaces/issues/1715#issuecomment-244608049 (bug No. 1)

**Comment by Restage** [comment] 2018-02-14 12:45
We could solve this problem by calling `clear()` before every new LazyLoadingQuery on the `EntityManager` in our DAO classes. This detaches all objects from the previous query from the EntityManager and hands a fresh result list to the view bean. This list gets rendered without any problems.
Without this mechanism we always had the correct number of rows and pages displayed in datatable, but the values appeared to be the old ones.

**Comment by melloware** [comment] 2020-07-16 18:31
Duplicate of #1715

**Closed as completed by melloware** 2020-07-16 18:31 UTC
Labels: Resolution: Duplicate
