### ISSUE TITLE
DataTable: Vertical header

### ISSUE THREAD

**Issue by richmondspears** [primefaces/primefaces#183] opened 2015-04-28 02:26 UTC
This is a migration of issue #6764 from the google hosted issue tracker (https://code.google.com/p/primefaces/issues/detail?id=6764).

It would be great if the orientation of the <p:dataTable> could be rotated such that the column data is horizontal.

e.g.
Rather than:

_Year Height
1990 63
1991 68
1992 73_

I would like:

_Year 1990 1991 1992
Height 63 68 73_

This was previously requested in a thread in 2010:

http://forum.primefaces.org/viewtopic.php?f=3&t=6427

On 18th April 2015, Cagatay suggested in a comment on the ticket that this requirement was catered for via reflow mode.

Reflow mode is a most welcome addition however I would suggest that the 'stacked mode' as demonstrated in the blog (see here: http://blog.primefaces.org/?p=3417) isn't the same as the example that led to the creation of this ticket.

i.e instead of:

_Year 1990 1991 1992
Height 63 68 73_

reflow mode produces:

_Year 1990 
Height 63 
Year 1991
Height 68
Year 1992
Height 73_

This is ideal for mobile devices but does not make the most of horizontal screen estate for desktop/widescreen devices or use cases where one would like to compare the data in this orientation and have it all visible on-screen at the same time.

I would imagine that reflow mode could be extended to include this feature?

**Comment by kukel** [comment] 2015-05-04 13:33
the way reflow works is totally different then what is required here. Your request is so much different. This requires a total transposition of the data and therefor is not something that 'reflow'  could include easily.

**Comment by aosama** [comment] 2015-09-02 03:07
would be great to have this feature

**Comment by mrodriguezmad** [comment] 2018-10-04 15:34
I think it is a very useful feature in some cases. Above all integrated with the DataExporter.

**Comment by melloware** [comment] 2021-06-15 19:33
Closing as duplicate of this request: https://github.com/primefaces/primefaces/issues/2931  Or its similar enough...

**Closed as not planned by melloware** 2021-06-15 19:33 UTC
Labels: Resolution: Duplicate

**Comment by jentrent** [comment] 2023-02-11 23:28
Was this feature ever implemented?

**Comment by melloware** [comment] 2023-02-11 23:33
No issue #2931 is still open and it would probably require Pro sponsorship.
