### ISSUE TITLE
Dialog: add onresizestart and onresizeend javascript events

### ISSUE THREAD

**Issue by mrswadge** [primefaces/primefaces#1588] opened 2016-07-08 17:11 UTC
When a dialog is resized we would like to change the opacity of the dialog and after resizing make sure that the dialog is positioned in the centre of the screen. The place to do this appears to be by modifying the PrimeFaces.widget.Dialog.prototype.setupResizable method for the start and stop functions. What could be better for developers would be for us to be able to define onresizestart and onresizeend functions that could be called upon a resize event.

```
PrimeFaces.widget.Dialog.prototype.setupResizable = function(setupResizable) {
    return function() {
    var a = this;
    this.jq.resizable({
      handles: "n,s,e,w,ne,nw,se,sw",
      minWidth: this.cfg.minWidth,
      minHeight: this.cfg.minHeight,
      alsoResize: this.content,
      containment: "document",
      start: function(b, c) {
        a.jq.css({opacity: 0.5}); // change opacity for resize
        a.jq.data("offset", a.jq.offset());
        if (a.cfg.hasIframe) {
          a.iframeFix = $('<div style="position:absolute;background-color:transparent;width:100%;height:100%;top:0;left:0;"></div>').appendTo(a.content)
        }
      },
      stop: function(b, c) {
        var d = a.jq.data("offset");
        a.jq.css("position", "fixed");
        a.jq.offset(d);
        if (a.cfg.hasIframe) {
          a.iframeFix.remove()
        }
        a.jq.css({opacity: 1}); // return opacity to normal
        a.initPosition(a.cfg.position); // center dialog
      }
    });
    this.resizers = this.jq.children(".ui-resizable-handle")
    };
}(PrimeFaces.widget.Dialog.prototype.setupResizable);
```

The method override above could be avoided if there was a method that could be provided at dialog definition time. i.e.

```
<p:dialog id="dialog1" widgetVar="dialog1" modal="true" fitViewport="true"
    onresizestart="function() { console.log('resize start.'); }"
    onresizeend="function() { console.log('resize end.'); }"
/>
```

And then a tweak to the configuration for the widget (not shown), plus the javascript change below.

```
      start: function(b, c) {
        if (a.cfg.onresizestart) {
          a.cfg.onresizestart.apply(a);
        }
        a.jq.data("offset", a.jq.offset());
        if (a.cfg.hasIframe) {
          a.iframeFix = $('<div style="position:absolute;background-color:transparent;width:100%;height:100%;top:0;left:0;"></div>').appendTo(a.content)
        }
      },
      stop: function(b, c) {
        var d = a.jq.data("offset");
        a.jq.css("position", "fixed");
        a.jq.offset(d);
        if (a.cfg.hasIframe) {
          a.iframeFix.remove()
        }
        if (a.cfg.onresizeend) {
          a.cfg.onresizeend.apply(a);
        }
      }
```

Hopefully this is a reasonable request.

Thanks,
Stuart

**Comment by tandraschko** [comment] 2017-10-18 14:25
Feel free to provide a PR!

**Comment by tandraschko** [comment] 2019-01-04 19:14
Implement behaviors.

You can do:
<p:ajax event="resizeStart|resizeStop" onstart="someJS(); return false;" />
or use
<pe:javascript event="resizeStart|resizeStop" execute="someJS(); return false;" />

the second approach produces fewer js content, maybe we should move it PF core.

**Comment by tandraschko** [comment] 2019-01-04 19:15
Duplicate of: https://github.com/primefaces/primefaces/issues/4028

**Closed as completed by tandraschko** 2019-01-04 19:14 UTC
Labels: Resolution: Duplicate, new feature

**Comment by landrit** [comment] 2022-11-30 08:16
@tandraschko 
Is there an example of this?
How can I set the width and height of the content to 100% of the space when resizing?
Every time I resize the dialog the width and height is getting set but it does not use the whole space available

![image](https://user-images.githubusercontent.com/34266191/204741637-3a90fccd-d3ad-4820-9ea5-17d174c82ec5.png)

How can I prevent the default behaviour that the height and width gets set whenever I resize?

**Comment by melloware** [comment] 2022-11-30 12:38
@landrit Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.
