### ISSUE TITLE
columnToggler doesn't hide when update dataTable in p:ajax

### ISSUE THREAD

**Issue by sourour** [primefaces/primefaces#1446] opened 2016-05-23 13:48 UTC
I use primefaces 5.3, I have dataTable with 4 rows header,so I use columnGroup ,I put columnToggler for the second row of header and manually with a listener fix the colspan of first row of header. so I should update the table with ajax.
when I put update at ajax (for columntoggler) , every thing is ok , but the check box of columntoggler doesn't hide when click out.
this is my xhtml code:
`<p:columnToggler datasource="table" trigger="toggler" widgetVar="columnToggler" id="columnToggler">
                   <p:ajax event="toggle" listener="#{dashbord.onToggle}" process="@this" 
                   update="table" />    
                   </p:columnToggler>`
Could someone have an idea please ?

Thanks

**Comment by cnsgithub** [comment] 2016-05-23 14:19
Hi, The info and code you posted  is probably not enough to reproduce what you are experiencing.

But my suggestion would be to try 6.0RC3, if you're using 5.3 (not elite), as there have been a lot of bugfixes since it's release.

**Comment by sourour** [comment] 2016-05-23 15:37
Hi,
I don't use elite version.
`
<h:form id="form1">
    <p:dataTable style="width:1300px" id="table1" scrollable="true"
        scrollHeight="500" scrollWidth="1300" selectionMode="single"
        rowKey="#{item.account}" value="#{dashbord.listAm}"
        widgetVar="table1V" var="item"
        filteredValue="#{dashbord.filteredList}">
        <p:ajax event="filter" listener="#{dashbord.onFilter}"
            update="form1:table1" process="@form" />
        <f:facet name="header">
            <div align="left">
                <p:commandButton id="toggler" type="button" title="Columns"
                    icon="ui-icon-calculator" />
                <p:columnToggler datasource="table1" trigger="toggler"
                    id="columnToggler">
                    <p:ajax event="toggle" listener="#{dashbord.onToggle}"
                        update="form1:table1" />
                </p:columnToggler>
        </f:facet>
        <p:columnGroup type="header">
            <p:row>
                <p:column rowspan="2" sortBy="#{item.status}" toggleable="false">
                    <f:facet name="header">
                        <h:outputText value="Status" />
                    </f:facet>
                </p:column>
                <p:column id="globalE" colspan="3" visible="#{dashbord.list[1]}">
                    <f:facet name="header">
                        <h:outputText value="Amount" />
                    </f:facet>
                </p:column>
                <p:column colspan="3" visible="#{dashbord.list[2]}"
                    toggleable="#{dashbord.showFlag eq false}">
                    <f:facet name="header">
                        <h:outputText value="Quantity" />
                    </f:facet>
                </p:column>
            </p:row>
            <p:row>
                <p:column sortBy="#{item.currentAmount}" toggleable="false"
                    visible="#{dashbord.list[1]}" headerText="Current" />
                <p:column sortBy="#{item.priorAmount}" headerText="Prior"
                    toggleable="false" visible="#{dashbord.list[1]}" />
                <p:column sortBy="#{item.diffAmount}" headerText="Diff"
                    toggleable="false" visible="#{dashbord.list[1]}" />
                <p:column sortBy="#{item.currentQuantity}" toggleable="false"
                    visible="#{dashbord.list[2] }" headerText="Current" />
                <p:column sortBy="#{item.priorQuantity}" headerText="Prior"
                    toggleable="false" visible="#{dashbord.list[2]}" />
                <p:column sortBy="#{item.diffQuantity}" headerText="Diff"
                    toggleable="false" visible="#{dashbord.list[2]}" />
            </p:row>
        </p:columnGroup>
        <p:column>
            <h:outputText value="#{item.status}" />
        </p:column>
        <p:column visible="#{dashbord.list[1]}">
            <div align="right">
                <h:outputText value="#{item.priorAmount}">
                    <f:convertNumber pattern="#,##0;(#,##0)" minFractionDigits="2"
                        minIntegerDigits="1" />
                </h:outputText>
            </div>
        </p:column>
        <p:column style="width:80px;font-size:90%"
            visible="#{dashbord.list[1]}">
            <div align="right">
                <h:outputText value="#{item.currenctAmount}">
                    <f:convertNumber pattern="#,##0;(#,##0)" minFractionDigits="2"
                        minIntegerDigits="1" />
                </h:outputText>
            </div>
        </p:column>
        <p:column style="width:80px;font-size:90%"
            visible="#{dashbord.list[1]}">
            <div align="right">
                <h:outputText value="#{item.diffAmount}">
                    <f:convertNumber pattern="#,##0;(#,##0)" minFractionDigits="2"
                        minIntegerDigits="1" />
                </h:outputText>
            </div>
        </p:column>
        <p:column
            visible="#{dashbord.list[2] and  dashbord.showFlag eq false}">
            <div align="right">
                <h:outputText value="#{item.currentQuantity}">
                    <f:convertNumber pattern="#,##0;(#,##0)" minFractionDigits="2"
                        minIntegerDigits="1" />
                </h:outputText>
            </div>
        </p:column>
        <p:column
            visible="#{dashbord.list[2] and  dashbord.showFlag eq false}">
            <div align="right">
                <h:outputText value="#{item.priorQuantity}">
                    <f:convertNumber pattern="#,##0;(#,##0)" minFractionDigits="2"
                        minIntegerDigits="1" />
                </h:outputText>
            </div>
        </p:column>
        <p:column
            visible="#{dashbord.list[2] and  dashbord.showFlag eq false}">
            <div align="right">
                <h:outputText value="#{item.diffQuantity}">
                    <f:convertNumber pattern="#,##0;(#,##0)" minFractionDigits="2"
                        minIntegerDigits="1" />
                </h:outputText>
            </div>
        </p:column>
    </p:dataTable>
</h:form>`

**Comment by sourour** [comment] 2016-06-13 13:19
Hi,
I try to use new version 6.0 but same issue .Please,you have an idea? how much time to fix this item.

Thanks.

**Comment by sourour** [comment] 2016-07-15 13:57
primefaces elite version could resolve this issue ? Please advise.

**Comment by jmorris1501** [comment] 2016-09-02 12:00
hi, i had the same issue as @sourour, updated to 6.0 with maven, no change.

**Comment by djmj** [comment] 2017-06-28 08:19
Its not a bug. The client widget of the column toggler is still visible. By updating your table you create a new instance leaving the old client instance of column toggler open. You must manually hide it before update or move it outside the scope of the table.

	<p:columnToggler widgetVar="colTogglerWidgetVar">
		<p:ajax event="toggle" process="@this"
	        	onstart="PF('colTogglerWidgetVar').hide();" />
	</p:columnToggler>

For the requirement to update the table after column visibility have changed a new ajax event like hide would be a better solution. So that multiple columns can be made invisible and after this the table is updated via ajax.

	<p:ajax event="hide" process="@this" update="myTable"/>

**Comment by jmorris1501** [comment] 2017-06-28 12:15
Updated columnToggler to have the "hide" ajax event, and tried the same with the datatable. This was the result:

javax.servlet.ServletException: /pages/reports/summaryhours.xhtml @97,98 <p:ajax> Event:hide is not supported.
	javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.stanchion.tma.util.AuthFilter.doFilter(AuthFilter.java:42)

**Comment by djmj** [comment] 2017-06-28 17:39
@jmorris1501 There is no ajax event _hide_ currently. It was just an idea for a feature request.

**Comment by melloware** [comment] 2020-03-31 19:11
This is fixed as of 8.0.  Attached is a reproducible test case showing the toggler is closed.
[pf-1446.zip](https://github.com/primefaces/primefaces/files/4411113/pf-1446.zip)

**Closed as completed by melloware** 2020-03-31 19:11 UTC
Labels: :lady_beetle: defect
