### ISSUE TITLE
Immediate form evaluation for queued requests with p:ajax

### ISSUE THREAD

**Issue by frederikd** [primefaces/primefaces#109] opened 2015-04-19 21:35 UTC
The behaviour of f:ajax (Mojarra) and p:ajax is currently quite different for queued requests.
In Mojarra the values that are supposed to be submitted as part of the ajax request are evaluated at the time the request is added to the queue, i.e. whatever the value was at the time the request is triggered is what is going to be submitted, irrespective of any changes to the value in the meantime.
In Primefaces the values are evaluated at the time the request is dequeued/processed, so any modifications to the form that happened after the request was triggred are reflected in the submission.

Both options seem reasonable to me as you might want to have different behaviour in different circumstances. E.g. if only "@this" is being submitted on an ajax request then you probably want the value at the time the event was triggerd, i.e. whatever the user entered, however if a field is being submitted as the result of another field being changed then you might want to have the latest value.

Our scenario is as follows:
We have pages with lots of fields (p:calendar, p:selectOneMenu, pe:inputNumber, h:inputText etc.) which all trigger ajax requests on change and re-render the parent panel. If the user tabs through and makes lots of changes quickly so that the ajax requests don't respond before the next change is made then some of the user input is lost, because the previous ajax request finishes late, potentially updates the next field and then p:ajax only evaluates the form input value when the request is dequeued. f:ajax on the other hand evaluates the the form input at the time of the request being added to the queue, so whatever the user entered will be sent, not whatever the components value is at the time the request is processed.

Ideally we would like to have p:ajax work like f:ajax, i.e. immediate evaluation rather than delayed evaluation, but it might make sense to add an option (either globally or on the p:ajax element as an attribute) to toggle this behaviour.

This issue is logged as a result of a discussion on issue #23

**Comment by cagataycivici** [comment] 2015-04-19 22:01
@tandraschko @mertsincan What do you guys think?

**Comment by tandraschko** [comment] 2015-04-20 06:40
As i already stated, i like the idea and this will probably fix an old bug of all my apps.
I could take care of it but the change is to heavy for a elite release IMO.

**Comment by cagataycivici** [comment] 2015-04-20 09:36
Let's discuss a bit more after I review.

**Comment by frederikd** [comment] 2015-04-20 20:36
If there is any additional details you need from us or if we can help in any other way to make this feature happen then please let me know. We are very keen on making full use of p:ajax and would be very happy to contribute where we can. :)

**Comment by tandraschko** [comment] 2015-04-21 07:02
@cagataycivici I will try if it will fix my problems and create a patch. So you can review both.

**Comment by cagataycivici** [comment] 2015-04-21 07:51
I'm not sure about this, delegated evaluation for me is the way to go which we have already. Immediate evaluation is confusing and buggy from my point of view. If we receive more demand, we'll consider it but for now we'll not take any action.

**Comment by tandraschko** [comment] 2015-04-21 14:32
@cagataycivici what about JUST evaluating the source component value early and the other inputs when the request starts?
This should fix the problem mention in the both issues and we change a small piece.

**Comment by cagataycivici** [comment] 2015-04-21 16:35
How do you plan to do that with a small piece? Will it solve @frederikd's case?

**Comment by tandraschko** [comment] 2015-04-21 19:02
let me do a small prototype tomorrow :)
Yep it will solve it and and it's a good mix between the two ways.
The problem currently  is really that the inputs are probably lost when the user types to fast. This is also replicateable via a small example:

p:input with p:ajax with update=@form
h:selectOneMenu with p:ajax with update=@form

focus the input, type something and directly click the checkbox. 

What happens:

1) leave input -> start request 1 with checkbox=unchecked
2) checkbox clicked and checked -> start request2
3) receive response 1 -> update checkbox with unchecked
4) send request 2 from queue -> eval from inputs (checkbox is currently unchecked)

Therefore the correct state of the checkbox is lost.
As i said, we can fix this if we eval the source component value before adding the request to the queue. What i need to check, how easy it is to pass/get the source component and value.
The handling is also just required for simple input components, not for e.g. datatable select event.

**Comment by frederikd** [comment] 2015-04-21 19:15
@cagataycivici what @tandraschko is explaining is exactly the kind of issue we have. So to only evaluate the source component early should solve our problem. I also agree that it probably makes more sense to evaluate other components late, so if there is a solution to this then that would be great.

**Comment by cagataycivici** [comment] 2015-04-21 19:32
I see, @tandraschko whenever you have time please do a fork and I'll take a look at the implementation from your repository.

**Comment by tandraschko** [comment] 2015-04-22 12:22
@frederikd please give it a try -> https://gist.github.com/tandraschko/a73e7ef85960d4d9e401

It should work, however, thats also not a 100% super for the enduser. My test works fine now but the checkbox ofc still blinks as it will be unchecked after the first request and checked again after the second ajax request.

**Comment by frederikd** [comment] 2015-04-22 19:30
Thanks @tandraschko - we'll give it a go and let you know as soon as we can.

**Comment by frederikd** [comment] 2015-04-23 05:49
@tandraschko we tried to use that patch in our application, but there are too many other changes between our currently used Primefaces version (5.1.7) and 5.2 so that we could not get it to run yet, so couldn't confirm so far.
I will be out of the office tomorrow and we have a public holiday on Monday, so will only be able to confirm on Tuesday whether it works for us or not. Sorry for the delay.

**Comment by tandraschko** [comment] 2015-04-29 12:46
any news? the patch should also work on 5.1 - it's just dirty migrated to 5.2 now for testing.

**Comment by frederikd** [comment] 2015-04-29 21:21
@tandraschko, sorry for the delay. We had some issues testing this, but this was due to our application, not Primefaces.
After getting it all to work I can now confirm that your change fixed our issue. Thanks.

**Comment by tandraschko** [comment] 2015-05-19 20:52
@cagataycivici 
plz have a look at my "alpha testing"-patch.
it fixes the problem but it needs more attention, like moving the early evaluation to a own method, adding the parameter namespace for portlets and so on.
If you agree, i will take care of it.
We can also disable it per default for now via a context param. But IMO it should be active per default.

**Comment by tandraschko** [comment] 2015-05-19 20:57
sourceElement.find(':input').serializeArray();
instead
sourceElement.find(':input').each(function(index, input) {
 ... loop code

should also be possible.
As it said, it was just done for testing.

**Comment by frederikd** [comment] 2015-08-30 20:33
@tandraschko it's been a while now with no activity so just wanted to check whether you guys are still planning to include this in the upcoming 5.3 release in "early fall 2015"?

**Comment by tandraschko** [comment] 2015-08-30 20:36
still need feedback from @cagataycivici
I would provide an far better patch like the last dirty patch check it again.

**Comment by tandraschko** [comment] 2015-10-12 18:22
Will do it probably next month - it's a current requirement in new application.
We can still decide to make it optional via config flag but that should be the default behavior as user input is lost if the ajax request takes longer. It's actually more a bug that a feature request.

**Comment by kukel** [comment] 2016-05-03 18:13
:-1:  for not making it into 6.0... I ran into this several days ago... @cagataycivici: can you please review for a 6.1 or 6.0.x release?

**Comment by tandraschko** [comment] 2016-05-03 18:46
i would commit it, it's not a problem but you will still see a flickering. So the fix it not perfect IMO.

**Comment by frederikd** [comment] 2016-05-04 07:19
@tandraschko it would still be better than the current solution. :)
We are still not using p:ajax (much) because of this issue, so we would really appreciate even a not-perfect fix.

**Comment by tandraschko** [comment] 2016-05-04 22:03
i fear the problem is that the is currently not fix which is really perfect :/
Does the flickering also occur in mojarra? (would be weird if it doesn't)

**Comment by frederikd** [comment] 2016-05-05 04:25
@tandraschko I haven't seen this fix in Primefaces so do not know what the flickering would look like, and therefore can't really confirm.
But in Mojarra the field might get its value changed by one queued Ajax request and then back again by the next and then back to a third value again, depending on how the data is modified server-side. Not sure whether you mean this with flickering. If yes then I don't see an issue with that as it is somewhat expected in the circumstances.

**Comment by tandraschko** [comment] 2016-05-05 07:47
ok, will do it on the weekend but i will disable it per default. Could you please also test it early next week?
I think that's actually an good enhancement for 6.0.

**Comment by tandraschko** [comment] 2016-05-05 07:48
It's an shame that you can't use p:ajax with it's cool features :)

**Comment by mikhailChibel** [comment] 2016-05-05 21:09
@tandraschko, on behalf of @frederikd, we will test the fix middle next week and then let you know results.

**Comment by tandraschko** [comment] 2016-05-06 10:47
Committed!
Please test test test guys
You can activate it via:
   `<context-param>  
        <param-name>primefaces.EARLY_POST_PARAM_EVALUATION</param-name>  
        <param-value>true</param-value>  
    </context-param>`

**Comment by tandraschko** [comment] 2016-05-13 09:29
Any news? ;)

**Comment by frederikd** [comment] 2016-05-13 09:56
@tandraschko we've started but not completed testing. Hopefully can do so on Monday. Will let you know as soon as possible. Thanks!

**Comment by mikhailChibel** [comment] 2016-05-16 03:16
@tandraschko  Sorry for the delay, I've tested on 6.0.RC4-SNAPSHOT and found no issues. When configuring with EARLY_POST_PARAM_EVALUATION the request evaluated immediately matching to JSF behavior. Without EARLY_POST_PARAM_EVALUATION settings, request evaluated at the send time (existing behavior). Thanks.

**Comment by tandraschko** [comment] 2016-06-01 09:50
Thanks for testing!

**Closed as completed** 2016-06-01 09:49 UTC
Labels: enhancement, 6.0.RC4
