### ISSUE TITLE
Dialog: Stacked Dialogs are closed in the wrong order using ESC button

### ISSUE THREAD

**Issue by RohdeSchwarz-SDC** [primefaces/primefaces#11308] opened 2024-01-19 15:21 UTC
### Describe the bug

Simply create some dialogs (let `dialog3`, `dialog2`, `dialog1`) with property `closeOnEscape="true"` and open them cascaded.

Then close them by pressing `ESC` button.

Dialogs close in the order, they appear in the DOM not according to `z-index` (topmost first).

### Reproducer

[StackedDialogs.zip](https://github.com/primefaces/primefaces/files/13991031/StackedDialogs.zip)

### Expected behavior

Dialogs should close from top to bottom (respecting the `z-index`).

### PrimeFaces edition

Community

### PrimeFaces version

13.0.4

### Theme

default

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

### Browser(s)

all

**Comment by melloware** [comment] 2024-01-19 19:24
Maybe the order is wrong but this fix looks like it is using z-index: https://github.com/primefaces/primefaces/issues/6677

**Comment by melloware** [comment] 2024-01-19 19:48
Runnable fixed reproducer with MonkeyPatch:
[pf-11308.zip](https://github.com/primefaces/primefaces/files/13993816/pf-11308.zip)

```js
if (PrimeFaces.widget.Dialog) {
    PrimeFaces.widget.Dialog.prototype.bindEvents = function() {
        var $this = this;

        //Move dialog to top if target is not a trigger for a PrimeFaces overlay
        this.jq.on("mousedown", function(e) {
            if (!$(e.target).data('primefaces-overlay-target')) {
                $this.moveToTop();
            }
        });

        this.icons.on('mouseover', function() {
            $(this).addClass('ui-state-hover');
        }).on('mouseout', function() {
            $(this).removeClass('ui-state-hover');
        }).on('focus', function() {
            $(this).addClass('ui-state-focus');
        }).on('blur', function() {
            $(this).removeClass('ui-state-focus');
        });

        this.closeIcon.on('click', function(e) {
            $this.hide();
            e.preventDefault();
        });

        this.maximizeIcon.on("click", function(e) {
            $this.toggleMaximize();
            e.preventDefault();
        });

        this.minimizeIcon.on("click", function(e) {
            $this.toggleMinimize();
            e.preventDefault();
        });

        if (this.cfg.closeOnEscape) {
            $(document).on('keydown.dialog_' + this.id, function(e) {
                if(!e.isDefaultPrevented() && e.key === 'Escape' && $this.isVisible()) {
                    // GitHub #6677 if multiple dialogs check if this is the topmost active dialog to close
                    var currentZindex = parseInt($this.jq.css('z-index'));
                    var dialogZIndex = parseInt($('.ui-dialog:visible').first().css('z-index'));
                    if(currentZindex === dialogZIndex) {
                         $this.hide();
                         e.preventDefault();
                         e.stopPropagation();
                    }
                };
            });
        }
    };
}
```

**Comment by melloware** [comment] 2024-01-23 01:46
13.0.5 has been released with this fix.

**Comment by vonnai** [comment] 2024-01-24 09:18
Hi, the way how you find the visible dialog with the highest z-index is wrong. This code ```var dialogZIndex = parseInt($('.ui-dialog:visible').first().css('z-index'));``` really doesn't find the dialog with the highest z-index, but some dialog.

Please try this solution:
```
var currentZIndex = parseInt($this.jq.css('z-index'));
var index_highest = 0;
$('.ui-dialog:visible').each(function(){
    var index_current = parseInt($(this).css("z-index"));
    if(index_current > index_highest) {
        index_highest = index_current;
    }
});
if(currentZIndex === index_highest) {
    $this.hide();
    e.preventDefault();
    e.stopPropagation();
}
```

**Comment by melloware** [comment] 2024-01-24 12:52
@vonnai check out my PR i slightly modified your code but it does the exact same behavior!

**Comment by vonnai** [comment] 2024-01-24 12:56
it looks good, better than before. Thanks.

**Comment by melloware** [comment] 2024-01-24 12:57
Thanks for the hint!

**Closed as completed** 2024-01-24 13:43 UTC
Labels: :lady_beetle: defect, workaround
