### ISSUE TITLE
p:selectOneMenu not rendering correctly on windows tablet/IE11

### ISSUE THREAD

**Issue by asiletto** [primefaces/primefaces#884] opened 2015-11-17 09:37 UTC
to replicate the issue you need a **windows touch** tablet. I tested it on a lenovo thinkpad
- Open IE11
- go to http://www.primefaces.org/showcase/ui/input/oneMenu.xhtml
- pinch & zoom on the screen
- open a select input

result: the panel is opened in a wrong screen location.

the same problem can be simulated on IE/Chrome adding a **zoom** css property to body
body {
  zoom: 1.4;
}

**Comment by fmasini** [comment] 2015-11-17 14:44
I have replicated the same issue on an HP Elite x2 1011 on IE11 (windows 8 touch).
Same issue on primefaces and primefaces sentinel showcase.

Problem on: pinch&zoom, select one menu, calendar.

**Comment by cagataycivici** [comment] 2015-11-18 09:40
Does it only happen on windows tables with IE? How about android, ios devices?

**Comment by asiletto** [comment] 2015-11-18 09:47
Hello, it happens only with windows on these windows tablets with detachable screen. It happens on IE11  but also in Chrome. Android and iOS are ok.

I think the pinch&zoom on these tablet are somewhat different from the classic mobile zoom (cannot be blocked/disabled with the meta viewport tag).

The same problem also happens on the datepicker dialog, in both primefaces and primefaces mobile.

**Comment by mertsincan** [comment] 2015-11-18 16:47
Can you please attach a screenshot for us?

**Comment by asiletto** [comment] 2015-11-18 16:58
Here's the screenshot from the online showcase, using some little zoom. Zooming more cause the panel to go completely off screen.

![select-one-zoom2](https://cloud.githubusercontent.com/assets/2478596/11247729/9be5ff32-8e1d-11e5-9289-3ceba5998e2d.png)

You can easily replicate the behaviour using Chrome on a PC, pressing F12 and setting a {zoom:1.5} css property on the tag body

![select-one-zoom1](https://cloud.githubusercontent.com/assets/2478596/11247657/52051286-8e1d-11e5-87aa-86f8da0543bb.png)

**Comment by mertsincan** [comment] 2015-11-19 07:41
Please try with  appendTo="@this" on selectOneMenu;

```
<p:selectOneMenu appendTo="@this" ...>
```

**Comment by asiletto** [comment] 2015-11-19 10:43
using appendTo="@this" the panel is shown correctly near the select box, but the values are not selectable anymore.

clicking on any value trigger the panel to disappear, but the value clicked is then not selected

**Comment by raskajan** [comment] 2016-03-23 13:57
I have same issue as you reported. 

I found a root cause. PF fail to detect clicks outside panel with item. jQuery that PF uses provides offset() and position(). But jQuery doesn't provide correct dimension: "Also, dimensions may be incorrect when the page is zoomed by the user; browsers do not expose an API to detect this condition. "

If PF detects a click outside of a panel, the panel is closed and selected value is revert to previous one. Otherwise PF fires selectItem event.

If selectOneMenu doesn't have appendTo attribute, clicks detection works because coordinates of panel and click are getting in the same way => wrong place, but detection works.
But if appendTo is used, PF doesn't care of placing panel, only on click coordinates. Different way, wrong detection.

Workaround: disable zooming or change component.

**Comment by asiletto** [comment] 2016-03-30 09:13
We have changed component. 

We cannot disable zoom, these hybrid mobile devices do behave like desktops, and do not follow the <meta name="viewport" tag

**Comment by raskajan** [comment] 2016-05-16 05:10
Hi,
If you can use own compiled primefaces libraries, the fix is easy.
Instead of detect click outside of a menu item panel using coordinates, you can check if a target of click is the panel or its children.
So bugfix in bindConstantEvents could be like this:

```
if (!$(c.target).parents(this.panelId)) {
                b.hide();
                b.revert();
                b.changeAriaValue(b.getActiveItem())
            }
```

**Comment by melloware** [comment] 2018-11-23 17:37
Can someone check this with the latest Showcase and IE11 to determine if this is still an issue?

**Comment by melloware** [comment] 2019-09-11 19:07
No answers from OP so closing until we get further information.

**Closed as completed by melloware** 2019-09-11 19:07 UTC
