### ISSUE TITLE
Update fullcalendar to 2.3.2

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#220] opened 2015-05-03 16:20 UTC
Update fullcalendar to 2.3.2 since it looks they are only correcting bugs. https://github.com/arshaw/fullcalendar/releases

**Comment by sudheerj** [comment] 2016-01-20 09:22
The current latest version is 2.6.So this issue can be duplciate of #1029

**Comment by erickdeoliveiraleal** [comment] 2016-05-02 16:09
2.7.1 https://github.com/fullcalendar/fullcalendar/releases

**Comment by tandraschko** [comment] 2016-05-02 19:04
Duplicate of #1029

**Closed as completed by tandraschko** 2016-05-02 19:04 UTC
Labels: Resolution: Duplicate
