### ISSUE TITLE
Charts MultiAxis issue with responsive option

### ISSUE THREAD

**Issue by RejDev** [primefaces/primefaces#408] opened 2015-06-08 04:33 UTC
Hello,
to better see the problem , take the example of the showcase (Charts - MultiAxis), and add the option `responsive="true"` to `<p:chart>` .
The width of the BarChartSeries do not fit(adapts) the window width when resizing.
a temporary solution is to force the refresh of the window every time.

Link : http://www.primefaces.org/showcase/ui/chart/multiaxis.xhtml
Thanks.

**Comment by cagataycivici** [comment] 2015-06-08 16:06
Duplicate of #343

**Closed as completed by cagataycivici** 2015-06-08 16:06 UTC
