### ISSUE TITLE
Sorting/filtering for dataTable with stickyHeader inside tabView seems broken.

### ISSUE THREAD

**Issue by miczal** [primefaces/primefaces#1937] opened 2016-11-30 14:28 UTC
## 1) Environment
- PrimeFaces version: **6.0**
- Does it work on the newest PrimeFaces version? **I didn't see any correction when greping "stickyHeader" in change log. I run community version.**

- Application server + version: **Apache Tomcat 8.0.36**
- Affected browsers: **Chrome, FF, IE**

## 2) Expected behavior

Columns of `p:dataTable` with `stickyHeader="true"`, which is inside `p:tabView`  should be sortable and filters should apply normally.

## 3) Actual behavior
Filters are unselectable and columns can't be sorted in base position of header. You have to click on "header" appearing somewhere inside the `p:dataTable` - if you don't have enough rows per page it's hidden. 

## 4) Steps to reproduce

Run code XHTML, try to sort/filter. When `stickyHeader="false"` everything's fine or when `p:dataTable` **isn't** inside `p:tabView`. When `rows` in `p:dataTable` are changed to small value, you don't see this pseudo-header. I don't know if this is related only to "lazy" DataTable - I didn't check that.
## 5) Sample XHTML
Modified Primefaces showcase [http://www.primefaces.org/showcase/ui/data/datatable/lazy.xhtml](http://www.primefaces.org/showcase/ui/data/datatable/lazy.xhtml)

```html
<p:tabView id="tabView" cache="false" dynamic="true"> 
    <p:tab id="STATUS">
        <f:facet name="title">
            <h:outputText value="#{messages['tab.status']}" /> 
        </f:facet>
        <h:form id="form">
            <p:dataTable var="car" value="#{dtLazyView.lazyModel}"
                paginator="true" rows="100"
                paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                rowsPerPageTemplate="5,10,15,100" selectionMode="single" selection="#{dtLazyView.selectedCar}" id="carTable" lazy="true" stickyHeader="true" >
                <p:column headerText="Id" sortBy="#{car.id}" filterBy="#{car.id}">
                    <h:outputText value="#{car.id}" />
                </p:column>
                <p:column headerText="Year" sortBy="#{car.year}" filterBy="#{car.year}">
                    <h:outputText value="#{car.year}" />
                </p:column>
                <p:column headerText="Brand" sortBy="#{car.brand}" filterBy="#{car.brand}">
                    <h:outputText value="#{car.brand}" />
                </p:column>
                <p:column headerText="Color" sortBy="#{car.color}" filterBy="#{car.color}">
                    <h:outputText value="#{car.color}" />
                </p:column>
            </p:dataTable>
            <p:dialog header="Car Detail" widgetVar="carDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false">
                <p:outputPanel id="carDetail" style="text-align:center;">
                    <p:panelGrid  columns="2" rendered="#{not empty dtLazyView.selectedCar}" columnClasses="label,value">
                        <f:facet name="header">
                            <p:graphicImage name="demo/images/car/#{dtLazyView.selectedCar.brand}-big.gif"/> 
                        </f:facet>
         
                        <h:outputText value="Id:" />
                        <h:outputText value="#{dtLazyView.selectedCar.id}" />
         
                        <h:outputText value="Year" />
                        <h:outputText value="#{dtLazyView.selectedCar.year}" />
         
                        <h:outputText value="Color:" />
                        <h:outputText value="#{dtLazyView.selectedCar.color}" style="color:#{dtLazyView.selectedCar.color}"/>
         
                        <h:outputText value="Price:" />
                        <h:outputText value="#{dtLazyView.selectedCar.price}">
                            <f:convertNumber type="currency" currencySymbol="$" />
                        </h:outputText>
                    </p:panelGrid>
                </p:outputPanel>
            </p:dialog>
        </h:form>
    </p:tab>
</p:tabView>
```

## 6) Sample bean
Beans are taken from mentioned showcase here:
[http://www.primefaces.org/showcase/ui/data/datatable/lazy.xhtml](http://www.primefaces.org/showcase/ui/data/datatable/lazy.xhtml)

**Comment by melloware** [comment] 2020-11-11 21:16
Duplicate of https://github.com/primefaces/primefaces/issues/6381 which has a reproducer.

**Closed as completed by melloware** 2020-11-11 21:16 UTC
Labels: Resolution: Duplicate
