### ISSUE TITLE
TabView: fixed width moves scrollable header

### ISSUE THREAD

**Issue by Ponferson** [primefaces/primefaces#7226] opened 2021-04-14 09:02 UTC
**Describe the defect**
With a fixed width and a scrollable head, the text is truncated and the header is moved when clicked.

**Reproducer**
If the header is minimally smaller than the TabView, the text is truncated.
![grafik](https://user-images.githubusercontent.com/39244449/114682239-312c7700-9d0f-11eb-8ffc-0dbc2fb1f712.png)
If you click on the padding of the first or last list element at the edge of the TabView, the header moves left.
![grafik](https://user-images.githubusercontent.com/39244449/114683876-afd5e400-9d10-11eb-8a5c-dcb5c6204b17.png)

**Environment:**
 - PF Version: 10
 - Affected browsers: Chrome, Firefox

**To Reproduce**
Steps to reproduce the behavior moving header:
1. Click on the padding of the first or last `<li>` at the upper left edge.

**Expected behavior**
No moving the header or show arrows after moving the header 

**Example XHTML**
```html
<h:form id="frmTest" style="width:425px;">
  <p:tabView  scrollable="true">
    <p:tab title="Test long text 1">
    </p:tab>
    <p:tab title="Test long text 2">
     </p:tab>
      <p:tab title="Test long text 3">
      </p:tab>
	</p:tabView>
    </h:form>
```

**Comment by melloware** [comment] 2021-04-14 12:08
Reproducer:
[pf-7226.zip](https://github.com/primefaces/primefaces/files/6310667/pf-7226.zip)

**Comment by melloware** [comment] 2021-04-14 12:09
I think this is as designed in the scrollable TabView.  If I make your width 800px it does not happen.  I think the problem is it thinks it needs to scroll your tab into view because it exceeds its container.  I believe this is expected behavior.

**Comment by Ponferson** [comment] 2021-04-14 14:08
> 
> 
> I think this is as designed in the scrollable TabView. If I make your width 800px it does not happen. I think the problem is it thinks it needs to scroll your tab into view because it exceeds its container. 

That is exactly the point. Apparently there is a width at which the tab titles are not fully displayed and the navigation arrows not showing, which are dependent on the size of the characters. 

For example, if I have a certain browser width then this problem occours.
*To Reproduce*
-> I can click on the first element and the header moves so it disappears.
or
-> I can click on the last element, I can no longer click on the first element.
![grafik](https://user-images.githubusercontent.com/39244449/114720596-6ef1c580-9d38-11eb-9ba5-5cb403a7d7e1.png)

**Comment by melloware** [comment] 2021-04-15 12:10
Assigning to @squores  I have no idea what the "correct" behavior should be.

**Comment by Ponferson** [comment] 2021-04-16 06:58
> 
> 
> Assigning to @squores I have no idea what the "correct" behavior should be.

I would expect to avoid scrolling if there are no navigation arrows visible. This would basically avoid scrolling over.
In the event 'focus.tabview' is checked scrollable header. 
A possible solution would be to change the event as follows
```js 
if (b.cfg.scrollable) {
  if (c.position().left + c.width() > b.navcrollerRight.position().left && b.navcrollerRight.is(':visible')) {
      b.navcrollerRight.trigger("click.tabview")
  } else {
      if (c.position().left < b.navcrollerLeft.position().left && b.navcrollerLeft.is(':visible')) {
          b.navcrollerLeft.trigger("click.tabview")
 }}}

**Comment by melloware** [comment] 2021-04-16 13:26
Great idea. I submitted a PR.  If anyone needs a monkeypatch just add this code to your application.
```javascript
if (PrimeFaces.widget.TabView) {

    PrimeFaces.widget.TabView.prototype.bindKeyEvents = function() {
        var $this = this,
            tabs = this.headerContainer;

        /* For Screen Reader and Keyboard accessibility */
        tabs.attr('tabindex', this.tabindex);

        tabs.on('focus.tabview', function(e) {
                var focusedTab = $(this);

                if (!focusedTab.hasClass('ui-state-disabled')) {
                    focusedTab.addClass('ui-tabs-outline');

                    if ($this.cfg.scrollable) {
                        if ($this.navcrollerRight.is(':visible') && (focusedTab.position().left + focusedTab.width() > $this.navcrollerRight.position().left)) {
                            $this.navcrollerRight.trigger('click.tabview');
                        } else if ($this.navcrollerLeft.is(':visible') && (focusedTab.position().left < $this.navcrollerLeft.position().left)) {
                            $this.navcrollerLeft.trigger('click.tabview');
                        }
                    }
                }
            })
            .on('blur.tabview', function() {
                $(this).removeClass('ui-tabs-outline');
            })
            .on('keydown.tabview', function(e) {
                var keyCode = $.ui.keyCode,
                    key = e.which,
                    element = $(this);

                if ((key === keyCode.SPACE || key === keyCode.ENTER) && !element.hasClass('ui-state-disabled')) {
                    $this.select(element.index());
                    e.preventDefault();
                }
            });

        //Scrolling
        if (this.cfg.scrollable) {
            this.navcrollerLeft.on('keydown.tabview', function(e) {
                var keyCode = $.ui.keyCode,
                    key = e.which;

                if (key === keyCode.SPACE || key === keyCode.ENTER) {
                    $this.scroll(100);
                    e.preventDefault();
                }
            });

            this.navcrollerRight.on('keydown.tabview', function(e) {
                var keyCode = $.ui.keyCode,
                    key = e.which;

                if (key === keyCode.SPACE || key === keyCode.ENTER) {
                    $this.scroll(-100);
                    e.preventDefault();
                }
            });
        }
    }
}
```

**Closed as completed** 2021-04-18 20:15 UTC
Labels: :lady_beetle: defect, workaround
