### ISSUE TITLE
PanelGrid: without <p:row> but with composite component containing <p:row> throws Exception

### ISSUE THREAD

**Issue by HolgerSuhr** [primefaces/primefaces#7272] opened 2021-04-29 12:59 UTC
A p:panelGrid without "columns=" needs to see at least one p:row directly. Otherwise it throws an exception.
If I use only composite components (with p:row inside) in this panelGrid I get this exception.

PanelGridRenderer:207 counts only p:row not p:row inside the component.

**Environment:**
 - PF Version: 10.0
 - Mojarra 2.3.9
 - Affected browsers: ALL

**Comment by melloware** [comment] 2021-04-29 13:04
Duplicate of https://github.com/primefaces/primefaces/issues/3355

**Closed as completed by melloware** 2021-04-29 13:04 UTC
Labels: workaround

**Comment by HolgerSuhr** [comment] 2021-04-29 13:14
That's no duplicate. Rel. 8.0 doesn't contain this code line

`        if (i == 0) {
            throw new FacesException("PanelGrid \"" + grid.getClientId(context)
                + "\" without a 'columns' attribute expects at least one <p:row> element.");
        }
`

**Comment by stolp** [comment] 2021-04-29 13:20
It is true that the behavior has changed from 8.0 to 10.0.0, yet IMHO it is now just enforcing a constraint that has been present all the time.

**Comment by melloware** [comment] 2021-04-29 13:47
@HolgerSuhr Can you please provide a PrimeFaces Test reproducer?  [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.

**Comment by melloware** [comment] 2021-04-29 13:49
It was originally fixed as part of this ticket: https://github.com/primefaces/primefaces/issues/6563

**Comment by HolgerSuhr** [comment] 2021-04-29 14:02
No, it wasn't present all the time.
Rel. 6-8.0 work perfect.
The xhtml doesn't contain a p:row but the components do. But these don't get counted.
If I insert a <p:row> in the first line after p:panelGrid, it works, because this one row was counted

**Comment by HolgerSuhr** [comment] 2021-04-29 14:08
@melloware 
You don't need a testproject.
Look at PanelGridRenderer line 207.
If *all* content gets rendered via line 198  `child.encodeAll(context);` you'll get the exception,
even if the table has 200 rows...

Ticket 6563 is a ticket to dataTable

**Comment by melloware** [comment] 2021-04-29 14:17
Yes I know what the code is doing but its working fine for me so without a reproducer how can we see your problem.

also working fine on all Showcase examples: https://www.primefaces.org/showcase/ui/panel/panelGrid.xhtml

So I am asking, I don't understand your problem?

**Comment by HolgerSuhr** [comment] 2021-04-29 14:22
hmm, it's so simple
I don't have any <p:row> in the xhtml of the <p:panelGrid>.
Instead I have many <x:specialComponent> which produce <p:row> 
But these don't get counted of the code in PanelGridRenderer because they are not at top level.
line 198 `child.encodeAll(context);` produces <p:row> entries, but these are not counted.

**Comment by melloware** [comment] 2021-04-29 14:30
Yep but isn't that EXACTLY ticket https://github.com/primefaces/primefaces/issues/3355 which I originally said is a duplicate.  Is that it doesn't search composites for <p:row> ????

**Comment by melloware** [comment] 2021-04-29 18:26
Try this...put and underendered row first `<p:row rendered="false"/>` does that work?
```xml
<p:panelGrid>
	<p:row rendered="false"/>
	<g:yourComposite />
</p:panelGrid>
```

**Comment by HolgerSuhr** [comment] 2021-04-30 07:37
Yes, that works.

**Comment by HolgerSuhr** [comment] 2021-05-03 12:37
This new exception in PanelGridRenderer:207 has really no need and no sense :-(
There are also many `<p:panelGrid` with a `<p:repeat` inside which often has nothing to repeat.
That's a normal situation, but now I get an exception.

**Comment by melloware** [comment] 2021-05-03 13:05
This exception makes perfect sense see: https://github.com/primefaces/primefaces/issues/6563

**Comment by HolgerSuhr** [comment] 2021-05-03 14:00
Did I read it correct in 6563?
For *this one* situation of
having a dataTable inside a panelGrid and don't like to insert `columns=` or `<p:row`
you inserted an exception that blows 
every empty panelGrid and every panelGrid consisting of composite components?

Very strange.
It would be interesting to know the count of blowing panelGrids in the world. I can start with 257.

**Comment by melloware** [comment] 2021-05-03 14:05
The real issue you are running into is this: https://github.com/primefaces/primefaces/issues/3355

If it searched composites and repeats for p:row's.

**Comment by stolp** [comment] 2021-05-03 14:06
We had about 40. With a little bit of regexp-magic, they were quick to find and fix.

I always welcome a framework telling me which mistakes make so I was quite ok with this in the long run.

Bu I confess I was excited at first too ...
