### ISSUE TITLE
JSF: Primefaces Selectonemenu nested combo issue

### ISSUE THREAD

**Issue by lcnerim** [primefaces/primefaces#6366] opened 2020-09-28 21:02 UTC
Hello

When you open two or more instances of a nested combo and you pick several options on each the page pops out the next error:

![errorcombo](https://user-images.githubusercontent.com/27609685/94485583-c917a880-01a3-11eb-9613-ddb68f743394.PNG)

The error can be checked at:
https://www.primefaces.org/showcase/ui/ajax/dropdown.xhtml

Thanks in advance!

**Comment by melloware** [comment] 2020-09-28 23:49
I think I fixed this in master already. I will check tomorrow morning.

**Comment by lcnerim** [comment] 2020-09-29 01:53
thanks for answer friend we appreciate your help :D keep in touch

**Comment by melloware** [comment] 2020-09-29 11:29
OK I cant reproduce your error.  Can you give me the exact steps you are doing?

**Comment by lcnerim** [comment] 2020-09-29 15:40
We were using IE and Chrome as browsers and did the next steps:

1.-Open the dropdown page, select values and click submit
2.-Duplicate the page and select values, then click submit
3.-Return to the first page, select a value and click submit

Now its not happening so often but sometimes pops the error

Can you please tell us what is the version of primefaces you are working
with?
Any dependency changes ?

Thanks friend!!

**Comment by melloware** [comment] 2020-09-29 15:49
hmm i am trying my hardest and i cant get it to happen with PF 8.0.

Chrome Version 85.0.4183.121 (Official Build) (64-bit)
Edge Version 85.0.564.63 (Official build) (64-bit)
IE 11.508

**Comment by melloware** [comment] 2020-09-30 12:35
@lcnerim any update on this?  I cant get it to happen.

**Comment by melloware** [comment] 2020-10-01 11:32
I am going to close this issue until we can get a reproducible test case. I can reopen if we do.

**Closed as completed by melloware** 2020-10-01 11:32 UTC
Labels: Resolution: Cannot Replicate, needs investigation
