### ISSUE TITLE
TabView: Update single tab

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#7467] opened 2021-06-25 16:36 UTC
When you explicitly set a tab to be updated, the tab content gets duplicated over all tabs.

**Environment:**
 - PF Version: 10.0.3
 - JSF + version: 2.3.14.SP04 (WildFly 24.0.0)
 - Affected browsers: all

**Example XHTML**
```html
<h:form id="frmTest">
    <p:tabView>
        <p:tab title="Tab 1">
        </p:tab>
        <p:tab title="Tab 2" id="tab2">
            <p:fieldset legend="Fieldset">
                ...
            </p:fieldset>
            <p:commandButton value="Save" action="..." update="tab2"/>
        </p:tab>
    </p:tabView>
</h:form>
```

When clicking "Save" in the above example, the fieldset from tab2 will also show up under the tab 1.

**Comment by melloware** [comment] 2021-06-25 16:44
Duplicate of https://github.com/primefaces/primefaces/issues/5960

See the explanation Tabs are not updateable you must update the whole TabView.

**Comment by fcorneli** [comment] 2021-06-25 16:45
ah OK, thanks.

**Comment by melloware** [comment] 2021-06-25 16:45
Also documented here: https://primefaces.github.io/primefaces/10_0_0/#/components/tabview?id=getting-started-with-the-tabview

**Closed as completed** 2021-06-25 16:45 UTC
Labels: Resolution: Duplicate, Resolution:  Wontfix
