### ISSUE TITLE
Noisy page transition in Wildfly 10

### ISSUE THREAD

**Issue by gpetrarca** [primefaces/primefaces#1368] opened 2016-05-02 09:48 UTC
[ExampleMavenServerOAM.zip](https://github.com/primefaces/primefaces/files/244800/ExampleMavenServerOAM.zip)
Here is attached a sample web app with 3 pages: 
- login page (access with username=admin)
- home page (PF based)
- home jsf page (similar to home page but only JSF based)

PF is 5.3 .
When running in Wildfly 10, the page transition from home page to login page is quite noisy, i.e. there is an evident transient where the page is displayed without the right CSS styles.
On the contrary, the transition from homejsf to login page is smooth.

Note: in Wildfly 8.2, the transition "noise" is quite smaller.

**Comment by tandraschko** [comment] 2016-05-02 11:15
And what should we do here? ;)

**Comment by tandraschko** [comment] 2016-05-02 11:16
The problem is that you update all (head + body) and therefore all resources will be loaded again. However, i don't think that a redirect will show a better result.

**Comment by gpetrarca** [comment] 2016-05-03 07:00
Without PF there is no "noise", therefore there is something wrong in the way with PF the page is loaded. 
Because of this noise I cannot (or I prefer not to) switch now from WildFly 8 to WF 10; someone else could be tempted to choose an alternative framework.
I think PF should care for a good interworking with the major Application Servers.

**Comment by tandraschko** [comment] 2016-05-03 07:38
Do you mean if i change home.xhtml to homejsf.xhtml in the faces-config nav rule?

We don't have any application server specific code and we won't add something.

**Comment by tandraschko** [comment] 2016-05-03 08:59
I replicated and created a issue for it:
https://github.com/primefaces/primefaces/issues/1379

our handling is actually correct. Will close this issue but you can stare the other one for the future.

**Closed as completed by tandraschko** 2016-05-03 08:59 UTC
Labels: Resolution:  Wontfix
