### ISSUE TITLE
DefaultCommand: exclusion of textarea,button,input[type="submit"],a does not work when used together with scope

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5348] opened 2019-11-19 16:28 UTC
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? No

## 2) Expected behavior
DefaultCommand should not be triggered inside a textarea. (Because inside a textarea we expect to create a new line with enter.)

## 3) Actual behavior
When used without scope it work´s fine. When used with scope it does not work.

## 4) Steps to reproduce
push enter within the textbox

## 5) Sample XHTML<?xml version="1.0" encoding="UTF-8"?>
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	  xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	  xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:f="http://xmlns.jcp.org/jsf/core"
	  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	  xmlns:p="http://primefaces.org/ui">

    <h:head>
    	<title>DefaultCommand; Scope</title>
    </h:head>
    
    <h:body>
    	<p:growl>
    		<p:autoUpdate />
    	</p:growl>
    
    	<h:form id="formA">
    		<p:inputText id="inputTextA" />
    		<p:inputTextarea id="inputTextareaA" />
    	</h:form>
    	
    	<h:form id="formB">
    		<p:commandButton id="commandButtonDoSomething" value="do something" action="#{defaultCommandIssueView.doSomething()}" />
    		<p:defaultCommand target="commandButtonDoSomething" scope="formA" />
    	</h:form>
    </h:body>
</html>
```

## 6) Sample bean
```
@Named
@RequestScoped
public class DefaultCommandIssueView {

	public void doSomething() {
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("something was done"));
	}
}
```

## 7) Root Cause:
https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/forms/forms.defaultcommand.js
In Line 27 we already check wether the event was triggered within a textarea.
But when the event is triggered via scope (line 43) this generates a new event and we loose the original event-context. So we need to add the 
```
if ($(e.target).is('textarea,button,input[type="submit"],a')) {
    return true;
}
```
between line 42 and 43 too.

**Comment by melloware** [comment] 2019-11-19 16:34
Related to https://github.com/primefaces/primefaces/issues/4984 See my comments on what may be wrong

**Comment by christophs78** [comment] 2019-11-19 16:44
Yes, same issue. Thank´s for pointing me on this.
I´ll provide a PR within the next few days.

**Comment by melloware** [comment] 2019-11-19 16:46
OK i will close this one as a dupe since the other has a runnable reproducer.

**Closed as completed by melloware** 2019-11-19 16:46 UTC
Labels: Resolution: Duplicate
