### ISSUE TITLE
CSP: splitButton - `onclick` does not work properly with blockUI, and file download. 

### ISSUE THREAD

**Issue by reginakupczak** [primefaces/primefaces#9769] opened 2023-02-06 09:42 UTC
### Describe the bug

CSP: splitButton - oncomplete, does not work properly with blockUI, and file download. 

### Reproducer

**Steps:**
1. run the code below
2. open the page
3. use the basic button
![image](https://user-images.githubusercontent.com/97100687/216937042-99dea0db-7f78-482e-ab3e-c80547706a7d.png)
4. use the save button
![image](https://user-images.githubusercontent.com/97100687/216937226-d47f7084-0487-4d93-afc3-6e5ff8add27b.png)
5. without CSP: -> block panel working fine, the file is downloaded 
6. with CSP:- > block panel not working, the file is not downloaded 
**Expected result**
App with CSP should work in the same way as without.

```xml
 <context-param>
        <param-name>primefaces.CSP</param-name>
        <param-value>true</param-value>
    </context-param>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

<h:head>
    <title>PrimeFaces Test</title>
    <h:outputScript name="test.js"/>
    <h:outputStylesheet name="test.css"/>
</h:head>
<h:body>
    <script>
        function startDl() {
            PF('buiDatatable').show();
        }

        function stopDl() {
            PF('buiDatatable').hide();
        }

    </script>

    <div class="card">
        <p:growl id="messages"/>
        <h:form id="sample123">
            <p:blockUI block="dlg1" widgetVar="buiDatatable">
                <i class="pi pi-spin pi-spinner" style="font-size: 3rem"></i>
            </p:blockUI>
        </h:form>

        <p:commandButton value="Basic" type="button" onclick="PF('dlg1').show();"/>

        <p:dialog id="dlg1" header="Basic Dialog" widgetVar="dlg1" minHeight="40">
            <h:form id="sample">
                <p:commandButton id="remoteDownload" ajax="false">
                    <p:fileDownload value="#{fileDownloadView.file}"/>
                </p:commandButton>

                <h5 class="mt-0">Basic</h5>
                <p:splitButton value="Save" action="#{buttonView.save}" update="messages"
                               onclick="startDl();"
                               oncomplete="stopDl(); document.getElementById('sample:remoteDownload').click();PF('dlg1').hide();"
                               icon="pi pi-save">
                    <p:menuitem value="Update" action="#{buttonView.update}" update="messages" icon="pi pi-refresh"/>
                    <p:menuitem value="Delete" action="#{buttonView.delete}" ajax="false" icon="pi pi-times"/>
                </p:splitButton>
            </h:form>
        </p:dialog>


    </div>

</h:body>
</html>
```

```java
package org.primefaces.test;

import org.primefaces.model.menu.DefaultMenuItem;
import org.primefaces.model.menu.DefaultMenuModel;
import org.primefaces.model.menu.DefaultSubMenu;
import org.primefaces.model.menu.MenuModel;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.util.concurrent.TimeUnit;

@Named
@RequestScoped
public class ButtonView {

    private MenuModel model;

    @PostConstruct
    public void init() {
        model = new DefaultMenuModel();

        //First submenu
        DefaultMenuItem item = DefaultMenuItem.builder()
                .value("External")
                .url("http://www.primefaces.org")
                .icon("pi pi-home")
                .build();

        DefaultSubMenu firstSubmenu = DefaultSubMenu.builder()
                .label("Dynamic Submenu")
                .addElement(item)
                .build();

        model.getElements().add(firstSubmenu);

        //Second submenu
        item = DefaultMenuItem.builder()
                .id("mniSave")
                .value("Save")
                .icon("pi pi-save")
                .function((i) -> save())
                .update("messages")
                .build();

        DefaultSubMenu secondSubmenu = DefaultSubMenu.builder()
                .label("Dynamic Actions")
                .addElement(item)
                .build();

        item = DefaultMenuItem.builder()
                .value("Delete")
                .icon("pi pi-times")
                .command("#{buttonView.delete}")
                .ajax(false)
                .build();
        secondSubmenu.getElements().add(item);

        model.getElements().add(secondSubmenu);
    }

    public MenuModel getModel() {
        return model;
    }

    public String save() {
        addMessage("Data saved");
        return null;
    }

    public void update() {
        addMessage("Data updated");
    }

    public void delete() {
        addMessage("Data deleted");
    }

    public String sleepAndSave() throws InterruptedException {
        TimeUnit.SECONDS.sleep(1);
        return save();
    }

    public void sleepAndUpdate() throws InterruptedException {
        TimeUnit.SECONDS.sleep(1);
        update();
    }

    public void sleepAndDelete() throws InterruptedException {
        TimeUnit.SECONDS.sleep(1);
        delete();
    }

    public void buttonAction() {
        addMessage("Welcome to PrimeFaces!!");
    }

    public void addMessage(String summary) {
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, summary, null);
        FacesContext.getCurrentInstance().addMessage(null, message);
    }
}

package org.primefaces.test;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;


@Named
@RequestScoped
public class FileDownloadView {

    public StreamedContent getFile() {
        ByteArrayInputStream reportResult = new ByteArrayInputStream("initialString".getBytes());
        return DefaultStreamedContent.builder()
                .stream(() -> reportResult)
                .contentType("plain/text")
                .name("sample.txt")
                .contentEncoding(StandardCharsets.UTF_8.name())
                .build();
    }
}

package org.primefaces.test;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.math.BigDecimal;
import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

import lombok.Data;

@Data
@Named
@ViewScoped
public class TestView implements Serializable {
    
    private String string;
    private Integer integer;
    private BigDecimal decimal;
    private LocalDateTime localDateTime;

    @PostConstruct
    public void init() {
        string = "Welcome to PrimeFaces!!!";
    }

}
```

### Expected behavior

App with CSP should work in the same way as without.

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### Theme

all

### JSF implementation

All

### JSF version

all

### Java version

all

### Browser(s)

Chrome

**Comment by reginakupczak** [comment] 2023-02-06 09:42
Code:
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/10661677/primefaces-test-master.zip)

**Comment by melloware** [comment] 2023-02-06 10:07
Thanks I will take a look

**Comment by melloware** [comment] 2023-02-06 14:04
Don't use `onClick` use `onstart` like `onstart="startDl();"`and it works.

The problem is there is multiple `onClick` events on that button and CSP rewrites them so the second call is being cancelled. The right way to do what you want is using `onstart` with our without CSP.

**Comment by melloware** [comment] 2023-02-06 14:38
@mihaiDumea You want to look at this one its similar to the other one you fixed with multiple `onclick` events registered.

**Comment by melloware** [comment] 2023-02-06 20:56
Ahhh yep and that is why my suggestion to change the above code to `onstart` works and works around the issue.

Yep the code here in CSPResponseWriter does use a Map...

```java
public void writeAttribute(String name, Object value, String property) throws IOException {

        if ("nonce".equalsIgnoreCase(name) && value != null) {
            lastNonce = (String) value;
        }
        else if ("id".equalsIgnoreCase(name) && value != null) {
            lastId = (String) value;
        }

        String lowerCaseName = name.toLowerCase();
        if (lowerCaseName.startsWith("on") && DOM_EVENTS.contains(lowerCaseName)) {
            if (value != null) {
                if (lastEvents == null) {
                    lastEvents = new HashMap<>(1);
                }
                lastEvents.put(name, (String) value);
            }
            return;
        }

        getWrapped().writeAttribute(name, value, property);
    }
```

Not sure an elegant way to fix this one...

**Comment by mihaiDumea** [comment] 2023-02-06 21:43
The problem with attribute duplication when CSP is not enabled, should also be addressed. The component renderer may pass a map argument to the renderPassThruAttributes that contains the values to use.

**Comment by melloware** [comment] 2023-02-08 18:01
Figured it out Splitbutton was not doing the same thing as other buttons and was rendering multiple onClick instead of 1 combined onClick

**Closed as completed** 2023-02-08 20:05 UTC
Labels: :lady_beetle: defect, workaround
