### ISSUE TITLE
SelectOneMenu: Single text box for editing and filtering

### ISSUE THREAD

**Issue by divyareddy12** [primefaces/primefaces#3115] opened 2017-12-28 06:51 UTC
We are looking for a primeface component which can replace rich:select. We tried p:selectOneMenu with editable="true" filter="true" but the filtering option give a new text box under the editable text box. To coincide with rich:select, p:selectOneMenu should have only one text box for both editing and filtering

We raised a ticket in Prime Forum and were asked to raise an enhancement request.
https://forum.primefaces.org/viewtopic.php?f=3&t=53587&p=162879#p162879

**Comment by tandraschko** [comment] 2017-12-28 10:35
As our current approach is by design, it's unlikely that we "just do it". If you really need it, the best way is probably to sponsor it via PrimeFaces PRO.

**Comment by melloware** [comment] 2020-05-25 17:36
Closing this ticket as RichFaces is gone and no one has upvoted this issue in 3 years.  It is extremely unlikely this would be implemented as @tandraschko said this is all by design and how all over PF components do filtering.  If someone feels strongly about it in the future i am happy to reopen the ticket or if someone submits a quality PR.

**Closed as completed by melloware** 2020-05-25 17:36 UTC
Labels: new feature
