### ISSUE TITLE
DataTable don't update paginator when no records found with given filter

### ISSUE THREAD

**Issue by Henny-cz** [primefaces/primefaces#2178] opened 2017-03-14 09:59 UTC
You can test it right on this example
https://www.primefaces.org/showcase/ui/data/datatable/tableState.xhtml

At start, you have 5 pages of records.
In column filter "Id" type for example: "blabla"
... message "No cars found with given criteria" will appear in dataTable

But paginator still shows 1 of 5 pages and you can move to next pages which also breaks filter totally. (filled but not filtered by this value)

(Sorry for my bad english)

**Comment by melloware** [comment] 2017-04-04 11:05
Duplicate of https://github.com/primefaces/primefaces/issues/2217 which was already fixed.   Please close this ticket.

**Closed as completed** 2017-04-04 11:14 UTC
Labels: :lady_beetle: defect

**Comment by Ulziimunkh** [comment] 2017-04-20 09:04
www
