### ISSUE TITLE
SelectOneMenu: Can't select item starting with letter "ö", by typing "ö"

### ISSUE THREAD

**Issue by ogivadon** [primefaces/primefaces#4764] opened 2019-04-28 10:22 UTC
1) Environment
PrimeFaces: 7.0.1
Mojarra: 2.3.9
Payara: 5.191
Ultima Layout: 2.0.0
Chrome: 74.0.3729.108 

2) Expected behavior
By typing the first letter of an existing item, an item could be selected.

3) Actual behavior
Items starting with national characters like ö, ú and others couldn't be selected by typing.
With PrimeFaces 6.2.19 and Ultima Layout 1.1.5 there wasn't any problem with this.

4) Steps to reproduce
Change forms.xhtml page of Ultima Layout sample program release 2.0.0 as follows.

 5) Sample XHTML

                        <p:selectOneMenu id="console" value="#{selectOneMenuView.console}" style="margin-bottom:10px;">
                            <f:selectItem itemLabel="Select One" itemValue="" />
                            <f:selectItem itemLabel="úbox One" itemValue="úbox One" />
                            <f:selectItem itemLabel="öbox One" itemValue="öbox One" />
                            <f:selectItem itemLabel="Öbox One" itemValue="Öbox One" />
                            <f:selectItem itemLabel="Xbox One" itemValue="Xbox One" />
                            <f:selectItem itemLabel="PS4" itemValue="PS4" />
                            <f:selectItem itemLabel="Wii U" itemValue="Wii U" />
                        </p:selectOneMenu>
                        

 6) Sample bean
There isn't any change in sample program.

**Comment by melloware** [comment] 2019-04-28 12:18
I will investigate.

**Comment by melloware** [comment] 2019-04-28 15:06
OK I verified it is boken in 7.0. and fixed in 7.1-SNAPSHOT due to this fix.

https://github.com/primefaces/primefaces/issues/4682

@mertsincan can you merge this into Elite 7.0.2?

Here is my reproducer: 
[pf-4764.zip](https://github.com/primefaces/primefaces/files/3125118/pf-4764.zip)

**Closed as completed** 2019-04-28 18:35 UTC
Labels: :lady_beetle: defect, 6.2.20, 7.0.2

**Comment by ogivadon** [comment] 2019-05-14 08:18
Hi Melloware,

I’ve just tested with PrimeFaces 7.0.2.
It works fine!

Thanks
