### ISSUE TITLE
DataTable: comma-separated keys in SelectableDataModel#getRowData(String rowKey)

### ISSUE THREAD

**Issue by andrewtobilko** [primefaces/primefaces#5946] opened 2020-05-22 17:02 UTC
The method 

    T getRowData(String rowKey);

defined in `org.primefaces.model.SelectableDataModel<T>` is not clearly defined/documented. `rowKey` could be a joined string of row keys, not a single one. 

**Environment:**
 - PF Version: _8.0_

**To Reproduce**

1. Create a single selection lazy table.
2. `PF('table').selectRow(1, true);` selects the row not firing an ajax
3. `PF('table').selectRow(1, false);` fires an ajax and `"<rowKey1>,<rowKey2>"` is coming to the method.

**Expected behavior**

I expected the parameter `rowKey` always refers to one row key, and the method works with one row at a time.

PS. It's not a new feature. It's rather a defect or my misunderstanding :)

**Comment by melloware** [comment] 2020-05-22 18:10
So what is the exact problem you are having?  You weren't expecting it to be comma separated and you have a comma in your key?

**Comment by andrewtobilko** [comment] 2020-05-22 18:52
@melloware yes, exactly. Is it by design?

**Comment by melloware** [comment] 2020-05-22 18:57
Yes it looks like by design, maybe comma wassn't the best choice maybe it should have been "~" or ";"

**Comment by tandraschko** [comment] 2020-05-22 18:57
Not sure, we have to debug.

At least we can improve it by adding a getRowsData(String[] rowKeys) and per default loop over all and call getRowData.

**Comment by Rapster** [comment] 2020-05-22 19:11
I had a try, and can't reproduce your problem.
> PF('table').selectRow(1, false); fires an ajax and "<rowKey1>,<rowKey2>" is coming to the method.

What exactly do you mean by "rowKey1,rowKey2" coming to the method?

> I expected the parameter rowKey always refers to one row key, and the method works with one row at a time.

This is correct, and that's the case

**Comment by melloware** [comment] 2020-05-23 16:51
I think he is saying if you go to the Showcase and do the following:
```javascript
PrimeFaces.widgets.widget_form_eventsDT.selectRow(1, true);
PrimeFaces.widgets.widget_form_eventsDT.selectRow(2, false);
```
In the network traffic you will see...
```
form:eventsDT_selection: 582d8134,a0718113
```
Then in SelectionFeature.decodeMultipleSelection:
```java
String[] rowKeys = selection.split(",");
                for (int i = 0; i < rowKeys.length; i++) {
                    Object rowData = table.getRowData(rowKeys[i]);

                    if (rowData != null) {
                        selectionList.add(rowData);
                    }
                }
```

**Comment by Rapster** [comment] 2020-05-23 18:05
ok, so is there a problem here? I'm confused...

**Comment by tandraschko** [comment] 2020-05-23 18:21
Yep
looks like getRowData will only receive one key? so everything is ok...

**Comment by Rapster** [comment] 2020-05-24 09:57
Should we close it then?

**Comment by melloware** [comment] 2020-05-24 11:52
I think the user's issue is that because its split by comma `selection.split(",");` no where in the documentaiton does it say NOT to use a comma in your rowKey.  His rowKeys have comma's in them so when it goes to split its splitting the rowKey's incorrectly.
So either we..
A) update the documentation for `rowKey` saying do not use a comma in your rowKey
B) Change that from a comma to a more odd character like "~" separate.

**Comment by tandraschko** [comment] 2020-05-24 12:10
he clearly says "\<rowKey1\>,\<rowKey2\>"

**Comment by melloware** [comment] 2020-05-24 12:12
Huh yeah you are right. @andrewtobilko what exactly is your issue?

**Comment by tandraschko** [comment] 2020-05-24 12:31
@andrewtobilko please provide a cloned primefaces-test project to replicate your issue.

**Comment by melloware** [comment] 2020-05-26 17:40
Will close for now. @andrewtobilko if you come up with a reproducible test case I will re-open it.

**Closed as completed by melloware** 2020-05-26 17:40 UTC
Labels: needs further work
