### ISSUE TITLE
UIRepeat: NoSuchMethodError in Calendar

### ISSUE THREAD

**Issue by ohlsen3000** [primefaces/primefaces#5911] opened 2020-05-18 07:13 UTC
**Describe the defect**
Using a Calendear with a dateSelect behaviour within a UIRepeat causes a NoSuchMethodError when date is selected. It is caused by the attempt to get the FacesContext from the FacesEvent in UIRepeat::broadcast.

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _MyFaces 2.2.10_
 - Affected browsers: _ALL_

**To Reproduce**
- Use Calendar within UIRepeat
- Add a dateSelect Event to that calendar
- Change the date of that calendar

**Expected behavior**
Ajax Event is processed without exception

**Example XHTML**
```xml
<ui:repeat value="#{myBean.items}" var="item">
	<p:calendar value=#{item.startDate} id="startDate">
		<p:ajax event="dateSelect" oncomplete="console.log('date changed')" update="#{p:resolveFirstComponentWithId('endDate', view).clientId}"/>
	</p:calendar>
	<p:calendar value=#{item.endDate} id="endDate"/>
</ui:repeat>
```

**Comment by tandraschko** [comment] 2020-05-18 07:32
I think you use p:repeat here?
Otherwise, please provide the stacktrace. It should be already fixed in trunk.

**Comment by ohlsen3000** [comment] 2020-05-18 08:38
Hi, both, the facelets and the prime UIRepeat show the same error:
`java.lang.NoSuchMethodError: javax.faces.event.FacesEvent.getFacesContext()Ljavax/faces/context/FacesContext;
	at org.primefaces.component.repeat.UIRepeat.broadcast(UIRepeat.java:916)
	at javax.faces.component.UIViewRoot._broadcastAll(UIViewRoot.java:1174)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:354)
	at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1660)
	at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:911)
	at org.apache.myfaces.lifecycle.ProcessValidationsExecutor.execute(ProcessValidationsExecutor.java:38)
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:196)
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:143)
	at org.apache.deltaspike.jsf.impl.listener.request.DeltaSpikeLifecycleWrapper.execute(DeltaSpikeLifecycleWrapper.java:89)
	at javax.faces.lifecycle.LifecycleWrapper.execute(LifecycleWrapper.java:46)`

**Comment by tandraschko** [comment] 2020-05-18 08:40
Please post the stacktrace with ui:repeat and provide the java bean. otherwise the issue is invalid as we can't replicate it.

NOTE: p:repeat is a hacky copy of Mojarra and should never be used on MyFaces.
If your exception is in MyFaces, we cant even fit ix here.

**Comment by ohlsen3000** [comment] 2020-05-18 08:43
Sorry, my bad. ui:repeat works ok, it was a wrapping p:repeat that caused the problem. Thanks for the hint on that one.

**Closed as completed** 2020-05-18 08:45 UTC
Labels: :lady_beetle: defect, Resolution: Duplicate

**Comment by tandraschko** [comment] 2020-05-18 08:46
Duplicate of: https://github.com/primefaces/primefaces/issues/5661

Please use the search next time before creating a issue
