### ISSUE TITLE
File-upload with multiple files fails in Primefaces 5.1

### ISSUE THREAD

**Issue by gatschet** [primefaces/primefaces#356] opened 2015-05-28 11:00 UTC
I try to do a file upload in primefaces with PF 5.1 and OmniFaces version 1.7.

My .xhtml code:

```
<h:form id="fileImportForm" styleClass="prepend-top"
    prependId="false">

    <div style='margin-bottom:10px'>
        <h:outputLabel value="#{msg.file_import_msg}"/>
    </div>
    <p:fileUpload id="fileImport" fileUploadListener="#{fileImport.handleFileUpload}"   
        mode="advanced"  
        update="messages"   
        multiple="true"
        label="#{msg.file_import_choose_label}" 
        uploadLabel="#{msg.file_import_upload_label}" 
        cancelLabel="#{msg.file_import_cancel_label}"       
    />  
    <p:growl id="messages" showDetail="true"/>  

</h:form>
```

My backing bean:

```
package test.boundary;

import javax.inject.Named;
import org.primefaces.event.FileUploadEvent;
import com.haslerrail.aura.common.exception.SystemException;

/**
 * BackingBean for <code>fileImport.xhtml</code> page.
 *
 */
@Named
public class FileImport implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    public void handleFileUpload(final FileUploadEvent event) throws SystemException, InterruptedException {

        if (event == null || event.getFile() == null || event.getFile().getSize() == 0) {
            System.out.println("No file");

        }
        System.out.println(event.getFile().getFileName());
        Thread.sleep(500); // wait a little to force the exception!
    }
}
```

The problem is, when my handleFileUpload function takes a little bit longer to parse the uploaded file (Thread.sleep(500), it throws an exception! The exception only occurs when I'm uploading more than one file at the same time.

The exception:

```
09:47:33,171 WARN  [org.jboss.weld.Conversation] WELD-000315 Failed to acquire conversation lock in 1,000 for Conversation with id: 1
09:47:33,180 SEVERE [org.omnifaces.exceptionhandler.FullAjaxExceptionHandler] FullAjaxExceptionHandler: An exception occurred during processing JSF ajax request. Error page '/pages/error/error.xhtml' will be shown.: org.jboss.weld.context.BusyConversationException: WELD-000322 Conversation lock timed out: 1
    at org.jboss.weld.context.AbstractConversationContext.activate(AbstractConversationContext.java:215) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
    at org.jboss.weld.jsf.WeldPhaseListener.activateConversations(WeldPhaseListener.java:108) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
    at org.jboss.weld.jsf.WeldPhaseListener.beforePhase(WeldPhaseListener.java:85) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
    at com.sun.faces.lifecycle.Phase.handleBeforePhase(Phase.java:228) [jsf-impl-2.1.7-jbossorg-2.jar:]
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:99) [jsf-impl-2.1.7-jbossorg-2.jar:]
    at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:116) [jsf-impl-2.1.7-jbossorg-2.jar:]
    at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118) [jsf-impl-2.1.7-jbossorg-2.jar:]
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593) [jboss-jsf-api_2.1_spec-2.0.1.Final.jar:2.0.1.Final]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
    at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:102) [primefaces-5.1.jar:5.1]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
    at org.jboss.weld.servlet.ConversationPropagationFilter.doFilter(ConversationPropagationFilter.java:62) [weld-core-1.1.5.AS71.Final.jar:2012-02-10 15:31]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
    at org.omnifaces.filter.CacheControlFilter.doFilter(CacheControlFilter.java:226) [omnifaces-1.7.jar:1.7]
    at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:77) [omnifaces-1.7.jar:1.7]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:489) [jbossweb-7.0.13.Final.jar:]
    at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.1.1.Final.jar:7.1.1.Final]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671) [jbossweb-7.0.13.Final.jar:]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930) [jbossweb-7.0.13.Final.jar:]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_75]  
```

For me it looks like an error in PF 5.1! Any other ideas?

**Comment by gatschet** [comment] 2015-05-28 11:16
In my opinion it's not allowed to upload every file in the fileupload in a own thread! I'm using a session scoped bean as backing bean. 
For every file a new thread will be started. If i wan't to store every file in a list this is not possible because i have as many list as threads and not one session list as expected...

**Comment by tandraschko** [comment] 2015-05-28 11:37
Just for clarification:

1) a new thread is not started by PF. We just use 1 http request per 1 file to upload. Your container propably starts multiple threads. Thats by design and we won't change this.
2) There already is PF 5.2
3) The exception is from WELD because it somehow tries to the lock the conversation. As the files will be uploaded in the same time, the second request will propably try to lock the conversation which is already locked from the first request.

I would try to better implement your upload mechanism and prevent conversations in this upload form. You have to check this.

**Comment by gatschet** [comment] 2015-05-28 11:48
Hi tandraschko

Thanks for your comment. I'm using JBosss as 7.1 and every file commes in a own thread. Session variables will not shared between them.

Because of this implementation it's not possible to handle all files of one upload request in the same way. (For example it's not possible to store all files with a same prefix from uploading date!)

How could i better implement my upload mechanism?

**Comment by tandraschko** [comment] 2015-05-28 11:54
To stop conversation stuff in this request, you need to put this in your form:
 <input type="hidden" name="nocid" value="true" />
However, you should not and can't use anymore conversation scoped stuff in this request.

// Session variables will not shared between them.
They must be shared! Otherwise something is wrong in your environment.

// Because of this implementation it's not possible to handle all files of one upload request in the same way. 
Thats up to your application. I would store all files somwhere and process them all e.g. in the actionListener.

I will close this as this isn't a PrimeFaces issue. Just need to be aware that each file will upload in an own request.

**Closed as completed by tandraschko** 2015-05-28 11:54 UTC

**Comment by gatschet** [comment] 2015-06-01 11:35
Hi tandraschko

I disagree with you! Every files comes in own request and for me this is a bug in primefaces 5.1 because there is no way to handle all files in the same way...

See the answer from Vsevolod Golovanov on http://stackoverflow.com/questions/30500731/file-upload-with-multiple-files-fails-in-primefaces-5-1/ how to work arround this issue...

**Comment by VsevolodGolovanov** [comment] 2015-06-04 12:50
@tandraschko, I consider this a PrimeFaces issue, since JSF explicitly requires client to queue requests. JSF's server-side implementation is not required to properly handle multiple requests to the same view simultaneously. And it doesn't (Mojarra at least).

**Comment by tandraschko** [comment] 2015-06-04 19:34
but it will be still uploaded in own threads ;)
Feel free to create a feature request to allow to queue the fileupload requests. It's not directly to this issue but it would also fix your problem.

**Comment by VsevolodGolovanov** [comment] 2015-06-05 14:39
> but it will be still uploaded in own threads

As opposed to what? Multiple threads accessing the same data without proper synchronization - this is exactly the problem. Created issue #403.
