### ISSUE TITLE
Exporter: XML export does not work with column's head text in Chinese 

### ISSUE THREAD

**Issue by Mararsh** [primefaces/primefaces#3588] opened 2018-04-16 05:11 UTC
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: GlassFish 4.1.2
- Affected browsers: Firefox

## 2) Expected behavior
XML dataExporter exports Chinese data when column head texts are in Chinese in pages.

## 3) Actual behavior
XML dataExporter fails to generate the file due to column head text in Chinese

## 4) Steps to reproduce
Create a p:dataTable with column head text containing Chinese.

## 5) Sample XHTML
“headerText” in “p:column” will be replaces as Chinese "报告时间"
```
<p:column style="width: 130px"
		  sortBy="#{item.reportTime}"
		  headerText="#{messages.ReportTime}"
		  filterBy="#{item.reportTime}" filterMatchMode="contains">
	<h:outputText value="#{item.reportTime}">
		<f:convertDateTime pattern="yyyy-MM-dd HH:mm:ss"  timeZone="#{localeBean.timeZone}" locale="#{localeBean.language}" />
	</h:outputText>
</p:column>
....

<p:commandLink value="xml" ajax="false"
	 actionListener="#{userFeedbackBean.exporter.checkExportFilename2('TUserFeedback')}">
	<p:dataExporter type="xml"  encoding="UTF-8"
					target=":TUserFeedbackListForm:datalist"
					pageOnly="#{userFeedbackBean.exporter.exportContent eq 'page'}"
					selectionOnly="#{userFeedbackBean.exporter.exportContent eq 'selected'}"
					fileName="#{userFeedbackBean.exporter.exportFilename}"/>
</p:commandLink>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
```

## 6) Sample bean
Not necessary

## 7) Root Reason
In file "XMLExporter.java"
[XMLExporter.java](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/export/XMLExporter.java)

```
    protected String getColumnTag(UIColumn column) {
        String headerText = column.getHeaderText();
        UIComponent facet = column.getFacet("header");
        String columnTag;

        if (headerText != null) {
            columnTag = headerText.toLowerCase();
        }
        else if (facet != null) {
            columnTag = exportValue(FacesContext.getCurrentInstance(), facet).toLowerCase();
        }
        else {
            throw new FacesException("No suitable xml tag found for " + column);
        }

        // #459 return columnTag.replaceAll(" ", "_");
        return XMLUtils.escapeTag(columnTag);
}
```

The "Tag" of XML file are fetched from "headerText " of data tables in xhtml, so it definitely fails to generate XML file with Chinese tags.

## 8) My solution
I customized data exporter to make it use internal defined columns to output columns' names and values.
Following is the basical data exporter which implements XML exporter and  Json exporter:
```
public class DataExporter implements Serializable {
...
    protected List<String> columns = null;
...
    public ByteArrayOutputStream exportXmlData(List<Object> data) {
        if (data == null) {
            return null;
        }
        try {
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            DocumentBuilder db = dbf.newDocumentBuilder();
            org.w3c.dom.Document document = db.newDocument();
            Element root = document.createElement("root");
            document.appendChild(root);

            if (description != null) {
                Element desNode = document.createElement("description");
                desNode.setTextContent(description);
                root.appendChild(desNode);
            }

            Element dataNode = document.createElement("data");
            root.appendChild(dataNode);

            Element rowNode, valueNode;
            for (Object row : data) {
                rowNode = document.createElement("row");
                dataNode.appendChild(rowNode);
                for (String column : columns) {
                    valueNode = document.createElement(column);
                    valueNode.setTextContent(getColumnValue(row, column));
                    rowNode.appendChild(valueNode);
                }
            }

            TransformerFactory tf = TransformerFactory.newInstance();
            Transformer t = tf.newTransformer();
            t.setOutputProperty("encoding", "UTF-8");
            t.setOutputProperty(OutputKeys.INDENT, "yes");
            t.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "4");
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            t.transform(new DOMSource(document), new StreamResult(baos));

            return baos;
        } catch (Exception e) {
//            logger.debug(e.toString());
            return null;
        }
    }

    public ByteArrayOutputStream exportJsonData(List<Object> data) {
        if (data == null) {
            return null;
        }
        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            try (JsonGenerator gen = Json.createGenerator(baos)) {
                gen.writeStartObject();
                if (description != null) {
                    gen.write("description", description);
                }
                gen.writeStartArray("data");

                for (Object row : data) {
                    gen.writeStartObject();
                    for (String column : columns) {
                        String value = getColumnValue(row, column);
                        if (value != null && !value.isEmpty()) {
                            gen.write(column, value);
                        }
                    }
                    gen.writeEnd();
                }
                gen.writeEnd().writeEnd();
            }

            return baos;
        } catch (Exception e) {
            logger.debug(e.toString());
            return null;
        }
    }

...
}
```

Following is the extended data export for a specific type of data:
```
public class LocationExporter extends DataExporter {

    public LocationExporter() {
        this.columns = Arrays.asList("dataid", "Terminal", "x", "y", "z", "direction", "speed", "recordTime");
        float[] w = {10f, 23f, 10f, 10f, 10f, 7f, 10f, 20f};
        this.widths = w;
    }

    @Override
    public String getColumnValue(Object data, String column) {
        try {
            TLocation location = (TLocation) data;
            switch (column) {
                case "dataid":
                    return location.getDataid() + "";
                case "Terminal":
                    return location.getTerminalid().getRegisterNumber();
                case "x":
                    return ValueTools.roundDouble(location.getX()) + "";
                case "y":
                    return ValueTools.roundDouble(location.getY()) + "";
                case "z":
                    if (location.getZ() != null) {
                        return ValueTools.roundDouble(location.getZ()) + "";
                    } else {
                        return "";
                    }
                case "direction":
                    if (location.getDirection() != null) {
                        return location.getDirection() + "";
                    } else {
                        return "";
                    }
                case "speed":
                    if (location.getSpeed() != null) {
                        return ValueTools.roundDouble(location.getSpeed()) + "";
                    } else {
                        return "";
                    }
                case "recordTime":
                    return DateTools.datetime2String(location.getRecordTime());
                default:
                    return "";
            }
        } catch (Exception e) {
            return "";
        }
    }
}
```

## 9) Possible general solution
Is it possible to add some options or parameters to allow developers to define the tags in exported XML files?

**Comment by cnsgithub** [comment] 2018-04-25 05:34
@Mararsh Next time, please consider [MCVE](https://stackoverflow.com/help/mcve). Then people will have a look at your issues more likely.

Minimal reproducible example - do it in showcase dataexporter/basic.xhtml:
```xml
            <p:dataTable id="tbl" var="car" value="#{dataExporterView.cars}" paginator="true" paginatorTemplate="{Exporters}">
                <f:facet name="{Exporters}">
                    <div style="float:right">
                        <h:commandLink>
                            <p:graphicImage name="/demo/images/xml.png" width="24"/>
                            <p:dataExporter type="xml" target="tbl" fileName="cars" />
                        </h:commandLink>
                    </div>
                </f:facet>
                <p:column headerText="报告时间">
                    <h:outputText value="#{car.id}" />
                </p:column>
            </p:dataTable>
```

@tandraschko As non-English letters are allowed in XML element names (see [W3C XML Elements](https://www.w3schools.com/xml/xml_elements.asp)) and the export is working without any failures I would drop the defect and rather add the enhancement label. 
Although those Chinese tags are for sure very uncommon in practice, they are syntactically correct. You may verify that on [W3C XML Validator](https://www.w3schools.com/xml/xml_validator.asp).
```xml
<?xml version="1.0"?>
<tbl>
	<car>
		<报告时间>c2fa3a2a</报告时间>
	</car>
</tbl>

```

**Comment by cnsgithub** [comment] 2018-04-25 06:05
Some notes:
1. You could also use `p:column exportFunction` to do some locale-specific stuff.
2. What do you think about adding an attribute `exportAs` to `p:column` (`String`) and `p:columns` (`ExportModel`)? Or even `exportHeaderText`?

**Comment by Mararsh** [comment] 2018-05-15 03:10
Yes, you are right. Chinese is permitted as the XML tag, and I did not realize this. Sorry for the mistake!
I will check why XML exporter failed in my env and update later.

**Comment by Mararsh** [comment] 2018-05-25 02:28
@cnsgithub  Your notes are correct: Errors may happen if `p:column exportFunction` is not used. 
Example, following returned when no stuff of locale defined in p:column:

`
警告:   No suitable xml tag found for org.primefaces.component.column.Column@5055f965
javax.faces.FacesException: No suitable xml tag found for org.primefaces.component.column.Column@5055f965
	at org.primefaces.component.export.XMLExporter.getColumnTag(XMLExporter.java:115)
	at org.primefaces.component.export.XMLExporter.exportCells(XMLExporter.java:92)
	at org.primefaces.component.export.Exporter.exportRow(Exporter.java:265)
	at org.primefaces.component.export.Exporter.exportAll(Exporter.java:250)
	at org.primefaces.component.export.XMLExporter.export(XMLExporter.java:52)
	at org.primefaces.component.export.DataExporter.processAction(DataExporter.java:134)
	at javax.faces.event.ActionEvent.processListener(ActionEvent.java:88)
	at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:814)
	at javax.faces.component.UICommand.broadcast(UICommand.java:300)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at com.qxsk9.filters.AuthorizationFilter.doFilter(AuthorizationFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at com.qxsk9.filters.AuthenticationFilter.doFilter(AuthenticationFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
	at java.lang.Thread.run(Thread.java:748)
` 

I believe your second note will be helpful for developers to define the XML tag in direct way.

Thanks for your information!

**Comment by melloware** [comment] 2019-11-11 17:39
Closing this issue as it has been solved with the above code. and the suggestion #2 above is a duplicate of https://github.com/primefaces/primefaces/issues/2238

**Closed as completed by melloware** 2019-11-11 17:39 UTC
Labels: :lady_beetle: defect
