### ISSUE TITLE
Schedule: Invisible Unless Another PF Component Is Present

### ISSUE THREAD

**Issue by mossaab0** [primefaces/primefaces#6411] opened 2020-10-13 14:06 UTC
**Describe the defect**
The following page renders fine. But when I remove `<p:button/>`, the schedule isn't shown anymore.

```
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <f:view>
        <h:head>
        </h:head>
        <h:body>
            <h:form>
                <p:button/>
                <p:schedule value="#{serviceController.schedule}"/>
            </h:form>
        </h:body>
    </f:view>
</html>
```

**Environment:**
 - PF Version: 8.0
 - JSF + version: joinfaces 4.3.0 (primefaces-spring-boot-starter, mojarra-spring-boot-starter).
 - Affected browsers: ALL

**Expected behavior**
The schedule should appear even when there is no `<p:button/>`.

**Comment by melloware** [comment] 2020-10-13 14:09
Duplicate of https://github.com/primefaces/primefaces/issues/6157

Already fixed in 8.04 and 9.0

**Comment by tandraschko** [comment] 2020-10-13 14:09
Please use the search next time before creating a new issue.

**Closed as completed by melloware** 2020-10-13 14:09 UTC
Labels: Resolution: Duplicate, 8.0.4

**Comment by mossaab0** [comment] 2020-10-13 14:12
Thanks @melloware!
@tandraschko I did search. But I didn't find it (As you can see, the body of the two issues are widely different).
