### ISSUE TITLE
Layout: units get overlaped after update="@all"

### ISSUE THREAD

**Issue by robertfdx** [primefaces/primefaces#3021] opened 2017-11-29 10:32 UTC
## 1) Environment
- PrimeFaces version: v6.1
- Affected browsers: only Chrome v60 to the latest version

## 2) Expected behavior
`ui-layout-unit` should have `auto` width and height so it won't get overlaped by the next `div` or primefaces component
Unfortunately I can't force that with CSS and I need to update every component.
## 3) Actual behavior
After pressing the load button, `ui-layout-unit` gets overlaped randomly (at least apparently).

## 4) Steps to reproduce
https://github.com/robertfdx/issue-ajax-primefaces

## 5) Sample XHTML
```xhtml
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>
<body>
	<p:layout>
		<p:layoutUnit style="border: 5px dotted red" position="center">
			<p:dataTable id="updateMe" var="car" value="#{mb.cars}">
				<p:column headerText="Id">
					<h:outputText value="#{car.id}" />
				</p:column>

				<p:column headerText="Year">
					<h:outputText value="#{car.year}" />
				</p:column>

				<p:column headerText="Brand">
					<h:outputText value="#{car.brand}" />
				</p:column>

				<p:column headerText="Color">
					<h:outputText value="#{car.color}" />
				</p:column>
			</p:dataTable>
			<h:form>
				<p:commandButton id="loadButton" value="Load"
					update="@all"/>
			</h:form>
			<div class="test-wrapper" style="height: 100px; border: 1px solid red; background-color: beige"></div>
		</p:layoutUnit>
	</p:layout>
</body>

</html>
```

**Comment by melloware** [comment] 2017-11-29 13:10
Is "@all" really what you want?  I have never in my use cases ever had the need to update everything have you tried giving your layout an id="" and just updating that does it have the same effect?

**Comment by robertfdx** [comment] 2017-11-29 13:25
Unfortunately, yes, I need to use `@all`. 
I tried to give an id to `p:layout` and it does nothing and if I give an id to the `p:layoutUnit`... it will be hidden because of: `.ui-layout-unit { visibility: hidden;}` from layout.css

**Comment by melloware** [comment] 2017-11-29 13:28
Understood.  How about for a quick expirement can you wrap your layout in a p:outputPanel with an ID and then update="IdOfOutputPanel".  OutputPanel gets rendered as a DIV and is update-able.

**Comment by robertfdx** [comment] 2017-11-29 13:39
That seems to be working just fine, but it feels like a workaround.

**Comment by melloware** [comment] 2017-11-29 13:44
To me it is not a workaround.  update =@all is extremely expensive as it tries to replace the entire DOM almost as if you did a FULL page refresh.  Your update="" should be targeted to only return to the components on the screen you want to repaint and some JS components like layout.js can behave strangely when you try and replace and redraw the whole DOM underneath of it.

So I would definitely say this is not a workaround but instead you reduced your network traffic of your AJAX update by targeting your update.  Like I said I have been doing this for 6 years and I have NEVER used "@all".

**Comment by robertfdx** [comment] 2017-11-29 13:56
I can understand that and I agree with you. Well, because it's not my code. But I can't just go to production and add outputPanels all over the app to fix that.
Also it's strange that it works just fine in other browsers and old versions of Chrome.

**Comment by melloware** [comment] 2017-11-29 14:01
It could be a problem with the core layout.js/css code that now Chrome 60 is interpreting some CSS rule differently that is wasn't before in previous Chrome's.   So my guess is this is not a PF issue but something Chrome is now doing and interpreting the core layout.js/css code.  

If you want to analyze further and provide a patch that you think might fix it while not breaking other browsers that would be great too!

**Comment by kukel** [comment] 2017-12-11 17:10
Personally I would not try to fix this issue. If you think you need `@all` in an application, refactor it to a non ajax call  or do a PRG from the bean and use a viewAccessScoped bean

**Comment by leandrodmartini** [comment] 2018-01-10 06:16
I'm using Primefaces 6.0 and facing the same issue. But it's not related to the update=@all flag. I'm using a p:commandButton to make an implicit navigation to another page. I'm using the same template in both (original and target) pages. When I click in my button and navigate to the next page my northy layoutunit gets missed with length.
My webpage is furadeirasoftware.com and I'm not facing the same problem when using Firefox.

**Comment by melloware** [comment] 2018-01-10 12:13
@leandrodmartini Can you create a small reproducible test case for us to reproduce?   Use the test project to get started...  Clone this project:  https://github.com/primefaces/primefaces-test

**Comment by leandrodmartini** [comment] 2018-01-11 03:27
@melloware I created a test case here: https://github.com/leandrodmartini/primefaces-test/
It's pretty similar to the @robertfdx one.
I'm facing the same problem without the update=@ALL. It happens if I use an implicit navigation through commandbutton. Observe the north layoutunit increasing length when you navigate to the target page.
Let me know if any other information is needed.

**Comment by melloware** [comment] 2018-01-11 11:26
Thank you for the test case.  Let me investigate and see if this is a PF bug or a Layout JS bug.

**Comment by leandrodmartini** [comment] 2018-01-18 15:16
Maybe this is related to what I found in this past topic: https://forum.primefaces.org/viewtopic.php?p=95589

**Comment by kukel** [comment] 2018-01-18 16:19
Easy to check. Does it not fail in other browsers?

**Comment by leandrodmartini** [comment] 2018-01-19 02:44
I'm not facing the same problem when using Firefox.
57.0.4 (64-bit) Mozilla Firefox for Ubuntu

**Comment by melloware** [comment] 2018-01-25 12:41
Has anyone tried this using PF 6.2RC1?  I updated the layout.js to the latest Jquery version with many fixes in it.

**Comment by melloware** [comment] 2018-03-12 20:58
Agreed this seems isolated to Chrome.

[primefaces-layout.zip](https://github.com/primefaces/primefaces/files/1804547/primefaces-layout.zip)

**Comment by melloware** [comment] 2018-03-13 13:56
For those of you that use Layout I got this note from OptimusPrime...

> Cagatay Civici added a comment - 13/Mar/18 8:14 AM
> Note that Layout component is deprecated in 6.2.x in favor of css driven modern layouts.

So it looks like Layout will be removed in 6.3 so you may want to start switching your projects over to using PrimeFaces Extensions version of Layout which will remain supported.

**Comment by leandrodmartini** [comment] 2018-04-09 03:58
Thank you Melloware for the investigation. I will consider changing my website layout.

**Comment by tandraschko** [comment] 2019-07-24 12:18
Layout is deprecated, i will close it as won't fix

**Closed as completed** 2019-07-24 12:23 UTC
Labels: Resolution:  Wontfix
