### ISSUE TITLE
Tabview: add/remove tabs without performing update

### ISSUE THREAD

**Issue by anabelenpz** [primefaces/primefaces#1541] opened 2016-06-20 07:55 UTC
It is not possible to update the state of one unique tab without performing update to the whole tabview.
This happens, for example, when I try to make conditional the value for attributes 'rendered' or 'disabled' due to an event triggered by other components in the view, like a booleancheckbox or something else.

Some references I have found in forums are these:
[http://forum.primefaces.org/viewtopic.php?f=3&t=30091](url)

I think this feature is too necessary to be implemented.

**Comment by fabiozanardi7** [comment] 2016-07-19 12:21
I agree

**Comment by Maikel-Nait** [comment] 2017-02-13 06:25
I'm also in need of this feature, and definitely we are not the only ones...

Several references in the forum are also made regarding this problem:
[http://forum.primefaces.org/viewtopic.php?f=3&t=46882&p=145699#p145699](http://forum.primefaces.org/viewtopic.php?f=3&t=46882&p=145699#p145699)
[http://forum.primefaces.org/viewtopic.php?f=3&t=45702&p=142962&hilit=add+tab#p142962](http://forum.primefaces.org/viewtopic.php?f=3&t=45702&p=142962&hilit=add+tab#p142962)

Someone found a way to achieve it using plain javascript, and somehow this is what we need!!
[http://forum.primefaces.org/viewtopic.php?f=3&t=47910](http://forum.primefaces.org/viewtopic.php?f=3&t=47910)

**Comment by tandraschko** [comment] 2021-01-04 11:50
This is currently completely by design.
TabViewRender renders the tab, there is no TabRenderer. Therfore it can never work without refactoring the whole component.

Even if we would have a TabRenderer, you cant update a component which isnt intially rendered and you still would need update the TabView.

I will close this for now.
I also aligned the docs a bit today for #5960

However, we could add JS helper methods for adding/removing new tabs int he future. WDYT @melloware?

**Closed as completed by tandraschko** 2021-01-04 11:50 UTC
Labels: Resolution:  Wontfix, new feature

**Comment by melloware** [comment] 2021-01-04 12:44
@tandraschko I we could think about adding JS methods for add and remove tab but i would think AddTab would have to be AJAX so it can notify the backend about the new Tab.   If more people ask we can create a ticket but I know people on the forums have asked they want to add a tab WITHOUT AJAX which to me doesn't seem possible or not without a lot of refactoring.

**Comment by tandraschko** [comment] 2021-01-04 12:45
I think we could allow something like:
addTab('title', 'content as string or jqueryelement'); whis woudlnt require AJAX but would be lost after update
