### ISSUE TITLE
DataTable: support globalFilter outside of DataTable

### ISSUE THREAD

**Issue by riyadomf** [primefaces/primefaces#12797] opened 2024-10-28 13:54 UTC
### Problem Summary
When using `globalFilter` with a `dataTable` and applying pagination, the `FilterMeta` for the `globalFilter` is reset. However, custom column-specific `FilterMeta` persist correctly across pagination. This issue causes the `globalFilter` value to be lost when navigating between pages, resulting in inconsistent filtering behavior.

### Code Context
The `globalFilter` is set up outside of the `dataTable` in an accordion and applied through the backing bean’s `onFilter` method. In this method, a `FilterMeta` instance is created with `MatchMode.CONTAINS` and inserted into the `filterBy` map. Additionally, the column-specific `FilterMeta` instances are applied simultaneously.
I'm populating the filterBy with `globalFilterMeta` and `customFilterMeta`. 
While paginating, `customFilterMeta` persists but `globalFilterMeta` resets.
* globalFilterMeta created with `FilterMeta.of()`
* customFilterMeta created with `FilterMeta.builder()` e.g.
  
I need the `globalFilter` because I need to search on multiple field of an entity

**`onFilter` method** on `ViewScoped` backing bean:
```java
public void onFilter(FilterEvent event) {
     myCustomFilterMetaMap =  Map.ofEntries(
                entry("parentOfficeLayer", FilterMeta.builder().field("parentOfficeLayer").filterValue(parentOfficeLayerFilterValue).matchMode(MatchMode.EQUALS).build());
     event.getFilterBy().putAll(myCustomColumnFilterMetaMap);
                
    if (globalFilterValue != null) {
        FilterMeta globalFilterMeta = FilterMeta.of(globalFilterValue, null);
        globalFilterMeta.setMatchMode(MatchMode.CONTAINS);
        event.getFilterBy.put(FilterMeta.GLOBAL_FILTER_KEY, globalFilterMeta);
    }
}
```

**`DataTable`:**
```java
            <h:form id="officeLayerForm">
                <!-- Accordion panel for filter section -->
                <p:accordionPanel widgetVar="basic" id="filterAccordionPanel">
                    <p:tab title="#{message['filter']}">
                        <p:outputPanel class="grid formgrid ui-fluid row-gap-3">
                            <!-- custom Global filter -->
                            <div class="field lg:col-3 col-12">
                                <p:outputLabel for="@next" styleClass="font-normal text-lg"
                                               value="#{message['officeLayer.name']}"/>
                                <p:inputText value="#{officeLayerView.globalFilterValue}"
                                             placeholder="#{message['officeLayer.nameAndNameLocale.placeholder']}"/>
                            </div>

                            <!-- Filter based on column -->
                            <div class="field lg:col-3 col-12">
                                <p:outputLabel for="@next" styleClass="font-normal text-lg"
                                               value="#{message['officeLayer.parent']}"/>
                                <p:selectOneMenu autoWidth="false" converter="omnifaces.SelectItemsConverter"
                                                 value="#{officeLayerView.parentOfficeLayerFilterValue}"
                                                 filter="true" filterMatchMode="contains"
                                                 dynamic="true">
                                    <f:selectItem
                                            itemLabel="#{message['officeLayer.parent.placeholder']}"
                                            noSelectionOption="true"/>
                                    <f:selectItems value="#{officeLayerView.officeLayerList}" var="officeLayer"
                                                   itemLabel="#{localization.bangla ? officeLayer.nameLocale : officeLayer.name}"
                                                   itemValue="#{officeLayer}"/>
                                </p:selectOneMenu>
                            </div>

                            <!-- Clear filters button -->
                            <div class="col-6 lg:col-2 lg:col-offset-2 flex align-items-end">
                                <p:commandButton styleClass="ui-button-secondary ui-button-outlined hover:bg-gray-300"
                                                 value="#{message['filter.clear']}"
                                                 onclick="PF('officeLayerTable').clearFilters()"
                                                 actionListener="#{officeLayerView.clearAllFilters('officeLayerForm:officeLayerTable')}"
                                                 update="@form">
                                    <p:resetInput target="@form"/>
                                </p:commandButton>
                            </div>

                            <!-- Search button to apply filters -->
                            <div class="col-6 lg:col-2 flex align-items-end">
                                <p:commandButton icon="pi pi-search" styleClass="ui-button-info"
                                                 value="#{message['filter.search']}"
                                                 oncomplete="PF('officeLayerTable').filter()"
                                />
                            </div>
                        </p:outputPanel>
                    </p:tab>
                </p:accordionPanel>

                <p:dataTable widgetVar="officeLayerTable" id="officeLayerTable" lazy="true"
                             cellNavigation="false"
                             value="#{officeLayerView.officeLayerLazyModel}" var="officeLayer"
                             reflow="true"
                             rows="5"
                             paginator="true"
                             paginatorAlwaysVisible="false"
                             paginatorPosition="bottom"
                             paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             currentPageReportTemplate="{startRecord}-{endRecord} of {totalRecords} records"
                             rowsPerPageTemplate="5,10,{ShowAll|'All'}"
                             rowsPerPageLabel="Showing per page"
                             rowIndexVar="rowIndex">
                    <!-- Filter event listener-->
                    <p:ajax event="filter" listener="#{officeLayerView.onFilter}"/>

                    <p:column headerText="#{message['text.name']}">
                        <h:outputText value="#{officeLayer.name}"/>
                    </p:column>
```

### Reproducer

Initialize the dataTable without any active filters.
Apply a globalFilter through the input field located outside of the dataTable.
Navigate to another page in the dataTable.
Observe that the globalFilter is cleared, while the column filters remain applied.

### Expected behavior

The globalFilter FilterMeta should persist across pagination actions, similar to the behavior of column-specific filters. This would allow both globalFilter and column filters to remain active as the user navigates through different pages of the dataTable.

### PrimeFaces edition

Community

### PrimeFaces version

14.0.2

### JSF implementation

Mojarra

### JSF version

4

### Java version

17

**Comment by melloware** [comment] 2024-10-28 14:26
we need more than just snippets we need a runnable reproducer because your example is missing too much code.

**Comment by riyadomf** [comment] 2024-10-28 19:26
> we need more than just snippets we need a runnable reproducer because your example is missing too much code.
I'll try to provide a runnable reproducer.

Is there any way to insert globalFilter meta by catching the FilterEvent.
Or any way to create globalFIlter meta which will be ignored by applyFilter of JPALazyDataModel. e.g., 
```java
            for (FilterMeta filter : filterBy.values()) {
                if (filter.getField() == null || filter.getFilterValue() == null || filter.isGlobalFilter()) {
                    continue;
                }
```

Basically I want filter based on multiple columns with a single filter field

**Comment by melloware** [comment] 2024-10-28 19:30
@FlipWarthog ☝🏻

**Comment by melloware** [comment] 2024-10-28 19:35
A runnable reproducer would help.  We even already have a JPA Lazy example set up: https://github.com/primefaces/primefaces-test/tree/jpa

**Comment by FlipWarthog** [comment] 2024-10-28 19:45
I'm not sure I'm entirely following. I think we'd still need a runnable reproduce either showing the original issue mentioned or what you're trying to do

**Comment by riyadomf** [comment] 2024-10-29 07:40
Here's a reproducer link: https://github.com/riyadomf/primefaces-test

I didn't use the JPALazyModel in this code. This is just for showing what I'm trying to achieve.

I have a `<p:dataTable>` using `JPALazyDataModel`. Below is a sample of the code I am using to set up the lazy data model:
```java
    protected JPALazyDataModel<T> get() {
        return JPALazyDataModel.<T>builder()
                .entityClass(entityClass)
                .entityManager(() -> em)
                .caseSensitive(false)
                .filterEnricher((filterBy, cb, cq, root, predicates) -> {

                    if (filterBy.containsKey(GLOBAL_FILTER_KEY) && (globalFilterFields != null && !globalFilterFields.isEmpty())) {
                        List<Expression<String>> fieldsToApplyGlobalFilterOn = globalFilterFields.stream().map(root::get).collect(Collectors.toList());
                        applyGlobalFilterByFields(fieldsToApplyGlobalFilterOn, filterBy.get(GLOBAL_FILTER_KEY), cb, predicates);
                    }
                })
                .build();
    }
```

Here, I'm extracting the globalFilter `FilterMeta` and creating predicates accordingly.


### What I Want to Achieve:
* **Global Filtering across Multiple Fields:** I want to apply a global filter that checks multiple fields in an entity. If any of the fields contain the filter value, the corresponding row should be included in the result.
 
* **Global Filter Outside the DataTable:** I want to place the global filter input field outside the data table, so users can interact with it independently. However, PrimeFaces doesn't allow me to generate a globalFilter meta unless it’s inside the <p:dataTable>


### My Approaches and Problems:
1. Using a Hidden Input Field to Generate the Global Filter Meta:
    * I added a hidden input field inside the `<p:dataTable>` to trigger the generation of the global filter meta. Inside the onFilter listener I update the filterValue of global filter meta and 
    insert the column filter meta.
      ```java
                      <p:dataTable widgetVar="officeLayerTable" id="officeLayerTable" lazy="true"
                                   cellNavigation="false"
                                   value="#{officeLayerView.officeLayerLazyModel}" var="officeLayer"
                                   reflow="true"
                                   rows="5"
                                   paginator="true"
                                   paginatorAlwaysVisible="false"
                                   paginatorPosition="bottom"
                                   paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                   currentPageReportTemplate="{startRecord}-{endRecord} of {totalRecords} records"
                                   rowsPerPageTemplate="5,10,{ShowAll|'All'}"
                                   rowsPerPageLabel="Showing per page"
                                   rowIndexVar="rowIndex">
                          <h:inputHidden id="globalFilter"/>
                          <!-- Filter event listener-->
                          <p:ajax event="filter" listener="#{officeLayerView.onFilter}"/>
      ```

      update the global filter meta:

      ```java
          public void onFilter(FilterEvent event) {
                Map<String, FilterMeta> filterBy = event.getFilterBy();
              // update the globalFilter creatd by inputHidden component.
              if (globalFilterValue != null) {
                  filterBy.get(FilterMeta.GLOBAL_FILTER_KEY).setFilterValue(globalFilterValue);
              }
          }
      ```
    * **Issue:** When I use this approach, the column filters reset on every pagination event.

2. Creating the Global Filter Meta Programmatically:
      * I removed the hidden input field and created the global filter meta using FilterMeta.of() manually.
          ```java
        public void onFilter(FilterEvent event) {
            Map<String, FilterMeta> filterBy = event.getFilterBy();
            
            if (globalFilterValue != null) {
                FilterMeta globalFilterMeta = FilterMeta.of(globalFilterValue, null);
                filterBy.put(FilterMeta.GLOBAL_FILTER_KEY, globalFilterMeta);
            }
        }
        ```
      * **Issue** In this approach, the global filter resets on every pagination event.


### My Questions:
1. Is there any way to place the globalFilter outside the data table?
I want to avoid adding an input field inside the header facet of the table.
If I was able to put the `globalFilter` component inside an accordionPanel in the table header, that would have been also enough. But when the `globalFilter` input component is inside an accordion panel, the dataTable doesn't create the global filter meta. 

2. Bypassing the Entity Attribute Check in JPALazyDataModel:
The JPALazyDataModel ensures that every field being filtered is an actual entity attribute. Is there any way to bypass this check for the global filter to allow custom filtering across multiple fields? 
There's a check like `isGlobalFilter()` but that's only for global filter meta created internally.

3. Filtering Across Multiple Fields Without Using globalFilter:
Is there any way to apply multi-field filtering without using the globalFilter mechanism?

**Comment by tandraschko** [comment] 2024-10-29 08:57
2 and 3) can be done with a custom JPALazyDataModel, we dont offer something OOTB as its to special

**Comment by tandraschko** [comment] 2024-10-29 09:23
as this now covers multiple issues/questions, i will dedicate this issue only to "support globalFilter outside of DataTable" which is likely a won't fix.
As i said, using the `officeLayerView` inside the filterEnricher or custom LazyDataModel is currently the way to go

**Comment by melloware** [comment] 2024-10-29 11:31
@riyadomf i agree with @tandraschko why don't you do this 

1. use `<p:ajax>` on your Global Filter field so its always set in the backing bean when they user sets it
2. In your `officeLayerView` use that field value in your global filter.

```java
@Named
@ViewScoped
@Data
public class OfficeLayerView implements Serializable {

    @Inject
    EntityManager em;

    JPALazyDataModel<CarEntity> model;

   String globalFilterValue;

    @PostConstruct
    public void init() {
        model = JPALazyDataModel.<CarEntity>builder()
                .entityManager(() -> em)
                .entityClass(CarEntity.class)
                .filterEnricher((filterBy, cb, cq, root, predicates) -> {
                    // predicates.add(cb.isNull(root.get("id")));
                    // use your globalFilterValue here and create as many predicates on as many columns as you want to filter on?
                })
                .build();
    }
}

```

**Closed as not planned** 2024-10-29 12:09 UTC
Labels: Resolution:  Wontfix

**Comment by riyadomf** [comment] 2024-10-29 12:45
> @riyadomf i agree with @tandraschko why don't you do this
> 
> 1. use `<p:ajax>` on your Global Filter field so its always set in the backing bean when they user sets it
> 2. In your `officeLayerView` use that field value in your global filter.
> 
> ```java
> @Named
> @ViewScoped
> @Data
> public class OfficeLayerView implements Serializable {
> 
>     @Inject
>     EntityManager em;
> 
>     JPALazyDataModel<CarEntity> model;
> 
>    String globalFilterValue;
> 
>     @PostConstruct
>     public void init() {
>         model = JPALazyDataModel.<CarEntity>builder()
>                 .entityManager(() -> em)
>                 .entityClass(CarEntity.class)
>                 .filterEnricher((filterBy, cb, cq, root, predicates) -> {
>                     // predicates.add(cb.isNull(root.get("id")));
>                     // use your globalFilterValue here and create as many predicates on as many columns as you want to filter on?
>                 })
>                 .build();
>     }
> }
> ```

This isn't possible for me. Because I'm using a separate class (`OfficeLayerLazyDataModelProvider`) which provides me the JPALazyDataModel. There's no way I can pass the `globalFilterValue` to the `filterEnricher`.  

```java
public class OfficeLayerLazyDataModelProvider extends BaseLazyDataModelProvider<OfficeLayer> {
    public JPALazyDataModel<OfficeLayer> getLazyDataModel() {
        return JPALazyDataModel.<OfficeLayer>builder()
                .entityClass(OfficeLayer.class)
                .entityManager(() -> em)
                .caseSensitive(false)
                .filterEnricher((filterBy, cb, cq, root, predicates) -> {
                   // 1.  can't use the globalFilterValue because it's in OfficeLayerView bean and 
                  //    I can't send the globalFilterValue as parameter in filterEnricher
                  // 2. If filterEnricher had executed before applying column based filters (right after applyGlobalFilters() execution)
                  //     then I could have passed a custom field FilterMeta and removed it before next execution

                })
                .build();
    }
}```

**Comment by melloware** [comment] 2024-10-29 12:46
Then you need to refactor your code?

**Comment by tandraschko** [comment] 2024-10-29 12:50
yeah
inject the officeLayerView or pass the value or something like that

**Comment by riyadomf** [comment] 2024-10-30 08:43
@tandraschko @melloware I've followed your approach (official way) and injected the value in filterEnricher.
It works but now I'm facing another problem.

The first `FilterMeta` I injected in the `FilterEvent` always stays in the `filterBy` map. 
I can manually reset the `filterBy` map but it still comes back in the pagination event. 


```java
    public void onFilter(FilterEvent event) {
        Map<String, FilterMeta> filterBy = event.getFilterBy();
        filterBy.put("name", FilterMeta.builder().field("parentOfficeLayer.id")
                .filterValue(filterValue).matchMode(MatchMode.EQUALS).build());
    }
```
I'm experiencing an issue where the FilterMeta I insert during the FilterEvent remains persistent in the filterBy map across events. For example, after loading the page, if I set a filter with FilterMeta for "name" with the value "x", it works as expected. However, when I subsequently search with a different value, such as "y", the DataTable retains the previous FilterMeta with "x" in the filterBy map.

Even after manually clearing the filterBy map, this FilterMeta reappears during subsequent pagination or filter events. 
Why the dataTable component reintroduces the previous filterMeta?

**Comment by tandraschko** [comment] 2024-10-30 08:49
i dont think you should manipulate filterMeta
its recreated at different points
as i said, put all your own stuff in filterEnricher, without manipulating datatable internals

**Comment by riyadomf** [comment] 2024-10-30 10:14
I planned to utilize the `JPALazyDataModel` - `createPredicate()`  to create Predicates from `filterMeta` internally. But it's not possible I guess.

**Comment by riyadomf** [comment] 2024-10-30 10:14
> i dont think you should manipulate filterMeta its recreated at different points as i said, put all your own stuff in filterEnricher, without manipulating datatable internals

I planned to utilize the `JPALazyDataModel` - `createPredicate()`  to create Predicates from `filterMeta` internally. But it's not possible I guess.

**Comment by tandraschko** [comment] 2024-10-30 10:18
you can do it - create a new dummy FilterMeta in your filterEnricher and call createPredicate

**Comment by riyadomf** [comment] 2024-10-30 10:26
> you can do it - create a new dummy FilterMeta in your filterEnricher and call createPredicate; just dont manipulate internals.

It's protected method. So I have to extend it, I guess. 
I was trying to use `createPredicate()` inside `filterEnricher` while building the `JPALazyDataModel`

```java
return JPALazyDataModel.<T>builder()
                .entityClass(entityClass)
                .entityManager(() -> em)
                .caseSensitive(false)
                .filterEnricher((filterBy, cb, cq, root, predicates) -> {
                    // use createPredicate() to create Predicate from filterMeta

                })
                .build();
```

**Comment by tandraschko** [comment] 2024-10-30 10:31
yeah, thats a valid point
can you make a new issue "JPALazyDataModel: make create Predicate usable from filterEnricher"?
maybe you can try to work on a PR

still unsure how we make it the best
this.createPredicate would be nice but not possible

**Comment by riyadomf** [comment] 2024-10-30 10:43
Ok, I'll look into it. Thanks for the help btw.

> yeah, thats a valid point can you make a new issue "JPALazyDataModel: make createPredicate usable from filterEnricher"? maybe you can try to work on a PR
> 
> still unsure how we make it the best this.createPredicate would be nice but not possible
