### ISSUE TITLE
BaseMenuModel: generateUniqueIds overwrites manually set ids

### ISSUE THREAD

**Issue by zicheee** [primefaces/primefaces#6647] opened 2020-12-11 15:16 UTC
**Describe the defect**
When I create a sub menu and assign my custom id, the id is overwritten by BaseMenuModel.generateUniqueIds.
In case a menu element already has an id it should not be overwritten.

**Environment:**
 - PF Version: _8.0_

**To Reproduce**
Copy the code below and create a sub menu and assign your custom id to the menu item. When the menu is rendered, the *BaseMenuRenderer* calls the method generateUniqueIds and the ids are overwritten.
If you want to access the menu later by the id 4711 (see doSomething) you will notice that the id of the element is 0. 

**Expected behavior**
I expect the id to not be overwritten

**Example XHTML**
```
<pu:menu widgetVar="me" model="#{menuDemoBean .menuModel}" />
```

**Example Bean**
```java
@ManagedBean
@SessionScoped
public class MenuDemoBean {

    private MenuModel menuModel;

    @PostConstruct
    public void initView() {
        DefaultMenuItem item = DefaultMenuItem.builder()
            .value("Sub Menu Entry")
            .outcome("/any-outcome.xhtml")
            .build();

        DefaultSubMenu subMenu = DefaultSubMenu.builder()
            .id("4711")
            .label("Sub-Menu")
            .build();
        subMenu.getElements().add(item);

        this.menuModel = new DefaultMenuModel();
        this.menuModel.getElements().add(subMenu);
    }

    public MenuModel getMenuModel() {
        return menuModel;
    }

    public void doSomething() {
        for (MenuElement menuElement : this.menuModel.getElements()) {
            System.out.println(menuElement.getId());
        }
    }

}
```

**Possible change**
```java
    private void generateUniqueIds(List<MenuElement> elements, String seed) {
        if (elements == null || elements.isEmpty()) {
            return;
        }

        int counter = 0;

        for (MenuElement element : elements) {
            
            String id = element.getId();
            if(id != null) {
                id = (seed == null) ? String.valueOf(counter++) : seed + ID_SEPARATOR + counter++;
                element.setId(id);
            }
            
            if (element instanceof MenuGroup) {
                generateUniqueIds(((MenuGroup) element).getElements(), id);
            }
        }
    }
```

**Comment by melloware** [comment] 2020-12-11 15:18
Duplicate of https://github.com/primefaces/primefaces/issues/1039 which is fixed for 9.0

**Closed as completed** 2020-12-11 15:18 UTC
Labels: Resolution: Duplicate
