### ISSUE TITLE
Dialog: Primefaces tooltip gets behind dialog on every click on dialog

### ISSUE THREAD

**Issue by stefan-veljkovic** [primefaces/primefaces#10100] opened 2023-05-09 17:10 UTC
### Describe the bug

Hi , could you check this bug please if it's fixed. The thing is when Primefaces dialog is opened, whenever I click on dialog property "z-index" is getting incremented and it lefts hover component behind dialog component.

### PrimeFaces edition

None

### PrimeFaces version

12.0

### JSF implementation

Mojarra

### Java version

11.0.11

**Comment by jepsar** [comment] 2023-05-09 17:21
See also #9295

**Comment by melloware** [comment] 2023-05-09 21:16
Have you tried this with 13.0-SNAPSHOT?

**Comment by melloware** [comment] 2023-05-09 21:17
Please follow the issue template or provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by Stefke-Novo** [comment] 2023-05-09 23:03
Sorry for not explaining the full story. Here's the whole issue.
Firstly, when I open dialog nothing is happening as expected and "z-index" value is 1012 as on picture below:
![image](https://github.com/primefaces/primefaces/assets/72997632/89d306eb-8c6b-4232-adb7-d56858238285)


After clicking icon for more information strange thing happens. Dialog gets new value of "z-index" property while tooltip component remains the same. The picture below describes the issue:
Number of "z-index" now has 1015. Wherever I click on dialog the number keeps increasing by 2 or 1 mostly.
![image](https://github.com/primefaces/primefaces/assets/72997632/b814edaa-155d-4724-88fa-efc6100950b8)


I don't know if the problem is solved. Could you please check? If not, is there any other solution or js document where the problem could be fixed (which I'm guessing)? 
Thank you so much for help .

**Comment by melloware** [comment] 2023-05-09 23:21
We need to see your exact code as I can't reproduce your issue. So please provide a reproducer as requested.

**Comment by Stefke-Novo** [comment] 2023-05-10 01:56
This is the only code necessary to execute bug.

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:jsf="http://xmlns.jcp.org/jsf"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>PrimeFaces Test</title>
	<h:outputScript name="test.js" />
	<h:outputStylesheet name="test.css" />
</h:head>
<h:body>
	<h:form id="frmTest">
		<h:panelGrid columns="1" cellpadding="5">
			<p:commandButton value="Basic" type="button"
				onclick="PF('dlg1').show();" />

			
		</h:panelGrid>
		<p:dialog header="Basic Dialog" widgetVar="dlg1" minHeight="40">
			<h:outputText id="top" value="Hover me for tooltip and then click me to see a bug." />
			<p:tooltip for="top" value="Enter your username" position="right"/>
		</p:dialog>

	</h:form>

</h:body>
</html>
```

This is situation before after hovering and before clicking label:
![image](https://github.com/primefaces/primefaces/assets/72997632/3e05a61d-83d0-4753-a89b-1b339dcfa8a6)

This is situation after clicking:
![image](https://github.com/primefaces/primefaces/assets/72997632/c799a533-ee6c-48b8-ad09-1611c7631a5d)

**Comment by melloware** [comment] 2023-05-10 02:03
Try adding `dynamic="true` to the p:dialog.

**Comment by Stefke-Novo** [comment] 2023-05-10 02:06
Unfortunately without success
Code :
```
<p:dialog header="Basic Dialog" widgetVar="dlg1" minHeight="40" dynamic="true">
			<h:outputText id="top" value="Hover me for tooltip and then click me to se a bug." />
			<p:tooltip for="top" value="Enter your username" position="right"/>
		</p:dialog>
```

**Comment by melloware** [comment] 2023-05-10 11:41
MonkeyPatch:
```js
if (PrimeFaces.widget.Dialog) {
    PrimeFaces.widget.Dialog.prototype.moveToTop = function() {
        this.jq.css('z-index', 1000);
    }
}
```

Working reproducer: 
[pf-10100.zip](https://github.com/primefaces/primefaces/files/11441383/pf-10100.zip)

**Comment by melloware** [comment] 2023-05-10 11:51
OK I fixed it along with https://github.com/primefaces/primefaces/pull/9949

**Comment by melloware** [comment] 2023-05-10 11:54
No it will be fixed in 13.0.0 which is not out yet just use that MonkeyPatch for now.

**Comment by Stefke-Novo** [comment] 2023-05-10 11:54
Thank you for information.

**Comment by melloware** [comment] 2023-05-11 15:33
This is a better monkeyPatch:

```js
if (PrimeFaces.widget.Dialog) {
    PrimeFaces.widget.Dialog.prototype.moveToTop = function() {
        if (!this.isVisible()) {
            this.jq.css('z-index', PrimeFaces.nextZindex());
        }
    }
}
```

**Closed as completed** 2023-05-12 11:47 UTC
Labels: workaround
