### ISSUE TITLE
Data from one of the columns is not being exported in Primefaces

### ISSUE THREAD

**Issue by tienthai48** [primefaces/primefaces#2970] opened 2017-11-17 19:23 UTC
For some reasons, I am getting the "**_org.primefaces.component.panelgrid.PanelGrid@ .._**." from one of the colunms when exporting data to a pdf file (please see attachment below).  I have been trying several approaches but unsuccessful.  Can you please let me know what could have caused this issue and how to get around it?  Many thanks for your help.

Regards,

![error](https://user-images.githubusercontent.com/12912012/32964835-83229644-cba2-11e7-8134-a8870bb5a67b.png)

###

Primefaces version : 5.3.9

**Comment by melloware** [comment] 2017-11-17 19:40
You are going to need to put your XHTML here so we can see the grid you are exporting.

**Comment by tienthai48** [comment] 2017-11-17 19:44
<p:panelGrid style="border:1px;width:100%;">									
									    <f:facet name="header">
										    <p:row>
										       	<p:column style="font-size:.8em;font-weight: bold;padding-top: 1px;padding-left: 1px;padding-right: 1px;padding-bottom: 1px;font-weight: bold;float:none;width:100%" colspan="2">
										         	<h:outputText value="#{result.testDesc}"/>
										      	</p:column>
									        </p:row>
										</f:facet>
										<p:row>
									        <p:column style="font-size:.8em; padding-bottom: 1px;padding-top: 1px; border-top-width: 1px;padding-right: 1px;padding-left: 1px; font-weight: bold; width:80px;float:left">
									            <h:outputText value="Action" style="font-weight: bold;"/>
									        </p:column>
									
									        <p:column style="font-size:.8em;padding-bottom: 1px;padding-top: 1px; border-top-width: 1px;padding-right: 1px;padding-left: 1px;float:none">
									            <h:outputText value="#{result.transaction}"/>
									        </p:column>
									    </p:row>
									    
								   		<p:row>
									        <p:column style="font-size:.8em;padding-bottom: 1px;padding-top: 1px; border-top-width: 1px;padding-right: 1px;padding-left: 1px; font-weight: bold; width:80px;float:left">
									            <h:outputText value="Session" style="font-weight: bold;"/>
									        </p:column>
									
									        <p:column style="font-size:.8em;padding-bottom: 1px;padding-top: 1px; border-top-width: 1px;padding-right: 1px;padding-left: 1px;float:none">
									            <h:outputText value="#{result.sessionId}"/>
									        </p:column>
									    </p:row>										
										
										<p:row>
									        <p:column style="font-size:.8em;padding-bottom: 1px;padding-top: 1px; border-top-width: 1px;padding-right: 1px;padding-left: 1px; font-weight: bold; width:80px;float:left">
									            <h:outputText value="Start" style="font-weight: bold;"/>
									        </p:column>
									
									        <p:column style="font-size:.8em;padding-bottom: 1px;padding-top: 1px; border-top-width: 1px;padding-right: 1px;padding-left: 1px;float:none">
									            <h:outputText value="#{result.startDate}"/>
									        </p:column>
									    </p:row>
										
										<p:row>
									        <p:column style="font-size:.8em;padding-bottom: 1px;padding-top: 1px; border-top-width: 1px;padding-right: 1px;padding-left: 1px; font-weight: bold; width:80px;float:left">
									            <h:outputText value="End" style="font-weight: bold;"/>
									        </p:column>
									
									        <p:column style="font-size:.8em;padding-bottom: 1px;padding-top: 1px; border-top-width: 1px;padding-right: 1px;padding-left: 1px;float:none">
									            <h:outputText value="#{result.endDate}"/>
									        </p:column>
									    </p:row>																	  
									</p:panelGrid>

**Comment by melloware** [comment] 2017-11-17 19:55
Yes its because your TestInfo column is a subtable.  How would it possibly render this in PDF?  You have a few choices.

1. Mark the Test Info column as exportable ="false" so it s not included.

2. Use the exportFunction="" on p:column to define how that column gets rendered. See this example on how to use ExportFunction.  https://github.com/primefaces/primefaces/issues/2238#issuecomment-300511806

However you are on PF 5.3.9 I have no idea when exportFunction was included.  It may have been in PF 6.0.

**Comment by melloware** [comment] 2017-11-17 19:56
Sorry I forgot to mention this is not a BUG so please close this ticket.

**Comment by tienthai48** [comment] 2017-11-17 20:02
sorry Melloware,  the version I sent you is a little messy as I was playing around with it.  Below is the data being exported. (see attached text file)
[test.txt](https://github.com/primefaces/primefaces/files/1483643/test.txt)

**Comment by melloware** [comment] 2017-11-17 20:04
Same issue. Your Test Info column contains `<p:panelGrid style="border:1px;width:100%;">` so the exporter doesn't know how to make that into Text because its a component.

**Comment by tienthai48** [comment] 2017-11-17 20:06
In your opinion, what should I be doing to correct this problem?  Any of your suggestion is appreciated.

TT

**Comment by melloware** [comment] 2017-11-17 20:10
Use the exportFunction="" on p:column to define how that column gets rendered in the Exporter. See this example on how to use ExportFunction. #2238 (comment)

**Comment by koan00** [comment] 2017-11-17 20:10
Did you try a p:subTable here? It would render something similar and hopefully export better?

**Comment by tienthai48** [comment] 2017-11-17 20:13
I will try out your suggestions Melloware and Koan00.  Many thanks for your suggestions.
TT

**Comment by melloware** [comment] 2017-11-17 20:16
i would close this ticket as its not a bug.  PF is working as designed.

**Closed as completed** 2017-11-17 20:19 UTC
