### ISSUE TITLE
SelectOneMenu and SelectCheckBoxMenu doesn't hide under the horizontal menu bar

### ISSUE THREAD

**Issue by stefan-dan** [primefaces/primefaces#6524] opened 2020-11-18 11:04 UTC
**Describe the defect**
SelectOneMenu and SelectCheckBoxMenu doesn't hide under the horizontal menu bar when nothing is selected.

**Reproducer**
Check the showcase: 
https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml
https://www.primefaces.org/showcase/ui/input/checkboxMenu.xhtml

**Environment:**
 - PF Version: 8.0.2-SNAPSHOT
 - JSF + version: Mojarra-2.3.13.
 - Affected browsers: ALL

**To Reproduce**
1. Go to https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml
2. Click on 'Select One'
3. Scroll down
![Capture](https://user-images.githubusercontent.com/52972263/99522667-9a959d00-299e-11eb-9e72-ee126610b385.PNG)

**Expected behavior**
When nothing is selected SelectOneMenu and SelectCheckBoxMenu should hide under the horizontal menu bar.

**Comment by Rapster** [comment] 2020-11-18 11:11
showcase issue?

**Comment by stefan-dan** [comment] 2020-11-18 11:48
@Rapster no, showcase is the simplest way to show the bug, I am using the same environment, with a <p:menubar> and the issue persist.

**Comment by melloware** [comment] 2020-11-18 12:51
When the page renders... PrimeFaces assigns components a zIndex starting at 1000, so 1001, 1002, etc.

When you click a SelectOne popup menu it generates a new `PrimeFaces.zIndex++` to ensure that the popup menu has a new higher zIndex like 1005 to ensure its on top.

In fact, if you use the DOM Inspector every time you click the SelectOne you see its Zindex increase 1006, 1007, 1008 etc.  I believe this is all as PrimeTek designed and not a bug. If you really want your menu bar on top assign it a zIndex like 99999.

When I make `layout-topbar` zIndex=9999 look what mine does..
![image](https://user-images.githubusercontent.com/4399574/99532831-ecc0c900-2972-11eb-851b-23c58072bb84.png)

**Closed as completed by melloware** 2020-11-18 12:51 UTC
Labels: Resolution:  Wontfix, workaround
