### ISSUE TITLE
DataTable: rendered condition is ignored inside celleditor

### ISSUE THREAD

**Issue by Bhaskar8055** [primefaces/primefaces#184] opened 2015-04-28 06:58 UTC
rendered condition is not working properly in side the P:datatable on celleditor/facets/columns
1. A data table having some columns, first and second column is having selectOnes for the inline edit.
   Based upon the selected value in first column, im loading the data for second selectOne value list.
   till here it works fine.
2. The problem is, if there is no values/records for second column selectOne - in this case, user should able to edit that selectOne.

So what i did,

I have in the second column input facet, i have added to selectOnes, i) rendered condition: if list is not empty, selectOne with edit=false
ii) rendered condition: if list is empty, selectOne with edit=true, user can enter manually.

But this render is not working, i tried visible condition, putting these selectOnes in different facets and rendered the facets even this didnt work.

here is my code,

```
                 <p:column headerText="col2" style="width:15%;">
                    <p:cellEditor id="edit2">
                        <f:facet name="output">
                            <h:outputText value="#{vdrlist.typWert}"/>
                        </f:facet>
                         <f:facet name="input" >
                              <p:selectOneMenu id="attrTypeLov" value="#{vdrlist.typWertObj}" onchange="setDirty()"  converter="#{attributeBean.hisDynAttributWertConverter}" filter="true"  filterMatchMode="contains" panelStyle="width:400" style="width:98%" var="wertObj" rendered="#{!empty bean.dataList}" visible="#{!empty bean.dataList}">
                                <f:selectItem itemLabel="#{res.label_selectOne}"
                                              itemValue="" noSelectionOption="true"/>
                                <f:selectItems value="#{attributeBean.attributesValueList}" var="atrLov"
                                               itemValue="#{atrLov}" itemLabel="#{atrLov.wert}"/>
                                <p:column>#{wertObj.wert}</p:column>
                                <p:column>#{wertObj.einheit.name}</p:column>
                                <p:column>#{wertObj.name}</p:column>
                                <p:column>#{wertObj.kommentar}</p:column>
                                <p:ajax event="change" update="valueMeaning unitOp atrUnit" listener="#{attributeBean.onChangeAtrValue(atrRowId)}" />
                            </p:selectOneMenu>                                   
                      <p:selectOneMenu id="attrTypeLov2" effect="fold" style="width:98%" editable="true" rendered="#{!empty bean.dataList}" visible="#{!empty          bean.dataList}"                             
                                         onchange="setDirty()" >
                                <f:selectItem itemLabel="No Value. Pls enter" itemValue="" noSelectionOption="true"/>

                            </p:selectOneMenu>

                        </f:facet>
                    </p:cellEditor>
                </p:column>
```

**Comment by melloware** [comment] 2019-12-02 14:30
Duplicate of https://github.com/primefaces/primefaces/issues/3956

Closing this ticket as the newer ticket has more information.

**Closed as completed by melloware** 2019-12-02 14:30 UTC
Labels: :lady_beetle: defect, Resolution: Duplicate
