### ISSUE TITLE
p:dialog showEffect-attribute side effect with p:inputSwitch

### ISSUE THREAD

**Issue by hoax** [primefaces/primefaces#1718] opened 2016-08-24 10:06 UTC
When I open a p:dialog for the first time with showEffect-attribute set and then click on the inputSwitch it turns on and straight off again as often as I click on it. After closing and reopening the dialog the inputSwitch works as expected. Using the Firefox (48.0) developer tools I see that after the first try there are are two event listeners for "click" that do toggle the switch.
If I remove the showEffect attribute of p:dialog everything works as expected from the beginning. 

This bug I can reproduce with 5.2 and 6.0 community edition.

``` xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">

    <h:head>
        <title>Test</title>
    </h:head>

    <h:body>
        <h:form>
            <p:dialog widgetVar="dialog" 
                showEffect="slide">

                <p:inputSwitch id="switch"
                        onLabel="on"
                        offLabel="off" />
            </p:dialog>

            <p:commandButton value="Open dialog"
                update="switch"
                onsuccess="PF('dialog').show();" />
        </h:form>
    </h:body>
</html>
```

**Comment by hoax** [comment] 2016-09-16 08:28
Just found that this bug has been found before: http://forum.primefaces.org/viewtopic.php?f=3&t=42821

**Comment by melloware** [comment] 2018-12-06 12:00
@tandraschko @Rapster can you close this ticket. Its a duplicate of https://github.com/primefaces/primefaces/issues/3969 which was closed by Optimus because he said InputSwitch is deprecated for ToggleSwitch.   But that issue is the exact same issue as this one here.

**Comment by Rapster** [comment] 2018-12-06 12:03
@hoax please use toogleSwitch instead. Thanks Emil

**Closed as completed by Rapster** 2018-12-06 12:03 UTC
