### ISSUE TITLE
Primefaces 8 showcase not working

### ISSUE THREAD

**Issue by paveljakov** [primefaces/primefaces#12051] opened 2024-06-02 06:30 UTC
### Describe the bug

Primefaces 8 showcase not working: https://www.primefaces.org/showcase-v8/

Please do not remove it, we still use primefaces 8.

### Reproducer

https://www.primefaces.org/showcase-v8/

### Expected behavior

Showcase opens

### PrimeFaces edition

None

### PrimeFaces version

8

### JSF implementation

Mojarra

### JSF version

2.1

### Java version

8

**Comment by tandraschko** [comment] 2024-06-02 07:43
Duplicate of: https://github.com/primefaces/primefaces/issues/12019

**Closed as not planned by tandraschko** 2024-06-02 07:43 UTC
Labels: Resolution: Duplicate
