### ISSUE TITLE
Documentation: how to set a default parameter for all components of same type

### ISSUE THREAD

**Issue by hfluz** [primefaces/primefaces#5836] opened 2020-04-23 21:43 UTC
## 1) Environment
- PrimeFaces version: 8.0
- Application server + version: jetty (primefaces-test project)

## 2) Expected behavior
If I select 23/04/2020, that should be the date submitted.

## 3) Actual behavior
However, the value submitted is 23/04/0020.

## 4) Steps to reproduce
Set locale to pt_BR, create a LocalDate variable and use it in a Calendar or DatePicker component.

.. 

## 5) Patch to reproduce the error with https://github.com/primefaces/primefaces-test:

```
Index: src/main/java/org/primefaces/test/TestView.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/org/primefaces/test/TestView.java	(revision 0fca0e2a9c3a808e29f69aa5bb8071b189eb004c)
+++ src/main/java/org/primefaces/test/TestView.java	(date 1587677612246)
@@ -1,26 +1,40 @@
 package org.primefaces.test;
 
-import java.io.Serializable;
 import javax.annotation.PostConstruct;
 import javax.faces.view.ViewScoped;
 import javax.inject.Named;
+import java.io.Serializable;
+import java.time.LocalDate;
 
 @Named
 @ViewScoped
 public class TestView implements Serializable {
     
     private String testString;
+    private LocalDate datInicio;
     
     @PostConstruct  
     public void init() {
         testString = "Welcome to PrimeFaces!!!";
     }
 
+    public void salvar(){
+        System.out.println(datInicio);
+    }
+
     public String getTestString() {
         return testString;
     }
 
     public void setTestString(String testString) {
         this.testString = testString;
-    }    
+    }
+
+    public LocalDate getDatInicio() {
+        return datInicio;
+    }
+
+    public void setDatInicio(LocalDate datInicio) {
+        this.datInicio = datInicio;
+    }
 }
Index: src/main/webapp/WEB-INF/faces-config.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/webapp/WEB-INF/faces-config.xml	(revision 0fca0e2a9c3a808e29f69aa5bb8071b189eb004c)
+++ src/main/webapp/WEB-INF/faces-config.xml	(date 1587676972305)
@@ -4,6 +4,10 @@
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-facesconfig_2_2.xsd">
     <application>
+        <locale-config>
+            <default-locale>pt_BR</default-locale>
+            <supported-locale>pt_BR</supported-locale>
+        </locale-config>
         <action-listener>org.primefaces.application.DialogActionListener</action-listener>
         <navigation-handler>org.primefaces.application.DialogNavigationHandler</navigation-handler>
         <view-handler>org.primefaces.application.DialogViewHandler</view-handler>
Index: src/main/webapp/test.xhtml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/webapp/test.xhtml	(revision 0fca0e2a9c3a808e29f69aa5bb8071b189eb004c)
+++ src/main/webapp/test.xhtml	(date 1587677860655)
@@ -5,12 +5,14 @@
       xmlns:p="http://primefaces.org/ui"
       xmlns:h="http://java.sun.com/jsf/html">
 
-    <h:head>
-        <title>PrimeFaces Test</title>
-    </h:head>
-    <h:body>
-
+<h:head>
+    <title>PrimeFaces Test</title>
+</h:head>
+<h:body>
+    <h:form prependId="false">
         <h1>#{testView.testString}</h1>
-
-    </h:body>
+        <p:calendar value="#{testView.datInicio}" pattern="dd/MM/yy"/>
+        <p:commandButton value="Salvar" action="#{testView.salvar}"/>
+    </h:form>
+</h:body>
 </html>
\ No newline at end of file

```

**Comment by hfluz** [comment] 2020-04-23 21:44
Forgot to mention, but if I set the pattern property, the issue doesn't happen.

**Comment by melloware** [comment] 2020-04-23 21:51
@hfluz can you read through this long thread?  

Duplicate of #5696

 I wonder if yours is the same issue.  It sounds like it.

**Comment by hfluz** [comment] 2020-04-24 00:00
Yes @melloware , it really sounds like the same issue. So it's a JDK bug and unfortunately the only workaround is to add pattern to all calendars/datepickers in all my projects.

I know it won't solve my issue right now, but a suggestion would be the creation of a context param that sets pattern value globally to all date components.

**Comment by melloware** [comment] 2020-04-24 11:18
@hfluz that is not a bad idea.  Somthing like...
```xml
	<context-param>  
		<param-name>primefaces.DEFAULT_DATE_PATTERN</param-name>  
		<param-value>dd/MM/yy</param-value>  
	</context-param>
```

**Comment by tandraschko** [comment] 2020-04-27 18:05
-1
as we would add a contextparam for almost each component attribute then

**Comment by tandraschko** [comment] 2020-04-27 18:08
we had a issue for creating a mechanism to allow default values, configured globbaly in the application for each attribute for each component
thats a better way to go

**Comment by tandraschko** [comment] 2020-04-28 18:21
Could someone search for the ticket? :D
Nevertheless, i have a good idea of doing it in PF, even possible for all components. This could be possible feature of a new JSF version as its really useful.

I just wonder about the config format... Should we do it in XML or something?
Actually some default properties might require java code.

**Comment by melloware** [comment] 2020-04-28 18:30
I did a search after you mentioned it and I could not find anything about it.  I looked for "gloabl" and "default value" but the GitHub search is not the best.

**Comment by tandraschko** [comment] 2020-04-28 18:58
ok, nvm
we can simply wrap Application#createCompoment and set default properties there.
However, a user can also simply wrap Application#createComponent. 
So we if we dont have some very nice API or other feature, it think its not worth to add a abstraction here.
Maybe just a good docu article

**Comment by melloware** [comment] 2020-04-28 19:57
That is really clever never even thought about doing that.

**Closed as completed** 2020-05-24 13:44 UTC
Labels: documentation

**Comment by melloware** [comment] 2020-05-24 13:45
Documented here on how to do set a global attribute: https://primefaces.github.io/primefaces/8_0/#/core/globalattributes?id=global-attributes
