### ISSUE TITLE
datePicker: selectionMode multiple -> js error when rendering existing not-empty value

### ISSUE THREAD

**Issue by joergmattes** [primefaces/primefaces#4547] opened 2019-02-15 18:29 UTC
## 1) Environment
- PrimeFaces version: 7.0.RC3
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? I guess no, since 7.0.RC3 was released yesterday
- Application server + version: Tomcat 9.0.12
- Affected browsers: Chrome 62

## 2) Expected behavior
When displaying a datepicker with selectionMode="multiple" and existing non-empty value, I expect that the datepicker works correctly.

## 3) Actual behavior
Datepicker doesn't pop up, and I get the following js error:
`Uncaught TypeError: this.viewDate.getMonth is not a function`
`   at K.(anonymous function).(anonymous function).renderDateView (http://.../datepicker.js?ln=primefaces&v=7.0.RC3:1:16614)`

## 4) Steps to reproduce
Use a bean with not-empty property `List<Date> dateList`, and datePicker with selectionMode multiple.

## 5) Sample XHTML
`<p:datePicker selectionMode="multiple" value="#{schedule.dateList}" .../>`

## 6) Sample bean
```
public class Schedule {
  private List<Date> dateList = Arrays.asList(new Date());
}
```

After debugging `renderDateView`, I saw that the code is not expecting an array as viewDate, and therefore fails with "is not a function". I am not a JavaScript expert, but I could fix it by checking for array and then using viewDate[0]:
```
renderDateView: function() {
  if (Array.isArray(this.viewDate)) {
    this.monthsMetaData = this.createMonths(this.viewDate[0].getMonth(), this.viewDate[0].getFullYear());
   } else {
    this.monthsMetaData = this.createMonths(this.viewDate.getMonth(), this.viewDate.getFullYear());
  }
```
But that's not enough, as the same error occurs e.g. on the `navForward `function.

**Comment by mertsincan** [comment] 2019-02-18 08:23
Duplicate of #4549

**Closed as completed by mertsincan** 2019-02-18 08:23 UTC
