### ISSUE TITLE
PrimeFaces 6.1.2 Picklist: browser crash Issue on transfer 4000+ records

### ISSUE THREAD

**Issue by praveen22goal** [primefaces/primefaces#5555] opened 2020-01-23 09:27 UTC
## 1) Environment
- PrimeFaces version: 6.1.2
- Does it work on the newest released PrimeFaces version? Version? No Tried in Version 7
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
No, I tried with steps https://github.com/primefaces/primefaces/issues/3675 but not works for me

- Application server + version: WebSphere Application Server Version 18.0.0.2 Liberty
- Affected browsers: IE

## 2) Expected behavior
should Transfer Data from Source to Target Immediately 
...

## 3) Actual behavior
If Data more than 4000, Browser crashed 
..

## 4) Steps to reproduce
Transfer less records, it will transfer source to target,
If more than 4000 records browser crashed
.. 

## 5) Sample XHTML

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"      
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
	
    <h:head>
    </h:head>
    <h:body>
    	<h2>Pick List Demo</h2>
    	<h:form>
    	   <p:pickList id="pickList" value="#{pickDemoBean.testNumber}" 
    	   var="numbers" itemLabel="#{numbers}" itemValue="#{numbers}" />
 
    	</h:form>
    </h:body>
</html>
..

## 6) Sample bean
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;

import org.primefaces.model.DualListModel;

@ManagedBean(name = "pickDemoBean")
public class PickDemoBean {
	private DualListModel<String> testNumber;
	
	@PostConstruct
    public void init() {
        List<String> testSource = new ArrayList<String>();
        List<String> testTarget = new ArrayList<String>();        
        for(int i=1;i<=4001;i++)        
           testSource.add("Test "+i);        
        testNumber = new DualListModel<String>(testSource, testTarget);    
    }
 

	public DualListModel<String> getTestNumber() {
		return testNumber;
	}

	public void setTestNumber(DualListModel<String> testNumber) {
		this.testNumber = testNumber;
	}
	
}

..

**Comment by tandraschko** [comment] 2020-01-23 09:30
Duplicate of? https://github.com/primefaces/primefaces/issues/4320

**Closed as completed** 2020-01-23 09:32 UTC
Labels: Resolution: Duplicate

**Comment by praveen22goal** [comment] 2020-01-23 09:43
https://github.com/primefaces/primefaces/issues/4320 for filter, we are not using filter.. During transfer browser gets crashed or could you please provide the js file for the fix?

**Comment by tandraschko** [comment] 2020-01-23 09:44
try 6.2.14 if it's fixed.
I dont have to time provide custom fixes, i just do it in my sparetime here.

**Comment by praveen22goal** [comment] 2020-01-23 11:26
added effect="none" and its working fine. 

<p:pickList id="pickList" value="#{pickDemoBean.testNumber}" 
	   var="numbers" itemLabel="#{numbers}" itemValue="#{numbers}" effect="none" />

**Comment by melloware** [comment] 2020-01-23 12:34
Yep I was going to suggest effect="none" next as the animation is really expensive when you have that many items.
