### ISSUE TITLE
Tree: collapse not called if dynamic = true

### ISSUE THREAD

**Issue by fabermundi** [primefaces/primefaces#5409] opened 2019-12-06 13:07 UTC
## 1) Environment
- PrimeFaces version: 7.0.10
- Does it work on the newest released PrimeFaces version? Version 7.0.10? No
- Application server + version: wildfly 16
- Affected browsers: Chrome, Firefox

## 2) Expected behavior
When "dynamic" property is setted to "true", "collapse" event should be called when node is collapsed.

## 3) Actual behavior
"collapse" event is not called.

## 4) Steps to reproduce
Use sample code and expand node "1" -> expand event is called. Then collapse the same node and the "collapse" event is not called.

## 5) Sample XHTML
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <f:view>
        <h:head>
            <title>Test tree</title>
            <link rel="shortcut icon" href="favicon.ico"/>
        </h:head>
        <h:body>
            <h:form>
                <p:tree value="#{testBean.testValues}" var="value" dynamic="true">
                    <p:ajax event="expand" listener="#{testBean.nodeExpanded}" />
                    <p:ajax event="collapse" listener="#{testBean.nodeCollapsed}" />
                    <p:treeNode>
                        <h:outputText value="#{value}" />
                    </p:treeNode>
                </p:tree>
            </h:form>
        </h:body>
    </f:view>
</html>
```

## 6) Sample bean
```
package lu.etat.pch.docroom.ejb.controllers;

import org.primefaces.event.NodeCollapseEvent;
import org.primefaces.event.NodeExpandEvent;
import org.primefaces.model.DefaultTreeNode;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import java.io.Serializable;

@Named
@SessionScoped
public class TestBean implements Serializable {
    public DefaultTreeNode getTestValues() {
        DefaultTreeNode root = new DefaultTreeNode();
        DefaultTreeNode node1 = new DefaultTreeNode("1", root);
        DefaultTreeNode node2 = new DefaultTreeNode("2", node1);
        return root;
    }

    public void nodeExpanded(NodeExpandEvent event) {
        System.out.println("nodeExpanded");
    }

    public void nodeCollapsed(NodeCollapseEvent event) {
        System.out.println("nodeCollapsed");
    }
}
```

**Comment by tandraschko** [comment] 2019-12-06 13:18
I can only talk about 8.0RC1 and what i see is this:
- the events are correctly called
- but as you update the whole tree, it's broken. I removed the update and everything is working fine.

Thats up to PrimeTek / @mertsincan to fix something in Elite.

**Comment by fabermundi** [comment] 2019-12-06 14:12
Indeed, I'm sorry but I published the wrong code. The tree should be dynamic and the update should not be there. I corrected the code above and tested it against version 8.0.RC1 of Primefaces and "collapsed" event is not called.

**Comment by tandraschko** [comment] 2019-12-23 09:39
Duplicate of: https://github.com/primefaces/primefaces/issues/3668
also with fix and details inside

**Closed as completed by tandraschko** 2019-12-23 09:39 UTC
Labels: Resolution: Duplicate
