### ISSUE TITLE
Schedule: Is there a way to format the slot time (first column of the schedule)?

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#5841] opened 2020-04-28 16:13 UTC
I am using 

```
<p:schedule ... slotLabelFormat="HH:mm" timeFormat="HH:mm">
```
But the first colum of the schedule which show the slot time is always formatted in am/pm style.

Is this a bug or does there exists some other attributes to do that?

## 1) Environment
- PrimeFaces version: 8.0

## 2) Expected behavior
Using the attribute slotLabelFormat I would expect that the slot time of schedule is formatted accordingly.

## 3) Actual behavior
Actually,  the attribute slotLabelFormat has no effect on formatting if the slot time of schedule

**Comment by melloware** [comment] 2020-04-28 17:20
Can you put together a small reproducer using Primefaces Test so we can debug it?

**Comment by tuerker** [comment] 2020-04-28 17:55
You can use the primefaces demo with         
```
<p:schedule id="schedule" value="#{scheduleJava8View.eventModel}" widgetVar="myschedule" 
slotLabelFormat="HH:mm" 
timeFormat="HH:mm">

```

Sorry, I forgot to explicitly mention that you have to look at the day or week view of the schedule. There the first column, which prints the slot time, is always in am/pm style independently whether you use the two attributes above or not.

**Comment by tuerker** [comment] 2020-04-28 17:56
![Screenshot from 2020-04-28 19-54-11](https://user-images.githubusercontent.com/10051373/80520838-4dae9280-898a-11ea-8465-4e3f2fcea211.png)

**Comment by melloware** [comment] 2020-04-28 20:08
I am searching the code and I don't see "slotLabelFormat" being used anywhere in the Renderer or Widget.  So i feel like this is a bug.

**Comment by tuerker** [comment] 2020-04-28 20:13
according to the documentation https://primefaces.github.io/primefaces/8_0/#/components/schedule
 the attribute slotLabelInterval should be an attribute of p:shedule.

**Comment by melloware** [comment] 2020-04-28 20:17
Yep just fixed with PR. it looks like SlotLabelInterval had the wrong "setter" and "slotLabelFormat" was never even used.

![image](https://user-images.githubusercontent.com/4399574/80533485-b4708380-896b-11ea-9f54-2f791e09c66a.png)

**Comment by tuerker** [comment] 2020-04-28 20:19
great. thank you very much.

**Comment by tuerker** [comment] 2020-04-28 20:21
hope that version 9 come out soon? what is the timeline for the next release?

**Comment by melloware** [comment] 2020-04-28 21:51
Unfortunately if you look at the release history here: https://repo.maven.apache.org/maven2/org/primefaces/primefaces/

Its been averaging about once a year in March.  That is why a lot of people subscribe to Elite releases or PRO support to get interim 8.0.1, 8.0.2 releases etc.

Or you can always build from source if you host your own Nexus repository and feel lucky.

**Closed as completed** 2020-04-28 21:52 UTC
Labels: :lady_beetle: defect
