### ISSUE TITLE
Inputmask: dir="RTL" doesn't work

### ISSUE THREAD

**Issue by tomspindola** [primefaces/primefaces#8627] opened 2022-04-04 13:13 UTC
When using InputMask in primefaces 10.0.0 (jakarta) with dir="RTL" the characters are entered in reverse order.
If the attribute value is used, the characters are displayed from end to begin.
As comparison, the behavior of the same attribute when using InputText is correct.

**Environment:**
 - PF Version: _10.0.0
 - Affected browsers: Chrome, FireFox, etc

**To Reproduce**
Add the attribute dir="RTL" to a form.

**Expected behavior**
The characters to be displayed in the correct order. ( Just as it happens, for example, in the InputText)

**Example XHTML**

```xml
<h:form id="frmTest">
<h:outputLabel value="RTL InputMask" />	           <p:inputMask  mask="999/99" dir="RTL"  /><br/>
<h:outputLabel value="RTL InputMask with value "/> <p:inputMask  value="123/45" mask="999/99" dir="RTL"  /><br/>	
							
<h:outputLabel value="RTL InputText " />		  <p:inputText  dir="RTL"  /><br/>
<h:outputLabel value="RTL InputText with value " /> <p:inputText  dir="RTL" value="123/45" />br/>
</h:form>
```

**Comment by melloware** [comment] 2022-04-04 13:18
Its an open issue in the plugin. Please go upvote that issue: https://github.com/RobinHerbots/Inputmask/issues/956

**Comment by melloware** [comment] 2022-04-12 20:25
I am using the latest PF 12.0.0 SNAPSHOT and it seems to be working fine.

```xml
<p:inputMask id="rtl" value="#{maskView.rtl}" mask="999/99" dir="rtl" />
```

![image](https://user-images.githubusercontent.com/4399574/163047575-fdff52ac-4077-47eb-851d-553dc27fbdab.png)

Have you tried it with 11.0.0 ?

**Comment by melloware** [comment] 2022-04-12 20:37
Nevermind I see:

![image](https://user-images.githubusercontent.com/4399574/163049477-9cc72c38-0eec-4afc-bf71-9e9b0398c77c.png)


Reproducer: [pf-8627.zip](https://github.com/primefaces/primefaces/files/8476391/pf-8627.zip)

**Comment by melloware** [comment] 2023-05-16 20:26
Tracking this in the third party library will re-open here when fixed in third party library

**Closed as completed by melloware** 2023-05-16 20:26 UTC
Labels: :lady_beetle: defect, third-party, rtl
