### ISSUE TITLE
Slider: NullPointerException when using in dynamic TabView

### ISSUE THREAD

**Issue by fabermundi** [primefaces/primefaces#4791] opened 2019-05-08 15:08 UTC
## 1) Environment
- PrimeFaces version: 7.0.1
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version: Wildfly 16
- Affected browsers: IE, Chrome, Firefox

## 2) Expected behavior
When submitted the given form I do not expect a NullPointerException to be thrown.

## 3) Actual behavior
A NullPointerException is thrown

## 4) Steps to reproduce
Use the given example (extended example from PrimeFaces Demo of Slider), when clicking the "ok" button then following error is thrown:
```
Caused by: java.lang.NullPointerException
        at deployment.infoChantier-wildfly16-PROD.war//org.primefaces.component.slider.Slider.validate(Slider.java:106)
```
The error seems to be coming from the "getSubmittedValue" funtion in the Slider.java.
The line:
`return input.getSubmittedValue() == null && input.isLocalValueSet() ? input.getValue() : input.getSubmittedValue();`
returns "NULL" because the "isLocalValueSet" return "false" and so the "getSubmittedValue" is returned which is "NULL" whereas the "getValue" would return the right number.

I do not know if this helps but this is as far as I came.

## 5) Sample XHTML
```
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">
    <f:view>
        <h:head>
            <title>InfoChantier</title>
        </h:head>
        <h:body>
            <h:form>
                <p:tabView dynamic="true" rows="20" value="#{sliderView.tabs}" var="tab">
                    <p:tab title="#{tab}">
                        <h:panelGrid columns="1" style="margin-bottom: 10px">
                            <h:outputText id="displayRange" value="Between #{sliderView.number8} and #{sliderView.number9}" />
                            <p:slider for="txt6,txt7" display="displayRange" style="width: 400px" range="true" displayTemplate="Between {min} and {max}" />
                        </h:panelGrid>
                        <h:inputHidden id="txt6" value="#{sliderView.number8}" />
                        <h:inputHidden id="txt7" value="#{sliderView.number9}" />
                    </p:tab>
                </p:tabView>
                <p:commandButton value="Ok" />
            </h:form>
        </h:body>
    </f:view>
</ui:composition>
```

## 6) Sample bean
```
package lu.etat.pch.infoChantier.ejb.controllers;

import javax.inject.Named;

@Named
public class SliderView {
    private int number8 = 30;
    private int number9 = 80;

    public int getNumber8() {
        return number8;
    }

    public void setNumber8(int number8) {
        this.number8 = number8;
    }

    public int getNumber9() {
        return number9;
    }

    public void setNumber9(int number9) {
        this.number9 = number9;
    }

    public String[] getTabs() {
        String[] result = new String[2];
        result[0] = "Tab 1";
        result[1] = "Tab 2";
        return result;
    }
}
```

**Comment by tandraschko** [comment] 2019-05-08 15:13
@cnsgithub @melloware interessted to look at it? probably related to our new validation

**Comment by melloware** [comment] 2019-05-08 16:26
Definitely related to this ticket: https://github.com/primefaces/primefaces/issues/3282

Reproducer: 
[pf-4791.zip](https://github.com/primefaces/primefaces/files/3158356/pf-4791.zip)

**Comment by cnsgithub** [comment] 2019-05-09 06:41
I'll have a look at it. 

`Slider.validate` seems to be called twice, first time everything's fine, second time gives the `NullPointerException`.

**Comment by cnsgithub** [comment] 2019-05-09 07:33
After testing further, I am not sure now if this is necessarily an issue related to validation.

As I mentioned before, `validate` is called two times. I had not recognized that before, but this is of course because we have two tabs containing a `p:slider`.

Four hidden input fields get rendered and submitted when pressing the _Ok_ button. @fabermundi Btw, what is the use-case of this when binding the slider values to exactly the same fields in the model? You'll always end up with contradictory values being submitted.

Nevertheless, debugging showed me that validation is always performed against the very same hidden input fields, regardless of the four request parameters being submitted.

Four request parameters:
![image](https://user-images.githubusercontent.com/13161711/57435230-1ad13300-723d-11e9-82c8-6c6bf5028115.png)

Only two `UIInput` components:
![image](https://user-images.githubusercontent.com/13161711/57435327-6552af80-723d-11e9-9e16-c0f9d7985dfd.png)

Maybe this bug is rather caused by the dynamic `tabView` or wrong usage. The validation seems to work properly without the tabs.

**Comment by tandraschko** [comment] 2019-05-09 09:04
@mertsincan can be ported to elite

**Comment by tandraschko** [comment] 2019-05-09 09:14
@cnsgithub i see
the real problem is the input lookup, let me try something and i will explain later

**Comment by fabermundi** [comment] 2019-05-09 09:23
@cnsgithub yes I know that the example is pretty useless, I was trying to keep it simple.
My use-case is a table that content is changed depending the tab you select, above the table is a range slider in order to select a year range to filter the values in the table so this slider must be shown in every tab.

Guys, thanks for your work so far :-)

**Comment by tandraschko** [comment] 2019-05-09 09:50
ok no idea :D
no time to dig deeper

But, from client side, it's expected that validation is called for both slider
not sure why the second are null values

**Comment by matinh** [comment] 2019-05-22 07:27
I tried to reproduce it and the NPE only happens with Mojarra, not with MyFaces! Maybe this is related to https://github.com/eclipse-ee4j/mojarra/issues/4562? Also related might be PrimeFaces issues https://github.com/primefaces/primefaces/issues/4756 and https://github.com/primefaces/primefaces/issues/4771.

**Comment by melloware** [comment] 2019-05-22 20:07
I would say if you have narrowed this to a Mojarra issue we should probably close this ticket.

**Comment by matinh** [comment] 2019-05-22 20:57
I actually don't know if it's a Mojarra issue. I just said it is not reproducable with MyFaces and it might be related to the linked Mojarra issue. @tandraschko said in https://github.com/primefaces/primefaces/issues/4756#issuecomment-490207259 

> "I'm also not sure if it's a Mojarra bug (could be a PF bug, too)"

So I wouldn't close this till somebody had a closer look.

**Comment by melloware** [comment] 2019-08-15 19:31
I am going to close this as a Mojarra issue. We can re-open if we determine its anything other than that.

**Closed as completed by melloware** 2019-08-15 19:31 UTC
Labels: :lady_beetle: defect, 7.0.3
