### ISSUE TITLE
UltimaMenu: Primefaces seem to break Primeface Extension menu (used in ultima theme)

### ISSUE THREAD

**Issue by Hamsterbau** [primefaces/primefaces#3867] opened 2018-07-12 12:38 UTC
## 1) Environment
- PrimeFaces version: 6.2.2 to 6.2.6
- PrimeFaces Extensions version: 6.2.6
- Does it work on the newest released PrimeFaces version? Version? Nope!
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Don't know :(
- Application server + version: Wildfly 11
- Ultima Theme + version: 1.1.3
- Affected browsers: All

## 2) Expected behavior
Menu entries should have context path in the URL. But after upgrading PF from 6.2.2 to 6.2.6 these URLs are broken in the mentioned Primefaces Extension UltimaMenu

## 3) Actual behavior
Menu is broken, because the URLs do not include the right context path:

Before Update:
https://my.hostname/context/myPage.xhtml
https://my.hostname/context/sub/myPage2.xhtml

After Update:
https://my.hostname/myPage.xhtml
https://my.hostname/sub/myPage.xhtml

## 4) Steps to reproduce
Just use the Primefaces Extensions Ultima Menu in PF 6.2.6.

## 5) Sample XHTML

<pu:menu widgetVar="me" model="#{contextBean.menuModel}" />

## 6) Sample bean

public MenuModel getMenuModel() {

MenuModel mm = new DefaultMenuModel();
DefaultMenuItem mi = new DefaultMenuItem(
"My Page",
"any-icon",
"/myPage.xhtml"
);
DefaultMenuItem subMi = new DefaultMenuItem(
"My Page",
"any-icon",
"/sub/myPage2.xhtml"
);

...

mm.addElement(mi);
mm.addElement(subMi);

return mm;
}

**Comment by tandraschko** [comment] 2018-07-12 12:42
Duplicate of: https://github.com/primefaces/primefaces/issues/3819

**Closed as completed by tandraschko** 2018-07-12 12:42 UTC
Labels: Resolution: Duplicate

**Comment by Hamsterbau** [comment] 2018-07-12 12:46
Ohh sorry not finding this issue. Should i just delete this one?
And thanks for linking the duplicate, i will view for help there.

PS: Are you the Flash, answering so fast ;D
