### ISSUE TITLE
p:treeTable: dynamic column p:columns is not rendered in partial request

### ISSUE THREAD

**Issue by hieusonson9x** [primefaces/primefaces#4056] opened 2018-09-20 11:17 UTC
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.1.11
- Application server + version: WildFly 9.5

## 2) Expected behavior
render p:columns
![image](https://user-images.githubusercontent.com/15144197/45873464-be5bf900-bdbc-11e8-9d06-073e614443fc.png)

## 3) Actual behavior
not render
![image](https://user-images.githubusercontent.com/15144197/45814925-5b595c00-bd01-11e8-864e-1608502c5ebe.png)
![image](https://user-images.githubusercontent.com/15144197/45873500-d6337d00-bdbc-11e8-8632-b03f01a71fec.png)

## 4) Steps to reproduce
- First time access - it rendered dynamic column
- Trigger to collapse, and re-expand -> the dynamic column will not be rendered again
## 5) Sample XHTML

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	>
		<h:form>
		 <p:treeTable
			value="#{coPmTreeBudgetQuotation.root}" var="data">
			<p:column styleClass="align-middle" headerText="item" style="min-width:50px">
				<h:outputText value="#{data.d_seq_no}" />
			</p:column>
			<p:column styleClass="align-middle" headerText="#{messages['item_description']}" filterBy="#{data.item_description}" filterStyle="width:98%">
				<h:outputText value="#{data.item_description}" style="min-width:300px"/>
			</p:column>
			<p:columns value="#{coPmTreeBudgetQuotation.test()}" var="temp" headerText="#{temp}">
				<h:outputText value="#{temp}" />
			</p:columns>
		</p:treeTable>
	</h:form>
</ui:composition>

## 6) Sample bean

@Named
public class CoPmTreeBudgetQuotation extends AbstractTreeBean<Co_contract_rev_pm> {

	private Co_bgtquote_base_hdr currentQuotation;

	@Override
	public TreeNode getRoot() {
		this.initTree(Co_contract_rev_hdr.find("FIT0000005", 4).getListOf_Pms());
		return super.getRoot();
	}

	public List<String> test() {
		final List<String> res = new ArrayList<>();
		res.add("aa");
		res.add("bb");
		return res;
	}
}

**Comment by melloware** [comment] 2018-09-20 12:11
Have you tried it in 6.2 or 6.3-SNAPSHOT.  There have been tons of TreeTable fixes since 6.1.11 you can see here: https://github.com/primefaces/primefaces/issues?page=1&q=is%3Aissue+treetable+is%3Aclosed&utf8=%E2%9C%93

**Comment by tandraschko** [comment] 2018-09-20 12:44
If you dont provide a runnable example, it will be closed as invalid

**Comment by hieusonson9x** [comment] 2018-09-21 09:41
> If you dont provide a runnable example, it will be closed as invalid

Sr, pls help me

**Comment by melloware** [comment] 2018-09-21 11:13
Just like the instructions above say:  "Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution."

**Comment by tandraschko** [comment] 2018-09-28 09:02
Will close it for now. If you have a forked primefaces-test reproducer, feel free to come back.

**Closed as completed by tandraschko** 2018-09-28 09:02 UTC
Labels: Resolution: Invalid
