### ISSUE TITLE
Datatable: setupDraggableColumns + Frozen Columns

### ISSUE THREAD

**Issue by qiuzhichao** [primefaces/primefaces#9976] opened 2023-03-29 09:20 UTC
### Describe the bug

When the table draggableColumns property and frozenColumns property exist at the same time, the frozen body and the drag column body appear to be misaligned when dragging operation.
I think it is  when drag happening，the problem attribute,function setupDraggableColumns which does not distinguish the frozen column elements well, causing the frozen column carcass to be able to fill

### PrimeFaces edition

None

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

1.0

### Java version

1.8

**Comment by Rapster** [comment] 2023-03-29 10:02
> You'll have better chance to receive an answer and a solution if you add a GitHub link or zip file of your reproducer. Clone https://github.com/primefaces/primefaces-test.git to create one.

**Comment by melloware** [comment] 2023-03-29 11:21
Also I am pretty sure these two features were not designed to work together. Not every datatable feature can be used in conjunction with every other datatable feature especially frozen columns.

**Comment by melloware** [comment] 2023-11-27 14:06
Hmm we already have this in the code..

```js
        // GitHub #5013 Frozen Columns should not be draggable/droppable
        if($this.cfg.frozenColumns) {
            var frozenHeaders = this.frozenThead.find('.ui-frozen-column');
            frozenHeaders.draggable('disable');
            frozenHeaders.droppable('disable');
            frozenHeaders.disableSelection();
        }
```

**Comment by melloware** [comment] 2023-11-27 14:08
@qiuzhichao  I can't reproduce this.  Going to close this for now unless you can provide a reproducer where I can see the issue?

**Closed as not planned by melloware** 2023-11-27 14:08 UTC
Labels: :lady_beetle: defect, workaround

**Comment by melloware** [comment] 2024-01-06 17:09
13.0.5 improves frozen + draggable support.
