### ISSUE TITLE
dataTable paginatorAlwaysVisible="false" do not show / hide paginator when filter values change

### ISSUE THREAD

**Issue by mauritz-lovgren** [primefaces/primefaces#1953] opened 2016-12-06 16:42 UTC
## 1) Environment
- PrimeFaces version: 5.x, 6.0.0 - 6.0.10
- Does it work on the newest PrimeFaces version? no
- Application server + version: JBoss EAP 7.0.3 GA (Mojarra 2.2.12)
- Affected browsers: All major (Firefox, Chrome, Opera, Safari, Edge, IE)

## 2) Expected behaviour

When using p:dataTable paginatorAlwaysVisible="false" one would expect paginator to display only when needed, also when changing filter values so that if number of visible rows are less than paginator rows, paginator should be hidden, and when filter changes so that number of visible rows exceeds paginator rows, paginator should be shown.

(Note: If we set paginatorAlwaysVisible="true" (default value), we would expect the paginator to always be present, of course.)

## 3) Actual behavior

Paginator does not show or hide dynamically when entering / removing filter values causing number of visible rows increase to above or decrease to below rows count for paginator. Initial display of paginator (at first render of page) works as expected.

## 4) Steps to reproduce

1. Run sample below, notice that the paginator is not shown at startup, this is expected, since the initial filter value ("A") assumes only one row is displayed, hence paginator should be hidden initially.
2. Remove the filter value ("A") from the filter input text box above the first (and only) column. Notice that the paginator is not shown, even though ALL items in the list are actually present in the table now (exceeding rows count). This state is very confusing to user since the user has no idea that there are really more than 5 rows in this table!
3. Refresh the page, notice that the paginator is now made visible (expected).
4. Enter "B" in the filter input text box, reducing number of displayed rows to 1. Notice that the paginator is still present, even though visible rows are now less than 5 (expecting it to hide automatically due to paginatorAlwaysVisible="false" setting). 

## 5) Sample XHTML

```
<h:form id="formId">

<p:dataTable id="tableId"
    value="#{stringListBean.stringListItems}" var="stringListItem"
    rows="5" paginatorAlwaysVisible="false"
    filterBy="#{stringListBean.initialFilterState}"
    filteredValue="#{stringListBean.filteredRows}">

    <p:column id="stringColId" headerText="Test"
        filterBy="#{stringListItem.string}"
        filterValue="#{stringListBean.filterValue}"
        filterMatchMode="contains">
       <h:outputText value="#{stringListItem.string}"/>
    </p:column>

</p:dataTable>

</h:form>
```
## 6) Sample bean

```

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import java.io.Serializable;
import java.util.ArrayList;

@SessionScoped
@Named
public class StringListBean implements Serializable {

    private List<StringListItem> stringListItems;
    private List<StringListItem> filteredRows;
    // Initial filter value set to same as first value in list.
    private String filterValue = "A";

    @PostConstruct
    private void init() {
        stringListItems = new ArrayList<>();
        stringListItems.add(new StringListItem("A"));
        stringListItems.add(new StringListItem("B"));
        stringListItems.add(new StringListItem("C"));
        stringListItems.add(new StringListItem("D"));
        stringListItems.add(new StringListItem("E"));
        stringListItems.add(new StringListItem("F"));
        stringListItems.add(new StringListItem("G"));
        stringListItems.add(new StringListItem("H"));
    }

    public List<FilterState> getInitialFilterState() {
        List<FilterState> initialFilterState = new ArrayList<>();
        // Send current filter value as initial filter value
        initialFilterState.add(new FilterState("formId:tableId:stringColId", filterValue);
        return initialFilterState;
    }

    public List<StringListItem> getStringListItems() {
        return stringList;
    }

    public List<StringListItem> getFilteredRows() {
        return this.filteredRows;
    }

    public void setFilteredRows(List<StringListItem> filteredRows) {
        this.filteredRows = filteredRows;
    }

    public String getFilterValue() {
        return filterValue;
    }

    public void setFilterValue(String filterValue) {
        this.filterValue = filterValue;
    }
}

public class StringListItem implements Serializable {
    private String string;

    public StringListItem() { }

    public StringListItem(String string) {
        this.string = string;
    }

    public String getString() {
        return string;
    }

    public void setString(String string) {
        this.string = string;
    }
}

```

## 7) Workaround

We have created a workaround for this issue (so that the paginator is hidden when visible row count goes below configured rows per page count) by a using a PostFilterEvent listener (f:event type="org.primefaces.event.data.PostFilterEvent" listener="...") that calls a custom JavaScript by adding a class having CSS display: none; every time filter values are changed by user.

(we could not use the regular p:ajax event="filter" listener, since filteredRows are not set until just before the PostFilterEvent is called, and we need the filteredRows.size() to determine if visible rows are less than rows configured for paginator.)

The JavaScript simply adds CSS 'display: none;' to the ui-paginator div to hide it. This, of course requires that the paginator is rendered at all times, so we need to have both paginator="true" and paginatorAlwaysVisible="true" to make sure it is rendered otherwise we cannot make it visible when filters are removed after initially not shown and visible rows exceeds paginator rows :-D.

It would of course be nice if the paginatorAlwaysVisible="false" handled all this automagically so we did not have to have custom event handling and JS everywhere we use p:dataTable.

**Comment by jxmai** [comment] 2016-12-06 18:26
Duplicate of #1715 (The same bug), which has already been marked as defect.

**Closed as completed** 2016-12-06 19:54 UTC
Labels: Resolution: Invalid
