### ISSUE TITLE
Dialog Framework:  Can't be used in iframe

### ISSUE THREAD

**Issue by zsuiqiang** [primefaces/primefaces#1776] opened 2016-09-21 00:54 UTC
## 1) Environment
- PrimeFaces version: 6.04
- Does it work on the newest PrimeFaces version?
- Application server + version:GlassFish v4
- Affected browsers:Chrome
## 2) Expected behavior

Dialog can be closed correctlty which opened through a button in a iframe.
## 3) Actual behavior

"dialogReturn" ajax listener was not invoked
## 4) Steps to reproduce

When i click "ok" button,method "closeSelectDlg" was invoked

```
   public void closeSelectDlg(ActionEvent e) {
        RequestContext.getCurrentInstance().closeDialog(getSelectedNode().getData());
    }
```

But "dialogReturn" ajax listener was not invoked

```
<p:ajax event="dialogReturn" listener="#{collectorManager.onCollectorTypeChosen}" update="type" />
```
## 5) Sample XHTML

```
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="shortcut icon" href="resources/images/favicon.png"/>
        <link rel="bookmark icon" href="resources/images/favicon.png"/>
        <h:outputStylesheet name="default.css" library="css"/>
        <title>#{sysParams.params.get('SystemName').des}</title>
        <style type="text/css">
            body, html {width: 100%;height: 100%;overflow: hidden;margin:0;}
            #workspace {width: 100%;height: 100%;overflow: scroll;margin:0;}
        </style>
    </h:head>
    <h:body>
        <ui:include src="/Template/header.xhtml"/>
        <pe:layout fullPage="false" style="position: absolute;top: 52px;bottom: 0px;left: 0px;right: 0px;overflow: visible">
            <pe:layoutPane position="west" size="180">         
                <!--<p:panelMenu model="{panelMenu.model}"/>--> 
                <h:form>
                    <p:tree  id="tree" value="#{menuManager.root}" var="menu" animate="true">
                        <p:treeNode expandedIcon="ui-icon-folder-open" collapsedIcon="ui-icon-folder-collapsed">
                            <a  class="header_a_class" href="#{menu.URL}"  target="workspace" style="text-decoration: none;font-size: 16px">
                                #{menu.name}
                            </a>
                        </p:treeNode>                  
                    </p:tree>          
                </h:form>
            </pe:layoutPane>
            <pe:layoutPane id="centerUnit" position="center" resizeWhileDragging="true">
                <iframe id="workspace" name="workspace" src="cbm/cm/RealtimeData.jsf"></iframe>
            </pe:layoutPane>
        </pe:layout>
    </h:body>
</html>
```

New page was opend in iframe,and the the first page CollectorManager.xhtml :

```
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet library="css" name="default.css"/>
        <h:outputScript library="script" name="locales.js"/>
        <title>Collector</title>
    </h:head>

    <h:body>
        <h:form id="form">
            <p:layout style="position: absolute;top: 0px;bottom: 0px;left: 0px;right: 0px;margin: 1px">
                <p:layoutUnit position="west" size="200" gutter="1"  resizable="true">
                    ..............
                </p:layoutUnit>
                <p:layoutUnit position="center" gutter="1"  id="centerUnit">   
                    <p:toolbar id="toolbar">
                        <f:facet name="left">
                            <p:commandButton value="add" actionListener="#{collectorManager.create}" process="@this" update=":form:dlg" oncomplete="PF('dlg').show()" icon="ui-icon-plusthick"/>
                        </f:facet>
                    </p:toolbar>
                    <p:dataTable id="table" value="#{collectorManager.model}" var="collector" selection="#{collectorManager.selection}" selectionMode="single" rowKey="#{collector.id}">
                        <p:ajax event="rowSelect"/>
                        <p:ajax event="rowDblselect" listener="#{collectorManager.onRowSelection}" update=":form:dlg" oncomplete="PF('dlg').show()"/>
                        <p:column headerText="Collector ID">
                            <h:outputText value="#{collector.id}"/>
                        </p:column>
                        ...............................
                    </p:dataTable>

                    <p:dialog id="dlg" widgetVar="dlg" style="width:500px; margin: 30px 20px 2px -20px" header="detail info">

                        <p:toolbar>
                            <f:facet name="left">
                                <p:commandButton value="save" actionListener="#{collectorManager.save}" process="dlg" update=":form:table" oncomplete="PF('dlg').hide()" icon="ui-icon-disk"/>
                            </f:facet>
                        </p:toolbar>
                        <p:panelGrid>
                            <p:row>
                                ...............
                                <p:column>
                                    <h:outputText value="type"/>
                                </p:column>
                                <p:column >
                                    <p:inputText id="type" value="#{collectorManager.selection.type}" readonly="true"/>
                                    <p:commandButton icon="ui-icon-search" actionListener="#{collectorManager.openCollectorTypeSelectDF}" process="@this">
                                        <p:ajax event="dialogReturn" listener="#{collectorManager.onCollectorTypeChosen}" update="type" />
                                    </p:commandButton>
                                </p:column>
                            </p:row>
                           .................
                        </p:panelGrid>                        
                    </p:dialog>
                </p:layoutUnit>
            </p:layout>
        </h:form>
    </h:body>
</html>
```

CollectorTypeSelectDF.xhtml

```
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <h:outputStylesheet name="default.css" library="css"/>
        <title>Please select type</title>
    </h:head>
    <h:body>
        <h:form>
            <p:toolbar>
                <f:facet name="right">
                    <p:commandButton value="ok" actionListener="#{collectorTypeManager.closeSelectDlg}" process="@form" icon="ui-icon-check"/>
                </f:facet>
            </p:toolbar>
            <p:fieldset>
                <p:tree  id="tree" value="#{collectorTypeManager.root}" var="node" selectionMode="single" selection="#{collectorTypeManager.selectedNode}">
                    <p:treeNode expandedIcon="ui-icon-folder-open" collapsedIcon="ui-icon-folder-collapsed">
                        <h:outputText value="#{node.name}" />
                    </p:treeNode>
                </p:tree>
            </p:fieldset>
        </h:form>
    </h:body>
</html>
```
## 6) Sample bean

I open second page like this:

```
    public void openCollectorTypeSelectDF(ActionEvent e) {
        Map<String, Object> options = new HashMap<>();
        options.put("resizable", true);
        options.put("draggable", true);
        options.put("contentWidth", 300);
        options.put("contentHeight", 600);
        options.put("modal", true);
        RequestContext.getCurrentInstance().openDialog("CollectorTypeSelectDF", options, null);
    }
```

When i click "ok" button,method "closeSelectDlg" was invoked

```
    public void closeSelectDlg(ActionEvent e) {
        RequestContext.getCurrentInstance().closeDialog(getSelectedNode().getData());
    }
```

But "dialogReturn" ajax listener was not invoked

```
<p:ajax event="dialogReturn" listener="#{collectorManager.onCollectorTypeChosen}" update="type" />
```

```
    public void onCollectorTypeChosen(SelectEvent event) {
        selection.setType((CollectorType) event.getObject());
    }
```

**Comment by tandraschko** [comment] 2017-10-17 14:06
duplicate of #1403

**Closed as completed by tandraschko** 2017-10-17 14:06 UTC
Labels: :lady_beetle: defect, Resolution: Duplicate
