### ISSUE TITLE
Calendar/DatePicker: Disabled or ReadOnly Mask breaks the page 

### ISSUE THREAD

**Issue by educalize** [primefaces/primefaces#7387] opened 2021-06-03 00:07 UTC
**Describe the defect**
When the p:calendar component has readonly or disabled properties set to true the action attribute of p:commandButton no longer works.

I reported similar issue in the following post. https://forum.primefaces.org/viewtopic.php?f=3&t=66983 which resulted in the following issue [https://github.com/primefaces/primefaces/issues/7362](url)

**Reproducer**
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/6588003/primefaces-test.zip)

**Environment:**
PF Version: 10.0
JSF + version: ALL
Affected browsers: ALL

Forum Post: [https://forum.primefaces.org/viewtopic.php?f=3&t=67098](url)

**To Reproduce**
1. Go to URL http://localhost:8080/primefaces-test-1.0-SNAPSHOT/index.xhtml
2. Click on button "Salvar" Save in my language
3. The action method should be executed.

**Expected behavior**
Show FacesMessage

**Example XHTML**
```<h:form id="form">
		
			<p:messages id="mensagem" showDetail="false" autoUpdate="true"/>
			
			<p:calendar id="dataVencimento" value="#{alunoMB.datnas}" pattern="dd/MM/yyyy" mask="true" locale="pt" readonly="true"/>
			
			<p:commandButton id="salvar" value="Salvar" icon="imagem-email-excluir" action="#{alunoMB.salvar}" />
								
			
		</h:form>
```

**Example Bean**
```
public void salvar() {

		FacesContext context = FacesContext.getCurrentInstance();
		FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Metódo chamado", null);
		context.addMessage("Método chamado", message);

		System.out.println("------------------------------------");

	}
```

**Comment by melloware** [comment] 2021-06-03 11:55
I can't reproduce.  Your example was not runnable.  Attached is an example that actually works and has no issues.
[pf-7387.zip](https://github.com/primefaces/primefaces/files/6591446/pf-7387.zip)

Unzip and run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml and you will see it works fine.

![image](https://user-images.githubusercontent.com/4399574/120641020-22299180-c441-11eb-9787-44ceffa50a2f.png)

**Comment by melloware** [comment] 2021-06-04 11:08
Closing until a reproducer can be provided.

**Comment by melloware** [comment] 2021-06-07 18:18
So I saw your note on the forums.  Are you saying that it is the `mask` that is breaking the code?  You didn't have a mask in your example?

**Comment by melloware** [comment] 2021-06-07 18:45
I need to apply the same fix for #7362 InputMask for Calendar/DatePicker if using a mask.

**Comment by educalize** [comment] 2021-06-08 20:21
Apparently the calendar and datpicker components are also having problems opening the date and hour and minute selection. Probably a related issue.

**Comment by melloware** [comment] 2021-06-08 20:47
I am sure its all the same issue.  I have no issues at all when no mask is used.  It has to be related to the mask.

**Closed as completed** 2021-06-09 13:12 UTC
Labels: :lady_beetle: defect, workaround

**Comment by educalize** [comment] 2021-06-09 19:08
I downloaded the source code from the master. Generated primefaces-11.0.0-SNAPSHOT.jar. I installed it in my project and the components still have problems, not opening the popup to select the date and other features such as selecting the hour and minute. The previous problem, which was a problem with the use of a mask, has apparently been solved. It remains these problems that I reported.

**Comment by melloware** [comment] 2021-06-09 19:26
Yep then you definitely have other unrelated issue.  Please create a PrimeFaces Test reproducer for me to debug that actually runs with `mvn clean jetty:run` or else there is nothing I can do.

**Comment by melloware** [comment] 2021-06-12 12:56
MonkeyPatch:

```javascript
if (PrimeFaces.widget.Calendar) {

    PrimeFaces.widget.Calendar.prototype.applyMask = function() {
        if (this.cfg.inline || this.input.is('[readonly]') || this.input.is(':disabled')) {
            return;
        }
        if (this.cfg.mask) {
            var maskCfg = {
                placeholder: this.cfg.maskSlotChar || '_',
                clearMaskOnLostFocus: this.cfg.maskAutoClear || true,
                clearIncomplete: this.cfg.maskAutoClear || true,
                autoUnmask: false
            };
            var pattern = new RegExp("m|d|y|h|s", 'i');
            var isAlias = pattern.test(this.cfg.mask);
            if (isAlias) {
                maskCfg.alias = 'datetime';
                maskCfg.inputFormat = this.cfg.mask;
            } else {
                maskCfg.mask = this.cfg.mask;
            }
            this.input.inputmask('remove').inputmask(maskCfg);
        }
    }
}

if (PrimeFaces.widget.DatePicker) {

    PrimeFaces.widget.DatePicker.prototype.applyMask = function() {
        if (this.cfg.inline || this.input.is('[readonly]') || this.input.is(':disabled')) {
            return;
        }
        if (this.cfg.mask) {
            var maskCfg = {
                placeholder: this.cfg.maskSlotChar || '_',
                clearMaskOnLostFocus: this.cfg.maskAutoClear || true,
                clearIncomplete: this.cfg.maskAutoClear || true,
                autoUnmask: false
            };
            var pattern = new RegExp("m|d|y|h|s", 'i');
            var isAlias = pattern.test(this.cfg.mask);
            if (isAlias) {
                maskCfg.alias = 'datetime';
                maskCfg.inputFormat = this.cfg.mask;
            } else {
                maskCfg.mask = this.cfg.mask;
            }
            this.input.inputmask('remove').inputmask(maskCfg);
        }
    }
}
```
