### ISSUE TITLE
DatePicker: maxdate/mindate causes popup not to work

### ISSUE THREAD

**Issue by brooksie** [primefaces/primefaces#5696] opened 2020-03-15 20:21 UTC
## 1) Environment
- PrimeFaces version: 8.0
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Not attempted
- Application server + version: wildfly-18.0.1.Final / Mojarra 2.3.9.SP04
- Affected browsers: Firefox, Edge

## 2) Expected behavior
Click into the datePicker field with either maxdate or mindate set and the DatePicker popup should occur.

## 3) Actual behavior
No date popup happens when clicking into the field on the web form

## 4) Steps to reproduce
Create maven project based on Jakarataee web project (use archetype: wildfly-jakartaee-webapp-archetype).
Add CDI support / web.xml / beans.xml
Copy index.xhtml and bean.java. Compile and build... 
Open webpage as supplied and click into datePicker fields.

## 5) Sample XHTML
```
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form>
            <p:panelGrid columns="2" >
                <p:outputLabel for="date1" value="Date" />
                <p:datePicker id="date1" value="#{bean.date1}" />
                <p:outputLabel for="date2" value="Max.Date" />
                <p:datePicker id="date2" value="#{bean.date2}" maxdate="#{bean.today}" />
                <p:outputLabel for="date3" value="Min.Date" />
                <p:datePicker id="date3" value="#{bean.date3}" mindate="#{bean.today}" />
            </p:panelGrid>
        </h:form>
    </h:body>
</html>

```
## 6) Sample bean

```
package mainpackage;

import java.io.Serializable;
import java.time.LocalDate;
import javax.annotation.PostConstruct;
import javax.inject.Named;
import javax.faces.view.ViewScoped;

/**
 *
 * @author sjbro
 */
@Named(value="bean")
@ViewScoped
public class Bean implements Serializable {

    private LocalDate date1;
    private LocalDate date2;
    private LocalDate date3;
    private LocalDate today;
    
    /** Creates a new instance of Bean */
    public Bean() {
    }
    
    @PostConstruct
    public void init() {
        today = LocalDate.now();
    }
    
    
    public LocalDate getDate1() {
        return date1;
    }

    public void setDate1(LocalDate date1) {
        this.date1 = date1;
    }

    public LocalDate getDate2() {
        return date2;
    }

    public void setDate2(LocalDate date2) {
        this.date2 = date2;
    }

    public LocalDate getDate3() {
        return date3;
    }

    public void setDate3(LocalDate date3) {
        this.date3 = date3;
    }

    public LocalDate getToday() {
        return today;
    }

    public void setToday(LocalDate today) {
        this.today = today;
    }   
}

```

**Comment by melloware** [comment] 2020-03-16 11:23
I can't reproduce your issue.  Here is my reproducer:
[pf-5696.zip](https://github.com/primefaces/primefaces/files/4339254/pf-5696.zip)


Run `mvn clean jetty:run-exploded -Pmojarra23` and navigate to http://localhost:8080/primefaces-test/test.xhtml

**Comment by brooksie** [comment] 2020-03-16 18:58
Hi. 
I'm still not able to get this to work on my PC using Wildfly 18.0.1.Attached is the project you sent, where I've amended the POM for Wildfly. I've also attached two screenshots - one where DatePicker (only) works fine; the other where DatePicker with maxdate/mindate doesn't.
The normal Primefaces showcase all works fine for me. 

I've also extended the example and added two Calendar fields - and the maxdate popup works OK for the calendar field (vs. not for DatePicker). I also separately tested if LocalDate vs. Date made any difference, but it didn't. 

I tried to install TomEE Plume to test the example directly, but struggled with the install and haven't [so far] got it working correctly on my PC (I'm certainly not an expert in this area!). 

I hope this helps to further identify the issue. Thank-you for looking.

**Comment by melloware** [comment] 2020-03-16 19:00
Your attachment did not come through...

**Comment by brooksie** [comment] 2020-03-16 19:10
![Test5](https://user-images.githubusercontent.com/4806551/76791861-abf82b00-67b9-11ea-8069-893d74d7a607.png)
![Test2](https://user-images.githubusercontent.com/4806551/76791864-ac90c180-67b9-11ea-9605-105d810e2bf2.png)
![Test1](https://user-images.githubusercontent.com/4806551/76791866-ac90c180-67b9-11ea-90fa-6edbbaba30e8.png)
[PF-5696-SJB-16Mar2020.zip](https://github.com/primefaces/primefaces/files/4339944/PF-5696-SJB-16Mar2020.zip)

**Comment by brooksie** [comment] 2020-03-16 19:14
Didn't mean to close this... reopening.

**Comment by melloware** [comment] 2020-03-16 19:17
So your changes to the pom.xml made this project no longer runnable?

I am using WildFly 14 currently with no issues.   Its possible something is wrong in 18.01 or that somehow the dependencies are messed up.  But running our Test project with the proper Mojarra 2.3 can't reproduce your issue.

**Comment by melloware** [comment] 2020-03-17 17:14
Going to close this until you can provide a reproducer we can debug.

**Comment by brooksie** [comment] 2020-03-18 20:57
Hi. 
I still have issues. I used your reproducer, slightly extended to include calendar as well as datePicker.
I tested it directly, without any changes to the POM, using just Maven to compile and with Jetty as recommended (so no NetBeans, no Wildfly).

When compiled with Mojarra23: DatePicker works; datePicker w/maxdate fails; Calendar works; calendar w/maxdate works. There is also a WARNING exception in the log, probably for THEME.css.
When compiled with Mojarra22: same.
When compiled with MyFaces23: Works, fails, works, fails... But there are also several java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
When compiles with MyFaces22: Works, fails, works, works... and no messages in the logs.

All logs are attached. 
The environment is:
C:\Users\sjbro>mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Users\sjbro\Documents\apache-maven-3.6.3\bin\..
Java version: 11, vendor: Oracle Corporation, runtime: C:\Java\jdk-11
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

C:\Users\sjbro>java -version
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

All the above was done with Firefox v74 browser. I also tried Edge and got similar - and also with Internet Explorer.
I'm at a loss to know why it should work for you and not for me. Any thoughts at what else could be different? Thanks.

[myfaces22 log.txt](https://github.com/primefaces/primefaces/files/4351277/myfaces22.log.txt)
[myfaces23 log.txt](https://github.com/primefaces/primefaces/files/4351278/myfaces23.log.txt)
[mojarra22 log.txt](https://github.com/primefaces/primefaces/files/4351279/mojarra22.log.txt)
[mojarra23 log.txt](https://github.com/primefaces/primefaces/files/4351280/mojarra23.log.txt)
[PFTest 18Mar2020.zip](https://github.com/primefaces/primefaces/files/4351293/PFTest.18Mar2020.zip)

**Comment by melloware** [comment] 2020-03-18 21:16
I will do some more testing. I will say the only difference I see is I am using JDK8 and that night explain that missing Java’s.xml. Class your are getting with MyFaces.

**Comment by melloware** [comment] 2020-03-19 13:44
OK I tested using Java8 and Java 11.

If you are using Java11 you need to add this to the pom.xml as these classes have been removed from the JDK.
```xml
		<dependency>
           <groupId>javax.xml.bind</groupId>
           <artifactId>jaxb-api</artifactId>
           <version>2.3.0</version>
        </dependency>
```

**JDK8**
myfaces22 - passed
myfaces23 -passsed
mojarra22 -passed
mojarra23 - passed

**JDK11**
myfaces22 - passed
myfaces23 -passsed
mojarra22 -passed
mojarra23 - passed

it is working 100% fine for me.

**Comment by brooksie** [comment] 2020-03-19 18:06
Thanks. Adding the extra dependency has made the four cases consistent, but unfortuantely the datapicker with maxdate (or mindate) still fails for me. The other cases pass. 
Inspecting the HTML, it looks like the code to invoke the popup is missing. Unfortunately my skill in JS and CSS is minimal :(
![Missing click event](https://user-images.githubusercontent.com/4806551/77097099-2d44fd00-6a08-11ea-9607-c0ce95eb0bca.png)

I am concerned at the io.EofException that looks to be related to theme.css from library primefaces-omega. This error appears intermittent, but I wonder if it is somehow related to the issue? Also, OMEGA should be working out of the box without any issues. Datepicker is a new component. Perhaps the objects datepicker needs are at the end of theme.css or referenced scripts??? Just hypothesizing..
Many thanks.
[mojarra23 log 19Mar2020 jdk13.0.1.txt](https://github.com/primefaces/primefaces/files/4356190/mojarra23.log.19Mar2020.jdk13.0.1.txt)

**Comment by tandraschko** [comment] 2020-03-19 18:10
the EOF are warnings because firefox cancels the requests as loading from disk cache is faster - there are topics in the forum.
In MyFaces 2.3 we handle the warning a bit nicer and skip logging stacktrace (at least in tomcat, can't remember if we did it for jetty)

**Comment by melloware** [comment] 2020-03-19 18:22
@brooksie are you only having this issue in Firefox?  I do all my testing in Chrome which could explain why I am not seeing your issue?

**Comment by melloware** [comment] 2020-03-19 18:26
I just tried with Firefox 72.0.2 no problem.

![image](https://user-images.githubusercontent.com/4399574/77101399-a08d4580-69ed-11ea-81ae-f7274f7de199.png)

**Comment by brooksie** [comment] 2020-03-19 19:08
It fails in Chrome, as well as Firefox, Edge and IE.

    On Thursday, 19 March 2020, 18:27:09 GMT, Melloware <notifications@github.com> wrote:  
 
 


I just tried with Firefox 72.0.2 no problem.

**Comment by melloware** [comment] 2020-03-19 19:09
OK i just tested in IE11, Edge, Chrome, and Firefox and all is working perfectly.

**Comment by brooksie** [comment] 2020-03-26 17:35
Hi again,
BINGO! I've identified that this is an **internationalization** issue.
When my computer's regional settings are set to US, it works!. When set to the UK, it fails. 
![UK regional settings](https://user-images.githubusercontent.com/4806551/77676974-f67e6200-6f86-11ea-8f8a-b4bcfc509662.png)
![US regional settings](https://user-images.githubusercontent.com/4806551/77676978-f7af8f00-6f86-11ea-965b-1805d40b4ee5.png)
Please reopen. Thanks.
NB. Also I think that <DatePicker value="#{...}" /> (default case) is not converting to LocalDate correctly by default. It's returning LocalDate = 0020-03-26 instead of 2020-03-26. Again, I suspect this is i18n-related.

**Comment by melloware** [comment] 2020-03-26 17:37
@christophs78 Any thoughts on this?

**Comment by christophs78** [comment] 2020-03-26 19:12
Can´t reproduce this within PF-Showcase:
![grafik](https://user-images.githubusercontent.com/10461942/77686843-d312e180-6f9d-11ea-89a6-4884d68ec8c4.png)

@brooksie : Can you test https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml?

Which browser do you use? (I tested with FF 74.0)

**Comment by melloware** [comment] 2020-03-26 20:04
I wonder if he is running his SERVER with that timezone not just the UI browser.  So its not a JS error its a Server side error with LocalDate.

**Comment by brooksie** [comment] 2020-03-26 20:15
It also works OK for me on Showcase - both the Date and the LocalDate versions. 
I concur with @melloware. When I run it, it's both SERVER and CLIENT that run on the same computer. It doesn't seem to matter which browser. Previously it's failed in Firefox, Chrome, IE and Edge. I'm also mostly using FF 74.0 64-bit. I used the reproducer and Jetty w/Mojarra23 in my tests earlier today.
But I spotted the original problem with WildFly 18 / Jakartaee 8 / PF8. The underlying Java JDK version is 13.0.1.

**Comment by melloware** [comment] 2020-03-26 20:17
Brooksie can you please test with both JDK 8 and with JDK 11 LTS.  Want to make sure this isn't some weird Java 13 bug.

**Comment by brooksie** [comment] 2020-03-26 22:49
The Java version doesn't make any difference. Nor does the browser. I've tested with JDK 8.241, JDK11, JDK13.0.1 and JDK14. I've also tested with Firefox, Chrome, Edge and IE. The tests all fail when the region is set to UK. The tests all pass with region set to US.

**Comment by christophs78** [comment] 2020-03-27 06:33
@brooksie:

1) Can you checkout and run PrimeFaces showcase in your local environment?

2) You said:
> NB. Also I think that (default case) is not converting to LocalDate correctly by default. It's returning LocalDate = 0020-03-26 instead of 2020-03-26. Again, I suspect this is i18n-related.
Where do you see this?

Do you talk about this?
![grafik](https://user-images.githubusercontent.com/10461942/77728619-26684c80-6ffd-11ea-8184-d3aee69e6f26.png)

3) Are there errors/warnings/... in the browser-console?

**Comment by melloware** [comment] 2020-03-28 21:03
@brooksie any updates for @christophs78 or myself?  We are still trying to reproduce this issue.

**Comment by brooksie** [comment] 2020-03-28 23:11
Hi... I've been testing lots of scenarios. 
My earlier comments about JDK8 were wrong (sorry for that). All the scenarios work OK for JDK8. This does seem to be an issue with JDK11 etc.  There's still a difference between region US and region UK.
After a fair amount of struggle, I've managed to get Showcase working with PF8 (not PF9-snapshot) and ALL versions of JDK and for both locales. I added the following to the POM to get Showcase to work for JDK11etc.....

        <dependency>
           <groupId>javax.xml.bind</groupId>
           <artifactId>jaxb-api</artifactId>
           <version>2.3.0</version>
        </dependency>
	<dependency>
	  <groupId>com.sun.xml.bind</groupId>
	  <artifactId>jaxb-core</artifactId>
	  <version>2.3.0</version>
	</dependency>
	<dependency>
	  <groupId>com.sun.xml.bind</groupId>
	  <artifactId>jaxb-impl</artifactId>
	  <version>2.3.0</version>
	</dependency>
	<dependency>
	    <groupId>com.sun.activation</groupId>
	    <artifactId>javax.activation</artifactId>
	    <version>1.2.0</version>
	</dependency>
Datepicker now functions correctly in Showcase when running on JDK8, 11 or 13. PFTest still works with US locale, but does _not_ work correctly with the UK locale.  Likewise with the LocalDate.toString() issue I reported. Here is screen shot. I don't see this issue at all in Showcase. The issue only shows itself in the UK locale with PFTest.
![PFTest - PF8 - JDK11 - UK](https://user-images.githubusercontent.com/4806551/77835800-4f492880-7148-11ea-81b8-fbf90dad17a6.png)
The PFTest code I've been using is here:
[PFTest 28Mar2020.zip](https://github.com/primefaces/primefaces/files/4398035/PFTest.28Mar2020.zip)
I run it with "mvn clean jetty:run-exploded -Pmojarra23"
I will continue to try an identify the essential difference between Showcase and PFTtest. 
Best wishes.

**Comment by christophs78** [comment] 2020-03-29 06:43
## PFTest
### Client
![grafik](https://user-images.githubusercontent.com/10461942/77843028-577d8400-7199-11ea-95ef-274cc38a5507.png)
![grafik](https://user-images.githubusercontent.com/10461942/77843077-cce95480-7199-11ea-8fd1-d2e04ac101a4.png)
### Server
![grafik](https://user-images.githubusercontent.com/10461942/77843427-71b96100-719d-11ea-982e-4dbe40a3108d.png)

## Showcase
### Client
![grafik](https://user-images.githubusercontent.com/10461942/77843262-b3e1a300-719b-11ea-9945-78ba05ac61c1.png)
### Server
![grafik](https://user-images.githubusercontent.com/10461942/77843351-94974580-719c-11ea-9cb0-716ef0d299e8.png)

**Comment by christophs78** [comment] 2020-03-29 07:18
Showcase sets
```
<locale-config>
    <default-locale>en</default-locale>
</locale-config>
```
in faces-config.xml. 

PFTest does not do this so it defaults to the system locale. And en_GB causes the issue.

**Comment by christophs78** [comment] 2020-03-29 07:36
I know where to continue my research. Will take some time because it seems to be a bit complicated.

**Comment by christophs78** [comment] 2020-03-29 07:57
When i remove default-locale from Showcase (or set it to en_GB)  it still works. What the hell?!?

**Comment by christophs78** [comment] 2020-03-29 08:04
Nailed it!
It´s related to the combination of `<default-locale>en_GB</default-locale>`and Java11.
With this combination the Showcase breaks too.

**Comment by christophs78** [comment] 2020-03-29 08:26
### minimal test
```
public static void main(String[] args) {
	LocalDate now = LocalDate.now();

	DateTimeFormatter formatterEN = DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT).withLocale(new Locale("en"));
	DateTimeFormatter formatterEN_GB = DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT).withLocale(new Locale("en_GB"));
	DateTimeFormatter formatterDE = DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT).withLocale(new Locale("de"));

	System.out.println("en: " + formatterEN.format(now));
	System.out.println("en_GB: " + formatterEN_GB.format(now));
	System.out.println("de: " + formatterDE.format(now));
}
```

### Java 8
en: 3/29/20
en_GB: 3/29/20
de: 29.03.20


### Java 11
en: 3/29/20
en_GB: 2020-03-29
de: 29.03.20

**Comment by brooksie** [comment] 2020-03-29 09:46
@christophs78,The minimal test results don't seen right to me, for either JDK8 or 11. The short form for en_GB should be 29/03/20 (or maybe 29/03/2020)
i.e. we follow the day-month-year convention, but with "/" instead of "."

    On Sunday, 29 March 2020, 09:27:00 BST, Christoph Straßer <notifications@github.com> wrote:  
 
 


minimal test
public static void main(String[] args) {
	LocalDate now = LocalDate.now();

	DateTimeFormatter formatterEN = DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT).withLocale(new Locale("en"));
	DateTimeFormatter formatterEN_GB = DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT).withLocale(new Locale("en_GB"));
	DateTimeFormatter formatterDE = DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT).withLocale(new Locale("de"));

	System.out.println("en: " + formatterEN.format(now));
	System.out.println("en_GB: " + formatterEN_GB.format(now));
	System.out.println("de: " + formatterDE.format(now));
}

Java 8

en: 3/29/20
en_GB: 3/29/20
de: 29.03.20

Java 11

en: 3/29/20
en_GB: 2020-03-29
de: 29.03.20

**Comment by christophs78** [comment] 2020-03-29 10:21
@brooksie - which output do you get on your machine, when you run this minimal test against Java 8 and 11?

**Comment by brooksie** [comment] 2020-03-29 11:56
I get the same as you... but for 
.withLocale(new Locale("en", "GB")) or for 
.withLocale(Locale.getDefault())
it returns 29/03/2020! and Locale.getDefault() returns "en_GB"!  As you said earlier.. What the...!
```
en: 3/29/20
en_GB: 2020-03-29
de: 29.03.20
Locale(en,GB):29/03/2020
Locale(getDefault()):29/03/2020
 ===> Locale.getDefault() returns en_GB
Locale.UK:29/03/2020
```
```
LocalDate now = LocalDate.now();

        DateTimeFormatter formatterEN = DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT).withLocale(new Locale("en"));
        DateTimeFormatter formatterEN_GB = DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT).withLocale(new Locale("en_GB"));
        DateTimeFormatter formatterDE = DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT).withLocale(new Locale("de"));

        System.out.println("en: " + formatterEN.format(now));
        System.out.println("en_GB: " + formatterEN_GB.format(now));
        System.out.println("de: " + formatterDE.format(now));

        DateTimeFormatter fmt1 = DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT).withLocale(new Locale("en", "GB"));
        System.out.println("Locale(en,GB):" + now.format(fmt1));

        DateTimeFormatter fmt2 = DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT).withLocale(Locale.getDefault());
        System.out.println("Locale(getDefault()):" + now.format(fmt2));
        System.out.println(" ===> Locale.getDefault() returns " + Locale.getDefault());

        DateTimeFormatter fmt3 = DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT).withLocale(Locale.UK);
        System.out.println("Locale.UK:" + now.format(fmt3));
```
For a bit of fun, I decided to try "en_US" and Locale("en", "US") and saw a similar issue. (2020-03-29 vs 3/29/20). It's almost as though 2020-03-29 is the default when the locale isn't recognised, perhaps???

**Comment by melloware** [comment] 2020-03-29 12:49
@brooksie Isn't the locale "en-GB" not "en_GB" ??? 
https://www.oracle.com/java/technologies/javase/jdk11-suported-locales.html

**Comment by christophs78** [comment] 2020-03-29 14:38
en-GB vs en_GB does not make a difference.

### At least i figured out a work-around
```
<p:outputLabel for="date2" value="Max.Date" />
<p:datePicker id="date2" value="#{testView.date2}" maxdate="#{testView.today}" pattern="MM/dd/yy" />
<p:outputLabel for="date3" value="Min.Date" />
<p:datePicker id="date3" value="#{testView.date3}" mindate="#{testView.today}" pattern="MM/dd/yy" />
```
Adding the pattern explicit helps.

### Some more details
```
LocalDate now = LocalDate.now();

FormatStyle formatStyle = FormatStyle.SHORT;

Locale localeEN = new Locale("en");
Locale localeEN_GB = new Locale("en_GB"); //or en-GB (same result)
Locale localeEN_GB2 = new Locale("en", "GB"); //or en-GB (same result)
Locale localeDE = new Locale("en");

DateTimeFormatter formatterEN = DateTimeFormatter.ofLocalizedDate(formatStyle).withLocale(localeEN);
DateTimeFormatter formatterEN_GB = DateTimeFormatter.ofLocalizedDate(formatStyle).withLocale(localeEN_GB);
DateTimeFormatter formatterEN_GB2 = DateTimeFormatter.ofLocalizedDate(formatStyle).withLocale(localeEN_GB2);
DateTimeFormatter formatterDE = DateTimeFormatter.ofLocalizedDate(formatStyle).withLocale(localeDE);

System.out.println("en: " + formatterEN.format(now));
System.out.println("en_GB: " + formatterEN_GB.format(now));
System.out.println("en_GB2: " + formatterEN_GB2.format(now));
System.out.println("de: " + formatterDE.format(now));

String patternEN = DateTimeFormatterBuilder.getLocalizedDateTimePattern(formatStyle, null, IsoChronology.INSTANCE, localeEN);
String patternEN_GB = DateTimeFormatterBuilder.getLocalizedDateTimePattern(formatStyle, null, IsoChronology.INSTANCE, localeEN_GB);
String patternEN_GB2 = DateTimeFormatterBuilder.getLocalizedDateTimePattern(formatStyle, null, IsoChronology.INSTANCE, localeEN_GB2);
String patternDE = DateTimeFormatterBuilder.getLocalizedDateTimePattern(formatStyle, null, IsoChronology.INSTANCE, localeDE);

System.out.println("Pattern en: " + patternEN);
System.out.println("Pattern en_GB: " + patternEN_GB);
System.out.println("Pattern en_GB2: " + patternEN_GB2);
System.out.println("Pattern de: " + patternDE);
```

Result with Java 11 (or newer)
```
"C:\Program Files\AdoptOpenJDK\jdk-14.0.0.36-hotspot\bin\java.exe" "-javaagent:F:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1\lib\idea_rt.jar=61759:F:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1\bin" -Dfile.encoding=UTF-8 -classpath D:\temp\LocalDate\out\production\LocalDate Main
en: 3/29/20
en_GB: 2020-03-29
en_GB2: 29/03/2020
de: 3/29/20
Pattern en: M/d/yy
Pattern en_GB: y-MM-dd
Pattern en_GB2: dd/MM/y
Pattern de: M/d/yy
```

Result with Java 8
```
"C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\bin\java.exe" "-javaagent:F:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1\lib\idea_rt.jar=61770:F:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\charsets.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\access-bridge-64.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\cldrdata.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\dnsns.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\jaccess.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\localedata.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\nashorn.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\sunec.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\sunjce_provider.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\sunmscapi.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\sunpkcs11.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\zipfs.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\jce.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\jsse.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\management-agent.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\resources.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\rt.jar;D:\temp\LocalDate\out\production\LocalDate" Main
en: 3/29/20
en_GB: 3/29/20
en_GB2: 29/03/20
de: 3/29/20
Pattern en: M/d/yy
Pattern en_GB: M/d/yy
Pattern en_GB2: dd/MM/yy
Pattern de: M/d/yy
```

With Java 8 DateTimeFormatter and and DateTimeFormatterBuilder seem to be in sync. (Year as two digits --> yy).
Java 11 and newer only deliver one y as year-pattern which causes issues one the client-side. (datepicker-js)
And this only for en_GB (or en-GB).

From my side i´m done. I really invested a heavy amount of time into this issue.

**Comment by melloware** [comment] 2020-03-29 14:43
@christophs78 Excellent work.  So to me this sounds like a JDK11+ issue with their GB locale not being in sync.  You have provided a workaround and now as I see this is not a Primefaces issue any objection to me closing this ticket?

**Comment by christophs78** [comment] 2020-03-29 15:10
No objection. Please close the ticket.

**Closed as completed** 2020-03-29 15:57 UTC
Labels: Resolution:  Wontfix

**Comment by brooksie** [comment] 2020-03-29 16:13
Ok to close. I appreciate the effort you guys have put into this. Thank-you. We've all spend a considerable amount of time on this.
Just one last thought... If the locale had been "de_DE", the same problem as "en_GB" occurs... so it suggests that this issue is related to any locale which is more than just a language code. 
```
Pattern de: dd.MM.yy
Pattern de_DE: y-MM-dd
```
Either way the workaround (and it is only a workaround) is to always include a pattern - that solves both the non-appearing popup and the incorrectly converted LocalDate. 
Thanks again.

**Comment by melloware** [comment] 2020-03-29 17:50
Your best bet would be to open a Jdk issue on OpenJDk.

**Comment by christophs78** [comment] 2020-03-29 18:07
Yep.

My last input to this:

```
public static void main(String[] args) {
	LocalDate now = LocalDate.now();

	FormatStyle formatStyle = FormatStyle.SHORT;

	Locale localeEN = new Locale("en");
	Locale localeEN_GB = new Locale("en", "GB");
	Locale localeDE = new Locale("de");
	Locale localeDE_AT = new Locale("de", "AT");

	DateTimeFormatter formatterEN = DateTimeFormatter.ofLocalizedDate(formatStyle).withLocale(localeEN);
	DateTimeFormatter formatterEN_GB = DateTimeFormatter.ofLocalizedDate(formatStyle).withLocale(localeEN_GB);
	DateTimeFormatter formatterDE = DateTimeFormatter.ofLocalizedDate(formatStyle).withLocale(localeDE);
	DateTimeFormatter formatterDE_AT = DateTimeFormatter.ofLocalizedDate(formatStyle).withLocale(localeDE_AT);

	System.out.println("en: " + formatterEN.format(now));
	System.out.println("en_GB: " + formatterEN_GB.format(now));
	System.out.println("de: " + formatterDE.format(now));
	System.out.println("de_AT: " + formatterDE_AT.format(now));

	String patternEN = DateTimeFormatterBuilder.getLocalizedDateTimePattern(formatStyle, null, IsoChronology.INSTANCE, localeEN);
	String patternEN_GB = DateTimeFormatterBuilder.getLocalizedDateTimePattern(formatStyle, null, IsoChronology.INSTANCE, localeEN_GB);
	String patternDE = DateTimeFormatterBuilder.getLocalizedDateTimePattern(formatStyle, null, IsoChronology.INSTANCE, localeDE);
	String patternDE_AT = DateTimeFormatterBuilder.getLocalizedDateTimePattern(formatStyle, null, IsoChronology.INSTANCE, localeDE_AT);

	System.out.println("Pattern en: " + patternEN);
	System.out.println("Pattern en_GB: " + patternEN_GB);
	System.out.println("Pattern de: " + patternDE);
	System.out.println("Pattern de_AT: " + patternDE_AT);
}
```

Java 8:
```
"C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\bin\java.exe" "-javaagent:F:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1\lib\idea_rt.jar=63636:F:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\charsets.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\access-bridge-64.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\cldrdata.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\dnsns.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\jaccess.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\localedata.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\nashorn.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\sunec.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\sunjce_provider.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\sunmscapi.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\sunpkcs11.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\ext\zipfs.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\jce.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\jsse.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\management-agent.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\resources.jar;C:\Program Files\zulu8.31.0.1-jdk8.0.181-win_x64\jre\lib\rt.jar;D:\temp\LocalDate\out\production\LocalDate" Main
en: 3/29/20
en_GB: 29/03/20
de: 29.03.20
de_AT: 29.03.20
Pattern en: M/d/yy
Pattern en_GB: dd/MM/yy
Pattern de: dd.MM.yy
Pattern de_AT: dd.MM.yy
```

Java 14:
```
"C:\Program Files\AdoptOpenJDK\jdk-14.0.0.36-hotspot\bin\java.exe" "-javaagent:F:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1\lib\idea_rt.jar=63651:F:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1\bin" -Dfile.encoding=UTF-8 -classpath D:\temp\LocalDate\out\production\LocalDate Main
en: 3/29/20
en_GB: 29/03/2020
de: 29.03.20
de_AT: 29.03.20
Pattern en: M/d/yy
Pattern en_GB: dd/MM/y
Pattern de: dd.MM.yy
Pattern de_AT: dd.MM.yy
```

IMO OpenJDK-Issues:
- Why do we get 4-digits-year for en_GB?
- Why contains the pattern only one "y"?

**Comment by melloware** [comment] 2020-05-24 13:45
Documented here on how to do set a global date pattern: https://primefaces.github.io/primefaces/8_0/#/core/globalattributes?id=global-attributes

**Comment by GedMarc** [comment] 2020-10-09 09:23
Ok I think I get it now, en_GB is actually one 'y' not a 4 year, this is a fix between JDK 8 and JDK 12, it's not a regression but a fix  to the standard - 

@christophs78  Are you running this with a module-info file or straight old classpath mode?

**Comment by christophs78** [comment] 2020-10-09 10:10
> @christophs78 Are you running this with a module-info file or straight old classpath mode?

I tried this with a new blank Java-project with IntelliJ on Java14. Whatever this does automatically.
Do you think this make a difference for this issue?

**Comment by melloware** [comment] 2020-10-10 14:59
Also this ticket from @blutorange addresses this issue at last with some of our conversions in code as he handles 1 letter year etc: https://github.com/primefaces/primefaces/issues/6257

But I still think the underlying problem is in `f:convertDateTime` and JDK11+ for these.
