### ISSUE TITLE
h:link in menuitem of panelmenu causes "ghost" links

### ISSUE THREAD

**Issue by dpassler** [primefaces/primefaces#1259] opened 2016-03-23 07:11 UTC
When i have <p:panelMenu> and inside this panelMenu i have any <p:menuItem> and inside the menuItem i have <h:link> then it causes rendering of "ghost" menu links (with no text and link href "#")

**Comment by tandraschko** [comment] 2017-10-16 20:19
Will close it for now as there is no information how the reproduce it.
If the issue is still there in 6.1 or 6.2-SNAPSHOT, please create new issue with all informations requested by our issue template.

**Closed as completed by tandraschko** 2017-10-16 20:19 UTC
Labels: :lady_beetle: defect, Resolution: Invalid
