### ISSUE TITLE
Datatable: (scrollable): size column size calculation defect for percentage-width or no width given

### ISSUE THREAD

**Issue by regenduft** [primefaces/primefaces#5014] opened 2019-07-22 15:15 UTC
Version: Primefaces 6.2.21

## 2) Expected behavior

when no width given, all columns should have same size and be distributed equally over the available scrollWidth

when width="30%", this should be 30% and not 30px!

## 3) Actual behavior

since commit https://github.com/primefaces/primefaces/commit/852741bf1376fc8e966441bffc9a82e80c601b15 to solve issue https://github.com/primefaces/primefaces/issues/4801

column width is NOT calculated correctly anymore, if NOT using box-sizing:border-box

- 30% is interpreted as 30px

- and when no width given, its distributed over the window-width instead of the given scrollWidth

- and columns on the left are small and further right columns get wider

## 4) Steps to reproduce

any datatable with scrollable=true

## 5) Sample XHTML

Primefaces 6.2.21 and 

`<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui" >

	<f:view contentType="text/html; charset=utf-8" >

		<h:head></h:head>

		<h:body>

		   <h3>Vertical</h3>
    <p:dataTable var="car" value="#{testBean.cars}" scrollable="true" scrollWidth="600px" scrollHeight="150">
        <p:column headerText="Id" footerText="Id" width="20%">
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Brand" footerText="Brand" >
            <h:outputText value="#{car.brand}" />
        </p:column>
        <p:column headerText="Year" footerText="Year" >
            <h:outputText value="#{car.year}" />
        </p:column>
        <p:column headerText="Color" footerText="Color" width="30%">
            <h:outputText value="#{car.color}" />
        </p:column>
    </p:dataTable>

		   <h3>Horizontal and Vertical</h3>
    <p:dataTable var="car" value="#{testBean.cars}" scrollable="true" scrollWidth="50%" scrollHeight="150">
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:column headerText="Id" footerText="Id" >
            <h:outputText value="#{car.id}" />
        </p:column>
    </p:dataTable>

    </h:body>

	</f:view>

</html>
`

## 6) Sample bean

use the example bean https://www.primefaces.org/showcase/ui/data/datatable/scroll.xhtml

**Comment by regenduft** [comment] 2019-07-22 15:16
workaround:

`if (PrimeFaces && PrimeFaces.widget && PrimeFaces.widget.DataTable && PrimeFaces.widget.DataTable.prototype) {
	PrimeFaces.widget.DataTable.prototype.setOuterWidth = function(element, width) {element.width(width)};
}`

**Comment by regenduft** [comment] 2019-07-22 15:19
I am using a theme WITHOUT box-sizing: border-box 

when enabling box-sizing: border-box, it works better, but still incorrect i.e. the columns further on the right are still wider etc

**Comment by melloware** [comment] 2019-07-22 18:22
@mertsincan can you investigate as this looks like a regression issue?

**Comment by torbenw** [comment] 2019-07-26 09:46
Do you think this could be fixed in the 6.2.23 release?

**Comment by melloware** [comment] 2019-08-01 19:04
@regenduft You workaround definitely works for me.  I will report this in my PRO account.

**Comment by SimonePadovan** [comment] 2019-11-11 13:03
Has this been fixed in 7.0.9 version ? thanks

**Comment by melloware** [comment] 2019-11-11 13:16
Yes its in Elite 7.0.6 and higher.

**Comment by SimonePadovan** [comment] 2019-11-11 13:45
I'm using 7.0.8 and still have this problem....

**Comment by melloware** [comment] 2019-11-11 13:49
Then yours' might be a different problem.   Please create a reproducer using the PrimeFaces Test project: https://github.com/primefaces/primefaces-test

**Comment by SimonePadovan** [comment] 2019-11-12 07:24
Thanks for your answer, i did what you suggested and noticed that the problem happens only in combination with ultima-theme. So i opened an issue in primefaces ultima forum.
thanks

**Comment by SimonePadovan** [comment] 2019-11-19 12:47
@mertsincan can you please investigate this problem happening only using ultima theme?

**Comment by SimonePadovan** [comment] 2019-11-26 13:55
Hi, i reallized that the problem is caused by this line in all ultima theme.css:
> * {  -moz-box-sizing: border-box;  -webkit-box-sizing: border-box;  box-sizing: border-box; }
I opened an issue in primefaces ultima theme by without answer....could you please telle me how to solve this problem ? Is it save to remove this line ? thanks

**Comment by regenduft** [comment] 2019-11-26 14:15
this is not a theming issue - this is a primefaces issue that was introduced with commit https://github.com/primefaces/primefaces/commit/852741bf1376fc8e966441bffc9a82e80c601b15

in this commit, instead of
` headerCol.width(width);`
the code is now 
`$this.setOuterWidth(footerCol, width);`

the source code of this.setOuterWidth was

```
        var diff = element.outerWidth() - element.width();
        element.width(parseFloat(width) - diff);
```

with commit https://github.com/primefaces/primefaces/commit/3f37ce9c5e954669d0e474b9514bd63453883a87 the problem was resolved for the old themes without box-sizing:border-box, now the method this.setOuterWidth is:

   ```
     if (element.css('box-sizing') === 'border-box') { // Github issue: #5014
            var diff = element.outerWidth() - element.width();
            element.width(parseFloat(width) - diff);
        }
        else {
            element.width(width);
        }
```

The problem is the parseFloat(width) - this means that you cannot longer use 30% - or you may still use 30% but it will be interpreted as 30px obviously because parseFloat just removes all letters.

For a workaround you cannot just overwrite 

`PrimeFaces.widget.DataTable.prototype.setOuterWidth = function(element, width) {element.width(width)}; }`

because for border-box, a more complicated calculation is necessary.

I am not sure, if this can be solved. Maybe with a css expression like 

`PrimeFaces.widget.DataTable.prototype.setOuterWidth = function(element, width) {
var diff = element.outerWidth() - element.width();
element.style.width('calc('+width+'% - ' + diff + 'px)' )}; 
}`


probably its easier to disable box-sizing:border-box for the specific element, but thats a question for your theme designer

**Comment by SimonePadovan** [comment] 2019-11-26 14:37
Thank you very much regenduft !
I'm simple using Ultima theme (we don't have a theme designer). With your workaround works partially, since header column sizes and body sizes become different. We hope primefaces will solve this problem

**Comment by SimonePadovan** [comment] 2019-11-26 14:42
one more thing how can i disable box-sizing:border-box for all datatables via css ?

**Comment by mertsincan** [comment] 2020-01-24 06:58
Hi @regenduft,
> The problem is the parseFloat(width) - this means that you cannot longer use 30% - or you may still use 30% but it will be interpreted as 30px obviously because parseFloat just removes all letters.
- No, the outerWidth() and width() always return float numbers.
> I'm simple using Ultima theme (we don't have a theme designer). With your workaround works partially, since header column sizes and body sizes become different.
- Could you please attach your forum issue?
> one more thing how can i disable box-sizing:border-box for all datatables via css ?
- Maybe, you can try;

```
.ui-datatable,
.ui-datatable * {
   -moz-box-sizing: content-box;
    -webkit-box-sizing: content-box;
    box-sizing: content-box;
}
```
Best Regards

**Comment by fanste** [comment] 2020-09-28 13:34
There are still problems with the outer-width calculation with `box-sizing: border-box`. And @regenduft is also right, with his statement that %-values are not correctly considered.

**1st problem**
`fixColumnWidths` gets the width of the column either from the CSS property `width` or using the jQuery method `width()`. While the latter one returns a unit-less pixel value, the first one returns what ever was set using the style property. This may be `%`, `em`, `px`, ... and therefore `parseFloat(...)` is simply wrong.

**2nd problem**
`setOuterWidth` uses jQuery `width(...)` to set the outer width of the column. In case of `box-sizing == border-box` the method calculates border + padding (`outerWidth() - width()`) and substracts that value from the given width. Then it set the width of the column using `width`. As the jQuery manual states: `Note that .width("value") sets the content width of the box regardless of the value of the CSS box-sizing property.`

That means, that we substract `border+padding` from the content-width and set that value as the content-width again, which is effectivally smaller than before.

e.g.: Column has 1px border on the left and right side. It has a padding of 10px on the left and right side. The content-width is 50px. That makes an outer-width of 72px.
 - jQuery width() => 50px
 - jQuery outherWidth() => 72px
 - outerWidth - width => 22px (border+padding)
 - width - (border+padding) =>28px
 - new content-width = 28px
 - new outerWidth = 50px
 - => column got smaller

You can see the effect `and columns on the left are small and further right columns get wider` reported by @regenduft on the screenshot:
![grafik](https://user-images.githubusercontent.com/3531183/94438877-f8c4b180-019f-11eb-9888-5704d081519d.png)

This scrollable datatable uses PF 8.


**possible fix**
The correct way should be to substract `border+padding` from the width if it was directly retrieved from the CSS property.

I will run some tests and try to find a solution.

**Comment by fanste** [comment] 2020-09-29 11:59
PR #6370 

I tested it with a normal scrollable table and a frozen-column table. Seems fine so far.

Side note: a `width` including the unit will be handled correctely - except `%`. Those values will use the scrollWidth as a reference, because thats how browsers work. Maybe we should convert %-values to px-values using the width of `.ui-datatable`? But all other units like `em`, `vw`, ... will work.

**Closed as completed** 2021-02-22 08:34 UTC
Labels: :lady_beetle: defect, 7.0.6, 6.2.23, pending-review
