### ISSUE TITLE
Focus: Implicit focus not set for SelectOneMenu as first item

### ISSUE THREAD

**Issue by i4eneco** [primefaces/primefaces#10770] opened 2023-10-04 11:40 UTC
### Describe the bug

If the first input-element of a form is p:selectOneMenu the focus will not (visibly) be set to this item. The focus will however be set to an inputElement with tabIndex="-1" and will not be visibly displayed.
You can use <p:focus context="..." /> or no <p:focus> to easily reproduce the bug.
Possibly bugfix:  I temporarily overwrote core.js focus: function() with the two following changes:
1.) explicitly put the "right" selectonemenu item to the selector and disabled the "wrong" selectonemenu item by filtering tabindex=-1:
var selector = '.ui-selectonemenu-label.ui-inputfield:visible, :not(:submit):not(:button):input:visible:enabled[name]:not([tabindex=\'-1\'])';
2.) uncommented the filter: var inputs = elements; //.filter(":input");

### Reproducer

[primefaces-bug.zip](https://github.com/primefaces/primefaces/files/12802736/primefaces-bug.zip)
after opening index.xhtml the focus will not be set to p:selectOneMenu (you can also not use p:focus and the same thing happens)

### Expected behavior

When opening a page with p:selectOneMenu as first element of the form, I want the focus to be on exactly on p:selectOneMenu when using no p:focus element oder <p:focus context="..." />

### PrimeFaces edition

Community

### PrimeFaces version

13.0.1

### Theme

Ultimate

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment] 2023-10-04 12:41
@i4eneco can you check if this is a duplicate of https://github.com/primefaces/primefaces/issues/10721 ???

**Comment by melloware** [comment] 2023-10-04 12:47
Its not a duplicate. Runnable reproducer:
[pf-10770.zip](https://github.com/primefaces/primefaces/files/12803453/pf-10770.zip)

**Comment by melloware** [comment] 2023-10-04 12:53
Yep it does!

**Closed as completed** 2023-10-04 13:47 UTC
Labels: :lady_beetle: defect
