### ISSUE TITLE
SelectCheckboxMenu: Option to have multiple columns

### ISSUE THREAD

**Issue by arunvc** [primefaces/primefaces#7406] opened 2021-06-10 07:12 UTC
**Description**

selectCheckboxMenu supports just single column, would be nice to have multiple columns like selectOneMenu 

**Sample**
```xml
<p:selectCheckboxMenu ... var="v">
...
                <p:column >
                  <h:outputText value="#{v.title1}" />
                </p:column>
                <p:column>
                  <h:outputText value="#{v.title2}" />
                </p:column>          
               
</p:selectCheckboxMenu>   
```

**Comment by melloware** [comment] 2021-06-10 18:11
Duplicate of https://github.com/primefaces/primefaces/issues/4696

**Closed as completed by melloware** 2021-06-10 18:11 UTC
Labels: Resolution: Duplicate
