### ISSUE TITLE
Graphic Image: Since PF 12 `ismap` attribute is rendered and causing invalid HTML

### ISSUE THREAD

**Issue by Bukama** [primefaces/primefaces#9373] opened 2022-11-03 11:50 UTC
### Describe the bug

Since Primefaces 12 the [Graphic Image](https://www.primefaces.org/showcase/ui/multimedia/graphicImage.xhtml?jfwid=f6fca) renderes a `ismap` attribute with the values `true` or `false`, resulting in invalid HTML:

![pf_img_ismap](https://user-images.githubusercontent.com/4354359/199713579-08c28d78-bd14-4995-b8a8-a3e04b215243.PNG)

While the `ismap` attribute is allowed on the image-tag and it is a boolean type, the correct syntax is to only add `ismap` when the image is a server side map and don't use it, when the image is not map, see this [example from W3C](https://www.w3schools.com/tags/att_img_ismap.asp):

```
<a href="/action_page.php">
  <img src="w3html.gif" alt="W3Schools.com" width="100" height="132" ismap>
</a>
```

If I've read the commit history right, the change was introduced with [commit f08ba1e3d57cc82b1a07f3a4ebb2098eec532e15](https://github.com/primefaces/primefaces/commit/f08ba1e3d57cc82b1a07f3a4ebb2098eec532e15) in PR #8772 to fix #7943.

### Reproducer

Check showcase of [Graphic Image](https://www.primefaces.org/showcase/ui/multimedia/graphicImage.xhtml?jfwid=f6fca)

### Expected behavior

* The `ismap` attribute is only rendered when true
* The `ismap` attribute is rendered as definied by the W3C, meaning without a value

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

All

### JSF version

2.2

### Java version

8

### Browser(s)

all

**Comment by melloware** [comment] 2022-11-03 11:51
Duplicate of: https://github.com/primefaces/primefaces/issues/9369

**Comment by Bukama** [comment] 2022-11-03 11:53
Oh sorry, I had the task to create an issue laying on my desk for about two weeks and didn't double checked if there was an issue created in the meantime :(

**Comment by melloware** [comment] 2022-11-03 11:54
No problem!

**Comment by melloware** [comment] 2022-11-03 11:55
I better test the TRUE scenario I fixed the false scenario.

**Comment by melloware** [comment] 2022-11-03 12:32
This PR makes it render correctly with false and true.

```xml
	<img id="j_id_90" src="/showcase/javax.faces.resource/images/nature/nature4.jpg.xhtml?ln=demo">
	<img id="j_id_91" src="/showcase/javax.faces.resource/images/nature/nature4.jpg.xhtml?ln=demo" ismap="ismap">
```

` ismap="ismap"` is the JSF XHTML way of rendering booleans and still passes the NuHTML checker as valid.

**Closed as completed** 2022-11-03 12:48 UTC
Labels: :lady_beetle: defect
