### ISSUE TITLE
DataTable Paginator: use standard layout for selectOneMenu created for rowsPerPageTemplate

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#7025] opened 2021-02-21 20:50 UTC
The selectOneMenu created for rowsPerPageTemplate looks as follows:

![Screenshot from 2021-02-21 21-45-38](https://user-images.githubusercontent.com/10051373/108638253-9fcb2200-748e-11eb-96ad-6462914076f0.png)

However, it should look consistently with the other selectOneMenus:

![Screenshot from 2021-02-21 21-45-11](https://user-images.githubusercontent.com/10051373/108638286-c0937780-748e-11eb-994e-847c06d147d2.png)

**Comment by melloware** [comment] 2021-02-21 21:28
Duplicate of #2270

**Closed as completed** 2021-02-21 21:29 UTC
Labels: Resolution: Duplicate

**Comment by tuerker** [comment] 2021-02-21 21:31
@melloware: it did not get the point. it does not look good, it should be really fixed.

**Comment by tuerker** [comment] 2021-02-21 21:31
is there a reason why not do that?

**Comment by melloware** [comment] 2021-02-21 21:35
That ticket #2270 is still open so I closed this as a duplicate.  The other ticket still being open means someone is free to work on it and provide a PR.

**Comment by tuerker** [comment] 2021-02-21 21:37
ok. i thought it might be a quick issue for the experts.

**Comment by melloware** [comment] 2021-02-21 21:57
Unfortunately it's not a quick or easy fix or I would definitely do it.

**Comment by tuerker** [comment] 2021-02-21 22:01
Thanks for the explanation and all your great work.
