### ISSUE TITLE
FileUpload: throws RuntimeExceptions when chunked mode is used

### ISSUE THREAD

**Issue by wal-jan** [primefaces/primefaces#7641] opened 2021-07-28 12:57 UTC
**Describe the defect**
1. Chunked FileUpload throws RuntimeException if `UPLOADER=native`.
```
java.util.NoSuchElementException
at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1495)
at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
at java.base/java.util.Collections$3.nextElement(Collections.java:5267)
at org.primefaces.component.fileupload.NativeFileUploadDecoder.lambda$getUploadDirectory$3(NativeFileUploadDecoder.java:79)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
at java.base/java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:397)
at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
at org.primefaces.component.fileupload.NativeFileUploadDecoder.getUploadDirectory(NativeFileUploadDecoder.java:82)
```

2. Chunked FileUpload throws NPE if `UPLOADER=comons` and
`<init-param><param-name>uploadDirectory</param-name>...</init-param>` is not configured in `web.xml`
```
java.lang.NullPointerException: Cannot invoke "java.io.File.getAbsolutePath()" because the return value of "org.primefaces.webapp.MultipartRequest.getUploadDirectory()" is null
	at org.primefaces.component.fileupload.CommonsFileUploadDecoder.getUploadDirectory(CommonsFileUploadDecoder.java:80)
	at org.primefaces.component.fileupload.CommonsFileUploadDecoder.getUploadDirectory(CommonsFileUploadDecoder.java:36)
```
**Reproducer**
Former issue cannot be reproduced with primefaces-test project, since jetty adds some attributes to the request which hide the bug.

Reproducer for latter issue.
[PF-7617-chunked.zip](https://github.com/primefaces/primefaces/files/6893161/PF-7617-chunked.zip)

**Environment:**
 - PF Version: _10.0_
 - JSF + version: _ALL_
 - Affected browsers: _ALL_

**To Reproduce**
1. Start server `mvn jetty:run`
2. Go to 'localhost:8080/primefaces-test/'
3. Click 'choose'
4. Select any file bigger than 1MB
5. Click 'upload'
6. See error in server log

**Expected behavior**
RuntimeExceptions should not be thrown. Files should be uploaded without error.

**Example XHTML**
```html
<h:form id="frmTest">
    <p:fileUpload id="fileupload" mode="advanced" maxChunkSize="65536" .../>
</h:form>
```

**Example Bean**
see reproducer

**Comment by wal-jan** [comment] 2021-07-28 12:58
I'll provide a PR with corrected FileUpload handling and some more integration test.

**Comment by melloware** [comment] 2021-07-28 13:07
I assigned it to you. Thanks!

**Comment by Rapster** [comment] 2021-07-28 18:13
Can't reproduce your first problem with native uploader

**Comment by wal-jan** [comment] 2021-07-28 18:41
The bug is in
https://github.com/primefaces/primefaces/blob/97e4308f0eca1a5b07f4dbb34341adc8e7c3bed2/primefaces/src/main/java/org/primefaces/component/fileupload/NativeFileUploadDecoder.java#L78-L79
`Stream.of(request.getAttributeNames())` sets up a stream of a *single element* (in this case the element is of type `Enumeration<String>`) In the next line `o,nextElement()` only succeeds if the enumeration is not empty. You need to create a file upload request without any request attributes. This is possible in primefaces-integration-test project.

**Comment by Rapster** [comment] 2021-07-28 19:03
And how do you create a request without any request attributes?

**Comment by wal-jan** [comment] 2021-07-28 19:17
primefaces-integration-test project utilizes TomEE. Looks like TomEE does not add request attributes (in contrary to Jetty). And the Reproducer does not set request attributes at all.

**Closed as completed** 2021-07-30 15:47 UTC
Labels: :lady_beetle: defect
