### ISSUE TITLE
[Deprecation] Synchronous XMLHttpRequest

### ISSUE THREAD

**Issue by john182** [primefaces/primefaces#5838] opened 2020-04-27 17:53 UTC
# IMPORTANT 
- PrimeFace version
  **7.0**

 [Deprecation] Synchronous XMLHttpRequest
- After ajax load 

## 1) Environment
- PrimeFaces version:
 **7.0**
## 2) Expected behavior

update component

## 3) Actual behavior

in console:
jquery.js.xhtml?ln=primefaces&v=7.0:2 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

## 4) Steps to reproduce

..

## 5) Sample XHTML

..

## 6) Sample bean

..

**Comment by tandraschko** [comment] 2020-04-27 17:56
PLEASE always search before creating new a new issue.
https://github.com/primefaces/primefaces/issues/2303

**Comment by tandraschko** [comment] 2020-04-27 17:59
Oh, it should be fixed in 7.0.x.

Ok but we need a small reproducer, otherwise it's invalid and we can't help.

**Comment by john182** [comment] 2020-04-27 18:15
Occurs in the autocomplete component

`
    
    <cc:interface>	
        <cc:attribute name="styleClass" />        
        <cc:attribute name="idComponente" required="true" />
        <cc:attribute name="label" required="true"/>
        <cc:attribute name="itemLabel" required="true"/>
        <cc:attribute name="completeMethod" required="true"/>
        <cc:attribute name="nomeAtributo" required="true"/>
        <cc:attribute name="requerido" default="true"/>       
        <cc:attribute name="controller" required="true"/>
        <cc:attribute name="tamanhoMinimo" default="3"/>
        <cc:attribute name="exibirInfo" default="#{false}"/>
        <cc:attribute name="drop" default="#{true}"/>
        <cc:attribute name="mensangemInfo"/>
        <cc:attribute name="emptyMessage" default="Nenhum registro encontrado"/>
        <cc:clientBehavior name="itemSelecionado" targets="#{cc.attrs.idComponente}" event="itemSelect" />

    </cc:interface>

    
    <cc:implementation>
        <div class="#{cc.attrs.styleClass}">
            <p:outputLabel value="#{cc.attrs.label}"
                           for="#{cc.attrs.idComponente}" />
            <c:if test="#{cc.attrs.exibirInfo}">
                <i class="glyphicon glyphicon-info-sign" style="margin-left: 5px" title="#{cc.attrs.mensangemInfo}"></i>
            </c:if>
            <br />

            <p:autoComplete id="#{cc.attrs.idComponente}"
                            value="#{cc.attrs.nomeAtributo}"
                            completeMethod="#{cc.attrs.controller[cc.attrs.completeMethod]}" var="objeto"
                            itemLabel="#{cc.attrs.itemLabel}" itemValue="#{objeto}"
                            queryDelay="500"
                            dropdown="#{cc.attrs.drop}"
                            style="width: 100%"
                            converter="defaultConverter" forceSelection="true"
                            scrollHeight="350"
                            minQueryLength="#{cc.attrs.tamanhoMinimo}" required="#{cc.attrs.requerido}"
                            emptyMessage="#{cc.attrs.emptyMessage}">

                <cc:insertChildren />

            </p:autoComplete>
        </div>
    </cc:implementation>
`

**Comment by tandraschko** [comment] 2020-04-27 18:24
We always need a runnable example, which consists atleast of a bean + xhtml.
In case of a more complex example, like yours with a composite component, please fork the primefaces-test project: https://github.com/primefaces/primefaces-test

**Comment by melloware** [comment] 2020-04-27 22:38
@john182 I can't reproduce in the Showcase: https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml

**Comment by stolp** [comment] 2020-04-28 09:11
I am currently seeing the same message while working with my 8.0 application.

I must admit that I never gave much attention to this so I am unsure what may be causing this and how to reproduce it.

I can definitely say that there is no AutoComplete involved in my case.

**Comment by john182** [comment] 2020-04-28 14:17
In showcase not exist example with <cc:clientBehavior name="itemSelecionado" targets="#{cc.attrs.idComponente}" event="itemSelect" />

**Comment by melloware** [comment] 2020-04-28 17:24
Yes the Select Event example here: https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml

```xml
<p:outputLabel value="Select Event:" for="event" />
<p:autoComplete id="event" value="#{autoCompleteView.txt8}" completeMethod="#{autoCompleteView.completeText}">
        <p:ajax event="itemSelect" listener="#{autoCompleteView.onItemSelect}" update="msgs" />
</p:autoComplete>
```

And I still don't see any warnings in my console?

**Comment by john182** [comment] 2020-04-29 13:59
I clone the project from the repository: https://github.com/primefaces/primefaces-test and simulated the same situation as mine and it didn't happen, so I have no idea what might be happening, the only thing I changed was the version of 6.2 to 7.0 and after this change I have system instability

**Comment by melloware** [comment] 2020-04-29 14:05
Are you sure you aren't having JAR conflicts with  6.2 and 7.0 in your WEB-INF/lib.

Sounds like you have multiple PF on your classpath.

**Comment by tandraschko** [comment] 2020-04-29 14:06
I will close it for now if you dont have a reproducer. I might even unrelated to PrimeFaces. Maybe it comes from a JQuery plugin.
Nevertheless: this warning DOES NOT bring a instability with it, it's just a warning that async is a bit better for performance.

**Closed as completed by tandraschko** 2020-04-29 14:06 UTC
Labels: Resolution: Invalid

**Comment by stolp** [comment] 2020-04-29 14:11
I wonder if this is relevant:

In https://github.com/primefaces/primefaces/issues/3621 tandraschko commented on May 2, 2018

> implemented this features now exactly the same way as in JSF 2.3.
> Only the warning in the browser: "sync requests in the mainthread are deprecated..." will now occur again.
> 
>

**Comment by tandraschko** [comment] 2020-04-29 14:14
Yep, that may be the same. But note: we just use a jQuery.append here.

I think JQuery has a good reason to load the JS sync in this case

**Comment by john182** [comment] 2020-04-29 14:14
Well, for me it becomes relevant, because in version 6.2 there is a bug in the autocomplete scroll that in version 7.0 does not have, however the application is not working correctly.

**Comment by tandraschko** [comment] 2020-04-29 14:15
@john182 but this is for 100% sure unrelated to this warning. Try 8.0 if your scroll problem is fixed. Otherwise create a new issue - but only with forked primefaces-test project to replicate it.

**Comment by melloware** [comment] 2020-04-29 14:16
@john182 I really think you have some other underlying issue going on with your deployment.

**Comment by stolp** [comment] 2020-04-29 14:16
I too see no detrimental effect to my application when this message appears. Your bug might be unrelated to this.

**Comment by john182** [comment] 2020-04-29 14:21
In addition to the message he is not updating the componets and also he duplicates the css imports

**Comment by john182** [comment] 2020-04-29 14:26
before update
![image](https://user-images.githubusercontent.com/10438644/80607692-2e584980-8a0c-11ea-9ab5-aafbf54f5088.png)

after update

![image](https://user-images.githubusercontent.com/10438644/80607796-4d56db80-8a0c-11ea-8309-cf1bc3895c47.png)

**Comment by tandraschko** [comment] 2020-04-29 14:34
please create a new issue with a reproducer
its unrelated to the warning and we can't help without a runnable primefaces-test project

AND please try 8.0 before - it might already be fixed

**Comment by john182** [comment] 2020-04-29 14:38
OK
