### ISSUE TITLE
p:calendar component issues with LocalDate/LocalDateTime

### ISSUE THREAD

**Issue by lprimak** [primefaces/primefaces#718] opened 2015-09-23 09:59 UTC
I am trying to use LocalDate bound to <p:calendar> component.
It works well, but there some UI issues.
For example, validation doesn't work at all, and if I enter 000000 in the date field,
it will not be handled gracefully or even get caught by the validation.
There are other quirks too, that are evident just by using LocalDate/LocalDateTime with <p:calendar>
I think the LocalDate/LocalDateTime story with PF should be improved

**Comment by tandraschko** [comment] 2016-01-02 17:42
Duplicate of #839

**Closed as completed by tandraschko** 2016-01-02 17:42 UTC
Labels: Resolution: Duplicate
