### ISSUE TITLE
p:panelGrid problem with composite as child will not be rendered and no error msg is thrown

### ISSUE THREAD

**Issue by Dr4gon** [primefaces/primefaces#959] opened 2015-12-16 10:55 UTC
Hi,

here's the complete info regarding the bug I found in PrimeFaces: 

http://stackoverflow.com/questions/34003868/jsf-primefaces-composite-component-with-nested-composite-component/34310031#34310031

Best regards
Dr4gon

**Comment by kukel** [comment] 2016-01-12 22:26
and what **is** the issue? Please improve at least the title

**Comment by Rapster** [comment] 2016-05-22 20:53
> Somehow the panelGrid doesn't accept a nested component and just swallows it without an error or warning. Replacing the prime faces panelGrid with a JSF one solves this problem:

I guess with simple words, the child component _(which is a composite)_ of p:panelGrid is not displayed

**Comment by Dr4gon** [comment] 2016-11-11 19:47
Hi @kukel ,

I'm very sorry about not replying - I didn't get any notifications about that.

I edited the title accordingly. 

Yeah @Rapster is correct. The child component won't be shown when it's a composite. Details in the stackoverflow post.

Best regards

**Comment by tandraschko** [comment] 2018-02-22 20:34
Could be the same as: https://github.com/primefaces/primefaces/issues/3355

**Comment by melloware** [comment] 2020-04-05 13:50
Duplicate of #3355

**Closed as completed by melloware** 2020-04-05 13:50 UTC
Labels: :lady_beetle: defect
