### ISSUE TITLE
InputNumber: Safari keyboard entry not working

### ISSUE THREAD

**Issue by iwamun** [primefaces/primefaces#5919] opened 2020-05-19 11:46 UTC
**Describe the defect**
Keyboard's Input of numbers is cleared by force.

**Environment:**
 - PF Version: 8.0
 - JSF + version: Mojarra 2.2.19
 - Affected browsers: Safari 13.1(MacOSX)

**Example XHTML**
```xml
<f:view>
<h:head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="content-language" content="ja"/>
</h:head>
<h:body>
    <h:form>
        <p:dataTable var="row" value="#{BackingBean.list}" editable="true" editMode="cell">
          <p:column headerText="p:inputText:string">
            <p:inputText value="#{row.string}"/>
          </p:column>
          <p:column headerText="p:inputText:integer">
            <p:inputText value="#{row.integer}"/>
          </p:column>
          <p:column headerText="p:inputNumber:integer">
            <p:inputNumber value="#{row.integer}"/>
          </p:column>
          <p:column headerText="p:inputText:decimal">
            <p:inputText value="#{row.decimal}"/>
          </p:column>
          <p:column headerText="p:inputNumber:decimal">
            <p:inputNumber value="#{row.decimal}"/>
          </p:column>
        </p:dataTable>
    </h:form>
</h:body>
</f:view>
```

**Example Bean**
```java
@ManagedBean(name="BackingBean")
@ViewScoped
public class BackingBean {
	private List<Bean> list = new ArrayList<>();
	public BackingBean() {
		list.add(new Bean());
		list.add(new Bean());
		list.add(new Bean());
		list.add(new Bean());
	}
	public List<Bean> getList() {
		return list;
	}
	public void setList(List<Bean> list) {
		this.list = list;
	}
}
```
```java
public class Bean {
	private String string;
	private int integer;
	private BigDecimal decimal;
	public String getString() {
		return string;
	}
	public void setString(String string) {
		this.string = string;
	}
	public int getInteger() {
		return integer;
	}
	public void setInteger(int integer) {
		this.integer = integer;
	}
	public BigDecimal getDecimal() {
		return decimal;
	}
	public void setDecimal(BigDecimal decimal) {
		this.decimal = decimal;
	}
}
```

**Comment by melloware** [comment] 2020-05-19 12:01
Attached is a reproducer: 
[pf-5919.zip](https://github.com/primefaces/primefaces/files/4650194/pf-5919.zip)

It works fine for me in Chrome, Edge, Firefox.   Are you saying this ONLY happens in Safari?

**Comment by iwamun** [comment] 2020-05-19 12:20
Hi, melloware. Thanks for replying.
That's right. It's only happens in Safari. When I tried to do in Chrome, it wasn't happen.
Actually I'm not sure of Edge, Firefox. But I certainly recognize happen in Safari of Mac OSX.

**Comment by melloware** [comment] 2020-05-19 12:26
Does it happen on the Showcase for your in Safari as well? https://www.primefaces.org/showcase/ui/input/inputNumber.xhtml

**Comment by iwamun** [comment] 2020-05-19 12:30
Yes, it happens. But if I change value by scrolling mouse, it doesn't happen. It's happen by keboard entry only.

**Comment by melloware** [comment] 2020-05-19 12:37
ok good at least we have narrowed it down.  let me investigate and see what I can find out

**Comment by melloware** [comment] 2020-05-19 17:23
OK I just tested the Showcase with 
```
Safari Version 13.1 (15609.1.20.111.8)
```
And I am having no problems with keyboard input on the InputNumber.  it works with Keyboard input or MouseWheel scrolling just fine.

**Comment by iwamun** [comment] 2020-05-20 01:44
Thanks melloware.
I also tried to do on another mac book. Then it works with Keyboard input. This PC is Mac Book Air and Safari Version is 13.04.
But it will happen in my environment of Mac Book Pro and Safari Version 13.1 (15609.1.20.111.8).
[capture 2020-05-20 10.32.56.zip](https://github.com/primefaces/primefaces/files/4654157/capture.2020-05-20.10.32.56.zip)

**Comment by melloware** [comment] 2020-05-20 11:14
weird. I tried on 2 more Mac's and neither one of them has an issue.  So is there something different about the one you have it does not work?  Browser plugins?  Some kind of special software installed?

Because on 3 Mac's I can't reproduce your issue.

**Comment by iwamun** [comment] 2020-05-20 11:48
Our customer gives a hint. He uses Safari Version 13.1 (15609.1.20.111.8) on mac book pro. And he could reproduce same issue. 
The same points of us are safari version and not installing any plugin, japanese environment. 
My mac book is installed some softwares of development but his one is not. So I can conclude my environment of development doesn't affect it's issue.

**Comment by melloware** [comment] 2020-05-20 11:57
OK so the only thing that may be a clue is that is a the your envionment or Browser locale is Japanese?

Can you do me a favor let's see if its a problem with AutoNumeric JS itself.  Can you go to this page:
http://autonumeric.org/examples

try that in Safari and see if it exhibits the same issue?

**Comment by iwamun** [comment] 2020-05-20 12:05
Same issue occurred.

[capture 2020-05-20 21.01.36.zip](https://github.com/primefaces/primefaces/files/4656682/capture.2020-05-20.21.01.36.zip)
.

**Comment by melloware** [comment] 2020-05-20 12:07
OK awesome.

Can you please report the issue to here: https://github.com/autoNumeric/autoNumeric/issues

The issue is in the Autonumeric Plugin and tell them you have narrowed it down to use Japanese locale on your Mac and that it is specific to Safari.

**Comment by iwamun** [comment] 2020-05-20 12:11
OK I will. Thank you for your help.

**Comment by melloware** [comment] 2020-05-20 12:30
OK issue is reported at AutoNumeric. https://github.com/autoNumeric/autoNumeric/issues/681

I watching that issue and will upgrade AutoNumberic when they fix it.  For now closing this ticket.

**Closed as completed by melloware** 2020-05-20 12:30 UTC
Labels: needs testing, browser-specific
