### ISSUE TITLE
Single quote in labels of Charts

### ISSUE THREAD

**Issue by MiguelAngelLV** [primefaces/primefaces#1760] opened 2016-09-13 10:10 UTC
# IMPORTANT
- If you open a issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open a issue, test it with the current/newest version.
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? no
- Application server + version: Glassfish 4.0
- Affected browsers: All
## 2) Expected behavior

Charts with any labels
...
## 3) Actual behavior

If labels charts have single quotes ', the javascript faild
..
## 4) Steps to reproduce

Add a single quote in label of a Series
.. 
## 5) Sample XHTML

..
## 6) Sample bean

..

**Comment by melloware** [comment] 2017-04-06 11:59
Duplicate of #709

**Closed as completed** 2017-04-06 12:52 UTC
Labels: :lady_beetle: defect
