### ISSUE TITLE
Calendar: popup with effect="fold" wrong show

### ISSUE THREAD

**Issue by omarbr** [primefaces/primefaces#3619] opened 2018-04-27 12:37 UTC
## 1) Environment
- PrimeFaces version: reproduced on 5.3 and 6.2
- Affected browsers: firefox, chrome, edge

simply reproduce on primeface showcase

## 3) Actual behavior
when click on p:calendar input field with effect="fold" show popup dialog and it's ok, click other calendar field, popup dialog is damaged.

## 4) Steps to reproduce
click on on p:calendar input field with effect="fold", not select date (popup dialog remains open), click on other p:calendar input field, then popup dialog is damaged.

## 6) Sample bean
primeface showcase

**Comment by melloware** [comment] 2018-11-27 22:04
@tandraschko This is a duplicate of https://github.com/primefaces/primefaces/issues/489 and can be closed.

**Closed as completed** 2018-11-27 22:32 UTC
Labels: :lady_beetle: defect
