### ISSUE TITLE
Tooltip: works incorrectly when used with position="top" and trackMouse="true"

### ISSUE THREAD

**Issue by rzapletal** [primefaces/primefaces#2359] opened 2017-05-12 11:08 UTC
## 1) Environment
PrimeFaces version: 6.0.17, browser FireFox ESR 52.1.1 (32-bit)

## 2) Expected behavior
Tooltip should appear above element and move with mouse.

## 3) Actual behavior
Tooltip shows below element

## 4) Steps to reproduce
just render page with code from below

## 5) Sample XHTML
<h:outputText id="text" value="some example text">
<p:tooltip value="... might be some some really long text ..." 
  id="toolt" for="text" trackMouse="true" layout="block"
  position="top" styleClass="textTooltip" />

## 6) Sample bean
not needed

**Comment by tandraschko** [comment] 2017-05-22 14:00
Feel free to provide a PR.

**Comment by rzapletal** [comment] 2017-05-22 17:56
Sorry, I have no idea what is a PR...

**Comment by jxmai** [comment] 2017-12-18 23:10
> Sorry, I have no idea what is a PR...

@rzapletal  "PR" stands for the abbreviation of "Pull Request". https://help.github.com/articles/about-pull-requests/

**Comment by melloware** [comment] 2018-12-27 21:11
OK this was made as a conscious decision by PrimeTek when using Track Mouse its always on the bottom left no matter what you have for position.  It on purpose ignores the position attribute.

https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js#L184-L193

https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/tooltip/tooltip.js#L303-L314

**Comment by melloware** [comment] 2020-06-24 18:21
Duplicate of: https://github.com/primefaces/primefaces/issues/92

**Closed as completed by melloware** 2020-06-24 18:21 UTC
Labels: :lady_beetle: defect

**Comment by melloware** [comment] 2021-01-18 12:27
Fixed in 10.0 with: https://github.com/primefaces/primefaces/issues/6845
