### ISSUE TITLE
AutoComplete: add facets to customize the visual output

### ISSUE THREAD

**Issue by nimo23** [primefaces/primefaces#10411] opened 2023-07-29 11:48 UTC
### Description

Actually, `AutoComplete` can only show raw text for the items suggested in the box (= **"selectables"**) and for the selected items (= **"selections"**) without much styling.

Users have to do many workarounds to achieve something like this. See the reproducer:

[autocomplete-with-facets.zip](https://github.com/primefaces/primefaces/files/12207008/autocomplete-with-facets.zip)

The workaround is not a clean and performance-wise solution, e.g. we need to provide two bean properties containing the selection of `AutoComplete` and `DataTable`. We need to hide the output (= "selections") of `AutoComplete` via CSS, but javascript still always computes it. We need to use raw javascript when the user deselects an item from the `DataTable` so that it doesn't remain selected in the `AutoComplete` bean either, etc. And all that stuff is not easy to make.

### Describe the solution you would like

Provide the two facets `selectables` (_to style the selectables)_ and `selections` (_to style the selections_). Look at the following example how to use it:

```
<p:autoComplete 
    id="search_users" 
    scrollHeight="300" 
    value="#{testView.selectedUsers}" 
    completeMethod="#{testView.autocompleteUsers}" 
    var="user" itemValue="#{user}">

<!-- set the selectables neatly in a facet ->
 <f:facet name="selectables"> 
       <!-- can be either any html content or column-tags -->
	<p:column width="80px">
	    <span>#{user.id}</span>
	</p:column>
	<p:column width="80px">
	    <span>#{user.name}</span>
	</p:column>
</f:facet>

<!-- should be used instead of autoComplete.itemLabel -->
 <f:facet name="selections"> 
        <!-- can be either any html content or column-tags -->
	<p:column width="80px">
	    <span>#{user.id}</span>
	</p:column>
	<p:column width="80px">
	    <span>#{user.name}</span>
	</p:column>
       <p:column width="80px">
	    <span>#{user.age}</span>
	</p:column>
</f:facet>

</p:autoComplete>
```

The content of `<f:facet name="selections">` should be any html which is put **below** the `autoComplete`-Box, i.e. the selections is presented below the `autoComplete`-InputField and NOT within the `autoComplete`-InputField.

### Additional context

 When this issue gets fixed, then https://github.com/primefaces/primefaces/issues/1903 will be also fixed as the facets `selections` and `selectables` would implicitly _"allowing lables to be defined using facets"_.

**Comment by melloware** [comment] 2023-07-29 12:03
I believe a lot of this was done for performance and ARIA needs not needing to make server round trips for certain UI aspects like say adding/removing a token from the Multiple value etc.   

Your component ideas have different goals in mind so I would think it would be a different component.  I think you might be better off opening a ticket under PrimeFaces Extensions for a new component that is rewritten from scratch specifically for this use case and can be incubated in the PFE sandbox.

See: https://github.com/primefaces-extensions/primefaces-extensions/issues

**Comment by melloware** [comment] 2023-07-29 12:11
Well you have 3 choices:

1) Pay PrimeTek 💰 to implement this feature using a PRO account.
2) Fix this component yourself and provide a PR that ensures it does not break backwards compatibility. 
3) Pray 🙏🏻 someone in the community takes up this ticket which I doubt they will.
4) Start a new component in PFE which can be tested, incubated, improved without affecting the current PF AutoComplete. But even then here you will have to write this new component and provide the beta to the PFE team.
5) ???

**Comment by melloware** [comment] 2023-07-29 15:18
Take a deeper look.   Let me explain the problem as I don't think you are grasping what you are asking for.  

**Your asking for:** To take what is currently all done client side rendering and move it to the server side.   

**What does that impact?**   It moves lots of client side code to the server side both decreasing performance and user experience while increasing the regression test load.  

**How can that be?**  Let me explain.

Let's take this example and you want to customize how the labels get rendered for "Afghanistan" and "Central African Republic".

![image](https://github.com/primefaces/primefaces/assets/4399574/8e374fa6-5e15-4371-891c-876481b1c779)

You want to declare a `<f:facet>` to allow you to control that rendering. Facets are of course server side elements not client side.  
  
Next, Bring up F12 in your browser and watch the Network tab. Then click the "X" to remove Central African Republic so it looks like this:
![image](https://github.com/primefaces/primefaces/assets/4399574/8956efc0-2e6a-403b-83e5-7a69473d415b)

Did you see anything on your Network tab?  NO you did not because it did not need a server side round trip to do anything.

In YOUR scenario every time you added or removed an item like above would force it to be an AJAX request because it would have to go evaluate your `<f:facet>` to render the HTML and then send it back to the client for display.

Does that make sense?

So you would be moving lots of client side JS all to the server side and forcing Network round trips for almost any behavior done by using facets.  To me it would make the AutoComplete less usable of a component and not more usable for my users.

**Comment by melloware** [comment] 2023-07-29 15:30
Well lucky for you with MonkeyPatching there is nothing stopping you from overwriting the client side JS to render whatever you want!!!  So your solution is available for you right now you just have to swap out the JS to render for your exact needs.

**Comment by melloware** [comment] 2023-07-29 19:06
Nope. Nothing like that. Facet is server side always.  Which goes back to my earlier statement of almost a complete rewrite or a new and different server side version of this component.

**Comment by tandraschko** [comment] 2023-07-31 08:08
also think about our endpoint support

in theory we could introduce something like a facet, called "itemTemplate" and there you can use some var inside it
but surely not a small task

**Comment by melloware** [comment] 2023-07-31 21:34
I am going to close this as Not Planned.

**Comment by tandraschko** [comment] 2023-08-21 13:51
IMO we could do the following:

1) provide a `itemLabel` facette, as alternative to the attribute
2) the itemLabel must be rendered on server side then, which requires an AJAX request after the item is selected

what does that mean?
it should work for all combinations, also like the endpoint, as just the selected-itemLabel is rendered via AJAX, nothing else.
it should be very fast compared to render all selectable items on the server side as its only for 1 item and only on selection.
We can preconfigure the AJAX request with some good defaults; also we dont need to render the whole autocomplete content, just the selected item, which is results in a very small response.

**Comment by tandraschko** [comment] 2023-08-22 13:24
2) is a different topic and new issue for me

**Closed as not planned** 2023-08-23 13:46 UTC
Labels: discussion
