### ISSUE TITLE
Submit key modifier when clicking command components

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#148] opened 2015-04-22 15:54 UTC
submit key modifier such as ALT/SHIFT as request parameters when clicking commandLink/Button. One use case is to open dialog to show content if SHIFT key is pressed.

http://forum.primefaces.org/viewtopic.php?f=3&t=29360

**Comment by melloware** [comment] 2023-01-20 20:30
Duplicate of #4068

**Closed as not planned by melloware** 2023-01-20 20:30 UTC
Labels: Resolution: Duplicate
