### ISSUE TITLE
DataTable: Header/Footer not updated by sort/filter

### ISSUE THREAD

**Issue by german1410** [primefaces/primefaces#988] opened 2015-12-30 18:21 UTC
If we create a data table with dynamic columns and pagination, if for some reason the number of columns change on pagination, for example using lazy loading and then update columns based on available data, then columns changes for dynamic columns are not reflected on the header. This is because of the pagination feature only encode the tbody:

```
public class PageFeature implements DataTableFeature {

    public void decode(FacesContext context, DataTable table) {
        throw new RuntimeException("PageFeature should not encode.");
    }

    public void encode(FacesContext context, DataTableRenderer renderer, DataTable table) throws IOException {
        table.updatePaginationData(context, table);

        if(table.isLazy()) {
            table.loadLazyData();
        }

        renderer.encodeTbody(context, table, true);
    }

    public boolean shouldDecode(FacesContext context, DataTable table) {
        return false;
    }

    public boolean shouldEncode(FacesContext context, DataTable table) {
        return table.isPaginationRequest(context);
    }

}
```

So in our case we have a lazy data model that upadtes the columns to display based on available data, so in the case you change from one page to another and the columns change, such change is nor reflected on the table header.

**Comment by german1410** [comment] 2015-12-30 19:11
Actually this looks like a limitation on pagination since on the DataTable widget we have:

#### Norma Data table

``` javascript
updateData: function(data, clear) {
        var empty = (clear === undefined) ? true: clear;

        if(empty)
            this.tbody.html(data);
        else
            this.tbody.append(data);

        this.postUpdateData();
    },
```

#### DataTable with frozen columns

``` javascript
    //@Override
    updateData: function(data, clear) {
        var table = $('<table><tbody>' + data + '</tbody></table>'),
        rows = table.find('> tbody > tr'),
        empty = (clear === undefined) ? true: clear; 

        if(empty) {
            this.frozenTbody.children().remove();
            this.scrollTbody.children().remove();
        }

        for(var i = 0; i < rows.length; i++) {
            var row = rows.eq(i),
            columns = row.children('td'),
            frozenRow = this.copyRow(row),
            scrollableRow = this.copyRow(row);

            frozenRow.append(columns.slice(0, this.cfg.frozenColumns));
            scrollableRow.append(columns.slice(this.cfg.frozenColumns));

            this.frozenTbody.append(frozenRow);
            this.scrollTbody.append(scrollableRow);
        }

        this.postUpdateData();
    }
```

Which only update the body

**Comment by german1410** [comment] 2016-01-07 17:11
This looks like a known limitation, but it would be nice to update documentation to indicate the limitation of this events and features (pagination+dynamic column):

https://code.google.com/p/primefaces/issues/detail?id=5403

Regards

**Comment by melloware** [comment] 2020-07-16 19:48
duplicate of https://github.com/primefaces/primefaces/issues/1178

**Closed as completed by melloware** 2020-07-16 19:48 UTC
Labels: Resolution: Duplicate
