### ISSUE TITLE
Media: request for StreamedContent not captured by FacesServlet and hence 404 is returned

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#5901] opened 2020-05-15 14:03 UTC
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? not tested
- Does it work on the newest sources in GitHub? not tested
- Application server + version: Tomcat 8.0.39, Tomcat 8.5.55
- Affected browsers: any

## 2) Expected behavior

I can display a pdf file named TEST.PDF supplied through a `StreamedContent` instance whose `getName()` returns `TEST.PDF`.

## 3) Actual behavior

The pdf file is not displayed by `p:media`, a 404 is returned for the generated URL.

## 4) Steps to reproduce

- in my web.xml I have the following mappings for FacesServlet:

```xml
<servlet>
  <servlet-name>Faces Servlet</servlet-name>
  <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
  <load-on-startup>1</load-on-startup>
</servlet>
<servlet-mapping>
  <servlet-name>Faces Servlet</servlet-name>
  <url-pattern>*.faces</url-pattern>
  <url-pattern>*.seam</url-pattern>
  <url-pattern>*.jspx</url-pattern>
  <url-pattern>*.xhtml</url-pattern>
  <url-pattern>/faces/*</url-pattern>
</servlet-mapping>
```

- I have a page with a simple:

```xml
<p:media value="#{myBean.myStreamedDocument}" player="pdf" />
```

- please note that in the above example `myBean.myStreamedDocument` returns a `StreamedContent` instance with `getName()` returning `TEST.pdf`
- `p:media` generates a `<object>` tag whose `data` attribute contains something like this:

    http://localhost:8080/shop-backend/javax.faces.resource/dynamiccontent.properties.jspx;/TEST.pdf?ln=primefaces&v=6.2&pfdrid=494db01692b3882917ffb08752dc12e8&pfdrt=sc&pfdrid_c=true

However, this URL resolves to a 404, because Tomcat (I tested with both 8.0.39 and 8.5.55, which is the latest 8.x one) is not mapping this URL to the `FacesServlet`, probably thinking that the file extension is `.pdf` rather than `.jspx`.

However,  if I change my `StreamedContent` instance to return `TEST.pdf.jspx` from its `getName()` method, all works fine and I can see my pdf. The URL in this case is something like this:

http://localhost:8080/shop-backend/javax.faces.resource/dynamiccontent.properties.jspx;/TEST.pdf.jspx?ln=primefaces&v=6.2&pfdrid=494db01692b3882917ffb08752dc12e8&pfdrt=sc&pfdrid_c=true

Please note that:
- no error log is produced either in the browser console, or in the server log
- I verified that in the first case the `FacesServlet` is not queried at all, because I put a breakpoint on `javax.faces.webapp.FacesServlet.service(ServletRequest, ServletResponse)` and it was not hit when the file name was set to `TEST.pdf`; instead it is when the file name is set to `TEST.pdf.jspx`

## 5) Sample XHTML

```xml
<p:media value="#{myBean.myStreamedDocument}" player="pdf" />
```

## 6) Sample bean

```
public class MyBean {
  public StreamedContent getMyStreamedDocument() {
    // let "is" be a FileInputStream built on a pdf file taken somewhere
    return new DefaultStreamedContent(new BufferedInputStream(is), "application/pdf", "TEST.pdf");
  }
}
```

**Comment by tandraschko** [comment] 2020-05-15 17:32
no idea where this comes from, the showcase examples are working fine.
Can you try the showcase on tomcat?

**Comment by tandraschko** [comment] 2020-05-15 17:34
And please try 9.0-SNAPSHOT
We should actually close all issues as invalid if not tested with the newest version. WDYT @melloware to change the template here?

**Comment by melloware** [comment] 2020-05-15 17:38
Not a bad idea.  would prevent reports of issues on PF 5.3 etc?  Or even on 8.0 if its already fixed in 9.0.  Want me to change the template?

**Comment by tandraschko** [comment] 2020-05-15 17:43
yes, please
thats really annoying
i would make a hard statement like that we dont support old versions anymore here and that issues must be tested on current versions
Everything else -> PRO user which can sponsor issues for elite versions

**Comment by melloware** [comment] 2020-05-15 17:44
yep i am on it.

**Comment by mauromol** [comment] 2020-05-15 17:45
Please consider that it's not always easy or viable for users to test with the latest version. I already spent a LOT of time to find this problem and open this bug report, I don't think the user should be blamed if he can't test with the latest version. IMHO a report on an older version would still be more useful than no report at all. Also because, in my own experience, if I know I've done nothing on a specific area, it's really unlikely that a problem has been fixed by itself. So, if you've not changed how that internal URL for showing documents in a `media` component is generated, how could it be fixed in 9.0?

Before opening this issue I checked that it was not reported before, I searched in Google, I debugged the code. Trying a newer PF version is not just a matter of switching JARs in the application where I experience this problem, because a newer version may completely break the application (having unsatisfied requirements over versions of JSF, application server, possibly, Java, etc., plus the risk of backward incompatibilities - unfortunately they happen with PF).

**Comment by melloware** [comment] 2020-05-15 17:48
@mauromol its is incredibly easy to test with 9.0-SNAPSHOT.  That is why we have PrimeFaces Test: https://github.com/primefaces/primefaces-test

Everything is all done for you in a small, simple, and concise reproducer.  You can change 8.0 to 
```xml
<dependency>
     <groupId>com.github.primefaces</groupId>
     <artifactId>primefaces</artifactId>
     <version>master-SNAPSHOT</version>
 </dependency>
```

and you are using the very latest code from 9.0-SNAPSHOT.

**Comment by tandraschko** [comment] 2020-05-15 17:48
@mauromol i dont like to blame anyone here, its just:
i dont have much time to fix issues here in my freetime.
if you create a issue here (which means that you please us to fix it), we can assume that you can replicate it with a simple sample bean + xhtml. In this case you can download primefaces-test, copy your sample there and test it. Thats an overhead of max. 5 mins.
After this we are sure its already fixed or not AND we already have a reproducer, so we can easily test and fix it for you.

**Comment by mauromol** [comment] 2020-05-15 17:57
Creating a webapp from scratch to reproduce the same scenario in which I encounter this problem is not a matter of 5 minutes, even if today we can use Spring Boot. If I were a PF developer I would probably have a set of different application templates to test with, but it's not my case.
I *may* try to do that, but I don't know right now when I will be able to do it. I already spent much more time than my employer gave me to implement a "pdf preview" feature with p:media and pe:documentViewer and in the outcome of this effort is this bug report and the other ones I opened today. I still think a report like this is more useful than no report at all, for myself, for you and for the community. At least, if someone else hits this bug someday, he will find this.

**Comment by mauromol** [comment] 2020-05-15 18:03
> @mauromol its is incredibly easy to test with 9.0-SNAPSHOT. That is why we have PrimeFaces Test: https://github.com/primefaces/primefaces-test
> 
> Everything is all done for you in a small, simple, and concise reproducer. You can change 8.0 to

The first two things that I note are this: that example uses Jetty and Maven. This issue is likely to be bound to Tomcat and I don't have so much experience with Maven (I use Gradle). Yes, many concepts are in common and yes, of course I can learn, but it's always a matter of available time.

Anyway, I'd like to keep the discussion constructive, so I'm not going to continue on this, but please: don't blame users that report bugs if they can't do it in a perfect way. I think their contribution is much more useful than no feedback at all from users that don't report.

**Comment by melloware** [comment] 2020-05-15 18:11
Reproducer took 5 minutes: 
[pf-5901.zip](https://github.com/primefaces/primefaces/files/4636292/pf-5901.zip)

Yes we use Jetty with profiles for MyFaces 2.2 and 2.3 and Mojarra 2.2/2.3 so we can take Jboss/Tomcat/WebSphere/Weblogic out of the equation.  We are trying to prove something is a PF bug not a Tomcat bug.

**Comment by tandraschko** [comment] 2020-05-15 18:20
does it work on jetty?

**Comment by melloware** [comment] 2020-05-15 18:22
No it does not work.  It has same issue.  Because the dynamic resource ends in .PDF it won't serve it from the FacesServlet.

**Comment by tandraschko** [comment] 2020-05-15 18:24
no idea
it seems someone added hack for PDF in the past:
MediaRender ln63

**Comment by melloware** [comment] 2020-05-15 18:27
yep i see it.  looking into it.

**Comment by melloware** [comment] 2020-05-15 18:56
We have this open enhancement ticket: https://github.com/primefaces/primefaces/issues/105

It definitely looks like this used to work: 
https://github.com/primefaces/primefaces/issues/4032
https://github.com/primefaces/primefaces/issues/2055

So something about it no longer is working.

**Comment by melloware** [comment] 2020-05-17 22:50
I actually have no idea how this ever worked.

**Comment by tandraschko** [comment] 2020-05-18 07:33
yep, same for me.
I think it might only work for prefix servlet mapping currently.

**Comment by tandraschko** [comment] 2020-05-18 08:48
I would do the following:
remove the ";filename" after the URL, this will never work correctly
+ add showcase example
+ try to replicate what didn't work and why we introduced this hack

**Comment by melloware** [comment] 2020-11-24 17:08
I think we need @mertsincan to weigh in here as he did the fix for https://github.com/primefaces/primefaces/issues/2055 originally and this seems to clearly work for some users i guess depending on what application server they are using?

**Closed as completed** 2020-12-26 19:14 UTC
Labels: :lady_beetle: defect, workaround
