### ISSUE TITLE
DataExporter : PrimeFaces 12.0.0 not exporting headers

### ISSUE THREAD

**Issue by Momenkh** [primefaces/primefaces#11156] opened 2023-12-20 11:56 UTC
### Describe the bug

I am trying to export the headers of a huge amount of datatables, I tried several things like exportHeaderValue / Making a Facet header , giving to the column headerText, but whenever I try to export it, only the data is exported, when I tried xls and xlsx, same problem but when I changed it to csv it exported the headers but there was a problem with the encoding (some data are written in arabic), I tried adding encoding UTF-8 still no hope

### Reproducer

                    <h:commandLink >
                        <p:graphicImage url="#{resource['harmony-layout/images/xlsicon.png']}" width="35" class="mt-2"/>
                        <p:dataExporter type="xlsx" target="dataTableId" fileName="AnyFileName"/>
                    </h:commandLink>
                    
                    ....................
                     <p:dataTable widgetVar="visitsAgentsDT" var="visitsAgents" value="#{searchTransferBB.visitsAgentsList}" reflow="true"
                     rowKey="#{visitAgent.id}" lazy="true" id="dataTableId"
                     paginator="true" rows="5" paginatorPosition="bottom"
                     rowsPerPageTemplate="5,10,50,100" selectionMode="single">
                    
                    
                    ..............
                <p:column>
                <f:facet name="header">
                    <h:outputText value="Visit Name"/>
                </f:facet>
                <h:outputText value="#{visitsAgents.visitId.name}" />
            </p:column>

### Expected behavior

Export the header name for the column and below it the data

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

8

**Comment by jepsar** [comment] 2023-12-20 12:00
Duplicate of #9290

**Closed as completed by jepsar** 2023-12-20 12:00 UTC
Labels: Resolution: Duplicate, 12.0.1

**Comment by melloware** [comment] 2023-12-20 12:37
Yes please upgrade to 13.0.4 or to 12.0.X if you are an Elite subscriber it was fixed in 12.0.1
