### ISSUE TITLE
PF 10 filter: dropdown values in datatable row reset after filtering

### ISSUE THREAD

**Issue by DazzlingBob** [primefaces/primefaces#7181] opened 2021-03-30 09:45 UTC
**Environment**
PrimeFaces version: primefaces 10.0.0
Application server: Jetty 9.4.46 + version: Mojarra-2.3

**Expected behavior**
The country dropdowns in a datatable row must always keep its value after whatever filtering.

**Actual behavior**
The country dropdowns in a datatable row are all reset to "Choose item".

**Steps to reproduce**
When filtering a country which is not in the datatable row (see country list on top) and then filter All
the country dropdowns in a datatable row are all reset to "Choose item".

This behavior is only in primefaces 10, primefaces 8 is fine.

**Sample XHTML / Sample bean**

Primefaces 10 (country dropdown is reset to choose item):
[primefaces-test-10.0.0-db.zip](https://github.com/primefaces/primefaces/files/6228031/primefaces-test-10.0.0-db.zip)

Primefaces 8 (works as expected):
[primefaces-test-8.0-db.zip](https://github.com/primefaces/primefaces/files/6228034/primefaces-test-8.0-db.zip)

run with:
mvn clean jetty:run -Pmojarra23

**Comment by christophs78** [comment] 2021-03-30 11:21
Sounds like https://github.com/primefaces/primefaces/issues/7026

**Comment by melloware** [comment] 2021-03-30 11:39
Duplicate of #7026 right now unless Mojarra fixes it switching to Myfaces is the only way to fix it.

**Closed as completed by melloware** 2021-03-30 11:39 UTC
Labels: Resolution: Duplicate

**Comment by DazzlingBob** [comment] 2021-03-30 12:10
I am a little puzzled?
It works fine in my project using mojarra-2.3 and primefaces 8+
When i upgrade to primefaces 10 it breaks.

And the only option is to switch to myfaces? (or keep using primefaces 8+)
So primefaces 10 is only compatible with myfaces?

**Comment by melloware** [comment] 2021-03-30 12:14
No this bug is a core Mojarra bug. So you need Mojarra to debug and fix the issue.  PrimeFaces 10 was refactored heavily to fix so many issues with the datatable.  It ended up exposing this Mojarra bug.   So while it worked in PrimeFaces 8 it was not correct.

**Comment by melloware** [comment] 2021-03-30 12:16
@DazzlingBob what you can do is put together a reproducer and report it on Mojarra like I did with this ticket here: https://github.com/eclipse-ee4j/mojarra/issues/4680

**Comment by christophs78** [comment] 2021-05-03 17:53
https://github.com/eclipse-ee4j/mojarra/releases/tag/2.3.15 is available
