### ISSUE TITLE
sortMeta in p:dataTable missing

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#6256] opened 2020-08-27 10:50 UTC
According to https://primefaces.github.io/primefaces/8_0/#/components/datatable there should be sortMeta property in p:dataTable, yet:
![missing](https://user-images.githubusercontent.com/1133953/91433596-cef83200-e863-11ea-9e5b-302c24bba1b2.png)

Primefaces 8.0.3

**Comment by morvael** [comment] 2020-08-27 10:52
Used sortBy to provide initial sort order for multisort table. It worked in PF 7.

Also, what should be provided into columnKey field of SortMeta object? In PF 7 I've used:
```
sm.setSortBy((UIColumn) FacesContext.getCurrentInstance().getViewRoot().findComponent(id));
```

**Comment by morvael** [comment] 2020-08-27 10:58
What is they key of the sortMeta map? Why wasn't this mentioned in the Migration Guide?

**Comment by melloware** [comment] 2020-08-27 11:24
OK a few things..
We have this open ticket: https://github.com/primefaces/primefaces/issues/5438

Here is what I do...
```xml
sortBy="#{taskManagerBean.multiSsortMetaData}"
```

and in Java Code use a LinkedHashMap.  The key is the `ID` of the UIColumn like `frmOrganizer:tblOrganizer:colTagId`
```java
final Map<String, SortMeta> sortMap = new LinkedHashMap<>();
final SortMeta meta = new SortMeta(column.getColumnKey(), sortFields[0], SortOrder.valueOf(sortFields[1]), null);
// key = frmOrganizer:tblOrganizer:colTagId
 sortMap.put(key, meta);
```

**Comment by melloware** [comment] 2020-08-27 11:25
Duplicate of #5348

**Closed as completed** 2020-08-27 11:25 UTC
Labels: Resolution: Duplicate

**Comment by morvael** [comment] 2020-08-27 12:19
So there will be the new sortMeta tag or the old sortBy will be used?

**Comment by melloware** [comment] 2020-08-27 12:34
I think the idea for 9 is there will be a new SortMeta tag, it was not in the taglib.xml of PF8.

**Comment by morvael** [comment] 2020-08-27 12:36
Ok, so the documentation is wrong.

**Comment by melloware** [comment] 2020-08-27 12:39
Yep hopefully getting fixed for 9.0 with #5348

**Comment by stolp** [comment] 2020-08-27 12:49
@melloware:I think it is #5438 instead of #5348

**Comment by melloware** [comment] 2020-08-27 12:51
Whoops!  yep too many similar numbers

**Comment by melloware** [comment] 2020-08-27 12:54
duplicate of #5438
