### ISSUE TITLE
SelectOneRadio with responsive and columns: wrong class in 13.0.3

### ISSUE THREAD

**Issue by SimonePadovan** [primefaces/primefaces#11128] opened 2023-12-15 14:25 UTC
### Describe the bug

This code generates the wrong html code in the class used in the radio tags using PF 13.0.1 to 13.0.3. 
It works OK with 13.0.0

`<h5>Responsive + Unselectable</h5>
        <p:selectOneRadio id="city2" value="#{radioView.city2}" layout="responsive" columns="3" unselectable="true">
            <f:selectItems value="#{radioView.cities}" var="city" itemLabel="#{city}" itemValue="#{city}"/>
 </p:selectOneRadio>`

With 13.0.0 generates: 
div class="ui-g-12 ui-md-4" role="radio" aria-checked="false"

With 13.0.1 to 13.0.3 generates: 
div class="col-12 md:col-4" role="radio" aria-checked="false"

### Reproducer

you can reproduce it via PF showcase

### PrimeFaces edition

None

### PrimeFaces version

13.0.3

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

11

**Comment by melloware** [comment] 2023-12-15 14:33
I think this is a duplicate of https://github.com/primefaces/primefaces/issues/11082 which is being fixed for 13.0.4

**Comment by SimonePadovan** [comment] 2023-12-15 14:39
ok thanks

**Closed as completed** 2023-12-15 14:46 UTC
Labels: Resolution: Duplicate
