### ISSUE TITLE
Datatable: filtering issue for SelectOne as input

### ISSUE THREAD

**Issue by saycchai** [primefaces/primefaces#6196] opened 2020-08-05 05:43 UTC
**Describe the defect**
I have a drop down (p:selectOneMenu) as the input field in the Primefaces 8.0 datatable row, after I select the value in the drop down, if I sort it the selected value can be kept after ajax submit. However if I input a filter and no row appear, and then I clear the filter, the selected value in the drop down disappeared

**Reproducer**
git clone https://github.com/saycchai/jsf-test.git
cd jsf-test

for payara server:
chmod +x *.sh
./buildAndRun.sh
browse: http://localhost:8080/index.xhtml

for other server: 
mvn clean package

copy the target/jsf-test.war to your deploy dir
browse: http://localhost:8080/jsf-test/index.xhtml

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _2.3_
 - Affected browsers: _ Chrome, Firefox_

**To Reproduce**
1. Select the drop down value in both drop down (e.g. K1 for 1st, K2 for second)
![1](https://user-images.githubusercontent.com/7637215/89375647-abd4d980-d720-11ea-83b1-9586c39e1781.png)

2. input the filter value "xx" so that all the rows are filter out
![2](https://user-images.githubusercontent.com/7637215/89375658-af686080-d720-11ea-8a7c-c9da11271231.png)

3. clear the filter, the selected value disappear
![3](https://user-images.githubusercontent.com/7637215/89375680-b8f1c880-d720-11ea-8282-9eb82c3af647.png)

**Expected behavior**
The selected value of the drop down should be retained after clear the filtering

**Example XHTML**
```xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui"
    xmlns:of="http://omnifaces.org/functions">

<h:head>
    <title>Hello World JSF 2.3</title>
</h:head>

<h:body>
    <h:form>
        <p:dataTable var="item" value="#{sampleBean.tableObjects}"
            widgetVar="itemTable">

            <p:ajax event="sort" process="@this" update="@this"
                skipChildren="false" />
            <p:ajax event="page" process="@this" update="@this"
                skipChildren="false" />
            <p:ajax event="filter" process="@this" update="@this" global="false"
                skipChildren="false" />

            <p:column headerText="Dropdown" sortBy="#{item.dd}" filterBy="#{item.dd}"
                filterMatchMode="contains">
                <p:selectOneMenu id="Dropdown" value="#{item.dd}" required="false"
                    label="Dropdown" style="width: 100%">

                    <f:selectItem itemValue="#{null}" itemLabel="" />
                    <f:selectItems value="#{sampleBean.dropDown.entrySet()}"
                        var="entry" itemValue="#{entry.value}" itemLabel="#{entry.key}" />
                </p:selectOneMenu>
            </p:column>
        </p:dataTable>
    </h:form>
</h:body>
</html>
```

note: 
1. input text and text area no such problem, only selectOneMenu has this problem.
2. already tried following, same problem happen:
```
<p:selectOneMenu ...><p:ajax/></p:selectOneMenu> 
<p:selectOneMenu ...><p:ajax event="change"/></p:selectOneMenu>
<p:selectOneMenu ...><p:ajax event="change" process="@form" update="@form"/></p:selectOneMenu>
```

**Example Bean**
```java
@Named
@SessionScoped
public class SampleBean implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 5307652891294044974L;

    private static final Map<String, String> dropDown = new HashMap<>();
    
    static {
        dropDown.put("K1", "K1");
        dropDown.put("K2", "K2");
        dropDown.put("K3", "K3");
    }

    public Map<String, String> getDropDown() {
        return dropDown;
    }

    private List<TableObject> tableObjects = Arrays.asList(new TableObject[] {new TableObject(), new TableObject()});
    
    public List<TableObject> getTableObjects() {
        return tableObjects;
    }

    public void setTableObjects(List<TableObject> tableObjects) {
        this.tableObjects = tableObjects;
    }

    public static class TableObject 
    {
        private String dd;

        public String getDd() {
            return dd;
        }

        public void setDd(String dd) {
            this.dd = dd;
        }
        
    }
}
```

**Comment by melloware** [comment] 2020-08-05 11:58
Not sure if this is a PrimeFaces issue or not as it doesn't work with the standard `h:selectOneMenu` either.

 See my attached reproducer:
[pf-6196.zip](https://github.com/primefaces/primefaces/files/5028115/pf-6196.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml

```xml
		<h:form>
			<p:dataTable var="item" value="#{sampleBean.tableObjects}"
			widgetVar="itemTable">

				<p:ajax event="sort" process="@this" update="@this"
				skipChildren="false" />
				<p:ajax event="page" process="@this" update="@this"
				skipChildren="false" />
				<p:ajax event="filter" process="@this" update="@this" global="false"
				skipChildren="false" />

				<p:column headerText="PF SelectOne" sortBy="#{item.dd}" filterBy="#{item.dd}"
				filterMatchMode="contains">
					<p:selectOneMenu id="Dropdown" value="#{item.dd}" required="false"
					label="Dropdown" style="width: 100%">

						<f:selectItem itemValue="#{null}" itemLabel="" />
						<f:selectItems value="#{sampleBean.dropDown.entrySet()}"
						var="entry" itemValue="#{entry.value}" itemLabel="#{entry.key}" />
					</p:selectOneMenu>
				</p:column>
				
				<p:column headerText="JSF SelectOne" sortBy="#{item.dd}" filterBy="#{item.dd}"
				filterMatchMode="contains">
					<h:selectOneMenu id="jsfDropDown" value="#{item.dd}" required="false"
					label="Dropdown" style="width: 100%">

						<f:selectItem itemValue="#{null}" itemLabel="" />
						<f:selectItems value="#{sampleBean.dropDown.entrySet()}"
						var="entry" itemValue="#{entry.value}" itemLabel="#{entry.key}" />
					</h:selectOneMenu>
				</p:column>
				
				<p:column headerText="InputText" sortBy="#{item.text}" filterBy="#{item.text}"
				filterMatchMode="contains">
					<p:inputText  value="#{item.text}" required="false" style="width: 100%"/>
				</p:column>
			</p:dataTable>
		</h:form>
```

**Comment by melloware** [comment] 2020-08-06 13:15
Duplicate of: https://github.com/primefaces/primefaces/issues/4446

Please follow that issue.

**Closed as completed by melloware** 2020-08-06 13:15 UTC
Labels: Resolution: Duplicate
