### ISSUE TITLE
sticky headers in dataTable

### ISSUE THREAD

**Issue by henrikthuesen** [primefaces/primefaces#12909] opened 2024-11-19 12:39 UTC
### Describe the bug

Sticky headers do not work for dataTable (and treeTable) when is inside an accordion. I have attached an example based on primefaces-test. 
[primefaces-test.zip](https://github.com/user-attachments/files/17815148/primefaces-test.zip)

### Reproducer

Remove the accordion and the sticky headers work again. 

### Expected behavior

The headers should be sticky also when the table is inside an accordion. 

### PrimeFaces edition

Elite

### PrimeFaces version

14.0.4

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

17.0.10

**Comment by tandraschko** [comment] 2024-11-19 12:42
duplicate of #12802

**Closed as not planned by tandraschko** 2024-11-19 12:42 UTC
Labels: Resolution: Duplicate
