### ISSUE TITLE
User Guide & Testing strategy

### ISSUE THREAD

**Issue by mdzaebel** [primefaces/primefaces#4762] opened 2019-04-26 22:12 UTC
# User Guide
* **Bug links**:
Unfortunaltely, bugs are rediscovered multiple times (e.g. in #4741, #4724 , #2514 [2017]). It would be extremely helpful, if the documentation **links important bugs** (which is easy with the new markdown concept). It would also be helpful to know, whether fixing plans exists or whether it will remain until someone pays for a fix. This would decrease the number of bugs and the satisfaction with PF.
# Testing
* **Component nesting**:
Even simple combinations of components seem to be untested. While showcase demos of single components have continuous high quality and we usually could rely on them, the combination of components (e.g. repeat/treeTable/cellEditor/columns) quickly becomes buggy. In my view, the testing strategy could be extended with automatic permutation of important components up to a certain depth. Additionally, test coverage should include at least the mentioned attributes and events. This would give developers more time to do more important things and to know, that some combinations are not working, is quite valuable, if you are seeking for workarounds. I'm sure, that the quality of the whole PF-Framework would increase quite a bit.

**Comment by tandraschko** [comment] 2019-04-27 08:24
Bug links:
i'm not sure if this makes sense. Everything is documented in the issue list, we or the user just have to check if there is an similar ticket already available. Mirroring this information is just more work. So -1 from my side.

Component nesting:
in generell everything is tested from the PrimeTek QA if it's in the showcase.
Also we had some automatic tests in the past but...
If the community is able to provide test cases and work on how to run them on travis, i would invest some time to provide a base for the whole automatic testing (see primefaces-arquillian)

**Comment by mdzaebel** [comment] 2019-04-27 10:35
**Bug links**: 
May be you're right, linking all bugs would be too much work. What about only linking "fatal" issues? E.g. if a feature is completely unusable (e.g. cellEditInit ...) it should be mentioned. It's difficult to decide for conditionalized issues, but my proposal would be to link issues, that block a main usecase of the component/attribute/event... in the doc. 

**Component nesting**
Yes, showcase QA works brilliant. Certainly right, to integrate automatic nesting/permutation tests with Travis CI and also to enable users to deliver and execute tests. For implementation, we'd need some kind of "_**grammars**_" for components. This would enable automatic generation of XHTML. Open points: Generation of sample beans and UI-tests. May be, the first quick win would be to be able to deliver tests in issues in a way that could afterwards be used in Travis or is this already possible? I found [primefaces-arquillian](https://github.com/primefaces-extensions/primefaces-arquillian) but not sure whats possible/intended with it. It would drastically increase quality/stability and the work for PF developers as you mentioned in [14](https://github.com/primefaces-extensions/primefaces-arquillian/issues/14).

Thanks a lot for your helful comments!

**Comment by tandraschko** [comment] 2019-04-27 11:09
I don't see a benefit of collect such fatal issues. In best case it should just be fixed.
I would only collect incompatibilites, which cant be fixed by design.

"normally" the examples in issues, if runnable, are already good tests.
You would just need to add the xhtml + bean to a "test project", write some statements and asserts like in the example of primefaces-arquillian.
This requires to write some arquillian wrappers in primefaces-arquillian, which can then be automatically used by tests of enduser applications and tests for primefaces itself.

**Comment by melloware** [comment] 2019-04-27 11:41
I would add over the last 2 years I have:

1. Reported any duplicate defects and linked the tickets together like you did by mentioning them and then having the others closed to reduce clutter on the issues list.

2. If an issue is reported multiple times I do my best to try and fix that bug since many people are having the issue.  The one area i usually stay away from is the Datatable bugs (like your CellEditInit) only because the Datatable is so complex I am afraid of introducing more bugs than I fix.

That being said I may try and look at this CellEditInit bug to see if its something obvious that can be fixed easily.

**Comment by melloware** [comment] 2019-07-12 11:13
Closing this question for now as it has been answered.

**Closed as completed by melloware** 2019-07-12 11:13 UTC
Labels: question
