### ISSUE TITLE
instead of empty value UploadedFile has null value

### ISSUE THREAD

**Issue by pranav-malanthra** [primefaces/primefaces#1166] opened 2016-02-18 10:35 UTC
Without selecting a file in p:fileUpload and do submit the form, in 5.0 UploadedFile object will have empty data(just like new DefaultUploadedFile(FileItem)). But in 5.3 UploadedFile object has null value. So i am facing null pointer exception since i upgraded to 5.3.

**Comment by tandraschko** [comment] 2016-02-18 12:37
Why not just add a null check?

**Comment by pranav-malanthra** [comment] 2016-02-18 13:54
I created my project using 5.2. If I go for a null check then I have to change my code several places.

**Comment by tandraschko** [comment] 2016-02-18 13:59
it's always possible that you need to modify your code on some places. you upgraded to a major version, not a bugfix version.

**Comment by kukel** [comment] 2016-02-18 19:59
@tandraschko: 5.2 -> 5.3 is 'officially' not a major versionThis is correct, but...

PF has proven in the past to  not always guarantee backwardscompatibility. And in several cases even an upgrade from 5.0 to 5.1 to 5.2 was not possible since a bug (only fixed in an elite release) prevented upgrading from 5.0 to 5.1 and a new bug (again only fixed in an elite release) prevented upgrading from 5.1 to 5.2... Imo PF should, right after a 'major release' have a .a//b community release with some fixes.

**Closed as completed** 2017-07-14 08:37 UTC
Labels: Resolution:  Wontfix
