### ISSUE TITLE
inputMask: regression in branch master.

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#3644] opened 2018-05-04 20:41 UTC
In Primefaces 6.2 this code works if the input is 999 or 9 or 99999999 (max)
but _master_ throws a NullPointerException when 999 (when length not equals 1 or max)

`<p:inputMask mask="9?9999999" maxlength="7" size="9" value="#{movimentoVeiculoBean.movimento.odometroAtual}" id="odatual"><p:ajax listener="#{movimentoVeiculoBean.validarOdometro()}" process="@this" update="movimentacoes:odatual,movimentacoes:salvar"/></p:inputMask>`

**Comment by tandraschko** [comment] 2018-05-04 22:00
@cnsgithub could you please check it? As i said, there are always cases when something breaks.

**Comment by cnsgithub** [comment] 2018-05-07 07:06
This issue is not conform with the template. 

Furthermore, I cannot reproduce it by using modified showcase:
`                <p:inputMask id="issue" value="#{maskView.phone}" mask="9?9999999" maxlength="7" size="9"/>                
`

> As i said, there are always cases when something breaks.

@tandraschko For this reason, more time should be invested in the design at the beginning. :stuck_out_tongue_winking_eye:

**Comment by tandraschko** [comment] 2018-05-07 07:48
Ok, lets close it until the issue is conform to our template and the example is complete.

**Closed as completed by tandraschko** 2018-05-07 07:48 UTC
Labels: Resolution: Invalid

**Comment by erickdeoliveiraleal** [comment] 2018-05-07 16:18
Bean
```
package org.primefaces.test.org.primefaces.test;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	Integer atual;

	public void validarOdometro() {
		System.out.println("test");
		System.out.println(atual);

	}

	public Integer getAtual() {
		return atual;
	}

	public void setAtual(Integer atual) {
		this.atual = atual;
	}
}
```

XHTML
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>

	<h:form>

		<p:inputMask mask="9?9999999" maxlength="7" size="9"
			value="#{testView.atual}">

			<p:ajax listener="#{testView.validarOdometro}" />

		</p:inputMask>
	</h:form>

</h:body>
</html>
```

**Comment by tandraschko** [comment] 2018-05-07 18:50
Can you can check again @cnsgithub ?
