### ISSUE TITLE
DataTable: Focus on paginator is not consistent with highlighted page number

### ISSUE THREAD

**Issue by MKhlon** [primefaces/primefaces#2567] opened 2017-07-24 10:23 UTC
1) Environment
- PrimeFaces version: 6.0.16
- Application server + version: 8.5.8
- Affected browsers: IE 11, Edge, FF

 2) Expected behavior
Focus and highlighting for the page number are consistent. If page 8 is selected, it's opened, highlighted and focus is on page 8.

 3) Actual behavior
Focus and highlighting for the page number are inconsistent. If page 8 is selected, it's opened, highlighted but focus is on page number where 8 was (in this case it will be on page 10).

4) Steps to reproduce
- Table with 20 pages is required. Page numbers from 1 to 10 are displayed on the page.
- Click on page number 8. (for pages 1-6 it's ok because only for numbers starting from 7, highlighted page is centered automatically.)
- So focus stays where user clicked but as more pages are loaded now here is placed not page that is opened. 
- As the result highlighted is correct page but focus is on page a few numbers ahead).

5) Sample XHTML
<pre><code><span class="ui-paginator-pages"><a tabindex="0" class="ui-paginator-page ui-state-default ui-corner-all" aria-label="Page 13" href="#">13</a><a tabindex="0" class="ui-paginator-page ui-state-default ui-corner-all" aria-label="Page 14" href="#">14</a><a tabindex="0" class="ui-paginator-page ui-state-default ui-corner-all" aria-label="Page 15" href="#">15</a><a tabindex="0" class="ui-paginator-page ui-state-default ui-corner-all" aria-label="Page 16" href="#">16</a><a tabindex="0" class="ui-paginator-page ui-state-default ui-corner-all" aria-label="Page 17" href="#">17</a><a tabindex="0" class="ui-paginator-page ui-state-default ui-corner-all ui-state-active" aria-label="Page 18" href="#">18</a><a tabindex="0" class="ui-paginator-page ui-state-default ui-corner-all" aria-label="Page 19" href="#">19</a><a tabindex="0" class="ui-paginator-page ui-state-default ui-corner-all ui-state-focus" aria-label="Page 20" href="#">20</a><a tabindex="0" class="ui-paginator-page ui-state-default ui-corner-all" aria-label="Page 21" href="#">21</a><a tabindex="0" class="ui-paginator-page ui-state-default ui-corner-all" aria-label="Page 22" href="#">22</a></span> </code></pre>

**Comment by tandraschko** [comment] 2017-07-24 19:48
Is it reproducable in the showcase? Link?
Please provide a better description in "steps to reproduce".

**Comment by MKhlon** [comment] 2017-07-24 20:13
It's not reproducible in showcase because showcase has only 10 pages, for this behavior more pages are required, for example 20. Steps to reproduce will be updated in a minute. I'll add gif movie tomorrow.

**Comment by MKhlon** [comment] 2017-07-26 09:22
![2017-07-26_11-18-22](https://user-images.githubusercontent.com/29551612/28614035-a7df2838-71f4-11e7-8576-2ccb8bf7956a.gif)

**Comment by jxmai** [comment] 2017-07-26 17:53
@MKhlon I cannot replicate this issue although there was clearly something off based on the gif you provided, but it could be theme related. Any example code you can provide ?

![image](https://user-images.githubusercontent.com/10467831/28635775-625ddcb6-7201-11e7-8119-1ae13713119b.png)

**Comment by MKhlon** [comment] 2017-07-28 12:42
Hi, I was able to reproduce it with showcase 6.1 source with following steps:
In our application we highlight where focus is but in showcase focus is not highlighted however the problem is still present as focus is not in line with open page.

1. change in paginator.xthml for p:dataTable rows value to ='2' (line 19)
2. click on page 10
3. click on page 13
4. press 'Tab'
Expected:
focus should be on page 14
Actual:
focus is on page 17

another example:
1. change in paginator.xthml for p:dataTable rows value to ='2' (line 19)
2. click on page 10
3. click on page 13
4. press Enter

Expected result:
user stays on page 13

Actual result:
page 16 is shown

**Comment by jxmai** [comment] 2017-10-16 03:22
@MKhlon I can replicate this issue now by following your step to replicate.  I see what went wrong in the primefaces codebase, but fixing this issue can be a bit challenging since we need to make sure not to break the existing codebase since the js file is used in multiple places.

For your info, here is what went wrong.

In `paginator.js`


https://github.com/primefaces/primefaces/blob/2692e9ae6f5aeeea3c89b25b57957342bb2ff706/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js#L273-L275

The tabindex algorithm does not correctly handle your special case

https://github.com/primefaces/primefaces/blob/2692e9ae6f5aeeea3c89b25b57957342bb2ff706/src/main/resources/META-INF/resources/primefaces/paginator/paginator.js#L240-L246

**Comment by melloware** [comment] 2019-06-29 15:11
@jxmai @MKhlon I believe this was fixed with this fix: https://github.com/primefaces/primefaces/issues/830

**Comment by jxmai** [comment] 2019-06-30 04:52
@melloware You're right. https://github.com/primefaces/primefaces/commit/e685fc6b0f574bdfa330bcf99d8e531fe979e199 fixed this issue. Thanks for pointing it out !

**Closed as completed** 2019-06-30 11:56 UTC
Labels: Resolution: Duplicate
