### ISSUE TITLE
PickList: drag&drop of multiple selected items not working as expected

### ISSUE THREAD

**Issue by weiprd** [primefaces/primefaces#8375] opened 2022-02-02 13:33 UTC
If you select more than one item in the PickList by holding down the crtl-key and move them with drag&drop, only one item will be moved.

**Environment**
PrimeFaces V11.0.0
Problem occurres on Chrome, Firefox and Edge.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the PickList showcase https://www.primefaces.org/showcase/ui/data/pickList.xhtml?jfwid=5fcaa
2. Select two or more items from the left list by holding down crtl-key 
3. Drag and drop these items to the right list
4. Only one item is dropped to the right list
5. Same behaviour occurred if you drag&drop multiple items from right to left or if you try to change the sort order of multiple selected items manually

**Expected behaviour**
All selected items should be dropped.

**Comment by melloware** [comment] 2022-02-02 14:13
Is this a duplicate of this: https://github.com/primefaces/primefaces/issues/1081

**Closed as completed** 2022-02-02 14:34 UTC
Labels: Resolution: Duplicate
