### ISSUE TITLE
Link: Ajax Navigation

### ISSUE THREAD

**Issue by lazaronixon** [primefaces/primefaces#5976] opened 2020-06-01 23:32 UTC
**Description**
One of reasons for dissemination of single-page applications is the performance it brings with navigation between screens without the cost of a full page load, specially JS/CSS. JSF 2.3 advanced a lot when the subject is GET requests with `h:link`, `f:metadata` and `f:viewAction` check my project [JSF-PERFECT-CRUD](https://github.com/lazaronixon/jsf-perfect-crud) to check how much I use it on my applications. 

Would be great primefaces provide a way to navigate between pages without a full HTTP request and this way provide the feeling of single-page applications without the added complexity of a client-side JavaScript framework.

**Describe the solution you would like**
- First implementation could be on `p:link`, when user set `ajax=true` primefaces changes the browser’s URL using the History API, update `h:body` with content of new page and merge his `h:head`.
- Second would be on all components that implements `action` property, when a action with `?redirect=true` is performed, a AJAX navigation needs to be handled.

I know it is not a simple thing to do and maybe changes a lot original JSF navigation but I was there when @cagataycivici made things like client-side validations.

**Additional context**
Some inspiration can be found on [Turbolinks](https://github.com/turbolinks/turbolinks) and [PJAX](https://github.com/MoOx/pjax).

**Example XHTML**
```xml
<h:link value="List Students" outcome="/views/students/index.xhtml" ajax="true" />
```

**Comment by tandraschko** [comment] 2020-06-02 07:17
duplicate of #1418

**Comment by tandraschko** [comment] 2020-06-02 07:18
i wont work on it and im not sure if we will change the internals to rely on turbolink.

**Comment by lazaronixon** [comment] 2020-06-02 10:33
I change my mind about use turbolinks.. but instead, a new navigation handle almost like dynamic dialog... and we can use native JSF ajax for that maybe it can make the work...

**Comment by tandraschko** [comment] 2020-06-02 10:46
Feel free to work on a PR ;)

**Comment by lazaronixon** [comment] 2020-06-02 10:49
Ok I will work on something...

**Comment by melloware** [comment] 2020-06-16 12:51
@lazaronixon I am going to close this ticket but will happily re-open if it you submit a quality PR.  As I don't think Primetek or any of the community are ever going to implement this ticket.

**Closed as completed by melloware** 2020-06-16 12:51 UTC
Labels: new feature

**Comment by lazaronixon** [comment] 2020-06-16 13:26
Soon...

**Comment by GedMarc** [comment] 2020-06-16 14:23
+100, MPA's is the only thing making PF unusable for post mobile-wave applications

**Comment by GedMarc** [comment] 2020-06-16 14:27
But i'm not going to help doing it that way, agree with Thomas, if you can't do it using raw JS or JQuery, don't give it an attempt. 

Wonder if I should actually ... hmm
