### ISSUE TITLE
TextEditor: inside TabView don't load hidden input field

### ISSUE THREAD

**Issue by p1Machado** [primefaces/primefaces#2905] opened 2017-11-07 16:50 UTC
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? Didn't try yet.
- Application server + version: Tomcat 8.0
- Affected browsers: Chrome and IE11 (didn't test any other)

## 2) Expected behavior

If a texteditor is placed inside a tabview's tab, it should load the hidden input field eagerly, even if don't open the tab where the texteditor is placed.

## 3) Actual behavior

If a texteditor is placed inside a tabview's tab, the hidden input field is not loaded unless I click the tab. Then, if I submit the form without clicking the tab, it will set a blank value.

This is the first tab that is displayed:
![image](https://user-images.githubusercontent.com/16403518/32505095-773eae58-c3c8-11e7-86b2-b1deb36cacfb.png)

Before I click the tab "Descrição", which contains a texteditor, the hidden input field is blank:
![image](https://user-images.githubusercontent.com/16403518/32505221-ca317d84-c3c8-11e7-8ee7-6e3e4787193b.png)

If I click the tab containing the texteditor, it's value is loaded:
![image](https://user-images.githubusercontent.com/16403518/32505147-95b79ff2-c3c8-11e7-9ec5-d08fdd3db7cf.png)
![image](https://user-images.githubusercontent.com/16403518/32505998-ab34ecb6-c3ca-11e7-8f96-bb1d83a5b542.png)

## 4) Steps to reproduce

1. Create a form with a text editor input;
2. Place it inside the second tab of a tabview;
3. Set the value of the texteditor in the bean init method;
4. Access the page;
5. Submit the form and the value will be overriden;

## 5) Sample XHTML

```
<h:form id="form">
<p:tabView id="tabView" >
<p:tab id="fisrt" title="First" >
...
</p:tab>
<p:tab id="second" title="Second" >
<p:textEditor
				id="textEditor"
				widgetVar="textEditorWidget"
				value="#{sampleBean.textEditorValue}" />
</p:tab>
</p:tabView>
</h:form>
```

## 6) Sample bean

...

ps.: I can update the issue to provide more content to reproduce if needed.

**Comment by melloware** [comment] 2017-11-07 19:38
It might be easier to create a fully reproducible test case using this test harness project and attach it here:

Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.

**Comment by tandraschko** [comment] 2017-11-07 19:49
Your example is not runnable for us - please update it or we will close it as invalid.

**Comment by p1Machado** [comment] 2017-11-07 19:50
OK. Just give me a little time and I will provide it

Em ter, 7 de nov de 2017 17:49, Thomas Andraschko <notifications@github.com>
escreveu:

**Comment by jxmai** [comment] 2017-11-07 19:56
OK, I could replicate the issue, but please attach a runnable project next time.

Here is the code:

[primefaces-test-2905.zip](https://github.com/primefaces/primefaces/files/1451414/primefaces-test-2905.zip)


```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>PrimeFaces Test</title>
</h:head>
<h:body>

	<h:form>
		<p:tabView>
			<p:tab title="tab1">
				<p:textEditor value="#{testView.test}"></p:textEditor>
			</p:tab>
			<p:tab title="tab2">
				<p:textEditor value="#{testView.test2}"></p:textEditor>
			</p:tab>
			<p:tab title="tab2">
				<p:inputText value="#{testView.test3}"></p:inputText>
			</p:tab>
		</p:tabView>

		<p:commandButton value="Test"
			actionListener="#{testView.testCommandButton()}" process="@form"></p:commandButton>
	</h:form>

</h:body>
</html>
```


```java
package org.primefaces.test;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 812243260866629419L;
    private String test = "test";
    private String test2 = "test2";
    private String test3 = "test3";

    public void testCommandButton() {
        System.out.println(test);
        System.out.println(test2);
        System.out.println(test3);
    }

    public String getTest() {
        return test;
    }

    public void setTest(String test) {
        this.test = test;
    }

    public String getTest2() {
        return test2;
    }

    public void setTest2(String test2) {
        this.test2 = test2;
    }

    public String getTest3() {
        return test3;
    }

    public void setTest3(String test3) {
        this.test3 = test3;
    }
}

```



![image](https://user-images.githubusercontent.com/10467831/32514657-558f848a-c3c3-11e7-84c6-d5aae94d23ac.png)


In the console, ```<p>test2</p>``` is missing when we click test directly without clicking tab2

console
```
<p>test</p>

test3

```

**Comment by p1Machado** [comment] 2017-11-07 20:20
Thank you @jxmai. This is the first time I interact here. Next time I will provide a running sample.

This is the issue, looks like Quill just didn't started, maybe it depends on rendering the element or some other event (like keyup or change).

**Comment by jxmai** [comment] 2017-11-07 20:26
No problem :) Most components  trigger `this.renderDeferred();` on init so when the view is not visible, they don't render. The problem here might be something deeper since I didn't see any obvious mistake at first glance. If you are willing to take a look to help solving the issue that will be great.

**Comment by p1Machado** [comment] 2017-11-07 20:37
I have a busy week at college right now, at the weekend I might try to figure out some solution.

**Comment by jxmai** [comment] 2017-11-07 21:52
Nevermind, I figured out the cause. I will raise a patch shortly.

**Closed as completed** 2017-11-08 08:20 UTC
Labels: :lady_beetle: defect

**Comment by p1Machado** [comment] 2017-11-08 11:39
Nice!

Since I want to keep my project in 6.1 right now, I simply copied the fix into a subclass of TextEditorRenderer and registered this new renderer:

```
package br.com.tindo.util.primefaces;

import java.io.IOException;

import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.context.ResponseWriter;

import org.primefaces.component.texteditor.TextEditor;
import org.primefaces.component.texteditor.TextEditorRenderer;
import org.primefaces.util.ComponentUtils;

/**
 * {@link https://github.com/primefaces/primefaces/issues/2905}
 * @author Patrick Machado
 */
public class TextEditorRendererPatch2905 extends TextEditorRenderer {

	@Override
	protected void encodeMarkup(FacesContext context, TextEditor editor) throws IOException {
		ResponseWriter writer = context.getResponseWriter();
		String clientId = editor.getClientId(context);
		String valueToRender = ComponentUtils.getValueToRender(context, editor);
		String inputId = clientId + "_input";
		String editorId = clientId + "_editor";
		UIComponent toolbar = editor.getFacet("toolbar");

		String style = editor.getStyle();
		String styleClass = editor.getStyleClass();

		writer.startElement("div", editor);
		writer.writeAttribute("id", clientId, null);
		if (style != null)
			writer.writeAttribute("style", style, null);
		if (styleClass != null)
			writer.writeAttribute("class", editor.getStyleClass(), null);

		if (toolbar != null) {
			writer.startElement("div", editor);
			writer.writeAttribute("id", clientId + "_toolbar", null);
			writer.writeAttribute("class", "ui-editor-toolbar", null);
			toolbar.encodeAll(context);
			writer.endElement("div");
		}

		writer.startElement("div", editor);
		writer.writeAttribute("id", editorId, null);
		if (valueToRender != null) {
			writer.write(valueToRender);
		}
		writer.endElement("div");

		writer.startElement("input", null);
		writer.writeAttribute("type", "hidden", null);
		writer.writeAttribute("name", inputId, null);
		// #2905
		if (valueToRender != null) {
			writer.writeAttribute("value", valueToRender, null);
		}
		writer.endElement("input");

		writer.endElement("div");
	}

}
```

```
	<render-kit>
		<renderer>
			<component-family>org.primefaces.component</component-family>
			<renderer-type>org.primefaces.component.TextEditorRenderer</renderer-type>
			<renderer-class>br.com.tindo.util.primefaces.TextEditorRendererPatch2905</renderer-class>
		</renderer>
	</render-kit>
```


Thank you, guys! ;D
