### ISSUE TITLE
DataTable: Paging slow when using selection

### ISSUE THREAD

**Issue by chaloma1** [primefaces/primefaces#12196] opened 2024-06-27 11:24 UTC
### Describe the bug

Having datatable with selection. Using selectionPageOnly="false". Tried to generate 7000 records when i found out page change is taking too long. Still not sure what exactly is wrong, but on our spring boot server, a single page change takes **2-5 minutes**. Unfortunately on reproducer which is on Jetty takes less time but it is still noticable 10-15s. 

1) First note is that i need to have all records selected on start / table load, that is why i put all the records inside selection list before page load instead using some ajax to call table.selectAllRows() method. I did notice when i **click the unselect all and then again select all checkbox, the requests are lot faster (200-400ms)** which is great...

2) Second note is that on reproducer i had to put this line in Jetty config file. These form settings might have the speed difference effect.
`"<Set name="maxFormContentSize" type="int">600000</Set>"`

Using Primefaces 13.0.10, but tried on 14.0.1 with the same result. Would be great to have fix made into 13.0.11 where i am waiting for similar/related bugfix https://github.com/primefaces/primefaces/issues/11885. Thank you.

### Reproducer

[table-paging.zip](https://github.com/user-attachments/files/16012583/table-paging.zip)

### Expected behavior

Selected record count should not have effect on page change speed. 

### PrimeFaces edition

Elite

### PrimeFaces version

13.0.10

### JSF implementation

Mojarra

### JSF version

4.0.6

### Java version

17

**Comment by tandraschko** [comment] 2024-06-27 11:54
sorry but i dont think 7000 items makes sense as non-lazy datatable
it will also be serialized in session, because you have a viewscoped bean
thats a big anti pattern

**Comment by chaloma1** [comment] 2024-06-27 12:27
I do agree that it is not perfect, but that is how the BE service is designed. 7000 is probably the maximum amount that can be in a table (and it is not a standard example)... So when i will use lazy, I cannot select it all, i will have to make new checkbox that is gonna call the service without paging and it will probably not be checked in the table as selected. 

Seeing how fast it is when i use the table select all checkbox, it makes me think that there is no perfomance issue, just a programming one...

**Comment by Rapster** [comment] 2024-06-27 17:51
> I do agree that it is not perfect, but that is how the BE service is designed. 7000 is probably the maximum amount that can be in a table (and it is not a standard example)... 

Then you have to deal with the consequences of a bad "design". If your team is still happy with this, you can always create your own model and do something like:

```java
public class TestListDataModel extends ListDataModel<TestObject> implements SelectableDataModel<TestObject> {

    private Map<String, TestObject> cache;

    public TestListDataModel(List<TestObject> list) {
        super(list);

        cache = list.stream().collect(Collectors.toMap(TestObject::getId, Function.identity()));
    }

    @Override
    public String getRowKey(TestObject object) {
        return object.getId();
    }

    @Override
    public TestObject getRowData(String rowKey) {
        return cache.get(rowKey);
    }
}
```


> So when i will use lazy, I cannot select it all, i will have to make new checkbox that is gonna call the service without paging and it will probably not be checked in the table as selected.

Not following...  

> Seeing how fast it is when i use the table select all checkbox, it makes me think that there is no perfomance issue, just a programming one...

They are two differents things, when you select all, all happens on client side, when you paginate, datatable gets processed on server side

**Comment by chaloma1** [comment] 2024-06-28 08:45
Thank you for the model example, might try it as a workaround. 

Tried using Jprofiler to see what exactly is wrong. Time can be slowered by Jprofiler because it took way longer (had to use only 3000 records to get faster result). First picture shows 4,5 milion invocations. Second picture is after i use table native unselect and select all checkbox and start paging after that.

Regular paging
![pf-test-invocation](https://github.com/primefaces/primefaces/assets/34541767/4199cc31-70a8-42c7-95ae-0f3757ef168c)

Paging after unselect/select all
![pf-test-invocation-after-selectAll](https://github.com/primefaces/primefaces/assets/34541767/893dbdb8-4c03-4514-97b5-681c21b0acde)

As you can see, after unselect/select all - getRowKey() is getting constant calling incremented by the number of records. Could you have a look at that?

**Comment by Rapster** [comment] 2024-06-28 09:30
By regular paging, you mean simple paging without selection? In that case, the first stacktrace is not expected indeed...

**Comment by chaloma1** [comment] 2024-06-28 09:40
By regular paging i mean i don't click on native unselect/select all. Selection (all records) is always made in java on init.

**Comment by chaloma1** [comment] 2024-06-28 09:44
Btw i also noticed, problem will be somewhere inside the selection. Because if i am having table completely without selection options, the paging works well...

**Comment by Rapster** [comment] 2024-06-28 10:41
Ok, so your problem has already been explained to you. As long you have selected items, and huge amount of items loaded, you will face that issue.

**Comment by martin654** [comment] 2024-06-28 11:38
Hi guys, could you please explain the difference in performance between the two scenarios? Why is it linear in one case and exponential in other?

**Comment by Rapster** [comment] 2024-06-28 11:42
which scenarios?

**Comment by melloware** [comment] 2024-06-28 12:42
Yes @martin654 @chaloma1 it is very unclear exactly what you are doing I think you need to spell it out step by step like.

1. Load page.
2. Click on Select All checkbox
3. Page to Page 2 and see it takes 3 minutes...

That kind of step by step exact scenarios.

**Comment by martin654** [comment] 2024-06-28 12:59
Hi, 
I tested the reproducer project from @chaloma1 with following scenario:

1. Page load - load time is OK 
2. Click on Second page - it takes 12s
3. Click on Third page - it takes 12s
4. Back to second page - it takes 12s
5. Unselect all - no request (client side event)
6. Click on First page - it takes 12s - all items are selected (probably fixed in 13.0.11) 
7. Unselect all - no request (client side event)
8. Select all - no request (client side event)
9. Click on Second page - it takes 40ms !!
10. Clicking on various pages - it takes 40ms

Please see attached GIF with this scenario:
![datatable_performance](https://github.com/primefaces/primefaces/assets/22746146/b746c5cc-a949-4b89-9912-8056af6510c1)

The scenarios I was talking above were the two situations from jprofiler - 12s call (with quadratic complexity) vs 40ms call

**Comment by melloware** [comment] 2024-06-28 13:03
@martin654 thanks for the detailed analysis. @Rapster does this change your opinion at all?  It does seem odd 12 seconds down to 40 milliseconds?

**Comment by Rapster** [comment] 2024-06-28 14:27
yes much better, i'll have a look. thanks @martin654 for clarifying

**Comment by Rapster** [comment] 2024-06-28 16:39
Ok I see, when you use the toggle, only one rowKey is used: `@all` instead of 7000 rowKeys, so 7000 iteration are made per page event instead of 7000².

**Comment by Rapster** [comment] 2024-06-29 11:01
One way to fix that problem would be to give the possibility to set the default "select all" value, but from the moment you unselect one item you might end up on the very same problem and probably this one also #11556

**Comment by martin654** [comment] 2024-07-01 09:44
Hi,
thank you for your feedback. I have a few questions:

1. Do I understand the mechanism correctly?
For each element in datatable you have to traverse the whole "selected" list and check equals on the rowKey on both elements?

From performance point of view it would be much better to store "selected" items in some hash-map like structure, like you mentioned above: https://github.com/primefaces/primefaces/issues/12196#issuecomment-2195311409

2. When I use "select all", the datatable uses @all instead of 7000 elements, so it runs much faster?

3. It seems like this algorithm is triggered on each pagination event, why is that? We want to display certain page, why do we re-calculate the whole datatable?


We decided to do it differently in our use case so we don't have to handle this huge dataset with selection feature. At this point I just want to better understand the problem and possilby be helpfull to improve PF performance in this case.

**Comment by Rapster** [comment] 2024-07-01 09:59
> For each element in datatable you have to traverse the whole "selected" list and check equals on the rowKey on both elements?

Iterate through list would be a better term _(traverse is more tree related)_ but yes, to fill `DataTable#selection` attr you need to iterate over every rowKey and find in the loaded data, the corresponding bean.

> From performance point of view it would be much better to store "selected" items in some hash-map like structure, like you mentioned above: https://github.com/primefaces/primefaces/issues/12196#issuecomment-2195311409

I believe I did a PR in the past that got reverted for some reasons, but anyway using lazy mode is the easiest/quite efficient way to go about it

> When I use "select all", the datatable uses https://github.com/ALL instead of 7000 elements, so it runs much faster?

Yes, it's one single rowKey (it's an alias, nothing to do with PFS `@all` btw...) that says "all row keys" which will run the algorithm much faster as it is only one rowKey (and not 7000...)

> It seems like this algorithm is triggered on each pagination event, why is that? We want to display certain page, why do we re-calculate the whole datatable?

Because pagination triggers a new HTTP request, and therefore requires to decode the dataTable component. I guess there could be a way of improving the algorithm, but in a situation like yours, you're supposed to use lazy mode, so not sure it worth the effort to cover this use case

**Comment by melloware** [comment] 2024-07-01 11:47
I agree with @Rapster this is exactly why `lazy` exists.   Loading 7000 rows in a databable to me does not make sense from a performance perspective period and the `lazy` scenario alleviates all of these issues.

**Closed as not planned** 2024-07-01 15:49 UTC
Labels: :zap: performance, discussion

**Comment by tandraschko** [comment] 2024-07-01 15:56
I feel like it could maybe improved to better support @all selection but no time here
