### ISSUE TITLE
Tablecell border has changed between version 14.0.6 and 14.0.7

### ISSUE THREAD

**Issue by janniksteen** [primefaces/primefaces#12948] opened 2024-11-25 14:03 UTC
### Describe the bug

1) Run the attached tester. It has PF 14.0.7 when unpacked. Observe table cell borders.
2) Change to PF 14.0.6 in pom.xml
3) Run tester. Observe table cell borders.

### Reproducer

[primefaces-test.zip](https://github.com/user-attachments/files/17903978/primefaces-test.zip)
![PF-14 0 7](https://github.com/user-attachments/assets/7be30865-4259-426f-b463-a7ff7345d696)
![PF-14 0 6](https://github.com/user-attachments/assets/0a39dc17-52f0-4ba3-bba5-a0fc43d24d7d)

### Expected behavior

I expect table cells to have the same border in each case.

### PrimeFaces edition

Elite

### PrimeFaces version

14.0.7

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

4.0.x

### Java version

21

### Browser(s)

Version 122.0.6261.111, Firefox 132.0.1 (64-bit)

**Comment by melloware** [comment] 2024-11-25 14:24
Duplicate of https://github.com/primefaces/primefaces/issues/12819 i will be releasing 14.0.8 today

**Closed as not planned** 2024-11-25 14:29 UTC
Labels: Resolution: Duplicate
