### ISSUE TITLE
dialog framework does not work well in 6.0RC3

### ISSUE THREAD

**Issue by hyogacs** [primefaces/primefaces#1393] opened 2016-05-09 08:02 UTC
We updated to 6.0 and there is a problem in DialogFramework.
The dialog'position seems default on the center of screen,even when the dialog is lagrer than the base page that we have to move it.
![ws000001](https://cloud.githubusercontent.com/assets/13062206/15106950/a2c07efa-1607-11e6-8cbd-d62da6df4c82.JPG)
But it works good in 5.3.
![ws000002](https://cloud.githubusercontent.com/assets/13062206/15106951/a2c5775c-1607-11e6-868e-1c74f186d669.JPG)

**Comment by Rapster** [comment] 2016-05-17 21:32
Looks like a duplicate of this #1290

**Comment by arunvc1** [comment] 2016-06-22 04:35
work around found in forum 
http://forum.primefaces.org/viewtopic.php?f=3&t=40364

**Comment by Maikel-Nait** [comment] 2017-06-20 05:11
I found a "better" solution myself, explained in the duplicated issue #1290 
Maybe you can also take a look ...

**Closed as completed** 2017-10-17 08:25 UTC
Labels: :lady_beetle: defect
