### ISSUE TITLE
Autocomplete (multiple) removes wrong items

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#178] opened 2015-04-27 12:12 UTC
You can test the following behaviour in the showcase: http://www.primefaces.org/showcase/ui/input/autoComplete.xhtml

Add some items to the autocomplete (multiple mode) WITH duplicates. Remove an item that occurs multiple times in the selection. All duplicates will be removed from the underlaying select-input, but the GUI will still contain the duplicates.
You can either verify it by using something like firebug or simply press "submit" in the showcase and see the list in the dialog.

**Comment by sudheerj** [comment] 2015-05-31 18:43
Duplicate of issue #365

**Closed as completed** 2015-06-01 04:09 UTC
Labels: Resolution: Duplicate
