### ISSUE TITLE
ColumnToggler: removes the Responsive priority of the selected columns

### ISSUE THREAD

**Issue by RejDev** [primefaces/primefaces#348] opened 2015-05-26 23:38 UTC
Hello,
interaction with `<p:columnToggler>` removes the 'Responsive' priority of the selected columns.
ex:
uncheck then re-select the display of a column, it will lose its priority when resizing.

Thanks.

**Comment by cagataycivici** [comment] 2015-05-27 09:35
What do you mean by priority, do you mean for responsiveness?

**Comment by RejDev** [comment] 2015-05-27 09:41
Responsive - Column Priority , 
example:
http://www.primefaces.org/showcase/ui/data/datatable/responsive.xhtml

**Comment by cagataycivici** [comment] 2015-05-28 08:54
I'll check, thanks.

**Comment by sudheerj** [comment] 2015-06-23 19:40
@RejDev 
I tried to replicate the issue.We need to unselect all the toggler checkboxes and then re-select all checkboxes then only the issue is replicated(even though column priority styles are still applied).Not replicated for the specific column.Isn't it?

**Comment by melloware** [comment] 2020-12-15 20:41
Going to close this for now as I am not quite sure what the issue is and no reproducer is provided.  If someone provides a reproducer I will gladly reopen it.

**Closed as completed by melloware** 2020-12-15 20:41 UTC
Labels: :lady_beetle: defect
