### ISSUE TITLE
Text Editor : Support Image Handling instead of  Base64  encoding 

### ISSUE THREAD

**Issue by ravihariharan** [primefaces/primefaces#4841] opened 2019-05-27 20:04 UTC
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: NA
- Affected browsers: NA

## 2) Expected behavior

How to insert images by uploading to the server instead of Base64 encoding the images?
https://github.com/quilljs/quill/issues/1089

Can we review how the above feature can be incorporated within primefaces ? 
...

**Comment by tandraschko** [comment] 2019-05-27 20:12
doesnt look like the issue is resolved.

**Comment by ravihariharan** [comment] 2019-05-27 20:24
there seems to be more than 1 solution and i cannot find a recommended approach.  let me review a bit more.

**Comment by melloware** [comment] 2019-05-29 17:44
@ravihariharan Isn't this a duplicate of this ticket: https://github.com/primefaces/primefaces/issues/4452 ???

**Comment by tandraschko** [comment] 2019-05-29 20:18
yup, seems to

**Closed as completed by tandraschko** 2019-05-29 20:18 UTC
