### ISSUE TITLE
SelectOneMenu: Unable to set autocomplete

### ISSUE THREAD

**Issue by Rawi01** [primefaces/primefaces#3512] opened 2018-03-22 13:49 UTC
## 1) Environment
- PrimeFaces version: **6.2**
- Does it work on the newest released PrimeFaces version? **No**
- Does it work on the newest sources in GitHub? **No**
- Application server + version: **WildFly 10.1**
- Affected browsers: **Firefox**

## 2) Expected behavior

Setting `<f:passThroughAttribute name="autocomplete" value="off" />` on a SelectOneMenu should disable autocomplete after a page refresh.

## 3) Actual behavior

The passThroughAttribute doesnt get added to the hidden `<select>` which consequently leads to a dropdown that keeps its value on refresh.

## 4) Steps to reproduce

```
<p:selectOneMenu value="#{viewScopedView.value}">
    <f:passThroughAttribute name="autocomplete" value="off" />
    <f:selectItem itemValue="A" itemLabel="Label A" />
    <f:selectItem itemValue="B" itemLabel="Label B" />
</p:selectOneMenu>
```

Select Label B
Page refresh (F5)

Expected: Label A is selected
Actual: Label B is selected

---
This behaviour was introduced with 3383ddd1

**Comment by cnsgithub** [comment] 2018-03-22 13:57
`f:passThroughAttribute` and` f:passThroughAttributes` have been introduced in JSF 2.2. Currently, PrimeFaces uses `pt:` namespace attributes to achieve what you want to do. However, `p:selectOneMenu `lacks support for passthrough.

**Comment by cnsgithub** [comment] 2018-03-22 13:58
> This behaviour was introduced with 3383ddd

Ok, that means it had worked before? Then forget about my previous answer...

**Comment by tandraschko** [comment] 2018-03-22 16:26
The problem is that passtrough attributes were rendered multiple times, on multiple elements.
We decided to only apply it on the root component for now.

**Comment by tandraschko** [comment] 2018-10-02 09:45
@cagataycivici currently stumbled upon this again.
As you assigned @HuseyinTurkmenoglu, i think you would like to work on it?

If yes, we should talk about it as it needs some work.
We may need something like a own "passThroughAttributes" tag, which has a scope or facet.

maybe something like:
`passThroughAttributes for="root"` (targets the rendered root element)
or
'passThroughAttributes for="select" (targets the select tag)

this really needs some basic work.
Appliying the f:passThroughAttributes to multiple components or to another tag (!= root) is wrong for me.

**Comment by tandraschko** [comment] 2019-11-19 12:52
Created a issue in the JSF specs: https://github.com/eclipse-ee4j/faces-api/issues/1481

As you are the only user currently with this feature request, i think we can close it for now and wait for JSF3.

**Closed as completed by tandraschko** 2019-11-19 12:52 UTC
Labels: :lady_beetle: defect

**Comment by Rawi01** [comment] 2019-11-19 16:42
Thanks for the update, would be great to get it in JSF3. I solved this problem using a custom renderer, guess that I have to maintain it for some time :smile:
