### ISSUE TITLE
SelectOneRadio: not displaying the input (circles)

### ISSUE THREAD

**Issue by lelduayen** [primefaces/primefaces#5216] opened 2019-10-03 20:01 UTC
## 1) Description
I've just updated to 6.2.25 and the select one radios stop displaying.

The problem is [this commit 135fce7](https://github.com/primefaces/primefaces/commit/135fce7d3c4b505702baf40e6848c455a0b66645#diff-646c47fad60da19b6baed1d4b0cc5634) because if I disable that css rule then the circles are back. 

The problem is that I don't know what the .ui-helper-hidden-accessible class means, it looks like a class for hidden fields but that class is always added to SelectOneRadio [since Feb 2012](https://github.com/primefaces/primefaces/commit/0efec742e9954c9a816bac1bf4b76702162a2b9b#diff-1410a5fcb4ee040cc203c21396ca632f).

I can't provide a solution because is not clear for me if the problem is:

1. the class being added always (even if the radio is not hidden)
2. the transform: scale(0) with the wrong selector.

I think that the SelectOneRadioRenderer should add the class if the radio is hidden or that css' class-name should be changed. 

## 2) Environment
- PrimeFaces version: 6.2.25
- Application server + version: Webjetty 9.4.14 (maven plugin)
- Affected browsers: all

## 2) Expected behavior
Non hidden radio button circles are displayed next to each label

## 3) Actual behavior
Non hidden radio button circles are not displayed at all

**Comment by melloware** [comment] 2019-10-03 20:08
@mertsincan can you investigate?

**Comment by melloware** [comment] 2019-10-03 20:10
@lelduayen I wonder if it is confined to the Elite releases as the Showcase appears OK?  https://www.primefaces.org/showcase/ui/input/oneRadio.xhtml

**Comment by lelduayen** [comment] 2019-10-03 20:42
Hi there, I downloaded it from the PrimeStore / Elite. 
Also I've just checked the css on the Showcase and it doesn't have the css rule I've mentioned.

**Comment by melloware** [comment] 2019-10-03 20:59
I see it is in master so the showcase should have that CSS.  Strange..
https://github.com/primefaces/primefaces/blob/bced07846e6715036c574c35ae87250a561982a7/src/main/resources/META-INF/resources/primefaces/core/core.css#L1-L7

**Comment by melloware** [comment] 2019-10-03 23:20
Can you make a small reproducer using the PrimeFaces Test project please? https://github.com/primefaces/primefaces-test

**Comment by melloware** [comment] 2019-10-04 15:30
@lelduayen I can't reproduce this so unless you can provide a small reproducible sample I am inclined to close it.

**Comment by lelduayen** [comment] 2019-10-04 18:10
Hi there, sorry about the late response. I'm going to provide you with an example, give me until tomorrow please.

**Comment by melloware** [comment] 2019-10-04 18:10
Not a problem!  I will investigate once you do.

**Comment by lelduayen** [comment] 2019-10-07 14:32
@melloware I've downloaded the primefaces test project, changed the dependency to prime 6.2.25 and added a simple SelectOneRadio to the test page. This way I reproduced the error. 
Here are some images of the issue:

### Select one radio issue
![select-one-radio issue](https://user-images.githubusercontent.com/11880357/66320408-282a4080-e8f5-11e9-83a4-f1fe2d2264c6.PNG)


### Select one radio issue css fix
![select-one-radio issue css fix](https://user-images.githubusercontent.com/11880357/66320442-3710f300-e8f5-11e9-9613-6d5468c57a68.PNG)


### Select one radio issue css file location
![select-one-radio css library location](https://user-images.githubusercontent.com/11880357/66320475-4728d280-e8f5-11e9-8606-a334e210b481.png)


Two things to add:

1. I have the 6.2.25 jar downloaded from Primefaces is store, I'm assuming you have access to that version
2. I have the project to share with you, can be a drive link? I don't know how do you normally share it (github link, mail, etc.)

**Comment by melloware** [comment] 2019-10-07 14:53
OK just attach here the zip file of your Test project.  Must zip it up and DO NOT INCLUDE the /target folder.

**Comment by lelduayen** [comment] 2019-10-07 15:13
Sorry, I tried with rar and just saw image extensions allowed 😄, my bad!

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/3698090/primefaces-test.zip)

**Comment by melloware** [comment] 2019-10-07 15:26
OK thanks for the sample.  I can confirm this is broken on 6.2.25 and 7.1-SNAPSHOT. It works on 7.0 which does not have this fix.  Assigning to @mertsincan

**Closed as completed** 2019-10-18 10:42 UTC
Labels: :lady_beetle: defect, 6.2.26, 7.0.9
