### ISSUE TITLE
dataTable within fragment not rendered correctly after paging

### ISSUE THREAD

**Issue by dkreye** [primefaces/primefaces#1730] opened 2016-08-29 15:13 UTC
If a p:dataTable (with paginator and AJAX page listener) is placed within a p:fragment (with autoUpdate), the dataTable is not rendered correctly after paging.

The initial rendering of the table is correct. But after switching to a different table page, the table is rendered wrong (all TABLE, THEAD, TR, TD, ... tags are missing, only the unformatted content of the table cells is visible).

Preconditions to reproduce this issue:
- p:fragment autoUpdate="true"
- p:dataTable paginator="true"
- p:ajax event="page"

See the attached XHTML snippet for an example.
[dataTableWithFragmentIssue.txt](https://github.com/primefaces/primefaces/files/442631/dataTableWithFragmentIssue.txt)

**Comment by melloware** [comment] 2020-03-31 18:36
Can't reproduce with 8.0.  Closing ticket.

**Closed as completed by melloware** 2020-03-31 18:36 UTC
Labels: Resolution: Invalid
