### ISSUE TITLE
Dialog locked to the top when minimize screen.

### ISSUE THREAD

**Issue by ChanaShuver** [primefaces/primefaces#2130] opened 2017-03-02 07:57 UTC
## 1) Environment
- PrimeFaces version:5.3
Its reproduce on the showcase (The latest version).
- Affected browsers:  Chrome 

## 2) Expected behavior
When open Dialog and minimize the screen and drag the Dialog to top of the Screen, The Dialog is not locked to the top and it is possible to close the Dialog.

## 3) Actual behavior
When open Dialog and minimize the screen and drag the Dialog to top of the Screen The Dialog is locked to the top and it is not possible to close the Dialog.

## 4) Steps to reproduce
![dialog1](https://cloud.githubusercontent.com/assets/26132981/23497072/281cae32-ff2a-11e6-91ab-b2bbde28bb9a.PNG)
![dialog2](https://cloud.githubusercontent.com/assets/26132981/23497074/281e23c0-ff2a-11e6-9052-ec9a8472b62c.PNG)
![dialog3](https://cloud.githubusercontent.com/assets/26132981/23497073/281cd1aa-ff2a-11e6-9e6e-b27051301394.png)

Open Dialog , minimize the screen ,Drag the Dialog to the Top try To close the Dialog or Drag it again.

**Comment by mertsincan** [comment] 2017-03-17 08:48
Please try with 6.1.RC1.

**Comment by tandraschko** [comment] 2017-07-10 16:35
Can't replicate it, no idea how you did this. Will close it for now.

**Comment by jxmai** [comment] 2017-07-10 18:55
@tandraschko  I can replicate this bug following the steps mentioned in the description using the latest snapshot (up to f7ca62af251b8d18a6ab6ed2fa94022b3b5f1d72) and showcase, so I suggest to **reopen** this ticket.

![image](https://user-images.githubusercontent.com/10467831/28034392-a2b09dae-6576-11e7-8f8d-6202ccce4ba7.png)


In order to guarantee 100% reproducible, here are the steps (Assuming you are running the showcase locally on jetty server).

1.  go to http://0.0.0.0:8080/showcase/ui/overlay/dialog/basic.xhtml

2. click `modal dialog` button.

![image](https://user-images.githubusercontent.com/10467831/28034468-e0266fc4-6576-11e7-9740-48f8cfaba4f9.png)

3. resize the dialog as large as possible.

![image](https://user-images.githubusercontent.com/10467831/28034524-0ad11724-6577-11e7-8028-6167dc2340d4.png)

4. Resize the browser to make the browser space smaller

![image](https://user-images.githubusercontent.com/10467831/28034572-314f8c64-6577-11e7-9d8c-82d14a20a9e5.png)


5. drag the modal dialog, and **the bug shows up**.

![image](https://user-images.githubusercontent.com/10467831/28034592-4011f46c-6577-11e7-95d4-8991ae0ab5b6.png)

6. resize the browser space back to normal.

![image](https://user-images.githubusercontent.com/10467831/28034645-6021d38a-6577-11e7-8086-3ac5d40961df.png)

**Comment by tandraschko** [comment] 2017-07-11 08:17
Yep, you are right. A PR to fix this would be great!

**Comment by jxmai** [comment] 2017-11-03 16:46
@tandraschko I don't think there is anything to fix on PF side. After https://github.com/primefaces/primefaces/commit/7c25c7bb1b730f8f15d31073c987aefc46f958ed, the go out of bound issue can be prevented if we only drag the dialog.

When we resize the browser instead of resize the dialog, and we should probably make the dialog `width` and `height` responsive. Let's say setting height and width using `%` or `vh` or `vw` since the default one is using `px` and I can confirm this problem won't occur.

**Comment by melloware** [comment] 2019-09-11 15:17
@tandraschko @jxmai I just tried this in the showcase and I can't reproduce it.  I think it was fixed somewhere along the way.

**Comment by melloware** [comment] 2023-05-28 17:00
I can no longer reproduce this with 13.0.0-RC1

**Closed as completed by melloware** 2023-05-28 17:00 UTC
Labels: :lady_beetle: defect
