### ISSUE TITLE
FileUpload: Spring Framework issue with commons-fileupload

### ISSUE THREAD

**Issue by clockwiser** [primefaces/primefaces#6611] opened 2020-12-07 11:01 UTC
**Describe the defect**
Listener of fileUpload is not invoked in advanced mode with common mode uploader. 

**Reproducer**
In the source of CommonsFileUploadDecoder, it looks like be possible to handle advanced mode, but simply not working.
With native uploader, same code runs without any problem. 
**Environment:**
 - PF Version: _8.0_
 - JSF + version: _e.g. Mojarra 2.2.20
-  Tomcat 8.5
 - Affected browsers: _e.g. Chrome, IE, Edge ALL_

**To Reproduce**
1. 
```xml
<h:form>  
   <p:fileUpload listener="#{fileUploadView.handleFileUpload}" mode="advanced" dragDropSupport="false"
                  update="messages" sizeLimit="100000" fileLimit="3" allowTypes="/(\.|\/)(gif|jpe?g|png)$/" />
 
    <p:growl id="messages" showDetail="true" />     
</h:form>
```

Based on the source from the following link.
https://www.primefaces.org/showcase/ui/file/upload/single.xhtml

2. Set upload mode to common.
```xml
<context-param>
    <param-name>primefaces.UPLOADER</param-name>
    <param-value>commons</param-value><!-- Allowed values: auto, native and commons. -->
</context-param>
<filter>
    <filter-name>primeFacesFileUploadFilter</filter-name>
    <filter-class>org.primefaces.webapp.filter.FileUploadFilter</filter-class>
        <init-param>
	       <param-name>thresholdSize</param-name>
	       <param-value>10000000000</param-value>
	</init-param>
	<init-param>
	        <param-name>uploadDirectory</param-name>
	        <param-value>/tmp/upload/</param-value>
	</init-param>
</filter>
<filter-mapping>
    <filter-name>primeFacesFileUploadFilter</filter-name>
    <servlet-name>facesServlet</servlet-name>
</filter-mapping>
```

3. Listener not invoked.

**Expected behavior**
It should work in common file upload mode as same as in native file upload mode.

**Comment by Rapster** [comment] 2020-12-07 12:39
Next time please, format your code: https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by melloware** [comment] 2020-12-07 13:01
When I try this I am getting a stack trace:
```
Dec 07, 2020 8:00:54 AM com.sun.faces.context.PartialViewContextImpl processPartial
INFO: java.lang.NullPointerException
java.lang.NullPointerException
        at org.primefaces.component.fileupload.CommonsFileUploadDecoder.createUploadedFile(CommonsFileUploadDecoder.java:53)
        at org.primefaces.component.fileupload.CommonsFileUploadDecoder.createUploadedFile(CommonsFileUploadDecoder.java:36)
        at org.primefaces.component.fileupload.AbstractFileUploadDecoder.decodeAdvanced(AbstractFileUploadDecoder.java:86)
        at org.primefaces.component.fileupload.AbstractFileUploadDecoder.decode(AbstractFileUploadDecoder.java:54)
        at org.primefaces.component.fileupload.FileUploadRenderer.decode(FileUploadRenderer.java:53)
        at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:509)
        at javax.faces.component.UIInput.decode(UIInput.java:798)
        at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:886)
        at javax.faces.component.UIInput.processDecodes(UIInput.java:692)
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:606)
        at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:159)
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1456)

```

Which explains why the Listener is not called.

**Comment by melloware** [comment] 2020-12-07 13:13
It looks like `MultiPartRequest` is NULL here:
```java
@Override
    protected UploadedFile createUploadedFile(MultipartRequest request, FileUpload fileUpload, String inputToDecodeId) {
        FileItem file = request.getFileItem(inputToDecodeId);
        if (file != null && !file.getName().isEmpty()) {
            return new CommonsUploadedFile(file, fileUpload.getSizeLimit());
        }

        return null;
    }
```

**Comment by Rapster** [comment] 2020-12-07 13:17
Yeah i'm having a closer look... Seems like the original request is no `ServletRequestWrapper`

**Comment by Rapster** [comment] 2020-12-07 13:24
Ok, make sure to enable multi part by setting enctype to your form (e.g `<h:form enctype="multipart/form-data">... </h:form>`)

**Comment by tandraschko** [comment] 2020-12-07 13:28
Should we add a warning log?

**Comment by Rapster** [comment] 2020-12-07 13:29
Good point

**Comment by melloware** [comment] 2020-12-07 13:29
Yes we should and we should fix the showcase form because that is what I am testing with.  I am fixing the showcase example now.

**Comment by Rapster** [comment] 2020-12-07 13:30
@melloware do you think you can also add the log?

**Comment by tandraschko** [comment] 2020-12-07 13:30
i will add the log, NP

**Comment by clockwiser** [comment] 2020-12-07 13:31
I have tried that <h:form enctype="multipart/form-data">, but didn't work.

By debugging, found the "FileItem file" becomes null in the following part.

source file: CommonsFileUploadDecoder
method: decodeAdvanced()
FileItem file = request.getFileItem(clientId);

Don't know why.

**Comment by Rapster** [comment] 2020-12-07 13:32
Make sure your filter-mapping is configured with the right servlet-name. Usually it's "Faces Servlet" you might have changed that name?

**Comment by melloware** [comment] 2020-12-07 13:34
@tandraschko I am wondering if we should throw a FacesException instead of log a warning?  "Your form is not a multipart form. Please use enctype="multipart/form-data"." Or something like that.

**Comment by clockwiser** [comment] 2020-12-07 13:35
> Make sure your filter-mapping is configured with the right servlet-name. Usually it's "Faces Servlet" you might have changed that name?

No. I have checked that matches. Also I tried allowCasualMultipartParsing="true", which is a context setting of tomcat 8.5.

**Comment by tandraschko** [comment] 2020-12-07 13:37
@melloware better we avoid that. There can be a different form on the client or even no parent form on the server side. (because appendTo e.g.)

**Comment by melloware** [comment] 2020-12-07 13:41
@clockwiser OK so this is specific to Tomcat. And just making sure you are using Commons FileUpload 1.4 the latest version correct?

**Comment by Rapster** [comment] 2020-12-07 13:42
@melloware +1 to throw exception in `CommonsFileUploadDecoder#getRequest`, if it returns null it will crash later so better to inform what's wrong asap

@clockwiser start debugging `FileUploadFilter`, you should be able to understand why your request is not wrapped into a `MultipartRequest`

**Comment by clockwiser** [comment] 2020-12-07 13:43
> @tandraschko I am wondering if we should throw a FacesException instead of log a warning? "Your form is not a multipart form. Please use enctype="multipart/form-data"." Or something like that.

If there is a concrete example of advanced mode with common uploader, it will be greatly appreciated.  Also my case is migration from richfaces to primefaces, and primefaces uploader has no createTempFile option, which is a big headache and the reason of why must use common uploader. In common uploader, thresholdsize can be used like a createTempFile switch.

**Comment by melloware** [comment] 2020-12-07 13:47
@clockwiser let me throw together a quick runnable example for you.

**Comment by clockwiser** [comment] 2020-12-07 13:49
> @clockwiser OK so this is specific to Tomcat. And just making sure you are using Commons FileUpload 1.4 the latest version correct?

No. I used 1.3.3 according the dependency from https://mvnrepository.com/artifact/org.primefaces/primefaces/8.0.

**Comment by tandraschko** [comment] 2020-12-07 13:49
added logging on renderer side
@Rapster please add the exception in the getRequest like you mentioned

**Comment by melloware** [comment] 2020-12-07 13:53
@clockwiser Here is a reproducer:
[pf-6611.zip](https://github.com/primefaces/primefaces/files/5653053/pf-6611.zip)

Unzip and run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml

**Comment by clockwiser** [comment] 2020-12-07 14:36
> @clockwiser Here is a reproducer:
> [pf-6611.zip](https://github.com/primefaces/primefaces/files/5653053/pf-6611.zip)
> 
> Unzip and run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtm

This sample uses glassfish, not tomcat 8.5. Maybe that's the reason of different running results.

**Comment by tandraschko** [comment] 2020-12-07 14:39
it uses jetty, not glassfish
you can normally do a simple "mvn clean package" and deploy it to your tomcat

**Comment by melloware** [comment] 2020-12-07 14:41
@clockwiser yes it uses Jetty but it is to prove the base PF code is working.  Now its time for you to help figure out why it doesn't work in Tomcat.  I use this code in Undertow (WildFly) and it also works fine.

**Comment by clockwiser** [comment] 2020-12-07 23:12
> @clockwiser yes it uses Jetty but it is to prove the base PF code is working. Now its time for you to help figure out why it doesn't work in Tomcat. I use this code in Undertow (WildFly) and it also works fine.

Not solved yet, but found out a similar case.
https://forum.primefaces.org/viewtopic.php?t=57347

**Comment by melloware** [comment] 2020-12-08 00:35
Yep now we just need to know why. I don't really use Tomcat so I never test and debug with it.

**Comment by clockwiser** [comment] 2020-12-08 05:17
> Yep now we just need to know why. I don't really use Tomcat so I never test and debug with it.

Compared required form formats of jetty and tomcat, there are differences.  Tomcat requires input tags for file items, then wrap  them into request. However, the generated html from JSF xhtml only has div tags for file items. Guess Jetty can handle div tags to make a proper uploader request, but tomcat can't.  

Samples of tomcat handling commons uploader.
https://balusc.omnifaces.org/2007/11/multipartfilter.html
http://www.avajava.com/tutorials/lessons/how-do-i-upload-a-file-to-a-servlet.html

**Comment by clockwiser** [comment] 2020-12-08 07:50
> Yep now we just need to know why. I don't really use Tomcat so I never test and debug with it.

Now I am going to take native upload method. But found another problem, the uploaded file handler disappears after finishing listener action. If pass the file handler to next process, and try to call getInputStream(), it shows file not found error. Is it possible to control when to delete the uploaded file with native uploader? Common uploader seems to have a cleantracker setting, but currently can't use common uploader.

**Comment by tandraschko** [comment] 2020-12-08 08:20
> Compared required form formats of jetty and tomcat, there are differences. Tomcat requires input tags for file items, then wrap
> them into request. However, the generated html from JSF xhtml only has div tags for file items. Guess Jetty can handle div tags to
> make a proper uploader request, but tomcat can't.

that isnt true. Even Jetty cant do that. Advanced FileUpload creates a temp form in a iframe to upload, so it never just submits the normal view. Check your network monitor.

**Comment by Rapster** [comment] 2020-12-08 11:47
> @clockwiser start debugging FileUploadFilter, you should be able to understand why your request is not wrapped into a MultipartRequest

@clockwiser did you do that at least?

**Comment by clockwiser** [comment] 2020-12-08 14:20
> > @clockwiser start debugging FileUploadFilter, you should be able to understand why your request is not wrapped into a MultipartRequest
> 
> @clockwiser did you do that at least?

I had tried to debug the filter but didn't figure out much. So I came here. :-)

**Comment by clockwiser** [comment] 2020-12-08 23:49
> it uses jetty, not glassfish
> you can normally do a simple "mvn clean package" and deploy it to your tomcat

There was no problem when ran your example on tomcat 8.5. Created maven snapshot and deployed the snapshot to tomcat wtp server, and ran from inside eclipse.

**Comment by melloware** [comment] 2020-12-09 00:02
So our sample works on Tomcat?  Does that mean you need to figure out what is different between your app and ours?

**Comment by clockwiser** [comment] 2020-12-09 00:11
> So our sample works on Tomcat? Does that mean you need to figure out what is different between your app and ours?

The biggest difference is that my project is still using good old spring framework+mybatis. But hardly it is the cause of the issue, I think.

**Comment by melloware** [comment] 2020-12-09 00:17
Ahh ok could it be some Spring filter or listener that is in between and somehow causing the issue. That would be my theory.

**Comment by Rapster** [comment] 2020-12-09 10:06
Would that help you https://forum.primefaces.org/viewtopic.php?t=24077 ?

**Comment by melloware** [comment] 2020-12-09 12:36
@clockwiser If you can confirm that the forum post @Rapster posted does fix your issue I will update the FileUpload docs so we don't run into this again.

**Comment by clockwiser** [comment] 2020-12-09 23:27
> @clockwiser If you can confirm that the forum post @Rapster posted does fix your issue I will update the FileUpload docs so we don't run into this again.

My project is based on spring mvc, not spring webflow. @Rapster's post doesn't fix the issue.

**Comment by Rapster** [comment] 2020-12-09 23:35
If it works with native but not with apache, then something's wrong with your FileUploadFilter (mapping) configuration, does it get called at least?

**Comment by melloware** [comment] 2020-12-09 23:46
@clockwiser can you post your full web.xml for us to see?

**Comment by clockwiser** [comment] 2020-12-10 00:42
> If it works with native but not with apache, then something's wrong with your FileUploadFilter (mapping) configuration, does it get called at least?

It is called, I even debug into it. 
By debugging, found the "FileItem file" becomes null in the following part, failing to get FileItem and action is not called.

source file: CommonsFileUploadDecoder
method: decodeAdvanced()
FileItem file = request.getFileItem(clientId);

**Comment by clockwiser** [comment] 2020-12-10 00:49
> @clockwiser can you post your full web.xml for us to see?

There are several customized filters involved in the web.xml. Now I'm checking into these filters. As for web.xml file, sorry I need to consult project manager if it is allowed to publish

**Comment by tandraschko** [comment] 2020-12-10 08:35
It seems that also basic && auto=true needs no enctype anymore, i will change the logging a bit.

**Comment by melloware** [comment] 2020-12-10 18:03
OK so we have ruled out its a Tomcat issue because our sample WAR works fine in Tomcat.

So that leaves us with its some Filter or Servlet in Spring Framework that must be causing the issue.  I will close this ticket for now and will re-open if we are provided a Test case we can debug and see the problem.

**Closed as completed by melloware** 2020-12-10 18:03 UTC
Labels: :lady_beetle: defect, needs investigation

**Comment by Rapster** [comment] 2020-12-10 19:30
Can you debug `CommonsFileUploadDecoder#createUploadedFile` and check/debug from there, anything suspecious like name being null or `FileItem#fileParams` being empty, does it actually contain anything etc. Basically, do you see a reason why file being null?

**Comment by clockwiser** [comment] 2020-12-11 00:14
> Can you debug `CommonsFileUploadDecoder#createUploadedFile` and check/debug from there, anything suspecious like name being null or `FileItem#fileParams` being empty, does it actually contain anything etc. Basically, do you see a reason why file being null?

From here fileItems become null.

class:MultipartRequest
method:parseRequest

private void parseRequest(HttpServletRequest request, ServletFileUpload servletFileUpload) throws IOException {
        try {
            List<FileItem> fileItems = servletFileUpload.parseRequest(request);

*******************************************************************************************
Behind servletFileUpload.parseRequest is apache commons module, the iter becomes null. Maybe ctx has some problem.

class name: FileUploadBase
method:parseRequest
public List<FileItem> parseRequest(RequestContext ctx)
            throws FileUploadException {
        List<FileItem> items = new ArrayList<FileItem>();
        boolean successful = false;
        try {
            FileItemIterator iter = getItemIterator(ctx);

**Comment by clockwiser** [comment] 2020-12-11 00:54
Exactly fails here. 
class:org.apache.commons.fileupload.MultipartStream
method:readBodyData

public int readBodyData(OutputStream output)
            throws MalformedStreamException, IOException {
        final InputStream istream = newInputStream();
        return (int) Streams.copy(istream, output, false);

Streams.copy throws exception: org.apache.commons.fileupload.MultipartStream$MalformedStreamException:Stream ended unexpectedy.

**Comment by Rapster** [comment] 2020-12-11 09:29
There you go, you know exactly where to look now :wink:

**Comment by melloware** [comment] 2020-12-11 12:13
@clockwiser I know this is for Spring Boot but this sounds an awful lot like your issue: https://stackoverflow.com/questions/51149162/spring-boot-streaming-apache-fileupload-stream-ended-unexpectedly

As I said some other Filter in your chain is somehow disturbing this process and corrupting or closing the stream.

**Comment by clockwiser** [comment] 2020-12-11 22:55
> @clockwiser I know this is for Spring Boot but this sounds an awful lot like your issue: https://stackoverflow.com/questions/51149162/spring-boot-streaming-apache-fileupload-stream-ended-unexpectedly
> 
> As I said some other Filter in your chain is somehow disturbing this process and corrupting or closing the stream.

If so, native uploader should not work as the input stream is corrupted by the same filters which cause problem to common uploader.  Only if native uploader not use input stream, your theory is possible.

**Comment by melloware** [comment] 2020-12-12 15:07
I may be mistaken but I believe COmmons FileUpload uses Servlet Filters so its in a chain with other Spring Filters.  Native uses `javax.servlet.http.Part` in the Servlet 3.0 spec to handle the MultiPart upload so I have a feeling they are two completely different things and handled by your container `Tomcat` or `Jetty` or whatever is implementing the Servlet 3.0 spec.
