### ISSUE TITLE
DatePicker: mask not working properly on Firefox

### ISSUE THREAD

**Issue by pm2013** [primefaces/primefaces#10024] opened 2023-04-14 11:34 UTC
### Describe the bug

 <p:datePicker  pattern="dd.MM.yyyy"  mask="true"/>

Mask is not working, I can put for example:

<img width="256" alt="mask" src="https://user-images.githubusercontent.com/13569972/232032227-580ecc70-e4a2-42be-97a4-c7f9bac589f9.png">

This occurs on Windows, Firefox 112
Firefox Mac & Chrome Windows works properly.

### PrimeFaces edition

Elite

### PrimeFaces version

12.03

### Theme

Serenity

### JSF implementation

MyFaces

### JSF version

2.2

### Java version

1.8.0_321-b07

### Browser(s)

Firefox 112

**Comment by melloware** [comment] 2023-04-14 11:39
Probably similar to: https://github.com/RobinHerbots/Inputmask/issues/2578

**Comment by jepsar** [comment] 2023-04-14 11:54
Showcase is working for me using FF 112 on Windows.

**Comment by melloware** [comment] 2023-04-14 11:54
@pm2013 I can't reproduce: 
[pf-10024.zip](https://github.com/primefaces/primefaces/files/11232436/pf-10024.zip)

I am running Firefox 112 on Windows and tested with PF 12.0 and 13.0-SNAPSHOT.

**Comment by melloware** [comment] 2023-04-18 01:20
Closing. Will reopen if more information is provided

**Closed as not planned** 2023-04-18 01:20 UTC
Labels: Resolution: Cannot Replicate
