### ISSUE TITLE
Menu: Provide screen reader compliant navigation for accessibility.

### ISSUE THREAD

**Issue by Rene-Stoeckel** [primefaces/primefaces#11849] opened 2024-05-02 11:01 UTC
### Description

The menues create with p:menu and p:menuitem are inaccesible/unusable with screenreaders like JAWS.
 Primefaces 13.0.1 - 13.0.8.

The reason is, because the menuitems do not get the fokus,
but the DIV with the class="ui-helper-hidden-accessible"
(see below). As a consequence the screenreader is not changing to 
navigation mode and thus does neither read the role of 
the menu/menuitem nor the label of the menuitem.

For reference: The Primefaces menu is rendered into the following structure:
```
<div id="main:j_id_f" class="ui-menu ui-widget ui-widget-content ui-corner-all ui-helper-clearfix ui-menu-toggleable" style="width: fit-content" role="menu">
	<div tabindex="0" class="ui-helper-hidden-accessible"></div>
	<ul class="ui-menu-list ui-helper-reset">
		<li class="ui-menuitem ui-widget ui-corner-all" role="menuitem">
```

### Describe the solution you would like

To solve the issue the following steps are required:

1. The LI with role="menuitem" must get the focus instead the DIV with class="ui-helper-hidden-accessible" 
2. The UL between the DIV with role="menu" and the LI with role="menuitem" must be attributed with role="none" 
3. The menu must be implemented according to "Menu and Menubar Pattern | APG | WAI | W3C", see https://www.w3.org/WAI/ARIA/apg/patterns/menubar/
4. The menu items must be implemented via the "Menu Button Pattern | APG | WAI | W3C", see https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/

### Additional context

 Primefaces 13.0.1 - 13.0.8.

**Comment by melloware** [comment] 2024-05-02 11:19
@Rene-Stoeckel this is a duplicate of this ticket: https://github.com/primefaces/primefaces/issues/6561  I am closing in favor of that ticket feel free to subscribe and add your additional observations to that ticket.

**Closed as not planned by melloware** 2024-05-02 11:19 UTC
Labels: Resolution: Duplicate

**Comment by melloware** [comment] 2024-05-02 11:23
Also a PR would be great!
