### ISSUE TITLE
SelectOneMenu: Improve filter performance

### ISSUE THREAD

**Issue by Rawi01** [primefaces/primefaces#4868] opened 2019-06-07 15:16 UTC
## 1) Environment
- PrimeFaces version: **latest**
- Does it work on the newest released PrimeFaces version? Version? **No**
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) **No**
- Application server + version: **all**
- Affected browsers: **Internet Explorer, Firefox**

## 2) Expected behavior
Using the filter in a SelectOneMenu with many entrys should be fast and without noticable lag.

## 3) Actual behavior
It lags...

## 4) Steps to reproduce
- Create a SelectOneMenu with 2000 items and filtering enabled
- Start typing
***
PR will be added soon

**Comment by Rapster** [comment] 2019-06-09 18:43
First, it's a duplicate of #4588 and second, displaying 2000 items in a SelectOneMenu is not the best idea. You better use another component... 

Though, I like your fix, maybe @mertsincan could share his wisdom

**Comment by Rawi01** [comment] 2019-06-11 14:02
Oh, I missed that old one, sorry about that.

If you always have that many items you should use a different component but in my case there are mostly small menus. In some specially cases it is possible that there are more but the UI should stay the same. It never reaches 2000, I only used that number because it gets quite obvious with such a high number.

**Comment by melloware** [comment] 2019-06-11 14:06
I fully support this fix.

**Closed as completed** 2019-06-25 14:15 UTC
Labels: :zap: performance
