### ISSUE TITLE
Tree: Drag&Drop buggy

### ISSUE THREAD

**Issue by AbaKai** [primefaces/primefaces#8447] opened 2022-02-16 12:33 UTC
**Describe the defect**
There seems to be a bug within the drag&drop functionality between two Tree controls. Dropping a node onto another node is not possible by default after loading the page - only dropping in between nodes is possible. In case a node is dragged and dropped into another Tree control (in between two nodes) this functionality is activated for only that node so then any other node can be dropped onto that specific node.

**Reproducer**
This bug can be reproduced within the showcase.

**Environment:**
 - PF Version: 11.0.0
 - PF Theme: default
 - Affected browsers: tested on Chrome and Firefox (latest)

**To Reproduce**
1. Go to the showcase - Tree - DragDrop.
2. Drag any node (eg.'Node 2') from the left Tree control to the right Tree control.
3. Now you can drag any other node (eg. 'Node 1' or 'item 0') onto 'Node 2' but not onto any other node.

**Expected behavior**
I expect the functionality of dragging a node onto another node either to be enabled or disabled permanently and not to change after a drop. In my specific case I want to use the functionality of dropping onto another node so I can use the showcase example to build a tree(left) with 'unused tree nodes'(right) by using drag&drop.

This is my first bug report ever so please don't be too hard on me in case I may have made some mistakes doing this properly.

**Comment by tandraschko** [comment] 2022-02-16 12:35
Should be a duplicate of #8223 ?

**Comment by melloware** [comment] 2022-02-16 12:45
Yep definitely a duplicate and already fixed

**Comment by AbaKai** [comment] 2022-02-16 12:46
Yes seems to be the same problem! Thanks =)

**Closed as completed by melloware** 2022-02-16 12:45 UTC
Labels: Resolution: Duplicate
