### ISSUE TITLE
DataTable: Reflow should use styled selectOneMenu, not native one

### ISSUE THREAD

**Issue by githubuser100007** [primefaces/primefaces#8173] opened 2021-12-16 03:55 UTC
Reflow on p:dataTable causes sort button with no styling. It looks like a normal html sort dropdown with no styling.

Primefaces 11, Rain Layout

**Comment by tandraschko** [comment] 2021-12-16 12:38
please provide a reproducer - at best a forked primefaces-test project
so we can see if related to rain or not

**Comment by githubuser100007** [comment] 2021-12-16 15:07
Any p:dataTable with reflow="true":

```
<p:dataTable id="items" reflow="true"
	value="#{view.items}" var="item" >

     <p:column field="value" />

</p:dataTable>
```

**Comment by tandraschko** [comment] 2021-12-16 15:17
i still dont know what you mean
what is the sort button? whats a sort dropdown?

**Comment by melloware** [comment] 2021-12-16 15:32
screenshots please.  reproducer please like @tandraschko asked for else we can'treally do anything and you should post on the RAIN forum: https://forum.primefaces.org/viewforum.php?f=138

**Comment by githubuser100007** [comment] 2021-12-16 16:13
Sort looks like this (with no formatting, looks unlike any other menu dropdown in the template)
![image](https://user-images.githubusercontent.com/37383950/146407784-b4272d38-63a0-4454-8f0a-cce8e3e7b8ec.png)

**Comment by githubuser100007** [comment] 2021-12-16 16:14
I did post on the rain forum, they asked me to create an issue here.

**Comment by melloware** [comment] 2021-12-18 18:54
Forum post: https://forum.primefaces.org/viewtopic.php?f=138&t=70034

Mert confirmed to open a ticket here so assigned to him.

**Comment by githubuser100007** [comment] 2022-01-30 14:35
Additional defect found while playing around with this sort dropdown on mobile. It seems to be selecting different dropdown values than the one that is actually selected. For instance, if I click on First Name Descending:

![image](https://user-images.githubusercontent.com/37383950/151704119-2d8e43fd-3e0c-4e68-8025-71bf3a5a2cd8.png)

It ends up closing the dropdown with a different value selected.

**Comment by melloware** [comment] 2022-01-30 15:44
@githubuser100007 this has been reported already here: https://github.com/primefaces/primefaces/issues/7471

**Comment by melloware** [comment] 2022-04-28 22:28
Duplicate of https://github.com/primefaces/primefaces/issues/2270

**Closed as completed by melloware** 2022-04-28 22:28 UTC
Labels: new feature
