### ISSUE TITLE
DataTable: columns order and visibility 

### ISSUE THREAD

**Issue by sergiyuvarov** [primefaces/primefaces#1897] opened 2016-11-14 10:55 UTC
# IMPORTANT 
Please, add such functionality to datatable component: saving and restoring columns order and visibility.

**Comment by kukel** [comment] 2016-11-25 15:22
Go ahead and create a pull request... (and using important in capitals and kind of bold without any real substantiation of your request has most likely the opposite effect, it gets ignored since it feels like shouting/begging)

**Comment by melloware** [comment] 2020-07-16 18:07
Duplicate of https://github.com/primefaces/primefaces/issues/2728

**Closed as completed by melloware** 2020-07-16 18:07 UTC
Labels: Resolution: Duplicate
