### ISSUE TITLE
Datatable: multiviewstate + lazy after sorting crashes

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2631] opened 2017-08-12 10:08 UTC
## 1) Environment
- PrimeFaces version: 6.2-SNAPSHOT
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Jetty
- Affected browsers: Chrome

## 2) Expected behavior

1. Sort any column of the table in lazy.xhtml showcase (using xhtml sample)
2. Go to another page
3. Go back to lazy.xhtml page: it crashes

## 3) Actual behavior

> java.lang.RuntimeException
> at org.primefaces.showcase.view.data.datatable.LazySorter.compare(LazySorter.java:43)
> at org.primefaces.showcase.view.data.datatable.LazySorter.compare(LazySorter.java:1)
> at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
> at java.util.TimSort.sort(TimSort.java:234)
> at java.util.Arrays.sort(Arrays.java:1512)
> at java.util.ArrayList.sort(ArrayList.java:1454)
> at java.util.Collections.sort(Collections.java:175)
> at org.primefaces.showcase.view.data.datatable.LazyCarDataModel.load(LazyCarDataModel.java:88)
> at org.primefaces.component.datatable.DataTable.loadLazyData(DataTable.java:1170)
> at org.primefaces.component.datatable.DataTableRenderer.preRender(DataTableRenderer.java:147)
> at org.primefaces.component.datatable.DataTableRenderer.encodeEnd(DataTableRenderer.java:91)
> at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
> at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
> at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
> at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:889)

## 5) Sample XHTML
```xml
<p:dataTable var="car" value="#{dtLazyView.lazyModel}" paginator="true" rows="10"
                         paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                         rowsPerPageTemplate="5,10,15" selectionMode="single" selection="#{dtLazyView.selectedCar}" id="carTable" lazy="true" multiViewState="true">
               <p:ajax event="rowSelect" listener="#{dtLazyView.onRowSelect}" update=":form:carDetail" oncomplete="PF('carDialog').show()" />
               <p:columns value="#{dtColumnsView.columns}" var="column" columnIndexVar="colIndex" sortBy="#{column.property}" filterBy="#{car[column.property]}">
                    <f:facet name="header">
                        <h:outputText value="#{column.header}" />
                    </f:facet>
                    <h:outputText value="#{car[column.property]}" />
                </p:columns>
            </p:dataTable>
```

**Comment by Rapster** [comment] 2017-08-12 10:08
@mertsincan you might have an idea on this

**Comment by sato92** [comment] 2017-11-10 09:33
// package org.primefaces.component.datatable.feature;
// overwrite the encode method from SortFeature class.

```
@Override
public void encode(FacesContext context, DataTableRenderer renderer, DataTable table) throws IOException {
    table.setFirst(0);

    if (table.isLazy()) {
        table.loadLazyData();
    }
    else {
        if (table.isMultiSort()) {
            multiSort(context, table);
        }
        else {
            singleSort(context, table);
        }

        if (table.isPaginator()) {
            RequestContext requestContext = RequestContext.getCurrentInstance();

            if (requestContext != null) {
                requestContext.addCallbackParam("totalRecords", table.getRowCount());
            }
        }

        // save state
        Object filteredValue = table.getFilteredValue();
        if (!table.isLazy() && table.isFilteringEnabled() && filteredValue != null) {
            table.updateFilteredValue(context, (List) filteredValue);
        }
    }

    renderer.encodeTbody(context, table, true);

    if (table.isMultiViewState()) {
        ValueExpression sortVE;
        String sortField = table.getSortField();

        /*
         * ################## IMPORTANT ##################
         * primefaces BUG - lazy datatable with multiViewState true destroys the session after sorting
         * FIX: comment out following lines
         */

        // if (sortField != null) {
        // sortVE = context.getApplication()
        // .getExpressionFactory()
        // .createValueExpression("#{'" + sortField + "'}",
        // String.class);
        // }
        // else {
        sortVE = table.getValueExpression(DataTable.PropertyKeys.sortBy.toString());
        // }
        List<SortMeta> multiSortMeta = table.getMultiSortMeta();
        if (sortVE != null || multiSortMeta != null) {
            TableState ts = table.getTableState(true);
            ts.setSortBy(sortVE);
            ts.setMultiSortMeta(multiSortMeta);
            ts.setSortOrder(table.getSortOrder());
            ts.setSortField(table.getSortField());
            ts.setSortFunction(table.getSortFunction());

            if (table.isPaginator()) {
                ts.setFirst(table.getFirst());
                ts.setRows(table.getRows());
            }
        }
    }
}`

**Comment by Rapster** [comment] 2017-11-10 09:36
Please make a PR instead (so we can see the differences, but... it doesn't look like a fix to me, more like workaround)

**Comment by mertsincan** [comment] 2017-12-19 13:53
Duplicate of #2613.  Good PR!! We need to add isMultiSort() check. Please see;
```
//in DataTableTemplate.java
         if(this.isMultiSort())
                data = lazyModel.load(first, getRows(), getMultiSortMeta(), getFilters());
            else
                data = lazyModel.load(first, getRows(), resolveSortField(), convertSortOrder(), getFilters());
```

**Closed as completed by mertsincan** 2017-12-19 13:53 UTC
Labels: :lady_beetle: defect
