### ISSUE TITLE
DatePicker throws JS error and fails on rerender on invalid input

### ISSUE THREAD

**Issue by havist** [primefaces/primefaces#6620] opened 2020-12-08 08:42 UTC
**Describe the defect**
When invalid input value is typed on the DatePicker the JS error occurs and the component is damaged when rerender during Ajax request because of invalid unparseable value initialization.

**Environment:**
 - PF Version: _8.0_
 - JSF + version: _Mojarra 2.2.20_
 - Affected browsers: _ALL_

**To Reproduce**
1. Go to Showcase at https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml.
2. Type invalid value to any DatePicker (e.g. `20`).
3. Blur the component.
4. See JS error `Uncaught TypeError: this.viewDate.getMonth is not a function`.

From now the internal state of a component is errorneous causing the component cannot be rerendered during Ajax request. It's because of invalid value is held in widget's `options.viewDate` and rerender during `_setInitValues` causes the component is not initialized properly (`parseDate` function fails with another JS error `Unexpected literal at position x` ).

**Expected behavior**
No JS error and valid widget's internal state.

**Comment by melloware** [comment] 2020-12-08 12:42
Fixed already in 9.0.

Duplicate of: https://github.com/primefaces/primefaces/issues/5683

**Closed as completed** 2020-12-08 12:43 UTC
Labels: Resolution: Duplicate
