### ISSUE TITLE
Enter does not submit form if a selectOneMenu is focused

### ISSUE THREAD

**Issue by BrianSiimAndersen** [primefaces/primefaces#1127] opened 2016-02-10 06:04 UTC
When pressing Enter in a form where the focus is in a selectOneMenu nothing happens. The same behavior can be seen in the PrimeFaces ShowCase: http://www.primefaces.org/showcase/ui/ajax/dropdown.xhtml

I would like the Enter to submit the form unless the use has opened the menu. When the menu is open Enter is used to select a value in the list.

**Comment by kukel** [comment] 2016-02-10 09:17
Please post your patch here…  or better yet, make a real pull request

**Comment by BrianSiimAndersen** [comment] 2016-02-10 09:57
I'm not familiar with Git, so I don't know how to make a pull request. But this is what I did to make it work:

```
PrimeFaces.widget.SelectOneMenu.prototype.handleEnterKey = function(event) {
    if (this.panel.is(':visible')) {
        this.selectItem(this.getActiveItem());
        event.preventDefault();
        event.stopPropagation();
    }
}
```

**Comment by cagataycivici** [comment] 2016-02-11 10:29
How does h:selectOneMenu behave?

**Comment by BrianSiimAndersen** [comment] 2016-02-11 12:55
Apparently it depends on the browser when using h:selectOneMenu. In Safari the form gets submitted, in Firefox it doesn't.

**Comment by cagataycivici** [comment] 2016-02-11 21:54
So what should we do at p:selectOneMenu side, normalize it or delegate to browser?

**Comment by kukel** [comment] 2016-02-15 17:20
Normalize... See also http://stackoverflow.com/questions/2968693/why-doesnt-hitting-enter-when-a-select-is-focused-submit-the-form (so as expected it is plain html related). Behaviour like FF is has my preference.

**Comment by melloware** [comment] 2019-09-10 17:14
@kukel this sounds like its expected behavior is it safe to close this ticket?

**Comment by melloware** [comment] 2019-09-11 15:02
I am going to close as WontFix since this is the default HTML5 behavior for this component.

**Closed as completed by melloware** 2019-09-11 15:02 UTC
Labels: Resolution:  Wontfix, needs further work
