### ISSUE TITLE
Evaluate JQuery 3 upgrade

### ISSUE THREAD

**Issue by amarendrar** [primefaces/primefaces#2989] opened 2017-11-23 05:15 UTC
We analysing the primefaces to use in our project(richfaces migration) and found that primefaces is using the older jquery and jquery UI versions

As per this site, "http://research.insecurelabs.org/jquery/test/" there are some issues with Jquery. Is there any plan in Primefaces to upgrade to latest Jquery version.  In Prime faces 6.1, jquery version is 1.11 and planned primefaces version 6.2 is upgraded to 2.x and not sure the minor version. Please comment.

**Comment by tandraschko** [comment] 2017-11-23 11:57
I think we will try to upgrade to 3.x after the 6.2 release next month.

**Comment by melloware** [comment] 2017-11-23 12:00
PF 6.1 = Jquery 1.12.4
PF 6.2 = Jquery 2.2.4

**Comment by amarendrar** [comment] 2017-11-24 06:32
Thanks for reply.

Please suggest the documentation/guide to use the  jquery/jqueryUI packaged by application instead of primefaces jquery.

Is it recommended to use the application jquery instead of primefaces jquery?

**Comment by melloware** [comment] 2017-11-24 13:20
I don't think that is possible because PF components rely on the Jquery version. So if you try and include 3.1.1 and remove PF's version many of the components in PF will not work.

**Comment by jxmai** [comment] 2017-11-24 15:14
> Is it recommended to use the application jquery instead of primefaces jquery?

You can't. It is really non-trivial. What you need to end up doing is making a customized primefaces and upgrading jquery to 3.x yourself if you choose this route.

---

Just wait for the next Primefaces iteration. Since Jquery 1.x and 2.x are no longer under maintenance, I don't think we should stay at 2.x  for long :smile:

**Comment by amarendrar** [comment] 2017-11-26 06:30
We planned to use the primefaces in our application, but our application is using jquery 3,2.1.  We faced some issues with 2.x and 3.1 jquery versions (EX: IE11 compatibility issues)

Please mention the timeline and planned primefaces version for jquery upgrade in primefaces.

**Comment by melloware** [comment] 2017-11-26 16:05
I don't speak for PF but if you look back in history they do a release about every 6 months.  So for..
PF 6.2 = Jquery 2.2.4 = December 2017
PF 6.3 = Jquery 3.3.1 = May 2018 (estimate)

**Comment by tandraschko** [comment] 2017-12-11 10:58
I tried to upgrade it this year, already fixed some stuff and it worked fine when adding the migration plugin (https://code.jquery.com/jquery-migrate-3.0.1.js), which just logs some warnings that methods were removed.
In core.js there is also something we can remove (see: // TODO remove when updating to jQuery 3)

**Comment by tandraschko** [comment] 2017-12-11 10:58
we can easily try to remove the warnings in the future and hopefully remove the migration plugin some day.

**Comment by mertsincan** [comment] 2017-12-11 11:55
Thanks Thomas ;) I created a new Github issue. I tested Jquery 3.2.1 on showcase. it works fine for me.

**Comment by mertsincan** [comment] 2017-12-11 11:55
Duplicate of #3062

**Closed as completed by mertsincan** 2017-12-11 11:55 UTC
Labels: new feature

**Comment by jxmai** [comment] 2017-12-11 20:21
The milestone of this closed ticket has been outdated. (6.3 -> 6.2)

![image](https://user-images.githubusercontent.com/10467831/33852031-8a621238-de7e-11e7-8aa9-9fe5e6094e65.png)
