### ISSUE TITLE
p:confirm and p:confirmDialog doen't work with p:commandButton with attribute  ajax="false"

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#750] opened 2015-10-04 20:10 UTC
I used following libraries:
primefaces-5.2.jar
jsf-api-2.2.10.jar
jsf-impl-2.2.10.jar
JDK 1.8

p:confirm and p:confirmDialog doen't work with p:commandButton with attribute ajax="false"
<code><pre>
<p:commandButton immediate="true" ajax="false" update="growl" action="#{bean.delete}" value="Delete" icon="ui-icon-delete">
    <p:confirm message="Are you sure?" icon="ui-icon-alert" />
</p:commandButton>
<p:confirmDialog global="true" >
    <p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
    <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close"/>
</p:confirmDialog>
</pre></code>

the action delete in ManageBean doesn't call

**Comment by kukel** [comment] 2016-01-13 00:54
remove global="true"... or use it differently. See the PF docs...

**Comment by Rapster** [comment] 2018-01-22 22:48
Duplicate of #99?

**Comment by tandraschko** [comment] 2018-01-23 08:25
Yep probably.

**Closed as completed by tandraschko** 2018-01-23 08:25 UTC
Labels: Resolution: Duplicate, new feature
