### ISSUE TITLE
TextEditor: Wrong placement of resize handle when used with toolbarVisible=true inside a p:resizable

### ISSUE THREAD

**Issue by stolp** [primefaces/primefaces#4942] opened 2019-06-26 14:32 UTC
## 1) Environment
- PrimeFaces version: 7.0.4
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? Not tested yet
- Application server + version: Tomcat 9
- Affected browsers: all

## 2) Expected behavior
The component should behave correct for both settings of the toolbarVisible attribute.

## 3) Actual behavior
The component does not behave correct for toolbarVisible=true.

## 4) Steps to reproduce
First of all: This works perfectly when the toolbarVisible attribute is set to false. But if set to true, the handle is initially placed at the right position, but once LMB is pressed the handle position suddenly jumps up by the amount of pixels corresponding to the height of the toolbar. The handle then stays inside the textEditor area.

## 5) Sample XHTML
```xml
<h:panelGroup layout="block">
  <p:textEditor id="descriptionTextEditor" value="#{jobDetailsBean.description}"
    toolbarVisible="true" />
  <p:resizable for="descriptionTextEditor" minHeight="100" maxHeight="800" handles="s" />
</h:panelGroup>
```

## 6) Sample bean
Not needed here.

**Comment by melloware** [comment] 2019-06-26 14:38
Any analysis or PR would be great here.  Find out of its a QuillJS issue or PF issue.

**Comment by stolp** [comment] 2019-06-27 14:19
I suspect that this is related to the way the QuillJS part renders the toolbar.

When opening a page containing a textEditor, i can see that first the editor area is drawn and then the toolbar is rendered a bit later.

Note that this is from observation only - reality might differ ...

**Comment by melloware** [comment] 2019-11-28 16:32
@stolp I also updated 8.0 to use the latest QuillJS 1.3.7 can you check if it is fixed in 8.0-SNAPSHOT?

**Comment by melloware** [comment] 2019-12-03 17:30
Attached is my runnable test case. Can't reproduce on 8.0.
[pf-4942.zip](https://github.com/primefaces/primefaces/files/3917857/pf-4942.zip)

Closing this ticket. We can re-open if you can reproduce the issue.

**Comment by stolp** [comment] 2019-12-03 22:11
I am sorry, but I can reproduce this issue using the given test case (thanks!) with the current 8.0-SNAPSHOT.

After the first resize the handle is stuck inside the text area. Please reopen this.

**Comment by melloware** [comment] 2019-12-03 22:16
Can you paste an animated Gif or screencast of what you are seeing?  I must be doing something different than you are doing.

**Comment by stolp** [comment] 2019-12-03 22:22
- move mouse to resize handle
- press and hold LMB when on handle
- pull down
- release LMB

After this, the resize hotspot has moved upwards by the vertical size of the toolbar

The video may not be helping much but here it is: https://www.file-upload.net/download-13809119/pf-4942.webm.html

**Comment by melloware** [comment] 2019-12-04 00:38
Ok let me try your steps.

**Comment by melloware** [comment] 2019-12-04 12:38
OK was able to reproduce.  definitely think its related to the QuillJS toolbar somehow messing up the coordinates of the resizable.

**Comment by melloware** [comment] 2020-12-22 19:32
@stolp I am going to close this for now as it looks like Jquery  Resizable has a significant number of bugs open and I am pretty ure we are running into one here with how it calculates the handles.
https://bugs.jqueryui.com/query?status=!closed&component=ui.resizable

**Closed as completed by melloware** 2020-12-22 19:32 UTC
Labels: :lady_beetle: defect, dependencies
