### ISSUE TITLE
Dialog: javascript error on multiple clicks

### ISSUE THREAD

**Issue by cristiandean** [primefaces/primefaces#2039] opened 2017-01-27 11:47 UTC
Hello, I'm with a problem with the modals on primefaces. Sometimes it works, but sometimes apper this error in Javascript Console (when the error appear, the modal don't open). 

```
Code: Select all
components.js?ln=primefaces&v=6.0:1 Uncaught TypeError: Cannot read property 'cfg' of undefined
    at Object.closeDialog (components.js?ln=primefaces&v=6.0:1)
    at Object.closeDialog (core.js?ln=primefaces&v=6.0:1)
    at eval (eval at <anonymous> (jquery.js?ln=primefaces&v=6.0:14), <anonymous>:1:12)
    at eval (<anonymous>)
    at jquery.js?ln=primefaces&v=6.0:14
    at Function.globalEval (jquery.js?ln=primefaces&v=6.0:14)
    at Object.doEval (core.js?ln=primefaces&v=6.0:3)
    at Object.handle (core.js?ln=primefaces&v=6.0:3)
    at Object.success (core.js?ln=primefaces&v=6.0:3)
    at i (jquery.js?ln=primefaces&v=6.0:25)
closeDialog @ components.js?ln=primefaces&v=6.0:1
closeDialog @ core.js?ln=primefaces&v=6.0:1
(anonymous) @ VM9372:1
(anonymous) @ jquery.js?ln=primefaces&v=6.0:14
globalEval @ jquery.js?ln=primefaces&v=6.0:14
doEval @ core.js?ln=primefaces&v=6.0:3
handle @ core.js?ln=primefaces&v=6.0:3
success @ core.js?ln=primefaces&v=6.0:3
i @ jquery.js?ln=primefaces&v=6.0:25
fireWith @ jquery.js?ln=primefaces&v=6.0:25
cf @ jquery.js?ln=primefaces&v=6.0:25
i @ jquery.js?ln=primefaces&v=6.0:25
```

I'm using the 6.0 version.

The bug happens when a dynamic button inside a modal is clicked several times.

I recorded a video using the example of the primefaces website itself.
[Video](https://youtu.be/Xe3FXoxQvic)

I slowed down the internet to make it easier to double click before the modal close.

Thank you

**Comment by Rapster** [comment] 2017-01-28 09:04
1. Follow the issue template
2. Use forum for this first
3. Try with the latest version of PF _(I can't reproduce the problem on showcase, event after several attempts)_

**Comment by cristiandean** [comment] 2017-01-28 09:25
I already did all this. 
http://forum.primefaces.org/viewtopic.php?f=3&t=49100

In my tests the error appears in the Windows and Mac in Chrome, Safari, Firefox and Edge.
I'm using the latest version of primefaces.

**Comment by Rapster** [comment] 2017-01-28 09:31
1. No, you didn't follow the issue template. 
2. Next time, provide the link to the forum. 
3. 6.0 is the last PF community version. Try to build it from source

**Comment by cristiandean** [comment] 2017-01-28 09:37
As you can see in the video, I performed the test on the site of the primefaces showcase itself. At the bottom there is the following text "Running PrimeFaces-6.0.14 on Mojarra-2.2.8.". I believe this is the last stable version not community. Is there any more recent?

Thank you

**Comment by Rapster** [comment] 2017-01-28 09:46
This is why we ask to follow the issue template... So we don't have to guess everything... Anyway, it's the 6.0.14 is the last elite version, and I don't think there anything committed related to this problem since. You have to figure out a way to reproduce it systematically

**Comment by cristiandean** [comment] 2017-01-28 09:51
I understand ... I believe the error happens when two or more requests are made to the server to close the dialog (it can be a quick double click). In my region this is a bit common due to the low speed of the Internet. I guess I just have to wait and see if anyone solves the problem. Thank you anyway

**Comment by Rapster** [comment] 2017-01-28 09:57
It can be the reason, I already tried clicking several times

**Comment by cristiandean** [comment] 2017-01-28 09:59
Did you see the video? Try slowing down your Internet with the Chrome developer tool, I believe you'll be able to simulate

**Comment by Rapster** [comment] 2017-01-28 10:11
Indeed, I reproduced the probem using GPRS. I really thought there was an option for such a case, like this http://ovaraksin.blogspot.fr/2011/05/prevent-multiple-clicks-in-jsf.html

**Comment by cristiandean** [comment] 2017-01-28 10:19
I will try, thank you very much

**Comment by Rapster** [comment] 2017-07-11 09:26
Related to https://github.com/primefaces/primefaces/issues/2521

**Closed as completed** 2020-12-21 17:58 UTC
Labels: :lady_beetle: defect
