### ISSUE TITLE
DataTable: Broken custom draggable helper with MOVE_SCRIPTS_TO_BOTTOM

### ISSUE THREAD

**Issue by fmarangon** [primefaces/primefaces#3494] opened 2018-03-19 11:17 UTC
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: TomCat 8.0.47 (JSF 2.3.3)
- Affected browsers: any

## 2) Expected behavior
Draggable data-table column with custom draggable helper

## 3) Actual behavior
Draggable is broken when **MOVE_SCRIPTS_TO_BOTTOM** is set to **true**.
The error in browser console reads:
_Uncaught TypeError: Cannot read property 'ownerDocument' of undefined_
on line:
_jquery-plugins.js.xhtml?ln=primefaces&v=6.2:88_

## 4) Steps to reproduce
Create a simple project with using the MOVE_SCRIPTS_TO_BOTTOM parameter and the sample XHTML below.

## 5) Sample XHTML
```
<h:form>
	<p:dataTable value="#{bean.list()}" var="l" rowIndexVar="i">
		<p:column>
			<p:outputLabel value="drag me" id="id" />
			<p:draggable for="id" />
			<script type="text/javascript">
				$('[id$="#{i}:id"]').draggable({
					helper: function() {
						return $('<label>#{l}</label>');
					}
				});
			</script>
		</p:column>
	</p:dataTable>
</h:form>
```

## 6) Sample bean
```
@ManagedBean("bean")
@SessionScoped
public class Bean {
	private List<String> l;
	public Bean() {
		l = new ArrayList<String>();
		l.add("1");
		l.add("2");
		l.add("3");
	}
	public List<String> list() {
		return l;
	}
}
```

**Comment by cnsgithub** [comment] 2018-03-19 11:42
I have already described the main reason for this problem here:

https://github.com/primefaces/primefaces/issues/3442

The problem with inline-scripts is they are processed at the point where they are rendered. And since all PF code is now on the bottom, it can't run properly inline. If it does it's just a timing thing. You could use 

```
$(document).ready(function() {
   //all custom code here
});
```

to ease the problem. But even this is not fail-proof if jquery is included _after_ the code. Probably if still problems arise, you need to add something like this for the $ and PF variables:

https://stackoverflow.com/questions/7307983/while-variable-is-not-defined-wait

**Comment by tandraschko** [comment] 2018-03-19 12:20
NOTE: actually the users inline-script should also be moved the bottom and executed in the correct order. So it should work.

**Comment by tandraschko** [comment] 2018-03-19 12:30
Don't know where it comes from but i don't see any error in PF. The script is executed correctly and after jquery is ready.

**Comment by fmarangon** [comment] 2018-03-19 13:41
@tandraschko I don't know why it works fine for you, but this problem orignally aroused in another piece of code where it was working fine (and still is), until I refresh the whole page (F5 on browser).
The I see the behaviour I described.

I can also tell you that if I do and AJAX update on the component including the script (after the browser refresh) the drag function works fine so i guess @cnsgithub is right about the load timing.

For the time being I will just drop the MOVE_SCRIPTS_TO_BOTTOM param

**Comment by tandraschko** [comment] 2018-03-19 13:47
I didn't say that it works, i just said that the script is executed late, when jquery is already ready.
Probably the DataTable script is rendered before yours. Will check it later.

**Comment by tandraschko** [comment] 2018-03-19 14:02
Ok, no idea. As i said, the script order is ok.
Maybe a jquery bug or missusage. No time to check it.

**Comment by melloware** [comment] 2019-10-11 19:47
Attached is sample reproducer: 
[pf-3494.zip](https://github.com/primefaces/primefaces/files/3719397/pf-3494.zip)

**Comment by tandraschko** [comment] 2022-04-21 15:55
@melloware something to retest? :D

**Comment by melloware** [comment] 2022-04-21 16:30
Yep i will look at this one!

**Comment by melloware** [comment] 2022-04-21 16:58
OK i debugged what is going on and I think we should mark this as won't fix.   the `draggable` jquery UI code is pre-supposing the `this[0]` is inside the DOM element where this is taking place.  However since we are moving the script to the bottom of the page and outside of the DOM element it can't find `this[0]` properly.   

This is a corner use case and since its all how Jquery UI Draggable works under the covers I am inclined to not spend any time on it and Jquery UI is only making bug fixes not major enhancements going forward.

Thoughts?

**Closed as completed** 2022-04-21 17:26 UTC
Labels: Resolution:  Wontfix
