### ISSUE TITLE
SelectCheckBoxMenu: adjust header label when too many items selected

### ISSUE THREAD

**Issue by anuragnz** [primefaces/primefaces#11037] opened 2023-11-27 00:53 UTC
### Description

When too many items are selected, then the component just keep expanding to show all the items in the header as labels.
Is it possible to have Max number items to show and rest show for e.g. 5 more

### Describe the solution you would like

Similar to this:

![image](https://github.com/primefaces/primefaces/assets/3331466/f54bb6e7-afe0-4e2b-9319-6f5090c4e3f2)

**Comment by melloware** [comment] 2023-11-27 12:33
Duplicate of https://github.com/primefaces/primefaces/issues/10305 which is already fixed for 14.0.0

**Closed as not planned by melloware** 2023-11-27 12:33 UTC
Labels: Resolution: Duplicate
