### ISSUE TITLE
PanelGrid: Support ui:repeat for rows

### ISSUE THREAD

**Issue by macbyte0815** [primefaces/primefaces#3536] opened 2018-03-27 13:28 UTC
## 1) Environment
- PrimeFaces version:6.1.9
- Does it work on the newest released PrimeFaces version? Version?
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Wildfly 12
- Affected browsers:Chrome, FireFox, MS Edge 

## 2) Expected behavior

Try to show Some Values from a ArrayList to interact with and add new Values
![grafik](https://user-images.githubusercontent.com/37838119/37969545-4c158e96-31d1-11e8-9824-44463b00bc95.png)

I use this code:
<p:repeat var="konkurrent" value="#{kundenmMB.listKumerkmaleKonkurrenzApotheken}">
										<p:column>
											<p:inplace styleClass="ghEdit"  editor="true" event="dblclick" effectSpeed="fast" disabled="#{!(kundenmerkmalePermission.getUserpermissions(loginBean).contains('aendern') or kundenmerkmalePermission.getUserpermissions(loginBean).contains('*ALL'))}">
												<p:ajax event="save" listener="#{kundenmMB.saveKonkurrenzByBGAN(konkurrent.kubgan)}" update="@([id$=pgKonkurrenz])"/>
												<f:facet name="input">
													<p:autoComplete scrollHeight="200" size="10" id="autoCompleteMenuKonkurrenz1" dropdown="true" forceSelection="true" converter="kudaConverter" value="#{kundenmMB.konkurrenzToSave}" 
																	completeMethod="#{kundenmMB.kudaList}" var="menu" itemValue="#{menu}" itemLabel="#{menu.abda}" >
													</p:autoComplete>
												</f:facet>
												<f:facet name="output">
													<p:inputText readonly="true" style="text-align: center;" value="#{konkurrent.kubgan}" />		
												</f:facet>
											</p:inplace>
										</p:column>
									</p:repeat>

## 3) Actual behavior
![grafik](https://user-images.githubusercontent.com/37838119/37969743-d191814c-31d1-11e8-9aa2-3d9a7c655af6.png)
I tried It with this code:
<p:repeat var="grosshaendler" value="#{kundenmMB.listKumerkmaleGrosshaendler}">
									<p:row styleClass="thin-border">
										<p:column id="GHName_col" styleClass="no-border" >
											<p:inplace id="ghEdit" styleClass="ghEdit" editor="true" event="dblclick" effectSpeed="fast" disabled="#{!(kundenmerkmalePermission.getUserpermissions(loginBean).contains('aendern') or kundenmerkmalePermission.getUserpermissions(loginBean).contains('*ALL'))}">
												<p:ajax event="save" listener="#{kundenmMB.saveGH}" update="@([id$=pgGroßhaendler])"/>
												<f:facet name="input">
													<p:autoComplete scrollHeight="200" size="10" id="autoCompleteMenuphgh1" dropdown="true" forceSelection="true" converter="phghConverter" value="#{kundenmMB.selectedKm.phgh1}" 
																	completeMethod="#{phghBean.phghList}" var="menu" itemValue="#{menu}" itemLabel="#{menu.rfbesc.trim()}"  >
													</p:autoComplete>
												</f:facet>
												<f:facet name="output">
													<p:inputText readonly="true" style="text-align:center; width:130px;" value="#{grosshaendler.grossHaendlerName}"/>
												</f:facet>
											</p:inplace>
										</p:column>
										<p:column id="GHVol_col" styleClass="right">
											<p:inplace id="gh1volEdit" editor="true" event="dblclick" effectSpeed="fast" disabled="#{!(kundenmerkmalePermission.getUserpermissions(loginBean).contains('aendern') or kundenmerkmalePermission.getUserpermissions(loginBean).contains('*ALL'))}">
												<p:ajax event="save" listener="#{kundenmMB.saveGH()}" update="@([id$=pgGroßhaendler])"/>
												<f:facet name="input">
													<p:inputText size="1" value="#{kundenmMB.selectedKm.gh1vol}" />
												</f:facet>
												<f:facet name="output">
													<p:inputText readonly="true" style="text-align:center; width:70px;" value="#{grosshaendler.grossHaendlerEinkaufVoloumen * 1000}" >
														<f:convertNumber minFractionDigits="2" maxFractionDigits="2" pattern="#,##0.00" locale="de_DE"/>
													</p:inputText>
												</f:facet>
											</p:inplace>
											<p:spacer width="5" />
											<p:inputText readonly="true" value="&euro;"  size="1" style="text-align: center; width:15px;" />
										</p:column>
										<p:column id="GHDelete">
											<p:commandLink action="#" rendered="#{kundenmMB.selectedKm.phgh1 != null}" id="delete_lnk" styleClass="ui-icon ui-icon-trash" update="@([id$=pgGroßhaendler])"/>
										</p:column>
									</p:row>

Now with this code the StyleClass - Attribute and Style-Attribute is not working and destroy´s the nested objects like the p:input text with the €-Symbol inside the HTML Output you can see in the < input > the value attribute is not rendered.

## 4) Steps to reproduce

.. 

## 5) Sample XHTML

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:my="http://www.mastertheboss.com/custom-taglib"
      xmlns:p="http://primefaces.org/ui">

<h:head></h:head> 

<h:body> 
	<p:outputLabel value="TESTING">
	</p:outputLabel>
	#{testBean.SList.size()}
	<p:panelGrid >
		<p:repeat value="#{testBean.SList}" var="sList">
			<p:row style="border:5px !important">
				<p:column style="ui-noborder">
					<p:outputLabel value="#{sList}" />
				</p:column>
				<p:column >
					<p:outputLabel value="#{sList}" />
				</p:column>
			</p:row>	
		</p:repeat>
	
	</p:panelGrid>
	
	<p:panelGrid styleClass="thin-border">
		<p:row style="border:5px">
			<p:column style="border-width:5px">
				<p:outputLabel value="TESTING" />
			</p:column>
		</p:row>	
	</p:panelGrid>
</h:body> 
</html>

## 6) Sample bean

package test;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;

import lombok.Data;

@ManagedBean(name = "testBean")
public @Data class TestBean implements Serializable {

	private static final long serialVersionUID = 1L;
	private List<String> sList = null;

	@PostConstruct
    public void init() {
		sList = new ArrayList<String>();
		for (int i = 1; i <= 10; i++) {
			sList.add("" + i + ".ter Test");
		}
	}

}

**Comment by tandraschko** [comment] 2018-03-27 13:38
Why not use ui:repeat and a simple div as child?
p:repeat is just a hacky thing actually, which was introduced for a mojarra bug.

**Comment by macbyte0815** [comment] 2018-03-27 13:52
Tried it already with ui:repeat same issue -> Is not working. They have problems with the Style and StyleClass.
I´m working for 3 Years with primefaces. I have rewritten some Components that they are working for me like tabView with IFrames and so on. But I do´t want to rewrite your components that they are working as expected.

**Comment by tandraschko** [comment] 2018-03-27 13:57
I don't think that the support of row inside p:repeat should work correctly and was never desigend to work.

So please post a simple as possible example that a ui:repeat doesn't work and i can check that case.

**Comment by cnsgithub** [comment] 2018-03-27 13:58
The code to reproduce this is awful, a lot of proprietary code. You could have shown the issue with a lot less lines probably.

**Comment by macbyte0815** [comment] 2018-03-27 14:01
```xml
<h:body> 
	<p:outputLabel value="TESTING">
	</p:outputLabel>
	#{testBean.SList.size()}
	<p:panelGrid >
		<ui:repeat value="#{testBean.SList}" var="sList">
			<p:row style="border:5px !important">
				<p:column style="ui-noborder">
					<p:outputLabel value="#{sList}" />
				</p:column>
				<p:column >
					<p:outputLabel value="#{sList}" />
				</p:column>
			</p:row>	
		</ui:repeat>
	
	</p:panelGrid>
	
	<p:panelGrid styleClass="thin-border">
		<p:row style="border:5px">
			<p:column style="border-width:5px">
				<p:outputLabel value="TESTING" />
			</p:column>
		</p:row>	
	</p:panelGrid>
</h:body> 
```


![grafik](https://user-images.githubusercontent.com/37838119/37972146-eabfd38e-31d7-11e8-86fd-c2e86a819bee.png)
It´s not working p:repeat is a copy of ui:repeat

**Comment by tandraschko** [comment] 2018-03-27 14:02
ui:repeat inside panelGrid doesn't work, the component is not designed for this.

**Comment by tandraschko** [comment] 2018-03-27 14:03
This is actually a common mistake in some components in PF. I will set "new feature" as label.

**Comment by macbyte0815** [comment] 2018-03-27 14:05
What should i do now? Wait for the new Feature ?
Or do you have any ideas for a workaround ?

**Comment by tandraschko** [comment] 2018-03-27 14:08
hmpf, i actually don't like to answer things like "WTF" but the easiest way would be to implement it and provide a PR.

**Comment by macbyte0815** [comment] 2018-03-27 14:10
Oh I´m Sorry....
What do you mean with PR ? Don´t understand

**Comment by tandraschko** [comment] 2018-03-27 14:11
Pull Request, something like a automatic patch in GitHub.

**Comment by tandraschko** [comment] 2018-03-27 14:12
And after you implemented it, you can even just overwrite the renderer in your application to get an instant fix. After the next release, you can just remove the overwritten renderer class.

**Comment by macbyte0815** [comment] 2018-03-27 14:14
Excuse me, I have never done thomething like this. I normally solve all problems by myself and it work´s. Or found WA´s for the Problems. I don´t use GIThub. ALL IS NEW FOR ME.
This was why I have rewritten Components from PF to work for me.

**Comment by tandraschko** [comment] 2018-03-27 15:49
It would be great if you could give back your bugfixes to the community and provide pull requests in the future.
I don't know a workaround as i never used this component. But i can see a encodeDynamicBody and encodeStaticBody, so there might be a way to use dynamic data.

**Comment by melloware** [comment] 2020-07-13 18:37
duplicate of https://github.com/primefaces/primefaces/issues/3355

**Closed as completed** 2020-07-13 18:38 UTC
Labels: new feature
