### ISSUE TITLE
Table: WCAG compliance

### ISSUE THREAD

**Issue by kunzen16A** [primefaces/primefaces#7826] opened 2021-09-15 09:23 UTC
**Description:**
The Diamond showcase 'Table' does not fulfill the WCAG accessibility criterion 4.1.1 as it renders syntactically incorrect HTML code. There are 20 errors that the attributes readonly and aria-readonly are not allowed on element input at this point.

![image](https://user-images.githubusercontent.com/77410849/133403860-6744caa4-801e-4659-9896-ac449480cb22.png)

**Environment:**
PF Version: 10.0.0

**Reproduction:**
Use the following steps to reproduce the behavior:

- Open the showcase Tabel of the Diamond theme
- Use the bookmarklet "Check serialized DOM of current page" from https://validator.w3.org/nu/about.html#extras to run Nu 
   Html Checker on the showcase
- Subsequently use the bookmarklet "Check for WCAG 2.0 parsing compliance" from the page named before and execute it on the website of Nu Html Checker which you allready opened to filter the results
- Check the errors the Nu Html Checker still shows after running both bookmarklets

**Expected behavior:**
To fulfill the accessibility criterion Nu Html Checker should show no error messages after checking the table's HTML code.

**Comment by melloware** [comment] 2021-09-17 00:47
duplicate of https://github.com/primefaces/primefaces/issues/7827

**Closed as completed by melloware** 2021-09-17 00:47 UTC
Labels: Resolution: Duplicate, accessibility
