### ISSUE TITLE
dialog return event not working version 7.0

### ISSUE THREAD

**Issue by youssefali424** [primefaces/primefaces#5011] opened 2019-07-20 13:24 UTC
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: ${title}
  Example:
  SelectOneMenu: Converter not called
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Otherwise the example must be as small and simple as possible! It must be runnable without any other dependencies (like Spring,..., or project/company internal classes)!
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: payara 4.1 
- Affected browsers: all (tested it on firefox , opera and ie)

## 2) Expected behavior

actionlistener function in ajax tag with dialogReturn event to be called upon closing the dialog

## 3) Actual behavior

nothing happens

## 4) Steps to reproduce

click close button on the dialog

## 5) Sample XHTML

<h:form id="form" dir="rtl">
            <p:commandButton value="إضافة"  action="#{addLongExtensionBB.openAddDialog}">
                <p:ajax event="dialogReturn" listener="#{addLongExtensionBB.refreshList}"/>
            </p:commandButton> 
 </h:form>

## 6) Sample bean
```
@Named(value = "addLongExtensionBB")
@ViewScoped
public class AddLongExtensionBB implements Serializable {
public void openAddDialog() {
        Map<String, Object> options = new HashMap<>();
        options.put("modal", true);
        options.put("width", 800);
        options.put("height", 336);
        options.put("contentWidth", "100%");
        options.put("contentHeight", "100%");
        options.put("headerElement", "customheader");
        
        PrimeFaces.current().dialog().openDynamic("AddLongExtensionDialog", options, null);
    }
public void refreshList(SelectEvent event) {
        System.out.println("returned ");
    }
}
```

**Comment by melloware** [comment] 2019-07-20 13:43
@youssefali424 Can you please create a small reproducible test case using our Test project: https://github.com/primefaces/primefaces-test

A runnable sample helps us debug way faster.

**Comment by youssefali424** [comment] 2019-07-20 14:29
i tried the same code on the test project same result

**Comment by youssefali424** [comment] 2019-07-20 14:33
i dont understand it seems working with everyone but i tried it in the very simplest way same result the ajax tag is working as well with other events removed all styles , still the only thing that i didnt try is changing the primefaces version from pom file

**Comment by melloware** [comment] 2019-07-20 14:35
Can you zip your test project and attach it here so we can debug?  Or are you saying you can't get it to happen in the test project?

**Comment by youssefali424** [comment] 2019-07-20 15:43
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/3413753/primefaces-test-master.zip)
here it is

**Comment by youssefali424** [comment] 2019-07-20 15:44
i edited it with so simple logic to test it

**Comment by Rapster** [comment] 2019-07-20 16:09
@youssefali424 please fill the template correctly, the environment section is empty...

**Comment by youssefali424** [comment] 2019-07-20 16:17
sorry about that...

**Comment by Rapster** [comment] 2019-07-20 17:15
Hard to believe it ain't working since I tried it out recently. Did you read this; https://primefaces.github.io/primefaces/7_0/#/core/dialogframework ?

**Comment by youssefali424** [comment] 2019-07-21 06:41
so is it working with the test project i sent ?

**Comment by youssefali424** [comment] 2019-07-21 06:44
for sure i looked through the documentation all of it and tried every possible workaround i tried onHide in the options map to call a js function as well it didnt work, sure that clicking the close button calls the callback onHide?

**Comment by youssefali424** [comment] 2019-07-21 13:02
> Hard to believe it ain't working since I tried it out recently. Did you read this; https://primefaces.github.io/primefaces/7_0/#/core/dialogframework ?

i know everyone says its working thats why i was so reluctant to put it as an issue but it took too much time and effort , and i got nothing in return, may be i am doing some dummy thing thats what i thought but it didnt work on the test project as well

**Comment by melloware** [comment] 2019-07-21 15:17
@youssefali424 I will try your sample tomorrow and let you know what I find out.

**Comment by melloware** [comment] 2019-07-22 11:21
@youssefali424 Your example worked fine for me. I unzipped it ran "mvn clean jetty:run-exploded" and pressed the Add button it brought up you dialog.  When I closed the dialog I see the `System.out.println("returned ");` printed out in the console?

So again what is not working?

**Comment by youssefali424** [comment] 2019-07-22 17:38
man you saw it once or twice?

**Comment by youssefali424** [comment] 2019-07-22 17:46
i added it to the open dialog function as well

**Comment by melloware** [comment] 2019-07-22 18:03
Sorry didn't see that.  OK so the issue is the "return" is not fired when you close hte dialog with no action.  That is the exact behavior as the Showcase: https://www.primefaces.org/showcase/ui/df/data.xhtml

If you select a Car the Dialog Return is fired.  If you just close the dialog with the "X" that is considered "No Action" and the event is not fired.

Check out this ticket: https://github.com/primefaces/primefaces/issues/2696

**Comment by youssefali424** [comment] 2019-07-22 18:09
Now i get it but for sure it isnt even near clear in the documentation what is called when the close button is clicked.....sorry for taking too much of your time

**Comment by melloware** [comment] 2019-07-22 18:12
No problem.  I will close this for now as a duplicate of #2696 the request for a dialog close event.

**Closed as completed by melloware** 2019-07-22 18:12 UTC
Labels: Resolution: Duplicate
