### ISSUE TITLE
Calendar: Popup panel does now appear the second time after first time show up with effect.

### ISSUE THREAD

**Issue by anhquande** [primefaces/primefaces#4311] opened 2018-12-04 08:45 UTC
## 1) Environment
- PrimeFaces version: **6.3.SNAPSHOT**
- Does it work on the newest released PrimeFaces version? => **NO**. Version? **6.3.SNAPSHOT**
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) **NO**
- Application server + version: Does not matter
- Affected browsers: Chrome Version 70.0.3538.110 (Official Build) (64-bit), maybe with other browsers as well

## 2) Expected behavior

- Calendar Popup panel should show up next to the input field

## 3) Actual behavior

- Calendar Popup panel does not show up, only one top line is visible

## 4) Steps to reproduce

- Go to [Primefaces Showcases / Page: Calendar](https://www.primefaces.org/showcase/ui/input/calendar.xhtml) (or checkout from source code)
- Click on the field Effect to open the Calendar popup panel.
- because of the effect, the panel is not shown up immediately. While the panel is not completely rendered, quickly click on other input field to open another popup.
- The bug will happen.
![primefaces-calendar](https://user-images.githubusercontent.com/4417654/49429784-ae439b00-f7a9-11e8-97c1-b18d8fc54d24.png)

**Comment by melloware** [comment] 2018-12-04 12:07
Please close. This is a duplicate of https://github.com/primefaces/primefaces/issues/489

**Closed as completed** 2018-12-04 12:09 UTC
Labels: Resolution: Duplicate
