### ISSUE TITLE
CSP: onclick events fail on Premium Themes

### ISSUE THREAD

**Issue by william-shuman** [primefaces/primefaces#5712] opened 2020-03-20 12:05 UTC
CspResponseWriter should wrap javascript in $(function() {});
## 1) Environment
- PrimeFaces version: 8.0
- Does it work on the newest released PrimeFaces version? Version? No, 8.0
- Does it work on the newest sources in GitHub? No
- Application server + version: JBoss EAP 7.1
- Affected browsers: Firefox, Chrome were tested and failed in some instances

## 2) Expected behavior
Events work after implementing CSP

## 3) Actual behavior
Events don't work after implementing CSP

## 4) Steps to reproduce
The left slide out menu in Barcelona doesn't fire events

## 5) Sample XHTML
<pa:tabMenu>
                <pa:tab icon="fa fa-home" title="Home">
                    <pa:menu>
                        <p:menuitem value="Change Something" icon="fa fa-exchange" action="#{bean.change}"
                                    ajax="false" onclick="loadingStart()"/>
                    </pa:menu>
                </pa:tab>
...

## 6) Sample bean
public String change() {
		return Pages.HOME + Pages.REDIRECT_SUFFIX;
	}

The CSP JavaScript should be wrapped in $(function() { ... });  If the JavaScript inside of the CSP block is run again then it starts to work.

**Comment by tandraschko** [comment] 2020-03-20 12:32
This workaround should work fine: primefaces.MOVE_SCRIPTS_TO_BOTTOM = true in your web.xml

**Comment by tandraschko** [comment] 2020-03-20 12:34
Also bit weird as we only move the onclick registration to the end of the body, which should be like $(...); 
@melloware  can you take a look?

**Comment by melloware** [comment] 2020-03-20 12:45
Hmmm yeah i wonder is this something special with the Barcelona menu component which is custom?

**Comment by melloware** [comment] 2020-03-20 12:45
Is this reproducible without having Barcelona in a regular PrimeFaces Test case so I can debug?

**Comment by william-shuman** [comment] 2020-03-20 12:49
I've only reproduced it in my project with that menu. I'll try to put something together today.

The MOVE_SCRIPTS_TO_BOTTOM workaround does resolve the issue for now.

**Comment by melloware** [comment] 2020-03-20 12:50
Thanks @william-shuman That will help me fix it.

**Comment by william-shuman** [comment] 2020-03-21 13:35
**https://github.com/william-shuman/csp-test**

This project will generate the csp js without the $(function() { ... });

**Comment by melloware** [comment] 2020-03-21 19:08
Excellent. This should help me fix it.

**Comment by melloware** [comment] 2020-03-23 11:44
@william-shuman I have made a self contained version of your example.

Download:
[pf-5712.zip](https://github.com/primefaces/primefaces/files/4369056/pf-5712.zip)

Run `mvn clean jetty:run-exploded`.
Navigate to http://localhost:8080/primefaces-test/test.xhtml

You app is working fine for me with CSP?

**Comment by william-shuman** [comment] 2020-03-23 15:19
Here is a example that doesn't work with CSP enabled but works without CSP.

https://github.com/william-shuman/csp-test/raw/master/csp_test.zip

**Comment by melloware** [comment] 2020-03-23 15:41
I am getting JS errors with or without CSP turned on...
![image](https://user-images.githubusercontent.com/4399574/77334460-33362900-6cfb-11ea-84b1-6236949a6899.png)

**Comment by melloware** [comment] 2020-03-23 16:02
also testing if I wrap it in `$(function() { ... });` it then works, but then when run as MOVE_SCRIPTS_TO_BOTTOM its broken either wrapped or NOT wrapped in `$(function() { ... });`.  So I really feel like this is something with this Barcelona component?

**Comment by william-shuman** [comment] 2020-03-23 16:04
latest fixed those errors.

https://github.com/william-shuman/csp-test/raw/master/csp_test.zip

**Comment by melloware** [comment] 2020-03-23 16:18
Thanks that example removed all the noise and help me fix and test with both MOVE_TO_BOTTOM on an off.  All is working now with my PR

**Comment by william-shuman** [comment] 2020-03-23 16:20
Thanks for taking a look and for the PR.

**Comment by melloware** [comment] 2020-04-02 18:52
I created a forum post on Barcelona here: https://forum.primefaces.org/viewtopic.php?f=53&t=61552

**Comment by melloware** [comment] 2020-04-03 12:00
OK @mertsincan suggestion I edit the Barcelona layout.js and change this line.
```javascript
this.menulinks.off('click.menuitem').on('click.menuitem', function(e) { // instead of off('click')
```

And sure enough that worked with CSP=true and not needing MoveScripts to bottom.

So PrimeTek probably has to update all their Premium Theme layouts to add qualifiers to their `click`  events in their layout.js files.

I am going to close this ticket because its a fix required in the Premium Themes and not anything the community can fix.

**Closed as completed by melloware** 2020-04-03 12:00 UTC
Labels: Resolution:  Wontfix

**Comment by melloware** [comment] 2020-04-21 16:58
Looks like Premium Themes have been updated for 8.0: https://forum.primefaces.org/viewtopic.php?f=3&t=61761
