### ISSUE TITLE
Menu: wrong calculated position with overlay="true"

### ISSUE THREAD

**Issue by astranCZ** [primefaces/primefaces#4536] opened 2019-02-13 06:15 UTC
## 1) Environment
- PrimeFaces version: 7.0.RC2
- Application server + version: Tomcat 7 and 9
- Affected browsers: All

## 2) Expected behavior
Calculated position of tag p:menu (overlay="true") on p:dialog is not dependent on the position of the scroll bar main window. 

## 3) Actual behavior
Calculated position of tag p:menu (overlay="true") on p:dialog is dependent on the position of the scroll bar main window.

## 4) Steps to reproduce
Create page with vertival scroll bar. Open p:dialog with button with p:menu (overlay="true").
p:menu position is dependent on the location of the scroll bar.

## 5) Sample XHTML

```
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>

<h:body style="height: 1500px;">
	<p:commandButton value="Modal" type="button" onclick="PF('dlg2').show();" />

	<p:dialog header="Modal Dialog" widgetVar="dlg2" modal="true" position="top" height="150">
		<h:form>
			<h:outputText value="This is a Modal Dialog." />
			<h3>Overlay</h3>
			<p:commandButton id="dynaButton" value="Show menu" type="button" />
			<p:menu overlay="true" trigger="dynaButton" my="left top" at="left bottom">
				<p:menuitem value="Save" />
				<p:menuitem value="Update" />
			</p:menu>
		</h:form>
	</p:dialog>
</h:body>
</html>
```

**Comment by OBreidenbach** [comment] 2019-02-14 10:54
I have the same behavior with a SelectOneMenu inside of a Dialog. If the drop down is visible it stays on its position in the view port during scrolling. So it looses contact to the component.
That did not happen with PF6.2

**Comment by melloware** [comment] 2019-02-14 11:53
@OBreidenbach do you mean this issue?  https://github.com/primefaces/primefaces/issues/4180

**Comment by melloware** [comment] 2019-02-14 12:00
@astranCZ Like I said in the other thread this isn't a fix more like a workaround but for now you can...

On 7.0RC2 is to set the p:dialog property to blockScroll="true".  That disables the page scrollbar while a modal dialog is being displayed.  To me this is good default behavior of a modal dialog as you should not need to scroll the outer page if a modal is displayed.

```xml
<p:dialog header="Autocomplete" widgetVar="dlg2" modal="true" blockScroll="true">
```

**Comment by tandraschko** [comment] 2019-02-14 13:17
works fine for me with trunk

EDIT: ok, not for all cases :D

**Comment by OBreidenbach** [comment] 2019-02-14 13:33
@melloware no I do not mean #4180. In #4180 the select box was initially rendered at the top left corner of the view port. No the select box is rendered at the right place, under the component. But if you scroll the page, everything moves, only the select box stays at it place relative to the view port.
Often our dialogs are higher than the view port, so blockScroll is no option for us.

**Comment by melloware** [comment] 2019-02-14 13:41
Thanks for the clarification.

**Comment by mertsincan** [comment] 2019-02-14 14:38
If I don't remember wrong, offset property has been removed position API. Maybe, this issue is related to it.???

**Comment by mertsincan** [comment] 2019-02-14 14:38
Please see; http://jqueryui.com/upgrade-guide/1.10/#removed-offset-option-use-my-or-at

**Comment by tandraschko** [comment] 2019-02-14 14:40
not sure, our jqueryui version seems quite old

**Comment by melloware** [comment] 2019-02-14 14:43
I think our Jquery UI 1.12.1 is the latest UI version available?

**Comment by mertsincan** [comment] 2019-02-14 14:50
Note: The offset option will be removed in 1.10; http://jqueryui.com/upgrade-guide/1.9/#deprecated-offset-option-merged-into-my-and-at

Our version is v1.12.1

**Comment by OBreidenbach** [comment] 2019-02-14 15:45
IMHO this is because of https://github.com/primefaces/primefaces/blob/9091e47cd104779e19d8191d471685be1b2bfdf4/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js#L989
Introduced by @mertsincan for issue #4126 
If I remove the line, for me everything is working fine.
But this only explains the behavior, for the SelectOneMenu not for the menu overlay=true.

**Comment by mertsincan** [comment] 2019-02-14 22:37
Please try this example;
[test.txt](https://github.com/primefaces/primefaces/files/2867041/test.txt)

I made some changes in align and show methods of Menu widget.
```
show: function() {
    this.jq.css({
        'z-index': ++PrimeFaces.zindex,
        'visibility': 'hidden'
    }).show();

    this.align();
    this.jq.css('visibility', '');
},
...
align: function () {
    this.jq.css({left: '', top: ''}).position({
        my: this.cfg.my
        ,at: this.cfg.at
        ,of: this.trigger
    });
}
```

Position API Note: jQuery UI does not support positioning hidden elements. Please see; https://api.jqueryui.com/position/

**Comment by melloware** [comment] 2019-02-15 14:59
Looks good to me @mertsincan but i will let anyone else try their use case.

**Comment by tandraschko** [comment] 2019-02-15 15:59
so autocomplete and all other components needs to fix, too?
we have many components with overlays like select* or chips.

**Comment by OBreidenbach** [comment] 2019-02-18 08:39
I did some testing:
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        <h:form id="formButton">
            <p:commandButton id="buttonShow"
                             onclick="PF('dialogVar').show()"
                             value="Open Dialog"/>
        </h:form>
        <p:dialog id="dialog"
                  positionType="absolute"
                  widgetVar="dialogVar"
                  closable="true"
                  visible="true"
                  resizable="true">

            <h:form id="formDialog">
                <h1>Wrong scroll behavior</h1>

                <h3>colorPicker</h3>
                <p:colorPicker value="#{testViewCdi.color}"/>

                <h3>Overlay</h3>
                <p:commandButton id="dynaButton" value="Show menu" type="button" />
                <p:menu overlay="true" trigger="dynaButton" my="left top" at="left bottom">
                    <p:menuitem value="Save" />
                    <p:menuitem value="Update" />
                </p:menu>

                <h3>selectOneMenu</h3>
                <p:selectOneMenu >
                    <f:selectItem itemLabel="1"/>
                    <f:selectItem itemLabel="2"/>
                    <f:selectItem itemLabel="3"/>
                </p:selectOneMenu>


                <h1>Correct scroll behavior</h1>

                <h3>chips</h3>
                <p:chips />

                <h3>calendar</h3>
                <p:calendar />

                <h3>datePicker</h3>
                <p:datePicker />

                <h3>keyboard</h3>
                <p:keyboard />

                <h3>password</h3>
                <p:password feedback="true" />

                <h3>selectCheckboxMenu</h3>
                <p:selectCheckboxMenu updateLabel="true" labelSeparator=", ">
                    <f:selectItem itemLabel="1"/>
                    <f:selectItem itemLabel="2"/>
                    <f:selectItem itemLabel="3"/>
                </p:selectCheckboxMenu>

                <h3>textEditor</h3>
                <p:textEditor widgetVar="editor1" height="300" style="margin-bottom:10px"/>
                <p:commandButton id="buttonHide"
                                 onclick="PF('dialogVar').hide()"
                                 value="Hide Dialog"/>
            </h:form>
        </p:dialog>

    </h:body>
</html>
```
I found the menu overlay, colorpicker and selectOneMenu. 

Others working fine: chips, calendar, datePicker, keyboard, password, selectCheckboxMenu and textEditor.
It does not seem as it is a general problem. May be we should create a separate issue for every component that has wrong scrolling behavior?

**Comment by mertsincan** [comment] 2019-02-18 09:52
Thanks a lot for your test, @OBreidenbach;) But, Dialog has two positionType; fixed and absolute. Could you please try the above test page without positionType? Also, please add  ```<h:body style="width: 15000px; height: 15000px">``` Then, after you open the panel of selectCheckboxMenu and scroll the page (vertical scroll and horizontal scroll), you will see that the panel is in different places of page.

I need to change setupDialogSupport method like;
```
setupDialogSupport: function() {
        var dialog = this.trigger.parents('.ui-dialog:first');

        if(dialog.length == 1 && dialog.css('position') === 'fixed') {
            this.jq.css('position', 'fixed');
        }
    },
```

**Comment by mertsincan** [comment] 2019-02-18 10:02
Is the menu fix Ok for everyone? @OBreidenbach, @melloware, @tandraschko ?? 

```
show: function() {
    this.jq.css({
        'z-index': ++PrimeFaces.zindex,
        'visibility': 'hidden'
    }).show();

    this.align();
    this.jq.css('visibility', '');
},
...
align: function () {
    this.jq.css({left: '', top: ''}).position({
        my: this.cfg.my
        ,at: this.cfg.at
        ,of: this.trigger
    });
},
...
setupDialogSupport: function() {
        var dialog = this.trigger.parents('.ui-dialog:first');

        if(dialog.length == 1 && dialog.css('position') === 'fixed') {
            this.jq.css('position', 'fixed');
        }
    },
```

**Comment by melloware** [comment] 2019-02-18 12:33
@mertsincan I did some minimal testing and it looks OK to me.  I did not stress it heavily though.

**Comment by OBreidenbach** [comment] 2019-02-18 13:09
@mertsincan If posititionType="fixed" the overlay menu is rendered at the correct location. 
But with positionType="absolute" it still does not scroll with the dialog.

**Comment by mertsincan** [comment] 2019-02-18 13:25
Thanks @melloware ;) @OBreidenbach Could you please attach a sample page for me?

Also, did you add my fixes into your page? (https://github.com/primefaces/primefaces/issues/4536#issuecomment-464666937)
Test page with my fixes;
[test.txt](https://github.com/primefaces/primefaces/files/2875775/test.txt)
Could you please try it?

**Comment by OBreidenbach** [comment] 2019-02-18 13:52
@mertsincan Sorry I missed your change to setupDialogSupport (dialog.css('position') === 'fixed'). 
Your fix is working for both positionTypes.
My sample page is the same as in https://github.com/primefaces/primefaces/issues/4536#issuecomment-464637526, plus your fix in the head section.

**Comment by tandraschko** [comment] 2019-02-19 15:07
@mertsincan will you also fix the others before the 7.0 release?
As mentioned in the ticket, colorpicker and selectOneMenu doesn't work, too.
And there is a ticket for AutoComplete: https://github.com/primefaces/primefaces/issues/4541

**Comment by mertsincan** [comment] 2019-02-28 07:48
Ok. I will work on these issues today ;)

**Closed as completed** 2019-02-28 08:05 UTC
Labels: :lady_beetle: defect, 6.2.18

**Comment by mertsincan** [comment] 2019-02-28 10:52
@OBreidenbach, @melloware and @tandraschko. Could you please check the fixes in the above issues? 
(Menu-SelectOneMenu-ColorPicker-InputTextarea-OverlayPanel)

**Comment by OBreidenbach** [comment] 2019-02-28 12:01
I checked ColorPicker, SelectOneMenu and Menu(overlay=true). They all scroll fine in a Dialog positionTyp="absolute".

**Comment by mertsincan** [comment] 2019-02-28 12:15
Thanks a lot, @OBreidenbach ;)

**Comment by heatherita** [comment] 2019-12-05 17:38
I am having this issue with the following:

```
<p:datatable>
<p:column>
<p:selectonemenu/>
</p:column>
</p:datatable>
```
I'm using PF 7.0 with the California custom theme 2.0. My select menu shows in upper left and not under the component. Has a workaround been found? Thanks.

**Comment by heatherita** [comment] 2019-12-05 20:48
Just to give a bit more detail on the issue, using the FF dom inspector, I see that when I click the p:selectonemenu the overlay box changes, I think due to a js script.

It changes from this:

`<div id="trackingForm:trackingTabs:searchTermListAdv:0:ctlSearchNumAdv_panel" class="ui-selectonemenu-panel ui-widget ui-widget-content ui-corner-all ui-helper-hidden ui-shadow ui-input-overlay" style="width: 209px; left: 0px; top: 26px; display: none;"><div class="ui-selectonemenu-items-wrapper" style="max-height:200px"><ul id="trackingForm:trackingTabs:searchTermListAdv:0:ctlSearchNumAdv_items" class="ui-selectonemenu-items ui-selectonemenu-list ui-widget-content ui-widget ui-corner-all ui-helper-reset" role="listbox" aria-activedescendant="trackingForm:trackingTabs:searchTermListAdv:0:ctlSearchNumAdv_0"><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="PO Number" tabindex="-1" role="option" id="trackingForm:trackingTabs:searchTermListAdv:0:ctlSearchNumAdv_13">PO Number</li></ul></div></div>
`

to this:

```
<div id="trackingForm:trackingTabs:searchTermListAdv:0:ctlSearchNumAdv_panel" class="ui-selectonemenu-panel ui-widget ui-widget-content ui-corner-all ui-helper-hidden ui-shadow ui-input-overlay" style="width: 209px; left: 0px; top: 26px; display: block; z-index: 1012;"><div class="ui-selectonemenu-items-wrapper" style="max-height:200px"><ul id="trackingForm:trackingTabs:searchTermListAdv:0:ctlSearchNumAdv_items" class="ui-selectonemenu-items ui-selectonemenu-list ui-widget-content ui-widget ui-corner-all ui-helper-reset" role="listbox" aria-activedescendant="trackingForm:trackingTabs:searchTermListAdv:0:ctlSearchNumAdv_0"><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="PO Number" tabindex="-1" role="option" id="trackingForm:trackingTabs:searchTermListAdv:0:ctlSearchNumAdv_13">PO Number</li>
</ul></div></div>
```

The problem is with the style attribute in the first div, some js script is causing it to be displayed and have  `z-index: 1012;`

Until it gets resolved, my only choice is to use `<h:selectonemenu>` which seems to work. 

thanks,

Heather

**Comment by melloware** [comment] 2019-12-05 20:58
PF always does "PrimeFaces.zindex++" starting at 1000 so any components on the page get incremented by 1.  That is why you are seeing the 1012.

**Comment by heatherita** [comment] 2019-12-05 21:07
I understand, but the inline style on that div is causing it to be displayed in the upper left. Is there something I can do to eliminate it?

`style="width: 209px; left: 0px; top: 26px; display: block;"`

**Comment by melloware** [comment] 2019-12-05 21:14
I would open an issue on the California forum: https://forum.primefaces.org/viewforum.php?f=79

**Comment by mertsincan** [comment] 2019-12-20 12:57
Hi @heatherita,

Could you please try it without California? I think this issue is not related to California. The theme/layout does not interfere with the z-index.
