### ISSUE TITLE
p:SelectOneMenu - JS function selectValue does not work 

### ISSUE THREAD

**Issue by wlhUser** [primefaces/primefaces#7557] opened 2021-07-08 09:24 UTC
For <p:selectOneMenu> the JS function widget.selectValue() does not work. Seems that the component is not correctly initialized.

**Reproducer**
Can be reproduced on the PF ShowCase Site:
1. Go to Show Case 'selectOneMenu'
2. Find the id of the component 'Hide NoSelection Option' in the browser debugger
3.  Execute in the browser debugger:
`PrimeFaces.getWidgetById('j_idt302:hideNoselectionOption').selectValue('Option2')`
Where 'j_idt302:hideNoselectionOption* is the ID in my case.
4. Error:
`Uncaught TypeError: this.items is undefined
    selectValue https://www.primefaces.org/showcase/javax.faces.resource/components.js.xhtml?ln=primefaces&v=10.0.0:20
    <anonymous> debugger eval code:1
`
5. Click on the element to open and close the selection list - this seems to initialize the component.
6. Execute the code from 3. again
7. Now it works - for one single time. Before executing the JS again you have to open/close the box again.

**Environment:**
 - PF Version: 10.0.4
  - Affected browsers: Chrome, Firefox

**Hint**:
Taking a look at the JS Code in 'forms.selectonemenu.js', the method 'init(cfg)' might not call 'initContents()' as initially '(this.itemWrapper.children().length == 0'. However, this is no sophisticated analysis, but more or less a rough guess.

**Comment by melloware** [comment] 2021-07-08 12:20
Duplicate of https://github.com/primefaces/primefaces/issues/7393 and workaround already provided there.

**Closed as completed by melloware** 2021-07-08 12:20 UTC
Labels: Resolution: Duplicate
