### ISSUE TITLE
DataTable: Invalid DOM (Incorrect Order of Body and Footer)

### ISSUE THREAD

**Issue by tetzla** [primefaces/primefaces#7187] opened 2021-03-31 16:34 UTC
**Description**

The serialized DOM of an EMPTY DataTable does not fulfill the "Web Content Accessibility Guidelines (WCAG)" (see https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0#qr-ensure-compat-parses). The footer element ist followed by the body element:

![HTML Check](https://user-images.githubusercontent.com/81367382/113178515-f62a3e00-924e-11eb-9580-980feecc3d46.png)

**Reproducibility**

1. Add bookmarklets "Check serialized DOM of current page" and "Check for WCAG 2.0 parsing compliance" from https://validator.w3.org/nu/about.html to browser favorites.
2. Create a web page with an empty DataTable:
![CodeSnippet](https://user-images.githubusercontent.com/81367382/113178497-f296b700-924e-11eb-9352-951630c809f3.png)
3. Run bookmarklet "Check serialized DOM of current page" on this page.
4. Run bookmarklet "Check for WCAG 2.0 parsing compliance" on the validator page.

We are providing web applications for the public sector, therefore WCAG conformity is required (see https://en.wikipedia.org/wiki/Web_Content_Accessibility_Guidelines#European_Union).

**Environment**

PF version: 8.0.5 (and probably higher)
Affected browsers: ALL

**Comment by melloware** [comment] 2021-03-31 16:46
Attached is my reproducer:
[pf-7187.zip](https://github.com/primefaces/primefaces/files/6238121/pf-7187.zip)

I am not seeing that....here is the HTML rendered in the DOM:
```xml
<table role="grid">
    <thead id="frmTest:emptyTable_head">
        <tr role="row">
            <th id="frmTest:emptyTable:j_idt7" class="ui-state-default" role="columnheader" scope="col">
                <span class="ui-column-title"></span>
            </th>
        </tr>
    </thead>
    <tbody id="frmTest:emptyTable_data" class="ui-datatable-data ui-widget-content">
        <tr class="ui-widget-content ui-datatable-empty-message">
            <td colspan="1">No records found.</td>
        </tr>
    </tbody>
    <tfoot id="frmTest:emptyTable_foot">
        <tr>
            <td class="ui-state-default">
                <span title="">Footer</span>
            </td>
        </tr>
    </tfoot>
</table>
```

**Comment by miedrl** [comment] 2021-04-01 06:55
@melloware Please try out the following code to reproduce the error:
![emptyTable](https://user-images.githubusercontent.com/77431692/113255260-e7cc3880-92c7-11eb-8d8d-4a1cde0121a3.png)

**Comment by jepsar** [comment] 2021-04-01 06:55
Isn't this a duplicate of #6301 ?

**Comment by tetzla** [comment] 2021-04-01 08:12
I agree, it is a duplicate of  #6301.

I'm little bit confused about the release strategy:

https://github.com/primefaces/primefaces/releases -> Why is there no release 9?
https://www.primefaces.org/store/elite.xhtml -> When will the next Elite release be published?

**Comment by jepsar** [comment] 2021-04-01 09:21
9 is skipped https://www.primefaces.org/introducing-primefaces-10-the-nextgen

Elite was released last week https://www.primefaces.org/primefaces-7-0-20-and-8-0-8-released/ previous release was 2 months ago

**Comment by tetzla** [comment] 2021-04-01 11:03
Is there a planned date for Elite 10 or even 11?

**Comment by melloware** [comment] 2021-04-01 11:47
10 you can get right now from Maven Central.
```xml
<dependency>
     <groupId>org.primefaces</groupId>
     <artifactId>primefaces</artifactId>
     <version>10.0.0</version>
 </dependency>
```

10.0.1 will most likely be the first Elite release but eveyrone is on public 10.0.0 right now.

**Closed as completed** 2021-04-01 11:48 UTC
Labels: Resolution: Duplicate

**Comment by melloware** [comment] 2021-04-01 11:53
@tetzla that is why I provided the runnable reproducer above on 10.0.0.  If you had run `mvn clean  jetty:run` with my attached reproducer you would see its working.  That is why we request these little reproducers before reporting bugs.
