### ISSUE TITLE
Enable the use of p:ajax for the p:ribbon component

### ISSUE THREAD

**Issue by alarive** [primefaces/primefaces#1514] opened 2016-06-10 14:32 UTC
p:ribbon does not allow the use of p:ajax because it does not implement ClientBehaviorHolder. It is a bit strange because p:ribbon seems to share a lot of functionnality with p:tabView, and p:tabView allows p:ajax

**Comment by alarive** [comment] 2016-07-21 08:42
Any idea when you plan to implement this ?

**Comment by tandraschko** [comment] 2016-07-21 10:18
No plans currently, but you can provide a PR

**Comment by melloware** [comment] 2017-03-22 00:01
Duplicate of https://github.com/primefaces/primefaces/issues/2185

**Closed as completed** 2017-03-22 14:02 UTC
Labels: new feature
