### ISSUE TITLE
SelectOneMenu: Filter input has wrong WAI-ARIA aria-controls 

### ISSUE THREAD

**Issue by ZeroBrushV2** [primefaces/primefaces#9727] opened 2023-01-25 15:14 UTC
### Describe the bug

Using the filter feature on SelectOneMenu it will generate a input in the dropdown where you can write down what to search.

The whole panel for the selectedOneMenu HTML will look like this:
```
<div id="j_idt319:optionSearch_panel"
    class="ui-selectonemenu-panel ui-widget ui-widget-content ui-corner-all ui-helper-hidden ui-shadow ui-input-overlay"
    style="
    display: block;
    width: 376.388px;
    left: 696.388px;
    top: 246.4px;
    transform-origin: center bottom;
    z-index: 1003;
  ">
    <div class="ui-selectonemenu-filter-container">
        <input class="ui-selectonemenu-filter ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all"
            id="j_idt319:optionSearch_filter" name="j_idt319:optionSearch_filter" type="text" autocomplete="off"
            aria-autocomplete="list" aria-controls="j_idt319:optionSearch_table" aria-label="Filter" /><span
            class="ui-icon ui-icon-search"></span>
    </div>
    <div class="ui-selectonemenu-items-wrapper" style="max-height: 200px">
        <ul id="j_idt319:optionSearch_items"
            class="ui-selectonemenu-items ui-selectonemenu-list ui-widget-content ui-widget ui-corner-all ui-helper-reset"
            role="listbox" aria-activedescendant="j_idt319:optionSearch_0">
            <li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-highlight" tabindex="-1"
                role="option" data-label="Select One" aria-selected="true" id="j_idt319:optionSearch_0">
                Select One
            </li>
            <li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" tabindex="-1" role="option"
                data-label="Option1" aria-selected="false" id="j_idt319:optionSearch_1">
                Option1
            </li>
            <li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" tabindex="-1" role="option"
                data-label="Option2" aria-selected="false" id="j_idt319:optionSearch_2">
                Option2
            </li>
            <li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" tabindex="-1" role="option"
                data-label="Option3" aria-selected="false" id="j_idt319:optionSearch_3">
                Option3
            </li>
        </ul>
    </div>
    <div class="ui-selectonemenu-footer">
        <div id="j_idt319:j_idt413" role="separator"
            class="ui-divider ui-widget mt-0 ui-divider-horizontal ui-divider-solid ui-divider-left"></div>
        <span style="font-weight: bold">3 options</span>
    </div>
</div>
```

Let's focus on the problem, the input for the filter:
```
<input class="ui-selectonemenu-filter ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all"
    id="j_idt319:optionSearch_filter" name="j_idt319:optionSearch_filter" type="text" autocomplete="off"
    aria-autocomplete="list" aria-controls="j_idt319:optionSearch_table" aria-label="Filter" />
```

The attribute `aria-controls` refers to an id that's not present in the page at all.

### Reproducer

Using the ShowCase 13.0.0-SNAPSHOT just add this to the oneMenu.xhtml:
```
<div class="field col-12 md:col-4">
                        <p:outputLabel for="@next" value="Filter Accessability Problem"/>
                        <p:selectOneMenu filter="true" filterMatchMode="startsWith" id="optionSearch" value="#{selectOneMenuView.selectedOption}">
                            <f:selectItem itemLabel="Select One" itemValue=""/>
                            <f:selectItem itemLabel="Option1" itemValue="Option1"/>
                            <f:selectItem itemLabel="Option2" itemValue="Option2"/>
                            <f:selectItem itemLabel="Option3" itemValue="Option3"/>
                            <f:facet name="footer">
                                <p:divider styleClass="mt-0" />
                                <h:outputText value="3 options" style="font-weight:bold;"/>
                            </f:facet>
                        </p:selectOneMenu>
                    </div>
```

### Expected behavior

The aria-controls attribute should be like this:
`aria-controls=j_idt319:optionSearch_items`.
**NOTE: AS FOR MY DISCRETION I CHOOSE THE VALUE INSIDE THE ATTRIBUTE AS THE ONE THAT FITS THE WAI-ARIA STANDARD. AN OPEN DISCUSSION COULD VOTE THE APPROPRIATE ID TO INSERT IN THE ATTRIBUTE**

As per WAI-ARIA combobox standard [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/combobox_role):

> When a combobox's popup is displayed, ensure the [aria-controls](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls) attribute on the combobox element is set to the [id](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#id) of the popup listbox, tree, grid, or dialog element. This is how the relationship between the element with the combobox role and the popup it controls is indicated. (Note: In older ARIA specs, this was aria-owns rather than aria-controls, so you may see aria-owns in older combobox implementations. The aria-owns in the code should be updated to aria-controls!))

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

MyFaces

### JSF version

2.0

### Java version

1.8

**Comment by melloware** [comment] 2023-01-25 15:29
Duplicate of https://github.com/primefaces/primefaces/issues/9279

Please add your details there.

**Closed as not planned by melloware** 2023-01-25 15:29 UTC
Labels: Resolution: Duplicate
