### ISSUE TITLE
primefaces datatable subtable very very useful,why is deprecated????

### ISSUE THREAD

**Issue by pfdeveloper** [primefaces/primefaces#4177] opened 2018-10-30 12:00 UTC
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Please use the naming convention for the title:
  ${component}: primefaces datatable subtable
  Example:

## 1) Environment
- PrimeFaces version: pf 6.2
- Does it work on the newest released PrimeFaces version? Version? yes it works but get me info it was deprecated
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:
- Affected browsers: google chrome

## 2) Expected behavior

...  primefaces datatable subtable is useful when we use  list iterate inside  another list 
... primefaces datatable subtable is useful more than rowgroup

## 3) Actual behavior

..INFO: SubTable has been deprecated, use row grouping instead

## 4) Steps to reproduce

.. 

## 5) Sample XHTML
<h:form>
    <p:dataTable var="team" value="#{dtSubTableView.teams}">
        <f:facet name="header">
            NBA Teams
        </f:facet>
 
        <p:columnGroup type="header">
            <p:row>
                <p:column rowspan="2" headerText="Team" />
                <p:column colspan="2" headerText="Stats" />
            </p:row>
            <p:row>
                <p:column headerText="Wins" />
                <p:column headerText="Losses" />
            </p:row>
        </p:columnGroup>
 
        <p:subTable var="stats" value="#{team.stats}">
            <f:facet name="header">
                <h:outputText value="#{team.name}" />
            </f:facet>
            <p:column>
                <h:outputText value="#{stats.season}" />
            </p:column>
            <p:column>
                <h:outputText value="#{stats.win}" />
            </p:column>
            <p:column>
                <h:outputText value="#{stats.loss}" />
            </p:column>
            <p:columnGroup type="footer">
                <p:row>
                    <p:column footerText="Totals: " style="text-align:right"/>
                    <p:column footerText="#{team.allWins}" />
                    <p:column footerText="#{team.allLosses}" />
                </p:row>
            </p:columnGroup>
        </p:subTable>
    </p:dataTable>
</h:form>
..

## 6) Sample bean

..

**Comment by tandraschko** [comment] 2018-10-30 12:01
duplicate of: https://github.com/primefaces/primefaces/issues/2269

**Closed as completed by tandraschko** 2018-10-30 12:01 UTC

**Comment by pfdeveloper** [comment] 2018-10-30 12:06
thats mean its still deprecated???

**Comment by tandraschko** [comment] 2018-10-30 12:10
PrimeTek decided to mark it as deprecated long time ago, i don't know anything else. Thats up to @mertsincan / @cagataycivici.

**Comment by pfdeveloper** [comment] 2018-10-30 12:14
its work fine on pf 6.2 can i still using it???
deprecated mean that i cant use it any more or it doesnt upgrade any more???
 ....thank you very much
