### ISSUE TITLE
schedule: Unable to render calendar using Primefaces 5.3.19 and dialog box is not rendered

### ISSUE THREAD

**Issue by shwetaprabhu** [primefaces/primefaces#3783] opened 2018-06-14 06:12 UTC
## 1) Environment
- PrimeFaces version:5.3.19
- Does it work on the newest released PrimeFaces 6.2? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Weblogic 10.3.6, Tomcat 7
- Affected browsers: All broswer

## 2) Expected behavior
Calendar should get rendered and dialog box should work oncomplete on dateSelect event

## 3) Actual behavior
Calender is not rendered

## 4) Steps to reproduce
[primefaces-test-master_schedule.zip](https://github.com/primefaces/primefaces/files/2101011/primefaces-test-master_schedule.zip)

..

**Comment by melloware** [comment] 2018-06-14 12:14
@OBreidenbach can you try this runnable sample and verify since you are the most familiar recently with the Schedule component?

**Comment by OBreidenbach** [comment] 2018-06-14 15:02
Sure I can. 
You call this a runnable sample???
File Name 'TestView', class name in File 'ScheduleView'. Did you look at the javascript console in the browser? Wondering about all the exceptions?
You have to use the &lt;h:head&gt; tag, not the &lt;head&gt; tag in your test.xhtml.
By the way, that has nothing to do with the Schedule component at all.
As a I am have no access to the elite versions I tried with 6.2.

**Comment by melloware** [comment] 2018-06-14 15:36
HA!  I assumed since gthey attached a ZIP it was a runnable sample.  if its garbage this ticket should be closed as invalid.

**Comment by OBreidenbach** [comment] 2018-06-15 07:07
Sorry @melloware, I did not mean you.

**Comment by tandraschko** [comment] 2018-06-15 09:07
@shwetaprabhu 
Please stop wasting our time and use the forum for equestsion. All your tickets are not reproducable and you didn't even provide correct examples.
If you have generell problems, just use the forum.

You even provideded a sample project without testing it, thats a no-go.

**Closed as completed by tandraschko** 2018-06-15 09:07 UTC
Labels: Resolution: Invalid
