### ISSUE TITLE
DataTable: bad keyboard support for scrollable dataTable with column filter

### ISSUE THREAD

**Issue by movalz** [primefaces/primefaces#3649] opened 2018-05-08 09:20 UTC
In case of a scrollable dataTable with sortable columns and without frozen column(s) and with a filter for at least one column TAB key jumps over the filter icon (when focus was inside the TH with the filter) instead of setting focus to "ui-selectcheckboxmenu-trigger" (more concrete: to the input with id "..._focus" inside that DIV).

If dataTable is pageable or has frozen column(s) it's working as expected. Reason is that in that cases TAB key steps through the original TH elements, in case of scrollable + non-frozen + non-pageable it steps through the cloned TH elements. And DataTable.cloneHead() contains following code:
```
        this.theadClone.find('th').each(function() {
            var header = $(this);
            header.attr('id', header.attr('id') + '_clone');
            $(this).children().not('.ui-column-title').remove();
        });
```
This removes the ui-selectcheckboxmenu-trigger element from the cloned TH.

Furthermore: if focus is inside the last element _before_ the dataTable pressing TAB key jumps to the "ui-selectcheckboxmenu-trigger" of the header with the filter and then to the first sortable column header.

## 1) Environment
- PrimeFaces version: 6.2.2
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: Tomcat 8 (arbitrary)
- Affected browsers: Firefox/Chrome/IE (arbitrary)

## 2) Expected behavior
pressing TAB key when focus is inside a TH element with a custom filter the focus is moved to the "ui-column-customfilter" element.

## 3) Actual behavior
pressing TAB key when focus is inside a TH element with a custom filter jumps to the next sortable TH element.

## 4) Steps to reproduce
see text above

## 5) Sample XHTML
```
<p:dataTable scrollable="true" scrollHeight="100%" var="tableRow" ...>
   <p:column id="col1" sortable="true" filterBy="#{bean.filterByCol1}" ...>
       <f:facet name="filter">
         <p:selectCheckboxMenu value="#{bean.filterValuesCol1}" ...>
           <f:selectItems value="#{bean.filterItemsCol1}" />
         </p:selectCheckboxMenu>
          <h:outputText value="#{tableRow.cellContentsByColumnId['col1']}" />
       </f:facet>
   </p:column>
   <p:column id="col2" sortable="true">
          <h:outputText value="#{tableRow.cellContentsByColumnId['col2']}" />
   </p:column>
</p:dataTable>
```

## 6) Sample bean
..

**Comment by melloware** [comment] 2020-11-25 14:29
I fix this in my apps by running this JS on pages with scrollable tables.
```javascript
/**
 * When using scrollWidth="100%" on a PF datatable it makes all filters tabindex="-1" so they are not tabbable.
 * This is done for ARIA/ScreenReader requirements when a blind user is tabbing that it will tab the columns to
 * the right that are scrolled off the screen. PF creates two cloned headers when scrollWidth="100%", but this fix
 * finds all of the filters and sets their tabindex=2001, 2002 etc.
 *
 * Issue: https://github.com/primefaces/primefaces/issues/3381
 */
fixScrollableFilters: function() {
    $(':input[tabindex=-1]').each(function(i) {
        $(this).attr('tabindex', 2000 + i);
    });
}
```

This is a duplicate of https://github.com/primefaces/primefaces/issues/3381

**Closed as completed by melloware** 2020-11-25 14:29 UTC
Labels: Resolution: Duplicate, workaround
