### ISSUE TITLE
Add style class ui-helper-clearfix to paginator div

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#865] opened 2015-11-08 15:52 UTC
Using custom content i added a component using `float: right;` to the paginator. 
This is displayed correct inside the paginator if the table is wide enough.

In a small dialog my custom content was outside of the paginator which you can see in below image:

http://fs5.directupload.net/images/151108/nivaarbp.jpg

The right version is with `ui-helper-clearfix` applied.

**Comment by tandraschko** [comment] 2017-02-17 15:34
The link doesn't work anymore.
A example and a PR would be nice;)

**Comment by tandraschko** [comment] 2017-07-11 07:56
Will close it for now. If the issue is still important for you, please create a new one with example and maybe screenshot.

**Closed as completed by tandraschko** 2017-07-11 07:56 UTC
Labels: enhancement
