### ISSUE TITLE
defaultCommand and autofill/autocomplete not working together

### ISSUE THREAD

**Issue by laurinmueller** [primefaces/primefaces#1941] opened 2016-12-01 16:25 UTC
## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? No
- Application server + version: Websphere 8.5.5.8
- Affected browsers: Chrome Version 54.0.2840.99 m/ Safari IOS 9

## 2) Expected behavior
When i have a simple Form, with autofill enabled on some fields and i have a defaultCommand that targets a p:commandButton  that triggers an action, I would suggest that when I start Typing my name in the field name, the chrome autofill features steps in and shows me a suggestion of the autofill values i could select from. When i select one autofill profile it should fill in all the available fields. then i should be able to fill in the other fields(that are not completed from autofill values) and then press enter to submit the form.

## 3) Actual behavior
When i have a simple Form, with autofill enabled on some fields and i have a defaultCommand that targets a p:commandButton  that triggers an action, the attempt to use Autofill of Chrome and Safari results in a direct submit of the form. But i would expect to have the oportunity to fill in the fields that are not filled by autofill. So I wouldnt expect the autofill feature to trigger the submit.

## 4) Steps to reproduce
Just make an autofill profile in chrome and try to fill a primefaces form with a p:defaultCommand added that targets a p:commandButton

## 5) Sample XHTML
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
  <h:head>
        <title>DefaultCommand and Autofill/Autocomplete</title>
    </h:head>
<h:body>
	<h:panelGroup>
		<h:messages id="messages" showDetail="true" showSummary="true"></h:messages>
		<h:form id="regForm">
			<p:panelGrid columns="2" layout="grid"
				columnClasses="firstColumn,secondColumn">

				<p:column>
					<p:outputLabel for="given-name" value="firstname: " />
				</p:column>

				<p:column>
					<p:inputText id="given-name"
						value="#{simpleBean.firstName}" required="true"
						placeholder="min. 3 Zeichen" autocomplete="given-name">
						<f:validateLength minimum="3" />
					</p:inputText>
				</p:column>

				<p:column>
					<p:outputLabel for="family-name"
						value="Family-Name: " />
				</p:column>

				<p:column>
					<p:inputText id="family-name"
						value="#{simpleBean.name}" required="true"
						placeholder="min. 3 Zeichen" autocomplete="family-name">
						<f:validateLength minimum="3" />
					</p:inputText>
				</p:column>


				<p:column>
					<p:outputLabel for="emailadresse" value="EMail " />
				</p:column>
				<p:column>
					<p:inputText id="emailadresse"
						value="#{simpleBean.email}" type="email" required="true"
						autocomplete="email" />
				</p:column>
				
				<p:column>
					<p:outputLabel for="password" value="Password " />
				</p:column>
				<p:column>
					<p:password id="password"
						value="#{simpleBean.password}" type="email" required="true"/>
				</p:column>
			</p:panelGrid>

			<p:panelGrid columns="2" layout="grid">
					<p:column>
					<p:commandButton value="Reset" update="regForm messages"
						process="@this" action="#{simpleBean.blankFields()}">
						<p:resetInput target="regForm" />
					</p:commandButton>
					</p:column>
					<p:column>
					<p:commandButton value="Save" update="regForm messages" id="regBtn"
						action="#{simpleBean.save()}"/>
					</p:column>
			</p:panelGrid>
			<p:defaultCommand target="regBtn" />
		</h:form>

	</h:panelGroup>
</h:body>
</html>

```

## 6) Sample bean

```
package ch.stzh.egov.regwww.web.view;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

@ManagedBean
@ViewScoped
public class SimpleBean {

    private String firstName;

    private String name;

    private String email;

    private String password;

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void blankFields() {
        firstName = null;
        name = null;
        email = null;
        password = null;
    }

    public void save() {
        StringBuilder sb=new StringBuilder();
        sb.append("FirstName: ").append(firstName);
        sb.append(" Name: ").append(name);
        sb.append(" EMail: ").append(email);
        sb.append(" Password: ").append(password);

        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Save", sb.toString()));
    }

}
```

## 7) My Awful Workaround ;)
I cant use the p:defaultCommand, so i use a snippet of javascript like this:
```
$(function(){
  $('#regForm').on('keypress', function(event){
    if(event.which === 13 && $(event.target).is('input')){
        event.preventDefault();
        $('#regForm\\:regBtn').trigger('click');
    }
  });
});
```

**Comment by mjiderhamn** [comment] 2017-06-16 15:24
Quite likely this is a duplicate of #2448. @laurinmueller, would you mind trying the workaround I provided there?

**Comment by laurinmueller** [comment] 2017-06-19 13:57
@mjiderhamn You are absolutly right. I tried your workaround and it worked, so this is a duplicate of #2448

**Comment by melloware** [comment] 2019-04-05 11:17
@tandraschko This is a duplicate of #2448 and #4672 so it can be closed.

**Closed as completed** 2019-04-05 11:33 UTC
