### ISSUE TITLE
Relative to issue #214 : javascript error when tabView has no tabs

### ISSUE THREAD

**Issue by sylvainroussy** [primefaces/primefaces#637] opened 2015-08-18 15:21 UTC
I have a javascript error when TabView has no tabs (when starting page in my case) :  
_Uncaught TypeError: Cannot read property 'left' of undefined_

I Suggest a test on the position () function:

``` javascript

initScrolling: function() {
  if (this.lastTab.position()) {
            var overflown = ((this.lastTab.position().left + this.lastTab.width()) - this.firstTab.position().left) > this.navscroller.innerWidth();
            if(overflown) {
                this.navscroller.css('padding-left', '18px');
                this.navcrollerLeft.show();
                this.navcrollerRight.show();
                this.restoreScrollState();
            }
  }
},

```

**Comment by tandraschko** [comment] 2015-08-19 11:02
Why do you render a tabview without tabs? I looks weird... I would not render the tabView.

**Comment by sylvainroussy** [comment] 2015-08-19 11:07
You're right, it's a possibility but I wanna avoid render evaluations and to have the empty tabView style (instead blank space)

**Comment by cagataycivici** [comment] 2015-08-28 07:35
Duplicate of #291, please do a search before creating new issues.

**Closed as completed by cagataycivici** 2015-08-28 07:35 UTC
Labels: Resolution: Duplicate

**Comment by sylvainroussy** [comment] 2015-08-28 07:48
Thanks  and sorry for duplicate.
