### ISSUE TITLE
SelectManyMenu: no AJAX behavior events available

### ISSUE THREAD

**Issue by JoHoop** [primefaces/primefaces#6965] opened 2021-02-09 13:54 UTC
There are no AJAX behavior events available for the SelectManyMenu component.
It would be great to have events similar to the SelectOneMenu component (`change`, `itemSelect`, `click`).

**Comment by tandraschko** [comment] 2021-02-09 13:55
Duplicate of: https://github.com/primefaces/primefaces/issues/2330

**Closed as completed by tandraschko** 2021-02-09 13:55 UTC
Labels: new feature
