### ISSUE TITLE
p:commandButtons and p:commandLinks do not fire events on root note in a p:tree with horizontal orientation

### ISSUE THREAD

**Issue by boanergesza1** [primefaces/primefaces#1795] opened 2016-09-27 16:03 UTC
## 1) Environment
- PrimeFaces version: 5.3
- Does it work on the newest PrimeFaces version? No
- Application server + version: Wildfly vs 8.2
- Affected browsers: Chrome, IE
## 2) Expected behavior

Events should be processed from the root node.
## 3) Actual behavior

No events are processed from the root node
## 4) Steps to reproduce

(see sample code below) Create xhtml with a tree with horisontal layout and a backing bean to support data in the tree node.
In the tree, on the treenode, add a commandbutton with an actionlistener or action, that calls a method on the backing bean. 
When deployed and running, clicking on the commandbutton on the root wil not fire the action listener, but clicking on the subnodes commandbuttons do.
## 5) Sample XHTML

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:p="http://primefaces.org/ui"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough" xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
</h:head>
    <h:body>
        <h:form>
        <p:tree value="#{testTreeNode.root}" var="node"  style="width: auto; height: auto;" orientation="horizontal" >
            <p:treeNode>
                <h:outputText value="#{node}"/>
                <p:commandButton id="aksie" icon="ui-icon-plus" action="#{testTreeNode.aksieAksie}" />
            </p:treeNode>
        </p:tree>
        </h:form>
    </h:body>
</html>`
## 6) Sample bean

`import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.enterprise.context.SessionScoped;
import javax.faces.bean.ManagedBean;
import javax.inject.Named;
import java.io.Serializable;

/**
- Created by F2861852 on 9/27/2016.
  */
  @Named("testTreeNode")
  @SessionScoped
  @ManagedBean
  public class TestTreeNode implements Serializable{
  private Logger logger = LoggerFactory.getLogger(TestTreeNode.class);
  
  private TreeNode root;
  
  public TestTreeNode() {
      root = new DefaultTreeNode("Root", null);
      root.setExpanded(true);
      TreeNode node0 = new DefaultTreeNode("Node 0", root);
      TreeNode node1 = new DefaultTreeNode("Node 1", root);
      TreeNode node2 = new DefaultTreeNode("Node 2", root);
      TreeNode node00 = new DefaultTreeNode("Node 0.0", node0);
      TreeNode node01 = new DefaultTreeNode("Node 0.1", node0);
      TreeNode node10 = new DefaultTreeNode("Node 1.0", node1);
      TreeNode node11 = new DefaultTreeNode("Node 1.1", node1);
      TreeNode node000 = new DefaultTreeNode("Node 0.0.0", node00);
      TreeNode node001 = new DefaultTreeNode("Node 0.0.1", node00);
      TreeNode node010 = new DefaultTreeNode("Node 0.1.0", node01);
      TreeNode node100 = new DefaultTreeNode("Node 1.0.0", node10);
  }
  
  public TreeNode getRoot() {
      return root;
  }
  
  public void setRoot(TreeNode root) {
      this.root = root;
  }
  
  public void aksieAksie(){
      logger.info("aksieAksie called");
  }
  }
  `

**Comment by tandraschko** [comment] 2019-01-04 16:35
XHTML missing, i will close it as invalid for now.
If you the issue is still present, please create a new issue with all required informations.

**Closed as completed by tandraschko** 2019-01-04 16:35 UTC
Labels: Resolution: Invalid
