### ISSUE TITLE
IntegrationTests: failed on Java17 today

### ISSUE THREAD

**Issue by tandraschko** [primefaces/primefaces#7880] opened 2021-09-28 08:50 UTC

**Comment by christophs78** [comment] 2021-09-28 09:51
We propably need to add `-Dmaven.javadoc.skip=true -Djsdoc.skip.typedoc=true` to https://github.com/primefaces/primefaces/blob/master/.github/workflows/nightly.yml#L35.
(I can provide a PR in the evening.)

**Comment by christophs78** [comment] 2021-09-28 10:03
Root cause seem to be
```
Error:  Constructing Javadoc information...
Error:  /home/runner/work/primefaces/primefaces/primefaces/src/main/java/org/primefaces/util/MessageFactory.java:33: warning: [removal] AccessController in java.security has been deprecated and marked for removal
Error:  import java.security.AccessController;
```

**Comment by christophs78** [comment] 2021-09-28 19:02
fixed with https://github.com/primefaces/primefaces/commit/0843f5efcab6fe874579d9725944cea6d03b7630

**Closed as completed** 2021-09-28 19:03 UTC
Labels: :lady_beetle: defect, integration_test
