### ISSUE TITLE
DataTable - p:headerRow duplicates first row

### ISSUE THREAD

**Issue by andyfinch** [primefaces/primefaces#2004] opened 2017-01-09 14:57 UTC
## 1) Environment
- PrimeFaces version: 6.0.13
- Does it work on the newest PrimeFaces version? No
- Application server + version: Weblogic 12.2.1.2 JSF 2.2.8-17
- Affected browsers: All

## 2) Expected behavior
p:headerRow should add a header for a group of rows

## 3) Actual behavior
The first normal data row is duplicated and appears twice in each group

## 4) Steps to reproduce
As per showcase.  Showcase has duplicated data.

## 5) Sample XHTML
```
<p:dataTable var="car" value="#{dtRowGroupView.cars}" sortBy="#{car.brand}" expandableRowGroups="true">
        <p:headerRow>
            <p:column colspan="3">
                <h:outputText value="#{car.brand}" />
            </p:column>
        </p:headerRow>
        <p:column headerText="Year">
            <h:outputText value="#{car.year}" />
        </p:column>
        <p:column headerText="Color">
            <h:outputText value="#{car.color}" />
        </p:column>
        <p:column headerText="Id">
            <h:outputText value="#{car.id}" />
        </p:column>
        <p:summaryRow>
            <p:column colspan="2" style="text-align:right">
                <h:outputText value="Total:" />
            </p:column>
            <p:column>
                <h:outputText value="#{dtRowGroupView.randomPrice}">
                    <f:convertNumber type="currency" currencySymbol="$" />
                </h:outputText>
            </p:column>
        </p:summaryRow>
    </p:dataTable>
```

## 6) Sample bean
See showcase

**Comment by pistamarti** [comment] 2017-01-18 06:58
Remark to 3)
Furthermore, the last normal data row in each group  is omitted.

**Comment by regenduft** [comment] 2017-01-23 16:12
just noticed that my issue is a duplicate of this one: https://github.com/primefaces/primefaces/issues/2032

**Closed as completed** 2017-01-24 09:29 UTC
Labels: Resolution: Duplicate
