### ISSUE TITLE
Autocomplete : Bug on field clearing when using converter and forceSelection=false

### ISSUE THREAD

**Issue by omasseau** [primefaces/primefaces#201] opened 2015-04-29 13:56 UTC
After clearing the value by using IE's clear field X button,  or by using Chromes' Delete entry of the context menu, the previous value is still submitted.
This only happens for autocomplete fields that use a converter and that have forceSelection=false.

This code, based on autoComplete.xhtml from the showcase, reproduces the problem:

```
<h:form>
  <h:panelGrid columns="2" cellpadding="5">

    <p:outputLabel value="Pojo:" for="themePojo" />
    <p:autoComplete id="themePojo" value="#{autoCompleteView.theme1}" completeMethod="#{autoCompleteView.completeTheme}"
                        var="theme" itemLabel="#{theme.displayName}" itemValue="#{theme}" converter="themeConverter" forceSelection="false"/> 

  </h:panelGrid>

  <p:commandButton value="Submit" icon="ui-icon-check" update="output" oncomplete="PF('dlg').show()" />

  <p:dialog header="Values" resizable="false" showEffect="fade" widgetVar="dlg">
    <p:panelGrid id="output" columns="2" columnClasses="label, value">

      <h:outputText value="Pojo:" />
      <h:outputText value="#{autoCompleteView.theme1}" />

    </p:panelGrid>
  </p:dialog>
</h:form>
```

Primefaces version : 5.2

**Comment by tandraschko** [comment] 2017-06-29 15:08
Does it still occur? @melloware Would you like to check that? AFAIR you did some PRs for autocomplete :D

**Comment by melloware** [comment] 2018-11-25 16:30
@tandraschko Tested on IE11 using the latest showcase and I can't reproduce.  Safe to close this issue.

**Closed as not planned** 2018-11-25 16:32 UTC
Labels: :lady_beetle: defect

**Comment by jepsar** [comment] 2024-04-17 12:38
@danbalves using IE? That's no longer supported.
