### ISSUE TITLE
InputNumber: minValue cant override value

### ISSUE THREAD

**Issue by StevenHachel** [primefaces/primefaces#9207] opened 2022-09-15 09:46 UTC
### Describe the bug

The value cannot be changed without going through a detour. To change the number, the content must be marked in order to overwrite it. This is very unfavorable if you have to change a whole lot of such values (table in goods distribution with 20 items and their quantity).

can only changed, when marked:
![grafik](https://user-images.githubusercontent.com/29144366/190372720-4e0b865b-d116-4686-9408-6b5a6f75bb30.png)

[pf-0001-input_number.zip](https://github.com/primefaces/primefaces/files/9574011/pf-0001-input_number.zip)

### PrimeFaces edition

Community

### PrimeFaces version

11

### JSF implementation

Mojarra

### JSF version

2.2.x/2.3.x

### Java version

8/11

### Browser(s)

FF, Chrome

**Comment by tandraschko** [comment] 2022-09-15 09:59
I think its a duplicate of: https://github.com/primefaces/primefaces/issues/5376

**Comment by StevenHachel** [comment] 2022-09-15 10:18
It works in PF version 8. I can replace the number without having to mark it first.

**Comment by melloware** [comment] 2022-09-15 11:19
Debugging the issue and PR is welcome here.  AutoNumeric was upgraded between 8 and 12.

Here is a great filter of everything that has changed in InputNumber from 12 back to 8.  https://github.com/primefaces/primefaces/issues?q=is%3Aissue+inputnumber+in%3Atitle+is%3Aclosed+sort%3Aupdated-desc+

**Comment by melloware** [comment] 2022-09-15 13:26
I am running with `12.0.0-RC3` and your demo is working fine.
[pf-9702.zip](https://github.com/primefaces/primefaces/files/9575604/pf-9702.zip)

I will re-open if you discover its not working fine for some reason on 12.0.0-RC3.

**Closed as completed by melloware** 2022-09-15 13:26 UTC
Labels: Resolution: Invalid
