### ISSUE TITLE
Block multiple components with BlockUI

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#50] opened 2015-04-18 12:32 UTC
t would be helpful if we had possibility to to add more than one area to be blocked on particular ajax action

``` xml
<p:blockUI block="area1, area2" target"someTarget"/>
```

**Comment by sudheerj** [comment] 2016-01-06 03:27
Duplicate of issue https://github.com/primefaces/primefaces/issues/717

**Comment by sudheerj** [comment] 2016-03-18 18:31
Already fixed for 5.3.1,5.2.13 and 6.0 releases.Now we can use PFS or comma separated mutiple component ids.

**Closed as completed by sudheerj** 2016-03-18 18:31 UTC
Labels: new feature
