### ISSUE TITLE
Support mixed static & dynamic tabs

### ISSUE THREAD

**Issue by JohnSchneider** [primefaces/primefaces#671] opened 2015-08-31 14:49 UTC
It'd be great if a new attribute in the tab component allowed specification of a tab as either dynamic or static.  The use case is a tabView or accordionPanel with several tabs which can be static, and one or more which must be dynamic and not cacheable.  For performance reasons, it would be great to avoid server communication on all the static tabs and only invoke an AJAX request on the dynamic tab(s).

**Comment by cagataycivici** [comment] 2015-09-22 08:26
Duplicate of #32

**Closed as completed by cagataycivici** 2015-09-22 08:26 UTC
