### ISSUE TITLE
Charts - Javascript escape quote in title, legend, serie labels

### ISSUE THREAD

**Issue by ulspider** [primefaces/primefaces#709] opened 2015-09-19 16:10 UTC
There is an issue with caracters like " or ' when they are in chart's title, legend, serie's label...

``` javascript
{PrimeFaces.cw('Chart','widget_form_chartSuiviNombreAnnoncesDialogStatistiquesRecherche',{id:'form:chartSuiviNombreAnnoncesDialogStatistiquesRecherche',type:'line',data:[[["Avril 2015",37],["Mai 2015",95],["Juin 2015",162],["Juillet 2015",152],["Août 2015",143]]],title:"Evolution du nombre d'annonces",legendPosition:"e",axes:{yaxis: {label:"Nombre d'annonces",min:0,max:200,renderer:$.jqplot.LinearAxisRenderer,tickOptions:{angle:"0"}},xaxis: {label:"Mois",renderer:$.jqplot.CategoryAxisRenderer,tickOptions:{angle:"0"}}},series:[{label:'Nombre d'annonces',renderer: $.jqplot.LineRenderer,showLine:true,markerOptions:{show:true, style:'filledCircle'}}],animate:true,showPointLabels:true,datatip:true},'charts');});
```

You can see an issue here : 
**series:[{label:'Nombre d'annonces',**

The caracter **'** isn't escaped. I think the issue is global for all string value defined using ChartModel.

**Comment by cagataycivici** [comment] 2015-09-21 11:26
What is your PF version?

**Comment by ulspider** [comment] 2015-09-26 06:43
Primefaces 5.2.

**Comment by melloware** [comment] 2017-04-06 11:59
Duplicate of #1760

**Closed as completed** 2017-04-06 12:52 UTC
Labels: :lady_beetle: defect
