### ISSUE TITLE
LazyDataModel Iterator causes endless loop

### ISSUE THREAD

**Issue by gako** [primefaces/primefaces#713] opened 2015-09-22 09:10 UTC
If you use the LazyDataModel.iterator() to iterate over the data you will get an endless loop because DataModelIterator.hasNext() always returns true:

DataModelIterator.hasNext() internally calls (Lazy))DataModel.isRowAvailable() which in turn checks for the boundaries of rowIndex (rowIndex >= 0 && rowIndex < data.size())

BUT the setRowIndex() method of LazyDataModel checks that the rowIndex is always within the bounds of data.

if(rowIndex == -1 || pageSize == 0)
    this.rowIndex = -1;
else
    this.rowIndex = (rowIndex % pageSize);

Due to this rowIndex can never be outside of bounds which is necessary for isRowAvailable to return false.

Workaround: For now I use a for loop and manually call setRowIndex, getRowData to retrieve the data.

---

Primefaces Version 5.2.11

**Comment by tandraschko** [comment] 2017-01-24 13:27
Feel free to provide a PR.

**Comment by tiagojn** [comment] 2018-02-15 13:10
Confirmed on Version 6.1

**Comment by fkjaekel** [comment] 2018-02-15 13:14
Since this issue was leading my server to out of memory errors, I disabled the iterator method:

```
@Override
public Iterator<T> iterator()
{
	throw new UnsupportedOperationException("nope");
}
```

**Comment by tandraschko** [comment] 2018-02-23 09:46
For me it's quite hard to replicate it without examples and will therefore close it.
Please reopen and provide all required informations requested by our issue template.

@fkjaekel If you faced this bug, could you please check it in detail and provide a PR to fix it?

**Closed as completed by tandraschko** 2018-02-23 09:46 UTC
Labels: :lady_beetle: defect, Resolution: Invalid

**Comment by renanbaggio** [comment] 2018-03-12 08:28
I'm using PrimeFaces 5.1 and I'm facing the same problem..

**Comment by tandraschko** [comment] 2018-03-12 08:29
It's fixed by: https://github.com/primefaces/primefaces/issues/3364

**Comment by renanbaggio** [comment] 2018-03-12 08:33
Thanks!
