### ISSUE TITLE
Proposal: Support for jQuery 3

### ISSUE THREAD

**Issue by darckyn** [primefaces/primefaces#2467] opened 2017-06-22 15:44 UTC
Hi.

I just tried to use jQuery 3 in my project and PrimeFaces is not compatible.

I removed jQuery 2 and applied the 3, which resulted in several errors like: not finding functions like unload. 
Which made the PrimeFaces break at various times and forced me to go back to version 2.

Please could you consider making PrimeFaces with jQuery 3 support?

I am using the PrimeFaces 6.1

jQuery Migrate could help to find a possible issues: 
[https://blog.jquery.com/2016/05/19/jquery-migrate-1-4-1-released-and-the-path-to-jquery-3-0/](url)

Thanks.

**Comment by tandraschko** [comment] 2017-06-22 18:03
We decided some months ago to update to jquery 2 instead of upgrading to jquery 3 as it requires more changes (and probably migrate plugins). And we also depend on some third party plugins.

I'm sure we will consider this in the future but likely not this year.
Will close it for now.

**Closed as completed by tandraschko** 2017-06-22 18:03 UTC

**Comment by mertsincan** [comment] 2017-12-11 11:50
Duplicate of #3062
