### ISSUE TITLE
Datatable: Use caption HTML tag

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2845] opened 2017-10-20 09:41 UTC
Facet `Header` is generated using a div tag while caption HTML tag exists https://www.w3schools.com/tags/tag_caption.asp That part is quite easy to rewrite, but when it comes with a paginator it's a bit more tricky since paginator is not part of the `table` itself. Is paginator should be encoded in caption tag?

Doing this makes datatable even more compliant to HTML spec and would probably help to achieve #2723

**Comment by jxmai** [comment] 2017-10-21 02:16
Is it technical possible ? If you read the spec of caption:

![image](https://user-images.githubusercontent.com/10467831/31847039-40ae84b8-b5da-11e7-8038-01805169b28c.png)

---

Primefaces table is not a standard html table.  The facet header is just a div on top of a real html table.

![image](https://user-images.githubusercontent.com/10467831/31847071-e3f56d6c-b5da-11e7-9c15-2a2261a55fb8.png)

---

Even if we can manage to insert the facet header caption immediately after a table, we still cannot add another one for footer since only one caption is allowed for a table.

**Comment by Rapster** [comment] 2017-10-21 11:45
That's the point, make databable as much standard as possible. Regarding the header, it's definitely technically possible, I already had a try.

As I said, it gets more complicated when it comes to add the paginator since we add it after the header. It means we should add paginator in caption, i didn't try that part yet. I don't understand your point regarding the footer, it is actually fine as it is

**Comment by jxmai** [comment] 2017-10-22 14:52
> I don't understand your point regarding the footer, it is actually fine as it is

Nevermind.  `encodeFacet(context, table, table.getFooter(), DataTable.FOOTER_CLASS);` gave me an impression that you were also  trying to encode facet footer in a caption.

> That's the point, make databable as much standard as possible. Regarding the header, it's definitely technically possible, I already had a try.

OK, I see. It may require some refactoring work but possible. I guess you may need to search `writer.startElement("table", null);` and insert an encoding helper method for everyone :)

Just as a quick demontration:

![image](https://user-images.githubusercontent.com/10467831/31863125-a624fe00-b70e-11e7-80bb-556c95e33995.png)

---

I just do a quick evaluation, so I will leave the rest decision up to you :)  thumb up this ticket 👍

**Comment by jxmai** [comment] 2017-10-22 15:59
Submitted a PR for review anyway

**Comment by jxmai** [comment] 2017-10-22 17:49
I should have mentioned that the PR is only for header since it should have done right in the first place.

---

> a paginator it's a bit more tricky since paginator is not part of the table itself. Is paginator should be encoded in caption tag?

As for paginator, not only it is not part of the table from the implementation perspective, but I haven't yet to see wrapping pagination in caption in pure html 🤔 . Normally the pagination is only located in the bottom part instead of locating in both bottom and top as Primefaces. For example, boostrap (https://datatables.net/examples/styling/bootstrap.html) 

![image](https://user-images.githubusercontent.com/10467831/31864678-4b5afd58-b727-11e7-9731-7bf0f6ee64c3.png)

Maybe you have a different idea but that part might desire a whole topic of discussion, but IMHO, I don't think putting pagination in caption is correct.

**The sole purpose of caption is to set an element to represent the title of a datatable (https://www.w3.org/TR/html5/tabular-data.html#the-caption-element)**

> The caption element represents the title of the table that is its parent, if it has a parent and that is a table element.

**Comment by Rapster** [comment] 2017-10-22 18:52
As I said in the PR, caption can't be set up without having any thoughts about pagination... I know it's not an easy job...

**Comment by jxmai** [comment] 2017-10-22 20:03
> As I said in the PR, caption can't be set up without having any thoughts about pagination... I know it's not an easy job...

Indeed. Wrapping facet header in caption is simple. But for wrapping pagination in caption...  Well, the implementation part is one thing, and the miserable spec is the other problem.

**Comment by jxmai** [comment] 2017-11-14 00:12
Actually this ticket is duplicate of #2048 that was reported quite a while ago.

**Closed as completed** 2017-11-14 08:24 UTC
Labels: Resolution: Duplicate, enhancement
