### ISSUE TITLE
SelectOneMenu: ItemLabel "" causes min heigth 

### ISSUE THREAD

**Issue by cadubad** [primefaces/primefaces#7076] opened 2021-03-05 14:18 UTC
**Describe the defect**
When I put itemLabel empty, it causes the height of the component to be too small

**Environment:**
PF Version: 10.0.0-RC2
JSF + version: jsf-impl-2.3.9.SP04
Affected browsers: Chrome

**To Reproduce**

1 - insert an empty itemLabel on any p:selectOneMenu
2 - When executed, even with other items in the list, the height is almost zero

```
<p:selectOneMenu value="#{usuarioBean.usuario.pais}" 
converter="paisConverter">
   <f:selectItem itemLabel="" />
   <f:selectItems value="#{utilBean.listarPaises()}" />
   <p:ajax event="change" update="@form" ></p:ajax>
</p:selectOneMenu>
```

**Expected behavior**
The height was expected to be the same for all items.

**Possible solution/workaround**
change empty value to any value
```    <f:selectItem itemLabel="..." /> ```

**Comment by melloware** [comment] 2021-03-05 14:22
Duplicate of https://github.com/primefaces/primefaces/issues/7044 fixed for 10.0.0 Final.

**Closed as completed by melloware** 2021-03-05 14:22 UTC
Labels: Resolution: Duplicate

**Comment by cadubad** [comment] 2021-03-05 14:26
Thanks!
