### ISSUE TITLE
SelectOneMenu displays an &nbsp; Text string when the selectItem itemLabel is set to empty string.

### ISSUE THREAD

**Issue by UserPSPretoria** [primefaces/primefaces#3336] opened 2018-02-14 14:15 UTC
## 1) Environment

- PrimeFaces version: 6.2.RC2
Application server + version: Payara 4.1.173
Affected browsers: Google Chrome

## 2) Expected behavior

Dropdown with the first item as an empty string.

## 3) Actual behavior

![image](https://user-images.githubusercontent.com/31402902/36208399-9c7e8c3e-11a1-11e8-98fd-990e19ab567d.png)

## 4) Steps to reproduce

Please use the code below 

## 5) Sample XHTML

                                <p:selectOneMenu id="console" value="#{selectOneMenuView.console}" style="width:125px">
                                    <f:selectItem itemLabel="" itemValue="111" />
                                    <f:selectItem itemLabel="Xbox One" itemValue="Xbox One" />
                                    <f:selectItem itemLabel="PS4" itemValue="PS4" />
                                    <f:selectItem itemLabel="Wii U" itemValue="Wii U" />
                                </p:selectOneMenu>

**Comment by tandraschko** [comment] 2018-02-14 14:28
Duplicate of: https://github.com/primefaces/primefaces/issues/3326
Please try a source build.

**Closed as completed by tandraschko** 2018-02-14 14:28 UTC
Labels: Resolution: Duplicate
