### ISSUE TITLE
DataTable: Paginator RowsPerPageDropdown not working (Java 8, Apache MyFaces JSF2.2, Primefaces 13.0.10), WAS 8.5

### ISSUE THREAD

**Issue by goldyrishi** [primefaces/primefaces#12396] opened 2024-08-03 12:02 UTC
### Describe the bug

I am using "Java 8, Apache MyFaces JSF2.2, Primefaces 13.0.10", using WAS 8.5 Server.

When I am changing rowsPerPageDropdown and expecting updated values in both top and bottom rowsPerPageDropdown.
The paginator template is updated and data table is also updated with new data, but rowsPerPageDropdown which I am changing is not getting updated.
 
![image](https://github.com/user-attachments/assets/de6c2017-cea1-4bc4-980b-1f8ebddb62d8)

Now, Changing RowsPerPageDropdown value to 6:

![image](https://github.com/user-attachments/assets/a326e6a1-627a-45f9-b483-43e695f4ca43)

The bottom one dropdown of RowsPerPageDropdown is updated and dataTable is also updated, but Top RowsPerPageDropdown dropdown remains same.

Similarly, when I am changing bottom dropdown then top one will not updated/change.

### PrimeFaces edition

None

### PrimeFaces version

13.0.10

### JSF implementation

MyFaces

### JSF version

2.2

### Java version

8

### Browser(s)

Edge, Chrome, FireFox

**Comment by tandraschko** [comment] 2024-08-03 12:05
The community does not support 13.x anymore.
Also see: https://github.com/primefaces/primefaces?tab=readme-ov-file#community--lts--pro

either you can also reproduce in a primefaces-test project with 14.x, otherwise we just have to close it here.

**Comment by melloware** [comment] 2024-08-03 12:24
And we can't reproduce it in either PF showcase or QuarkusFaces showcase which run Mojarra 2.3 and MyFaces 4.0.2 respectively.

https://github.com/primefaces/primefaces/issues/12359

**Closed as not planned** 2024-08-12 10:43 UTC
Labels: Resolution: Cannot Replicate
