### ISSUE TITLE
DataTable: sorting regressions due to changes introduced today (Dec 27, 2020) or yesterday (Dec 26, 2020)

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#6727] opened 2020-12-27 18:08 UTC
Error:    DataTable003Test.testMultiSort2:99->AbstractDataTableTest.assertRows:21 expected: <2> but was: <5>
Error:    DataTable003Test.testMultiSort:68->AbstractDataTableTest.assertRows:21 expected: <4> but was: <2>
Error:    DataTable013Test.testSortByWithDefault:50->AbstractDataTableTest.assertRows:21 expected: <4> but was: <2>

https://github.com/primefaces-extensions/primefaces-integration-tests/runs/1614284410?check_suite_focus=true

@tandraschko

**Comment by melloware** [comment] 2020-12-28 12:50
@tandraschko I just kicked off the tests again and they are still failing even with your latest change?
```
 Failures: 
Error:    DataTable003Test.testMultiSort2:99->AbstractDataTableTest.assertRows:21 expected: <2> but was: <5>
Error:    DataTable003Test.testMultiSort:68->AbstractDataTableTest.assertRows:21 expected: <4> but was: <2>
Error:    DataTable013Test.testSortByWithDefault:50->AbstractDataTableTest.assertRows:21 expected: <4> but was: <2>
```

**Comment by tandraschko** [comment] 2020-12-28 13:02
for me it looked correct, i started the integration test suite with tomee-embedded:run and checked the code. Before my change the "sort priority" was not correct. Could you check it maybe? maybe the test is wrong? not sure

**Comment by melloware** [comment] 2020-12-28 13:32
OK I verified locally its not working and the Showcase Sort example is broken.
The showcase example sorts by Brand then Year but in the screenshot its sorted by Year then Brand.
```xml
 <p:column headerText="Year" field="year" sortOrder="desc" sortPriority="2"/>
<p:column headerText="Brand" field="brand" sortOrder="asc" sortPriority="1"/>
```

See:
![image](https://user-images.githubusercontent.com/4399574/103217606-fe3caf80-48e6-11eb-9888-6625a4792032.png)

**Comment by Rapster** [comment] 2020-12-28 13:42
Just giving my 2 cents, but `SortFeature#sort` sort "reversly" the list. Certainly a regression since 7dba5cb7fdf185ecdf2a03515103faa9f57ca585

**Comment by tandraschko** [comment] 2020-12-28 14:04
looks good now, can you rerun the tests @melloware ?

**Comment by melloware** [comment] 2020-12-28 14:06
Running now!
https://github.com/primefaces-extensions/primefaces-integration-tests/actions/runs/448803808

**Comment by melloware** [comment] 2020-12-28 14:19
All tests passing again. Thanks @tandraschko closing ticket.

**Closed as completed by melloware** 2020-12-28 14:19 UTC
Labels: :lady_beetle: defect
