### ISSUE TITLE
f:ajax throws JS error with PF components on Firefox

### ISSUE THREAD

**Issue by mattweaver-cv** [primefaces/primefaces#23] opened 2015-04-15 15:08 UTC
In PrimeFaces 5+, if I use an f:ajax tag as an event handler under a datable (or other components), I get a JavaScript error in Firefox, "event is undefined".  It works in other browsers.

I traced it through to CoreRenderer.java, in PF 4 it was wrapping ClientBehavior scripts in a block like this:

``` java
writer.write("function(event,ext){PrimeFaces.bc(this,event,ext,[");
```

In PF 5 it was changed to this:

``` java
writer.write("function(ext) {");
```

MyFaces seems to generate JS for f:ajax that looks like this:

``` javascript
jsf.ajax.request('id',event,...)
```

Since the wrapper function no longer has an event argument, it causes a JS error in Firefox (Chrome, IE, Opera and Safari have a global event object, so it works there).

I have a small project I made to demonstrate by modifying the Showcase example, I will try to attach.

**Comment by mattweaver-cv** [comment] 2015-04-15 15:11
I could not find a way to attach to GitHub issues, so I uploaded project to here: http://www.filedropper.com/dttest

If you try the top table everything should work as expected, on the bottom one it gives an error in Firefox but works in Chrome, etc (although selected object is null)

**Comment by tandraschko** [comment] 2015-04-16 08:11
The change is already very old and it was introduced cause mobile event rendering.
I'm not sure if anyone will fix this in the near future as it affects almost every component.
I would stay with p:ajax.

**Comment by cagataycivici** [comment] 2015-04-18 19:42
I'll think about this.

**Comment by frederikd** [comment] 2015-04-19 05:01
This is quite a severe issue for us. We cannot use p:ajax just for primefaces components (and f:ajax for the rest) because of the separate ajax queue handling to Mojarra's queue handling so we would get concurrent ajax requests.
And we can't change all our components to use p:ajax either because the behaviour of p:ajax is so different to f:ajax and the delayed parameter execution of p:ajax is causing massive issues for queued ajax requests for us (sending "wrong" values).
So a fix for this would really be great as otherwise we can't use Primefaces components or need to override the Javascript ourselves resulting in maintenance nightmares.

**Comment by cagataycivici** [comment] 2015-04-19 07:06
I see but custom events like tabChange, page, sort can only be used with p:ajax. Don't you use them?

**Comment by tandraschko** [comment] 2015-04-19 09:55
@cagataycivici we should this allign with the JSF api - this may also cause incompatibilities with other client behaviors.
Why can tabChange only be used with page, sort? because of the callpack params?

@frederikd could you please describe your problem in detail? we should fix such an problem if there is one with p:ajax.

**Comment by frederikd** [comment] 2015-04-19 10:18
@cagataycivici we do use those, but mostly on pages where we don't have a mix of p:ajax and f:ajax. Our problem is not really about data tables though. We have issues mostly with primefaces multiselects and datepickers on pages where we use lots of data fields with non-primefaces components.

@tandraschko our original issue was logged as https://code.google.com/p/primefaces/issues/detail?id=7669 but it seems to be the same as described here.
Or if you mean our issue with using p:ajax in general, then the issue is the following:
We have pages with lots of fields (p:calendar, p:selectOneMenu, pe:inputNumber, h:inputText etc.) which all trigger ajax requests on change and re-render the parent panel. If the user tabs through and makes lots of changes quickly so that the ajax requests don't respond before the next change is made then some of the user input is lost, because the previous ajax request finishes late, potentially updates the next field and then p:ajax only evaluates the form input value when the request is dequeued. f:ajax on the other hand evaluates the the form input at the time of the request being added to the queue, so whatever the user entered will be sent, not whatever the components value is at the time the request is processed. This difference prevents us from using p:ajax in most cases, and is why this issue is so important for us.
Ideally we would like to have p:ajax work like f:ajax, i.e. immediate evaluation rather than delayed evaluation, but if this is not going to be changed then at least f:ajax should work.

**Comment by tandraschko** [comment] 2015-04-19 10:25
a delayed evaluation sounds like an good improvement. We can pass the  cfg to our ajax queue and when the requests starts, we collect the parameters.
WDYT Cagatay?

Nevertheless, IMO f:ajax should work without problems, too!

**Comment by frederikd** [comment] 2015-04-19 10:29
@tandraschko the delayed execution is what p:ajax is currently doing already. We want immediate evaluation - which is what f:ajax is doing in Mojarra. :) But I guess ideally there should be a parameter/config (as you said).

**Comment by tandraschko** [comment] 2015-04-19 10:37
Ahh i see, i didn't touch the ajax on client side many months.

Hmmm, i understand the problem. Could you please check how myfaces works?

Is there probably any case where a delayed evaluation is better?

**Comment by frederikd** [comment] 2015-04-19 21:36
@tandraschko we haven't tested this in myfaces yet, but will do so and get back to you.
I rather logged a new issue now to keep track of this discussion. It seems like the delayed vs immediate evaluation on p:ajax is really a separate issue and I don't want to hijack this issue.

**Comment by cagataycivici** [comment] 2015-04-19 22:03
I plan to work on this in a couple of days.

**Comment by mikhailChibel** [comment] 2015-04-21 06:03
Following @frederikd and @tandraschko discussion, I've checked MyFaces behavior and can confirm that MyFaces does immediate evaluation of form parameters, thus it behaves the same as Mojarra.

**Comment by cagataycivici** [comment] 2015-04-21 07:45
Worked on this a bit and f:ajax actually works in most cases where it should be such as;

``` xml
<p:inputText>
   <f:ajax 
</p:inputText>
```

As output is 

```
onchange="mojarra.ab('j_idt87:name',event,'valueChange',0,0})"
```

Which is valid as browser passes the event to the mojarra call. Even twith chaning where you have f:ajax and p:ajax inside an input text, event is passed;

``` xml
<p:inputText>
   <f:ajax />
   <p:ajax />
</p:inputText>
```

``` javascript
PrimeFaces.bcn(this,event,[function(event){mojarra.ab('j_idt87:name',event,'valueChange',0,0})},function(event){PrimeFaces.ab({s:"j_idt87:name",e:"valueChange",f:"j_idt87",p:"j_idt87:name"});}])
```

The case that fail is with custom events like page, sort, tabChange;

``` xml
<p:dataTable
  <f:ajax event="page" />
</p:dataTable>
```

Output is;

```
page:function(ext) {mojarra.ab('j_idt88:j_idt89',event,'page',0,0}
```

Even if we render it like

```
page:function(ext, event) {mojarra.ab('j_idt88:j_idt89',event,'page',0,0}
```

We don't pass event when we execute the page callback as it is invoked via;

``` javascript
var pageBehavior = this.cfg.behaviors['page'];
 pageBehavior.call(this, options);  //options is the ext
```

Where options is the ajax cfg object, f:ajax were never supported in custom events due to implementation so we extended it with p:ajax.

So simply adding event to the renderer should not fix anything, event will still be undefined as we don't pass it. So both close to 100 custom event calls in javascript should be changed in addition to corerender to support f:ajax rendering that will still not work in the end because f:ajax doesn't know about custom events so it will be all for nothing.

**Comment by frederikd** [comment] 2015-04-22 00:28
@cagataycivici hmm, that's a shame that it doesn't work that easily.
I just played around with it a little bit and it seems like simply defining a global event variable does the trick in Firefox (IE and Chrome already have it), e.g. have this in the beginning of the page:

``` javascript
var event = event || {};
```

I only did limited testing (e.g. dateSelected event for p:calendar), but it appears like the event object does not need to have any content as long as it is at least defined.

So could a workaround maybe be to render something like the following?

``` javascript
page:function(ext, event) {mojarra.ab('j_idt88:j_idt89',event === "undefined" ? {} : event,'page',0,0}`
```

**Comment by frederikd** [comment] 2015-04-22 06:11
I had another look at the Mojarra source code and in the jsf.ajax.request function (which is called by mojarra.ab) it says that the event object is optional:

> The DOM event that triggered this Ajax request. The event argument is optional.

So it seems like we really only need to avoid the reference exception here to make at least the basic functionality work with custom events.

**Comment by codeturner** [comment] 2015-04-27 16:00
Thanks @frederikd for the best workaround, which is to simply ensure that event is defined globally:

```
var event = event || {};
```

For the long term fix, I understand, @cagataycivici, how adding event as a function parameter will not functionally do anything, but the simple fact is that mojarra is expecting it, for whatever reason.  So yes, rendering it like:

```
page:function(ext, event) {mojarra.ab('j_idt88:j_idt89',event,'page',0,0}
```

will, in fact, fix this bug because you will have defined it within the scope of this anonymous function.

Making this code change for the sake of mojarra will fix a ton of our code, and end all future struggles from other developers who won't know why some components won't work with f:ajax.

**Comment by tandraschko** [comment] 2015-04-27 18:38
@cagataycivici What about rendering this instead of a global event var:

```
page:function(ext, event) {if(!event){event={};} mojarra.ab('j_idt88:j_idt89',event,'page',0,0}
```

**Comment by cagataycivici** [comment] 2015-04-27 19:04
@tandraschko -1, that is too much change for me. How about;

``` javascript
page:function(ext, event) {mojarra.ab('j_idt88:j_idt89',event,'page',0,0}
```

**Comment by tandraschko** [comment] 2015-04-27 19:16
If it works, too -> sure! +1

**Comment by cagataycivici** [comment] 2015-04-27 19:20
I'll work on it tomorrow. Thank you.

**Comment by codeturner** [comment] 2015-04-27 19:52
Awesome, thank you!

**Comment by cagataycivici** [comment] 2015-04-28 07:39
Consider the following case;

https://jsfiddle.net/wsnrjbnx/

This works on Chrome but gives JS error on Firefox? Can anyone else confirm? How about IE? I don't have IE right now.

Working version is;

https://jsfiddle.net/wsnrjbnx/1/

**Comment by tandraschko** [comment] 2015-04-28 07:45
Yep, works in IE but not in FireFox.

**Comment by cagataycivici** [comment] 2015-04-28 08:13
Made the changes, I'd appreciate if you confirm the fix is working.

**Closed as completed** 2015-04-28 08:12 UTC
Labels: :lady_beetle: defect

**Comment by frederikd** [comment] 2015-04-28 23:16
Thanks @cagataycivici, we tested the changes in IE8, IE11, latest Chrome and Firefox and it all worked fine.

**Comment by cagataycivici** [comment] 2015-04-29 07:16
Glad to hear!
