### ISSUE TITLE
Calendar: Popup on dialog with wrong position

### ISSUE THREAD

**Issue by huinazhu** [primefaces/primefaces#5709] opened 2020-03-19 11:26 UTC
1. Environment
PrimeFaces version: PrimeFaces-6.2.26
Affected browsers: Chrome, Firefox

2. Expected behaviour
Correct position of the popup calendar when browser is zoomed in or out

3. Actual behaviour
When a p:calendar component is placed inside a p:dialog the popup shows in a wrong position when this 2 conditions are met:

4. Actual behaviour
Page is zoomed in or out
Page is scrolled down

5. Sample XHTML
```xml
<p:dialog modal="true" width="1100" appendTo="body" resizable="false" draggable="true" closable="false">
  <p:calendar locale="de" value="#{dateController.endTime}" pattern="dd.MM.yyyy HH:mm:ss" />
</p:dialog>
```

6. Sample bean
```java
@ViewScoped
@Named("dateController")
`
public class DateController implements Serializable
{
    protected Date endTime;

    public Date getEndTime() {
        return this.endTime;
    }
    public void setEndTime(Date endTime) {
        this.endTime = DateUtils.truncate(endTime, Calendar.SECOND);
    }
}
```

**Comment by melloware** [comment] 2020-03-19 12:53
Can't reproduce with PF 7.0 or 8.0.

[pf-5709.zip](https://github.com/primefaces/primefaces/files/4354617/pf-5709.zip)

1. Unzip the above zip.
2. Run `mvn clean jetty:run-exploded`
3. Navigate to http://localhost:8080/primefaces-test/test.xhtml

**Comment by melloware** [comment] 2020-03-19 12:56
Duplicate of #3868

**Closed as completed** 2020-03-19 12:56 UTC
Labels: Resolution: Invalid
