### ISSUE TITLE
Datatable: Not displayed when using reflow within ajaxstatus

### ISSUE THREAD

**Issue by mjp16** [primefaces/primefaces#9891] opened 2023-03-09 19:47 UTC
### Describe the bug

I found similar issue to what I'm experiencing with Case 8614, which was closed because users should be using update as jsf standard instead of js show() function.  However, when using p:ajaxstatus, the component is wrapped in display: none and if the datatable within the p:ajaxstatus uses reflow, then it is not displayed (given style=null;visibility:hidden;)

### Reproducer

```xml
<p:ajaxStatus>  
        <f:facet name="default">
          <p:poll interval="10"   
            listener="#{pollView.increment}" update="txt_count" />
        </f:facet>
        <f:facet name="start">
          Loading...
        </f:facet>       
        <f:facet name="complete">
          <ui:insert name="content"/>
        </f:facet>    
      </p:ajaxStatus>
   
      content:
      
      <p:dataTable var="someVar" editable="true" reflow="true"
						 value="#{val.values}" id="datatableExample"
						 stripedRows="true">
...
</p:dataTable>
```

### Expected behavior

After the poll increate runs, I expect the content to display that is within ajax status complete.  Everything within content is shown except for the datatable which white space is shown in place where data should be.

If I remove the reflow=true, then the datatable will show when content is shown with ajax status of complete.

I was able to override this by updating css with the following:

```css
table .ui-widget {
 visibility: visible!important;
}
```

However, this is not a good work around for anyone who would like to use the visibility hidden functionality within their css/app

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0-RC3

### JSF implementation

Mojarra

### JSF version

2.3.14

### Java version

11

**Comment by melloware** [comment] 2023-03-10 12:08
Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

I can't reproduce what you are saying so it must be something I am missing from your demo?

**Comment by melloware** [comment] 2023-03-14 21:28
Closing as workaround provided and no reproducer was provided.  Will re-open if necessary

**Closed as not planned** 2023-03-14 21:29 UTC
Labels: workaround, Status: Needs Reproducer
