### ISSUE TITLE
Pagination of lazy data with an unknown total row count

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#51] opened 2015-04-18 12:37 UTC
Support paginator even when total row count is not specified.

**Comment by cagataycivici** [comment] 2015-05-16 17:47
Review for 5.2.4.

**Comment by cagataycivici** [comment] 2015-05-19 12:17
@kukel Is there PR about this? Can't find it.

**Comment by cagataycivici** [comment] 2015-05-22 08:10
I couldn't understand anything from the patch. I need to do a discussion, anyone up for this? @kukel, @erik-wramner ?

**Comment by erik-wramner** [comment] 2015-05-22 11:28
Sure. The two patches are related, but I'll go through mine.

Normally the row count is known when the dataTable is first rendered. However, in my use case it is not. The problem is that counting the rows is so expensive, so we don't want to do it. It is much faster to just show the first page. We can navigate to the next page without problems, but we don't know the actual row count until we reach the last page - probably never. For live scrolling the dataTable initializes scrollLimit when it is first renedered and in our case it will be set to pageSize + 1, so the table knows that there is more to read. When the user scrolls down the dataTable will call loadLiveRows in order to get the next (and as it thinks final) page from the server. The server reads the next page and unless it is the last one it knows that there are at least (2 \* pageSize + 1) rows and modified the row count for the LazyDataModel accordingly. However, we need to notify the client-side code as this is an AJAX call. The patch in DataTableTemplate fixes that, totalRecords will be sent to the client side in the response.

The patch in oncomplete modifies the method signature so that the args (containing totalRecords) are available and sets the scrollLimit to the new row count value.

Finally I have had problems with live scroll keeping to load rows even though all have been read, so the patch in loadLiveRows adds an extra check that prevents that from happening.

Does that help? If not just ask.

**Comment by kukel** [comment] 2015-05-26 11:45
@cagataycivici: There is: https://github.com/primefaces/primefaces/pull/224

What the patch does is largely the same as what @erik-wrammer described. After each page event  check if the 'new' rowCount is larger than the current rowcount. If so, it still enables the 'next' page button. That is all. What effectively happens is to take the new rowcount that is send from the server into account.

The client is responsible then, in the load method of the lazydatamodel, to update the rowcount each time if the end is not reached. How to use this is to retrieve 'page-size' + 1 rows in a lazy datamodel and only retrieve 'page-size' records, but set the new rowCount at least one higher than the new total rowcount (previous rowcount + page size).  For an example check http://forum.primefaces.org/viewtopic.php?f=3&t=31126

**Comment by kukel** [comment] 2016-01-12 21:38
Can someone of the core team either fix this or close it? Having an interesting pull request open for over half a year after a request for comment and given is not 'appreciated' ;-)

**Comment by cagataycivici** [comment] 2016-01-12 21:40
Time flies fast, I'll review in 2 weeks. Promise :)

**Comment by tandraschko** [comment] 2016-01-24 16:22
The PR for the pagination looks fine for me. Not sure about the livescroll PR - never checked that part of the datatable.
Would be great if you could review both, Cagatay.

**Comment by cagataycivici** [comment] 2016-01-28 16:52
@tandraschko Thanks, I'll review tomorrow.

**Comment by erik-wramner** [comment] 2016-02-05 12:05
Any news on this and the related #287?

**Comment by cagataycivici** [comment] 2016-02-08 15:32
First to start with @kukel 's patch. This change is backward compatible right? I mean for users who load the actual number of rows, the changes in pr does not break anything as totalRecords will be the real totalRecords.

**Comment by cagataycivici** [comment] 2016-02-08 15:41
Both patches are based on the same idea, one question so it is up the developer to decide if pagination/scrolling should continue by adding at least +1 to the current number of loaded rows right? My question is how would they know where to stop and not update rowCount -> totalRecords to avoid updating the ui in the end?

**Comment by erik-wramner** [comment] 2016-02-09 05:50
Both patches are backwards compatible and they are based on the same idea. As for how the developer knows when to stop: when there is nothing more to read. The LazyDataModel asks for more rows. Assume a page size of 20. Then the first call will read 21 records, return 20 and report totalRecords as 21. If the user reads the next page (the client thinks there is one more record) it will read starting with record 21 in the total result set and return 20 records and report totalRecords as 41. The client asks for another page. If the total result set is 50 records, then the lazy data model will return the 10 remaining records and report totalRecords 50, meaning no more pages to read.

**Closed as completed** 2016-02-11 10:10 UTC
Labels: new feature

**Comment by cagataycivici** [comment] 2016-02-11 10:14
Both patches are merged, thank you.

**Comment by kukel** [comment] 2016-02-16 16:35
cool.. no version set yet?

One patch less in my custom version

**Comment by cagataycivici** [comment] 2016-02-16 20:37
6 for sure.
