### ISSUE TITLE
SelectCheckboxMenu: itemDisabled is broken

### ISSUE THREAD

**Issue by christophih** [primefaces/primefaces#5359] opened 2019-11-21 14:56 UTC
## 1) Environment
- PrimeFaces version: latest
- Does it work on the newest released PrimeFaces version? no
- Does it work on the newest sources in GitHub? no
- Application server + version: OpenLiberty
- Affected browsers: Browser independent

## 2) Expected behavior

If selectItems are disabled
...
<f:selectItems ... itemDisabled="#{val.valid} ... />
...
it should be rendered to the client. That means that the items in the panel (or at least the checkboxes) should get the css style class "ui-state-disabled".

## 3) Actual behavior

No disabled style is set.

## 4) Steps to reproduce

Just add the attribute itemDisabled to the f:selectItems...

## 5) Sample XHTML

<p:selectCheckboxMenu value="#{bean.values}" filter="true" filterMatchMode="startsWith">
   <f:selectItems value="#{bean.persons}" var="person" itemLabel="#{person.name}" itemValue="#{person.personId}" itemDisabled="#{person.valid}" />
</p:selectCheckboxMenu>

## 6) Sample bean
not necessary to reproduce

I've found the problem: 
The SelectCheckboxMenuRenderer.java sets the disabled style to the label (see writer.writeAttribute("class", "ui-state-disabled", null); ).

In the relevant js file forms.selectcheckboxmenu.js in Line 167 the input element is checked for a disabled attribute (disabled = input.is(':disabled'));

This doesn't match. In older versions of the SelectCheckboxMenuRenderer.java a disabled attribute is set on the input.

**Comment by melloware** [comment] 2019-11-21 14:59
Might be related to this fix: https://github.com/primefaces/primefaces/issues/5063

**Comment by melloware** [comment] 2019-11-21 15:07
[pf-5359.zip](https://github.com/primefaces/primefaces/files/3875316/pf-5359.zip)
Attached is test case run `"mvn clean jetty:run-exploded"` to run it and go to localhost:8080.

Can you reproduce your issue with that?  It seems to be fixed on 8.0-SNAPSHOT?

**Comment by christophih** [comment] 2019-11-22 07:36
Thank you for information about issue #5063. Seems to be fixed with 8.0-SNAPSHOT.

**Closed as completed** 2019-11-22 08:13 UTC
Labels: needs testing

**Comment by thogau** [comment] 2020-10-06 14:31
Any chances to have it fixed on the 7.x branch ?
