### ISSUE TITLE
SelectOneMenu: Wrong fixed position panel on dialog with scroll

### ISSUE THREAD

**Issue by astranCZ** [primefaces/primefaces#4609] opened 2019-03-05 08:40 UTC
## 1) Environment
- PrimeFaces version: 7.0.RC3
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tomcat 7 + 9
- Affected browsers: Chrome, Firefox, Microsoft Edge

## 2) Expected behavior
When you open the SelectOneMenu selection in the panel with the scrolling bar after turning the mouse wheel, the selection does not move.

## 3) Actual behavior
When you open the SelectOneMenu selection in the panel with the scrolling bar after turning the mouse wheel, the selection does move.

## 4) Steps to reproduce
When you open the SelectOneMenu selection in the panel with the scrolling bar after turning the mouse wheel, the selection does move.

## 5) Sample XHTML
```
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>

<h:body>
	<p:commandButton value="Modal" type="button"
		onclick="PF('dlg').show();" />

	<p:dialog header="Autocomplete" widgetVar="dlg" modal="true"
		resizable="false" position="400,200" width="400" height="400">
		<div style="height: 1500px;">
			<h:form>
				<br/><br/><br/><br/><br/><br/><br/>
				<p:selectOneMenu id="console" value="#{selectOneMenuView.console}"
					style="width:125px">
					<f:selectItem itemLabel="Select One" itemValue="" />
					<f:selectItem itemLabel="Xbox One" itemValue="Xbox One" />
					<f:selectItem itemLabel="PS4" itemValue="PS4" />
					<f:selectItem itemLabel="Wii U" itemValue="Wii U" />
				</p:selectOneMenu>
			</h:form>
		</div>
	</p:dialog>
</h:body>
</html>
```
![image](https://user-images.githubusercontent.com/15103640/53791855-aae7b900-3f2a-11e9-8264-8f181cc0a763.png)

## 6) Sample bean
not necessary

**Comment by Rapster** [comment] 2019-03-05 09:17
It looks like there was a bunch of issues fixed in the past which sound the same as that... For example: https://github.com/primefaces/primefaces/issues/4180

**Comment by tandraschko** [comment] 2019-03-05 09:35
Please try a build from source, should be fixed

**Comment by OBreidenbach** [comment] 2019-03-05 09:35
Sounds like this is a duplicate of #4590

**Comment by astranCZ** [comment] 2019-03-05 10:09
> Please try a build from source, should be fixed

I have build from SNAPSHOT (master-6_1-g79934bb-2532) and still no fix.
```
<dependency>
	<groupId>com.github.primefaces</groupId>
	<artifactId>primefaces</artifactId>
	<version>master-SNAPSHOT</version>
</dependency>
```

**Comment by melloware** [comment] 2019-03-05 12:57
Attached test case is working fine for me in 7.0-SNAPSHOT.
[pf-4609.zip](https://github.com/primefaces/primefaces/files/2930976/pf-4609.zip)

Run "mvn clean jetty:run-exploded" and navigate to http://localhost:8080/primefaces-test/test.xhtml

**Comment by astranCZ** [comment] 2019-03-05 16:06
I started your example. The same problem. 
The menu opens at the right place, but after turning the mouse wheel, the field changes the position and the menu remains in place.

**Comment by melloware** [comment] 2019-03-05 16:08
Hmm I am using Windows 10 and Chrome and when I mouse wheel the selectone menu closes properly and does not scroll along with it.

**Comment by astranCZ** [comment] 2019-03-05 16:21
After click, the menu closes - OK.
But do not click but turn the wheel to scroll the scrollbar.
I too using Windows 10 and Chrome, but same behavior in all browsers.

**Comment by tandraschko** [comment] 2019-03-05 16:51
@mertsincan can you check this before the release?

**Comment by melloware** [comment] 2019-03-05 21:13
OK after pressing CTRL+F5 to reload my JS I can confirm the issue.

**Comment by OBreidenbach** [comment] 2019-03-06 07:20
The height of the div inside the dialog is higher then the height of the dialog. So the dialog gets a scrollbar. The failure happens if using the scrollbar of the dialog, not if using the scrollbar of the window/document.
The failure happens not only with SelectOneMenu but also with:
colorpicker, overlay menu, calendar, keyboard, passwort, selectCheckboxMenu

No problem with: datePicker

You can easily use my example from https://github.com/primefaces/primefaces/issues/4536#issuecomment-464637526 and add a height to the dialog and the form

**Comment by tandraschko** [comment] 2019-03-18 09:26
@mertsincan will you fix this for 7.0? It really breaks some cases.

**Comment by mertsincan** [comment] 2019-03-18 10:32
Unfortunately, no! This issue is different from #4536. A new attribute can be added and some JS codes can be modified accordingly. I need a lot of time to fix the issue and do the tests. Therefore, I'll fix this issue on 7.0.x and 7.1.

**Comment by serdarayalp** [comment] 2020-01-14 08:49
use appendTo="@this" for selectOneMenu, this should solve your problem.

**Comment by serdarayalp** [comment] 2020-01-14 08:51
try to use appendTo="@this" for selectOneMenu, this should solve your problem.

**Comment by serdarayalp** [comment] 2020-06-22 08:14
is there anything new for this ticket? We have the same problem here.

**Comment by melloware** [comment] 2020-11-30 19:52
I think this one is more similar to: https://github.com/primefaces/primefaces/issues/1173

**Closed as completed** 2020-11-30 20:55 UTC
Labels: :lady_beetle: defect
