### ISSUE TITLE
[Documentation] Showcase v.8

### ISSUE THREAD

**Issue by diogo-cvs** [primefaces/primefaces#12069] opened 2024-06-05 15:03 UTC
### Describe the bug

The documentation (showcase) for version 8.0 is inaccessible https://www.primefaces.org/showcase-v8/

### PrimeFaces edition

None

### PrimeFaces version

8.0

### JSF implementation

All

### JSF version

2.3

### Java version

11

**Comment by tandraschko** [comment] 2024-06-05 15:06
Duplicate of https://github.com/primefaces/primefaces/issues/12019

**Comment by melloware** [comment] 2024-06-05 15:58
@diogo-cvs see this for a solution: https://github.com/orgs/primefaces/discussions/2031

**Closed as not planned** 2024-06-06 10:56 UTC
Labels: Resolution:  Wontfix
