### ISSUE TITLE
Add implicit converter fot p:autocomplete when the value is a SelectItem object

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1494] opened 2016-06-06 19:57 UTC
Add implicit converter for p:autocomplete when the value is a SelectItem object similar to SelectOneMenu component when the list values are a SelectItem list

![image](https://cloud.githubusercontent.com/assets/8562436/15840472/9dc87042-2c0f-11e6-9b92-5b45e2d18c97.png)

**Comment by JaviRpo** [comment] 2016-09-22 04:49
Any solutions about this issue?

**Comment by tandraschko** [comment] 2017-10-16 20:04
Will close it for now as there is no information how the reproduce it.
If the issue is still there in 6.1 or 6.2-SNAPSHOT, please create new issue with all informations requested by our issue template.

**Closed as completed by tandraschko** 2017-10-16 20:04 UTC
Labels: Resolution: Invalid
