### ISSUE TITLE
selectOneMenu: Wrongly escaping input when selecting a value from the list 

### ISSUE THREAD

**Issue by MWI-msg** [primefaces/primefaces#9528] opened 2022-12-20 11:57 UTC
### Describe the bug

If the selectOneMenu is used with items that contains characters that have to be escaped within the HTML than those characters are escaped wrongly within the input field of the selectOneMenu. Initially the values are correct, the error occurs if the js script is triggered for setting the text of the current selected item. The error entered with PF11 where within the "PrimeFaces.widget.SelectOneMenu.prototype.renderSelectItem" method an escaping was added "PrimeFaces.escapeHTML(..)". A reproducer is attached. 

[Uploading SelectOneMenuReproducer.zip…]()

### Reproducer

Start the reproducer and open the browser on "http://localhost:8080/primefaces-test/". There you see the select one menu with the correct text. As soon as you click on the drop-down-button the text is displayed with escaped characters. Within the test.js file is a TODO where you can find the line that is causing this issue and also the line that is fixing it. 
[SelectOneMenuReproducer.zip](https://github.com/primefaces/primefaces/files/10268130/SelectOneMenuReproducer.zip)

### Expected behavior

Even if another item is selected about the drop down box the displayed text should not contain escaped characters. 

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### Theme

Diamond

### JSF implementation

MyFaces

### JSF version

2.3

### Java version

11

**Comment by jepsar** [comment] 2022-12-20 12:25
Duplicate of https://github.com/primefaces/primefaces/issues/9336? @MWI-msg Did you try with the 13.0.0-SNAPSHOT?

**Comment by melloware** [comment] 2022-12-20 13:34
If I remove your test.js and run with 13.0.0-SNAPSHOT this works fine so I think this is already fixed.

**Comment by melloware** [comment] 2022-12-20 13:35
MonkeyPatch:

```js
if (PrimeFaces.widget.SelectOneMenu) {
    PrimeFaces.widget.SelectOneMenu.prototype.renderSelectItem = function(item, isGrouped) {
        var content = "";
        var $item = $(item);
        var label, dataLabel;
        var title = $item.data("title");
        var escape = $item.data("escape");
        var cssClass;

        if (item.tagName === "OPTGROUP") {
            label = $item.attr("label");
            if (escape) {
                label = $("<div>").text(label).html();
            }
            cssClass = "ui-selectonemenu-item-group ui-corner-all";
        } else { //OPTION
            if (escape) {
                label = $item.html();
                if ($item.text() === "&nbsp;") {
                    label = $item.text();
                }
            } else {
                label = $item.text();
            }
            
            cssClass = "ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all";
            if (isGrouped) {
                cssClass += " ui-selectonemenu-item-group-children";
            }
        }

        dataLabel = this.escapeHTMLIfNecessary(label.replace(/(<([^>]+)>)/gi, ""));

        if ($item.data("noselection-option")) {
            cssClass += " ui-noselection-option";
        }

        content += '<li class="' + cssClass + '" tabindex="-1" role="option"';
        if (title) {
            content += ' title="' + title + '"';
        }
        if ($item.is(':disabled')) {
            content += ' disabled';
        }
        content += ' data-label="' + dataLabel + '"';
        content += '>';
        content += label;
        content += '</li>';

        if (item.tagName === "OPTGROUP") {
            content += this.renderSelectItems($item, true);
        }

        return content;
    };

    PrimeFaces.widget.SelectOneMenu.prototype.escapeHTMLIfNecessary = function(value) {
            return String(value).replace(/[<>"'`=\/]/g, function(s) {
                return PrimeFaces.entityMap[s];
            });
     };
}
```

**Closed as not planned** 2022-12-20 13:36 UTC
Labels: Resolution: Duplicate
