### ISSUE TITLE
dataTable: paginator=true breaks dynamic rendering of columns

### ISSUE THREAD

**Issue by NOTiFYcouk** [primefaces/primefaces#4774] opened 2019-05-01 16:12 UTC
Attached is zip containing a working example that allows you to dynamically display columns in the dataTable. Added to code supplied by @Melloware.

## 1) Environment
- PrimeFaces 7.0:
- Does it work on the newest released PrimeFaces version? Version? NO
- Does it work on the newest sources in GitHub? (Build by source) NO
https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: Used Jetty here. JBoss WildFly 16.0.0.Final in production.
- Affected browsers: Google Chrome & Safari
Google Chrome Version 74.0.3729.108 (Official Build) (64-bit)
Safari 12.1 (14607.1.40.1.4)
macOS Mojave 10.14.4

## 2) Expected behaviour
Add & remove columns from dataTable. Move back and forward within the table. Change pagination size. Click on checkbox to add or remove further columns from dataTable.
...

## 3) Actual behaviour
Add & remove columns from dataTable. Move back and forward within the table. Change pagination size. Click on checkbox DOES NOT add or remove (render) columns from dataTable.
..

## 4) Steps to reproduce

Unzip file. CD to pf-4477 directory. Run: 
mvn jetty:run-exploded

In browser:
http://localhost:8080/primefaces-test/
.. 

## 5) Sample XHTML
See ZIP file.
..

## 6) Sample bean
See ZIP file.
..
Code also available at: https://github.com/NOTiFYcouk/pf-4477
[pf-4477-master.zip](https://github.com/primefaces/primefaces/files/3135108/pf-4477-master.zip)

**Comment by melloware** [comment] 2020-07-14 19:24
@NOTiFYcouk I just tried this with PF 8.0 and can't reproduce it.  Closing for now.

**Closed as completed by melloware** 2020-07-14 19:24 UTC
Labels: :lady_beetle: defect
