### ISSUE TITLE
DataTable: Filtering and sorting does not work on ColumnGroup

### ISSUE THREAD

**Issue by kodmarcel** [primefaces/primefaces#2672] opened 2017-08-29 11:45 UTC
The showcase for grouping [https://www.primefaces.org/showcase/ui/data/datatable/group.xhtml](https://www.primefaces.org/showcase/ui/data/datatable/group.xhtml) is used and modified to add sorting and filtering. The header columns show sorting arrows and input area for filtering but neither works on dynamic columns.

## 1) Environment
- PrimeFaces version: 6.0 (6.1, 6.2-SNAPSHOT(29.8.2017) are not working either)
- Does it work on the newest released PrimeFaces version? Version? NO
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: Tested with : Wildfly-8.2.1 , Jetty-8.1.9.v20130131
- Affected browsers: Tested on Firefox 55, but should not work on others either.

## 2) Expected behavior

Sorting and filtering is working for the dynamic headers.

## 3) Actual behavior

Sorting and filtering are working for static header column. On dynamic header columns filtering is not invoked and sorting causes a null pointer exception.  

>SEVERE: java.lang.NullPointerException
	at org.primefaces.component.datatable.feature.SortFeature.decode(SortFeature.java:87)
	at org.primefaces.component.datatable.DataTableRenderer.decode(DataTableRenderer.java:64)
	at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:831)
	at org.primefaces.component.api.UIData.processDecodes(UIData.java:287)
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:573)
	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
	at org.primefaces.component.api.UIData.visitTree(UIData.java:827)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIForm.visitTree(UIForm.java:371)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700)
	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:403)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:266)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
	at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:927)
	at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:78)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646)

A quick check with a debugger shows that the id of the column on which sorting was invoked by user is different in the org.primefaces.component.datatable from the id  that is passed as a parameter to it when searching for the component.

## 4) Steps to reproduce
1. Clone [https://github.com/kodmarcel/primefaces-test](https://github.com/kodmarcel/primefaces-test)
2. Execute `mvn jetty:run` from the project folder
3. Visit [http://localhost:8080/primefaces-test/groupingBug.xhtml](http://localhost:8080/primefaces-test/groupingBug.xhtml) in browser and try to sort/filter the year columns on the lower table.

Alternatively: 
1. Clone [https://github.com/primefaces/primefaces-test.git](https://github.com/primefaces/primefaces-test.git)
2. Copy beans and xhtml code from below samples into the cloned project.
3. Execute `mvn jetty:run` from the project folder
4. Visit [http://localhost:8080/primefaces-test/groupingBug.xhtml](http://localhost:8080/primefaces-test/groupingBug.xhtml) in browser and try to sort/filter the year columns on the lower table.

## 5) Sample XHTML
Code from : [https://www.primefaces.org/showcase/ui/data/datatable/group.xhtml](https://www.primefaces.org/showcase/ui/data/datatable/group.xhtml) with added `filterBy`, `sortBy` and `filteredValue` to the second table.

groupingBug.xhtml:

```html
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
  xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:p="http://primefaces.org/ui"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:h="http://java.sun.com/jsf/html">

<h:head>
  <f:facet name="first">
    <meta http-equiv="X-UA-Compatible" content="IE=EDGE" />
  </f:facet>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>Home</title>
  <link href="resources/css/default.css" rel="stylesheet"
    type="text/css" />
</h:head>


<h:body>
  <div style="padding: 15px 15px 0px 15px">


    <h:form>
      <p:dataTable var="sale" value="#{dtGroupView.sales}"
        paginator="true" rows="10">
        <f:facet name="header">
            Sales/Profits of Manufacturers
        </f:facet>

        <p:columnGroup type="header">
          <p:row>
            <p:column rowspan="3" headerText="Manufacturer" />
            <p:column colspan="4" headerText="Sale Rate" />
          </p:row>
          <p:row>
            <p:column colspan="2" headerText="Sales" />
            <p:column colspan="2" headerText="Profit" />
          </p:row>
          <p:row>
            <p:column headerText="Last Year" />
            <p:column headerText="This Year" />
            <p:column headerText="Last Year" />
            <p:column headerText="This Year" />
          </p:row>
        </p:columnGroup>

        <p:column>
          <h:outputText value="#{sale.manufacturer}" />
        </p:column>
        <p:column>
          <h:outputText value="#{sale.lastYearProfit}%" />
        </p:column>
        <p:column>
          <h:outputText value="#{sale.thisYearProfit}%" />
        </p:column>
        <p:column>
          <h:outputText value="#{sale.lastYearSale}">
            <f:convertNumber type="currency" currencySymbol="$" />
          </h:outputText>
        </p:column>
        <p:column>
          <h:outputText value="#{sale.thisYearSale}">
            <f:convertNumber type="currency" currencySymbol="$" />
          </h:outputText>
        </p:column>

        <p:columnGroup type="footer">
          <p:row>
            <p:column colspan="3" style="text-align:right"
              footerText="Totals:" />
            <p:column footerText="$#{dtGroupView.lastYearTotal}" />

            <p:column footerText="$#{dtGroupView.thisYearTotal}" />
          </p:row>
        </p:columnGroup>

        <f:facet name="footer">
            Data between 2013-2014
        </f:facet>
      </p:dataTable>

      <p:dataTable var="player" value="#{dtGroupView.players}"
        filteredValue="#{dtGroupView.filteredPlayers}"
        style="margin-top:40px">
        <f:facet name="header">
            Dynamic Columns
        </f:facet>

        <p:columnGroup type="header">
          <p:row>
            <p:column rowspan="2" headerText="Player"
              sortBy="#{player.name}" filterBy="#{player.name}" />
            <p:column colspan="#{dtGroupView.yearCount}"
              headerText="Goals" />
          </p:row>
          <p:row>
            <ui:repeat value="#{dtGroupView.years}" var="year">
              <p:column id="#{year}Header" headerText="#{year}"
                sortBy="#{player.getGoals(year)}"
                filterBy="#{player.getGoals(year)}" />
            </ui:repeat>
          </p:row>
        </p:columnGroup>

        <p:column>
          <h:outputText value="#{player.name}" />
        </p:column>

        <p:columns value="#{dtGroupView.years}" var="year"
          style="min-width: 48px;">
          <h:outputText value="#{player.getGoals(year)}" />
        </p:columns>

        <f:facet name="footer">
            Data between 2010-2014
        </f:facet>
      </p:dataTable>
    </h:form>
  </div>
</h:body>

</html>
```

## 6) Sample bean
Code from [https://www.primefaces.org/showcase/ui/data/datatable/group.xhtml](https://www.primefaces.org/showcase/ui/data/datatable/group.xhtml) with added field `filterdPlayers` to `GroupView.java`

Player.java:
```java
public class Player {
     
    private String name;
     
    private Map<Integer,Integer> goals;
     
    public Player() {
        goals = new LinkedHashMap<Integer,Integer>();
    }
     
    public Player(String name, Map<Integer,Integer> goals) {
        this.name = name;
        this.goals = goals;
    }
 
    public String getName() {
        return name;
    }
 
    public void setName(String name) {
        this.name = name;
    }
     
    public int getGoals(int year) {
        return goals.get(year);
    }
}
```

Sale.java:
```java
public class Sale implements Serializable {
 
    private String manufacturer;
 
    private int lastYearSale;
 
    private int thisYearSale;
 
    private int lastYearProfit;
 
    private int thisYearProfit;
 
    public Sale() {}
 
    public Sale(String manufacturer, int lastYearSale, int thisYearSale, int lastYearProfit, int thisYearProfit) {
        this.manufacturer = manufacturer;
        this.lastYearSale = lastYearSale;
        this.thisYearSale = thisYearSale;
        this.lastYearProfit = lastYearProfit;
        this.thisYearProfit = thisYearProfit;
    }
 
    public int getLastYearProfit() {
        return lastYearProfit;
    }
 
    public void setLastYearProfit(int lastYearProfit) {
        this.lastYearProfit = lastYearProfit;
    }
 
    public int getLastYearSale() {
        return lastYearSale;
    }
 
    public void setLastYearSale(int lastYearSale) {
        this.lastYearSale = lastYearSale;
    }
 
    public String getManufacturer() {
        return manufacturer;
    }
 
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }
 
    public int getThisYearProfit() {
        return thisYearProfit;
    }
 
    public void setThisYearProfit(int thisYearProfit) {
        this.thisYearProfit = thisYearProfit;
    }
 
    public int getThisYearSale() {
        return thisYearSale;
    }
 
    public void setThisYearSale(int thisYearSale) {
        this.thisYearSale = thisYearSale;
    }
}
```

GroupView.java:
```java
@ManagedBean(name = "dtGroupView")
@ViewScoped
public class GroupView implements Serializable {

    private final static String[] manufacturers;
    private List<Sale> sales;

    private final static String[] playerNames;
    private List<Integer> years;
    private List<Player> players;
    private List<Player> filteredPlayers;

    static {
        manufacturers = new String[10];
        manufacturers[0] = "Apple";
        manufacturers[1] = "Samsung";
        manufacturers[2] = "Microsoft";
        manufacturers[3] = "Philips";
        manufacturers[4] = "Sony";
        manufacturers[5] = "LG";
        manufacturers[6] = "Sharp";
        manufacturers[7] = "Panasonic";
        manufacturers[8] = "HTC";
        manufacturers[9] = "Nokia";
    }

    static {
        playerNames = new String[10];
        playerNames[0] = "Lionel Messi";
        playerNames[1] = "Cristiano Ronaldo";
        playerNames[2] = "Arjen Robben";
        playerNames[3] = "Franck Ribery";
        playerNames[4] = "Ronaldinho";
        playerNames[5] = "Luis Suarez";
        playerNames[6] = "Sergio Aguero";
        playerNames[7] = "Zlatan Ibrahimovic";
        playerNames[8] = "Neymar Jr";
        playerNames[9] = "Andres Iniesta";
    }

    @PostConstruct
    public void init() {
        sales = new ArrayList<Sale>();
        for (int i = 0; i < 10; i++) {
            sales.add(new Sale(manufacturers[i], getRandomAmount(), getRandomAmount(), getRandomPercentage(),
                    getRandomPercentage()));
        }

        years = new ArrayList<Integer>();
        years.add(2010);
        years.add(2011);
        years.add(2012);
        years.add(2013);
        years.add(2014);

        players = new ArrayList<Player>();
        for (int i = 0; i < 10; i++) {
            players.add(new Player(playerNames[i], generateRandomGoalStatsData()));
        }
    }

    public List<Sale> getSales() {
        return sales;
    }

    private int getRandomAmount() {
        return (int) (Math.random() * 100000);
    }

    private int getRandomPercentage() {
        return (int) (Math.random() * 100);
    }

    public String getLastYearTotal() {
        int total = 0;

        for (Sale sale : getSales()) {
            total += sale.getLastYearSale();
        }

        return new DecimalFormat("###,###.###").format(total);
    }

    public String getThisYearTotal() {
        int total = 0;

        for (Sale sale : getSales()) {
            total += sale.getThisYearSale();
        }

        return new DecimalFormat("###,###.###").format(total);
    }

    public List<Integer> getYears() {
        return years;
    }

    public int getYearCount() {
        return years.size();
    }

    public List<Player> getPlayers() {
        return players;
    }

    public List<Player> getFilteredPlayers() {
        return filteredPlayers;
    }

    public void setFilteredPlayers(List<Player> filteredPlayers) {
        this.filteredPlayers = filteredPlayers;
    }

    private Map<Integer, Integer> generateRandomGoalStatsData() {
        Map<Integer, Integer> stats = new LinkedHashMap<Integer, Integer>();
        for (int i = 0; i < 5; i++) {
            stats.put(years.get(i), getRandomGoals());
        }

        return stats;
    }

    private int getRandomGoals() {
        return (int) (Math.random() * 50);
    }
}
```

**Comment by Rapster** [comment] 2020-11-02 15:39
I'll have to see again but I think this should be fixed if we fixed #6409 instead

**Comment by Rapster** [comment] 2020-11-02 16:09
My PR won't fix it, it won't actually give the possibility to sort since as explained in #6409, columns are defined in a very unconventionnel way (13 columns define to actually display 5, other Prime librairies do the same mistake). I'm not in favor of changing my PR to support this sample as it will involve a lot of fiddling resulting ugly code, while it can be solved just by fixing #6409. FYI, I have a fix for #6409

**Comment by melloware** [comment] 2020-11-02 16:17
Agreed let's unlink it.

**Comment by tandraschko** [comment] 2020-12-25 21:20
@melloware would you Like to retest? I feel this might be fixed by my commits

**Comment by melloware** [comment] 2020-12-26 13:52
I have modernized the reproducer:
[pf-2672.zip](https://github.com/primefaces/primefaces/files/5743160/pf-2672.zip)

Using 9.0-SNAPSHOT we don't get a stacktrace but none of the columns actually sort.

**Comment by tandraschko** [comment] 2020-12-26 15:30
will check it now
seems like the generated columnKey is wrong

**Comment by tandraschko** [comment] 2020-12-26 20:07
@melloware i fixed sorting but AIFACS there are not filters displayed?!

**Comment by melloware** [comment] 2020-12-26 21:55
I know his original sample did not have filters so not sure why they said filters were not working.

**Comment by tandraschko** [comment] 2020-12-27 00:23
its quite hard to support ui:repeat here. the basic functionality is working but filtering/sorting doesnt work because the #getColumnKey doesnt contain the ui:repeat index

i fixed it now 
rendering now works perfectly but sort doest not work because the sortBy contains a var from ui:repeat, which isnt available at this time. This would need a refactoring, it works fine in filtering because forEachColumn can easily be used.

**Comment by tandraschko** [comment] 2020-12-27 00:24
@melloware could you write some basic integration tests for this and #5117?

**Comment by tandraschko** [comment] 2020-12-27 15:27
had to refactor sorting a bit and fixed all bugs now (note: Player in the example needs to be Serializable)

the code before was cleaner as it could simple use sortMeta#getColumn, which doest have the correct state of the ui:repeat, therfore in JSF its always better to use visit/invoke pattern vs findComponent.

In theory we should never use sortMeta#getColumn or filterMeta#getColumn

**Closed as completed by tandraschko** 2020-12-27 15:27 UTC
Labels: :lady_beetle: defect

**Comment by melloware** [comment] 2020-12-27 16:02
Yep let me see if I can add some Integration tests for this.  Great work!

**Comment by melloware** [comment] 2020-12-27 16:52
@tandraschko We have 3 failing integration tests after this change revolving around sorting.
```
DataTable003Test.testMultiSort2:99->AbstractDataTableTest.assertRows:21 expected: <2> but was: <5>
DataTable003Test.testMultiSort:68->AbstractDataTableTest.assertRows:21 expected: <4> but was: <2>
DataTable013Test.testSortByWithDefault:50->AbstractDataTableTest.assertRows:21 expected: <4> but was: <2>
```

**Comment by melloware** [comment] 2020-12-27 17:00
I see its not sorting correctly because DataTable003Test sorts by "First Appeared, then by Name" but if you look at the screenshot it looks like the sort order is off and its sorting by Name first even though we clicked it second.

![image](https://user-images.githubusercontent.com/4399574/103175833-063f1580-483b-11eb-9990-5c9261e6201e.png)

**Comment by Rapster** [comment] 2023-10-13 09:34
I'm kinda waking up a bit late about this _(better too late than never...)_, but why using `<ui:repeat />` with column when you could use `<p:columns />` it works fine with that. So why bothering supporting `<ui:repeat />` when it's not necessary?
