### ISSUE TITLE
Calendar popup in dynamic dialog not fully visible

### ISSUE THREAD

**Issue by morvael** [primefaces/primefaces#5593] opened 2020-02-10 13:53 UTC
## 1) Environment

PrimeFaces version: 7.0.11

## 2) Expected behavior

Calendar popup fully visible, even when part of external page in a dynamically generated dialog.

## 3) Actual behavior

![picker_bug](https://user-images.githubusercontent.com/1133953/74155274-9456e100-4c14-11ea-9888-bc88160f580e.png)

**Comment by melloware** [comment] 2020-02-10 14:15
What happens when you add `appendTo="@(body)"` to the calendar?

**Comment by morvael** [comment] 2020-02-10 14:26
"The attribute appendTo is not defined on the component calendar". Only datePicker has that attribute, and I am unable to use datePicker because of missing functionality (editing milliseconds).

**Comment by melloware** [comment] 2020-02-10 14:38
OK please create a reproducer using PrimeFaces Test project and attach to this ticket.

**Comment by morvael** [comment] 2020-02-10 15:01
[primefaces-test.tar.gz](https://github.com/primefaces/primefaces/files/4181472/primefaces-test.tar.gz)

**Comment by melloware** [comment] 2020-02-10 15:05
Thanks for the reproducer!

**Comment by christophs78** [comment] 2020-02-11 09:24
Dynamic dialog is based on HTML-IFRAME. Due to this the content of the dynamic dialog has to fit within the dialog=IFRAME. (I know that´s not ideal.)
Knowing it´s not ideal you may e.g. work around by increasing the height of the dialog.

**Comment by melloware** [comment] 2020-02-11 11:47
Yes this is a limitation of the dialog framework using an IFRAME.  Not content can be drawn outside the IFRAME so I am going to mark this as WONTFIX.

**Closed as completed by melloware** 2020-02-11 11:47 UTC
Labels: Resolution:  Wontfix

**Comment by morvael** [comment] 2020-02-11 11:55
Was afraid this may be so. Yes, I'll have to resize the dialog.
