### ISSUE TITLE
Spotlight: highlight multiple elements

### ISSUE THREAD

**Issue by mdkbdg** [primefaces/primefaces#5949] opened 2020-05-23 16:49 UTC
**Description**
multiple spotlight on multiple elements (or group of elements) different triggered once by, for example, a commandbutton

**Describe the solution you would like**
```xml
<p:commandButton value="Highlight" 
   onclick="PF('elem1').show();PF('elem2').show()"  <-- maybe like this?
/>
```
The above results only `elem2` spotlighted

Maybe it is possible to have both elements spotlighted?
Am not sure what to change here
https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/resources/primefaces/spotlight/spotlight.js

array of target?
accumulative offset?

Appreciate any inputs

**Comment by melloware** [comment] 2020-05-23 16:55
Can you use the target to spolight multiple elements?
```xml
<p:inputText id="txt1" styleClass="observe-spotlight" />
<p:inputText id="txt2" styleClass="observe-spotlight" />
```
Then you can try...
```xml
<p:spotlight target="@(.observe-spotlight)" widgetVar="spot"/>
```
or
```xml
<p:spotlight target="txt1 txt2" widgetVar="spot"/>
```

**Comment by melloware** [comment] 2020-05-23 16:59
Ah no looking at the code the spotlight only draws one box for spotlighting so that explains why your element2 won since it was 2nd called.

Is there any way to put both elements inside one p:outputPanel and use that as the target?

**Comment by mdkbdg** [comment] 2020-05-23 18:04
Exactly.
`calculatePositions` only draws one spotlight box.

Putting elements inside an outputPanel is surely an alternative. 
Unfortunately currently I am having multiple elements scattered on different panels

(I use this spotlight not for validation as the showcase, but am using this for 'explanation' of which field to focus when doing an action)

**Comment by melloware** [comment] 2020-05-23 21:38
Let me see what I can do. I think this component just needs some rearranging.

**Comment by melloware** [comment] 2020-05-24 15:00
I investigate this and have it spotlightighint multiple components the but the problem is the way the masks are calculated one mask is not blocking another spotlighted component.  So I don't think this can be done easily or do what you want.  Here is what I have so far if you want to try and tweak it further.

```javascript
/**
 * __PrimeFaces Spotlight Widget__
 * 
 * Spotlight highlights a certain component on page, drawing the user's attention to it.
 * 
 * @prop {JQuery} target The DOM element for the target component to highlight.
 * 
 * @interface {PrimeFaces.widget.SpotlightCfg} cfg The configuration for the {@link  Spotlight| Spotlight widget}.
 * You can access this configuration via {@link PrimeFaces.widget.BaseWidget.cfg|BaseWidget.cfg}. Please note that this
 * configuration is usually meant to be read-only and should not be modified.
 * @extends {PrimeFaces.widget.BaseWidgetCfg} cfg
 * 
 * @prop {boolean} cfg.active Whether the spotlight is initially turned on.
 * @prop {boolean} cfg.blockScroll `true` to block scrolling when the spotlight is turned on, or `false` otherwise.
 * @prop {string} cfg.target The search expression for the target component to highlight.
 */
PrimeFaces.widget.Spotlight = PrimeFaces.widget.BaseWidget.extend({

    /**
     * @override
     * @inheritdoc
     * @param {PrimeFaces.PartialWidgetCfg<TCfg>} cfg
     */
    init: function(cfg) {
        this._super(cfg);
        this.target = PrimeFaces.expressions.SearchExpressionFacade.resolveComponentsAsSelector(this.cfg.target);

        if(this.cfg.active) {
            this.show();
        }
    },
    
    /**
     * @override
     * @inheritdoc
     * @param {PrimeFaces.PartialWidgetCfg<TCfg>} cfg
     */
    refresh: function(cfg) {
        // clean up any spotlight divs
        this.hide();
        
        this._super(cfg);
    },

    /**
     * Creates the mask overlay element for the spotlight effect and adds it to the DOM.
     * @private
     * 
     * @param {number} index the index number of the spotlight
     * @return {JQuery} the new DIV created for spotlighting
     */
    createMasks: function(index) {
        var documentBody = $(document.body),
            spotlight = $('<div class="ui-widget-overlay ui-spotlight ui-spotlight-top ui-helper-hidden"></div><div class="ui-widget-overlay ui-spotlight ui-spotlight-bottom ui-helper-hidden"></div>' +
                    '<div class="ui-widget-overlay ui-spotlight ui-spotlight-left ui-helper-hidden"></div><div class="ui-widget-overlay ui-spotlight ui-spotlight-right ui-helper-hidden"></div>')
        documentBody.append(spotlight);
        return spotlight;
    },

    /**
     * Turns the spotlight on so that a certain part of the page is highlighted.
     */
    show: function() {
        this.calculatePositions();

        this.spotlights.show();

        this.bindEvents();
    },

    /**
     * Computes and applies the rectangular position of the spotlight.
     * @private
     */
    calculatePositions: function() {
        var doc = $(document),
            $this = this,
            documentBody = $(document.body);
        
        $.each(this.target, function(index, obj) {
            var zindex = ++PrimeFaces.zindex,
            component = $(obj),
            offset = PrimeFaces.utils.calculateRelativeOffset(component);
            
            var mask = $this.createMasks(index),
                spotlightTop = $(mask.get(0)),
                spotlightBottom = $(mask.get(1)),
                spotlightLeft = $(mask.get(2)),
                spotlightRight = $(mask.get(3));

            spotlightTop.css({
                'left': 0,
                'top': 0,
                'width': documentBody.width(),
                'height': offset.top,
                'z-index': zindex
            });

            var bottomTop = offset.top + component.outerHeight();
            spotlightBottom.css({
                'left': 0,
                'top': bottomTop,
                'width': documentBody.width(),
                'height': doc.height() - bottomTop,
                'z-index': zindex
            });

            spotlightLeft.css({
                'left': 0,
                'top': offset.top,
                'width': offset.left,
                'height': component.outerHeight(),
                'z-index': zindex
            });

            var rightLeft = offset.left + component.outerWidth();
            spotlightRight.css({
                'left': rightLeft,
                'top': offset.top,
                'width': documentBody.width() - rightLeft,
                'height': component.outerHeight(),
                'z-index': zindex
            });
        });
        
        this.spotlights = documentBody.children('div.ui-spotlight');
    },

    /**
     * Sets up all event listeners that are required by this widget.
     * @private
     */
    bindEvents: function() {
        var $this = this;

        this.target.data('zindex',this.target.zIndex()).css('z-index', ++PrimeFaces.zindex);

        if (this.cfg.blockScroll) {
            PrimeFaces.utils.preventScrolling();
        }
        PrimeFaces.utils.preventTabbing(this.id, $this.target.zIndex(), function() {
            return $this.target.find(':tabbable');
        });

        $(window).on('resize.spotlight scroll.spotlight', function() {
            $this.calculatePositions();
        });
    },

    /**
     * Removes the event listeners that were added when the spotlight was turned on.
     * @private
     */
    unbindEvents: function() {
        PrimeFaces.utils.enableTabbing(this.id);
        if (this.cfg.blockScroll) {
            PrimeFaces.utils.enableScrolling();
        }
        $(window).off('resize.spotlight scroll.spotlight');
    },

    /**
     * Turns of the spotlight so that the entire page is visible normally again.
     */
    hide: function() {
        // clean up any spotlight divs
        if(this.spotlights.length > 0) {
            this.spotlights.remove();
        }
        this.unbindEvents();
        this.target.css('z-index', this.target.zIndex());
    }

});
```

**Comment by mdkbdg** [comment] 2020-05-24 17:45
I'm gonna have to find a simple way to override only this particular js. 
Is there any way to do it without having to build the whole PF project?

---
Found it: 
```
<h:body>
    <h:outputScript name="js/spotlight.js" />
</h:body>
```
Quick and dirty, but... well...

---

Now, back to main topic: 

I notice, the more elements to be 'spotlighted', the darker my screen gets :)
I understand the problem you mentioned and I agree, it seems like a simple one but it is not. 

Thanks much for this. It is actually a great start. Really appreciate it

**Comment by melloware** [comment] 2020-05-24 20:36
You No problem!  Yes you see the problem is the "mask" panes are overlapping each other.

You can also override each method by doing this.

```javascript
PrimeFaces.widget.Spotlight.refresh = function(cfg) {
    // clean up any spotlight divs
    this.hide();

    this._super(cfg);
};


PrimeFaces.widget.Spotlight.createMasks = function(index) {
    var documentBody = $(document.body),
        spotlight = $('<div class="ui-widget-overlay ui-spotlight ui-spotlight-top ui-helper-hidden"></div><div class="ui-widget-overlay ui-spotlight ui-spotlight-bottom ui-helper-hidden"></div>' +
            '<div class="ui-widget-overlay ui-spotlight ui-spotlight-left ui-helper-hidden"></div><div class="ui-widget-overlay ui-spotlight ui-spotlight-right ui-helper-hidden"></div>')
    documentBody.append(spotlight);
    return spotlight;
};


PrimeFaces.widget.Spotlight.show = function() {
    this.calculatePositions();

    this.spotlights.show();

    this.bindEvents();
};


PrimeFaces.widget.Spotlight.calculatePositions = function() {
    var doc = $(document),
        $this = this,
        documentBody = $(document.body);

    $.each(this.target, function(index, obj) {
        var zindex = ++PrimeFaces.zindex,
            component = $(obj),
            offset = PrimeFaces.utils.calculateRelativeOffset(component);

        var mask = $this.createMasks(index),
            spotlightTop = $(mask.get(0)),
            spotlightBottom = $(mask.get(1)),
            spotlightLeft = $(mask.get(2)),
            spotlightRight = $(mask.get(3));

        spotlightTop.css({
            'left': 0,
            'top': 0,
            'width': documentBody.width(),
            'height': offset.top,
            'z-index': zindex
        });

        var bottomTop = offset.top + component.outerHeight();
        spotlightBottom.css({
            'left': 0,
            'top': bottomTop,
            'width': documentBody.width(),
            'height': doc.height() - bottomTop,
            'z-index': zindex
        });

        spotlightLeft.css({
            'left': 0,
            'top': offset.top,
            'width': offset.left,
            'height': component.outerHeight(),
            'z-index': zindex
        });

        var rightLeft = offset.left + component.outerWidth();
        spotlightRight.css({
            'left': rightLeft,
            'top': offset.top,
            'width': documentBody.width() - rightLeft,
            'height': component.outerHeight(),
            'z-index': zindex
        });
    });

    this.spotlights = documentBody.children('div.ui-spotlight');
};


PrimeFaces.widget.Spotlight.bindEvents = function() {
    var $this = this;

    this.target.data('zindex', this.target.zIndex()).css('z-index', ++PrimeFaces.zindex);

    if (this.cfg.blockScroll) {
        PrimeFaces.utils.preventScrolling();
    }
    PrimeFaces.utils.preventTabbing(this.id, $this.target.zIndex(), function() {
        return $this.target.find(':tabbable');
    });

    $(window).on('resize.spotlight scroll.spotlight', function() {
        $this.calculatePositions();
    });
};


PrimeFaces.widget.Spotlight.unbindEvents = function() {
    PrimeFaces.utils.enableTabbing(this.id);
    if (this.cfg.blockScroll) {
        PrimeFaces.utils.enableScrolling();
    }
    $(window).off('resize.spotlight scroll.spotlight');
};


PrimeFaces.widget.Spotlight.hide = function() {
    // clean up any spotlight divs
    if (this.spotlights.length > 0) {
        this.spotlights.remove();
    }
    this.unbindEvents();
    this.target.css('z-index', this.target.zIndex());
};
```

**Comment by melloware** [comment] 2020-06-01 17:24
@mdkbdg Did you make any progress on this?  if not for now I will close this ticket as its not how Spotlight was designed to work.  If you figure it out and want to provide a fix I can reopen the ticket.

**Closed as completed by melloware** 2020-06-01 17:24 UTC
Labels: new feature

**Comment by mdkbdg** [comment] 2020-06-02 15:41
@melloware thanks for the support these past few weeks. I will leave it as it is now, maybe for future reference.
