### ISSUE TITLE
DatePicker: Problem with 29/02/2024 (leap year)

### ISSUE THREAD

**Issue by kika73** [primefaces/primefaces#11536] opened 2024-02-29 11:26 UTC
### Describe the bug

Todays date is a special date that only occurs every 4 years: 29th of february
For this reason there is an errormessage and behaviour, that ist not correct:

```xml
<p:datePicker id="minmax" value="#{calendarView.date11}" mindate="#{calendarView.todaysDate}"
							maxdate="#{calendarView.todaysDatePlusYears(10)}"/>
```

Values of the both methods above:
```
12:19:33,417 INFO  [stdout] (default task-20) todaysDate: 29.02.2024
12:19:33,417 INFO  [stdout] (default task-20) todaysDatePlusYears: plusJahre [10], returnDate: 28.02.2034
12:19:33,418 SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-20) Error Rendering View[/views/bvplus/antrag/einstellungsinformationen.xhtml]: javax.faces.FacesException: DatePicker : "contentFrm:orgaFelderList:0:wunschEinstellungsTermin:DP" minimum date must be less than maximum date.
```

### Reproducer

Use the 29th February as minDate und something in future for maxDate in Datepicker

### Expected behavior

there should be no exception

### PrimeFaces edition

Elite

### PrimeFaces version

10.0.17

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

### Browser(s)

Firefox 122.0

**Comment by kika73** [comment] 2024-02-29 11:38
debugging Primefaces-code shows the problem:
![grafik](https://github.com/primefaces/primefaces/assets/80694586/dc0152a7-cb0e-496f-b2e6-724c939b65f8)

**Comment by melloware** [comment] 2024-02-29 13:06
@kika73 i can't reproducer:
[pf-11536.zip](https://github.com/primefaces/primefaces/files/14448342/pf-11536.zip)

Unzip and run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

Edit my reproducer to see if you can make it happen?

**Comment by kika73** [comment] 2024-02-29 13:11
sorry, my mistake - we used a string and not a date-object

**Comment by kika73** [comment] 2024-02-29 13:30
but - i found in documentation, that String is allowed - but then you have the described problem
![grafik](https://github.com/primefaces/primefaces/assets/80694586/9b991ba2-6239-4dc3-b7b1-4c7e055e71c7)

**Comment by melloware** [comment] 2024-02-29 14:12
Can you update my reproducer showing the issue with String?

**Comment by kika73** [comment] 2024-02-29 14:56
its not possible to reproduce it with PF 13. UICalendar.validateMinMax(FacesContext context) was changed and the problem is not a problem anymore.
PF 13:
![grafik](https://github.com/primefaces/primefaces/assets/80694586/2b588b33-a09c-4c01-b40b-f84eba14ec46)
PF 10:
![grafik](https://github.com/primefaces/primefaces/assets/80694586/f47cc458-165c-40b9-a92a-cfee83c8bb83)

**Comment by melloware** [comment] 2024-02-29 15:13
OK if its fixed in 13 then I will close this issue as we don't backport to 10.x. This is the community tracker only.

**Closed as not planned by melloware** 2024-02-29 15:13 UTC
Labels: Resolution: Cannot Replicate

**Comment by melloware** [comment] 2024-02-29 15:30
You can read more here: https://github.com/primefaces/primefaces?tab=readme-ov-file#community--elite--pro
