### ISSUE TITLE
Calendar: stops working after change template with calendar component

### ISSUE THREAD

**Issue by milansie** [primefaces/primefaces#11121] opened 2023-12-13 20:11 UTC
### Describe the bug

Hiya,

we found a bug in p:calendar component. If you switch template (via ui:include or ui:decorate) which includes p:calendar component, after second page visit, the calendar component stops working.

There is javascript error:
Uncaught TypeError: u._base_updateDatepicker is not a function
 in this function:
```   $.datepicker._updateDatepicker = function(n) {
        var t = n.input[0];
        if (!$.datepicker._curInst || $.datepicker._curInst === n || !$.datepicker._datepickerShowing || $.datepicker._lastInput === t)
            if ("boolean" !== typeof n.stay_open || !1 === n.stay_open) {
                var u = this;
                setTimeout(function() {
                    u._base_updateDatepicker(n);
                    var y = u._get(n, "timepicker");
                    y && y._addTimePicker(n);
                    u._updateDatePickerPosition(n)
                }, 0)
            }
    }
```

It seems that main component is created again, but inner datepicker isn't initialized correctly.
With p:datePicker it's working correctly.

Check attached demo https://github.com/milansie/pf_calendar_bug . Use switch button to switch from field view to calendar view. On second switch the calendar component stops working, while datePicker works ok.

Thanks
Milan 

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0 (all)

### JSF implementation

MyFaces

### JSF version

4.0

### Java version

17+

**Comment by tandraschko** [comment] 2023-12-13 20:43
Should be fixed by: https://github.com/primefaces/primefaces/issues/11046

**Comment by melloware** [comment] 2023-12-13 20:49
@milansie  i will have you retest after 13.0.4 comes out.

**Comment by milansie** [comment] 2023-12-13 20:58
I've tested it right now with 13.0.4-SNAPSHOT and unfornutaelly it doesn't work. Javascript error does not occur anymore,  but the calendar popup is not displayed.

**Comment by melloware** [comment] 2023-12-13 21:37
Can you try it with 14.0.0-SNAPSHOT as well?

**Comment by milansie** [comment] 2023-12-14 07:51
I've tested it on 14.0.0-SNAPSHOT, and behaviour is the same as with 13.0.4. No javascript error but not displaying popup.

**Comment by melloware** [comment] 2023-12-15 17:42
@milansie how can I reproduce with your reproducer? I keep calling "Switch" and then using the Calendar and it works fine?

**Comment by melloware** [comment] 2023-12-15 17:43
Nevermind I reproduced it.

**Comment by melloware** [comment] 2023-12-15 17:54
OK I see what's going on its because when we broke out the calendar we moved `calendar/2-jquery.ui.pfextensions.js` to this component when it used to be loaded when jquery was loaded.    So if I add a calendar to the main page this all works because the JS is loaded on the page already.

We may have to move `calendar/2-jquery.ui.pfextensions.js` back to jquery packaging.

**Comment by melloware** [comment] 2023-12-15 23:26
So a lame workaround is to put a calendar on your main page but hidden

```xml
<p:calendar style="display:none" />
```

**Comment by milansie** [comment] 2023-12-16 06:42
Yep, it is working, but it is not possible solution for our project. 
But, what is the future of p:calendar component? Isn't now is the best time to switch to p:datePicker, which is working great?

**Comment by melloware** [comment] 2023-12-16 12:38
Oh yes Calendar was deprecated in version 10 and recommendation is to move to DatePicker.  Calendar isn't even on the Showcase anymore.   We keep Calendar in the code because for 15 years it has been PrimeFaces Calendar and we understand its hard for people to migrate large projects.

But at my clients we have switched all our code to DatePicker from Calendar.

**Comment by milansie** [comment] 2023-12-16 13:06
Yes, we will do the same. 
For me, we could close this issue with "workaround" solution - if you agree. I think fixing that would be waste of time.
Thanks very much

**Closed as not planned** 2023-12-16 13:10 UTC
Labels: :lady_beetle: defect, workaround
