### ISSUE TITLE
DataTable: Sort not working when javax.faces.STATE_SAVING_METHOD is set to client

### ISSUE THREAD

**Issue by zakhdar** [primefaces/primefaces#7192] opened 2021-04-02 10:38 UTC
**Describe the defect**
Sorting of datatable is not working when javax.faces.STATE_SAVING_METHOD is set to client

**Reproducer**
Tested with Primefaces 10 Showcase  repo from github

**Environment:**
 - PF Version: 10
 - JSF + version: Mojarra 2.3.14.SP02
 - Affected browsers:  Firefox
 - AS : Wildfly 22

**To Reproduce**
1. Go to Datable Sort Demo page
2. Click on column when sorting is actived  (on broswer console we can see the XHR request is fired , but datatable not sorted

**Comment by melloware** [comment] 2021-04-02 10:55
Duplicate of https://github.com/primefaces/primefaces/issues/6987

**Closed as completed** 2021-04-02 10:55 UTC
Labels: Resolution: Duplicate
