### ISSUE TITLE
When lazy=true on datatable then cellediting and commandButtons don't work

### ISSUE THREAD

**Issue by Serkan80** [primefaces/primefaces#1527] opened 2016-06-15 15:39 UTC
My problem:
When I enable lazy loading then suddenly cell editing/updating doesn't work anymore and also any commandLink or button in the datatable doesn't get called.

Here is my code:
`
<p:dataTable` id="patienten" value="#{pqBean}" var="p" editable="true" editMode="cell" rowKey="#{p.id}" stickyHeader="true" rows="15" paginator="true" paginatorAlwaysVisible="false" lazy="true">

```
   <p:column>
         <p:commandButton immediate="true" icon="ui-icon-search" onclick="PF('afsprakenDlg').show()">
            <f:setPropertyActionListener value="#{p.id}" target="#{patientHome.id}" />
        </p:commandButton>
        <p:commandButton update="patienten" action="#{patientHome.remove}" icon="fa fa-remove">
            <f:setPropertyActionListener value="#{p.id}" target="#{patientHome.id}" />                
        </p:commandButton>
    </p:column>
 </p:dataTable>
```

And here is my LazyModel implementation:

`@Name("pqBean")`
`@Scope(ScopeType.CONVERSATION)`
`public class LazyQuery extends LazyDataModel<Patient> {`

```
@In
private EntityManager entityManager;
private List<Patient> patienten;


@Override
public Patient getRowData(String rowKey) {
    long id = Long.parseLong(rowKey);
    for (Patient p : patienten) {
        if (p.getId() == id)
            return p;
    }
    return null;
}

@Override
public Object getRowKey(Patient p) {
    return p.getId();
}

@Override
@SuppressWarnings("unchecked")
public List<Patient> load(int first, int pageSize, String sortField, SortOrder sortOrder, Map<String, Object> filters) {
    String query = getQuery(sortField, sortOrder, filters);
    patienten = entityManager.createQuery(query).setFirstResult(first).setMaxResults(pageSize).getResultList();
    Long totalCount = totalCount(query);

    // rowCount
    int dataSize = patienten.size();
    this.setRowCount(totalCount.intValue());

    // paginate
    if (dataSize > pageSize) {
        try {
            return patienten.subList(first, first + pageSize);
        }
        catch (IndexOutOfBoundsException e) {
            return patienten.subList(first, first + (dataSize % pageSize));
        }
    }
    else {
        return patienten;
    }
}
```

`

Note that cellediting works fine if lazy is disabled and also buttons start working.

I've tested this on PF 5.3 and 6.0. And I'm using Tomcat 8.0 with JSF 2.2 (Mojara) and JDK 8.

**Comment by michael-las** [comment] 2016-06-15 17:07
Using JSF+CDI+PF 6 running on Jetty 9.3 your example works for me using CDIs ViewScoped and ConversationScoped, too. I don't use Seam and it didn't work as long no conversation has been started.

Example: 
[issue1527.zip](https://github.com/primefaces/primefaces/files/316723/issue1527.zip)

**Comment by tandraschko** [comment] 2016-06-15 17:23
Is @Scope from seam?

**Comment by Serkan80** [comment] 2016-06-15 18:59
Yes, I'm using Seam 2.3 which has support for JSF 2.x.

@michael-las 
Do you mean that it works when you don't use the conversation scope ? 

It's strange because I was debugging the code and somewhere in UIData (of Primefaces) my data was set to null and this passes the value to CellEditEvent and this goes to LazyDataModel, which makes the old and new value both null.

**Comment by michael-las** [comment] 2016-06-15 19:05
No, your example works with both ViewScoped and ConversationScoped beans. But when using ConversationScoped beans, I had to start the conversation first, otherwise it won't work. You can download the zip above, it contains a few .java and one index.html file of a working example.

**Comment by Serkan80** [comment] 2016-06-15 19:06
@michael-las 
Ok, I will try to start a long running conversation scope then. And I'm checking your zip file, I let you hear in a second.

**Comment by Serkan80** [comment] 2016-06-15 19:11
@michael-las 

Yes, you were right ! It works now. I'm using a LRC now and it works !

Thx !

**Comment by michael-las** [comment] 2016-06-15 19:28
Nice. So, the datatable works as intended or is there any bug?

**Comment by Serkan80** [comment] 2016-06-15 19:33
Till now, it works as intended. But it's strange though that a LRC is needed, since a default Conversation should be similar to ViewScope.

**Comment by tandraschko** [comment] 2016-06-15 19:51
probably you need to pass the conversationId somehow on the ajax request, not sure.

**Comment by tandraschko** [comment] 2016-06-15 19:51
Will close it as invalid as we don't "care" about scopes in PF.

**Closed as completed by tandraschko** 2016-06-15 19:51 UTC
Labels: Resolution: Invalid
