### ISSUE TITLE
dataTable: horizontal scroll not work on RTL language

### ISSUE THREAD

**Issue by awenger63** [primefaces/primefaces#3369] opened 2018-02-26 16:27 UTC
## 1) Environment
- PrimeFaces version: 6.2.RC1 (actual showcase)
- Affected browsers: All

## 2) Expected behavior
support RTL language in dataTable horizontal scroll

## 3) Actual behavior
dataTable Header have not horizontal scrolling on RTL language and virtualScrolling haven't horizontal scrollbar

## 4) Steps to reproduce
- Go to show case : [https://www.primefaces.org/showcase/ui/data/datatable/scroll.xhtml](url)
- Examine Element 
- Modify `<div class="PC">` add dir property `<div class="PC" dir="RTL">`
- dataTable are in RTL mode
- use horizontal scrollbar : header don't move 
- go to virtualScrolling : no horizontal scroll

**Comment by awenger63** [comment] 2019-06-27 12:43
Any news ?

**Comment by awenger63** [comment] 2019-06-27 12:44
Issue always exist. to reproduce :
`<div class="content-section content-implementation " dir="RTL">`
Thanks for update ?

**Comment by mertsincan** [comment] 2019-06-28 15:15
Duplicate of #4950

**Closed as completed by mertsincan** 2019-06-28 15:15 UTC
Labels: Resolution: Duplicate
