### ISSUE TITLE
CommandButton: Same Files are being download from a JSF backing bean

### ISSUE THREAD

**Issue by chsreedhar** [primefaces/primefaces#5955] opened 2020-05-26 07:26 UTC
https://github.com/omnifaces/omnifaces/issues/552

**Comment by Rapster** [comment] 2020-05-26 08:33
There is an issue template to follow, you could help us by summarizing what has been discussed already instead of simply copying/pasting a link and let us deal with it...

**Comment by chsreedhar** [comment] 2020-05-26 10:19
#### Below commandButton is inside `<p:dataTable>`'s footer
This commandButton is updated on `rowSelect` & `rowUnselect` events of `<p:ajax>`

    <p:commandButton id="pdfVwBtn" value="View PDF Doc." icon="pi pi-file-pdf "  action="#{pdfView.viewPDF}" onclick="this.form.target='_blank'" ajax="false"  >
       <f:param name="id" value="#{sid}" />
       <f:param name="type" value="#{type}" />
    </p:commandButton>

#### CDI Bean 
    public void viewPDF() throws IOException {
	        String fileName = Faces.getRequestParameter("id");
    	String fileType = Faces.getRequestParameter("type");
    	File pdffile = new File(getFilePath(), fileName);
    	Faces.sendFile(pdffile, false);
	}

### Issue:
On first time `rowSelect` event, able to dowonload the required file and this same file is being downloaded even different `rowSelect` of `<p:dataTable>` selected.

As suggested by @BalusC  `noCache` filter also added as below to `web.xml` and tried with view below
```
<filter>
    <filter-name>noCache</filter-name>
    <filter-class>org.omnifaces.filter.CacheControlFilter</filter-class>
</filter>
<filter-mapping>
    <filter-name>noCache</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
```
#### View
```
<h:form>
   <p:commandButton value="View HE10107" action="#{pdfView.viewPDF}" ajax="false" onclick="this.form.target='_blank'">
      <f:param name="id" value="BP-HE10107R2.pdf" />
      <f:param name="type" value="PRS" />
   </p:commandButton>
   <p:commandButton value="View HE10119" action="#{pdfView.viewPDF}" ajax="false" onclick="this.form.target='_blank'">
      <f:param name="id" value="BP-HE10119R1.pdf" />
      <f:param name="type" value="PRS" />
   </p:commandButton>
   <h:commandButton value="View HE10107" action="#{pdfView.viewPDF}" onclick="this.form.target='_blank'">
      <f:param name="id" value="BP-HE10107R2.pdf" />
      <f:param name="type" value="PRS" />
   </h:commandButton>
   <h:commandButton value="View HE10119" action="#{pdfView.viewPDF}" onclick="this.form.target='_blank'">
      <f:param name="id" value="BP-HE10119R1.pdf" />
      <f:param name="type" value="PRS" />
   </h:commandButton>
</h:form>
```
`<h:commandButton>`s are working as expected. But incase of `<p:commandButton>` problem repeats.

### Environment
TomEE 7.1.2 with JSF 2.2.20
PrimeFaces 8.0/7.0
OmniFaces 2.7.4

**Comment by melloware** [comment] 2020-05-26 11:25
Please follow the issue template or provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

because I still don't understand what the actual problem is.

**Comment by melloware** [comment] 2020-05-29 11:37
Closing ticket without a reproducer.  I will reopen if a reproducer is provided.

**Closed as completed by melloware** 2020-05-29 11:37 UTC
Labels: needs further work
