### ISSUE TITLE
Diagram: editable - overflow: auto issue problem (not scrolling as Basic diagram)

### ISSUE THREAD

**Issue by andresantos22** [primefaces/primefaces#3603] opened 2018-04-23 11:13 UTC
## 1) Environment
- PrimeFaces version: 6.2.2
- Does it work on the newest released PrimeFaces version? Version? Yes.
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source). Yes.
- Application server + version: Jboss 6.4
- Affected browsers: Chrome, Firefox.

## 2) Expected behavior

Auto resize the working panel, as others Diagram components (like the Basic one).

## 3) Actual behavior

It´s not scrolling the actual working p:diagram when dragging an Element.

## 4) Steps to reproduce

1) Look at the primefaces showcase;
2) https://www.primefaces.org/showcase/ui/data/diagram/basic.xhtml;
3) Drag one element to force the scroll bar appears (css overflow: auto);
4) The element goes outside, you can reach it when scrolling the model;
5) https://www.primefaces.org/showcase/ui/data/diagram/editable.xhtml
6) Drag one element to force the scroll bar appears (css overflow: auto). It won´t scroll more than a little piece. It gets worse when a change in resolution occurs.

## 5) Sample XHTML

Exactly the same as Editable Diagram component at PF showcase.

## 6) Sample bean

Exactly the same as Editable Diagram component at PF showcase.

**Comment by andresantos22** [comment] 2018-04-23 13:36
Adding, I´ve found that using Connectors it won´t work:

```
connector = new StateMachineConnector();
model.setDefaultConnector(connector);
```

As the BASIC does not set a Global connector  it´s not affected.

**Comment by melloware** [comment] 2020-09-08 15:08
duplicate of #4726

**Closed as completed by melloware** 2020-09-08 15:08 UTC
Labels: Resolution: Duplicate, Resolution: Invalid

**Comment by melloware** [comment] 2020-09-08 15:41
Just set the following `containment` property to false:
```java
model = new DefaultDiagramModel();
model.setContainment(false);
```
