### ISSUE TITLE
OutputPanel: Deferred mode ignored when component is rendered after AJAX interaction

### ISSUE THREAD

**Issue by rvieira5** [primefaces/primefaces#7867] opened 2021-09-25 19:35 UTC
**Describe the defect**

The defect occurs in a page with 2 sections. The first one, which can be viewed as a menubar or a sidebar, is responsible to trigger the load of the second section using AJAX. The second section contains a listing component (e.g., a `p:dataTable`), and for each element in the list, a `p:outputPanel` is rendered, with deferred loading enabled and deferred mode set to "visible".

In this scenario, when the user triggers the load of the second section by clicking in the button of the first section, all of the content in the list is loaded, ignoring the deferred mode configuration (visible).

If the code is changed to load the listing without the need to click in the button of the first section, the configuration works as expected.

**Reproducer**

1. Clone repository https://github.com/rvieira5/primefaces-test
2. Checkout branch **deferred-loading-bug**

**Environment:**
 - PF Version: _10.0_
 - JSF versions: _Mojarra 2.2.20_, _Mojarra 2.3.16_, _MyFaces 2.2.12_, _MyFaces 2.3.9_
 - Affected browsers: _Firefox_, _Opera_, possibly _ALL_

**To Reproduce**
1. Clone repository https://github.com/rvieira5/primefaces-test
2. Checkout branch **deferred-loading-bug**
3. Run the command `mvn jetty:run` in the root directory of the project
4. Open the URL http://localhost:8080/primefaces-test in the browser
5. Choose one of the 6 scenarios
6. Click on the "Load content" button
7. At this point, it is possible to see that all the items were loaded in the page, both by checking visually and by checking the HTTP request in the browser developer tools.

**Expected behavior**
Only the content of the visible items should be loaded in the page.

**Example XHTML**
```html
<div id="loader-container">
    <h:form>
        <p:commandButton update="loaded-container"
                       action="#{testView.setFlag(true)}"
                       value="Load content" />
    </h:form>
</div>

<h:panelGroup id="loaded-container">
    <ui:fragment rendered="#{testView.flag}">
        <p:dataTable value="#{testView.list}" var="obj">
            <p:column>
                <p:outputPanel deferred="true" deferredMode="visible">
                    <div class="loaded-content">
                        Loaded
                    </div>
                </p:outputPanel>
            </p:column>
        </p:dataTable>
    </ui:fragment>
</h:panelGroup>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
    private List<Object> list;
    private boolean flag;

    @PostConstruct
    public void init() {
        list = new ArrayList<>();

        for (int i = 0; i < 15; i++) {
            list.add(new Object());
        }

        // To load the page correctly, change the following value to true
        flag = false;
    }

    public boolean isFlag() {
        return flag;
    }

    public void setFlag(boolean flag) {
        this.flag = flag;
    }

    public List<Object> getList() {
        return list;
    }

    public void setList(List<Object> list) {
        this.list = list;
    }

}
```

**Comment by melloware** [comment] 2021-09-26 14:35
The OutputPanel Widgets are never being called.

So when you load the page only 1 widget is loaded for the command button: `$(function(){PrimeFaces.cw("CommandButton","widget_j_idt7_j_idt8",{id:"j_idt7:j_idt8"});});`

When you click the button only 1 widget for DataList is loaded again not all the output panel widgets it looks like their DIVS are rendered but their widgets are never called. `PrimeFaces.cw("DataList","widget_j_idt11",{id:"j_idt11"})`.  The only way `deferredMode` would work is if all the OutputPanel Widgets were also being called but for DataList/DataTable/ that appears not to be the case.

The problem seems to be in `OutputPanelRenderer` where it determines that deferred mode is not necessary if being rendering in an AJAX request.

```java
protected boolean isDeferredNecessary(FacesContext context, OutputPanel panel) {
        if (!panel.isDeferred()) {
            return false;
        }
        if (panel.getValueExpression(OutputPanel.PropertyKeys.loaded.name()) != null) {
            return !panel.isLoaded();
        }
        return !context.getPartialViewContext().isAjaxRequest();
    }
```

However this is fixed in 11.0.0 with the new `loaded` property was added for scenarios like this: https://github.com/primefaces/primefaces/pull/7732/files

However @jepsar it is still not working in his scenario above.  If I add `loaded="true"` or false I can't get the deferred loading to work in this scenario?

Reproducer: 
[pf-7867.zip](https://github.com/primefaces/primefaces/files/7231568/pf-7867.zip)

Navigate to http://localhost:8080/primefaces-test/test-pcommandbutton-pdataList.xhtml and you will see the issue.

**Comment by melloware** [comment] 2021-09-26 14:45
OK @jepsar this is very confusing it ONLY works if it an EL expression?
```xml
<p:outputPanel deferred="true" deferredMode="visible" loaded="#{not testView.flag}">
```

However now it looks like it is in an infinite AJAX loop when I add the above line to the reproducer?

**Comment by jepsar** [comment] 2021-09-27 17:28
@melloware I want to check if the attribute is used. Maybe it needs to be changed to a `Boolean` object and check for not `null`.

**Comment by melloware** [comment] 2021-09-29 13:07
@rvieira5 if you try this reproducer with the latest 11.0.0-SNAPSHOT it is resolved.
[pf-7867.zip](https://github.com/primefaces/primefaces/files/7252067/pf-7867.zip)

**Closed as completed** 2021-09-29 13:07 UTC
Labels: :lady_beetle: defect
