### ISSUE TITLE
DataTable: Value of component  in non rendered column gets evaluated after ajax update.

### ISSUE THREAD

**Issue by nemanjajovanovicgit** [primefaces/primefaces#10639] opened 2023-09-11 15:40 UTC
### Describe the bug

As the title says, component which should not be rendered gets evaluated after ajax update of parent DataTable. Problem lies in  `org.primefaces.component.api.UIData.visitRows` and in `org.primefaces.component.api.UIData.visitColumnContent` .  `org.primefaces.component.api.UIData.visitColumnContent`  gets called on a child component whether or not the column `isVisitable`.

### Reproducer

[primefaces-test-master-nonjakarta.zip](https://github.com/primefaces/primefaces/files/12764091/primefaces-test-master-nonjakarta.zip)

### Expected behavior

Expected behavior would be that child component does not get evaluated if the column is not rendered

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### JSF implementation

Mojarra

### JSF version

4.0.4

### Java version

Adoptium Temurin jdk-17.0.8.1+1

**Comment by nemanjajovanovicgit** [comment] 2023-09-11 16:35
> I believe it is by design that even though components are not rendered, they're still part of the JSF tree therefore visited

Ok, but what possible use would that design have? The component is not rendered and its evaluation seems like a waste of time at best. At worst as is my case it produces a NullPointerException in the backend since the same xhtml page is used for more than one entity, and columns that are not rendered do not exist in the back model.

**Comment by Rapster** [comment] 2023-09-11 18:33
Yeah I see what you mean, could be a question for https://github.com/jakartaee/faces

**Comment by fcorneli** [comment] 2023-09-12 06:08
> > I believe it is by design that even though components are not rendered, they're still part of the JSF tree therefore visited
> 
> Ok, but what possible use would that design have? 

To ensure that JSF always assigns the same Id's, whether it's rendered or not. Else AJAX updates might go foobar.

**Comment by nemanjajovanovicgit** [comment] 2023-09-12 06:48
> > > I believe it is by design that even though components are not rendered, they're still part of the JSF tree therefore visited
> > 
> > 
> > Ok, but what possible use would that design have?
> 
> To ensure that JSF always assigns the same Id's, whether it's rendered or not. Else AJAX updates might go foobar.

Ok sure that makes somewhat sense, but I still stand by my opinion. If id of a component is relevant to a developer it should be manually assigned. Correct my if I am wrong but I cannot think of a use case where referencing dynamically assigned JSF id is useful.

**Comment by Rapster** [comment] 2023-09-12 09:22
Since UIData from PF is based on UIData from Mojarra, I invite you again to ask to the specs guys here https://github.com/jakartaee/faces

Depending what they say, we can do something on PF side

**Comment by melloware** [comment] 2023-09-12 20:54
Hmm we do in other places skip un-rendered?

In ComponentUtils.java we have

```java
public static final Set<VisitHint> VISIT_HINTS_SKIP_UNRENDERED = Collections.unmodifiableSet(
            EnumSet.of(VisitHint.SKIP_UNRENDERED));
```

That is used in quite a few places?

**Comment by Rapster** [comment] 2023-09-13 21:42
Would be great to have a reproducer to know where your NPE comes from (meaning you can always give a stacktrace)

**Comment by melloware** [comment] 2023-09-27 01:35
@nemanjajovanovicgit can you provide a reproducer please?

**Comment by nemanjajovanovicgit** [comment] 2023-09-29 10:43
Uploaded reproducer, when you update input text in second table value from non rendered column in first table gets evaluated. Upon further inspection, when updating whole table everything works as expected, but when updating just a single row, problem occurs. (See reproducer for more info)

**Comment by melloware** [comment] 2023-10-30 13:26
@nemanjajovanovicgit but if you are updating a single row how can it know the evaluation of the columns on the datatable being rendered since they are not being touched?

**Comment by melloware** [comment] 2023-12-21 21:33
I took a look at the Mojarra code and they do check `rendered` on the columns in the latest Faces 5.0 codebase but it looks like our UIData has some special code for PF that was not accounting for rendered.

**Comment by melloware** [comment] 2024-12-04 20:15
Going to close this as a workaround has been provided and the use case is a corner case

**Closed as not planned by melloware** 2024-12-04 20:15 UTC
Labels: :zap: performance, discussion
