### ISSUE TITLE
SelectOneMenu: Screenreader Talkback (Android) resets selected value

### ISSUE THREAD

**Issue by HISeG-ME** [primefaces/primefaces#5799] opened 2020-04-16 12:01 UTC
## 1) Environment
- PrimeFaces version: 6.2.1
- Does it work on the newest released PrimeFaces version? Version? not reproducable
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) 
- Application server + version: Tomcat 9
- Affected browsers: Android Screenreader Talkback & Chrome

## 2) Expected behavior
If a SelectOneMenu-Listitem gets selected with the Screenreader Talkback in the Browser Chrome, the chosen Value should appear within the label (ui-selectonemenu-label). 
...

## 3) Actual behavior
If the User selects a Listitem from the Selectonemenu, (Advanced) which holds a blank first entry, the Value won´t be displayed in the Label. Chrome renders a &nbsp; instead. The parent-Element Div (ui-selectonemenu) has the correct title after the selection. This is the only occurance of the behaviour, I´ve tested also with Iphone and Safari (Screenreader Voiceover), it works. The same for Android Talkback and Firefox, as well as Screenreader Jaws17 and IE11 on Desktop, it works without this error.
..

## 4) Steps to reproduce
Swipe to a Selectonemenu until you reach the opening Element. Doubletab to open the List and swipe until you focus the Element that should be selected. Doubletab to select, the Label wont take the Value. The Primefaces Showcase Example has no blank first entry, so I can´t reproduce this there.

Things we found out so far:
We added console.log in Selectonemenu.js at the functions which trigger the selected value of the list and it turned out, that the value is being removed after added.

**1.**
bindItemEvents:function () {
    	        var a = this; 
    	        this.items.filter(":not(.ui-state-disabled)").on("mouseover.selectonemenu", function () {
    	            var b = $(this); 
    	            if ( ! b.hasClass("ui-state-highlight")) {
    	                $(this).addClass("ui-state-hover"); 
    	            }
    	        }).on("mouseout.selectonemenu", function () {
    	            $(this).removeClass("ui-state-hover");
    	        }).on("click.selectonemenu", function () {
    	            **console.log("a first", a);**
    	        	a.revert();
    	            a.selectItem($(this));
    	            a.changeAriaValue($(this));
    	        }); 
    	    },
**2.**
 revert:function () {
    	        if (this.cfg.editable && this.customInput) {
    	            this.setLabel(this.customInputVal); 
    	            **console.log("revert", this.customInputVal);**
    	            this.items.filter(".ui-state-active").removeClass("ui-state-active"); 
    	            this.items.eq(0).addClass("ui-state-active"); 
    	        }
    	        else {
    	            this.highlightItem(this.items.eq(this.preShowValue.index())); 
    	        }
    	    },

**3.**
highlightItem:function (a) {
    	        this.items.filter(".ui-state-highlight").removeClass("ui-state-highlight"); 
    	       **console.log("highlightItem", a);**
    	        if (a.length > 0) {
    	            a.addClass("ui-state-highlight"); 
    	            this.setLabel(a.data("label")); 
    	        }
    	    },
**4.**
 setLabel:function (c) {
    	    	**console.log("setlabel", c);**
    	        var b = this.getLabelToDisplay(c); 
    	        if (this.cfg.editable) {
    	            if (c === "&nbsp;") {
    	                this.label.val(""); 
    	            }
    	            else {
    	                this.label.val(b); 
    	            }
    	        }
              ....}

**5.**
getLabelToDisplay:function (a) {
    	        **console.log("a", a);**
    	    	if (this.cfg.labelTemplate && a !== "&nbsp;") {
    	            return this.cfg.labelTemplate.replace("{0}", a); 
    	        }
    	        return a; 
    	    },

Console Output: (I selected the first entry "divers"

**a first** c {_super: undefined, jqId: "#selbstregistrierung\:persondata\:gender", cfg: {…}, id: "selbstregistrierung:persondata:gender",

**highlightItem** r.fn.init [li#selbstregistrierung:persondata:gender_0
**setlabel**
**a** 
**highlightItem** r.fn.init [li#selbstregistrierung:persondata:gender_1
**setlabel divers**
**a divers**
**highlightItem** r.fn.init [li#selbstregistrierung:persondata:gender_0
**setlabel**
**a** 
.. 

## 5) Sample XHTML

Xhtml:

<his:selectOneMenu id="gender" value="#{person.genderId}" p:autocomplete="sex"
   disabled="#{flowScope.seStData}" styleClass="dropdown_33" layout="pageDirection">
		<his:selectItems value="#{valueServiceController.allGenders}" 
			var="item" itemLabel="#{item.defaulttext}" itemValue="#{item.id}" />
</his:selectOneMenu>

Rendered Html:

<div id="selbstregistrierung:persondata:gender" class="ui-selectonemenu ui-widget ui-state-default ui-corner-all dropdown_33 required" role="listbox" aria-haspopup="listbox" aria-expanded="false" autocomplete="sex" title="&nbsp;" aria-owns="selbstregistrierung:persondata:gender_0 selbstregistrierung:persondata:gender_1 selbstregistrierung:persondata:gender_2 selbstregistrierung:persondata:gender_3 selbstregistrierung:persondata:gender_4">
	<div class="ui-helper-hidden-accessible">
		<input id="selbstregistrierung:persondata:gender_focus" name="selbstregistrierung:persondata:gender_focus" type="text" autocomplete="off" aria-expanded="false" aria-labelledby="selbstregistrierung:persondata:gender_focusLabel" aria-autocomplete="list" aria-describedby="selbstregistrierung:persondata:gender_0" aria-disabled="false" aria-activedescendant="" readonly="readonly">
		</div>
		<div class="ui-helper-hidden-accessible">
			<select id="selbstregistrierung:persondata:gender_input" name="selbstregistrierung:persondata:gender_input" tabindex="-1" aria-hidden="true">
				<option value="">&nbsp;</option>
				<option value="5">divers</option>
				<option value="1">männlich</option>
				<option value="3">undefiniert / k.A.</option>
				<option value="2">weiblich</option>
			</select>
		</div>
		<label id="selbstregistrierung:persondata:gender_label" class="ui-selectonemenu-label ui-inputfield ui-corner-all">&nbsp;</label>
		<div class="ui-selectonemenu-trigger ui-state-default ui-corner-right" tabindex="-1" style="left: 348.098px; top: 1767.55px;">
			<span></span>
		</div>
		<div id="selbstregistrierung:persondata:gender_panel" class="ui-selectonemenu-panel ui-widget ui-widget-content ui-corner-all ui-helper-hidden ui-shadow ui-input-overlay">
			<div class="ui-selectonemenu-items-wrapper" style="max-height:200px">
				<ul id="selbstregistrierung:persondata:gender_items" class="ui-selectonemenu-items ui-selectonemenu-list ui-widget-content ui-widget ui-corner-all ui-helper-reset" role="listbox" aria-activedescendant="selbstregistrierung:persondata:gender_0">
					<li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-highlight" data-label="&nbsp;" tabindex="-1" role="option" title="&nbsp;" id="selbstregistrierung:persondata:gender_0">&nbsp;</li>
					<li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="divers" tabindex="-1" role="option" title="divers" id="selbstregistrierung:persondata:gender_1">divers</li>
					<li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="männlich" tabindex="-1" role="option" title="männlich" id="selbstregistrierung:persondata:gender_2">männlich</li>
					<li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="undefiniert / k.A." tabindex="-1" role="option" title="undefiniert / k.A." id="selbstregistrierung:persondata:gender_3">undefiniert / k.A.</li>
					<li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="weiblich" tabindex="-1" role="option" title="weiblich" id="selbstregistrierung:persondata:gender_4">weiblich</li>
				</ul>
			</div>
		</div>
	</div>

..

## 6) Sample bean

..

**Comment by tandraschko** [comment] 2020-04-16 12:03
So you say it's working fine on PrimeFaces8?

**Comment by HISeG-ME** [comment] 2020-04-16 12:15
Actually I can´t reproduce this, since we´re working with 6.2 
If the Showcase Example of SelectOneMenu has a blank first entry, I can verify this.

**Comment by melloware** [comment] 2020-04-16 12:25
@HISeG-ME Attached is a small reproducer.
[pf-5799.zip](https://github.com/primefaces/primefaces/files/4486990/pf-5799.zip)

Run `mvn clean jetty:run-exploded` and navigate to http://localhost:8080/primefaces-test/test.xhtml

It is using PF8 Advanced Theme example and I put a blank first line item.

**Comment by tandraschko** [comment] 2020-04-16 12:35
JFYI: the problem is that 6.2 isnt maintained anymore. So if it works fine on 8.0, we would just close it

**Comment by melloware** [comment] 2020-04-16 22:17
@HISeG-ME that sample app i provided above what so you could figure out if it is still an issue in 8.0

**Comment by melloware** [comment] 2020-04-21 15:24
@HISeG-ME I will close for now. We can reopen if you can verify its an issue on 8.0

**Closed as completed by melloware** 2020-04-21 15:24 UTC
Labels: needs further work, browser-specific
