### ISSUE TITLE
Dialog state (maximized/minimized) buggy across AJAX updates

### ISSUE THREAD

**Issue by Adam-1** [primefaces/primefaces#3039] opened 2017-12-02 22:23 UTC
When a dialog is closed while in minimized/maximized state and then updated (via AJAX) its state become corrupted somehow.

If it was closed in maximized state, when it's shown again it's in normal size but it "thinks" it's still in maximized state so 2 clicks on the maximize button are required in order to maximize it.

If, on the other hand, it was closed while in minimized state, when it's shown again it appears behind the overlay (in case of overlay dialog) which makes the page unusable.

## 1) Environment
Tested on
Tomcat 7
Primfaces 6.1
Chrome

## 2) Expected behavior

The dialog should show in the former state, or at least be consistent (i.e. not show in regular state but thinking it's maximized and not blocking the page)

## 3) Actual behavior

- If the dialog was maximized before closing, two clicks on the maximize button are needed in order to maximize it

- If the dialog was minimized before closing and is modal, it's shown behind the overlay, making the page unusable

## 4) Steps to reproduce

1. Open a dialog
2. Maximize/minimize it
3. Close it
4. Fire any ajax that will cause the dialog to be updated
5. Open the dialog again

## 5) Sample XHTML

https://github.com/Adam-1/primefaces-test/blob/master/src/main/webapp/dialogTest.xhtml

## 6) Sample bean

N/A

**Comment by Adam-1** [comment] 2017-12-02 23:03
Added PR #3040 
(just my 2 cents, there may be better ways to handle it)

**Comment by jxmai** [comment] 2017-12-05 20:23
First of all, I could confirm this bug.  

about the PR: @Adam-1 

The changes are all over the place, could you explain the intention in details (your thought) that can help us see through the suggestion.

**Comment by Adam-1** [comment] 2017-12-05 20:42
@jxmai 
Well, since the problem arise when the dialog DOM is updated but the **client** state isn't, I thought I could restore the maximize/minimize state when the dialog is updated.

Most of the code is just method extraction of the actual maximizing/minimizing without all the checkings and event triggering.

When I detect in the "refresh" method that there was a state (and was probably overridden by the DOM update) I'm using the specific function (max/min) to restore the state of the dialog as before the update.

The minimize bug needed some workaround because it's transferring the dialog to the dock, and DOM updates could even cause duplicate dialogs in the page (one from the update in the original place, the other in the dock)

**Comment by melloware** [comment] 2017-12-07 00:35
@Adam-1 can you review this fix it definitely looks related to yours but not sure if it does as much as yours does.  https://github.com/primefaces/primefaces/issues/3050

**Comment by mertsincan** [comment] 2017-12-07 06:11
Duplicate of #3050

**Comment by mertsincan** [comment] 2017-12-07 06:15
This issue is fixed for 6.1.10 and 6.2. Please create a new issue for max/min state issue.

**Comment by jxmai** [comment] 2017-12-07 23:37
@mertsincan @melloware This issue is only partially duplicate of #3050, I can confirm the maximize state has been resolved, but not the modal block after minimizing 

Please try @Adam-1 's sample. It is straightforward to replicate which is one of the good samples I have seen. We should not just close this issue without trying to see what went wrong. Not to mention that @Adam-1 also gave a suggested  PR 

**This issue was raised before #3050, there is no reason to ask @Adam-1**  to raise another new ticket since the bug is still valid as the description mentioned in this ticket.

```xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<f:view contentType="text/html">
	<h:head>
	</h:head>
	<h:body>

		<h:form id="mainForm">

			<p:commandButton value="Modal" type="button"
				onclick="PF('dlg2').show();" />

			<p:commandButton value="test" process="@this" update="dialog2" />

			<p:dialog id="dialog2" header="Modal Dialog" widgetVar="dlg2"
				modal="true" minimizable="true" maximizable="true" height="100">
				<h:outputText value="This is a Modal Dialog." />
			</p:dialog>

		</h:form>

	</h:body>
</f:view>

</html>
```

1. open dialog
![image](https://user-images.githubusercontent.com/10467831/33743947-990359f8-db74-11e7-8f28-02085c63117d.png)


2. minimize:


![image](https://user-images.githubusercontent.com/10467831/33743993-b1f7e154-db74-11e7-91e3-3b28cf37c4f8.png)


3. close dialog

4. click `Test`

![image](https://user-images.githubusercontent.com/10467831/33744030-dbd6dde0-db74-11e7-959c-ddbeda5a0eea.png)

5. click `modal` again

![image](https://user-images.githubusercontent.com/10467831/33744040-eb5f43f6-db74-11e7-8230-480aad96a424.png)


Please reopen this ticket. and @Adam-1  it would be nice if you could modify this ticket a bit only to mention the bug after minimizing.

**Comment by melloware** [comment] 2017-12-07 23:53
@jxmai I agree this should be reopened.

**Comment by Adam-1** [comment] 2017-12-08 12:14
@jxmai The minimize state problem (modal) is mentioned in the bug description. (Unless you mean to change this ticket to be about minimize+modal bug **only**?)

**Closed as completed** 2017-12-08 14:05 UTC
Labels: :lady_beetle: defect, 6.1.11
