### ISSUE TITLE
Picklist: transfer event not fired with required=true on last target item

### ISSUE THREAD

**Issue by PlassJ** [primefaces/primefaces#5779] opened 2020-04-08 07:37 UTC
## 1) Environment
- PrimeFaces version: 8.0
- Does it work on the newest released PrimeFaces version? No
- Application server + version: Wildfly 16
- Affected browsers: all

## 2) Expected behavior
- Transfer event should be fired.
## 3) Actual behavior
- Transfer event won't be fired.
## 4) Steps to reproduce
Create a Picklist with `required="true"` then remove the last item of the target list.
This is the moment where the event should be fired, but the event is not fired.

If you remove the `required="true"` from the picklist, the event will be fired.

## 5) Sample XHTML

```xml
<p:pickList id="PojoPickList" value="#{pickListView.themes}" var="theme" effect="bounce"
                itemValue="#{theme}" itemLabel="#{theme.displayName}" showSourceControls="true" showTargetControls="true" showCheckbox="true"
                showSourceFilter="true" showTargetFilter="true" filterMatchMode="contains" converter="#{themeConverter}" required="true" >
 
        <f:facet name="sourceCaption">Available</f:facet>
        <f:facet name="targetCaption">Starting</f:facet>
 
        <p:ajax event="transfer" listener="#{pickListView.onTransfer}" update="msg" />
        <p:ajax event="select" listener="#{pickListView.onSelect}" update="msg"/>
        <p:ajax event="unselect" listener="#{pickListView.onUnselect}" update="msg"/>
        <p:ajax event="reorder" listener="#{pickListView.onReorder}" update="msg"/>
 
        <p:column style="width:15%">
            <h:graphicImage name="showcase/images/themeswitcher/themeswitcher-#{theme.name}.png" alt="#{theme.name}" styleClass="ui-theme"/>
        </p:column>
 
        <p:column style="width:85%;">
            <h:outputText value="#{theme.displayName}" />
        </p:column>
    </p:pickList>
```

## 6) Sample bean
PickListView from showcase. https://www.primefaces.org/showcase/ui/data/pickList.xhtml

**Comment by kukel** [comment] 2020-04-08 09:07
please improve your title. It is in my opinion too broad for the issue you descirbe

**Comment by melloware** [comment] 2020-04-08 11:34
I can't reproduce.  I just did exactly what you said and added `required="true"` and then transferred the last item in the list and the transfer event fired.

![image](https://user-images.githubusercontent.com/4399574/78779731-691a1500-796b-11ea-975e-8795abff5fca.png)

Am I not doing the same thing you are doing?

**Comment by melloware** [comment] 2020-04-08 11:37
OK I re-read your steps its transfer last item of `target` list I was doing `source` list and now I get this.

![image](https://user-images.githubusercontent.com/4399574/78779873-ba2a0900-796b-11ea-99ea-0b1c05cb5f14.png)

**Comment by melloware** [comment] 2020-04-08 11:48
It even happens if you just load the page and try and re-order elements in the source list.  It is because the way the picklist works it submits all of its source and target elements to the backend to be bound to the backing bean lists.  When the target is empty this component is technically failing the required=true check.   I am not sure if there is an easy fix for this.

**Comment by tandraschko** [comment] 2020-05-19 08:38
This is how JSF validation works.
I think we can make it work but its more like an enhancement as it was never implemented to support it.

Sponsoring via PrimeFaces PRO would be great, it think it's not an easy task.

**Comment by melloware** [comment] 2024-01-07 15:25
Replaced by #11249

**Closed as completed by melloware** 2024-01-07 15:25 UTC
Labels: workaround, Resolution: By Design

**Comment by bsanders1979** [comment] 2024-05-16 02:58
Simple fix here... You're gonna love it...
```
required="#{component.clientId != param['javax.faces.source']}"
```

**Comment by melloware** [comment] 2024-05-16 11:15
@bsanders1979 i love it!  @tandraschko do you think we can do this in the component?  this makes sense to me that ONLY the target should be checked for required not the "source" list?

**Comment by melloware** [comment] 2024-05-16 15:13
OK no problem we have a workaround provided.
