### ISSUE TITLE
DataTable: frozenColumns + draggableColumns + rendered content gets out of sync

### ISSUE THREAD

**Issue by wlhUser** [primefaces/primefaces#11023] opened 2023-11-23 19:04 UTC
### Describe the bug

In DataTable with frozenColumns, draggableColumns and not rendered columns (rendered="false"), table header and content of table gets out of sync. Content is shifted 1 or 2 cols compared to header. This does not happen immediately when displaying the page, but after the 1st ajax update.

Example with 2 Data tables. The 1st has no not rendered columns while the 2nd has one. Otherwise the tables are identical.

Initial page:
![InitialPage](https://github.com/primefaces/primefaces/assets/47218021/01a20d41-95a8-4847-8df6-dbbbdb39b3d0)

Now scroll down in both tables about 30%, and press the 'Update' button.
The 1st table is still ok, while in the 2nd header and data are no longer in sync.
![PageAfterUpdate](https://github.com/primefaces/primefaces/assets/47218021/5d979f72-89ca-4e4e-b12f-c7ba5fc474e2)
 

### Reproducer

[pf-11023.zip](https://github.com/primefaces/primefaces/files/13475960/pf-11023.zip)

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.6

### JSF implementation

Mojarra

### JSF version

4.0.4 (Wildfly30)

### Java version

17

### Browser(s)

All

**Comment by melloware** [comment] 2023-11-23 21:05
Duplicate of: https://github.com/primefaces/primefaces/issues/9976  But I will close that one as this one includes a reproducer.

**Comment by melloware** [comment] 2023-11-23 21:05
@wlhUser can you try the workaround in that ticket?

**Comment by wlhUser** [comment] 2023-11-24 07:30
@melloware to be honest, I do not fully understand the other ticket. I think the problem described in that ticket are related to dragging columns. In my case the problem happens without any dragging. The workaround I use in general is to reduce the frozen columns to 1 or prevent using 'rendered="false"' with columns.

I also tried debugging into the PF Code, but I'm not that deep into it to propose solutions. I could see the in the DataTable Object, all  columns are present, independently of being rendered or not, which is OK. But at some point the ordering of the columns gets confused. When debugging in ColumnAware.collectCollumns(), and set a breakpoint in columns.sort(c1, c2), you can see that columns which are not rendered have a displayPriority of 0, which causes them to be shifted to the top of the column list, and in the frozen area.

**Comment by melloware** [comment] 2023-11-24 13:25
I wonder if columns that are NOT rendered should get a priority of 999?

**Comment by wlhUser** [comment] 2023-11-24 18:18
I'm not sure if the priority of NOT rendered columns should be changed, as there might be actions which changes their 'render' attribute, and than they might be shifted to a position which is not desired.  
But maybe the columns.sort() function could shift them to the end of the columns list, without affecting their prio. However, this is only a rough guess. I did not have the chance to test this approach yet.

**Comment by melloware** [comment] 2023-11-27 15:00
@wlhUser its not Draggable Columns that is the issue its `virtualScroll="true"`

**Comment by melloware** [comment] 2024-01-04 16:08
Column order on first render:

```
form:testTable3_frozenThead Start:= 0 End:= 2
Col1
Col2
form:testTable3_scrollableThead Start:= 2 End:= 5
Col3
Col4
Col5
```

Column Order on Update:
```
form:testTable3_frozenThead Start:= 0 End:= 2
Col1
Col4
form:testTable3_scrollableThead Start:= 2 End:= 5
Col2
Col3
Col5
```

Notice Column4 is 2nd that is because in `UITable.decodeColumnDisplayOrderState` it is setting them all to 0 then decoding the UI columns.

```java
Map<String, ColumnMeta> columMeta = getColumnMeta();
columMeta.values().forEach(s -> s.setDisplayPriority(0));
```

However on first update with draggable columns it only sends the 4 visible columns from the client to decode column order which puts the order wrong which puts FrozenColumns=2 now incorrect.

```js
{
	"form:testTable3_columnOrder": "form:testTable3:j_idt10,form:testTable3:j_idt12,form:testTable3:j_idt14,form:testTable3:j_idt18",
	"javax.faces.ViewState": "-7232794966269752203:-2061201527638343433"
}
```

**Closed as completed** 2024-01-08 16:55 UTC
Labels: :lady_beetle: defect
