### ISSUE TITLE
DataTable: rowEdit+partialSubmit could only post the edited row instead whole dataTable

### ISSUE THREAD

**Issue by arunvc** [primefaces/primefaces#2008] opened 2017-01-11 06:33 UTC
## 1) Environment
http://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml

## 2) Expected behavior
process="@this" partialSubmit="true" 
post the datatable single row than all the rows

## 3) Actual behavior
post the full datatable rows than edited row

## 4) Steps to reproduce
try showcase example by adding process="@this" partialSubmit="true"

<p:ajax event="rowEdit" process="@this" partialSubmit="true"    listener="#{bean.onEdit}" update="dataTable" />

![image](https://cloud.githubusercontent.com/assets/9069988/21837950/448f73f8-d7f5-11e6-982c-5375688abcb1.png)

**Comment by tandraschko** [comment] 2017-07-14 09:40
As the source of the event still is the datatable, @this contains "everything" of the datatable.
So this works correctly but surely it can be improved.

**Comment by arunvc** [comment] 2019-10-23 07:46
Related issue - 
We have datatable with editable inputs in all rows and column 
A column with autocomple and inputNumber with ajax calls,
when an ajax call is made from these control the whole datatable values are posted with the request, which is not necessary.

**Comment by melloware** [comment] 2019-10-23 11:46
@arunvc That is the way the Datatable works it submits the whole form.  if you want cell by cell submission to not submit the whole table that is why the PrimeFaces Extensions Sheet component exists: https://www.primefaces.org/showcase-ext/sections/sheet/basicUsage.jsf

It submits cell by cell only the data you have changed on the sheet.

**Comment by melloware** [comment] 2020-10-26 20:00
Duplicate of: #3571

**Closed as completed** 2020-10-26 20:01 UTC
Labels: Resolution: Duplicate, new feature
