### ISSUE TITLE
Datatable: renders empty header row when nested in <p:column> element

### ISSUE THREAD

**Issue by HeavyMetalPirate** [primefaces/primefaces#3476] opened 2018-03-12 13:55 UTC
## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? Works with latest maven build
- Does it work on the newest sources in GitHub? n/a
- Application server + version: Tomcat 8.5.5
- Affected browsers: Mozilla Firefox, any recent versions; Google Chrome, any recent versions

## 2) Expected behavior
When nesting a datatable with a header row (i.e. expanding rowgroups, https://www.primefaces.org/showcase/ui/data/datatable/rowGroup.xhtml) in a column element, the header row should be displayed once.

## 3) Actual behavior
The actual behavior reflects this issue: https://github.com/primefaces/primefaces/issues/2206
The key difference here is that in the current maven build only header rows are affected by this issue. Normal cells are rendered as intended.

See also sample screenshot from our test system, with actual data obfuscated: ![rowheader issue](https://user-images.githubusercontent.com/37298940/37287495-385703da-2605-11e8-8968-40952dd36196.png)

## 4) Steps to reproduce
Wrap rowGroup.xhtml example with a panelGrid, row and column.

## 5) Sample XHTML
Taken from the rowGroup.xhtml example. Basically wraps the first table with a panelGrid, row and column tag.

```html
<p:panelGrid>
	<p:row>
		<p:column>
			<p:dataTable var="car" value="#{dtRowGroupView.cars}"
				sortBy="#{car.brand}" expandableRowGroups="true">
				<p:headerRow>
					<p:column colspan="3">
						<h:outputText value="#{car.brand}" />
					</p:column>
				</p:headerRow>
				<p:column headerText="Year">
					<h:outputText value="#{car.year}" />
				</p:column>
				<p:column headerText="Color">
					<h:outputText value="#{car.color}" />
				</p:column>
				<p:column headerText="Id">
					<h:outputText value="#{car.id}" />
				</p:column>
				<p:summaryRow>
					<p:column colspan="2" style="text-align:right">
						<h:outputText value="Total:" />
					</p:column>
					<p:column>
						<h:outputText value="#{dtRowGroupView.randomPrice}">
							<f:convertNumber type="currency" currencySymbol="$" />
						</h:outputText>
					</p:column>
				</p:summaryRow>
			</p:dataTable>
		</p:column>
	</p:row>
</p:panelGrid>
```

## 6) Sample bean
n/a

**Comment by tandraschko** [comment] 2020-12-15 12:50
JFYI if anyone would like to check it in detail: it does NOT happen without p:panelGrid/p:row around the DataTable.

**Comment by melloware** [comment] 2020-12-15 20:50
Yep I have no idea what's wrong but somehow the panelGrid styles are interfering with the DataTable styles becuase its TR/TD inside TR/TD.  I stared at it for a while but I can't figure out exactly where the problem is.

**Comment by melloware** [comment] 2022-05-06 18:53
I know why this is.  This is just like #2206 except the HeaderRow is just rendering its contents.

```java
    protected void encodeHeaderRow(FacesContext context, DataTable table, HeaderRow headerRow) throws IOException {
        headerRow.encodeAll(context);
    }
```

EncodeAll is just rendering its components and one of those is <p:column> so its rendering another `<TD>` which throws everything off.    Not sure there is any good way to fix this other than switch your PanelGrid to `<div>` layout with PrimeFlex.

**Comment by melloware** [comment] 2022-05-07 15:32
Going to close this now as WontFix

**Closed as completed by melloware** 2022-05-07 15:32 UTC
Labels: Resolution:  Wontfix, discussion
