### ISSUE TITLE
columnToggler confict with pagination function

### ISSUE THREAD

**Issue by luongdangdung** [primefaces/primefaces#217] opened 2015-05-02 07:12 UTC
I have datatable with 3 columns.
**Problem**
By default I want to display 2 columns and hide 1 column (last column in this sample)

I use columnToggler to mange show or hide last column. If I use pagination feature, the bug appear as follow steps:
1. I click on columnToggler to view last column (everything will be ok)
2.  I click on page 2 of datatable, data of lastcolumn will disappear. (maybe some issues about javascript and backing bean, i guest that)

**Expectation**
When I use columnToggler to show  any column, data of column must be appear when I show any page of datatable.

**Sample code:**

``` html
                <p:dataTable id="dataTable" var="row"
                    value="#{datatestBean.lazyEntity}" paginator="true"
                    sortOrder="UNSORTED" rows="10"
                    paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                    rowsPerPageTemplate="5,10,15" selectionMode="single"
                    rowKey="#{row.id}" selection="#{datatestBean.entityRow}"
                    lazy="true" filterEvent="enter">

                    <p:ajax event="rowSelect" listener="#{datatestBean.selectRow()}"
                        update=":form:panel" />


                    <f:facet name="header">  
                               #{msgs.mn_system_user}
                               <p:commandButton id="toggler"
                            type="button" styleClass="colSelection" icon="ui-icon-calculator" />
                        <p:columnToggler datasource="dataTable" trigger="toggler" />
                    </f:facet>

                    <p:column headerText="#{msgs.system_user_username}">
                        <h:outputText value="#{row.id}" />
                    </p:column>

                    <p:column headerText="#{msgs.system_user_tenantid}"
                        filterBy="#{row.tenantid}" filterMatchMode="contains"
                        sortBy="#{row.tenantid}">
                        <h:outputText value="#{row.tenantid}" />
                    </p:column>

                    <p:column headerText="#{msgs.system_user_playerid}" visible="false"
                        filterBy="#{row.playerid}" filterMatchMode="contains"
                        sortBy="#{row.playerid}">
                        <h:outputText value="#{row.playerid}" />
                    </p:column>

                </p:dataTable>
```

**Comment by cagataycivici** [comment] 2015-05-02 07:57
Duplicate of #96, please do a search before creating new tickets.

**Closed as completed by cagataycivici** 2015-05-02 07:57 UTC
