### ISSUE TITLE
Scrollable dataTable: Header and Body misaligned

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#811] opened 2015-10-21 15:24 UTC
Tested with PrimeFaces 5.2 and 5.3.

Setting `scrollable=true` for a `p:dataTable` may cause a misalignment in the column-width of the header and the column-width of the scrollable body. This happens, if a cell in the body has a bigger non-breakable content than the header (e.g. empty header, but an image/icon in the body).

The most simple solution would be to first clone the header and then calculate the width based on the cloned one. As the cloned header is attached to the table of the scrollable body, it will represent the correct width.

Currently you first fix the width and then clone the header.

**Comment by mertsincan** [comment] 2015-11-09 08:19
Can you please attach a sample test.xhtml and testView.java for us to replicate?

**Comment by fanste** [comment] 2015-11-12 07:48
I will try to prepare an example. But as I'm short of time, this may take a bit.

**Comment by mtbadi39** [comment] 2016-01-17 11:15
Possible duplicate of [#971](https://github.com/primefaces/primefaces/issues/971)

**Comment by hink084** [comment] 2016-02-10 15:47
[Issue811.zip](https://github.com/primefaces/primefaces/files/125032/Issue811.zip)

I was able to create a misalignment but differently than @fanste reported above.
Also I was only able to create the misalignment in Firefox.

Now before I continue on...it could be that by making these adjustments that it is expected to cause a misalignment...I don't know.

I created the misalignment by adjusting the CSS line-height property and/or adjusting the underlying HTML Table column widths.  I've attached a ZIP file containing an example .JAVA and two example .XHTML - issue811a, issue811b.  The first example adjusts the line-height property; the second adjusts the column widths.  I think the odds of misalignment are slim (especially with the first example), but the possibility does exist.

I'm using Primefaces 5.3, Firefox 44.0.1, Glassfish 4.1, Mojarra 2.2.12
I was also using the Primefaces Bootstrap theme in my web.xml via:

```
<context-param>
    <param-name>primefaces.THEME</param-name>
    <param-value>bootstrap</param-value>
</context-param>
```

issue811a.xhtml as supplied:

If you look at the PrimeFaces datatable.js file, the alignScrollBody() function adjusts the margin-right CSS properties causing the misalignment.  However, digging deeper you'll see that "this.bodyTable.outerHeight() > this.scrollBody.outerHeight()" by 1px in the hasVerticalOverflow() function.  Maybe this is a Firefox/JS/JQuery issue?  

JavaScript Debug via Firebug:

```
PF('MyDataTable').hasVerticalOverflow();
true
PF('MyDataTable').bodyTable.outerHeight();
263
PF('MyDataTable').scrollBody.outerHeight();
262
PF('MyDataTable').alignScrollBody();
No Effect (Obviously)
```

issue811b.xhtml as supplied:

This issue is a little different as you look at the JavaScript Debug right off the bat you'll see:

```
PF('MyDataTable').hasVerticalOverflow();
false
PF('MyDataTable').bodyTable.outerHeight();
434
PF('MyDataTable').scrollBody.outerHeight();
500
PF('MyDataTable').alignScrollBody();
Resets margin-right property to 0px for Table Header/Footer.
```

It appears the issue here is during the setup process somewhere.  I think this is somehow caused by the wrapping text and width of the 2nd column.

**Comment by chuckbinder** [comment] 2018-01-18 16:27
We run into the same issue.  We would love to use the scrollbar feature on DataTable but the column headings never align.  

For us we never define widths.  We allow the columns to be dynamic in width.  We do however have style classes that don't allow wrapping applied to the column.  So if you setup a DataTable that has lots of data and paginated with large amounts of data in lets say column one and two and add a style to force the cell to not wrap you will see the issue.

**Comment by svrolanski** [comment] 2018-08-23 14:07
Duplicate of #3492, old bug, there is workaround in the mentioned issue

**Comment by melloware** [comment] 2019-11-19 14:07
Closing issue as duplicate with workaround

**Closed as completed by melloware** 2019-11-19 14:07 UTC
Labels: Resolution: Duplicate
