### ISSUE TITLE
PickList: Multiple Entries

### ISSUE THREAD

**Issue by e-reznik** [primefaces/primefaces#5309] opened 2019-11-06 09:50 UTC
## 1) Environment
- PrimeFaces version: **7.0**
- Application server + version: **Payara 5**
- Affected browsers: **Firefox**

## 2) Expected behavior
I want to have some entries multiple times in my right list. So the entries shouldn't disappear from the left list.
![grafik](https://user-images.githubusercontent.com/55981254/68288093-15399600-0084-11ea-8f86-186a0d6a0670.png)

## 3) Actual behavior
When you add (i.e. transfer) one element from left to right, it appears at the right list, but disappears from the left list
![grafik](https://user-images.githubusercontent.com/55981254/68288152-2c788380-0084-11ea-8cf1-eda08cd1fb74.png)

## Possible Solution

PickList has a method [onTransfer](https://www.primefaces.org/docs/vdl/7.0/primefaces-p/pickList.html):

> Client side callback to execute when an item is transferred from one list to another.

So I could check, which element was transferred (deleted from the left list) and put it there again. But maybe there is a more elegant way.

**Comment by melloware** [comment] 2019-11-06 12:19
Isn't this a duplicate of this: https://github.com/primefaces/primefaces/issues/2858

**Comment by tandraschko** [comment] 2019-11-06 13:48
I think #2858 can be a part of this ticket.
But this ticket also allows duplicate of the same items in the target and source.

I think we can close #2858 in favor of this.

**Comment by melloware** [comment] 2024-01-07 15:26
Replaced by https://github.com/primefaces/primefaces/issues/11249

**Closed as completed by melloware** 2024-01-07 15:26 UTC
Labels: new feature, sponsoring required
