### ISSUE TITLE
FileUpload: file name encoding

### ISSUE THREAD

**Issue by crocimi** [primefaces/primefaces#10436] opened 2023-08-03 08:08 UTC
### Describe the bug

File name seem not be handled correctly by fileUpload.
Example:
über2.jpeg -> über2.jpeg (OK)
Über.jpeg -> �?ber.jpeg (NOT OK)

The latin capital letter U with diaeresis is not encoded correctly so we can't retrieve the original file name

### Reproducer

1. Drag&Drop attached files
2. Press "Upload" Button
3. Look at file name in the displayed messages or in the console.

### Expected behavior

Both file names should be encoded correctly.
[fileupload.zip](https://github.com/primefaces/primefaces/files/12248396/fileupload.zip)

### PrimeFaces edition

Community

### PrimeFaces version

13.0.0

### Theme

Babylon

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11.0.16

**Comment by tandraschko** [comment] 2023-08-03 08:09
does it work on 13.0.0?

**Comment by crocimi** [comment] 2023-08-03 08:44
No, same issue

![2023-08-03_10-42-00](https://github.com/primefaces/primefaces/assets/13310149/a58a5f1d-a65d-44df-8836-857c4ce37435)

**Comment by melloware** [comment] 2023-08-03 11:14
@crocimi do you mind attaching that file here in a zip so I can test with your exact file please?

**Comment by crocimi** [comment] 2023-08-03 11:27
@melloware the files are part of fileupload.zip package, you find it in the description above. I'm trying to analyse the flow, the encoded bytes seems correct, maybe I'm doing the conversion to utf-8 String in a wrong way

Üb
[Ü        , b]
[-61, -100, 98]
[0xc3,  0x9c, 0x62]

üb
[ü        , b]
[-61, -68, 98]
[0xc3,  0xbc, 0x62]

**Comment by melloware** [comment] 2023-08-03 11:37
OK great let me test.

**Comment by melloware** [comment] 2023-08-03 12:17
I think it might be messed up in the JS code as when I press F12 and watch the network traffic this is what it posts which does not look right to me?

![image](https://github.com/primefaces/primefaces/assets/4399574/acbbd291-ebd1-40f1-b34f-c9ce6db18cda)

**Comment by melloware** [comment] 2023-08-03 12:40
@Rapster i wonder if its something we need to patch in BlueImp: https://stackoverflow.com/questions/29864327/jquery-file-upload-blueimp-filenames-with-special-characters

**Comment by melloware** [comment] 2023-08-03 13:14
Reproducer: 
[pf-10436.zip](https://github.com/primefaces/primefaces/files/12251183/pf-10436.zip)

**Comment by Rapster** [comment] 2023-08-03 21:54
I can have a look in 2 weeks

**Comment by Rapster** [comment] 2023-08-20 17:26
Seems to be fixed by https://github.com/primefaces/primefaces/pull/10272 My guess is that `Part#getSubmittedFileName` does the right job, or something has changed on client side because the encoding seems to be okay when I look at network traffic

**Comment by melloware** [comment] 2023-08-20 22:12
Ok I will try it with 14.0.0 Snapshot tomorrow and report back.

**Comment by melloware** [comment] 2023-08-21 14:47
@Rapster I am still seeing the issue with 14.0.0-SNAPSHOT.

Console:
```
filename: ?ber.jpeg
```

![image](https://github.com/primefaces/primefaces/assets/4399574/0b7f1810-33e3-4ed9-8f73-d568c63b7b50)

**Comment by Rapster** [comment] 2023-08-21 15:15
Using chrome?

**Comment by melloware** [comment] 2023-08-21 15:17
actually that was Firefox let me try Chrome.

**Closed as completed** 2023-08-21 16:22 UTC
Labels: :lady_beetle: defect
