### ISSUE TITLE
DatePicker: Popups Fail to Close When Selecting a Field with an Input Mask

### ISSUE THREAD

**Issue by imoehldf** [primefaces/primefaces#8323] opened 2022-01-24 22:22 UTC
**Describe the defect**
When clicking in a DatePicker field, you'll get a popup to select a date. If you then select a different input field with a mask (i.e. Input Mask or a DatePicker with mask=true), the initial DatePicker popup won't close. 

This itself isn't that big of an issue on its own, but it's a bigger issue with dialogs. If you select a date picker component, then an InputMask field (in this case, must be InputMask), the DatePicker popup won't close, and will be behind the dialog component. Then, when you try to select the initial DatePicker field again, the popup will still be behind the dialog. This can be extremely confusing for users on bigger dialogs, when they can't see that the DatePicker popup is behind the dialog.

**Reproducer**
https://github.com/imoehldf/primefaces-test-datepicker-popup-bug

**Environment:**
 - PF Version: 11.0
 - JSF + version: MyFaces 2.2.12
 - Affected browsers: ALL

**To Reproduce**
1. Open the dialog
2. Click on the "Start Date" DatePicker input
3. Click on the Phone Number input
4. You'll see the DatePicker's popup is now behind the dialog. When selecting the DatePicker input again, the popup is still behind the dialog.

**Expected behavior**
When selecting a field with a mask after selecting a DatePicker field, the DatePicker popup should close.

**Example XHTML**
```html
    <h:body>

        <h1>Mask Test</h1>
        <h:form id="frmTest">
            <p:outputLabel for="phone" value="Phone Number: " />			
			<p:inputMask id="phone" label="Phone Number" value="#{testView.string}" 
				mask="(999) 999-9999 [x99999]" maxlength="14" />
		
			<p:outputLabel for="startDate" value="Start Date: "/>			
       		<p:datePicker id="startDate" value="#{testView.startDate}"
	        	pattern="MM/dd/yyyy" mask="true">
	        </p:datePicker>

			<p:outputLabel for="endDate" value="End Date: " />			
       		<p:datePicker id="endDate" value="#{testView.endDate}"
	        			pattern="MM/dd/yyyy" mask="true" >
	        </p:datePicker>
        </h:form>

		<h5>Basic</h5>
    	<p:commandButton value="Show" type="button" icon="pi pi-external-link" onclick="PF('dlg1').show()"/>
    	<p:dialog header="Header" widgetVar="dlg1" minHeight="200" width="400" position="center,top" showEffect="fade">
	    	<h:panelGrid columns="2"  cellpadding="5">
			    <p:outputLabel for="phoneDialog" value="Phone Number: " />			
				<p:inputMask id="phoneDialog" label="Phone Number" value="#{testView.stringDialog}" 
					mask="(999) 999-9999 [x99999]" maxlength="14" />
			
				<p:outputLabel for="startDateDialog" value="Start Date: "/>			
	       		<p:datePicker id="startDateDialog" value="#{testView.startDateDialog}"
		        	pattern="MM/dd/yyyy" mask="true">
		        </p:datePicker>
	
				<p:outputLabel for="endDateDialog" value="End Date: " />			
	       		<p:datePicker id="endDateDialog" value="#{testView.endDateDialog}"
		        			pattern="MM/dd/yyyy" mask="true" >
		        </p:datePicker>
	        </h:panelGrid>
		</p:dialog>

    </h:body>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
    private String string;
    private Integer integer;
    private BigDecimal decimal;
    private LocalDate startDate;
    private LocalDate endDate;
    
    private String stringDialog;
    private LocalDate startDateDialog;
    private LocalDate endDateDialog;
    
    @PostConstruct  
    public void init() {
        string = "Welcome to PrimeFaces!!!";
    }

//...
//Getters and Setters
//...
```

**Comment by melloware** [comment] 2022-01-24 23:24
Thanks for the reproducer I will take a look.

**Comment by melloware** [comment] 2022-01-25 12:39
Yep I have confirmed your issue.

**Comment by melloware** [comment] 2022-01-25 12:47
I am pretty sure its the InputMask is eating the focus call thus not triggering the popup to close.

Pretty sure its this issue: https://github.com/RobinHerbots/Inputmask/issues/2423

**Comment by melloware** [comment] 2022-01-28 14:57
Just confirmed the bug was fixed in InputMask and I tested it here and confirmed the issue is fixed. Thanks for reporting!

**Comment by imoehldf** [comment] 2022-01-28 15:07
Thanks for the fast action!

**Closed as completed** 2022-01-28 15:10 UTC
Labels: :lady_beetle: defect, third-party
