### ISSUE TITLE
dataExporter:Error when exporting tabledata with type xls and xlsx

### ISSUE THREAD

**Issue by markusg80** [primefaces/primefaces#3985] opened 2018-08-23 14:42 UTC
## 1) Environment
- PrimeFaces version: 6.2.8
- Does it work on the newest released PrimeFaces version? No Version? 6.2.8
- Does it work on the newest sources in GitHub?  Not tested yet
- Application server + version: Payara 5.182
- Affected browsers: all

## 2) Expected behavior

When i use dataExporter it should export tabledata inside an xls file

## 3) Actual behavior

Error message;
java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.CellStyle.setAlignment(Lorg/apache/poi/ss/usermodel/HorizontalAlignment;)V
	at org.primefaces.component.export.ExcelExporter.applyOptions(ExcelExporter.java:307)
	at org.primefaces.component.export.ExcelExporter.export(ExcelExporter.java:82)
	at org.primefaces.component.export.DataExporter.processAction(DataExporter.java:137)
	at javax.faces.event.ActionEvent.processListener(ActionEvent.java:96)
	at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:514)
	at javax.faces.component.UICommand.broadcast(UICommand.java:235)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:871)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1419)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:82)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:731)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:475)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1622)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:339)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
	at com.ruag.ticketsystem.utils.LoginFilter.doFilter(LoginFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:256)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:654)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:593)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:516)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:213)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:182)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:156)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:218)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:95)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:260)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:177)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:109)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:88)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:53)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:524)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:89)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:94)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:33)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:114)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)

## 4) Steps to reproduce

dataExporter inside commandButton 

## 5) Sample XHTML

`<p:commandButton value="#{intl.download}" icon="fa fa-file-excel-o" ajax="false">
<p:dataExporter type="xlsx" target=":ilistform:incidenttable" fileName="incidents" postProcessor="#componentReportBean.postProcessXLS}" />
</p:commandButton>`                 

## 6) Sample bean

not neccessary

**Comment by tandraschko** [comment] 2018-08-23 14:43
use the right POI version?!

**Comment by markusg80** [comment] 2018-08-23 14:45
I use the POI Version like in 6.2 Documention: POI 3.13

**Comment by melloware** [comment] 2018-08-23 14:53
POI is 3.17 as of PF 6.2

**Comment by melloware** [comment] 2018-08-23 14:54
Duplicate of https://github.com/primefaces/primefaces/issues/3576

**Closed as completed** 2018-08-23 15:00 UTC
Labels: Resolution: Duplicate

**Comment by markusg80** [comment] 2018-08-23 15:34
Why the Documentation still has the version 3.13 listed in section 2.2?

**Comment by melloware** [comment] 2018-08-23 15:41
it is a mistake that will be corrected for 6.3 documentation as noted by this ticket: https://github.com/primefaces/primefaces/issues/3576 to update the documentation.
