### ISSUE TITLE
Datatable pagination + rows broken if both are dynamic

### ISSUE THREAD

**Issue by karlkilden** [primefaces/primefaces#21] opened 2015-04-15 10:29 UTC
Hello,

When both pagination and rows are used together it does not always work correctly. We have a use case with a simple table with 15 rows and when you click advanced it instead uses 100 rows with pagination.

That works fine - but when you selected another page say page nr 2 you are hitting UIData#updatePaginationData then when you switch back to the simple table with 15 rows it get's stuck using 100 rows because UIData#updatePaginationData will not get touched again resetting the value.

What worked for me as a workaround was to override DataTableRender#encodeTbody and add this 

```
    if (rowCount < rows) {
        rows = rowCount;
    }
```

Not sure if the if (rowCount < rows) sanity check is okay or not. I am not sure if this weird line can be changed instead:

```
    int rowCountToRender = rows == 0 ? (table.isLiveScroll() ? (table.getScrollRows() + table.getScrollOffset()) : rowCount) : rows;
```

Using primefaces 5.2 with latest TomEE (1.7.1)

**Comment by tandraschko** [comment] 2018-02-23 09:51
looks like a duplicate of #1921

**Closed as completed by tandraschko** 2018-02-23 09:51 UTC
Labels: :lady_beetle: defect, Resolution: Duplicate
