### ISSUE TITLE
Bar charts don't work with DateAxis

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#100] opened 2015-04-19 07:24 UTC
Forum reference: http://forum.primefaces.org/viewtopic.php?f=3&t=38367
PrimeFaces 5.0
GlassFish 3.1.2.2
Mojarra 2.1.6
(using Facelets)

It seems that using a DateAxis on a bar-type chart causes the bars on the chart not to display (though some other things on the chart do display -- grid lines, etc.). I have pared down and slightly modified the DateAxis sample code (PF 5.0 user guide secion 3.13.10) to be a bar chart as a fairly minimal example of the problem I'm getting (this is the same code as in my forum post [above]):

``` xml
<p:chart type="bar" value="#{bean.model}" />
```

``` java
public class Bean {
       private BarChartModel model;
       public ChartBean() {
              dateModel = new BarChartModel();
              BarChartSeries series1 = new BarChartSeries();
              series1.setLabel("Series 1");
              series1.set("2014-01-01", 51);
              series1.set("2014-01-06", 22);
              series1.set("2014-01-12", 65);
              series1.set("2014-01-18", 74);
              series1.set("2014-01-24", 24);
              series1.set("2014-01-30", 51);
              dateModel.addSeries(series1);
              dateModel.setTitle("Zoom for Details");
              dateModel.setZoom(true);
              dateModel.getAxis(AxisType.Y).setLabel("Values");
              DateAxis axis = new DateAxis("Dates");
              axis.setTickAngle(-50);
              axis.setMax("2014-02-01");
              axis.setTickFormat("%b %#d, %y");
              dateModel.getAxes().put(AxisType.X, axis);
       }
       public BarChartModel getModel() { return model; }
}
```

**Comment by sudheerj** [comment] 2015-06-20 14:14
Duplicate of issue #447

**Closed as completed** 2015-06-20 15:08 UTC
Labels: :lady_beetle: defect
