### ISSUE TITLE
p:selectManyMenu with filter - strange column resizing

### ISSUE THREAD

**Issue by Henny-cz** [primefaces/primefaces#2297] opened 2017-04-21 08:46 UTC
## 1) Environment
- PrimeFaces version: 6.0.16
- Affected browsers: Chrome, FireFox

## Actual problem

You can try it: https://www.primefaces.org/showcase/ui/input/manyMenu.xhtml

When you start to type "Afterdark" into filter, less and less record will be shown in menu and it seems that columns are stretching. I have same problem with my Menu.

(Better example is if you copy showCase example but give it a greater width)

**Comment by melloware** [comment] 2017-04-22 00:02
Is this related to this defect as well?  #1111

**Comment by Henny-cz** [comment] 2017-04-22 06:43
It seems that yes

**Comment by melloware** [comment] 2020-03-29 12:32
Duplicate of #1111

**Closed as completed by melloware** 2020-03-29 12:32 UTC
