### ISSUE TITLE
FileDownload: cause ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ZiupeX** [primefaces/primefaces#7343] opened 2021-05-22 18:37 UTC
I faced problem with <p:fileDownload /> after update primefaces to version 10.  When open the view where is <p:fileDownload /> I faced the following exception:

```
20:20:08,053 SEVERE [org.primefaces.application.exceptionhandler.PrimeExceptionHandler] (default task-2) Index 13 out of bounds for length 13: java.lang.ArrayIndexOutOfBoundsException: Index 13 out of bounds for length 13
	at javax.faces.api@2.3.9.SP02//javax.faces.component.UIComponentBase.restoreChildState(UIComponentBase.java:3418)
	at javax.faces.api@2.3.9.SP02//javax.faces.component.UIComponentBase.processRestoreState(UIComponentBase.java:1026)
	at javax.faces.api@2.3.9.SP02//javax.faces.component.UIComponentBase.restoreFacetsState(UIComponentBase.java:3445)
	at javax.faces.api@2.3.9.SP02//javax.faces.component.UIComponentBase.processRestoreState(UIComponentBase.java:1029)
	at javax.faces.api@2.3.9.SP02//javax.faces.component.UIViewRoot.processRestoreState(UIViewRoot.java:932)
	at com.sun.jsf-impl@2.3.9.SP02//com.sun.faces.application.view.JspStateManagementStrategy.restoreView(JspStateManagementStrategy.java:252)
	at com.sun.jsf-impl@2.3.9.SP02//com.sun.faces.application.StateManagerImpl.restoreView(StateManagerImpl.java:113)
	at com.sun.jsf-impl@2.3.9.SP02//com.sun.faces.application.view.ViewHandlingStrategy.restoreView(ViewHandlingStrategy.java:99)
	at com.sun.jsf-impl@2.3.9.SP02//com.sun.faces.application.view.FaceletViewHandlingStrategy.restoreView(FaceletViewHandlingStrategy.java:272)
	at com.sun.jsf-impl@2.3.9.SP02//com.sun.faces.application.view.MultiViewHandler.restoreView(MultiViewHandler.java:133)
	at javax.faces.api@2.3.9.SP02//javax.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:101)
	at javax.faces.api@2.3.9.SP02//javax.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:101)
	at javax.faces.api@2.3.9.SP02//javax.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:101)
	at com.sun.jsf-impl@2.3.9.SP02//com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:180)
	at com.sun.jsf-impl@2.3.9.SP02//com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.jsf-impl@2.3.9.SP02//com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:109)
	at com.sun.jsf-impl@2.3.9.SP02//com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
	at javax.faces.api@2.3.9.SP02//javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
	at javax.faces.api@2.3.9.SP02//javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at deployment.shops-ear-1.0.ear//org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:111)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at deployment.shops-ear-1.0.ear.org.vcm.shops-uberwar-web-1.0.war//org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:274)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:209)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.spec.RequestDispatcherImpl.forwardImpl(RequestDispatcherImpl.java:227)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.spec.RequestDispatcherImpl.forwardImplSetup(RequestDispatcherImpl.java:149)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.spec.RequestDispatcherImpl.forward(RequestDispatcherImpl.java:111)
	at deployment.shops-ear-1.0.ear.org.vcm.shops-uberwar-web-1.0.war//org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler.handleResult(HttpRewriteResultHandler.java:42)
	at deployment.shops-ear-1.0.ear.org.vcm.shops-uberwar-web-1.0.war//org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:297)
	at deployment.shops-ear-1.0.ear.org.vcm.shops-uberwar-web-1.0.war//org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:198)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.opentracing.contrib.opentracing-jaxrs2//io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:55)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.core@2.0.21.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.core@2.0.21.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:835)

```

below my code

```
<h:form>
                <p:commandButton value="#{cmsOrderView.stringGenerateInvoice}"
                                 ajax="false"
                                 onclick="PrimeFaces.monitorDownload(start, stop);"
                                 icon="pi pi-arrow-down"
                                 styleClass="p-mr-2">
                    <p:fileDownload value="#{cmsOrderView.file}"/>
                </p:commandButton>
            </h:form>
```

```
 public StreamedContent getFile() {
        try {
            final ByteArrayInputStream stream = invoiceService.generateInvoiceFromOrderProduct(defaultCompany, order.getJson());
            return DefaultStreamedContent.builder()
                    .name("downloaded_boromir.pdf")
                    .contentType("application/pdf")
                    .stream(() -> stream)
                    .build();
        } catch (Exception ex) {
            Logger.getLogger(CmsOrderView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return DefaultStreamedContent.builder().build();
    }
```

before ubgrade to version 10 it works without exception. I tried also with empty stream but the same issue

```
    public StreamedContent getFile() {
       return DefaultStreamedContent.builder().build();
    }
```

**Comment by melloware** [comment] 2021-05-22 18:52
I have seen this same issue.  It's related to storing state but haven't figured out what has changed between 8 and 10.   We also use Wildfly/Undertow.

**Comment by melloware** [comment] 2021-05-22 19:02
Attached is your example and it doesn't happen:
[pf-7343.zip](https://github.com/primefaces/primefaces/files/6526986/pf-7343.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml

**Comment by ZiupeX** [comment] 2021-05-22 21:25
Hmm maybe it is related with server where is runned. I runned your example and it works but on wildfly not. Have you tried with 

instead of jetty:run >> wildfly:run

I`m use newest version of wildfly 23.0.2.Final

https://www.wildfly.org/downloads/

**Comment by ZiupeX** [comment] 2021-05-22 22:02
I found problem. Problem was related with following parameter:

```
<context-param>
        <param-name>javax.faces.PARTIAL_STATE_SAVING</param-name>
        <param-value>false</param-value>
    </context-param>
```

when I remove it problem gone

**Comment by melloware** [comment] 2021-05-23 01:29
Ok I will try and add that to my reproducer to see if I can get it to happen.

**Comment by melloware** [comment] 2021-05-23 12:11
OK yep now I can reproduce it by adding that to the web.xml.
[pf-7343.zip](https://github.com/primefaces/primefaces/files/6528034/pf-7343.zip)

It looks like a Mojarra bug as it works fine in Myfaces.

`mvn clean jetty:run -Pmyfaces22` - WORKS

`mvn clean jetty:run -Pmyfaces23` - WORKS

`mvn clean jetty:run -Pmojarra22` - **ERROR**

`mvn clean jetty:run -Pmojarra23` - **ERROR**

**Comment by melloware** [comment] 2021-05-23 12:19
Possibly related to: https://github.com/eclipse-ee4j/mojarra/issues/4925

**Comment by melloware** [comment] 2021-05-23 12:24
Opened Mojarra Issue: https://github.com/eclipse-ee4j/mojarra/issues/4936

**Comment by tandraschko** [comment] 2021-05-25 09:10
so lets close it? looks like it should be fixed in mojarra

**Closed as completed** 2021-05-25 11:28 UTC
Labels: third-party
