### ISSUE TITLE
Datatable: selection remains on page refresh with `multiviewstate=true`

### ISSUE THREAD

**Issue by trawat** [primefaces/primefaces#11146] opened 2023-12-12 19:17 UTC
1) **Environment**
Primefaces version - 11
Server - JBoss Wildfly 11
JSF version - mojarra 2.2.13

2) **Defect description**
`multiViewState=true` remembers the selection from the last AJAX request when we use browser refresh.

3) **Primefaces reproducer** [link](https://github.com/trawat/primefaces-dt-selection)

   Steps (on the landing page) - 
              - select `id#4` and change the status from `CLOSED` to `OPEN`
              - use browser refresh

### Discussed in https://github.com/orgs/primefaces/discussions/552

**Comment by tandraschko** [comment] 2023-12-18 15:51
isnt selection remember by design?

**Comment by melloware** [comment] 2023-12-18 16:04
@tandraschko here is the reproducer:
[pf-trawat.zip](https://github.com/primefaces/primefaces/files/13705903/pf-trawat.zip)

It seemed strange to me that the AJAX call looks like the datable has no selections.  Then pressing F5 the selections re-appear.

1. Find a row with Trolley as its type.
2. Select that row
3. Press the "Apply Status" button to change its status from CLOSED to OPEN and the item is no longer selected.
4. Press F5 and see the selection is back.

**Comment by melloware** [comment] 2024-01-03 18:33
Something is broken worse in 14.0.0 the SplitButton doesn't even execute its `action` now.

[pf-trawat-14.zip](https://github.com/primefaces/primefaces/files/13822209/pf-trawat-14.zip)

**Comment by tandraschko** [comment] 2024-01-04 13:32
thats because mvceCtlr vs ctrl in EL

**Comment by melloware** [comment] 2024-01-04 16:13
OK I have confirmed between #11231 and #3551 this is fixed in 14.0.0-SNAPSHOT and when you press "Open" the selection remains.

**Closed as completed** 2024-01-04 16:14 UTC
Labels: :lady_beetle: defect
