### ISSUE TITLE
DataScroller: backend method not called everytime 

### ISSUE THREAD

**Issue by rider87** [primefaces/primefaces#9959] opened 2023-03-23 17:51 UTC
### Describe the bug

I have an issue with `p:dataScroller` and also lazy loading.

I have a simple button / link to call a backend function.

```
<p:commandLink process="@this"
     actionListener="#{lazyView.doEdit(customer)}" resetValues="true"
	styleClass="m-1">
    <h:outputText value="Test" />
 </p:commandLink>
```

```
public void doEdit(Customer customer) {
		String test = customer.getName();
		System.out.print("TEST");
	}
```

For the first entries I´m able to call the function, but if I load more and more data, I cannot call the function anymore.
Please find attached also my reproducer.

### Reproducer

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/11054145/primefaces-test-master.zip)

### Expected behavior

Call the backend function for each entry from the list and not only for the first loaded rows.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

2.4

### Java version

11

**Comment by Rapster** [comment] 2023-03-23 19:08
I started to look at it, and it seems it stops working once rows (e.g 300) is reached

**Comment by Rapster** [comment] 2023-03-23 19:21
Ok, you set 300 rows, so it'll just "process" the 300 first rows. Any idea as of why you specified rows?

**Comment by rider87** [comment] 2023-03-27 19:43
ok, seems like that is wrong but even if I use JpaLazyDataModel, I´m have the same issue...

Unfortunately I cannot add JpaLazyDataModel in the producer example, but can you test this on your side?
Here is my code to create the JpaLazyDataModel:

	```
public JpaLazyDataModel createJpaLazyDataModel(Class<MyEntity> entityClass,
			JpaQueryBuilder jpaQueryBuilder, List<MyEntitySelectionItem> picPictureSelectionItemList) {
		
		JpaLazyDataModel lazyModel = new JpaLazyDataModel<MyEntity>(entityClass, () -> entityManager, "id") {

			@Override
			public List<MyEntity> load(int first, int pageSize, Map<String, SortMeta> sortBy,
					Map<String, FilterMeta> filterBy) {

				EntityManager em = this.entityManager.get();

				CriteriaBuilder cb = em.getCriteriaBuilder();
				CriteriaQuery<MyEntity> cq = cb.createQuery(entityClass);
				Root<MyEntity> root = cq.from(entityClass);
				cq = cq.select(root);

				applyFilters(cb, cq, root, filterBy);
				applySort(cb, cq, root, sortBy);

				TypedQuery<MyEntity> query = em.createQuery(cq);
				query.setFirstResult(first);
				query.setMaxResults(pageSize);

				List<MyEntity> result = (List<MyEntity>) query.getResultList();


				return (List<MyEntity>) result;
			}

			@Override
			protected void applyGlobalFilters(Map<String, FilterMeta> filterBy, CriteriaBuilder cb, CriteriaQuery<?> cq,
					Root<MyEntity> root, List<Predicate> predicates) {

				CustomLazyLoadingFunctionHelper.applyGlobalFilters(jpaQueryBuilder, filterBy, cb, cq, root, predicates);
			}

			@Override
			protected void applySort(CriteriaBuilder cb, CriteriaQuery<MyEntity> cq,
					Root<MyEntity> root, Map<String, SortMeta> sortBy) {
				
				CustomLazyLoadingFunctionHelper.applySort(jpaQueryBuilder, cb, cq, root, sortBy);
			}
		};

		return lazyModel;
	}
```

**Comment by rider87** [comment] 2023-03-27 19:47
Maybe also related to: https://github.com/primefaces/primefaces/issues/6087

**Comment by Rapster** [comment] 2023-03-27 20:52
`JpaLazyDataModel` is at the end of the day a `LazyDataModel` so shouldn't make a difference therefore you should be able to make a reproducer, or give more details to reproduce your issue because so far I gave you the answer to your problem

**Comment by rider87** [comment] 2023-03-28 14:20
I´m sure the issue is the **JpaLazyDataModel**...
Unfortunatelly I cannot create a producer with Database access at the PF test project.
Plesae let me know which information might help?

Please be so kind and test it with the `JpaLazyDataModel` with a running project on your side.

Is there maybe something wrong in setup then for `JpaLazyDataModel` ?
Please see here my code:
https://github.com/primefaces/primefaces/issues/9959#issuecomment-1485763268

**Comment by tandraschko** [comment] 2023-03-28 14:28
we have a JPA branch in the primefaces-test project: https://github.com/primefaces/primefaces-test/tree/jpa

just provide us a reproducer, otherwise we cant help

**Comment by rider87** [comment] 2023-03-30 11:12
I´ve tried more than 4 hours to debug with this JPA test producer, but I´m not able to replicate.
Maybe it has something to do with the JSF version.
I´m using currently WildFly 21 for it and I´ve tried here with `mvn clean jetty:run -Pmojarra23`

Any further idea what I can debug etc. when the number of data loaded (after chunkSize reached) ?

**Comment by Rapster** [comment] 2023-03-30 11:24
Just to be sure, but are you still having the same issue after removing `rows` attribute like I said previously in https://github.com/primefaces/primefaces/issues/9959#issuecomment-1481767253?

**Comment by rider87** [comment] 2023-03-30 11:41
> Just to be sure, but are you still having the same issue after removing `rows` attribute like I said previously in [#9959 (comment)](https://github.com/primefaces/primefaces/issues/9959#issuecomment-1481767253)?

Yes , I´ve adjusted this already...

This is my JSF file:
`<p:outputPanel deferred="true"
			loaded="#{not empty testView.lazyDataModel}">

			<p:ajax event="load" listener="#{testView.init()}" />

			<p:dataScroller id="dataScroller" value="#{testView.lazyDataModel}"
				rendered="#{testView.lazyDataModel != null}" lazy="true"
				var="testJpa" chunkSize="50">

				<f:facet name="loading">
					<div class="EmptyBox5"></div>
					<i class="fa fa-spinner fa-spin fa-fw"></i>
					<h:outputText value="Weitere Einträge laden..." />
				</f:facet>

				<div class="EmptyBox5"></div>

				<div class="flex justify-content-start align-items-center">

					<p:commandLink process="@this" immediate="true"
						oncomplete="PF('detailPictureDialog').show()"
						update=":detailPictureDialogForm"
						actionListener="#{testView.doEdit(testJpa)}" resetValues="true"
						styleClass="m-1">

						<h:outputText value="#{testJpa.stringCol}" />
					</p:commandLink>

				</div>

			</p:dataScroller>
		</p:outputPanel>

	</h:form>


	<h:form id="detailPictureDialogForm">

		<p:dialog id="detailPictureDialog" widgetVar="detailPictureDialog"
			appendTo="@(body)" header="Show Picture" showHeader="true"
			height="50vh" width="50vw" maximizable="false" minimizable="false"
			dynamic="true" modal="true" fitViewport="true" responsive="true"
			blockScroll="true" draggable="false" resizable="false"
			closable="true" closeOnEscape="true">

			<h:panelGroup id="overall_container" layout="block">


		Test

			</h:panelGroup>

		</p:dialog>
	</h:form>
`
It seems it´s loosing the connection to the loaded objects as soon more data has been loaded...

**Comment by Rapster** [comment] 2023-06-03 11:56
@rider87  Were you able to create a reproducer?

**Comment by rider87** [comment] 2023-06-04 06:27
@Rapster - no I´m sorry... 

But the issue still exists.
I´ve tried to implement it via Primefaces Test project but it seems it´s not 100% reproducable.

**Comment by melloware** [comment] 2023-06-28 00:57
I think this is related to #6087

**Comment by melloware** [comment] 2023-08-19 00:10
Closing this until a reproducer can be provided else we can't debug.  Will reopen once a reproducer is provided.

**Closed as not planned** 2023-08-19 00:11 UTC
Labels: Status: Needs Reproducer
