### ISSUE TITLE
SelectOneMenu: filter input sets other input fields placeholder text as default text in IE 11 browser

### ISSUE THREAD

**Issue by payal-gupta-04** [primefaces/primefaces#5401] opened 2019-12-05 04:50 UTC
If <p:selectOneMenu> component has "filter" attribute as "true" along-side a <p:inputText> component, then the placeholder text of <p:inputText> becomes its default value [XHTML code below] when filter dropdown of <p:selectOneMenu> component is opened and control is taken to the <p:inputText> component. 

**Version:** 7.0

**Note**: **The issue is occurring on in IE 11 browser.**

Steps to reproduce the issue are below. Also, an image demonstrating the issue is also attached.
- Use sample code below and open the test page in IE11 browser.
- Click selectOneMenu to open filter field with options list.
- Now, click on adjoining text field having id as "inputField" in sample code.
- Type letters (say, 'asd') in "inputField" text field. Observe that the letters become part of placeholder text along-with CSS style of placeholder.

```
<!DOCTYPE html>
<h:html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head>
	<title>Test Page</title>
	<style>
	::placeholder { /* Firefox and Chrome */
		color: #cdcdcd !important;
		text-transform: none;
	}

	:-ms-input-placeholder { /* Internet Explorer 10-11 */
		color: #cdcdcd !important;
		text-transform: none !important;
	}

	::-ms-input-placeholder { /* Microsoft Edge */
		color: #cdcdcd !important;
		text-transform: none;
		z-index: 100;
	}
	</style>
</h:head>
<h:body style="margin: 100px; text-align:center">
	<p:selectOneMenu id="dropdownField" filter="true" filterPlaceholder="Filter placeholder" widgetVar="dropdownField"
		filterMatchMode="startsWith" style="margin: 10px;">
		<f:selectItem itemLabel="Select" itemValue="" />
		<f:selectItem itemLabel="Option 1" itemValue="Option 1" />
		<f:selectItem itemLabel="Option 2" itemValue="Option 2" />
		<f:selectItem itemLabel="Option 3" itemValue="Option 3" />
		<f:selectItem itemLabel="Option 4" itemValue="Option 4" />
		<f:selectItem itemLabel="Option 5" itemValue="Option 5" />
	</p:selectOneMenu>

	<p:inputText id="inputField" placeholder="input field" style="margin: 10px;" />
</h:body>
</h:html>
```
![Issue on Test Page](https://user-images.githubusercontent.com/53164560/70204847-05c37080-1748-11ea-97ec-da4199e322d0.jpg)

**Comment by melloware** [comment] 2019-12-05 12:25
Attached is a reproducer:
[pf-5401.zip](https://github.com/primefaces/primefaces/files/3926786/pf-5401.zip)

I have verified the issue in IE11 and it is the strangest thing.  The InputText has focus to edit the placeholder text but is not highlighted in blue like it really has focus.  It feels like an IE bug almost.  You should never be able to edit the placeholder text!

**Comment by melloware** [comment] 2020-01-23 14:04
Unfortunately I think this truly is an IE bug that PF cannot fix.  I swapped out the PrimeFaces Inputtext for a regular native input and it still happens.   Its like IE11 isn't detecting the focus and leaving the placeholder text.  I would say report it to Microsoft but I doubt you will get any fix since IE is in maintenance mode.

```xml
<h:body style="margin: 100px; text-align:center">
	<p:selectOneMenu id="dropdownField" filter="true" filterPlaceholder="Filter placeholder" widgetVar="dropdownField"
		filterMatchMode="startsWith" style="margin: 10px;">
		<f:selectItem itemLabel="Select" itemValue="Test" />
		<f:selectItem itemLabel="Option 1" itemValue="Option 1" />
		<f:selectItem itemLabel="Option 2" itemValue="Option 2" />
		<f:selectItem itemLabel="Option 3" itemValue="Option 3" />
		<f:selectItem itemLabel="Option 4" itemValue="Option 4" />
		<f:selectItem itemLabel="Option 5" itemValue="Option 5" />
	</p:selectOneMenu>

	<input name="native" id="native" style="margin: 10px;" type="text" placeholder="input field"></input>
</h:body>
```

**Comment by melloware** [comment] 2020-01-23 14:56
I found another person not using PrimeFaces that has the same issue with IE11:
https://stackoverflow.com/questions/37018143/placeholder-text-is-editable

I am going to close this ticket for now as WontFix

**Closed as completed by melloware** 2020-01-23 14:56 UTC
Labels: :lady_beetle: defect, Resolution:  Wontfix
