### ISSUE TITLE
SelectOneRadio with custom layout inside ui:repeat not functional

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#539] opened 2015-07-17 13:02 UTC
We build a highly dynamic table using `ui:repeat`. The first column has a label and the `SelectOneRadio` (custom layout). Column two & three contain the radioButtons associated with the `SelectOneRadio`.

Only the first iteration of the `ui:repeat` has the correct state for the `SelectOneRadio` and therefor shows the correct checked radio button. Each subsequent iteration does not show any checked radio button, but the `SelectOneRadio` has the correct values (in its hidden accesibility).

We traced down the error to the method `SelectOneRadio#getRadioButtonId(FacesContext)`. In this method is a variable called `index`. This will be incremented with each call to this method. The Problem is that this variable is not state-relevant. Each iteration of `ui:repeat` should use its own state of the `SelectOneRadio`. 

![Image of the final table](http://s30.postimg.org/77nmx8uap/Unbenannt.png)

**current state**

```
Iteration=0 (Deckel)
  Call => index=0 (i.O.)
  Call => index=1 (n.i.O.)
Iteration=1 (Anpressplatte)
  Call => index=2 (i.O.)
  Call => index=3 (n.i.O.)
Iteration=2 (Zwischenpressplatte)
  Call => index=5 (i.O.)
  Call => index=6 (n.i.O.)
...
```

**expected state**

```
Iteration=0 (Deckel)
  Call => index=0 (i.O.)
  Call => index=1 (n.i.O.)
Iteration=1 (Anpressplatte)
  Call => index=0 (i.O.)
  Call => index=1 (n.i.O.)
Iteration=2 (Zwischenpressplatte)
  Call => index=0 (i.O.)
  Call => index=1 (n.i.O.)
...
```

A workaround is the usage of `c:forEach` instead of `ui:repeat`. But this is really ugly.

**Comment by hatemalimam** [comment] 2016-06-08 11:15
Can you mention the version number please ?

**Comment by minexew** [comment] 2017-03-10 17:42
Facing this issue in 5.2. Was it fixed in a later version?

**Comment by tandraschko** [comment] 2017-03-10 20:12
The issue is still open -> not fixed ;)

**Comment by tandraschko** [comment] 2017-03-10 20:17
But it would be great if anyone could provide a PR here!

**Comment by tandraschko** [comment] 2018-02-23 09:43
If you still ahve this problem, it would be great if someone could recreate the issue with all informations and examples.
It's quit hard to rebuild the example to check it currently.
I will close it for now.

**Closed as completed by tandraschko** 2018-02-23 09:43 UTC
Labels: :lady_beetle: defect, Resolution: Invalid
