### ISSUE TITLE
Add input page to Paginator

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primefaces#77] opened 2015-04-18 14:46 UTC
One of the most demanded functionality of our clients is that the paginators should contain an input text where they can type the page of the datatable/datagrid, press enter and display that page.

**Comment by sudheerj** [comment] 2016-01-05 12:18
We can add {JumpToPageInput} input template similar to {JumpToPageDropdown} dropdown.But Do we need to skip setting the page when user enters an invalid value(out of range,non-numeric characters) or any error notifications for the user.

**Comment by tandraschko** [comment] 2018-08-29 11:27
Duplicate of: https://github.com/primefaces/primefaces/issues/3198

**Closed as completed by tandraschko** 2018-08-29 11:27 UTC
Labels: new feature
