### ISSUE TITLE
SelectOneMenu: PF10 Parse Error in Dialog Framework Page

### ISSUE THREAD

**Issue by andrew-simmons** [primefaces/primefaces#7313] opened 2021-05-11 23:06 UTC
**Describe the defect**
When opening a Dialog Framework page in PrimeFaces 10, a Parse Error occurs due to use of non-breaking space entities in a selectOneMenu. 

Note when similar markup is used in normally loaded pages, this issue does not occur. It may be worthwhile to replace usages of `&nbsp;` with `&#160;`.

**Environment:**
 - PF Version: _10.0_ (parse error), _8.0.2_ (renders without error)
 - JSF + version: _Mojarra 2.3.9.SP02_
 - Affected browsers: _Chrome_

**To Reproduce**
1. Create a Dialog Framework page.
2. Add a p:selectOneMenu to it.
3. Add f:selectItems where the first item has an empty label
4. Open the page as a dynamic dialog. Parse error (see below).

**Expected behavior**
Page renders normally without error.

**Example XHTML**
```html
<h:form id="frmTest">
    <p:outputLabel for="conditionCode" value="Condition"/>
    <p:selectOneMenu id="conditionCode" 
                     value="#{testView.conditionCode}">
        <f:selectItems value="#{allConditionCodes}"
                       var="cond"
                       itemValue="#{cond}"
                       itemLabel="#{cond.value}"/>
        <f:validateBean disabled="true"/>
    </p:selectOneMenu>
</h:form>
```

**Example Bean**
```java
@Named
@ViewScoped
public class TestView implements Serializable {
    public enum ConditionCode {
          NULL,
          A,
          F,
          H
          ;
          
          public String getValue() { return (this != NULL) ? name() : ""; }
    
          @Produces @ApplicationScoped @Named
          public static Set<ConditionCode> getAllConditionCodes() { return EnumSet.allOf(ConditionCode.class); }
    }

    private ConditionCode conditionCode = ConditionCode.NULL;

    public getConditionCode() { return conditionCode; }
    public setConditionCode(ConditionCode code) { this.conditionCode = code; }
}
```

**Parse Error**
```
This page contains the following errors:
error on line 70 at column 1180: Entity 'nbsp' not defined
Below is a rendering of the page up to the first error.
```

**PrimeFaces 10.0.0 Generated HTML line 70**
```
                    <div class="p-col-12 p-sm-3"><label id="j_idt25:j_idt42" class="ui-outputlabel ui-widget" for="j_idt25:conditionCode_focus">Condition</label><div id="j_idt25:conditionCode" class="ui-selectonemenu ui-widget ui-state-default ui-corner-all readonly ui-state-disabled" aria-owns="j_idt25:conditionCode_panel" role="combobox" aria-haspopup="listbox" aria-expanded="false"><div class="ui-helper-hidden-accessible"><input id="j_idt25:conditionCode_focus" name="j_idt25:conditionCode_focus" type="text" autocomplete="off" aria-labelledby="j_idt25:j_idt42" disabled="disabled" aria-disabled="true" /></div><div class="ui-helper-hidden-accessible"><select id="j_idt25:conditionCode_input" name="j_idt25:conditionCode_input" tabindex="-1" aria-hidden="true" disabled="disabled"><option value="NULL" data-escape="true"></option><option value="A" selected="selected" data-escape="true">A</option><option value="F" data-escape="true">F</option><option value="H" data-escape="true">H</option></select></div><label id="j_idt25:conditionCode_label" class="ui-selectonemenu-label ui-inputfield ui-corner-all">&nbsp;</label><div class="ui-selectonemenu-trigger ui-state-default ui-corner-right"><span class="ui-icon ui-icon-triangle-1-s ui-c"></span></div><div id="j_idt25:conditionCode_panel" class="ui-selectonemenu-panel ui-widget ui-widget-content ui-corner-all ui-helper-hidden ui-shadow ui-input-overlay"><div class="ui-selectonemenu-items-wrapper" style="max-height:200px"><ul id="j_idt25:conditionCode_items" class="ui-selectonemenu-items ui-selectonemenu-list ui-widget-content ui-widget ui-corner-all ui-helper-reset" role="listbox"><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="&amp;nbsp;" tabindex="-1" role="option">&nbsp;</li><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="A" tabindex="-1" role="option">A</li><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="F" tabindex="-1" role="option">F</li><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="H" tabindex="-1" role="option">H</li></ul></div></div></div>
```

**PrimeFaces 8.0.2 Generated HTML line 70**
```
                    <div class="p-col-12 p-sm-3"><label id="j_idt25:j_idt42" class="ui-outputlabel ui-widget" for="j_idt25:conditionCode_focus">Condition</label><div id="j_idt25:conditionCode" class="ui-selectonemenu ui-widget ui-state-default ui-corner-all readonly ui-state-disabled" aria-owns="j_idt25:conditionCode_panel" role="combobox" aria-haspopup="listbox" aria-expanded="false"><div class="ui-helper-hidden-accessible"><input id="j_idt25:conditionCode_focus" name="j_idt25:conditionCode_focus" type="text" autocomplete="off" aria-labelledby="j_idt25:j_idt42" disabled="disabled" aria-disabled="true" /></div><div class="ui-helper-hidden-accessible"><select id="j_idt25:conditionCode_input" name="j_idt25:conditionCode_input" tabindex="-1" aria-hidden="true" disabled="disabled"><option value="NULL" data-escape="true"></option><option value="A" selected="selected" data-escape="true">A</option><option value="F" data-escape="true">F</option><option value="H" data-escape="true">H</option></select></div><label id="j_idt25:conditionCode_label" class="ui-selectonemenu-label ui-inputfield ui-corner-all">&nbsp;</label><div class="ui-selectonemenu-trigger ui-state-default ui-corner-right"><span class="ui-icon ui-icon-triangle-1-s ui-c"></span></div><div id="j_idt25:conditionCode_panel" class="ui-selectonemenu-panel ui-widget ui-widget-content ui-corner-all ui-helper-hidden ui-shadow ui-input-overlay"><div class="ui-selectonemenu-items-wrapper" style="max-height:200px"><ul id="j_idt25:conditionCode_items" class="ui-selectonemenu-items ui-selectonemenu-list ui-widget-content ui-widget ui-corner-all ui-helper-reset" role="listbox"><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="&amp;nbsp;" tabindex="-1" role="option">&nbsp;</li><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="A" tabindex="-1" role="option">A</li><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="F" tabindex="-1" role="option">F</li><li class="ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all" data-label="H" tabindex="-1" role="option">H</li></ul></div></div></div>
```

**Comment by melloware** [comment] 2021-05-12 11:31
@andrew-simmons Can you please create a reproducer using PrimeFaces Test so I can debug [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  

You can just attach the zip file of the just the /src folder and pom.xml no need to include target.

**Comment by melloware** [comment] 2021-05-13 14:26
@andrew-simmons I can't reproduce.  Attached is my reproducer
[pf-7313.zip](https://github.com/primefaces/primefaces/files/6473045/pf-7313.zip)

Run `mvn clean jetty:run -Pmojarra23` and navigate to http://localhost:8080/primefaces-test/test.xhtml

Can you see if I am doing something different than you?

**Comment by wal-jan** [comment] 2021-05-14 11:28
Interesting issue. Here's a reproducer

Run `mvn clean jetty:run`, navigate to [http://localhost:8080/primefaces-test/test.xhtml](http://localhost:8080/primefaces-test/test.xhtml) and click on button "Show dynamic dialog"

The dialog is send to the browser as XML (not HTML). In fact the dynamic dialog isn't even neccessary, just put the `<p:selectOneMenu ...` and `<f:view contentType="application/xhtml+xml>"` into `test.xhtml`. 

Reproducer [PF7313.zip](https://github.com/primefaces/primefaces/files/6478435/PF7313.zip)

see my PR

**Comment by tandraschko** [comment] 2021-05-14 11:32
same on MyFaces?

sorry, i dont have time to try the reproducer but im not sure about the fix
i think this should be escaped by the JSF impl probably

**Comment by wal-jan** [comment] 2021-05-14 12:31
Same on Myfaces!
But my PR does not work, please ignore.

**Comment by melloware** [comment] 2021-05-14 13:11
I guess the question is why do you do this? `<f:view contentType="application/xhtml+xml>` ??

**Comment by andrew-simmons** [comment] 2021-05-14 15:11
Haven't had time to dig into this. Will work on it today.

**Comment by andrew-simmons** [comment] 2021-05-14 20:10
Made some changes, but no luck causing the error with [pf-7313.zip](https://github.com/primefaces/primefaces/files/6480978/pf-7313.zip). 

Could anything cause what PrimeFaces / Mojarra generates to be parsed a second time?

**Comment by melloware** [comment] 2021-05-14 23:55
Not that I am aware of. Was hoping you could reproduce so I can see the issue

**Comment by melloware** [comment] 2021-05-16 13:55
I think this has something to do with how the Dialog Framework is opening the page and what is getting wrapped in CDATA or not.  Very strange.

**Comment by melloware** [comment] 2021-05-25 18:51
Going to close this one for now until someone provides a use case where this makes sense.  Right now the only way to reproduce is to do `<f:view contentType="application/xhtml+xml"/>` which doesn't make any sense to me why you would do that.

**Closed as completed by melloware** 2021-05-25 18:51 UTC
Labels: needs further work
