### ISSUE TITLE
Datatable: Does not render correctly inside a dialog

### ISSUE THREAD

**Issue by aLeXcBa1990** [primefaces/primefaces#8332] opened 2022-01-26 03:59 UTC
**Describe the defect**
Creating a Datatable within a dialog with the paginator="true" option renders the paginator to one side of the table, this happens in the paginatorPosition="both" and paginatorPosition="top" options. 

**Environment:**
 - PF Version: _11.0.0_
 - Affected browsers:  Chrome, Firefox

**To Reproduce**
1. Only open a dialog

**Expected behavior**
The dialog opens and the paginated table is displayed correctly. 

**Example XHTML**
```html
<p:commandButton value="Show" type="button" icon="pi pi-external-link"
			onclick="PF('dlg2').show()" />
		
<p:dialog  widgetVar="dlg2" minHeight="40" width="350" modal="true">

	<p:dataTable id="table"	value="#{productsView.productList}" var="product"
	rows="10" paginator="true" rowKey="#{product.proId}">

		<p:column width="130" headerText="Code">
			<h:outputText value="#{product.proCode}" />
		</p:column>

		<p:column width="200" headerText="Desc.">
			<h:outputText value="#{product.proObser}" />
		</p:column>

		<p:column width="75" headerText="Price">
			<h:outputText value="#{product.proPrice}">
				<f:convertNumber minFractionDigits="2" />
			</h:outputText>
		</p:column>

	</p:dataTable>
</p:dialog>
```
**Screenshot rendered**
![Screenshot 2022-01-25 at 22-58-45 Screenshot](https://user-images.githubusercontent.com/12514121/151101803-6a715236-83cc-484c-90d3-ac5fd0073e86.png)

**Comment by jepsar** [comment] 2022-01-26 06:39
Cannot reproduce. [primefaces-test.zip](https://github.com/primefaces/primefaces/files/7939422/primefaces-test.zip)

**Comment by jepsar** [comment] 2022-01-26 06:46
@aLeXcBa1990 Cannot reproduce. [primefaces-test.zip](https://github.com/primefaces/primefaces/files/7939469/primefaces-test.zip)

Can you please try with the Saga theme?

**Comment by melloware** [comment] 2022-01-29 12:49
Closing for now unless we hear from OP

**Closed as completed** 2022-01-29 13:31 UTC
Labels: needs further work
