### ISSUE TITLE
Migration guide: Inplace change not mentioned in 6.2->7.0 migration guide (also impacting user guide)

### ISSUE THREAD

**Issue by mauromol** [primefaces/primefaces#9164] opened 2022-09-01 10:23 UTC
### Describe the bug

I found another annoying and undocumented change from PF 6.2 to 7.0 (in addition to #8892). 

I'm following the migration guide at:
https://primefaces.github.io/primefaces/11_0_0/#/../migrationguide/7_0

However, I see no mention of the fact that `<p:inplace>`, when adding `save` and/or `cancel` ajax behaviors, now requires an `update="@this"` in order for the inplace to work correctly (i.e.: to return to output mode).

### Reproducer

```xml
<p:inplace label="Foo" editor="true">
  <p:inputText />
  <p:ajax event="cancel" global="false" />
</p:inplace>
```

Try to hit the "cancel" button: nothing happens.

### Expected behavior

Honestly I would expect the inplace `@this` update to be automatic, as it was before, since this is an intrinsic mechanism of the component. Or else, if you think it should not, this should be well documented. The same user guide at https://primefaces.github.io/primefaces/7_0/#/components/inplace?id=inplace uses the following example:

```xml
<p:inplace editor="true">
    <p:ajax event="save" listener="#{inplaceBean.handleSave}" update="msgs" />
    <h:inputText value="#{inplaceBean.text}" />
</p:inplace>
<p:growl id="msgs" />
```

which I can't make to work unless I add `@this` in the `update` attribute of the `<p:ajax>`.

So, either the documentation or the library is wrong.

This makes the migration from 6.2 to 7.0 harder indeed...

### PrimeFaces edition

Community

### PrimeFaces version

7.0

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

11

### Browser(s)

Firefox 104, Chrome 105

**Comment by tandraschko** [comment] 2022-09-01 10:53
we dont document bugs; duplicate of https://github.com/primefaces/primefaces/issues/4721

**Closed as completed by tandraschko** 2022-09-01 10:53 UTC
Labels: :lady_beetle: defect

**Comment by mauromol** [comment] 2022-09-01 11:05
So whoever is upgrading to 7.0 is... left alone - to use kind words ;-). 
It won't cost so much to add a note to the migration guide, since adding the `update="@this"` is an actual requirement for upgrading. We broke our production because of this.

**Comment by tandraschko** [comment] 2022-09-01 11:13
we fixed like 381 tickets for 8.0, where propably 50% of it are bugs
and many of them could been introduced in 7.0 and fixed in 8.0 

maybe many of them are maybe worth to put in a migration guide but as 7.0 is already 3 years old and the most people just migrate the whole chain to the newest version, its just impossible to document all correctly

**Comment by mauromol** [comment] 2022-09-01 11:22
I'd really like to know people who dare to upgrade PrimeFaces to more than 2 major versions ahead in a REAL production environment (in a sufficiently complex application, of course)... every time it's a pain to just upgrade to one version ahead. Moreover, from version 7.0 to version 8.0 there's also an updated requirement for Java version, and the migration guide 7.0->8.0 is quite long, so performing such an upgrade step for us will require significant effort (in addition to that already spent for 6.2->7.0 upgrade). 
I'm not saying you should document all bugs, but there are certain bugs that are more severe than others and may have an extended impact because they affect common use cases (indeed, even an example so simple that it's in the user guide). This is one of those IMHO.

**Comment by tandraschko** [comment] 2022-09-01 11:26
then feel free to provide a PR with your findings to enhance the migration guide, you dont need to create a issue for each.
i wont invest time here, sorry.

**Comment by jepsar** [comment] 2022-09-01 11:26
That's not my experience. I'm not saying I enjoy updating, but it surely is not a pain IMO.

**Comment by mauromol** [comment] 2022-09-01 12:40
Seems like this problem is even worse, because putting `update="@this"` on my `<p:ajax event="cancel">` causes the value to be submitted, just like it happens with the `save` event... any suggested workaround would be appreciated.

@jepsar glad to know it's not a pain for you. From my experience, I could reference at least one issue (regression or breaking change) for each major (aka community) release of PrimeFaces from 4.0 on, that caused us a lot of headaches, extensive changes to our codebase or even prevented us from upgrading. Like in this case: if I can't find a workaround for this problem, I have to revert to 6.2 or to try 8.0 upgrade (something I was not willing to do right now...).

**Comment by mauromol** [comment] 2022-09-14 13:38
@jepsar just for your curiosity (maybe...), the forced upgrade from 7.0 to 8.0 (which was requested, I remember, because of a regression in 7.0, or better, one of the regressions we found in 7.0) for us is showing itself as a pain, as expected.
These are the regressions encountered so far:
- p:confirmDialog inside tabView+panelGrid reguired the addition of an appendTo="form" otherwise the overlay got broken (no way to click any more on widgets inside the confirmDialog)
- #5661, which is really scaring me... I don't know how to workaround

These not to mention the documented changes (liked: attribute name change in fileUploadListener, API change in LazyDataModel and UploadedFile, with no deprecation at all to allow for smooth migration).

Sorry to say, but I really think Prime Faces needs better QA.

**Comment by melloware** [comment] 2022-09-14 13:45
@mauromol are you an Elite subscriber?  That Repeat bug 5661  was fixed in 8.0.1+?

As for QA over 600 Integration tests have been added in PF 11 and 12 to prevent exactly these kinds of issues. I guess the bigger question is why are you upgrading from a major version 5 versions behind to a version 4 versions behind?

**Comment by melloware** [comment] 2022-09-14 13:46
Also the migration guides are open source if something is missing simply submit a PR updating the documentation.

**Comment by mauromol** [comment] 2022-09-14 14:35
@melloware I deeply respect your work and your business model, don't get me wrong. Yet, I think that perhaps a bit more care towards the open source community should be due, especially when you ask people to open PRs: if I were truly cynical, I could ask you if I am supposed to fix your bugs so that you can sell your elite versions, without having the ability to download these versions unless I pay for elite membership. But I don't think this is the right approach and, being a developer myself, I acknowledge the value of your work and I know it costs time, and time is money.

This said, I still believe that regressions are really bad for an important library like PrimeFaces and that some bugs (like regressions, indeed) would be important enough to consider about releasing minor bugfix releases to the community. I'm not talking about new features. I'm not talking about long-standing issues fixed in a major release. I'm just talking about some very specific cases that otherwise are also mining trust in the library. As I previously said, I could make a list of at least one severe regression I found in every PF release from 6.0 to 8.0 included (but I'm pretty sure there were problems even before, simply I haven't documented them so carefully in my project source code).

You ask me why I'm upgrading to 4 versions behind: in the real world (at least in ours), there are applications used in production for which very limited resources are devoted to cover the technical debt and upgrade dependencies to try to stay as much current as possible without hurting stability too much. Apart from the fact that you say I'm upgrading to 4 versions behind, but if I look to your download page I see that the latest stable version is PF 10 and there's no PF 9, so I'm just one version behind the latest stable (or perhaps 2: why are PF 11 downloads missing from https://www.primefaces.org/downloads/?), are you really convinced that an upgrade from PF 6.2 straight to PF 10 or 11 is feasable, without the need to upgrade (or at least carefully evaluate) the so many other dependencies our application has (I can think of Tomcat, JSF, Spring, Hibernate, JRE, etc., not to mention the Jakarta vs JEE refactoring)? In my own career I always proceeded by simple steps, one library component after the other (when feasible, of course) and this allowed me to successfully upgrade many technology stacks. I'm sorry to say that PrimeFaces has probably always been the most critical component to upgrade, due to the above reasons.

I'm glad to know that many integration tests have been added to PF 11 and 12, I really hope these will help to prevent future regressions as much as possible.

**Comment by tandraschko** [comment] 2022-09-14 14:40
wheter I, nor @melloware are working for PrimeTek and we dont have a business model; we are just open source commiters.

and if you are unhappy with it, i can just suggest to improve our documentation, provide integration tests to make it more stable in future or just buy PrimeFaces PRO to fix your bugs in a elite release; see https://github.com/primefaces/primefaces#community--elite--pro

**Comment by tandraschko** [comment] 2022-09-14 14:50
and about the versions on the homepage; we have no control over it, therefore we have:
https://github.com/primefaces/primefaces#versions
