### ISSUE TITLE
SelectCheckboxMenu: highlight component if option selected

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#8054] opened 2021-11-07 23:09 UTC
**Description**

Give users visual feedback if option selected with _multiple="false"_. 
In a datatable with filters a user has no idea which filter is selected.

**Describe the solution you would like**

a) Add css class "ui-state-active" to _SelectCheckboxMenu_ if any option is selected and _multiple="false"_.

b) Optional if only one option is selected use that selection option as label to behave like _SelectOneMenu_ giving user even better feedback. Basically the combination of _updateLabel="true"_ and _multiple="false"_. In our use cases, even its a _SelectManyCheckbox_ often we just select one option for filtering.

**Additional context**

Preview: https://i.ibb.co/X3yVLS2/Unbenannt.jpg

This styling makes it consistent with other select components like _SelectManyButton_.

**Comment by tandraschko** [comment] 2021-11-08 08:12
@mertsincan can you please comment? I think its a by design currently and probably a wont fix?

**Comment by djmj** [comment] 2021-11-09 16:43
@tandraschko But by design it is undefined for combination of `updateLabel="true" and multiple="false"`. It could be an opt-in feature using `updateLabel="true"`.

**Comment by mertsincan** [comment] 2022-04-06 23:58
Hi @djmj,

Yes, I think a study can be done on this subject. We would be grateful if you could send a PR about it. Also, please see PrimeReact example;
https://www.primefaces.org/primereact/multiselect/

_Note: If I had a chance, I would remove the label attribute :D it's so confusing_

**Comment by melloware** [comment] 2022-04-26 12:41
@djmj I already add the ability to use `multiple=false` and `updateLabel="true"` in this ticket: https://github.com/primefaces/primefaces/issues/7241

Now I added `ui-state-active` in `multiple="false"` mode so you can update the styling in 12.0.0

**Closed as completed** 2022-04-26 14:15 UTC
Labels: new feature

**Comment by djmj** [comment] 2022-04-26 22:08
@melloware  That sounds great and i look forward to 12.0.0. Thank you!
