### ISSUE TITLE
DataExporter: Align footer cells based on column alignment

### ISSUE THREAD

**Issue by rho66** [primefaces/primefaces#10098] opened 2023-05-09 08:48 UTC
### Describe the bug

Footer cells should have the same alignment (right, center, and left) in PDF and Excel exports as the corresponding data cells.

The alignment in data cells was fixed with #6430 and #6432.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### Theme

Rain

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

11

**Comment by melloware** [comment] 2023-05-09 16:58
Hmmm I don't know about this one as it would align Header and Footer facets the same as the column.  And right now all facets are CENTER on purpose.

**Comment by Rapster** [comment] 2023-05-10 08:40
I understand it's a regression since it was working in 10.0.0 no ?

**Comment by melloware** [comment] 2023-05-10 11:53
Actually @Rapster I don't think we ever aligned facets only the cells.  I don't remember ever having the header and footer facets aligned.

```java
private CellStyle createFacetStyle() {
        CellStyle style = wb.createCellStyle();
        style.setFont(createFont());
        style.setAlignment(HorizontalAlignment.CENTER);
        style.setVerticalAlignment(VerticalAlignment.CENTER);
        style.setWrapText(true);
        applyFacetOptions(style);
        return style;
    }
```

**Comment by Rapster** [comment] 2023-05-10 12:36
But that's what #6432 fixed no?

**Comment by melloware** [comment] 2023-05-10 12:55
Yep "Cell" alignment of data cells works fine.  What @rho66 wants is the HEADER and FOOTER facets to also be aligned with the column which I am not quite sure is a good feature.

So if you had a right aligned column "Price"  that was a number... it right aligns the data but the the Header Cell for "Price" is still centered properly.  This request would right align that word "Price" in the header which I don't think many users will expect that to happen.

**Comment by melloware** [comment] 2023-05-10 15:53
I know exactly what you want.  But right now facets are treated the same so if we fixed this the HEADER text "Price" would also be right aligned which violates [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) for most users.

**Comment by melloware** [comment] 2023-05-10 16:13
Well its not really a single `style` though like CSS style is....it is POI code to set the cells which requires multiple settings.

```java
private CellStyle createFacetStyle() {
        CellStyle style = wb.createCellStyle();
        style.setFont(createFont());
        style.setAlignment(HorizontalAlignment.CENTER);
        style.setVerticalAlignment(VerticalAlignment.CENTER);
        style.setWrapText(true);
        applyFacetOptions(style);
        return style;
```

I wonder if this can be done in the PostProcessor similar to this and you can basically set the styles of those footer cells in the Post Processing. See: https://primefaces.github.io/primefaces/12_0_0/#/components/dataexporter?id=change-excel-table-header

**Comment by stolp** [comment] 2023-05-10 17:07
I think modifications like this should be handled by a user defined exporter implementation. This is how we are handling this.

**Comment by rho66** [comment] 2023-05-10 17:12
Here is a reproducer project and the exported PDF. From my perspective, an export should look the same as the data in UI!

[items.pdf](https://github.com/primefaces/primefaces/files/11444461/items.pdf)
[primefaces-test-10098.zip](https://github.com/primefaces/primefaces/files/11444462/primefaces-test-10098.zip)

**Comment by rho66** [comment] 2023-05-10 17:13
> I think modifications like this should be handled by a user defined exporter implementation. This is how we are handling this.

Do you have any example of a custom PDF or EXCEL exporter?

**Comment by stolp** [comment] 2023-05-10 19:05
Here is an example for footer suppression in Excel to get you started (PrimeFaces 12):

```
public class MyDataTableExcelXStreamExporter extends DataTableExcelXStreamExporter {

    /**
     * Patched to disable Footer rows.
     */
    @Override
    protected void addColumnFacets(final DataTable table, final Sheet sheet,
        final DataTableExporter.ColumnType columnType) {

        final int sheetRowIndex = columnType == DataTableExporter.ColumnType.HEADER ? 0 : (sheet
            .getLastRowNum() + 1);
        final Row rowHeader = sheet.createRow(sheetRowIndex);

        for (final UIColumn col : table.getColumns()) {
            if (col instanceof DynamicColumn) {
                ((DynamicColumn) col).applyStatelessModel();
            }

            if (col.isRendered() && col.isExportable()) {
                final UIComponent facet = col.getFacet(columnType.facet());
                String textValue;
                switch (columnType) {
                    case HEADER :
                        textValue = (col.getExportHeaderValue() != null) ? col.getExportHeaderValue() : col
                            .getHeaderText();
                        break;

                    case FOOTER :
                        // Always skip footer
                        textValue = null;
                        break;

                    default :
                        textValue = null;
                        break;
                }

                if (textValue != null) {
                    addColumnValue(rowHeader, textValue);
                } else if (ComponentUtils.shouldRenderFacet(facet)) {
                    addColumnValue(rowHeader, facet);
                } else {
                    addColumnValue(rowHeader, "");
                }
            }
        }
    }
}

```

**Comment by rho66** [comment] 2023-05-11 05:25
Thanks for the example - I'll give it a try.

**Comment by rho66** [comment] 2023-05-11 05:33
> I know exactly what you want. But right now facets are treated the same so if we fixed this the HEADER text "Price" would also be right aligned which violates [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) for most users.

however, I still think the export should look the same as it does in the UI - without a custom exporter

**Comment by rho66** [comment] 2023-05-11 07:37
DatatableExcelExporter works as expected because in methode `applyColumnAlignments()` it applies the correct alignment (e.g. `cellStyleRightAlign`).

DatatablePdfExporter does not call `applyColumnAlignments()` for footer cells.

**Comment by melloware** [comment] 2023-05-11 11:31
@rho66 feel free to submit a PR for the PDF exporter.

**Comment by rho66** [comment] 2023-05-16 17:23
I'll do that ;-)

**Comment by melloware** [comment] 2023-05-16 18:00
No a Pull Request implementing the feature.   https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by melloware** [comment] 2023-05-18 00:33
@rho66 going to close this for now as a feature that won't be implemented. If you figure out how to align PDF cells feel free to open another ticket on how to implement applyColumnAlignment in PDF's.

**Closed as not planned** 2023-05-18 00:33 UTC
Labels: Resolution:  Wontfix, workaround
