### ISSUE TITLE
Panel: Inconsistently themed borders.

### ISSUE THREAD

**Issue by irieill** [primefaces/primefaces#8511] opened 2022-03-04 10:28 UTC
**Describe the defect**
_Custom Toolbar_ section is the blueprint for panel borders. When adding a footer the content box stays with rounded borders and the footer box itself comes with angular borders (_Regular_ section). When collapsing a toggleable panel there is no bottom border at all (_Toggleable_ section).
![current](https://user-images.githubusercontent.com/21124034/156742504-1598c7c0-bc05-4c1c-8f5b-b41abb68e9cf.png)

**Reproducer**
Showcase

**Environment:**
 - PF Version: _11.0.0, master_
 - PF Theme: _ALL_
 - Affected browsers: _ALL_

**Expected behavior**
![should](https://user-images.githubusercontent.com/21124034/156742528-e40702f4-d2a8-4605-bce8-823433edc8a6.png)

**Comment by tandraschko** [comment] 2022-03-04 10:40
duplicate of https://github.com/primefaces/primefaces/issues/8215

please use the issue search next time before

**Closed as completed by tandraschko** 2022-03-04 10:40 UTC
Labels: :lady_beetle: defect

**Comment by irieill** [comment] 2022-03-04 10:50
Well, I did use the search and I was wondering why this was not reported before. But obviously i used the wrong keywords. Sorry.
