### ISSUE TITLE
SplitButton: support dynamic model

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#2913] opened 2017-11-09 13:46 UTC
Just like components like MenuButton, Menu, etc. They support programmatic model. Would be awesome to do the same with SplitButton. Someone requested this feature some time ago https://forum.primefaces.org/viewtopic.php?p=70595

**Comment by melloware** [comment] 2017-11-09 13:48
duplicate of https://github.com/primefaces/primefaces/issues/766

**Closed as completed** 2017-11-09 14:18 UTC
Labels: Resolution: Duplicate

**Comment by Rapster** [comment] 2017-11-09 14:22
My bad :(
