### ISSUE TITLE
DataTable: facet type filter input render issue on dataTable update after column:render toggle

### ISSUE THREAD

**Issue by MontyZoomer** [primefaces/primefaces#8091] opened 2021-11-19 10:51 UTC
**Title**
When using a facet name=filter to hold the filter input fields, the input field is not shown when a dataTable column is activated using the render attribute of the column.  Works with PF8 and 10 but not 11RC2.

**Reproducer**
https://github.com/MontyZoomer/primefaces-test.git

**Environment:**
 - PF Version: 11.0.0-RC2
 - JSF + version: _e.g. Mojarra 2.2.20 
 - Affected browsers: ALL

**To Reproduce**
Press the toggle buttons in test demo

**Expected behavior**
The filter input field to be rendered

**Example XHTML**
```xml
 <p:dataTable id="animalDT" widgetVar="animsDT" value="#{testView.animalList}" var="animal">

                <p:column rendered="#{testView.columnMap['COL1']}" sortBy="#{animal.type}" filterBy="#{animal.type}" >
                    <f:facet name="filter">
                        <p:selectOneMenu onchange="PF('animsDT').filter()">
                            <f:selectItem itemLabel="All" noSelectionOption="true" itemValue="#{null}"/>
                            <f:selectItem itemLabel="Tiger" itemValue="Tiger"/> 
                            <f:selectItem itemLabel="Elephant" itemValue="Elephant"/> 
                            <f:selectItem itemLabel="Bear" itemValue="Bear"/> 
                        </p:selectOneMenu>
                    </f:facet>
                    #{animal.type}
                </p:column>
                
                <p:column rendered="#{testView.columnMap['COL2']}" sortBy="#{animal.name}" filterBy="#{animal.name}" >
                    <f:facet name="filter">
                        <p:selectOneMenu onchange="PF('animsDT').filter()">
                            <f:selectItem itemLabel="All" noSelectionOption="true" itemValue="#{null}"/>
                            <f:selectItem itemLabel="Max" itemValue="Max"/> 
                            <f:selectItem itemLabel="Nellie" itemValue="Nellie"/> 
                            <f:selectItem itemLabel="Balloo" itemValue="Balloo"/> 
                        </p:selectOneMenu>
                    </f:facet>
                    #{animal.name}
                </p:column>
                <p:column rendered="#{testView.columnMap['COL3']}" sortBy="#{animal.color}" filterBy="#{animal.color}" >
                    <f:facet name="filter">
                        <p:selectOneMenu onchange="PF('animsDT').filter()">
                            <f:selectItem itemLabel="All" noSelectionOption="true" itemValue="#{null}"/>
                            <f:selectItem itemLabel="White" itemValue="White"/> 
                            <f:selectItem itemLabel="Pink" itemValue="Pink"/> 
                            <f:selectItem itemLabel="Brown" itemValue="Brown"/> 
                        </p:selectOneMenu>
                    </f:facet>
                    #{animal.color}
                </p:column>                
            </p:dataTable>
            <div></div>
            <p:commandButton value="Toggle Col 2" actionListener="#{testView.toggleColumn('COL2')}" update="animalDT" />
            <div></div>
            <p:commandButton value="Toggle Col 3" actionListener="#{testView.toggleColumn('COL3')}" update="animalDT" />
            <div></div>
            <p:commandButton value="Toggle Col 2 Non Ajax" ajax="false" actionListener="#{testView.toggleColumn('COL2')}" update="animalDT" />
            
```

**Example Bean**
```java
    public void init() {
        string = "Welcome to PrimeFaces!!";

        columnMap = new HashMap<String, Boolean>() {
            {
                put("COL1", Boolean.TRUE);
                put("COL2", Boolean.FALSE);
                put("COL3", Boolean.TRUE);
            }
        };
        
        animalList = Arrays.asList(
                new Animal("Tiger", "Max", "White"),
                new Animal("Elephant", "Nellie", "Pink"),
                new Animal("Bear", "Balloo", "Brown")
        );
    }
    
    public void toggleColumn(String col) {
        columnMap.put(col, !(columnMap.get(col)));
    }
```

**Comment by djmj** [comment] 2021-11-20 19:06
Possible duplicate of #8051 did not had time for a reproducer though.

**Comment by melloware** [comment] 2021-11-21 01:53
Yep it is a duplicate.  I am going to close 8051 and leave this one open since this one provides a runnable reproducer

**Comment by djmj** [comment] 2021-11-22 14:31
A similar issue we observed today is _SortMeta_ in lazy loading method is not populated for columns where render attribute was updated e.g. columns that were not visible at page load. I will make a test case later.

**Closed as completed** 2021-11-22 15:22 UTC
Labels: :lady_beetle: defect

**Comment by tandraschko** [comment] 2021-11-22 15:23
@dmjm sort code already had the lazy init code and should work

but feel free to create a issue BUT plz not create a issue again and dont provide a reproducer

**Comment by djmj** [comment] 2021-11-22 15:54
Thank you and yes you are right, next time i add a reproducer.
