### ISSUE TITLE
Button: onclick attribute doesn't work as expected in PF 10.0

### ISSUE THREAD

**Issue by jacekzwroclawia** [primefaces/primefaces#7740] opened 2021-08-23 11:45 UTC
Hi,
I've just upgraded PF 8.0 to PF 10.0. But now I have problem with my previously working `<p:button ... />` tags with `onclick` attribute.

PF tag:
`<p:button href="https://www.google.com/" value="Google Search" onclick="someFunction();" />`

**Generated HTML in PF 8.0:**
`<button id="j_idt125:j_idt164" name="j_idt125:j_idt164" type="button" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="someFunction();window.open('https:\/\/www.google.com\/','_self')" role="button" aria-disabled="false"><span class="ui-button-text ui-c">Google Search</span></button>`

**Generated HTML in PF 10.0:**
```<button id="j_idt140:j_idt179" name="j_idt140:j_idt179" type="button" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="someFunction();" role="button" aria-disabled="false"><span class="ui-button-text ui-c">Google Search</span></button>```

So, as you can see there is missing `window.open(...)` function in generated onclick attribute on PF 10.0 and button doesn't work as expected.

**Comment by jepsar** [comment] 2021-08-23 11:49
Duplicate of https://github.com/primefaces/primefaces/issues/7729 ?

**Comment by tandraschko** [comment] 2021-08-23 11:55
duplicate of https://github.com/primefaces/primefaces/issues/7729

11.0 SNAPSHOT works as designed and renders the window.open

**Closed as completed by tandraschko** 2021-08-23 11:55 UTC
Labels: :lady_beetle: defect

**Comment by jacekzwroclawia** [comment] 2021-08-23 12:03
Thanks for answer, for now I use workaround:
`<p:button href="https://www.google.com/" value="Google Search" onmousedown="someFunction()" pt:ontouchstart="someFunction()" />`
