### ISSUE TITLE
Dialog: inside a tab modal=true is blocking also dialog

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#5675] opened 2020-03-11 18:21 UTC
I believe this is bad practice, but a colleague of mine asked me to report. If the dialog is out of tab it works normal.

## 1) Environment
- PrimeFaces version:
- Does it work on the newest released PrimeFaces version? Version? 8.0
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) no
- Application server + version:
- Affected browsers:

## 2) Expected behavior
click on button should open a dialog not blocked
version 7.0 is ok

## 3) Actual behavior

dialog is blocked
	

## 4) Steps to reproduce

click on button

sample project: https://github.com/erickdeoliveiraleal/primefaces-test

**Comment by melloware** [comment] 2020-03-11 18:41
Add `appendTo="@(body)"` fixes it...

```xml
<p:dialog widgetVar="carDialog" modal="true" showEffect="fade"
		header="Adicionar Horas Estudo" hideEffect="fade"
		resizable="false" closeOnEscape="true" closable="true" appendTo="@(body)">
```

**Comment by ralfmohr** [comment] 2020-04-05 20:34
Adding appendTo is a workaround, but the bug still needs to be fixed. A can not see that there commit which fixes this bug. Why is it set to invalid? Please reopen.

**Comment by melloware** [comment] 2020-04-05 21:21
@ralfmohr The dialog has good defaults.  We don't want to ALWAYS attach it to the body thus its not the default and this setting is provided.   @tandraschko can speak to any different reasons why this is not the default

**Comment by melloware** [comment] 2020-04-06 12:02
@ralfmohr  Can you put together a little Example reproducer using PF Test: https://github.com/primefaces/primefaces-test

Then please attach your reproducer to that ticket.  It could be something broke in 8.0 or that some ticket was "fixed" for other reasons causing your issue.

**Comment by tandraschko** [comment] 2020-04-06 12:21
appendTo was/is a hack for older browsers as the a inner DOM element could not be bigger as a outer DOM element; this was probably done for IE6 or 7.

Today its just a workaround for edge cases IMO.

**Comment by melloware** [comment] 2020-04-06 12:35
So @tandraschko should we make @(body) the default?

**Comment by tandraschko** [comment] 2020-04-06 12:50
nope
we should try to analyze the bug here and then decide if we can easy fix it or not.

**Comment by melloware** [comment] 2020-04-06 12:51
got it I see @erickdeoliveiraleal already provided a reproducer.  So @ralfmohr nevermind...

**Comment by melloware** [comment] 2020-04-06 16:31
OK this is working in Elite 7.0.12 and broken in 8.0 but looking at the commits for tabview.js and dialog.js nothing is really standing out.

**Comment by ralfmohr** [comment] 2020-04-07 21:47
Hello Melloware,

I tryed out the primefaces-test fork from Erick de Oliveira Leal with 
the latest primefaces/primefaces on Github, but it did not work.
Are the commits on github or just for primefaces elite?

Greetungs
Ralf

Am 06.04.2020 18:32 schrieb Melloware:

**Comment by melloware** [comment] 2020-04-07 22:04
If you pulled down his example and run `mvn clean jetty:run-exploded` it should work fine?   He has it set for PF8.0 in the pom.xml which is available publicly.

**Comment by ralfmohr** [comment] 2020-04-08 14:24
Unfortunately not. Doing exactly that shows a blocked dialog.
Changing to the latest 9.0-SNAPSHOT has a blocked dialog, too.
Adding appendTo only helps at first glance: the values of input fields 
are not copied to the bean.

Am 08.04.2020 00:05 schrieb Melloware:

**Comment by melloware** [comment] 2020-04-08 14:32
@ralfmohr Maybe we are talking past each other.  @erickdeoliveiraleal example was to SHOW the bug in PF 8.0.  

If you change the pom.xml back to PF 7.0 the example works.  8.0 and 9.0-SNAPSHOT it fails that is the point is to produce the bug.

A better fix is to move your dialog OUTSIDE of the Tabview and into its own `h:form`.

**Comment by melloware** [comment] 2020-04-08 14:36
Attached is a version that works in PF 7, 8, 9 with no appendTo and to me is the proper design for this type of logic.

[pf-5675.zip](https://github.com/primefaces/primefaces/files/4451062/pf-5675.zip)

**Comment by ralfmohr** [comment] 2020-04-09 14:21
In the attached example "pf-5675.zip" you placed the dialog after the tabView.
That does not fit to this defect. It is about modal dialogs within tabs.
I have an existing application with 50 modal dialogs within tabs. It was recently migrated to PF 8.0 and is no longer working. Adding appendTo="@(body)" is no solution. It prevents input values from being copied into the bean.

**Comment by melloware** [comment] 2020-04-09 15:12
@ralfmohr you are killing me...

1. Original Defect shown in this project from @erickdeoliveiraleal : https://github.com/erickdeoliveiraleal/primefaces-test  Just dowload it and run it you will see its your exact bug.

2. My attached project shows you how to fix it properly using PF 7, 8, or 9.

**Comment by jopen-ux** [comment] 2020-04-16 13:37
> Attached is a version that works in PF 7, 8, 9 with no appendTo and to me is the proper design for this type of logic.
> 
> [pf-5675.zip](https://github.com/primefaces/primefaces/files/4451062/pf-5675.zip)

**Comment by jopen-ux** [comment] 2020-04-16 13:40
The simple solution in  example is ok for a simple demo, but is not realistic as  moving the dialog outside the tabview or accordion changes all the update strategy when you have dynamics tabs/ accordions and sophisticated UI. When do you think this regression can be fixed ? as we need to revert back to PF7.0 for the moment

**Comment by tandraschko** [comment] 2020-04-16 13:43
I think the best would be if someone could sponsor a fix via PrimeFaces PRO.

**Comment by jopen-ux** [comment] 2020-04-16 13:52
ON my side it will be too late to wait, a too huge work to change all of our pages (more than hundreds with douzens very sophisticated) and .. customer in prod !!

**Comment by melloware** [comment] 2020-04-16 14:03
You don't have to just add `appendTo="@(body)"` to your dialogs.

**Comment by tandraschko** [comment] 2020-04-16 14:04
In this case it would even better to get the fix into a 8.0.2 :)

**Comment by melloware** [comment] 2020-04-16 14:05
Agreed but for now the ticket is open with no solution.

**Comment by tandraschko** [comment] 2020-04-16 14:05
@melloware maybe but its only a workaround and you have to adjust all pages

**Comment by melloware** [comment] 2020-04-16 14:10
@tandraschko i agree. But the only change between 7 and 8 I can see is this one.

https://github.com/primefaces/primefaces/issues/5520

I reverted that and it had no effect.  So its something deeper.

**Comment by jopen-ux** [comment] 2020-04-16 14:38
If this may help another side effect (that could be reletad ?) is  : a (non modal) dialog inside a tab in PF7 : was correctly displayed even if it's height is greater than the tab height, but is truncated to the tab height in PF8... 
hope may help

**Comment by firsthour** [comment] 2020-04-16 17:34
This is a showstopper for us moving to 8.0. We have multiple mature applications that we are in the process of migrating from 6.2.10 to 8.0 because we're required to upgrade to jquery 3.4.1 due to security. It looks like we can use 7.0.13 to achieve this but we'll be stuck on 7.x until this is solved.

**Comment by aarner42** [comment] 2020-04-16 17:55
In our application we've discovered the dialogs in this situation aren't truly blocked.  While they are obscured/back-grounded and don't accept clicks,  they do have focus when they appear, and **will accept keyboard input.  One can press escape to close it, or tab through the buttons and use the spacebar to _press_ them.**  Any actionListeners, onClose, or other server-side or client-side callbacks _still work fine._  So this may be a subtle rendering issue that's partially hiding the dialog and stopping it from accepting mouse input, but leaving the dialog otherwise totally functional.

**Comment by metaxmx** [comment] 2020-04-20 15:49
Hi, this is a showstopper for us as well, and prevents us from migrating to PrimeFaces 8.0.
I made some analysis, and the problem seems to be, that the new `transform: scale(1)` attribute on the TabView base element creates a new stacking context which basically breaks all z-indexes inside the element.
For details see my explanation #5429 (the original issue that introduced the new `transform: scale(1)` attribute).

As I mentioned in #5429, I'm not sure why we need the `transform: scale(1)` attribute at all. From the description of the other issue it seemed that the original (non-standard) `zoom:1` to be a legacy fix for IE8, and the `transform: scale(1)` was introduced as replacement. Maybe we can just drop this CSS attribute? Or at least roll back the change in #5429. I believe a Javascript console warning is not as important as this kind of layouting bug, which breaks modal dialogs for multiple people.

I would be really happy to have this fixed in the next PrimeFaces Elite version...

**Comment by melloware** [comment] 2020-04-20 16:26
@metaxmx Thanks for investigating.  I will definitely fix it.    So some history on that is I don't believe PrimeFaces should be using a property all browser don't support and `zoom` is a non W3C property that Firefox complains about.  All the articles say to replace zoom with `transform: scale(1)` as the proper W3C CSS attribute supported by all browsers.

Clearly it has this side effect.  I will do some testing and report back!

**Comment by metaxmx** [comment] 2020-04-20 16:31
Thanks, melloware!
Your effort is much appreciated!
I believe, they mean if you want "zoom: 3" you can use "transform: scale(3)" in order to change the objects size. But the original "zoom: 1" was only introduced as an Internet Explorer Hack (to give an element "hasLayout", so the old IE layouting would be better - see e.g. https://stackoverflow.com/questions/1794350/what-is-haslayout); we don't actually zoom any element here ...

**Comment by melloware** [comment] 2020-04-20 16:52
OK removed them all and tested in IE11, Edge, Chrome, and Firefox and everything is working.  Seems this was truly an IE8 hack and PF no longer supports IE8.

**Closed as completed** 2020-04-21 10:56 UTC
Labels: :lady_beetle: defect, 8.0.2

**Comment by melloware** [comment] 2020-06-01 11:40
8.0.2 Elite was released today which fixes this issue.
