### ISSUE TITLE
DataExporter: with type XLS and XLSX exportHeader doesn't works

### ISSUE THREAD

**Issue by raul810y** [primefaces/primefaces#10224] opened 2023-06-14 03:57 UTC
### Describe the bug

When uses "DataExporter" with "type" XLS or XLSX,  attribute "exportHeader" is ignored (with or without attribute does't export the header row, with type CSV works fine) 

### Reproducer

1. Go to DataExporter primefaces demo: 
https://www.primefaces.org/showcase/ui/data/dataexporter/basic.xhtml?jfwid=a4418
2. Clic "XLS" or "XLSX" button
3. File downloaded doesn't include a header row (According to documentation, attribute "exportHeader" default value is true, but even add that attibute is the same result)

### Expected behavior

When export a XLS or XLSX file must include a header row.

### PrimeFaces edition

Community

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

8 and later

### Browser(s)

Chrome Versión 111.0.5563.64 (Build oficial) (x86_64) macOS

**Comment by jepsar** [comment] 2023-06-14 06:07
Duplicate of #9290

**Closed as completed** 2023-06-14 06:07 UTC
Labels: Resolution: Duplicate

**Comment by melloware** [comment] 2023-06-14 09:48
@raul810y you can use 13.0.0-RC1 which is in Maven Central if you are not an Elite subscriber.
