### ISSUE TITLE
textEditor does not render properly when using CelEdit (in dataTable)

### ISSUE THREAD

**Issue by Dragonsol** [primefaces/primefaces#2649] opened 2017-08-18 14:53 UTC
1) Environment

    PrimeFaces version: PrimeFaces 6.2-SNAPSHOT (August 15, 2017)
    Application server + version: WildFly 10.1.0
    Other: Hibernate 5
    Affected browsers: all

2) Expected behavior

textEditor to be properly rendered.

3) Actual behavior

In "view" mode, it works properly and displays the data as expected.
![pic1](https://user-images.githubusercontent.com/8823006/30273361-adf4e824-96c6-11e7-8b2b-d90326c94e85.png)

However, when you click on the cell to edit the data, the entire cell being edited becomes greyed out with only text (value attribute) visible. There is no ability to edit anything in the cell.
![pic2](https://user-images.githubusercontent.com/8823006/30273376-be598b16-96c6-11e7-95dd-fc5f8eceea02.png)

4) Steps to reproduce

5) Sample XHTML

 <p:dataTable id="table" value="#{requirementManagedBean.requirementList}" var="iterator"
                         editable="true" editMode="cell"
                         paginator="true" rows="10"
                         sortBy="#{iterator.requirementName}">
...
...
...

<p:column sortBy="#{iterator.requirementDescription}" filterBy="#{iterator.requirementDescription}" filterMatchMode="contains" headerText="Description" width="30%">
                    <p:cellEditor>
                        <f:facet name="output">
                            <p:textEditor value="#{iterator.domainDescription}" readonly="true" toolbarVisible="false"/>
                        </f:facet>
                        <f:facet name="input">
                            <p:textEditor value="#{iterator.requirementDescription}" />
                        </f:facet>
                    </p:cellEditor>
                </p:column>
..
## 6) Sample bean

Not applicable

**Comment by melloware** [comment] 2017-12-09 17:41
@Dragonsol can you try this again since we just updated 6.2-SNAPSHOT to use the latest version of QuillJS and report back if it is still an issue?

**Comment by jxmai** [comment] 2017-12-17 05:23
I don't think this feature (cellEdt with advanced text editor) ever worked even with the original `p:editor`.

---

Eveything needs to be explained by the celleditor's architecture. If you look at the implementation:

https://github.com/primefaces/primefaces/blob/481fdff1c23dfff61425afd2800d3d93d4c2c5c3/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L2392-L2398

the inputcontainer is pure html without invoking any js to transform into an editor beforehand.  If user uses `p:textEditor` as input, the render result will only be a div. As a result,

> However, when you click on the cell to edit the data, the entire cell being edited becomes greyed out with only text (value attribute) visible. There is no ability to edit anything in the cell.

**Comment by Dragonsol** [comment] 2018-01-22 01:07
Sorry, it took me a while to compile the latest snapshot (January 21, 2018). The result is the same - it is not possible to use <p:textEditor> within <p:dataTable> when editable="true" editMode="cell".

**Comment by Dragonsol** [comment] 2018-01-22 01:09
@jxmai, what do you suggest to use as a rich text editor within a data table?

**Comment by jxmai** [comment] 2018-01-22 04:21
@Dragonsol If I am not mistaken, the rich text editor does not render in input mode by design currently. 

> https://github.com/primefaces/primefaces/blob/55eae01b63e22058efc2bdab7985b3e0d517b1d8/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L2394

> the inputcontainer is pure html without invoking any js to transform into an editor beforehand. If user uses p:textEditor as input, the render result will only be a div.

I would say it might be a flaw in PF but I am not entirely sure the best way to fix it :thinking: . 

---

As a workaround: If you do need an rich editor in datatable, you can put an icon /a  link in a cell to invoke a dialog with any rich editor. That's the way I tackle similar requirements for now.

**Comment by melloware** [comment] 2020-03-17 20:13
The CellEditor was definitely not designed to have a Rich Text Editor in the cell.  Plus that seems like a really funky bad UI design. Closing this issue.

**Closed as completed by melloware** 2020-03-17 20:13 UTC
