### ISSUE TITLE
DataTable decoding does not consider dynamically added/removed columns correctly

### ISSUE THREAD

**Issue by jessepeng** [primefaces/primefaces#2110] opened 2017-02-22 15:04 UTC
## 1) Environment
- PrimeFaces version: 6.0
- Application server + version: Tomcat 8.5.8 with Mojarra 2.2.14
- Affected browsers: all

## 2) Expected behavior

When adding/removing columns dynamically (e.g. using `getChildren().add()`), attached AJAX events to these columns or components inside these columns should get fired on every request. In detail, the `processChildren()` method should iterate over all actual children at every point in time.

## 3) Actual behavior

The `processChildren()` method iterates over the table's columns using `getIterableChildren()`. In `DataTable` this method is overwritten as follows:

```
@Override
    protected List<UIComponent> getIterableChildren() {
        if(iterableChildren == null) {
            iterableChildren = new ArrayList<UIComponent>();
            for(UIComponent child : this.getChildren()) {
                if(!(child instanceof ColumnGroup)) {
                    iterableChildren.add(child);
                }
            }
        }
        
        return iterableChildren;
    }
```

As one can easily see, once `iterableChildren` is set during first rendering, this method does not reflect further changes to the column structure. So if after the first rendering, a column is added using `getChildren().add()`, it will not be considered in further calls to `processChildren()`.

By the way, `getColumns()` suffers from the same assumption that columns won't be changed in between two requests. However, there is a `setColumns(...)` method that can be used to make the table "forget" about it's previous columns.

## 4) Steps to reproduce

* Create a DataTable
* Add column dynamically (using `getChildren().add()`) and add AJAX behavior to this column (e.g. by adding a CommandButton)
* Render table
* Notice that AJAX event will get fired
* Do something with column structure (e.g. add/remove a column) with AJAX behavior
* Restore view and render table again (e.g. using a postback request)
* Notice that AJAX event will not get fired

## 5) Possible fixes for this problem

Easy fix 1: Just as there is a `setColumns(List<UIColumn> columns)` method, there should be a `setIterableChildren()` method to reset `iterableChildren` so that the table notices that there are different children.

Easy fix 2: Do not save the iterable columns in an instance variable, but do the iteration every time the method is called (probably bad idea, since it's called during every request phase and changes in between the request phases should not happen).

More complex but better fix (not tested, just an idea): using for example a `PostAddToViewEvent`, columns could notify their parent table that they have been added and that the lists `columns` and `iterableColumns` should be invalidated.

**Comment by tandraschko** [comment] 2017-02-24 16:38
Please provide as sample java / xhtml as requested in the issue template.

**Comment by melloware** [comment] 2020-08-06 14:21
Reproducible example was requested but the OP has not provided.  Will reopen if reproducer is provided.

**Comment by tandraschko** [comment] 2020-08-06 14:34
Let me check that, even If we dont have a reproducer, the bad code might still be there

**Comment by tandraschko** [comment] 2020-08-06 19:57
should be fixed now - feel free to retest and review

**Closed as completed by tandraschko** 2020-08-06 19:57 UTC
Labels: :lady_beetle: defect

**Comment by tandraschko** [comment] 2020-08-06 20:08
how can i configure my git? your commit now crashes my next commit...

**Comment by melloware** [comment] 2020-08-06 20:10
So our `.gitattributes` file in the root dir already has this..
```
# Declare files that will always have CRLF line endings on checkout.
*.sln text eol=crlf
```
I am not sure why your git client doesn't respect that but I use both SmartGit and IDEA Git and both respect that and always correct the line endings before I commit.

**Comment by tandraschko** [comment] 2020-08-06 20:11
i use netbeans at home, no idea...

**Comment by melloware** [comment] 2020-08-06 20:13
Ahh and we have this set:
```
# Set the default behavior, in case people don't have core.autocrlf set.
* text=auto
```

Which according to the docs https://git-scm.com/docs/gitattributes 

Set to string value "auto"
When text is set to "auto", the path is marked for automatic end-of-line conversion. If Git decides that the content is text, its line endings are converted to LF on checkin. When the file has been committed with CRLF, no conversion is done.

I wonder if we need to set `eol` as well?

**Comment by tandraschko** [comment] 2020-08-06 20:15
to be honest, i dont care about lineending
it always works on github and my client, doesnt matter if you use your or mine lineending
just annoying all the time

**Comment by melloware** [comment] 2020-08-06 20:16
Well the problem is look at your commit: https://github.com/primefaces/primefaces/commit/a0ea3fc5c2988b98b5f34933f00d93664be22893

It looks like you edited the entire file so I can't tell what you changed.

**Comment by melloware** [comment] 2020-08-06 20:17
Same with this commit: https://github.com/primefaces/primefaces/commit/b7cd83e4dd4d05338d6a1fb7f8a7ddb5dc05d3d1  it looks like you are changing the entire file because eveyr single line got updated with a new line ending.

**Comment by melloware** [comment] 2020-08-06 20:18
And then when I do a Git Pull to refresh my fork it thinks those files are different and Git forces me to fix the line endings before committing further.

**Comment by tandraschko** [comment] 2020-08-06 20:18
then we have to configure our gitattributes to work on all clients the same, everything else doesnt make sense

**Comment by melloware** [comment] 2020-08-06 20:20
Agreed.  @Rapster @christophs78 any idea on this line ending problem?

**Comment by melloware** [comment] 2020-08-06 20:25
Found this article: https://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/

it looks like we are doing it correctly but it looks like your Netbeans is somehow not respecting it?

_One final note that the man page for gitattributes mentions is that you can tell git to detect all text files and automatically normalize them (convert CRLF to LF):_

`*       text=auto`

**Comment by tandraschko** [comment] 2020-08-06 20:34
no idea, sorry
really no time to read why we changed the settings it in the past, i never had problems before AFAIR
i have some deadlines about the CSV topics

**Comment by melloware** [comment] 2020-08-06 23:32
The .gitattributes has been like that for 3+ years.  I have read multiple bugs online that NetBeans uses JGit under the covers and JGit does not respect `.gitattributes`.  I don't know if that is the case but it definitely seems like it.  I am really leaning into this is a Netbeans issue.

All files should be checked in with just LF and that is what `* text=auto` does.  Somehow Netbeans is checking in files with CRLF which is not correct and making he whole file look like it has changed in GitHub.

See: https://stackoverflow.com/questions/61943608/configuring-git-in-netbeans

Also: https://stackoverflow.com/questions/3294451/how-to-change-the-line-ending-used-in-netbeans

_Netbeans does not seem to correctly support .gitattributes. It uses JGit behind the scenes: bugs.eclipse.org/bugs/show_bug.cgi?id=342372 (chaotic) . I has struggling to findout why some sometimes newlines were added as CRLF and sometimes they weren't. It depended on whether Netbeans was used to add the files or the git cli._

This is exactly the problem you are seeing.

**Comment by Rapster** [comment] 2020-08-19 08:31
@tandraschko please could have a look at your settings regarding this EOL issue? It keeps happening...

**Comment by tandraschko** [comment] 2020-08-19 08:35
i have to switch to intellij as not supported in NB but this wont happen before autumn.
