### ISSUE TITLE
Reproduced with PF 7.0.

### ISSUE THREAD

**Issue by alejandrojimenezgarcia89** [primefaces/primefaces#5740] opened 2020-03-31 08:03 UTC
I have problems with this issue but modifying a bit the xhtml file

[pf-5709.zip](https://github.com/primefaces/primefaces/files/4354617/pf-5709.zip)

1. Unzip the above zip.
1.1 Modify xhtml allowing scroll
2. Run `mvn clean jetty:run-exploded`
2.1 In chrome , zoom out, and scroll down
3. Navigate to http://localhost:8080/primefaces-test/test.xhtml

Example xhtml:
```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

	<h:head>
		<title>PrimeFaces Test</title>
	</h:head>
	<h:body>
		<h:form>
			<p:commandButton value="Show" type="button" onclick="PF('dlg1').show();" />
			<p:dialog widgetVar="dlg1" modal="true" width="1100" appendTo="@(body)" resizable="false" draggable="true" closable="false">
				<p:calendar locale="de" value="#{dateController.endTime}" pattern="dd.MM.yyyy HH:mm:ss"/>
			</p:dialog>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<p>lalalallalalalalalallalalalallalalal</p>
		</h:form>

	</h:body>
</html>
```
![image](https://user-images.githubusercontent.com/29012803/78002396-787bdb80-7337-11ea-9bf1-cb1bb4358496.png)

**Comment by alejandrojimenezgarcia89** [comment] 2020-03-31 08:09
More scroll
![image](https://user-images.githubusercontent.com/29012803/78002501-a19c6c00-7337-11ea-9572-25dc2fade338.png)

**Comment by tandraschko** [comment] 2020-03-31 08:17
I think its a duplicate of: https://github.com/primefaces/primefaces/issues/4609

**Comment by tandraschko** [comment] 2020-03-31 08:25
As its still not fixed by Mert, it would be great if someone could take care of it via PrimeFaces PRO.

**Comment by alejandrojimenezgarcia89** [comment] 2020-03-31 08:26
Is not duplicate, is look like https://github.com/primefaces/primefaces/issues/5709, but scrolling de body

**Closed as completed by tandraschko** 2020-03-31 08:25 UTC
Labels: Resolution: Duplicate

**Comment by tandraschko** [comment] 2020-03-31 08:29
Yep, but i'm sure it's the same reason

as workaround you could set blockScroll=true to the dialog

**Comment by alejandrojimenezgarcia89** [comment] 2020-03-31 08:31
No, i don't want use blockScroll=true, my page must has scroll and the page contains a table and every row click display a dialog

**Comment by melloware** [comment] 2020-03-31 11:51
@alejandrojimenezgarcia89 I would subscribe to the #4609 ticket and try and sponsor it via PRO or a 1 time "get a quote" from PrimeTek to fix it. It is definitely the same issue you are reporting above.

**Comment by alejandrojimenezgarcia89** [comment] 2020-04-01 06:42
@melloware @tandraschko ok, thank you guys
