### ISSUE TITLE
Provide a way to add a new tab, without updating the whole tabView

### ISSUE THREAD

**Issue by abeel** [primefaces/primefaces#1994] opened 2016-12-30 11:08 UTC
When a p:tab is added to p:tabView all other tabs is processed/rerendered to (which might be costly) if we have organized our application on tabs.

**Comment by tandraschko** [comment] 2017-01-27 21:56
Duplicate of #1541
Next time please search in the issue tracker before creating new issues.

**Closed as completed by tandraschko** 2017-01-27 21:56 UTC
Labels: Resolution: Duplicate
