### ISSUE TITLE
DF Cann't be used in iframe

### ISSUE THREAD

**Issue by zsuiqiang** [primefaces/primefaces#1253] opened 2016-03-21 08:26 UTC
`<iframe src="data.jsf" style="width: 100%;height: 600px;" name="workspace" scrolling="auto"/>`

data.xhtml is as same as in showcase.

**Comment by tandraschko** [comment] 2016-03-31 20:37
A PR would be great.

**Comment by zsuiqiang** [comment] 2016-04-26 06:47
The problem exist from 5.3.6 to 5.3.11, why not fix?

**Comment by tandraschko** [comment] 2016-04-27 14:36
why not provide a PR?
Is there a JS error?

**Comment by zsuiqiang** [comment] 2016-04-29 01:08
http://forum.primefaces.org/viewtopic.php?f=3&t=45274

**Comment by zsuiqiang** [comment] 2016-05-10 03:44
Is this issue confirmed? When to solve?

**Comment by ndrikdarto** [comment] 2017-06-17 01:17
@tandraschko 
I think, there is a JS error.
The method RequestContext.getCurrentInstance().closeDialog(Object) won't close the dialog and the dialogReturn method is not invoked. In Firebugs console give a JS error.

![pf fd error js](https://user-images.githubusercontent.com/29494455/27248942-17cafcf0-5335-11e7-849c-4096c255d2a9.PNG)

I tried this with Primefaces 6.1 community library. When I changed back to 5.3 community library, this bugs was not appear.

Could someone please check this issue?

**Comment by tandraschko** [comment] 2017-10-17 13:58
duplicate of #1403

**Closed as completed by tandraschko** 2017-10-17 13:58 UTC
Labels: Resolution: Duplicate

**Comment by dani7120** [comment] 2019-01-29 03:16
Hi, this issue was solved and released?

**Comment by melloware** [comment] 2019-01-29 12:39
@dani7120 Yes it was fixed in PF 6.2 or higher: https://github.com/primefaces/primefaces/issues/1403
