### ISSUE TITLE
SelectCheckBoxMenu group item selection

### ISSUE THREAD

**Issue by prancius** [primefaces/primefaces#12913] opened 2024-11-19 13:31 UTC
### Description

SelectCheckBoxMenu group item selection

### Describe the solution you would like

When using SelectCheckBoxMenu with grouped items need checkbox nearly group name to check / uncheck group items

**Comment by tandraschko** [comment] 2024-11-19 13:32
why did you create a new issue? its a duplicate of #3524 ?

**Closed as completed** 2024-11-19 15:04 UTC
Labels: Resolution: Duplicate
