### ISSUE TITLE
selectOneRadio with a custom layout in a datatable is disabled after sorting or paging

### ISSUE THREAD

**Issue by tripleentendre** [primefaces/primefaces#1329] opened 2016-04-21 20:52 UTC
I added a selectOneRadio with a custom layout to a datatable and everything works as expected until I either sort or change the number of records being displayed. After that the radio button is disabled. The issue can be reproduced in the attached project.

[poc.zip](https://github.com/primefaces/primefaces/files/230721/poc.zip)

**Comment by melloware** [comment] 2020-03-17 19:51
Can't reproduce and provided runner is missing code needed to run it.  Closing.

**Closed as completed by melloware** 2020-03-17 19:51 UTC
