### ISSUE TITLE
TreeTable: CommandButton/CommandLink seem not to work properly inside a treeTable on SubElements

### ISSUE THREAD

**Issue by Michael-Breu-UIbk** [primefaces/primefaces#3682] opened 2018-05-18 10:59 UTC
## 1) Environment: 
Primefaces 6.2 (both Windows 10 and Debian Linux latest) tomcat 8.5. Tested with latest Firefix. 

## 2) Expected behavior
CommandButtons and CommandLinks should work properly on all levels of a treeTable.

## 3) Actual behavior

It seems, for certain circumstances (bean is requestScoped? rows are not preexpanded programmatically before?), that the command is only executed on top level rows.

## 4) Steps to reproduce

- SetUp a request-scoped bean, that returns a TreeNode .
- Include it in a treeTable. Insert a p:commandButton on each row.
- open page in browser: you should see only top level rows
- On Top Level the commandButton works,
- however if you open a sub element and click on button, it doesn't work

The demo page below shows also a table with preexpaned rows. There the buttons work properly.

## 5) Sample XHTML
(mainly from showcase)
[demo-xhtml.txt](https://github.com/primefaces/primefaces/files/2016538/demo-xhtml.txt)

## 6) Sample bean
Java-Code (mainly copied from showcase)
[ErrorDemo-java.txt](https://github.com/primefaces/primefaces/files/2016539/ErrorDemo-java.txt)

**Comment by tandraschko** [comment] 2020-12-14 16:05
@melloware would you also like to retest? we have something similar in our app and it works fine

**Comment by melloware** [comment] 2020-12-14 17:36
I have verified this is still broken.  Attached is reproducer:
[pf-3682.zip](https://github.com/primefaces/primefaces/files/5690565/pf-3682.zip)

**Comment by melloware** [comment] 2020-12-14 17:54
Nevermind this is because its `RequestScoped` and it is destroying and re-creating the TreeModel every request.  I don't think this is expected use case.  If I switch it to `SessionScoped` or `ViewScoped` everything works perfectly.  

I think we should close this ticket.

**Comment by tandraschko** [comment] 2020-12-14 17:56
yep, thats by design. Same happens in repeat or datatable.

**Closed as completed by tandraschko** 2020-12-14 17:56 UTC
Labels: :lady_beetle: defect
