### ISSUE TITLE
calendar: validation error

### ISSUE THREAD

**Issue by giorgioprimefaces** [primefaces/primefaces#4813] opened 2019-05-16 15:19 UTC
I just discovered that with PF7 (test made with PF 7.0.2) all my calendars with mindate=value (didn't test maxdate) I get the following validation error:
"Validation Error: Value is out of range."

## 1) Environment
 PrimeFaces version: 7.0.2
working with PF 6.x.x 

Affected browsers: all

## 2) Expected behavior
no validation error

## 3) Actual behavior
throws a validation error which is corrupting the page

## 4) Steps to reproduce

use the same date in mindate and value

## 5) Sample XHTML

 <!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>
        <h:form id="form">
            <p:growl id="msgs" showDetail="true" />
            <p:calendar id="c1"  value="#{bean.data1}"
              pattern="dd/MM/yyyy"  navigator="true"
             showOn="button"  />

            <p:calendar  id="c2"  value="#{bean.data2}"
             mindate="#{bean.data1}"
             pattern="dd/MM/yyyy"  navigator="true"
             showOn="button"  />
        </h:form>
    </h:body>
</html>
 
## 6) Sample bean 

@ViewScoped
public class Tcalendar implements Serializable {
     
    private Date data1;
    private Date data2;

    @PostConstruct
    public void init() {
       data1=new Date();
       data2=data1;

    }
 
    public Date getData1() {
        return data1;
    }

    public void setData1(Date data1) {
        this.data1 = data1;
    }

    public Date getData2() {
        return data2;
    }

    public void setData2(Date data2) {
        this.data2 = data2;
    }
}

**Comment by tandraschko** [comment] 2019-05-16 15:21
A valid issue constists either of a full xhtml+bean or a forked primefaces-test project!

**Comment by melloware** [comment] 2019-05-16 20:33
Reproducer: 
[pf-4813.zip](https://github.com/primefaces/primefaces/files/3188934/pf-4813.zip)

Simply select the 2nd calendar and pick the same date and you see the error.  Pick a future day and no error.

**Comment by cnsgithub** [comment] 2019-05-17 04:58
Wrong usage?

> Simply select the 2nd calendar and pick the same date and you see the error.

When debugging `Calendar.validateValue`:
```
minDate: Fri May 17 06:50:27 CEST 2019
date: Fri May 17 00:00:00 CEST 2019
```
=> `date > minDate`
=> `minDate=new Date()` (instantiation time)

Try to first select another date in the first calendar (this will force the date's time to be _00:00:00_), then select the very same date in the second calendar. You will realize it's working then.

**Comment by giorgioprimefaces** [comment] 2019-05-17 07:03
no wrong usage, 
onload if the mindate=value starting from PF 7.0.2 (not tested 7.0.1) it throws the validation error, than it is possible to select another date in the second calendar, but you already had the error, which is pretty annoying...

**Comment by cnsgithub** [comment] 2019-05-17 07:18
> PF 7.0.2 (not tested 7.0.1) it throws the validation error

Because PF < 7 did not have any validation at all.

You agree that `Fri May 17 00:00:00 CEST 2019` is less than `Fri May 17 06:50:27 CEST 2019`?

You have to know that `p:calendar` is not only able to deal with date-only dates, but also with datetime dates.

Hopefully, things will get better when the new Java datetime API is supported. Then you should be able to use either `LocalDate` or `LocalDateTime` and such unsuspected behaviours should no longer occur...

Maybe you could do something like this as a workaround:
````java
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        data1 = cal.getTime();
        data2 = data1;
````

**Comment by giorgioprimefaces** [comment] 2019-05-17 08:57
[pf-4813_v2.zip](https://github.com/primefaces/primefaces/files/3190699/pf-4813_v2.zip)
Just performed some more testing: in the attached example validation error is thrown on button click (non ajax), which means that non ajax navigation is not working anymore with those validation controls

**Comment by cnsgithub** [comment] 2019-05-17 09:07
@giorgioprimefaces There is no need to include compiled classes... :wink: 

Update: I am not sure what you want to prove with `pf-4813_v2.zip`. The reason is the same in all cases. Sorry, this is a wontfix issue for me.

**Comment by giorgioprimefaces** [comment] 2019-05-17 11:11
@cnsgithub  the provided zip shows that non ajax navigation is corrupted by that validation check, since it is feasible to select a date=mindate, this should not happen!

**Comment by cnsgithub** [comment] 2019-05-18 18:52
> non ajax navigation is corrupted by that validation check

It does not matter if form params are submitted via ajax or non-ajax, **all** submitted values **must** be valid, **always**. And that's not the case in your examples! I'm out.

**Comment by giorgioprimefaces** [comment] 2019-05-20 08:44
@cnsgithub 
Sorry, probably I do not get the point but here's another example which is showing some strange behaviour of this validation:
as you can see now we have 2 different scenarios:
1-your workaround (removed hours, minutes, seconds and milliseconds)
same datetime in milliseconds (1558303200000=1558303200000), no validation error

2-no hours, minutes, second and milliseconds removed, same datetime as shown in milliseconds
1558341197764=1558341197764
now I get the validation error

[![cal2.png](https://i.postimg.cc/3rvgHB6F/cal2.png)](https://postimg.cc/3W3yXg3k)

here's the test case, by running it you get the validation error both inizializing
` data3 = new Date();
        data4 = data3;`
or
`  data3 = new Date();
        data4 = new Date();`
even more, in this latter scenario I do not expect a validation error since data4 is inizialized **after** data3 which means that we can **only** have data4>=data3 
[pf-4813_v3.zip](https://github.com/primefaces/primefaces/files/3196981/pf-4813_v3.zip)

**Comment by melloware** [comment] 2019-05-30 14:44
OK I have been testing this with my production application and everything appears to be working properly.  It throws the error when its before mindate, works fine if it is equal to or greater than mindate.

**Closed as completed** 2019-06-21 08:21 UTC
Labels: :lady_beetle: defect, Resolution: Invalid
