### ISSUE TITLE
Calendar: Timezone looks not to work properly regarding to ui-datepicker-today

### ISSUE THREAD

**Issue by dennyboechat** [primefaces/primefaces#275] opened 2015-05-14 00:23 UTC
Example of issue:
The user's computer has New Zealand timezone set (i.e. UTC+12), but his/her application has Samoa timezone set (i.e. UTC-11), including the Calendar component through "timeZone" property.
The problem occurs with the highlighted date shown as "today" due to it considers the New Zealand timezone, not Samoa. It is evident because we were expecting to see one day before (e.g. if in New Zealand it is 14/05/2015, in Samoa should be 13/05/2015).

Primefaces version: 5.2.1
Server: Glassfish 4.0
Browser: Chrome, Firefox, IE11

This ticket is related to:
https://code.google.com/p/primefaces/issues/detail?id=7851

**Comment by cagataycivici** [comment] 2015-05-16 08:02
Can you provide a pull request?

**Comment by frederikd** [comment] 2015-05-17 03:26
@cagataycivici we currently don't have a fix for this, but we'll try to come up with a solution and post the pull request as soon as we can.

**Comment by olpf** [comment] 2015-06-23 08:08
I can reproduce this. Just a question: if I set the timezone of the calendar to "Pacific/Pago_Pago" for instance, shouldn't be the managed bean date property have this timezone? Mine got the default timezone "Europe/Berlin" in my case.

**Comment by cagataycivici** [comment] 2015-06-24 07:13
Note that timeZone attribute is used during conversion of the submitted value, I don't think it is used anywhere at client side. So user submits Samoa time but it gets converted using New Zealand time. For conversion process, it needs to know about the offset right?

https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset

Could we just put this info in hidden variable and submit it as well to be used at conversion at server side?

**Comment by frederikd** [comment] 2015-06-24 21:15
@cagataycivici I am not sure how submitting something to the server will help in this context. The problem is seemingly on the client side only. In our scenario we don't care about the computer's/client's time zone, but only about the one that the user can choose themselves in their user profile.
On the server side everything is handled as UTC, so conversion is happening already based on user profile's time zone and that is working all fine. The only thing that is not working at the moment is the default value of "today" in the calendar component.
So from my understanding the timeZone attribute is used on the client side, but not for deciding what "today" is.

**Comment by cagataycivici** [comment] 2015-06-25 16:49
Ok, I think datepicker plugin's today button just gets the local time from user computer with no ability for timezone offset, I've found this;

http://blog.pocko.org/2010/04/jquery-datepicker-utc-offset-feature/

**Comment by frederikd** [comment] 2015-06-25 20:53
That looks exactly like the issue we are having. Is there any way to support this as part of Primefaces, or would we have to do our own override for this?

**Comment by melloware** [comment] 2020-06-14 11:28
This looks like it was fixed along the way as this method in in the jquery.pfextensions.js override file.
```javascript
    $.datepicker._gotoToday = function (id) {
        var target = $(id),
                inst = this._getInst(target[0]);

        original_gotoToday.call(this, id);
        this._selectDate(id, this._formatDate(inst, inst.selectedDay, inst.drawMonth, inst.drawYear));
    };
```

**Closed as completed by melloware** 2020-06-14 11:28 UTC
Labels: :lady_beetle: defect
