### ISSUE TITLE
Update quill from 1.3.1 to 1.3.3

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#2803] opened 2017-10-11 17:02 UTC
https://github.com/quilljs/quill/compare/v1.3.1...v1.3.3

**Comment by jxmai** [comment] 2017-10-11 17:43
We really should evaluate the regression first since 1.3.0. See #2802

**Comment by tandraschko** [comment] 2017-10-11 17:49
First, we should check if fixed in 1.3.3.
If not, try if we can workaround it in PF, otherwise create a issue there.
However, i don't have time sry.

**Comment by jxmai** [comment] 2017-10-11 17:51
Agree. will take a look later

**Comment by jxmai** [comment] 2017-10-11 21:35
Update quill to 1.3.3 does not fix the problem. More details will be post back to #2802. I suspect the issue is triggered by the change of `picker.js` in quill js. by https://github.com/quilljs/quill/pull/1576/commits/83bc6912304f6347e9264ae94cd1a9881a2478fb Not 100% sure yet.


Also that commit was a part of the 1.3.0 released, which strengthen my assumption

https://github.com/quilljs/quill/releases

![image](https://user-images.githubusercontent.com/10467831/31468122-14e4e212-aea2-11e7-9b93-de8ca12593c6.png)

**Comment by jxmai** [comment] 2017-10-11 22:34
Analysis in https://github.com/primefaces/primefaces/issues/2802#issuecomment-335961894, but I lean toward downgrade quill back to 1.2.6 for PF 6.2.

**Comment by jxmai** [comment] 2017-11-09 02:21
@tandraschko This issue can be closed since I can confirm 1.3.3 is also a buggy version.

---

I am currently negotiating with quill maintainer for that regression, and it might take some time. Hopefully we can see some result soon. :pray:

**Comment by tandraschko** [comment] 2017-11-09 08:15
All right, please come back if you have news!

**Closed as completed by tandraschko** 2017-11-09 08:15 UTC
Labels: enhancement
