### ISSUE TITLE
DatePicker: showTime not detected automatically for LocalDateTime

### ISSUE THREAD

**Issue by tuerker** [primefaces/primefaces#6458] opened 2020-10-28 11:24 UTC
In the migration document (8->9), it is stated that the attribute showTime is detected automatically based on value-binding to LocalDateTime. I cannot nor verify this for the latest PF9-snapshot. Could somebody please check and fix this. Many thanks in advance.

**Comment by tandraschko** [comment] 2020-10-28 11:26
Please always a attach a reproducer, otherwise we may close it as invalid.

**Comment by tuerker** [comment] 2020-10-28 11:36
Please use the LocalDateTime example of your showcase 

https://www.primefaces.org/showcase/ui/input/datepicker/datePickerJava8.xhtml 

```
   <p:outputLabel for="time1" value="Time:" />
   <p:datePicker id="time1" value="#{calendarJava8View.dateTime1}" showTime="true"/>
```

 and leave away the attribute showTime. Is it still working as expected?

In my case:

```
<p:datePicker
            value="#{workflowStep.startDateTime}"
            pattern="yyyy-MM-dd HH:mm:ss"/>
```

where startDateTime is of class LocalDateTime, it is not working.

**Comment by melloware** [comment] 2020-10-28 11:40
The code is definitely trying to do that:
```java
if (datepicker.isShowTimeWithoutDefault() == null) {
            Class<?> type = datepicker.getTypeFromValueByValueExpression(context);

            if (type != null) {
                datepicker.setShowTime(LocalDateTime.class.isAssignableFrom(type));
            }
            else {
                datepicker.setShowTime(CalendarUtils.hasTime(pattern));
            }
        }
```

So I wonder if somehow your Type is not being detected as LocalDateTime.

**Comment by tuerker** [comment] 2020-10-28 11:48
Java attribute is definitively LocaldDateTime:

```
    /**
     * Get endDateTime.
     *
     * @return the endDateTime
     */
    public LocalDateTime getEndDateTime() {
        return endDateTime;
    }

    /**
     * Get startDateTime.
     *
     * @return the startDateTime
     */
    public LocalDateTime getStartDateTime() {
        return startDateTime;
    }

```

PF code fragment (here adapted to show the difference):

```
        <h:outputText value="#{messages.startDateTimeLabel}" />
        <ui:decorate template="/fragments/required.xhtml">
          <p:datePicker
            id="startDateTime"
            value="#{workflowStep.startDateTime}"
            pattern="yyyy-MM-dd HH:mm:ss"
            showButtonBar="true"
            yearNavigator="true"
            inputStyle="width: 122px">
          </p:datePicker>
        </ui:decorate>

        <h:outputText value="#{messages.endDateTimeLabel}" />
        <ui:decorate template="/fragments/edit.xhtml">
          <p:datePicker
            id="endDateTime"
            value="#{workflowStep.endDateTime}"
            pattern="yyyy-MM-dd HH:mm:ss"
            showTime="true"
            showSeconds="true"
            showButtonBar="true"
            yearNavigator="true"
            inputStyle="width: 122px">
          </p:datePicker>
        </ui:decorate>

```

produces

![Screenshot from 2020-10-28 12-47-53](https://user-images.githubusercontent.com/10051373/97432169-d5fef780-191b-11eb-8b87-38e6dbd098d2.png)

while it comes even worse such that the date picker for the startdatetime (which does not use the attribute showTime) is even not popping up.

**Comment by melloware** [comment] 2020-10-28 11:55
Works fine for me:
[pf-6458.zip](https://github.com/primefaces/primefaces/files/5451643/pf-6458.zip)

Run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/test.xhtml

**Comment by tandraschko** [comment] 2020-10-28 12:00
therefore issues without attached primefaces-test are actually invalid :P

**Comment by melloware** [comment] 2020-10-28 12:14
@tuerker can you run my example above and if verified please close ticket.

**Comment by tuerker** [comment] 2020-10-28 12:17
unfortunately not. build fails. 

```
/primefaces$ mvn clean jetty:run
[INFO] Scanning for projects...
Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.pom (4.7 kB at 67 kB/s)
Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/maven/plugins/maven-plugins/12/maven-plugins-12.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/12/maven-plugins-12.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/12/maven-plugins-12.pom (12 kB at 559 kB/s)
Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/maven/maven-parent/9/maven-parent-9.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/9/maven-parent-9.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/9/maven-parent-9.pom (33 kB at 1.1 MB/s)
Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.3/maven-antrun-plugin-1.3.jar (24 kB at 1.1 MB/s)
Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.pom (15 kB at 758 kB/s)
Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/maven/plugins/maven-plugins/16/maven-plugins-16.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/16/maven-plugins-16.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/16/maven-plugins-16.pom (13 kB at 647 kB/s)
Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.2-beta-5/maven-assembly-plugin-2.2-beta-5.jar (209 kB at 5.2 MB/s)
Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.pom (11 kB at 573 kB/s)
Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.jar (153 kB at 5.3 MB/s)
Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/maven/plugins/maven-release-plugin/2.1/maven-release-plugin-2.1.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.1/maven-release-plugin-2.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.1/maven-release-plugin-2.1.pom (8.2 kB at 411 kB/s)
Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/maven/release/maven-release/2.1/maven-release-2.1.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/release/maven-release/2.1/maven-release-2.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/release/maven-release/2.1/maven-release-2.1.pom (7.1 kB at 307 kB/s)
Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/maven/plugins/maven-release-plugin/2.1/maven-release-plugin-2.1.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.1/maven-release-plugin-2.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-release-plugin/2.1/maven-release-plugin-2.1.jar (40 kB at 1.8 MB/s)
Downloading from apache-snapshots: https://repository.apache.org/snapshots/com/github/eirslett/frontend-maven-plugin/1.9.1/frontend-maven-plugin-1.9.1.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/github/eirslett/frontend-maven-plugin/1.9.1/frontend-maven-plugin-1.9.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/github/eirslett/frontend-maven-plugin/1.9.1/frontend-maven-plugin-1.9.1.pom (4.9 kB at 222 kB/s)
Downloading from apache-snapshots: https://repository.apache.org/snapshots/com/github/eirslett/frontend-plugins/1.9.1/frontend-plugins-1.9.1.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/github/eirslett/frontend-plugins/1.9.1/frontend-plugins-1.9.1.pom
Downloaded from central: https://repo.maven.apache.org/maven2/com/github/eirslett/frontend-plugins/1.9.1/frontend-plugins-1.9.1.pom (6.6 kB at 314 kB/s)
Downloading from apache-snapshots: https://repository.apache.org/snapshots/com/github/eirslett/frontend-maven-plugin/1.9.1/frontend-maven-plugin-1.9.1.jar
Downloading from central: https://repo.maven.apache.org/maven2/com/github/eirslett/frontend-maven-plugin/1.9.1/frontend-maven-plugin-1.9.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/com/github/eirslett/frontend-maven-plugin/1.9.1/frontend-maven-plugin-1.9.1.jar (35 kB at 1.7 MB/s)
Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/codehaus/mojo/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloading from apache-snapshots: https://repository.apache.org/snapshots/org/apache/maven/plugins/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 688 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 kB at 436 kB/s)
Downloaded from apache-snapshots: https://repository.apache.org/snapshots/org/apache/maven/plugins/maven-metadata.xml (8.5 kB at 110 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.178 s
[INFO] Finished at: 2020-10-28T13:13:05+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'jetty' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/srv/bfabric/.m2/repository), apache-snapshots (https://repository.apache.org/snapshots/), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

```

**Comment by tuerker** [comment] 2020-10-28 12:18
could this issue be related to the java version:

```
java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

```

**Comment by melloware** [comment] 2020-10-28 12:21
Nope you need to have PF 9.0-SNAPSHOT in Maven.    The pom has this
```
        <dependency>
            <groupId>org.primefaces</groupId>
            <artifactId>primefaces</artifactId>
            <version>9.0-SNAPSHOT</version>
        </dependency>
```

So its expecting you have a PF 9.0-SNAPSHOT built locally.

**Comment by melloware** [comment] 2020-10-28 12:22
Oh no it looks like your maven central is pointed to Apache Snapshots?
```
 https://repository.apache.org
```

Instead of Maven Central.

**Comment by melloware** [comment] 2020-10-28 12:23
And are you sure you are in the right directory?  It looks like you are in /primefaces not the unzipped /pf-6458 directory?

**Comment by tuerker** [comment] 2020-10-28 12:33
i have now unzipped the file and build it successfully after having also checked out your latest fix.

however:  http://localhost:8080/primefaces-test/test.xhtml delivers

```
HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException
URI:	/primefaces-test/test.xhtml
STATUS:	500
MESSAGE:	javax.servlet.ServletException: javax.servlet.ServletException
SERVLET:	Faces Servlet
CAUSED BY:	javax.servlet.ServletException: javax.servlet.ServletException
CAUSED BY:	javax.servlet.ServletException
CAUSED BY:	java.lang.NullPointerException
Caused by:
javax.servlet.ServletException: javax.servlet.ServletException
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:671)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1418)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:572)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1612)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1582)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	... 12 more
Caused by: java.lang.NullPointerException
	at org.primefaces.component.datepicker.DatePickerRenderer.encodeMarkup(DatePickerRenderer.java:124)
	at org.primefaces.component.calendar.BaseCalendarRenderer.encodeEnd(BaseCalendarRenderer.java:89)
	at org.primefaces.component.datepicker.DatePickerRenderer.encodeEnd(DatePickerRenderer.java:63)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
```

**Comment by melloware** [comment] 2020-10-28 12:57
Try again please.

**Comment by tuerker** [comment] 2020-10-28 13:22
your reproducer looks fine now.

but there is still a problem.

when the LocalDateTime is required, .i.e., annotation with @NotNull it does not work.
In this case, an invalid time exception is thrown which is not caught and thus datepicker does not pop-up.

**Comment by melloware** [comment] 2020-10-28 13:28
Works fine for me with @NotNull...
[pf-6458-notnull.zip](https://github.com/primefaces/primefaces/files/5452119/pf-6458-notnull.zip)

Run my reproducer here...

**Comment by tuerker** [comment] 2020-10-28 13:32
i see. the reproducer also works with NotNull.

**Comment by tuerker** [comment] 2020-10-28 13:32
i forgot to attach the screenshot related to my previous comment.

![Screenshot from 2020-10-28 14-16-02](https://user-images.githubusercontent.com/10051373/97442662-62b0b200-192a-11eb-9db5-dc055d24eb3f.png)

**Comment by melloware** [comment] 2020-10-28 13:39
Hmm here is a detailed reproducer:
[pf-6458-nn.zip](https://github.com/primefaces/primefaces/files/5452183/pf-6458-nn.zip)

I don't see any JS Console errors.

**Comment by tuerker** [comment] 2020-10-28 13:44
i see, this reprocuders also works fine.

**Comment by tuerker** [comment] 2020-10-28 13:45
however there must be something which breaks the code that running for years. i will investigate.

**Comment by tuerker** [comment] 2020-10-28 13:48
something that has changed in the last 4 months. our productive system runs on a snapshot of june 23, 2020

**Comment by melloware** [comment] 2020-10-28 13:48
Keep digging on your production code until you find the problem.  And if you do please provide a reproducer like I do.  Without a reproducer it makes it difficult or impossible for developers to see your issue.

**Comment by tuerker** [comment] 2020-10-28 13:50
i will let you when i am step further because this will surely reveal a bug to be fixed.

**Comment by MatthiasScherrerFGCZ** [comment] 2020-10-28 14:12
> Keep digging on your production code until you find the problem. And if you do please provide a reproducer like I do. Without a reproducer it makes it difficult or impossible for developers to see your issue.

Yes we will. Somehow the component is already broken when the page is loaded. It has definitely nothing to do with the @NotNull validation.

**Comment by tuerker** [comment] 2020-10-28 14:28
@melloware : i could reproduce the problem. it appears when the LocalDateTime attribute is non-empty when invoking the datePicker. 

you will see the problem when you change the line in the reproducer:

`	private LocalDateTime dateTime1 = LocalDateTime.now();
`

results in 

![Screenshot from 2020-10-28 15-26-10](https://user-images.githubusercontent.com/10051373/97449617-284b1300-1932-11eb-8153-22a2cf19e8cd.png)

**Comment by melloware** [comment] 2020-10-28 15:26
OK i found the issue and provided a PR.  I am going to write an Integration Test for this.

**Comment by melloware** [comment] 2020-10-28 15:40
Integration Test updated: https://github.com/primefaces-extensions/primefaces-integration-tests/commit/d014a7ec8d0553e95f4b14fb5b856f50b616e1af

**Closed as completed** 2020-10-28 17:12 UTC
Labels: :lady_beetle: defect
