### ISSUE TITLE
Inputtextarea bean validation maxlength conflict

### ISSUE THREAD

**Issue by mustafacataltepe** [primefaces/primefaces#1723] opened 2016-08-26 11:21 UTC
When having a bean validation set with @Size annotation inputTextarea component renders data-p-maxlength equal to the bean side value but renders maxlength with Integer.MAX_VALUE in InputTextareaRenderer so bean validation becomes void since its overriden with maxlength.

**Comment by tandraschko** [comment] 2016-08-29 08:54
Please provide a example. I also don't understand whats wrong exactly.

**Comment by mustafacataltepe** [comment] 2016-08-31 08:24
When you have field such as:

@Size(max=20)
private String areaStr;

in your bean definition, and set this value with a inputTextarea component as:

p:inputTextarea value="#{myController.areaStr}"

@Size annotation discarded and maxlength of the inputTextarea is set to be Integer.MAX_VALUE instead of the defined value which 20 in this example. When i check the generated html of the component, attributes are set as _data-p-val="Size" data-p-minlength="0" data-p-maxlength=20 maxlength="2147483647"_

**Comment by tandraschko** [comment] 2016-09-01 20:20
do you mean with primefaces.TRANSFORM_METADATA?
works fine for me on /showcase/ui/csv/bean.xhtml and enabled primefaces.TRANSFORM_METADATA.

**Comment by mustafacataltepe** [comment] 2016-09-02 11:18
it works for inputText but not fot inputTextarea in my case there is only inputText example on showcase for @Size validation, i am using mojarra 2.2.8-15 and PF 6.0 community release. When i debug InputTextareaRenderer inside encodeScript during widget building inputTextarea.getMaxlength() returns 2147483647 as value. If i convert component to an inputText it is working as intended.

**Comment by tandraschko** [comment] 2016-09-02 11:23
I see, the problem is that InputTextarea has a own special handling of maxlength. We would need to read @Size there.

**Comment by tandraschko** [comment] 2016-09-02 11:29
For now you can just set primefaces.TRANSFORM_METADATA to true.
Will probably close this request as won't fix in the future.

**Comment by mustafacataltepe** [comment] 2016-09-02 13:02
primefaces.TRANSFORM_METADATA is already set to true in web.xml. Should i assume this won't be fixed and i need to implement a workaround?

**Comment by tandraschko** [comment] 2016-09-02 13:07
If you set this to true, please provide a simple jetty/maven app. I can only reproduce it if primefaces.TRANSFORM_METADATA is false, and this is expected.

**Comment by mustafacataltepe** [comment] 2016-09-06 06:19
Attached jetty/mvn app

[textarea test.zip](https://github.com/primefaces/primefaces/files/456030/textarea.test.zip)

**Comment by tandraschko** [comment] 2016-09-06 07:29
Thanks :) fixed now!

**Closed as completed by tandraschko** 2016-09-06 07:29 UTC
Labels: new feature
