### ISSUE TITLE
DataTable: draggableRows and selection (single) -> dragged row sould be selected

### ISSUE THREAD

**Issue by quetsalkoatl** [primefaces/primefaces#2457] opened 2017-06-21 07:09 UTC
## 1) Environment
- PrimeFaces version: 6.1
- Application server + version: Apache Tomcat 8.0.23
- Affected browsers: FF ESR 52.1.0, IE 11

## 2) Expected behavior
When `<p:dataTable>` has `draggableRows="true"` and` selectionMode="single"`, dragged row sould be selected afterwards

## 3) Actual behavior
When row is dragged, it is not selected.

## 4) Steps to reproduce
Create dataTable which draggable rows and selectionMode="single".

## 5) Sample XHTML
```xhtml
<p:dataTable id="tblId" var="row" value="${detail.data}" rowKey="#{row.order}" draggableRows="true"
             widgetVar="tblVar" selectionMode="single" selection="#{detail.selected}">
    <f:facet name="header">Excel Export</f:facet>
    <p:ajax event="rowReorder" listener="${detail.onReorder}" update="msg_ajax" />
    [colums]
    <p:column headerText="Datum" style="width: 70px; background-color: ${row.dateRGB}">
        <p:cellEditor>
            <f:facet name="output">
                <h:outputText value="${row.date}">
                    <f:convertDateTime pattern="dd.MM.yyyy"/>
                </h:outputText>
            </f:facet>
            <f:facet name="input">
                <p:calendar value="#{row.date}" pattern="dd.MM.yyyy" locale="de" navigator="true"
                            showOtherMonths="true" selectOtherMonths="true" placeholder="Datum" />
            </f:facet>
        </p:cellEditor>
    </p:column>
    [columns]
</p:dataTable>
```

**Comment by melloware** [comment] 2020-12-21 18:28
If you need this fix right now just add this JS to your application.
```javascript
if (PrimeFaces.widget.DataTable) {
    PrimeFaces.widget.DataTable.prototype.makeRowsDraggable = function() {
        var $this = this,
            draggableHandle = this.cfg.rowDragSelector || 'td,span:not(.ui-c)';

        this.tbody.sortable({
            placeholder: 'ui-datatable-rowordering ui-state-active',
            cursor: 'move',
            handle: draggableHandle,
            appendTo: document.body,
            start: function(event, ui) {
                ui.helper.css('z-index', PrimeFaces.nextZindex());
            },
            helper: function(event, ui) {
                var cells = ui.children(),
                    helper = $('<div class="ui-datatable ui-widget"><table><tbody class="ui-datatable-data"></tbody></table></div>'),
                    helperRow = ui.clone(),
                    helperCells = helperRow.children();

                for (var i = 0; i < helperCells.length; i++) {
                    var helperCell = helperCells.eq(i);
                    helperCell.width(cells.eq(i).width());
                    // #5584 reflow must remove column title span
                    helperCell.children().remove('.ui-column-title');
                }

                helperRow.appendTo(helper.find('tbody'));

                return helper;
            },
            update: function(event, ui) {
                var fromIndex = ui.item.data('ri'),
                    fromNode = ui.item;
                itemIndex = ui.item.index(),
                    toIndex = $this.paginator ? $this.paginator.getFirst() + itemIndex : itemIndex;
                isDirectionUp = fromIndex >= toIndex;

                // #5296 must not count header group rows
                // #6557 must not count expanded rows
                if (isDirectionUp) {
                    for (i = 0; i <= toIndex; i++) {
                        fromNode = fromNode.next('tr');
                        if (fromNode.hasClass('ui-rowgroup-header') || fromNode.hasClass('ui-expanded-row-content')) {
                            toIndex--;
                        }
                    }
                } else {
                    fromNode.prevAll('tr').each(function() {
                        var node = $(this);
                        if (node.hasClass('ui-rowgroup-header') || node.hasClass('ui-expanded-row-content')) {
                            toIndex--;
                        }
                    });
                }
                toIndex = Math.max(toIndex, 0);

                $this.syncRowParity();

                var options = {
                    source: $this.id,
                    process: $this.id,
                    params: [{
                            name: $this.id + '_rowreorder',
                            value: true
                        },
                        {
                            name: $this.id + '_fromIndex',
                            value: fromIndex
                        },
                        {
                            name: $this.id + '_toIndex',
                            value: toIndex
                        },
                        {
                            name: this.id + '_skipChildren',
                            value: true
                        }
                    ]
                }

                if ($this.hasBehavior('rowReorder')) {
                    $this.callBehavior('rowReorder', options);
                } else {
                    PrimeFaces.ajax.Request.handle(options);
                }

                // GitHub #2457 select row after it was moved
                if ($this.cfg.selectionMode === 'single') {
                    $this.selectRow(fromNode, true);
                }
            },
            change: function(event, ui) {
                if ($this.cfg.scrollable) {
                    PrimeFaces.scrollInView($this.scrollBody, ui.placeholder);
                }
            }
        });
    };
}
```

**Comment by tandraschko** [comment] 2020-12-22 12:38
@melloware what is the bug here?
is a row selected and re-ordered, its not selected anymore after this?

**Comment by melloware** [comment] 2020-12-22 12:40
So if it is selected when you reorder it works.  But what fails is if you click and hold down on a row it is not selected you can drag it and drop it somewhere and its still not selected. I think the expected behavior and so does the OP thinks this row should be selected if you drag and drop it and I agree.

**Comment by tandraschko** [comment] 2020-12-22 12:42
not sure TBH
the current behavior fits more my taste, i think thats up to @mertsincan

**Comment by melloware** [comment] 2020-12-22 12:44
Yep we can leave it up to @mertsincan but its strange to me I click and drag a row, then i have to click it again to select it.

**Comment by tandraschko** [comment] 2020-12-22 12:45
what happens if you click on a button, still hold the click but move away, and relese the click? the button is still not click
Thats the case i compare, i dont like to click the action, just reorder

**Comment by melloware** [comment] 2020-12-22 12:56
Good point.  Think we should close this PR and issue?  I am OK with that.  I can mark it as "workaround" since I have provided one and we can close this.

**Comment by melloware** [comment] 2020-12-22 18:06
Closing with workaround provided and "works as expected".

**Closed as completed by melloware** 2020-12-22 18:06 UTC
Labels: Resolution:  Wontfix, workaround
