### ISSUE TITLE
Menu: not working in PF 14.0.1

### ISSUE THREAD

**Issue by SimonePadovan** [primefaces/primefaces#12136] opened 2024-06-18 10:12 UTC
### Describe the bug

`	<h:form >
							<p:commandButton id="nuovoStandard" value="Nuovo" 
										  type="button" icon="material-icons mi-plusthick"  />
							<p:menu model="#{confBean.getTipiDomandaMenu(false)}" maxHeight="400"
										 overlay="true" trigger="nuovoStandard" my="left bottom" at="left top" />
						</h:form>`

when i click the button and move the cursor over an item of the menu and even when i click on the menu item comes this javascript error:

With PF 14.0.0 it works good.

> Uncaught InternalError: too much recursion
    jQuery 3
    resetFocus http://localhost:8080/Survey/jakarta.faces.resource/components.js.xhtml?ln=primefaces&v=14.0.1:609
    focus http://localhost:8080/Survey/jakarta.faces.resource/components.js.xhtml?ln=primefaces&v=14.0.1:610
    bindEvents http://localhost:8080/Survey/jakarta.faces.resource/components.js.xhtml?ln=primefaces&v=14.0.1:631
    jQuery 2

### PrimeFaces edition

Community

### PrimeFaces version

14.0.1

### JSF implementation

Mojarra

### JSF version

4

### Java version

17

### Browser(s)

chrome, firefox

**Comment by melloware** [comment] 2024-06-18 11:19
Duplicate of: https://github.com/primefaces/primefaces/issues/12117

Already fixed for 14.0.2 and monkeypatch included in that ticket.

**Comment by SimonePadovan** [comment] 2024-06-18 11:42
Perfect, when will PF 14.0.2 come out ? thanks

**Comment by melloware** [comment] 2024-06-18 11:52
in the next couple of weeks

**Closed as completed** 2024-06-26 07:09 UTC
Labels: Resolution: Duplicate
