### ISSUE TITLE
SelectOneMenu: RowExpansion value lost

### ISSUE THREAD

**Issue by ghost** [primefaces/primefaces#4446] opened 2019-01-17 09:41 UTC
This issue is similar to one I already reported and fixed but now for select one menu: https://github.com/primefaces/primefaces/issues/4138

If the SelectOneMenu is inside a RowExpension and the row is closed the submitted value will be lost on ajax process.

## 1) Environment
- PrimeFaces version: 6.2
- Does it work on the newest released PrimeFaces version? Version? no
- Does it work on the newest sources in GitHub? no
- Application server + version: Wildfly-11
- Affected browsers: ALL

## 2) Expected behavior
The value should be submitted.

## 3) Actual behavior
The submitted value will be changed to default ("")

## 4) Steps to reproduce
- Select something from an SelectOneMenu which is inside a RowExpension.
- Close the RowExpension.
- Process the form.
- Open the RowExpension.
- The SelectOneMenu will be empty.

**Comment by melloware** [comment] 2019-01-17 12:09
Nice debugging and fix.  I think your changes clean up the code nicely too.

**Comment by tandraschko** [comment] 2019-02-24 20:53
Reisen because of #5474

**Comment by tandraschko** [comment] 2019-02-24 20:53
Please provide a example

**Comment by fanste** [comment] 2019-02-25 13:42
Now I had been able to reproduce the issue. It does not appear on the first submit but on each following submit, when the row was not expanded again. So the correct "steps to reproduce"

1. Select something from an SelectOneMenu which is inside a RowExpension.
2. Close the RowExpension (optional)
3. Process the form.
4. Dot expand the last changed row.
5. Process the form (e.g. because you changed some other row)
6. Open the RowExpension of the first changed row.
7. The SelectOneMenu will be empty

If you have ``required=true`` on the SOM step 5 will fail with with a validation failure.

### The root cause
- The row expansion initially does not renderer the ``tr`` (table row).
- The AJAX sets process to the table which also processes all children (and therefore also the selectOneMenu inside the rowExpansion)
- Because of the missing ``tr`` no values will be submitted for the selectOneMenu which currently sets an empty submitted value in the decode method.
- This empty submitted value will result in a setter invocation of the selectOneMenu with ``null``

### Possible fix
 - Keep the fix of Gaboros but enhance it for selectOneRadio. But align the select-many components. Because those still replace "no value submitted" with empy string.

OR (maybe even better)

 - Skip the children of the rowExpansion when the row is not expanded. That should prevent such error for all types of components.
This requires some state that is transmitted to the server that tells which rows were expanded.

### Other considerations
 - You can not put fields in the rowExpansion that have special validation on it (e.g. required=true) because those won't be executed when the row was not expanded on submit.


WDYT @tandraschko

**Comment by tandraschko** [comment] 2019-02-25 13:47
Please Ping me in some weeks again
We should not change it until the final release, its to risky

**Comment by rider87** [comment] 2020-08-10 10:58
hi,

any plan to fix this?

**Comment by tandraschko** [comment] 2020-08-10 11:42
i dont have time for it but you can simple fix it by yourself (and provide a PR) or use PrimeFaces PRO.

**Comment by rider87** [comment] 2020-09-16 16:28
Please let me know how this can be fixed... But when it´s simple, why can it not fixed in the PF core? 
@melloware can you fix this maybe?

**Comment by melloware** [comment] 2020-09-16 17:17
@rider87 this change was already backed out once because of a regression issue.  Not sure how "simple" this is to fix without tons of regression testing.

**Comment by rider87** [comment] 2020-09-17 07:40
So you want to say it will be NOT considered in PF9 ?
If not: is there a workaround available? This is for my project currently a huge bug.

**Comment by melloware** [comment] 2020-09-17 11:16
Th workaround is you can implement the original PR in your own overridden SelectOneRenderer and SelectOne.  See the fixes made here: https://github.com/Gaboros/primefaces/commit/ac5c8ba231f5938dbfe405ff15f90581bfb2982a

**Comment by rider87** [comment] 2020-09-17 11:31
ok, thank you...

1) Will this fix be available in PF9?
2) How can I override the SelectOneMenuRenderer class? 
- I´m using the primefaces8.0.jar in my project.... How can I override that?

**Comment by melloware** [comment] 2020-09-17 11:42
I don't work for PrimeTek or speak for PrimeTek so unless someone from the community fixes this bug or pays for this bug to be fixed through their PRO support I doubt it will be in 9.0.

Overriding default PF behavior is easy see: https://stackoverflow.com/questions/8179449/jsf-2-0-primefaces-renderer-override

**Comment by fanste** [comment] 2020-09-17 13:18
PR #6326 which implements [my second "possible fix" proposal](https://github.com/primefaces/primefaces/issues/4446#issuecomment-467015318)

Testcase: https://github.com/fanste/primefaces-test/tree/test-4446

**Comment by rider87** [comment] 2020-09-17 13:30
> I don't work for PrimeTek or speak for PrimeTek so unless someone from the community fixes this bug or pays for this bug to be fixed through their PRO support I doubt it will be in 9.0.
> 
> Overriding default PF behavior is easy see: https://stackoverflow.com/questions/8179449/jsf-2-0-primefaces-renderer-override

I don´t understand exactly... I thought this bug has been fixed already from @fanste ....
Who can decide that the fix will be pushed to the core?

**Comment by melloware** [comment] 2020-09-17 13:39
@rider87 the original fix was from @Gaboros not from @fanste ???  See: https://github.com/Gaboros/primefaces/commit/ac5c8ba231f5938dbfe405ff15f90581bfb2982a

**Comment by fanste** [comment] 2020-09-17 13:48
I started to implement the fix _after_ melloware posted his message. I was surprised how easy the solution came out.

But changes to the datatable component normally won't be merged that fast as it is quite a complex component. You (@rider87) could take my fixed branch, build PF yourself and give it a try. Report back if everything is working. Maybe @Gaboros is able to do this too. That may speed up the merge process.

**Comment by melloware** [comment] 2020-09-17 13:49
And I noticed your are using rowIndex for tracking that doesn't get messed up with filtering the table does it?

**Comment by fanste** [comment] 2020-09-17 13:53
> 
> 
> And I noticed your are using rowIndex for tracking that doesn't get messed up with filtering the table does it?

Those events shouldn't be any problem, but maybe it would be even better to hook up with `tbody`-changing events (filter, sort, page, ...are there more events?) and rebuild the state for the latest `tbody`.

**Comment by melloware** [comment] 2020-09-17 13:54
i would think those would be the big 3 to test filtering, sorting, paging.

**Comment by fanste** [comment] 2020-09-17 14:36
Already found some errors, but not regarding events:

- The frozen column widget is totally bugged regarding row expansion
- Frozen rows are not recognized during row expansion JS event binding because of a different tbody

Those 3 events all use the `updateData` JS function which could be a good point to rebuild the expansion state to absolutly overcome any problems

**Comment by melloware** [comment] 2020-09-17 15:34
Not sure Frozen columns was designed to work with Row Expansion so i wouldn't worry about that.  Not all features of the datatable were designed to be able to be used with all other features.

**Comment by fanste** [comment] 2020-09-21 07:19
I've added a change that re-inits the after `updateData`.
I've updated the testcase to validate that my change still works.

- row expansion for normal datatable with frozen rows should be tracked in another issue as it doesn't really belong to this one
- a frozen column datatable was adjusted for row expansion some (ok.. a lot of) years ago by cagataycivici (78644a6). This should probably also be tracked in another issue.

**Comment by rider87** [comment] 2020-09-25 05:33
> I started to implement the fix _after_ melloware posted his message. I was surprised how easy the solution came out.
> 
> But changes to the datatable component normally won't be merged that fast as it is quite a complex component. You (@rider87) could take my fixed branch, build PF yourself and give it a try. Report back if everything is working. Maybe @Gaboros is able to do this too. That may speed up the merge process.

Yes, it´s working fine...
I hope this can be fixed in PF9

**Comment by melloware** [comment] 2020-09-25 11:09
Thanks for reporting in @rider87.  Just waiting for more people to review it since its a Datatable change.

**Closed as completed** 2020-09-30 09:08 UTC
Labels: :lady_beetle: defect
