### ISSUE TITLE
DataTable filter is not triggered when changing input by pasting by mouse or dragging text

### ISSUE THREAD

**Issue by jepsar** [primefaces/primefaces#4606] opened 2019-03-02 08:41 UTC
Affects PF 7.0 RC3

**Comment by tandraschko** [comment] 2019-03-02 13:57
@mertsincan can you review and apply the PR if correct?

**Comment by mertsincan** [comment] 2019-03-04 07:49
Firstly, thanks a lot, @jepsar ;)
I think it is not a bug. We have customizable attributes such as filterEvents for users to solve such issues and most of Users use filterEvent with 'keyup' event. You can change it according to your issue. 

Best Regards,

**Comment by jepsar** [comment] 2019-03-04 08:11
Bug or not, this seems like a more reasonable default to me. Keystrokes will also trigger a 'input propertychange' event.

**Comment by jepsar** [comment] 2019-03-04 10:14
@mertsincan I was just checking the `autoComplete` component, and there by default mouse pasting and text dragging is supported. Shouldn't that behave in the same way then?

**Comment by mertsincan** [comment] 2019-03-04 10:44
Hi @jepsar,
Thanks a lot for the feedback. We have to think about other users. Most of Users use keyup event. Also, I think it's not right to change the default behavior before 7.0.Final release. Maybe, we can make this change on 7.1. 
For autocomplete, please see the following code;
```if(this.cfg.queryEvent !== 'enter') {
            this.input.on('input propertychange', function(e) {
                $this.processKeyEvent(e);
            });
        }

        this.input.on('keyup.autoComplete', function(e) {
            var keyCode = $.ui.keyCode,
            key = e.which;

            if(PrimeFaces.env.isIE(9) && (key === keyCode.BACKSPACE || key === keyCode.DELETE)) {
                $this.processKeyEvent(e);
            }....
``` 
It has a completely different implementation. The implementation such as filtering, sorting, keyboard navigation, focusing may vary by component. Not the same in all components. For now, you can use filterEvent="input propertychange". Thanks a lot for your understanding! 
Best Regards,

**Comment by jepsar** [comment] 2019-11-12 07:49
FYI as a workaround I currently use a custom renderer for `p:dataTable` where I default the filter event.

**Comment by melloware** [comment] 2019-11-28 17:02
I am going to close this for now as there is a workaround and Mert said this is how its supposed to work.

**Closed as not planned by melloware** 2019-11-28 17:02 UTC
Labels: enhancement, workaround
