### ISSUE TITLE
Datatable: command buttons inside datatable not called when virtualScroll is enabled

### ISSUE THREAD

**Issue by YotillaPablo** [primefaces/primefaces#10902] opened 2023-10-25 10:40 UTC
### Describe the bug

I have a datatable with virtualScrolling and lazy loading enabled.
Each row displays a label and has a commandButton which turns the label to upperCase and then updates the datatable.
This works for the first rows but not for the ones loaded when scrolling down: the commandButton action is never executed on the backing bean. 

### Reproducer

Reproducer in [https://github.com/YotillaPablo/primefaces-test](https://github.com/YotillaPablo/primefaces-test)

Go to http://localhost:8080/primefaces-test/
Click the 'toUpperCase' button on the first row, labelled 'Item 1': this will turn it to 'ITEM 1' and a 'updating ITEM 1' message will appear on System.out.
Click the 'toUpperCase' button on the row 57, labelled 'Item 57': this won't have any effect and nothing will be printed to System.out

### Expected behavior

The commandButton works on all datatable rows.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.2

### JSF implementation

Mojarra

### JSF version

2.2

### Java version

17

**Comment by melloware** [comment] 2023-10-25 11:23
Just a question did this work in 12.0.0?

**Comment by YotillaPablo** [comment] 2023-10-25 11:26
I hadn't checked before, but the reproducer works as expected on 12.0.0

**Comment by melloware** [comment] 2023-10-25 11:43
@Rapster this looks like a DT regression as it worked in 12 and not in 13.

**Comment by melloware** [comment] 2023-10-25 13:18
@YotillaPablo I just downloaded your example ran `mvn clean jetty:run` and it works fine.  Item 1 works then I scroll down and load more data and ITEM 42 works fine?

**Comment by melloware** [comment] 2023-10-25 13:22
OK the ID is messed up.  

Row 0 which is Item 1 has the proper Source:
![image](https://github.com/primefaces/primefaces/assets/4399574/b8e3100b-fdfd-4f4c-a09e-98089e7348eb)

But Row 57 has the wrong ID and thus doesn't match so it won't call the backing bean:
![image](https://github.com/primefaces/primefaces/assets/4399574/86b40385-29a4-4116-8085-84ec926aff33)

**Comment by Rapster** [comment] 2023-10-25 21:17
clientids are fine, since virtual scroll is enabled it only keeps one chunk... But something off about the offset, still investigating... I have a feeling it's the same issue as https://github.com/primefaces/primefaces/issues/8949

**Comment by melloware** [comment] 2023-10-25 21:39
OK let me know what you find out maybe its two bugs in one!

**Comment by Rapster** [comment] 2023-10-25 22:42
One thing or two are not right in this area: https://github.com/primefaces/primefaces/blob/bbf7c874049bb9081e6ca6c8cb20053fc487e589/primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L1461-L1474

Not sure what's the whole idea behind scrollStep, scrollRows etc.

**Comment by melloware** [comment] 2024-01-05 17:25
@Rapster i am not sure its the JS code I compared the Network AJAX calls between PF 12.0.0 which works and PF 13.0.4 which does not work and they are identical.    Something is not being decoded properly on the backend since the button never makes it to its listener method.

![image](https://github.com/primefaces/primefaces/assets/4399574/7544be5c-bf4c-40ff-9a6e-e1afa9fef73f)

**Comment by Rapster** [comment] 2024-01-05 17:48
AFAIR, the reason why it's not being decoded is because of this JS function which doesn't the right page?

**Comment by melloware** [comment] 2024-01-05 18:07
OK I think I tracked it down.

Issue is this change: https://github.com/primefaces/primefaces/pull/9809/files which went into 13.0.0.

Here is what I see if I scroll to row 57 its HTML looks like this notice row `16`.

```xml
<button id="frmTest:myTable:16:toUpperCaseButton" name="frmTest:myTable:16:toUpperCaseButton" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="PrimeFaces.ab({s:&quot;frmTest:myTable:16:toUpperCaseButton&quot;,f:&quot;frmTest&quot;,u:&quot;frmTest:myTable&quot;});return false;" type="submit"><span class="ui-button-text ui-c">toUpperCase</span></button>
```

Button does **NOTHING**

if I manually change the HTML in the browser to this the ID as row 56 everywhere. it then works fires its Button and ITEM 57 is uppercased.

```xml
<button id="frmTest:myTable:56:toUpperCaseButton" name="frmTest:myTable:56:toUpperCaseButton" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="PrimeFaces.ab({s:&quot;frmTest:myTable:56:toUpperCaseButton&quot;,f:&quot;frmTest&quot;,u:&quot;frmTest:myTable&quot;});return false;" type="submit"><span class="ui-button-text ui-c">toUpperCase</span></button>
```

So to me it looks like the ID's are constantly reset 0-40 for every virtual scroll where it used to go 0-40, then 40-80, etc.

**Comment by Rapster** [comment] 2024-01-05 18:31
Can't reproduce (I remember I had to modify a bunch of stuff in the past, but don't feel like doing it again)... Do you have a reproducer without the TestView being ApplicationScoped and no static variables?

**Comment by melloware** [comment] 2024-01-05 18:36
Yep here you go:
[pf-10902.zip](https://github.com/primefaces/primefaces/files/13845421/pf-10902.zip)

**Comment by Rapster** [comment] 2024-01-05 18:48
So you just changed into ViewScoped, and you systematically have the bug? For me it's completely random

**Comment by melloware** [comment] 2024-01-05 18:49
i get it almost eveyr time 

The only way it works is if I manually change those ROW ID's in the HTML and then click the button

**Comment by Rapster** [comment] 2024-01-05 18:59
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/13845590/primefaces-test-master.zip)

Easier to reproduce with this

**Comment by melloware** [comment] 2024-01-05 18:59
Thanks!

**Comment by wlhUser** [comment] 2024-02-01 08:47
Sorry that I interfere with this ticket, but this problem is a blocker for me in using PF 13.

So I tried to debug it, with my limited knowledge about the guts of  PF,  but I might have found a hint.
While debugging I compared the behavior of PF 12.0.0 with PF 13.0.5.
According to what I found the following code might cause the problem.

![grafik](https://github.com/primefaces/primefaces/assets/47218021/3ae58624-7d17-4264-afb2-4d188199c380)

The attribute 'first' is being used for calculating the current rowIndex, and the row Index is used to calculate the clientId of the row in a data table. Here we need to keep in mind, that the clientId of a row in a data table with virtualScroll enabled, does not reflect the absolute position in the data model, but the position in the currently loaded chunk of data.
In the attached screenshot, the 'pressMe' link has the clientId 'form:testTable2:3:press2' (3 ist the rowIndex of the row in the currently loaded chunk), while data-ri shows the absolute position int the data model -> 253. 
When clicking 'pressMe' the clientId with index 3 is being sent to the server.
![grafik](https://github.com/primefaces/primefaces/assets/47218021/deccdfe8-118b-4a74-83ec-a0ebf6139e4a)

On server side, the clientIds of the table components are calculated as well, but here suddenly they are calculated with the absolute rowIndex. This results in an element which has the clientId 'form:testTable2:3:press2' on client side, the server side calculates a clientId of 'form:testTable2:253:press2'. By this mismatch the server cannot figure out which element was being clicked.
![grafik](https://github.com/primefaces/primefaces/assets/47218021/dad29e51-5e8a-48d0-a1c9-a19f4e61f5b9)

When debugging with PF12.0.0 I see here a parentId the Ids which match the ones of the client side.


I hope, that you can understand my explanation, and it helps narrowing down the problem.

**Comment by melloware** [comment] 2024-02-01 13:41
Great explanation and similar to what I debugged as well.    Did you have a proposed fix @wlhUser ?

**Comment by wlhUser** [comment] 2024-02-01 14:25
@melloware Unfortunately I do not have a proposal for a fix, as I did not really understand the meaning of the attribute 'first'.
At least with PF 12.0.0 and virtualScroll enabled, I had the impression that 'first' always stays 0. I would try removing the line in DataTable.java with setFirst(offset) - alt least for virtualScroll enabled - , as it is very different to PF 12.0. However I do not have an environment where I can apply changes to PF to test it. I hope @Rapster can judge if my explanation makes sense.

**Comment by wlhUser** [comment] 2024-02-02 06:53
@melloware Just a short feedback. I've manually patched a copy of primefaces.jar, by replacing the DataTable.class, with one where the line 'setFirst(offset)' is not executed in case of virtualScroll. I used this jar in my application, and ran some  Selenium Junit tests, which look pretty good, and confirm the behavior is the same as in PF 12.0. Maybe you should give it a try.

**Comment by melloware** [comment] 2024-02-02 11:43
I will do some testing today thanks @wlhUser !

**Comment by wlhUser** [comment] 2024-02-02 11:54
@melloware In case you do some testing, maybe you apply the modification for liveScroll as well, and check if it might fix issue #11045 as well. It seems that both issues are related.

**Comment by melloware** [comment] 2024-02-02 13:35
Yep i will test both reproducers.

**Comment by melloware** [comment] 2024-02-02 13:45
As a note this change was made in this commit: https://github.com/primefaces/primefaces/pull/9809/files#diff-4701970a7aabff8b155f0f3a7e3c2a54291a39b17a4176684c82ed83cb8fe53e

**Comment by Rapster** [comment] 2024-02-02 13:46
I'll see if I can have a PR for this w-e, I had a fix (not a great one, I tried to have a better one without great success and meantime I lost the original fix 😓 ) I could be wrong, but this problem has always been there.

**Comment by melloware** [comment] 2024-02-02 13:53
@Rapster if I change the code to this then this reproducer in the ticket goes back to working.

```java
        if (isVirtualScroll() || isLiveScroll()) {
            setFirst(0);
        }
        else {
            setFirst(offset);
        }
```

I am going to test https://github.com/primefaces/primefaces/issues/11045 as well.

**Comment by melloware** [comment] 2024-02-02 14:05
Confirmed it fixes #11045 as well

**Comment by wlhUser** [comment] 2024-02-02 16:36
@melloware Seems that the fix works. You assigned this issue to me - what am I supposed to do now?

**Comment by melloware** [comment] 2024-02-02 17:36
Nothing I was giving you credit for figuring it out!

**Closed as completed** 2024-02-02 17:44 UTC
Labels: :lady_beetle: defect
