### ISSUE TITLE
Bug fileDownload on Primefaces 14, Jakarta 10 EE

### ISSUE THREAD

**Issue by oscargt90** [primefaces/primefaces#12554] opened 2024-09-03 14:03 UTC
Hello

I have detected that when I try to download a file with **fileDownload** I get the following error:

No enum constant com.sun.faces.context.ExternalContextImpl.PREDEFINED_COOKIE_PROPERTIES.SameSite
java.lang.IllegalArgumentException: No enum constant com.sun.faces.context.ExternalContextImpl.PREDEFINED_COOKIE_PROPERTIES.SameSite

The environment is: Jakarta 10 EE, Payara 6.2024.8, Primefaces 14.

If I do not use the fileDownload component, they do download the files correctly

**Comment by tandraschko** [comment] 2024-09-03 14:06
Duplicate of: https://github.com/primefaces/primefaces/issues/11908#issuecomment-2105294610

**Closed as not planned by tandraschko** 2024-09-03 14:06 UTC
Labels: Resolution: Duplicate
