### ISSUE TITLE
Not able to add more than 970 elements in <p:picklist>

### ISSUE THREAD

**Issue by mariaarora** [primefaces/primefaces#2635] opened 2017-08-16 05:30 UTC
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version:6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> No https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version: JBOSS EAP 7.0
- Affected browsers:Chrome and Mozilla

## 2) Expected behavior
<p:picklist> should accept all the elements
...

## 3) Actual behavior
<p:picklist> is not accepting more than 970 elements
..

## 4) Steps to reproduce
Add more than 970 elements to be added in <p:picklist> using for loop.
It will not accept it
.. 

## 5) Sample XHTML
                                                               <p:pickList value="#{pickListView.deviceListSource}"
								var="picklist" itemLabel="#{picklist.displayName}"
								itemValue="#{picklist}" styleClass="Wid30"
								showSourceFilter="true" showTargetFilter="true"
								converter="entityConverter" id="picklistMonitor"
								filterMatchMode="contains">
				                              </p:pickList>
..

## 6) Sample bean
                     for(int testdevice=1000;testdevice<=1970;testdevice++)
			{
				DeviceVO testobj=new DeviceVO();
				testobj.setDeviceid(testdevice);
				testobj.setEnterprise("airtel");
				testobj.setIpaddress("10.1.8.3");
				deviceListSource.add(testobj);
			}
..

**Comment by Rapster** [comment] 2017-08-16 07:33
#2543 #2527 At this stage, you should provide a sample, otherwise we won't bother to have a try...

**Comment by tandraschko** [comment] 2017-08-16 07:47
Duplicate of #2543

**Closed as completed by tandraschko** 2017-08-16 07:47 UTC
Labels: Resolution: Duplicate
