### ISSUE TITLE
error in p:inputTextarea

### ISSUE THREAD

**Issue by Vomitory1** [primefaces/primefaces#1068] opened 2016-01-27 12:59 UTC
issue when press enter key into textArea

it count 1 character when keyenter have 2 characters

in the screenshot i pressed many times key enter or intro
![captura](https://cloud.githubusercontent.com/assets/12599197/12614053/7d7a2d7c-c4cb-11e5-8123-e40cd304514f.JPG)

**Comment by sudheerj** [comment] 2016-01-27 16:56
AFAIK keyenter will consume only character in inputtextarea.Any live demos where it takes two characters? Or Do I miss anything?

**Comment by kukel** [comment] 2016-01-28 18:23
PF version? Browser versions?

**Comment by sudheerj** [comment] 2016-03-16 03:27
It depends on browser.IE and FF will take one character for linebreak and Chrome will take two characters will take two characters for linebreak.The cross browser solution is provided here https://github.com/primefaces/primefaces/pull/1204.

With this PR it will take two characters for all browsers and it works fine with maxlength as well.

**Comment by mertsincan** [comment] 2016-03-16 08:02
Fixed for 5.3.10 and 6.0. Duplicate of #768

Thanks @sudheerj for your PR. :+1:

**Closed as completed by mertsincan** 2016-03-16 08:02 UTC
