### ISSUE TITLE
Primefaces 5.2.2 not working in JBoss EAP 6.3+

### ISSUE THREAD

**Issue by AleksanderKostowski** [primefaces/primefaces#268] opened 2015-05-12 07:31 UTC
After upgrade from JBoss EAP 6.2 to 6.3.3 our Primefaces application is not working. There is an exception in logs:

11:22:23,719 SEVERE [org.primefaces.application.exceptionhandler.PrimeExceptionHandler](http-localhost/127.0.0.1:8180-5) null: java.lang.IllegalStateException
                at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1010) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
                at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
                at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
                at org.primefaces.component.dialog.Dialog.queueEvent(Dialog.java:378) [primefaces-5.2.2.jar:5.2.2]
                at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]

We have noticed that these jars have changed in JBoss:

jsf-impl-2.1.19-redhat-2.jar -> jsf-impl-2.1.28.redhat-8.jar
jboss-jsf-api_2.1_spec-2.1.19.1.Final-redhat-1.jar -> jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar

We have opened new Case in RedHat and got answer that there is a bug in Primefaces.

**Comment by tandraschko** [comment] 2015-05-12 11:50
please post the complete stacktrace.
Looks like our ExceptionHandler JUST! prints the occured exception.

**Comment by AleksanderKostowski** [comment] 2015-05-12 11:54
``` java
11:22:23,707 ERROR [stderr] (http-localhost/127.0.0.1:8180-5) java.lang.IllegalStateException

11:22:23,707 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1010)

11:22:23,707 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012)

11:22:23,707 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012)

11:22:23,708 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.primefaces.component.dialog.Dialog.queueEvent(Dialog.java:378)

11:22:23,708 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012)

11:22:23,708 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.primefaces.component.fieldset.Fieldset.queueEvent(Fieldset.java:166)

11:22:23,708 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012)

11:22:23,708 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012)

11:22:23,708 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012)

11:22:23,708 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012)

11:22:23,709 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012)

11:22:23,709 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at com.sun.faces.facelets.component.UIRepeat.queueEvent(UIRepeat.java:996)

11:22:23,709 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012)

11:22:23,709 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012)

11:22:23,709 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012)

11:22:23,709 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012)

11:22:23,710 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012)

11:22:23,710 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIInput.validate(UIInput.java:980)

11:22:23,710 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIInput.executeValidate(UIInput.java:1237)

11:22:23,710 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIInput.processValidators(UIInput.java:702)

11:22:23,710 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,710 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,710 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,711 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,711 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at com.sun.faces.facelets.component.UIRepeat.process(UIRepeat.java:569)

11:22:23,711 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at com.sun.faces.facelets.component.UIRepeat.processValidators(UIRepeat.java:822)

11:22:23,711 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,711 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,711 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,712 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,712 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,712 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.primefaces.component.fieldset.Fieldset.processValidators(Fieldset.java:188)

11:22:23,712 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,712 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.primefaces.component.dialog.Dialog.processValidators(Dialog.java:395)

11:22:23,712 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,712 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,713 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.primefaces.component.api.UITabPanel.processValidators(UITabPanel.java:1069)

11:22:23,713 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,713 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,713 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,713 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,713 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIForm.processValidators(UIForm.java:253)

11:22:23,714 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,714 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,714 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.primefaces.extensions.component.layout.Layout.processValidators(Layout.java:240)

11:22:23,714 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,714 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216)

11:22:23,714 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1164)

11:22:23,715 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:76)

11:22:23,715 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)

11:22:23,715 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)

11:22:23,715 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)

11:22:23,715 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)

11:22:23,715 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)

11:22:23,715 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:100)

11:22:23,716 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)

11:22:23,716 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)

11:22:23,716 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at pl.ing.wapf.filters.RequestMdcContextFiller.doFilter(RequestMdcContextFiller.java:59)

11:22:23,716 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)

11:22:23,716 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)

11:22:23,716 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.omnifaces.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:122)

11:22:23,717 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)

11:22:23,717 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)

11:22:23,717 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)

11:22:23,717 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231)

11:22:23,717 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)

11:22:23,717 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:512)

11:22:23,718 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50)

11:22:23,718 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50)

11:22:23,718 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)

11:22:23,718 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:150)

11:22:23,718 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)

11:22:23,718 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)

11:22:23,719 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)

11:22:23,719 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:854)

11:22:23,719 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)

11:22:23,719 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926)

11:22:23,719 ERROR [stderr] (http-localhost/127.0.0.1:8180-5)   at java.lang.Thread.run(Thread.java:745)

11:22:23,719 SEVERE [org.primefaces.application.exceptionhandler.PrimeExceptionHandler] (http-localhost/127.0.0.1:8180-5) null: java.lang.IllegalStateException
    at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1010) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at org.primefaces.component.dialog.Dialog.queueEvent(Dialog.java:378) [primefaces-5.2.2.jar:5.2.2]
    at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at org.primefaces.component.fieldset.Fieldset.queueEvent(Fieldset.java:166) [primefaces-5.2.2.jar:5.2.2]
    at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at com.sun.faces.facelets.component.UIRepeat.queueEvent(UIRepeat.java:996) [jsf-impl-2.1.28.redhat-8.jar:2.1.28.redhat-8]
    at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1012) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIInput.validate(UIInput.java:980) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIInput.executeValidate(UIInput.java:1237) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIInput.processValidators(UIInput.java:702) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at com.sun.faces.facelets.component.UIRepeat.process(UIRepeat.java:569) [jsf-impl-2.1.28.redhat-8.jar:2.1.28.redhat-8]
    at com.sun.faces.facelets.component.UIRepeat.processValidators(UIRepeat.java:822) [jsf-impl-2.1.28.redhat-8.jar:2.1.28.redhat-8]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at org.primefaces.component.fieldset.Fieldset.processValidators(Fieldset.java:188) [primefaces-5.2.2.jar:5.2.2]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at org.primefaces.component.dialog.Dialog.processValidators(Dialog.java:395) [primefaces-5.2.2.jar:5.2.2]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at org.primefaces.component.api.UITabPanel.processValidators(UITabPanel.java:1069) [primefaces-5.2.2.jar:5.2.2]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIForm.processValidators(UIForm.java:253) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at org.primefaces.extensions.component.layout.Layout.processValidators(Layout.java:240) [primefaces-extensions-3.1.0.jar:3.1.0]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1216) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1164) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:76) [jsf-impl-2.1.28.redhat-8.jar:2.1.28.redhat-8]
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [jsf-impl-2.1.28.redhat-8.jar:2.1.28.redhat-8]
    at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118) [jsf-impl-2.1.28.redhat-8.jar:2.1.28.redhat-8]
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593) [jboss-jsf-api_2.1_spec-2.1.28.Final-redhat-1.jar:2.1.28.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:100) [primefaces-5.2.2.jar:5.2.2]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at pl.ing.wapf.filters.RequestMdcContextFiller.doFilter(RequestMdcContextFiller.java:59) [classes:]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.omnifaces.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:122) [omnifaces-2.0.jar:2.0]
    at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108) [omnifaces-2.0.jar:2.0]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:512) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
    at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50) [jboss-as-jpa-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169) [jboss-as-web-7.5.0.Final-redhat-21.jar:7.5.0.Final-redhat-21]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:150) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:854) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926) [jbossweb-7.5.7.Final-redhat-1.jar:7.5.7.Final-redhat-1]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_76]
```

**Comment by tandraschko** [comment] 2015-05-12 11:58
I can't see any PrimeFaces relation directly in the StackTrace.
AFAICS at javax.faces.component.UIComponentBase.queueEvent(UIComponentBase.java:1010)
triggers an IllegalStateException.

Can you post their answer please? Im not sure but i don't think thats an PrimeFaces problem.

**Comment by AleksanderKostowski** [comment] 2015-05-12 12:00
_Most likely your Primefaces version has issues with the newer JSF version from EAP 6.3. Primefaces is a 3rd party framework which is not tested by Red Hat. Our similar product is RichFaces which is included in Web Framework Kit [1]. The Primefaces support may provide more information on this problem, but if you reproduce the issues without using PrimeFaces components, we can investigate it and work with the Mojarra team on fixing it._

**Comment by tandraschko** [comment] 2015-05-12 12:03
Ok, i could just say the same of course.
Cause i don't have much time, if you can reproduce it in a simple project with maven and jetty/tomcat, i will have an look at it.
We would always need an example, so if you extract it to a small project without EAP, we will see if it depends on EAP. If it's related to PrimeFaces, i will fix it.

**Comment by AleksanderKostowski** [comment] 2015-05-12 12:04
OK, i will try. Thanks

**Comment by tandraschko** [comment] 2015-05-12 13:22
I will close it for now - please come back here when you have an working example.

**Closed as completed by tandraschko** 2015-05-12 13:22 UTC
Labels: :lady_beetle: defect, Resolution: Invalid

**Comment by cagataycivici** [comment] 2015-05-13 08:50
RedHat support just played it safe without spending much time on actual issue.

I can't see how this is PF related. See the code form UIComponentBase that Dialog extends;

``` java
    public void queueEvent(FacesEvent event) {

        if (event == null) {
            throw new NullPointerException();
        }
        UIComponent parent = getParent();
        if (parent == null) {
            throw new IllegalStateException();
        } else {
            parent.queueEvent(event);
        }

    }
```

Dialog's parent is null, this is unlikely unless component is detached from component tree.

**Comment by AleksanderKostowski** [comment] 2015-05-13 08:52
Thank you very much, I will contact them again.

**Comment by AleksanderKostowski** [comment] 2015-05-13 11:20
We have found the place in code which generates this error:

```
<p:accordionPanel widgetVar="wdg_accordModules" multiple="true" id="accordModules" 
    binding="#{accordionHelperController.accordionPanel}"
    activeIndex="#{accordionHelperController.activeIndexes}" dynamic="true" cache="false">
```

Changing dynamic="true" to dynamic="false" makes our application working correctly on JBoss EAP 6.3.3 and 6.4
