### ISSUE TITLE
Chart: BarChartSeries DateAxis

### ISSUE THREAD

**Issue by tfe2012** [primefaces/primefaces#2972] opened 2017-11-19 07:13 UTC
## 1) Environment
- PrimeFaces version: 6.1
- Application server + version: java 8,
- Affected browsers: chrome

## 2) Expected behavior

When I try  create multiaxis chart, I want make 2 bar series and 3 line. X axis -> DateAxis, and 2 Y axis, 2 different prices. Bar chart shows incorrect. 
`
DateAxis axis = new DateAxis("Period");
            axis.setTickAngle(-50);
            axis.setTickFormat("%b %#d, %y");
            lineChartModel.getAxes().put(AxisType.X, axis);
`

<img width="1390" alt="screen shot 2017-11-19 at 08 56 32" src="https://user-images.githubusercontent.com/8733714/32988230-7f9d9dd6-cd08-11e7-9524-2e87c06cee01.png">

If I set: lineChartModel.setStacked(true); shows bar chart columns correct:

`
DateAxis axis = new DateAxis("Period");`
            `axis.setTickAngle(-50);`
            `axis.setTickFormat("%b %#d, %y");`
            `lineChartModel.setStacked(true);`
            `lineChartModel.getAxes().put(AxisType.X, axis);
`

<img width="1395" alt="screen shot 2017-11-19 at 08 57 14" src="https://user-images.githubusercontent.com/8733714/32988219-450dfe36-cd08-11e7-8bd6-e21bc374b1b3.png">

If I set X axis type to CategoryAxis
`
lineChartModel.getAxes().put(AxisType.X, new CategoryAxis("Period"));
`
<img width="1394" alt="screen shot 2017-11-19 at 09 05 23" src="https://user-images.githubusercontent.com/8733714/32988264-26169f3c-cd09-11e7-97e0-bd5c251b131c.png">

How to graph like this? :

![screen-shot-2017-11-20](https://user-images.githubusercontent.com/8733714/32988300-d5142e64-cd09-11e7-9e47-816a17a1b30b.png)

**Comment by melloware** [comment] 2017-11-19 12:17
It could be an issue with jqPlot itself as a bug or it could also be not possible with jqPlot to graph the way you want it to.  Have you tried to create a chart like this with just raw jqPlot and take PrimeFaces out of the equation?

http://www.jqplot.com/

**Comment by melloware** [comment] 2019-06-29 17:25
Duplicate of https://github.com/primefaces/primefaces/issues/3684 so closing this ticket.

**Closed as completed by melloware** 2019-06-29 17:25 UTC
Labels: :lady_beetle: defect, Resolution: Duplicate
