### ISSUE TITLE
Calendar: should trigger change event if date is selected from popup

### ISSUE THREAD

**Issue by vonnai** [primefaces/primefaces#2304] opened 2017-04-25 19:57 UTC
Hi, calendar with popup should trigger change event before some ajax event is fired. I looked in datepicker source code and then if no onSelect function is defined, datepicker triggers change event to main input element. So if there is nobody who use ajax events, it's not possible to catch change. Please, check it. After your agreement, I will create pull request. SelectOneMenu after select item from menu triggers change event too.

Look for simple change:

calendar.js

     bindDateSelectListener: function() {
         var _self = this;
         this.cfg.onSelect = function() {
             if(_self.cfg.popup) {
                 _self.input.trigger("change"); // added
                 _self.fireDateSelectEvent();
             }
             else {
                 var newDate = $.datepicker.formatDate(_self.cfg.dateFormat, _self.getDate());
                 _self.input.val(newDate);
                 _self.fireDateSelectEvent();
             }
         };
     },

**Comment by tandraschko** [comment] 2017-04-25 20:25
i'm sure there a reason that jquery doesn't trigger onchange per default.

you can still catch this event via p:ajax event=dateselect onstart=....

**Comment by vonnai** [comment] 2017-04-26 06:42
It's standard behavior, that jquery doesn't trigger onchange event on input element if value is changed programmaticaly by jquery. That's the reason why datepicker triggers change event. Please, could you explain, why there is jquery trigger in select one menu if value is changed and there is nothing in calendar? What is the difference? So, If I want to catch change event from another component source code, it's impossible and <p:ajax event ... is not the right way. I can show you simple example:

If I put p:calendar with popup mode inside p:inplace component, I really don't want to use p:ajax on calendar, because I am using save event of p:inplace. I really need to catch calendar change event for call save event automatically. So the scenario is: click on inplace -> open popup -> select date -> automatially save event and back to the inplace display. All I want to have in one source code, not duplicities in p:ajax onstart=" where I must return to inplace via widget var.

If you really think, that it doesn't make any sence, I will keep this method overriden, but it could be useful for other primefaces users. That's the reason why this issue has been created.
Thanks

**Comment by tandraschko** [comment] 2017-04-26 08:20
We have to discuss this as this would break backward compatibility as users currently register 2 events:
change and itemSelect

if they upgrade, 2 ajax events instead 1 would be fired.

**Comment by melloware** [comment] 2020-01-29 14:34
This is a duplicate of #3054 so we will track the issue there.  The fix above will introduce multiple onChange events when used with TimePicker.

**Closed as completed by melloware** 2020-01-29 14:34 UTC
Labels: Resolution: Duplicate
