### ISSUE TITLE
Tooltip in timeline: stop work after update

### ISSUE THREAD

**Issue by Eiten1984** [primefaces/primefaces#5025] opened 2019-07-27 16:21 UTC
Hi, 

I use version Primefaces 7.0 I have a issue with Tooltip. I should work with timeline, after mouse over the timeline event I would like to show tooltip. Iti works until ajax rangechanged of timeline. 

<p:timeline id="timeline" value="#{schedulerControler.model}" var="event" varGroup="group" editable="true">
         <h:panelGroup id="myEvent" class="evenClassId#{event.id}">
            <h:outputText value="#{event.transportAsset.city}"/>
        </h:panelGroup>
        <p:ajax event="rangechanged" update="tooltipsPanel" listener="{schedulerControler.rangeChanged}"/>
</p:timeline>

<p:panel id="tooltipsPanel" >
      <ui:repeat value="#{schedulerControler.model.events}" var="varTooltip" >
                    <p:tooltip for="@(.evenClassId#{varTooltip.data.id})">
                        <h:outputText value="#{varTooltip.data.carNumber}"/>
                    </p:tooltip>
      </ui:repeat>
</p:panel>

**Comment by melloware** [comment] 2019-07-27 16:39
Duplicate of https://github.com/primefaces/primefaces/issues/4770

**Closed as completed** 2019-07-31 09:12 UTC
Labels: Resolution: Duplicate
