### ISSUE TITLE
Dialog: AJAX fails when nested in composite components

### ISSUE THREAD

**Issue by mkomko** [primefaces/primefaces#9807] opened 2023-02-17 07:37 UTC
### Describe the bug

We are currently migrating from WildFly 10 (EE 7) and PrimeFaces 7 to WildFly 27 (EE 10) and PrimeFaces 12. We used composite components quite extensively and thus have a "dialogBase" composite component and then many concrete dialog composite components using this component internally.

Now whenever a p:ajax triggers inside the dialog (for example a selectOneMenu changes), the values are not processed (the setters are not being called) and the listener is not called either. After the update any values are reset, because nothing was processed.

This also happens if we convert the "dialogBase" component to a "taglib component".

@tandraschko asked me to create a GitHub issue in this forum thread: https://forum.primefaces.org/viewtopic.php?f=3&t=79342

### Reproducer

I have created a reproducer using the jakarta branch from the primefaces-test repository: https://github.com/mkomko/primefaces-test/tree/dialog-ajax-update-issue
The master branch (Mojarra 2.2.x) shows the same behavior.
It still worked with PrimeFaces 8 and 10 (the PrimeFaces 11 tag wouldn't start).

When you run the reproducer, clicking the button opens a dialog. Selecting a different item from the selectOneMenu triggers an AJAX call and instead of the new value being selected, the value is reset. The setter is not being called, the listener is not being called either.

### Expected behavior

The values being processed, the setter and listener being called and the selected value still displayed after the AJAX update.

### PrimeFaces edition

Elite

### PrimeFaces version

12.0.0

### JSF implementation

Mojarra

### JSF version

4.0.0.SP01

### Java version

17.0.5

**Comment by melloware** [comment] 2023-02-20 02:15
So if it happens with mojarra 2.2 as well it sounds like it is not 4.0 related?  Have you tried MyFaces with your reproducer does it have the same behavior?

**Comment by mkomko** [comment] 2023-02-20 07:16
@melloware  Yeah, it doesn't really seem 4.0 related, more PrimeFaces related in general. I can't get the example to work in MyFaces, I always get the following error even though I think no changes should be necessary when changing the JSF implementation?

`ComponentNotFoundException: Cannot find component for expression "testDialog" referenced from "frmTest:openTestDialog".`

Nothing is rendered inside my composite component, so I don't know if I'm maybe missing some configuration needed for composite components in MyFaces.

**Comment by Rapster** [comment] 2023-02-20 10:00
2 things:
- you didn't set itemValue on your selectOneMenu component
- you didn't set a converter either (like https://showcase.omnifaces.org/converters/SelectItemsConverter)

Note aside: I'm surprised converter is still needed in 4.0 for UISelectOne components (I remember reading this https://arjan-tijms.omnifaces.org/p/jsf-23.html#1422 but only for UISelectMany component?)

**Comment by mkomko** [comment] 2023-02-20 10:34
@Rapster Thank you very much. Setting a converter indeed makes my reproducer work :-(. I don't think itemValue is required if a value collection is provided, at least we never use it.

Since we obviously use converters in our production code, I'll have to come up with a better reproducer. Thanks!

**Comment by tandraschko** [comment] 2023-02-20 10:47
also i still wonder why it works in Mojarra but not in MyFaces
could anyone check if the example is valid and create a issue in MyFaces? i will fix it then

**Comment by Rapster** [comment] 2023-02-20 10:47
I wouldn't advise to leave itemValue not set if you didn't implement toString() of your Item, since Class#toString does not a return a deterministic value, more details in the link from Omnifaces I shared with you. Up to you 😉 

Can it be closed or there is still an issue?

**Comment by mkomko** [comment] 2023-02-20 10:50
@Rapster Thank you. That explains why we never use itemValue - all relevant objects of ours implement toString().
The problem in our production code still exists, I'll just have to come up with a better reproducer. If you want to close this issue until then, feel free, thanks!

**Comment by mkomko** [comment] 2023-02-20 12:28
@Rapster Alright, the problem in our production code seems to be caused by something else. Since we are also trying to move away from using so many composite components we must have made a mistake somewhere along the way.
I am sorry and apologize for wasting all your time! I'll close the issue.

**Comment by mkomko** [comment] 2023-02-20 14:21
@Rapster Okay I'll open this issue back up. I have adapted [my reproducer](https://github.com/mkomko/primefaces-test/tree/dialog-ajax-update-issue). The problem appears under the following conditions:
* Base composite component with `p:dialog` inside
* Concrete composite component with base dialog composite component inside
* Have a `p:messages` with a `p:autoUpdate` in the component as well

So I suspect it may be related to `p:autoUpdate`!

I would very much appreciate if you could take another look. Thank you very much!

**Comment by Rapster** [comment] 2023-02-20 15:57
Something off about the clientids... Your selectItem composite clientid is `testDialog:dialog1:j_idt7` while it shoud be `testDialog:dialog1:dialogForm:j_idt7`.  They look ok on server side, but not on client side

**Comment by Rapster** [comment] 2023-02-20 17:01
Don't know how you suspected autoUpdate to be the problem, but indeed looks like it. If you remove it, it works... See also: https://github.com/eclipse-ee4j/mojarra/issues/5023

**Comment by tandraschko** [comment] 2023-02-20 17:12
Just 2 notes from my side:

1) it looks like autoUpdate does all correct
   - it collects "testDialog:dialog:dialogForm:j_idt7:msgs"
   - it adds "testDialog:dialog:dialogForm:j_idt7:msgs" to the renderIds in this request
   however it seems that Mojarra then calculates a wrong clientId when rendering - propably a bug in Mojarra while visiting the component and we cant fix it on PrimeFaces side
   
2) it doesnt run on MyFaces
    this is mostly a bad sign that the code uses some weird stuff, not compatible with specs; but it looks good to me.
    If you remove the update="..." it seems that the component library isnt found as the rendered HTML contains the composite markup "test:dialogtest" and not the rendered HTML. If we can fix this, we can atleast check if it works in MyFaces.
    Could be a bug in MyFaces or something i currently dont see

**Comment by tandraschko** [comment] 2023-02-20 17:18
the whole example works in MF after changing:

xmlns:test="http://xmlns.jcp.org/jsf/composite/components/test" -> xmlns:test="http://xmlns.jcp.org/jsf/composite/components"

and moving the files one dir above
not sure if this should work or a bug in MF

but for me it confirms there is a bug in Mojarra; we cant fix it on PF side, as well the ID handling in AutoComplete looks correct
its really looks like: https://github.com/eclipse-ee4j/mojarra/issues/5023

**Comment by tandraschko** [comment] 2023-02-20 17:20
and yes, it might work in older PF versions as we completely refactored the AutoUpdate handling but we are using a official JSF API, which should just be fixed in Mojarra

**Comment by tandraschko** [comment] 2023-02-20 17:24
Would you please create a new issue, based on https://github.com/eclipse-ee4j/mojarra/issues/5023 and add your reproducer?

i will check the MF issue tomorrow, if this usage with composite subdirs is supported in the specs

**Comment by mkomko** [comment] 2023-02-21 09:25
> Don't know how you suspected autoUpdate to be the problem, but indeed looks like the problem. If you remove it, it works... See also: [eclipse-ee4j/mojarra#5023](https://github.com/eclipse-ee4j/mojarra/issues/5023)

I commented everything out in our production code and slowly put things back in ;-). Thank you JRebel!
Thanks for your analysis!


> Would you please create a new Mojarra issue, based on [eclipse-ee4j/mojarra#5023](https://github.com/eclipse-ee4j/mojarra/issues/5023) and add your reproducer?

Done: https://github.com/eclipse-ee4j/mojarra/issues/5214
Thank you very much!

**Comment by tandraschko** [comment] 2023-02-21 15:20
MyFaces works fine when setting org.apache.myfaces.STRICT_JSF_2_ALLOW_SLASH_LIBRARY_NAME = true

**Closed as not planned** 2023-02-21 15:33 UTC
Labels: :lady_beetle: defect, third-party

**Comment by melloware** [comment] 2023-09-10 11:36
BalusC has fixed this in Mojarra 4.0.5-SNAPSHOT.
