### ISSUE TITLE
SelectOneListbox: add keyboard support

### ISSUE THREAD

**Issue by movalz** [primefaces/primefaces#1436] opened 2016-05-18 16:04 UTC
I'm missing keyboard support for tag p:selectOneListbox like it is present for h:selectOneListbox:
- when focus is reached via TAB key one of the rows (the first row or the selected row) should be highlighted with a dotted frame
- pressing UP or DOWN key should move the highlighted row up/down and select that row
- POS1/END should jump to the beginning/end of the items list with changing the selected item
- If a p:outputLabel has a defined accesskey and is assigned to the p:selectManyMenu via its 'for' attribute the selectOneListbox should get focus (like when using TAB key to reach it) if the accesskey is pressed

I'm using PrimeFaces 6.0-RC3

**Comment by tandraschko** [comment] 2017-10-16 20:05
a PR is really welcome here

**Comment by mertsincan** [comment] 2018-11-13 09:17
Duplicate of #4237

**Closed as completed by mertsincan** 2018-11-13 09:17 UTC
