### ISSUE TITLE
DataTable: Navigation from header facet causes the value EL to be re-evaluated

### ISSUE THREAD

**Issue by mihaiDumea** [primefaces/primefaces#9793] opened 2023-02-13 19:04 UTC
### Describe the bug

Navigation from header facet causes the value EL to be re-evaluated, recreating the bean referenced by the EL in a new scope. This recreation is unnecessary as is for no use and may cause problems. This doesn't happen for navigation from table rows.

### Reproducer

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/10725355/primefaces-test-master.zip)
1. Click the menu item to navigate to new page.
2. Both webbeans are reconstructed. The current one shouldn't be.

### Expected behavior

The current webbean should not be reconstructed after navigation, as the current scope is no longer valid.

### PrimeFaces edition

None

### PrimeFaces version

12

### JSF implementation

Mojarra

### JSF version

2.3.19

### Java version

1.8

**Comment by melloware** [comment] 2023-02-13 19:20
Wow I just checked out your reproducer that is interesting!

**Comment by melloware** [comment] 2023-02-14 21:12
Also their generated scripts are identical.

Header:
```js
PrimeFaces.ab({s:&quot;frmTest:dt:hcb&quot;,f:&quot;frmTest&quot;});return false;
```

Row:
```js
PrimeFaces.ab({s:&quot;frmTest:dt:0:cb&quot;,f:&quot;frmTest&quot;});return false;
```

**Comment by mihaiDumea** [comment] 2023-02-14 23:50
The row index from ActionEvent(UIData#broadcast) is a valid index as the button is on a row I suppose. But when the ActionEvent is created by the menu item, the row index is invalid(-1) and the model is set to null.

**Comment by mihaiDumea** [comment] 2023-02-14 23:54
It may be a bug on JSF.

**Comment by Rapster** [comment] 2023-02-15 09:30
Like you said, when event gets queued, it is with index -1 (because it doesn't come from a row), later on when that same event is broadcasted, redirection happens (bean TestView is destroyed) and as rowIndex is -1 call to getValue will force creation of TestView.

See code:

```java
    public void broadcast(FacesEvent event) throws AbortProcessingException {
        if (!(event instanceof WrapperEvent)) {
            super.broadcast(event);
        } else {
            FacesContext context = event.getFacesContext();
            WrapperEvent revent = (WrapperEvent)event;
            if (this.isNestedWithinIterator(context)) {
                this.setDataModel((DataModel)null);
            }

            int oldRowIndex = this.getRowIndex();
            this.setRowIndex(revent.getRowIndex());
            FacesEvent rowEvent = revent.getFacesEvent();
            UIComponent source = rowEvent.getComponent();
            UIComponent compositeParent = null;

            try {
                if (!UIComponent.isCompositeComponent(source)) {
                    compositeParent = UIComponent.getCompositeComponentParent(source);
                }

                if (compositeParent != null) {
                    compositeParent.pushComponentToEL(context, (UIComponent)null);
                }

                source.pushComponentToEL(context, (UIComponent)null);
                source.broadcast(rowEvent); // redirection happens here
            } finally {
                source.popComponentFromEL(context);
                if (compositeParent != null) {
                    compositeParent.popComponentFromEL(context);
                }

            }

            this.setRowIndex(oldRowIndex); // does it makes sense to do that while redirection is happening...?
        }
    } 
```


Hard to say if it's a bug...

**Comment by mihaiDumea** [comment] 2023-02-15 10:14
The h:dataTable also has facets. Then the bug should also replicate there. Unless is a limitation(navigation outside columns) and is specified in the docs.

**Comment by mihaiDumea** [comment] 2023-02-15 10:19
If you change the p:dataTable with h:dataTable in the reproducer, will also replicate the bug.

**Comment by tandraschko** [comment] 2023-02-15 10:40
Then lets close this bug and feel free to open a issue on Mojarra and MyFaces side

**Closed as not planned** 2023-02-15 10:40 UTC
Labels: :lady_beetle: defect
