### ISSUE TITLE
Filter dataTable is not working 

### ISSUE THREAD

**Issue by louayabdelhedi** [primefaces/primefaces#2063] opened 2017-02-07 09:50 UTC
# IMPORTANT 
- If you open an issue, fill every item. Otherwise the issue might be closed as invalid.
- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? NO
- Application server + version: Tomcat 8
- Affected browsers: All

## 2) Expected behavior

dataTable filter should work normally

## 3) Actual behavior

When I am trying to use the filter inside the dataTable is not filtering the data

## 4) Steps to reproduce

Upgrade primefaces 5.3 to 6.0

## 5) Sample XHTML

<h:form id="Holidays_Form" dir="auto" >
			<div class="align_btn_ar" align="right">
				<p:commandButton action="#{holidayBean.create()}" icon="ui-icon-plus" value="#{msg.Nouveau}" title="#{bundle.Nouveau}" ajax="false" type="push" />
			</div>
			<p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" />
			
			<p:dataTable var="holiday" value="#{holidayBean.holidaysList}" widgetVar="DataTable" rows="10" paginator="true" rendered="true" emptyMessage="#{msg.MsgNoRecords}" id="DataTable"
				filteredValue="#{holidayBean.filteredHolidaysList}" class="fixed_table" paginatorPosition="bottom" rowsPerPageTemplate="5,10,20,50">
				
				<f:facet name="header">
					<div align="left">
						<p:outputPanel>
							<p:inputText id="globalFilter" onkeyup="PF('DataTable').filter();PF('statusDialog').hide()" style="width:150px;" placeholder="#{msg['SearchFields']}" />
						</p:outputPanel>
					</div>
				</f:facet>
				<p:column headerText="#{msg['Description']}" sortBy="#{holiday.name}" filterBy="#{holiday.name}" filterStyle="display:none" filterMatchMode="contains" class="fixed_table_width">
					<h:outputText value="#{holiday.name}" />
				</p:column>

## 6) Sample bean

public class Holiday extends TimestampEntity implements Serializable {

    private static final long serialVersionUID = 1L;
    private int id;

    
    private String name;

     private Date startDate;

    private Date endDate;

   private Company company;

    public Holiday() {
    }

    public Holiday(int id, String name, Date startDate, Date endDate, Company company) {
        super();
        this.id = id;
        this.name = name;
        this.startDate = startDate;
        this.endDate = endDate;
        this.company = company;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }
  }

**Comment by melloware** [comment] 2017-02-08 00:45
I suggest you take the steps above and "Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution."   

We use datatable filtering all the time and it is working fine in PF 6.0 so it must be something wrong with your code.  By creating a simple test case like above you should be able to prove whether or not it is a real bug.

**Comment by jxmai** [comment] 2017-03-13 19:50
The sample is not complete and not in minimal form. There is no `HolidayBean`  and no `TimestampEntity` for instance. 

---

AFAICS, please check the way to create the table and examine any error on the console since using `ajax='false'` is suspicious.

```xhtml
<p:commandButton action="#{holidayBean.create()}"  ... ajax="false" type="push" />

```

**Comment by tandraschko** [comment] 2017-03-14 08:30
closing as invalid as the sample is not complete. Maybe better try to forum first if you don't have a complete sample.

**Closed as completed by tandraschko** 2017-03-14 08:30 UTC
Labels: Resolution: Invalid
