### ISSUE TITLE
OutputLabel: Label in composite component cannot resolve required attribute of input component in another composite component

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#6856] opened 2021-01-19 16:14 UTC
**Describe the defect**
I have two composite components. One (CC1) contains the `p:outputLabel` and the other one (CC2) a `p:inputNumber`. Both are connected using the for-attribute.

The `OutputLabelRenderer` tries to resolve the `required` attribute of the `p:inputNumber` which is defined as `required="#{cc.attrs.required}"` (required for CC2 is not hardcoded in the composite component, it is an attribute on the composite component). The problem is, that the renderer does not push the parent (==CC2) of the `p:inputNumber` to the stack and therefore the EL-resolvers use CC1 for the reference to `cc.attrs`.

OmniFaces had the same bug in its `o:tree` and fixed it using the code I will provide in a PR

- https://stackoverflow.com/a/36294437/1741604
- https://github.com/omnifaces/omnifaces/commit/bfa8d00901a6e2079220f80986675e6c3cb89bf3

**Environment:**
 - PF Version: 9.0-SNAPSHOT (But 10.0.0-SNAPSHOT has the same code)

**Comment by melloware** [comment] 2021-01-19 16:18
Isn't that similar to this? https://github.com/primefaces/primefaces/issues/3709

**Comment by fanste** [comment] 2021-01-19 16:21
#3709 seems to complain about bean validation. This issue has to to with composite components.

PR #6857

**Comment by tandraschko** [comment] 2021-01-19 16:22
nope it isnt, it think #3709 might already be working?

**Comment by fanste** [comment] 2021-01-19 17:53
Simplified [test](https://github.com/fanste/primefaces-test/tree/test-6856) as requested in the PR.

It is enough if the input component is inside a composite component.
With the fix of #6857 the indicator is displayed.

**Comment by melloware** [comment] 2021-01-19 21:30
I jut wrote an Integration Test using your example its test 8 `testComposite3` and its passing.

Now our Integration tests use MyFaces 2.3.7 not sure if that makes a difference?

See: https://github.com/primefaces-extensions/primefaces-integration-tests/commit/2cd813feb3e85d4e50dd5df363629178adf20d75

**Comment by melloware** [comment] 2021-01-19 21:32
I think the integration test also proves #3709 is working.

**Comment by Rapster** [comment] 2021-01-19 21:33
@fanste I had a quick look on your reproducer, I only see one composite and it's very similar to https://github.com/primefaces/primefaces/issues/1633 but this has been fixed in PF6. Am I missing something?

Except (according to the fix I made with Thomas), you can write it down like this (without specifying `:invalue`):

```xml
<p:outputLabel for="ccTC" value="This should have an indicator!" />
<g:testComposite id="ccTC" value="#{testView.string}" required="true" />
```

Also, maybe you meant to use targets and not name (of editableValueHolder)

**Comment by Rapster** [comment] 2021-01-19 21:55
Also, maybe you meant to use targets and not name

**Comment by fanste** [comment] 2021-01-20 10:06
@Rapster Yes I mentioned in that comment that it is enough to only put the input component inside a composite component. I just also found your #1633 but it does still not work with Mojarra 2.2.x nor MyFaces 2.2.x (using my reproducer).

I currently use `for="ccTC"` as a workaround - maybe it also is the only solution as the MyFaces guy said, that a composite component is a self-contained thing whoose internals should not be referenced from outside.

So it is up to you to decide if we should add a fix or not.

> Also, maybe you meant to use targets and not name (of editableValueHolder)

According to the comments `name` could be used if only a single component is referenced and `targets` is then set to `name`. Only if multiple components should be referenced you have to additionally fill `targets`.

**Comment by tandraschko** [comment] 2021-01-20 10:07
@fanste can you please check the JSF specs/docs, if invokeOnComponent should always push all components, not only if the clientId matches?

**Comment by tandraschko** [comment] 2021-01-20 10:09
@Rapster the difference of our other issue (#1633) is, that in @fanste example the required attr of the wrapped input is based upon a #{cc} expression. If his example would be just be required=true, it would work.

**Comment by tandraschko** [comment] 2021-01-20 10:14
Ok, i think we mix some issues here.
What works:
- p:outputLabel for=cc:input, required set to any value just not something with #{cc}
- p:outputPabel for=cc, , required set to any value, also with #{cc}

What works not:
- p:outputLabel for=cc:input, required set any expression with #{cc} inside

**Comment by tandraschko** [comment] 2021-01-20 10:14
We could only fix that correctly and good if we use invokeOnComponent if Mojarra would implement it the same like MyFaces. We need to check whats correct.

Otherwise i dont think there is a good solution.

**Comment by fanste** [comment] 2021-01-20 10:20
@tandraschko The spec does not really tell something about push/pop inside `invokeOnComponent` if I had the correct document. But the Mojarra JSF API for 2.3 has the following comment on `findComponent`. (Edit: MyFaces API for 2.3 has the same comment)

>     * <p class="changed_added_2_2">WARNING: The found
>     * <code>UIComponent</code> instance, if any, is returned
>     * <strong>without</strong> regard for its tree traversal context.
>     * Retrieving an EL-bound attribute from the component is not safe.
>     * EL expressions can contain implicit objects, such as
>     * <code>#{component}</code>, which assume they are being evaluated
>     * within the scope of a tree traversal context.  Evaluating
>     * expressions with these kinds of implicit objects outside of a
>     * tree traversal context produces undefined results.  See {@link
>     * #invokeOnComponent} for a method that <strong>does</strong>
>     * correctly account for the tree traversal context when operating
>     * on the found <code>UIComponent</code> instance.  {@link #invokeOnComponent}
>     * is also useful to find components given a simple <code>clientId</code>.

This tells me, that the traversal context has to be completely valid which it is not at the moment. MyFaces should have the correct impl while Mojarra is wrong.

**Comment by fanste** [comment] 2021-01-20 10:21
@tandraschko The spec does not really tell something about push/pop inside `invokeOnComponent` if I had the correct document. But the Mojarra JSF API for 2.3 has the following comment on `findComponent`.

>     * <p class="changed_added_2_2">WARNING: The found
>     * <code>UIComponent</code> instance, if any, is returned
>     * <strong>without</strong> regard for its tree traversal context.
>     * Retrieving an EL-bound attribute from the component is not safe.
>     * EL expressions can contain implicit objects, such as
>     * <code>#{component}</code>, which assume they are being evaluated
>     * within the scope of a tree traversal context.  Evaluating
>     * expressions with these kinds of implicit objects outside of a
>     * tree traversal context produces undefined results.  See {@link
>     * #invokeOnComponent} for a method that <strong>does</strong>
>     * correctly account for the tree traversal context when operating
>     * on the found <code>UIComponent</code> instance.  {@link #invokeOnComponent}
>     * is also useful to find components given a simple <code>clientId</code>.

This tells me, that the traversal context has to be completely valid which it is not at the moment. MyFaces should have the correct impl while Mojarra is wrong.

**Comment by tandraschko** [comment] 2021-01-20 10:23
yep, seems like a Mojarra bug then. Please create a issue here: https://github.com/eclipse-ee4j/mojarra 
and maybe you can create a PR, mojarra team doesnt to be very active.

**Comment by Rapster** [comment] 2021-01-20 10:28
I remember talking about this long time back when I was working on #1633: https://github.com/primefaces/primefaces/issues/1633#issuecomment-283584995 

Sounds like a Mojarra issue

**Comment by tandraschko** [comment] 2021-01-20 10:34
yep. TBH i dont think we should support this case. There are 2 possible solutions:
- use invokeOnComponent but Mojarra doesnt follow the specs
- loop all parents and push them into EL (expressions could even contain #{component})

both results in much worse performance as outputLabel is mostly very often used on a view.
I think our way to support #1633 is ok.


@fanste you can use either
```
            <p:outputLabel for="ccTC:inValue" value="This should have an indicator!" indicateRrequired="true" />
            <g:testComposite id="ccTC" value="#{testView.string}" required="true" />
```
or
```
            <p:outputLabel for="ccTC" value="This should have an indicator!" indicateRrequired="true" />
            <g:testComposite id="ccTC" value="#{testView.string}" required="true" />
```

**Comment by Rapster** [comment] 2021-01-20 10:38
Or don't use composite, facelet tags instead (combined with omnifaces is even better)😉 Just like mention Thomas, composite itself has poor performance and IMO not really well supported

**Comment by tandraschko** [comment] 2021-01-20 10:42
composite itself are a bit slower as own tags yes, but the performance isnt bad, even great in MyFaces.
Composites are in general good supported IMO, just some edge cases are not. Like p:message for="#{mycc}", same case as #1633, just for messages.

Just invokeOnComponent would slower as findComponent, which is currently used.

**Comment by fanste** [comment] 2021-01-20 10:47
Maybe we should at least use `forComponent.invokeOnComponent(...)` as that would push the correct value for `#{component}`. Not supporting `#{cc}` is okay for me if the myfaces guy is correct about that internals of composite components should not be adressed from outside. For that case we can directly reference the composite component as long as we only have a single-component `cc:editableValueHolder`.

I will set the PR for Mojarra on my todo.

**Comment by tandraschko** [comment] 2021-01-20 10:56
As we dont have any open issue regarding outputLabel and #{component} since years, we should not change that for now.

JSF applications are often form-centric with many outputLabels on the view.

**Closed as completed by tandraschko** 2021-01-20 10:56 UTC
Labels: :lady_beetle: defect

**Comment by fanste** [comment] 2021-01-21 11:14
> As we dont have any open issue regarding outputLabel and #{component} since years[...]

Well.. until now i guess :D But thats not that a big deal, as there is a not that ugly workaround. So this is just for documentation in case someone has the same problem and stumbles accros this comment: 

`The class 'org.primefaces.component.outputlabel.OutputLabel' does not have the property 'xxx'.`
```
<p:outputLabel for="input" ... />
<p:inputText id="input" ... required="#{... and component.xxx ...}" />
```

**Solution:**
Set the `binding` attribute and use that instead of `#{component}`.
```
<p:outputLabel for="input" ... />
<p:inputText id="input" binding="#{bndInput}" ... required="#{... and bndInput.xxx ...}" />
```
This is required because `component` is pointing to the output label instead of the input text while evaluating the required expression.
