### ISSUE TITLE
Ribbon onTabChange

### ISSUE THREAD

**Issue by integrityhu** [primefaces/primefaces#2185] opened 2017-03-16 12:29 UTC
The documentation say that ribbon delivered from tabview, and any event that implemented in tabview should use. I try to implement onTabChange event to hold actual page index in server side, but the javascript doesn't invoked. I think there missing event handler, so I looked around the code. 

primefaces/ribbon/src/main/java/org/primefaces/component/ribbon/RibbonRenderer.java
primefaces/ribbon/src/main/resources-maven-jsf/ui/ribbon.xml

There is no onTabChange event implemented. Please change the source for handle tab change events (attached)
[ribbon.zip](https://github.com/primefaces/primefaces/files/847651/ribbon.zip)

**Comment by Rapster** [comment] 2017-03-16 12:43
Please provide a PR instead

**Comment by Rapster** [comment] 2017-03-16 12:49
I'm not sure if `onTabChange` should be an attribute, indeed, it is for `TabView` but is it necessary or common while we could use`p:ajax event="tabChange"`?

**Comment by integrityhu** [comment] 2017-03-16 12:58
Yes, but unfortunately Ribbon is not an ajax behavior component.

**Comment by Rapster** [comment] 2017-03-16 13:05
You can make become one ;)

**Comment by integrityhu** [comment] 2017-03-16 13:10
Yes I'd like. Can you write me how can I start it? Could you send me a sample?

**Comment by Rapster** [comment] 2017-03-16 13:19
It should give you some clues to start https://github.com/primefaces/primefaces/pull/2167

**Comment by integrityhu** [comment] 2017-03-16 14:02
how can I add getBehaviorEventMapping() to Ribbon? I visit Slider for sample.

**Comment by integrityhu** [comment] 2017-03-16 14:05
ok., I placed it in RibbonTemplate.java

**Comment by integrityhu** [comment] 2017-03-16 14:32
I made some changes for ajax behavior (attached)
[ribbon-ajaxbehavior.zip](https://github.com/primefaces/primefaces/files/847983/ribbon-ajaxbehavior.zip)

**Comment by Rapster** [comment] 2017-03-16 14:35
Again, provide a PR please. See https://help.github.com/articles/creating-a-pull-request/

**Comment by Rapster** [comment] 2017-03-16 14:47
Check out your template by the way, you did a bad copy-paste I think :p

**Comment by integrityhu** [comment] 2017-03-16 15:31
https://github.com/primefaces/primefaces/pull/2186
thanx :p

**Comment by Rapster** [comment] 2017-03-16 15:34
Your PR will never be accepted, too many files changed for no reason. Did you do a merge? Please do a rebase

**Comment by integrityhu** [comment] 2017-03-16 15:34
Usage:

<p:ribbon id="topRibbon" widgetVar="topRibbonWidget" activeIndex="#{styleManager.actualRibbonIndex}" onTabChange="handleTabChange(index)">
		<p:ajax event="tabChange" listener="#{styleManager.handleTabChange}"/>
...
</p:ribbon>

StyleManager:
    public void handleTabChange(TabChangeEvent event) {
        actualRibbonIndex = (Integer)event.getData();
    }

JavaScript:
function handleTabChange(index) {
	alert(index);
}

**Comment by integrityhu** [comment] 2017-03-16 15:39
please take your piece to merge it. Best regards, Zoltán

**Comment by Rapster** [comment] 2017-03-16 15:43
Sorry no can do :)

**Comment by integrityhu** [comment] 2017-03-16 15:44
that's what I can do now, too. :-)

**Comment by integrityhu** [comment] 2017-03-16 15:55
I changed 3 files only. Please check it in attachet zip file.
I've no idea how can I rebase, and I've no time to continue with github.

**Comment by Rapster** [comment] 2017-03-16 15:57
Don't bother, I'll take care of this (one day :p)

**Comment by integrityhu** [comment] 2017-03-16 16:05
Ok, thank you! Have a nice day!

**Comment by Rapster** [comment] 2017-03-16 19:40
@cagataycivici any reason why Ribbon does not extend TabView? I just make it work but I'm wondering....

**Comment by integrityhu** [comment] 2017-03-16 19:56
Neither onTabChange nor  ajax tabChange... so I made it. ;-)
Just github usage not know me, sorry.

**Comment by integrityhu** [comment] 2017-03-16 20:05
ribbon.xml parent > javax.faces.component.UIPanel
tabview.xml parent > org.primefaces.component.api.UITabPanel
JavaScript working well from /src/main/resources/META-INF/resources/primefaces/ribbon/ribbon.js 
PrimeFaces.widget.Ribbon = PrimeFaces.widget.TabView.extend

But onTabChange callback didn't work, before I added it in ribbon.xml. 

If it's easy just change the parent, well done. I just try understand AjaxBehavior, so I implemented it as if it has no parent with implemented event handlers.

**Comment by Rapster** [comment] 2017-03-19 07:48
@tandraschko should we implement `onTabChange` while we could do this:
```xml
<p:ribbon>
    <p:ajax event="tabChange" oncomplete="alert('it's alive!')" />
</p:ribbon>
```

**Comment by tandraschko** [comment] 2017-03-19 09:18
IMO the behavior event is enough

**Comment by integrityhu** [comment] 2017-03-19 10:53
Okay, I changed my implementation (see attachment). TabView has onTabChange, so I added to ribbon.xml, too. Ajax tabChange event has getTab() method. How can I find out the index of this tab?
Best Regards, Zoltan
[ribbon-withnewparent.zip](https://github.com/primefaces/primefaces/files/853131/ribbon-withnewparent.zip)

**Comment by integrityhu** [comment] 2017-03-19 11:17
I changed RibbonRenderer.java, but activeIndex become -1 on tabChange event.
[ribbon-withnewparent.zip](https://github.com/primefaces/primefaces/files/853143/ribbon-withnewparent.zip)

**Comment by integrityhu** [comment] 2017-03-19 16:46
IMHO that two file fix is not enought...

**Comment by integrityhu** [comment] 2017-03-19 20:39
I think we need declare interfaces in ribbon.xml like this:

         <interfaces>
                <interface>
                        <name>org.primefaces.component.api.Widget</name>
                </interface>
                <interface>
                        <name>javax.faces.component.behavior.ClientBehaviorHolder</name>
                 </interface>
                <interface>
                        <name>org.primefaces.component.api.PrimeClientBehaviorHolder</name>
                </interface>
         </interfaces>

What do you think?

**Comment by integrityhu** [comment] 2017-03-19 21:14
Ok, I checked. Not needed (interfaces are inherited).

**Comment by integrityhu** [comment] 2017-03-19 21:18
Why I get activeIndex = 0 on tabChange event?

    public void handleTabChange(TabChangeEvent event) {
        Ribbon ribbon = ((Ribbon)event.getComponent());
        int tabIndex = ribbon.getActiveIndex();
        actualRibbonIndex = tabIndex; 
    }

event.data = null

**Comment by integrityhu** [comment] 2017-03-20 09:54
workaround:
new index:
        Ribbon ribbon = ((Ribbon) event.getComponent());
        int tabIndex = ribbon.getChildren().indexOf(event.getTab());
old index:
        int oidx = ribbon.getActiveIndex();

**Comment by melloware** [comment] 2017-03-22 00:01
While we are at it this ticket is a duplicate of #1514 so if we do fix this make sure that one is closed as well.

**Closed as completed** 2017-03-22 13:57 UTC
Labels: enhancement

**Comment by tandraschko** [comment] 2017-03-22 14:02
@cagataycivici could you please create a new milestone for RC3 or final?
