### ISSUE TITLE
SelectOneMenu: NPE in decode method

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#5809] opened 2020-04-17 13:45 UTC
setEditable(true) gives an NPE at SelectOneMenuRenderer.decode.
PrimeFaces version: 7.0, 7.0.12, 8.0

**Comment by melloware** [comment] 2020-04-17 13:48
Looks fine on the Showcase. https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml

Can you post your full NPE stacktrace?  Reproduce it with PF Test project?

**Comment by fcorneli** [comment] 2020-04-17 14:04
The issue happens in combination with an empty UISelectItem as follows:
```
input = (SelectOneMenu) application.createComponent(SelectOneMenu.COMPONENT_TYPE);
SelectOneMenu selectOneMenu = (SelectOneMenu) input;
//selectOneMenu.setDisabled(!editable);
selectOneMenu.setEditable(editable);
UISelectItem emptySelectItem = (UISelectItem) application.createComponent(UISelectItem.COMPONENT_TYPE);
input.getChildren().add(emptySelectItem);
```

**Comment by fcorneli** [comment] 2020-04-17 14:05
See:
https://github.com/e-Contract/jsf-crud
for a working example. Within `CRUDComponent` you can play with the above code.

**Comment by melloware** [comment] 2020-04-17 14:06
Can you just create a reproducible example for us?
https://github.com/primefaces/primefaces-test

**Comment by melloware** [comment] 2020-04-20 11:46
@fcorneli Any word on a small reproducer?

**Comment by fcorneli** [comment] 2020-04-20 16:43
Tried to replicate it with:
```
<p:selectOneMenu editable="true" value="#{testView.testString}">
    <f:selectItem /> 
    <f:selectItem itemLabel="label" itemValue="value"/>
</p:selectOneMenu>
```
but this does not give me the NPE. Will try to create an example with a simple custom component.

**Comment by melloware** [comment] 2020-04-20 16:53
excellent.  that would be great.

**Comment by fcorneli** [comment] 2020-04-20 20:35
For the moment I'm only capable of replicating the issue within:
https://github.com/e-Contract/jsf-crud
I've added within `CRUDComponent` a reference to this issue. Hence simply uncomment:
```
selectOneMenu.setEditable(true);
```
And run the demo at:
http://localhost:8080/jsf-crud-demo/auto-id.xhtml
to replicate the issue.
BTW: I've stumbled upon another NPE using Column.sortBy. Also documented this within the demo.

**Comment by melloware** [comment] 2020-04-20 22:21
@fcorneli I definitely believe you.  However the reason we ask for a PrimeFaces test project is multiple reasons:

1. We are not debugging your app, we are debugging a problem.

2. An MVCE minimal, complete and verifiable example: https://stackoverflow.com/help/minimal-reproducible-example

3. Using the minimal amount of code to reproduce the problem then allows us to see if it a JSF issue by testing both:

`mvn clean jetty:run-exploded -Pmojarra23`

`mvn clean jetty:run-exploded -Pmyfaces23`

So we can see your bug in both Mojarra and MyFaces easily.

4. Takes all the noise out of equation of a complex scenario.

So I still ask if you can reproduce it using PF Test.

**Comment by fcorneli** [comment] 2020-04-21 04:54
primefaces-test based test is available at:
https://github.com/fcorneli/dynamic-table/tree/5809

**Comment by melloware** [comment] 2020-04-21 14:27
Thank you!  Now that I see the error and stack trace the problem is obvious.  Fixed with PR

**Closed as completed** 2020-04-21 14:34 UTC
Labels: :lady_beetle: defect
