### ISSUE TITLE
DataTable: saving edited row after reorder (drag n' drop) updates wrong row

### ISSUE THREAD

**Issue by Karolis92** [primefaces/primefaces#1499] opened 2016-06-07 10:39 UTC
When `p:dataTable` is used with attributes `draggableRows="true"` and `editable="true"` and user tries to reorder row by dragging it when row is in editing mode - after saving, row in old position gets changed, and not the dragged one.

Strangely `event.getObject()` on `rowEdit` event returns correct Object (dragged one), which is unedited, because values are overwritten to Object in old position.

This editing could work correctly or dragging could be disabled when rows are edited.

Primefaces 6.0

**Comment by Karolis92** [comment] 2016-06-08 06:24
Found out, that there is simpler way to reproduce this issue, dragging not in edit mode also causes problems:
1. reorder table row by dragging it
2. then edit that row
3. row in old position gets changed, and not the dragged one.

**Comment by michael-las** [comment] 2016-06-08 15:38
I guess it has to do with the client id of the row. It won't change after the row was dropped onto a new position. The row-edit ajax-request addresses the row by its index. Therefore the correct row will be updated in the model (event.getObject()) but the response will contain the new client id of the row so that the wrong row will be replaced in the DOM.

E. g. 

| Index | Client ID | Brand | Color |
| --- | --- | --- | --- |
| 0 | cars:0 | Honda | Yellow |
| 1 | cars:1 | Mercedes | Black |
| 2 | cars:2 | Toyota | Red |

After the Toyota was moved to the top of the table:

| Index | Client ID | Brand | Color |
| --- | --- | --- | --- |
| 0 | cars:2 | Toyota | Red |
| 1 | cars:0 | Honda | Yellow |
| 2 | cars:1 | Mercedes | Black |

Changing the Color of the Toyota to 'Silver' and saving the row will lead to a row-edit-request with a rowEditIndex of 0. The correct object will be updated in the model and rendered again. The result of the rendering will be part of the response. Since the object is at index 0, the client id of the row will become cars:0, that is

| Client ID | Brand | Color |
| --- | --- | --- |
| cars:0 | Toyota | Silver |

Now, the DOM element with ID cars:0 (the Honda) will be updated. 

| Index | Client ID | Brand | Color |
| --- | --- | --- | --- |
| 0 | cars:2 | Toyota | Red |
| 1 | cars:0 | Toyota | Silver |
| 2 | cars:1 | Mercedes | Black |

It seems to be a bit more complicated under the hood, since you don't see the change immediately. You'll have to edit the Honda and cancel the edit first. But this is not part of the problem.

**Comment by Karolis92** [comment] 2016-06-08 19:14
No, it's not only the response and redrawing.

When Toyota is edited, edit request goes for the index 2 of the list, and in the list as index 2 there is Mercedes (now after reorder), so it's edited,
ClientId's for the input remain the same after reorder, so Toyota color input has id: `cars:2:colorInput` (now Mercedes) etc.

**Comment by michael-las** [comment] 2016-06-08 23:30
You're right, I forgot about the ajax request lifecycle. I assume, that the client ids will be used there. Since they're different between view and model, the wrong object will be updated. For the row edit event, the rowEditIndex will be used, so that it contains the moved (but unchanged) object.

Anyway, the problem is that the client ids won't get updated after a row is dragged.

**Comment by michael-las** [comment] 2016-06-09 11:37
@tandraschko (@cagataycivici, or any other project member): what do you think of the following approach:
1. encode the DraggableRowsFeature, so that all rows between fromIndex and toIndex will be encoded
2. update the DOM by the encoded rows.
3. because of 2: disable drag while row editing is active.

**Comment by gahsifuentes** [comment] 2016-06-15 17:31
Hello, @Karolis92 .

Is it similar to what I describe [ here ? ](http://forum.primefaces.org/viewtopic.php?f=3&t=45925)

Have you already seen [this topic on StackOverFlow](http://stackoverflow.com/questions/33908480/primefaces-reordering-rows-containing-inputs/33911857#33911857) ?

Do you have any disabled or readonly field in ur Datatable?

**Comment by Karolis92** [comment] 2016-06-16 05:09
Hi,  @gahsifuentes 
No, I don't have disabled or readonly fields in the DataTable.
And I use `p:cellEditor` with output and input facets

Now I use `<p:ajax event="rowReorder" update="@this"/>`, so after reorder dataTable is redrawn and inputs after that work as expected, but this has a down side - any rows that are in input (editing) mode switches back to output mode and loses all unsaved changes.

As you don't use cellEditor, you could try encapsulate dataTable into `p:fragment` (http://www.primefaces.org/showcase/ui/ajax/fragment.xhtml) with my mentioned ajax element or if that doesn't work, try to add `process="@form"`

**Comment by michael-las** [comment] 2016-06-16 06:52
@Karolis92 As there's no answer from the project team, I didn't provide a PR. [edit] I don't know if this is the way to go [/edit]. But perhaps, the commit above may help you.

**Comment by Airblader** [comment] 2016-09-25 09:29
I just came across this as well trying to write a simple TODO list demo app. Reordering items and then marking one as done causes the wrong item to be marked.

Given that this causes a user to unknowingly modify the wrong data this can be a fairly severe bug if the table contains important data.

**Comment by lcottereau** [comment] 2017-06-12 16:31
I encountered the same problem when the `action` of a `<p:commandButton>` depends on the row item. Adding `<p:ajax event="rowReorder" update="@this"/>` to the `<p:dataTable>` solved it. Thank you @Karolis92 

My version of primefaces is 5.2.5

**Comment by melloware** [comment] 2019-11-13 15:16
Closing this issue as new issue #5326 has attached a reproducible test case.

**Closed as completed by melloware** 2019-11-13 15:16 UTC
Labels: :lady_beetle: defect, workaround
