### ISSUE TITLE
InputTextarea Remaining Chars blocking input

### ISSUE THREAD

**Issue by TimLewen** [primefaces/primefaces#537] opened 2015-07-17 12:20 UTC
![remainingchars](https://cloud.githubusercontent.com/assets/13380617/8746937/7d4b40dc-2c8e-11e5-8c13-1a314ca9ef21.png)

When I manually enter the values as shown as in the attachment it's not possible to enter any more
chars even though it's displayed that I can enter 3 more chars.

I used http://www.primefaces.org/showcase/ui/input/inputTextarea.xhtml  for testing. It appears to be working in firefox and ie but not with Chrome 43.0.2357.134 m

**Comment by pthorson** [comment] 2015-09-25 20:43
An apparent fix by our friends at Goggle to the CR LF issue described here:
http://stackoverflow.com/questions/10030921/chrome-counts-characters-wrong-in-textarea-with-maxlength-attribute.

When a form with a text area like above is submitted, browsers will pass along 2 characters for each carriage return: "\r" and "\n". That is required behavior. However, client javascript only sees 1 character for each of the carriage returns.

Remaining Chars is "broken" in Chrome since PrimeFaces now passes through the maxLength attribute to browsers that support it (http://caniuse.com/#feat=maxlength). Chrome is preventing the entry of data which would cause trouble on the backend by counting the 2 characters for each carriage return.

**Comment by mertsincan** [comment] 2016-03-16 07:59
Fixed for 5.3.10 and 6.0. Duplicate of #768

**Closed as completed by mertsincan** 2016-03-16 07:59 UTC
