### ISSUE TITLE
SelectOneMenu: on page load and update will flicker on jQuery 3

### ISSUE THREAD

**Issue by jxmai** [primefaces/primefaces#3075] opened 2017-12-14 21:34 UTC
## 1) Environment
- PrimeFaces version: PF latest
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) No
- Application server + version: not relevant
- Affected browsers: not relevant

## 2) Expected behavior

Select One menu should not flicker

## 3) Actual behavior

Select one menu flickers on page load and on update

## 4) Steps to reproduce

load the page, you will see the select one menu flicker

and keep pressing the test button.

![pf_3075](https://user-images.githubusercontent.com/10467831/34278308-8d0b6464-e66f-11e7-9beb-c72556224b99.gif)

## 5) Sample XHTML

```xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

<f:view contentType="text/html">
	<h:head>
	</h:head>
	<h:body>

		<h:form id="mainForm">
			<p:selectOneMenu>
				<f:selectItem itemValue="" itemLabel="Some content....."/>
			</p:selectOneMenu>
			<p:commandButton value="Test" update="@form"/>
		</h:form>

	</h:body>
</f:view>

</html>
```

## 6) Analysis

This regression is caused by fc9eda2bdf7852523f553e26a52413f2d6c741b5 (#3062 jquery upgrade )

**Comment by tandraschko** [comment] 2017-12-15 09:41
I think its just caused by bad performance. SelectOneMenu JS takes ~12-22ms to render.

**Comment by tandraschko** [comment] 2017-12-15 10:11
Improved the performance a bit BUT the flickering is still there.

**Comment by tandraschko** [comment] 2017-12-15 10:24
seems like jquery 2.x is sometimes 1/3 - 1/2  faster on the initial page load to execute the selectors...
Can also be found here: https://jsperf.com/jquery-1-7-2-vs-jquery-1-8/96
Of course the difference is not big but that causes the flickering as the width is initialized after everything else...
so ~5ms can make a big difference here

**Comment by tandraschko** [comment] 2017-12-15 10:50
The best solution probably is to render the label via html directly insteadof JS - so the size is correct on rendering, also without JS.

**Comment by jxmai** [comment] 2017-12-21 23:42
Indeed, I also did an experiment to measure the time it takes to execute the following statements by the built in `performance.now`

https://github.com/primefaces/primefaces/blob/9f03b4ec1e4f1c9d9380929c60c735d56714f76a/src/main/resources/META-INF/resources/primefaces/forms/forms.selectonemenu.js#L7-L31


Using JQ2 (each click  generated an output)

![image](https://user-images.githubusercontent.com/10467831/34279020-06d16420-e674-11e7-8bea-346a4732ce8b.png)


Using JQ3 (each click  generated an output)

![image](https://user-images.githubusercontent.com/10467831/34279129-a574b5e6-e674-11e7-9a33-597efb928b87.png)


---

> so ~5ms can make a big difference here

The difference is really small (not even 5ms but 0.5ms :D ), but since JQ3 took longer than 1ms on average to finish initializing the component. The extra time is enough for monitors to capture the flickering.

![pf_3075](https://user-images.githubusercontent.com/10467831/34278308-8d0b6464-e66f-11e7-9beb-c72556224b99.gif)

> The best solution probably is to render the label via html directly insteadof JS - so the size is correct on rendering, also without JS.

:+1: 

---

note: Strangely, no matter how I manage to throttle JQ2, there is no flickering can be observed by profiler (throttle to 20ms each click). However, break points show that the label appears after init but it still cannot be caught by the profiler.
On the other hand, JQ3 shows flickering even running by a beefy processor (under 1ms each click).

**Comment by tandraschko** [comment] 2017-12-26 14:09
its true that jquery3 is a bit slower BUT i think the real problem is the document ready async behavior now
The fix is quite easy:
replace WidgetBuilder#initWithDomReady with WidgetBuilder#init
but not sure if it will have any side effects....

**Comment by tandraschko** [comment] 2017-12-26 14:58
Please see https://github.com/primefaces/primefaces/issues/3073

Its not a good way to use plain JS vs document.ready (or MOVE_SCRIPTS_TO_BOTTOM).
The only way to fix it correctly, is to render the label correctly in the DOM, without JS.

**Comment by tandraschko** [comment] 2017-12-28 12:00
Can you still reproduce it? I can't somehow...

**Comment by tandraschko** [comment] 2017-12-28 12:02
probably it's already fixed as the widget init is now snychronous again. See https://github.com/primefaces/primefaces/issues/3073

**Comment by tandraschko** [comment] 2017-12-28 12:03
The reason was:
the dom was replaced by the ajax engine
but the widget script was executed async, so probably you have some ms between "replace dom" and "init widget"

**Comment by tandraschko** [comment] 2017-12-28 12:04
The behavior should now only be visible on the initial page load when MoveScriptsToBottom is activated
there is also some flickering with selectBooleanButton
but those are more improvemets then bugs

**Comment by melloware** [comment] 2017-12-28 13:35
I do not notice any flicker now.

**Comment by tandraschko** [comment] 2017-12-28 14:07
Also tried to fix it via "rendering the label already on the server side" but the selectOneMenu still has a width calculation so it still flickers a bit, depending in the items-label length.
I think i  would close it as won't fix for now.
Modern layouts also use grids with ui-fluid, so the selectOneMenu will have 100% width and it won't flicker.
WDYT?

**Comment by jxmai** [comment] 2017-12-31 05:08
No flicking on update now :smiley: .  Comparing to JQ2 version, there only defect is flicking on initial page load but I am not too picky about the initial flickering

**Closed as completed** 2018-01-02 12:39 UTC
Labels: :lady_beetle: defect
