### ISSUE TITLE
DataTable: clearFilters doesnt work correclty with p:selectBooleanCheckbox

### ISSUE THREAD

**Issue by mihaiDumea** [primefaces/primefaces#8104] opened 2021-11-23 08:43 UTC
https://github.com/primefaces/primefaces/blob/f5643fc9b4a1574a8d2023a85794aedf390f74cb/primefaces/src/main/resources/META-INF/resources/primefaces/datatable/datatable.js#L3966

**Comment by tandraschko** [comment] 2021-11-23 09:45
same
a issue without description and sample is invalid

**Comment by mihaiDumea** [comment] 2021-11-23 12:08
Same example ai in #8105 but using the clearFilters instead of filter:
<p:selectBooleanCheckbox id="toggleFilters" value="#{mBean.showFilters}" itemLabel="#{mBean.showFilters ? 'Hide filters' : 'Show filters'}">
        <p:ajax update="items" oncomplete="PF('items').**clearFilters**()" />
    </p:selectBooleanCheckbox>
After clearFilter is executed, further usage of the column filter component will submit their entries with empty value instead of original. Instead of value reset, uncheck is appropriate.

**Comment by tandraschko** [comment] 2021-11-23 12:09
is it a duplicate of https://github.com/primefaces/primefaces/issues/8071? clearFilters just currently doesnt work perfectly with non-basic inputs like h:*

**Comment by mihaiDumea** [comment] 2021-11-23 12:17
I just replaced: _this.thead.find('> tr > th.ui-filter-column > .ui-column-customfilter :input').val('');_ with
this.thead.find('> tr > th.ui-filter-column > .ui-column-customfilter :input').each((index, element) => {
        if (element.type === 'checkbox') {
            element.checked = false;
        }
        else {
            element.value = '';
        }
    });

I need more time to check #8071

**Comment by tandraschko** [comment] 2021-11-23 12:26
could you please check if it works fine for h:selectBooleanCheckbox? If yes, i would close this issue in favor of #8071, i also renamed the title there

**Comment by mihaiDumea** [comment] 2021-11-23 12:47
h:selectBooleanCheckbox renders as an checkbox so, proposed solution works: it unchecks and does not remove the "on" value.

**Comment by melloware** [comment] 2021-11-23 12:50
Yep let's close this and @mihaiDumea can you subscribe to #8071 we will track this issue there.

**Closed as completed** 2021-11-23 12:55 UTC
Labels: :lady_beetle: defect

**Comment by tandraschko** [comment] 2021-11-24 10:20
@mihaiDumea can you retest pls?
