### ISSUE TITLE
CommandLink: In dynamic columns header doesn't work

### ISSUE THREAD

**Issue by ElSamplio** [primefaces/primefaces#2068] opened 2017-02-09 00:00 UTC
# ABSTRACT
I have a datatable with grouped header and dynamic columns. I put a commandLink in the dynamic columns header with its listener that gets some parameters, however it doesn't run the listener method. In the same XHTML I have the same kind of commandLinks in every row (first column) and they work properly

## 1) Environment
- PrimeFaces version: 6.0
- Does it work on the newest PrimeFaces version? No
- Application server + version: Glassfish 4.0
- Affected browsers: Chrome, Firefox, IE

## 2) Expected behavior
When commandLink is clicked, fire the event listener
...

## 3) Actual behavior
When commandLink is clicked, the event listener doesn't get fired
..

## 4) Steps to reproduce

1) Generate the dynamic model
2) Click on a commandLink of the columns header
.. 

## 5) Sample XHTML
```xml
html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <p:importEnum type="com.crowncolombiana.cute.web.enums.FiltroBlogEnum"
                  var="fltrEnm"/>
    <p:panel widgetVar="wvPnTablaEficiencia"
             header="#{msg.eficiencia_titulo_tabla}">
        <p:remoteCommand name="remotoFiltro" process="@this"
                         action="#{eficienciaOperacionalBean.commandLinkFiltroBlogListenerParaMaquina()}"/>
        <p:dataTable id="dtEficiencia" style="width: 3000px;"
                     widgetVar="wvDtEficiencia" scrollable="true"
                     scrollWidth="1200"
                     value="#{eficienciaOperacionalBean.tipoEventoEficienciaList}"
                     var="efc"
                     rowIndexVar="efcRowIndex"
                     rendered="#{eficienciaOperacionalBean.tipoEventoEficienciaList !=null and eficienciaOperacionalBean.tipoEventoEficienciaList.size()>0}">
            <p:columnGroup type="header">
                <p:row>
                    <p:column rowspan="3" headerText="#{msg.eficiencia_tipo_parada}" width="150"/>
                    <p:column colspan="#{eficienciaOperacionalBean.numeroMaquinas}" headerText="#{msg.eficiencia_tipo_maquina}" />
                </p:row>
                <p:row>
                    <p:columns value="#{eficienciaOperacionalBean.tipoMaquinasMaquinasDataModel}" var="tpMqDm" 
                               colspan="#{tpMqDm.cantidadPorTipo}">
                        <f:facet name="header">
                            <h:outputText value="#{tpMqDm.tipoMaquina.nombre}"/>
                        </f:facet>
                    </p:columns>
                </p:row>
                <p:row>
                    <p:columns value="#{eficienciaOperacionalBean.maquinaEficienciaList}"
                               var="mqEf" width="150">
                        <f:facet name="header">
                            <p:commandLink value="#{mqEf.maquina.nombre}" 
                                           onclick="remotoFiltro([{name:'maquinaId', value:#{mqEf.maquina.maquinasId}}])"/>
                        </f:facet>
                    </p:columns>
                </p:row>
            </p:columnGroup>
            <p:column width="150">
                <p:commandLink value="#{efc.tipoEvento.nombre}"
                               style="#{efc.tipoEvento.nombre.equals(msg.eficiencia_operacional)?'font-weight:bolder':'font-weight: normal'}"
                               process="@this"
                               action="#{eficienciaOperacionalBean.commandLinkFiltroBlogListener(efc.tipoEvento, fltrEnm.FILTRO_TIPO_EVENTO)}"/>
            </p:column>
            <p:columns value="#{eficienciaOperacionalBean.maquinaEficienciaList}"
                       var="cols" columnIndexVar="colsIndex" width="150">
                <h:outputText id="otEficiencia" value="#{cols.eficiencia}" rendered="#{efcRowIndex==0}"
                              style="font-weight: bolder">
                    <f:convertNumber locale="es" maxFractionDigits="2"/>
                </h:outputText>
                <p:tooltip for="otEficiencia"
                           value="#{efc.tipoEvento.nombre}"/>
                <h:outputText id="otEficienciaCalc" value="#{eficienciaOperacionalBean.calculoEficienciaPorMaquinaYTipoEvento(cols.maquina, efc.tipoEvento)}"
                              rendered="#{efcRowIndex!=0}">
                    <f:convertNumber locale="es" maxFractionDigits="2"/>
                </h:outputText>
                <p:tooltip for="otEficienciaCalc"
                           value="#{efc.tipoEvento.nombre}"/>
                <h:outputText value="%"/>
            </p:columns>
        </p:dataTable>
    </p:panel>
    <p:panel header="Gráfico de eficiencia" 
             rendered="#{eficienciaOperacionalBean.tipoEventoEficienciaList !=null and eficienciaOperacionalBean.tipoEventoEficienciaList.size()>0}">
        <p:scrollPanel>
            <p:chart type="bar" model="#{eficienciaOperacionalBean.barrasEficienciaModel}"
                     style="#{eficienciaOperacionalBean.chartStyle}"/>
        </p:scrollPanel>
    </p:panel>
</html>
```

..

## 6) Sample bean

```java
/*
 * Sistema de Informaci�n Crown CUTE
 * Propiedad de CROWN COLOMBIANA S.A.  * 
 * Desarrollado por SOLUCIONES INTEGRALES ESPECIALIZADAS EN SOFTWARE S.A.S - SIE SOFTWARE * 
 * 2016 - Todos los Derechos Reservados  * 
 */
package com.crowncolombiana.cute.web.bean.eficiencia;

import com.crowncolombiana.cute.negocio.entidades.Bitacoras;
import com.crowncolombiana.cute.negocio.entidades.BitacorasEventosMaquinas;
import com.crowncolombiana.cute.negocio.entidades.EstadosCrown;
import com.crowncolombiana.cute.negocio.entidades.Maquinas;
import com.crowncolombiana.cute.negocio.entidades.TipoEventos;
import com.crowncolombiana.cute.negocio.entidades.TipoMaquinas;
import com.crowncolombiana.cute.negocio.transacciones.BitacorasEventosMaquinasFacade;
import com.crowncolombiana.cute.negocio.transacciones.BitacorasFacade;
import com.crowncolombiana.cute.negocio.transacciones.EstadosCrownFacade;
import com.crowncolombiana.cute.negocio.transacciones.MaquinasFacade;
import com.crowncolombiana.cute.negocio.transacciones.TipoEventosFacade;
import com.crowncolombiana.cute.negocio.transacciones.TipoMaquinasFacade;
import com.crowncolombiana.cute.web.bean.CrownRootBean;
import com.crowncolombiana.cute.web.datamodel.MaquinaEficienciaDataModel;
import com.crowncolombiana.cute.web.datamodel.TipoEventoEficienciaDataModel;
import com.crowncolombiana.cute.web.datamodel.TipoMaquinasMaquinasDataModel;
import com.crowncolombiana.cute.web.enums.FiltroBlogEnum;
import com.crowncolombiana.cute.web.excepciones.CrownCuteWebException;
import com.crowncolombiana.cute.web.util.CalculadoraEficiencia;
import com.crowncolombiana.cute.web.util.FiltroBlogDTO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import javax.servlet.http.HttpSession;
import org.primefaces.model.chart.Axis;
import org.primefaces.model.chart.AxisType;
import org.primefaces.model.chart.BarChartModel;
import org.primefaces.model.chart.ChartSeries;
import org.primefaces.model.chart.LegendPlacement;

/**
 *
 * @author Sergio
 */
@Named(value = "eficienciaOperacionalBean")
@ViewScoped
public class EficienciaOperacionalBean extends CrownRootBean {

    //<editor-fold defaultstate="collapsed" desc="Declaración de variables">
    //<editor-fold defaultstate="collapsed" desc="EJB's">
    @EJB
    private BitacorasFacade bitacorasFacade;
    @EJB
    private BitacorasEventosMaquinasFacade bitacorasEventosMaquinasFacade;
    @EJB
    private EstadosCrownFacade estadosFacade;
    @EJB
    private MaquinasFacade maquinasFacade;
    @EJB
    private TipoMaquinasFacade tipoMaquinasFacade;
    @EJB
    private TipoEventosFacade tipoEventosFacade;

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Variables generales">    
    private Date fechaInicioConsulta;
    private Date fechaFinConsulta;
    private List<MaquinaEficienciaDataModel> maquinaEficienciaList;
    private List<TipoEventoEficienciaDataModel> tipoEventoEficienciaList;
    private BarChartModel barrasEficienciaModel;
    private List<TipoMaquinasMaquinasDataModel> tipoMaquinasMaquinasDataModel;
    private List<Bitacoras> bitacoras;
    private int numeroMaquinas;
    private int numeroConsultas;
    private String chartStyle;
    private HttpSession session;
    //</editor-fold>
    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="Inicialización">
    @PostConstruct
    @Override
    public void init() {
        session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(true);
        reiniciarCampos();
        alimentarModeloTipoDeMaquinasMaquinas();
        try {
            alimentarVolviendoDesdeBlog();
        } catch (CrownCuteWebException ex) {
            Logger.getLogger(EficienciaOperacionalBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void reiniciarCampos() {
        setFechaInicioConsulta(null);
        setFechaFinConsulta(null);
        setMaquinaEficienciaList(new ArrayList<MaquinaEficienciaDataModel>());
        setTipoEventoEficienciaList(new ArrayList<TipoEventoEficienciaDataModel>());
        setBarrasEficienciaModel(new BarChartModel());
        bitacoras = new ArrayList<>();
        setChartStyle("height: 600px; width: 1200px;");
        setNumeroConsultas(0);
    }

    public void alimentarModeloTipoDeMaquinasMaquinas() {
        tipoMaquinasMaquinasDataModel = new ArrayList<>();
        List<TipoMaquinas> tipoMaquinasList = tipoMaquinasFacade.encontrarTipoMaquinasOrdenadas();
        if (tipoMaquinasList != null && !tipoMaquinasList.isEmpty()) {
            for (TipoMaquinas tm : tipoMaquinasList) {
                List<Maquinas> maquinasList = maquinasFacade.buscarPorTiposMaquinas(tm.getTipoMaquinasId());
                if (maquinasList != null && !maquinasList.isEmpty()) {
                    TipoMaquinasMaquinasDataModel tmdm = new TipoMaquinasMaquinasDataModel();
                    tmdm.setTipoMaquina(tm);
                    tmdm.setCantidadPorTipo(maquinasList.size());
                    tipoMaquinasMaquinasDataModel.add(tmdm);
                }
            }
        }
    }

    public void alimentarVolviendoDesdeBlog() throws CrownCuteWebException {
        FiltroBlogDTO fbDto = (FiltroBlogDTO) session.getAttribute("filtroBlog");
        if (fbDto != null
                && fbDto.getFechaInicio() != null
                && fbDto.getFechaFin() != null) {
            setFechaInicioConsulta(fbDto.getFechaInicio());
            setFechaFinConsulta(fbDto.getFechaFin());
            setBarrasEficienciaModel(fbDto.getBarrasEficienciaModel());
            setNumeroConsultas(fbDto.getNumeroConsultas());
            consultarPorFechas(false);
        }
    }

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Acciones de componentes">
    public String menuConsultaAction() {
        session.setAttribute("filtroBlog", null);
        return "/reportes/eficiencia/consultarEficiencia?faces-redirect=true";
    }

    public void btConsultarPorFechasListener() {
        try {
            consultarPorFechas(true);
        } catch (CrownCuteWebException ex) {
            mostrarMensajeErrorManejado(ex.getLocalizedMessage());
        }
    }

    public String commandLinkFiltroBlogListener(Object filtro, FiltroBlogEnum tipoFiltro) {
        FiltroBlogDTO fbDto = new FiltroBlogDTO();
        fbDto.setFechaInicio(getFechaInicioConsulta());
        fbDto.setFechaFin(getFechaFinConsulta());
        fbDto.setFiltro(filtro);
        fbDto.setTipoFiltro(tipoFiltro);
        fbDto.setBarrasEficienciaModel(getBarrasEficienciaModel());
        fbDto.setNumeroConsultas(getNumeroConsultas());
        session.setAttribute("filtroBlog", fbDto);
        return "/reportes/blog/consultarBlog?faces-redirect=true";
    }

    public String commandLinkFiltroBlogListenerParaMaquina() {
        Map<String, String> params = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap();
        int maquinaId = Integer.valueOf(params.get("maquinaId"));
        Maquinas maq = (Maquinas) maquinasFacade.buscarPorId(Maquinas.class, maquinaId);
        return commandLinkFiltroBlogListener(maq, FiltroBlogEnum.FILTRO_MAQUINA);
    }

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Lógica">
    /**
     * Realiza la consulta por fechas y alimenta el reporte
     *
     * @param agregarSerie Flag que indica si se debe o no gagregar una nueva
     * serie al gráfico
     * @throws CrownCuteWebException
     */
    public void consultarPorFechas(boolean agregarSerie) throws CrownCuteWebException {
        setTipoEventoEficienciaList(new ArrayList<TipoEventoEficienciaDataModel>());
        setMaquinaEficienciaList(new ArrayList<MaquinaEficienciaDataModel>());
        List<EstadosCrown> estados = estadosFacade.buscarTodos(EstadosCrown.class);
        bitacoras = null;
        CalculadoraEficiencia.calcularNumeroDeDias(getFechaInicioConsulta(), getFechaFinConsulta());
        if (getFechaInicioConsulta() != null && getFechaFinConsulta() != null) {
            bitacoras = bitacorasFacade.encontrarPorRangoFechasYEstados(getFechaInicioConsulta(), getFechaFinConsulta(), estados);
        }
        if (bitacoras != null && !bitacoras.isEmpty()) {
            List<Maquinas> maquinasList = maquinasFacade.buscarMaquinasOrdenadasPorTipo();
            setNumeroMaquinas(maquinasList != null ? maquinasList.size() : 0);
            if (maquinasList != null && !maquinasList.isEmpty()) {
                for (Maquinas maquina : maquinasList) {
                    List<BitacorasEventosMaquinas> eventos = bitacorasEventosMaquinasFacade.encontrarPorVariasBitacorasYMaquina(bitacoras, maquina);
                    MaquinaEficienciaDataModel edm = new MaquinaEficienciaDataModel();
                    edm.setMaquina(maquina);
                    edm.setEventos(eventos);
                    calcularEficiencia(eventos, edm);
                    maquinaEficienciaList.add(edm);
                }
                TipoEventoEficienciaDataModel tipoEventoEficienciaGenerico = new TipoEventoEficienciaDataModel();
                TipoEventos tipoEventoGenerico = new TipoEventos();
                tipoEventoGenerico.setNombre(capturarValor("eficiencia_operacional"));
                tipoEventoEficienciaGenerico.setTipoEvento(tipoEventoGenerico);
                tipoEventoEficienciaGenerico.setMaquinaEficienciaList(maquinaEficienciaList);
                tipoEventoEficienciaList.add(tipoEventoEficienciaGenerico);
                List<TipoEventos> tipoEventosList = tipoEventosFacade.encontrarTipoEventos();
                if (tipoEventosList != null && !tipoEventosList.isEmpty()) {
                    for (TipoEventos tipoEvento : tipoEventosList) {
                        List<MaquinaEficienciaDataModel> maqEfDmTipoEvt = new ArrayList<>();
                        if (!maquinasList.isEmpty()) {
                            for (Maquinas maquina : maquinasList) {
                                List<BitacorasEventosMaquinas> eventos = bitacorasEventosMaquinasFacade.encontrarPorVariasBitacorasYMaquinaYTipoEvento(bitacoras, maquina, tipoEvento);
                                MaquinaEficienciaDataModel edm = new MaquinaEficienciaDataModel();
                                edm.setMaquina(maquina);
                                edm.setEventos(eventos);
                                maqEfDmTipoEvt.add(edm);
                            }
                        }
                        TipoEventoEficienciaDataModel tipoEventoEficiencia = new TipoEventoEficienciaDataModel();
                        tipoEventoEficiencia.setTipoEvento(tipoEvento);
                        tipoEventoEficiencia.setMaquinaEficienciaList(maqEfDmTipoEvt);
                        tipoEventoEficienciaList.add(tipoEventoEficiencia);
                    }
                }
            }
            numeroConsultas++;
            generarGrafico(agregarSerie);
        } else {
            throw new CrownCuteWebException(capturarValor("eficiencia_no_hay_eventos"));
        }
    }

    /**
     * Mediante este método se calcula la eficiencia de acuerdo al tipo de
     * evento y máquina, de esta manera se muestran en la DataTable
     *
     * @param maquina
     * @param tipoEvento
     * @return
     */
    public Double calculoEficienciaPorMaquinaYTipoEvento(Maquinas maquina, TipoEventos tipoEvento) {
        List<BitacorasEventosMaquinas> eventos = bitacorasEventosMaquinasFacade.encontrarPorVariasBitacorasYMaquinaYTipoEvento(bitacoras, maquina, tipoEvento);
        Double eficiencia = calcularEficiencia(eventos);
        return eficiencia;
    }

    /**
     * Realiza el cálculo de eficiencia para un
     * <code>MaquinaEficienciaDataModel</code>
     *
     * @param eventos El listado de eventos a partir de los cuales se calcula la
     * eficiencia
     * @param edm El <code>MaquinaEficienciaDataModel</code> para el cual se
     * calcula la eficiencia
     */
    public void calcularEficiencia(List<BitacorasEventosMaquinas> eventos, MaquinaEficienciaDataModel edm) {
        if (eventos != null && !eventos.isEmpty()) {
            double tiempoNeto = CalculadoraEficiencia.calcularNetTime(eventos);
            double tiempoOperacional = CalculadoraEficiencia.calcularOperationalTime(eventos);
            edm.setEficiencia(CalculadoraEficiencia.calcularEficienciaDeProduccionUOperacional(tiempoNeto, tiempoOperacional));
        } else if (eventos == null || eventos.isEmpty()) {
            edm.setEficiencia(100D);
        }
    }

    /**
     * Calcula la eficiencia para un grupo de eventos
     *
     * @param eventos El grupo de eventos para el cálculo de la eficiencia
     * @return La eficiencia calculada
     */
    public Double calcularEficiencia(List<BitacorasEventosMaquinas> eventos) {
        if (eventos != null && !eventos.isEmpty()) {
            double tiempoNeto = CalculadoraEficiencia.calcularNetTime(eventos);
            double tiempoOperacional = CalculadoraEficiencia.calcularOperationalTime(eventos);
            return CalculadoraEficiencia.calcularEficienciaDeProduccionUOperacional(tiempoNeto, tiempoOperacional);
        } else if (eventos == null || eventos.isEmpty()) {
            return 100D;
        }
        return 0D;
    }

    /**
     * Genera el gráfico de eficiencia
     *
     * @param agregarSerie Indica si se debe agregar la serie actual
     */
    public void generarGrafico(boolean agregarSerie) {
        if (agregarSerie) {
            ChartSeries serie = new ChartSeries();
            for (MaquinaEficienciaDataModel maquinaEficienciaDm : maquinaEficienciaList) {
                serie.setLabel(maquinaEficienciaDm.getMaquina().getNombre());
                serie.set(maquinaEficienciaDm.getMaquina().getNombre(), maquinaEficienciaDm.getEficiencia());
            }
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            serie.setLabel(sdf.format(getFechaInicioConsulta()) + " al " + sdf.format(getFechaFinConsulta()));
            barrasEficienciaModel.addSeries(serie);
        }
        barrasEficienciaModel.setLegendPosition("n");
        barrasEficienciaModel.setLegendPlacement(LegendPlacement.OUTSIDEGRID);
        Axis xAxis = barrasEficienciaModel.getAxis(AxisType.X);
        xAxis.setLabel(capturarValor("eficiencia_operacional_grafico_titulo_eje_x"));
        Axis yAxis = barrasEficienciaModel.getAxis(AxisType.Y);
        yAxis.setLabel(capturarValor("eficiencia_operacional_grafico_titulo_eje_y"));
        yAxis.setMin(0);
        yAxis.setMax(100);
        yAxis.setTickInterval("10");
        xAxis.setTickAngle(90);
        int chartWidth = getNumeroMaquinas() * 50 * numeroConsultas;
        setChartStyle("height: 600px; width: " + chartWidth + "px;");
    }

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Getter's y setter's">
    public Date getFechaInicioConsulta() {
        return fechaInicioConsulta;
    }

    public void setFechaInicioConsulta(Date fechaInicioConsulta) {
        this.fechaInicioConsulta = fechaInicioConsulta;
    }

    public String getChartStyle() {
        return chartStyle;
    }

    public void setChartStyle(String chartStyle) {
        this.chartStyle = chartStyle;
    }

    public int getNumeroMaquinas() {
        return numeroMaquinas;
    }

    public void setNumeroMaquinas(int numeroMaquinas) {
        this.numeroMaquinas = numeroMaquinas;
    }

    public List<TipoMaquinasMaquinasDataModel> getTipoMaquinasMaquinasDataModel() {
        return tipoMaquinasMaquinasDataModel;
    }

    public void setTipoMaquinasMaquinasDataModel(List<TipoMaquinasMaquinasDataModel> tipoMaquinasMaquinasDataModel) {
        this.tipoMaquinasMaquinasDataModel = tipoMaquinasMaquinasDataModel;
    }

    public BarChartModel getBarrasEficienciaModel() {
        return barrasEficienciaModel;
    }

    public void setBarrasEficienciaModel(BarChartModel barrasEficienciaModel) {
        this.barrasEficienciaModel = barrasEficienciaModel;
    }

    public List<MaquinaEficienciaDataModel> getMaquinaEficienciaList() {
        return maquinaEficienciaList;
    }

    public List<TipoEventoEficienciaDataModel> getTipoEventoEficienciaList() {
        return tipoEventoEficienciaList;
    }

    public void setTipoEventoEficienciaList(List<TipoEventoEficienciaDataModel> tipoEventoEficienciaList) {
        this.tipoEventoEficienciaList = tipoEventoEficienciaList;
    }

    public void setMaquinaEficienciaList(List<MaquinaEficienciaDataModel> maquinaEficienciaList) {
        this.maquinaEficienciaList = maquinaEficienciaList;
    }

    public int getNumeroConsultas() {
        return numeroConsultas;
    }

    public void setNumeroConsultas(int numeroConsultas) {
        this.numeroConsultas = numeroConsultas;
    }

    public Date getFechaFinConsulta() {
        return fechaFinConsulta;
    }

    public void setFechaFinConsulta(Date fechaFinConsulta) {
        this.fechaFinConsulta = fechaFinConsulta;
    }

    //</editor-fold>
}
```

..

**Comment by tandraschko** [comment] 2017-02-09 17:08
Please provide a small example, which is useable in the showcase. We don't have your DTO's and other dependencies.

**Comment by kukel** [comment] 2017-02-10 15:33
Yes, search google for MCVE and SSCCE

**Comment by jxmai** [comment] 2017-12-18 23:26
@tandraschko Suggest to close this issue as it is impossible to replicate and no update since months.

**Comment by fanste** [comment] 2021-03-22 16:52
We are currently observing the same problem in PF 8. Yet untested with PF 10.

It seems that a `p:commandLink` inside `p:columns` inside `p:columnGroup` is not working. Not working means, that the request is sent to the server but it doesn't seem to invoke the decode method of the `p:commandLink`.

I will investigate this tomorrow. Find a reproducer below.

```html
<h:form>
    <p:dataTable>
        <p:columnGroup type="header">
            <p:row>
                <p:columns value="#{tmpBean.columnList}">
                    <f:facet name="header">
                        <p:commandLink value="Klick!" process="@this" partialSubmit="true" actionListener="#{tmpBean.doAction}"/>
                    </f:facet>
                </p:columns>
            </p:row>
        </p:columnGroup>
    </p:dataTable>
</h:form>
```

```java
@Named
@ViewScoped
public class TmpBean implements Serializable {
       private static final long serialVersionUID = 1L;

       private List<Integer> columnList;

       @PostConstruct
       public void initialize() {
             columnList = new ArrayList<>();
             columnList.add(0);
       }
       
       public void doAction() {
             PrimeFaces.current().executeScript("alert('Worked!')");
       }

       public List<Integer> getColumnList() {
             return columnList;
       }
}

```

**Comment by melloware** [comment] 2021-03-23 11:23
Hmm it would be interesting if you could try it with a PF Test Reproducer and see if this is fixed in 10?

**Comment by fanste** [comment] 2021-03-23 13:09
Tested with PF 10 and the bug still exists. Narrowed it down to https://github.com/primefaces/primefaces/blob/d4ce8fccc8d72627c350847cad911428dcff732c/src/main/java/org/primefaces/component/api/UIData.java#L788-L796
which only checks for `Column` but not for `Columns`. I will try to implement a fix

**Comment by melloware** [comment] 2021-03-23 13:12
I reopened the ticket and assigned to you.  Thanks!

**Comment by fanste** [comment] 2021-03-23 13:30
PR #7159

**Closed as completed** 2021-03-23 13:36 UTC
Labels: :lady_beetle: defect
