### ISSUE TITLE
DataTable: Subtable appends column header text value

### ISSUE THREAD

**Issue by spauny** [primefaces/primefaces#1399] opened 2016-05-10 09:40 UTC
Hello, just upgraded to 6.0.RC3 (from 5.3) and using the same code, it seems the subTable uses the parent's column header text value and appends it to all the child values. 
Code: 

```
   <p:dataTable value="#{searchController.playerAcidReportRecordsGroupedByOperator}" var="entry" rows="100" 
                                         emptyMessage="No activity found" reflow="true"
                                         paginator="true" paginatorAlwaysVisible="false" scrollable="true" scrollWidth="100%" style="min-height: 150px" >
           <p:columnGroup type="header">
                    <p:row>
                          <p:columns var="group" value="#{searchController.columns}" width="200" headerText="#{group.title}" />
                     </p:row>
            </p:columnGroup>
            <p:subTable var="report" value="#{entry.value}" >
                      <f:facet name="header">
                             <h:outputText value="#{entry.key}" />
                      </f:facet>
                      <c:forEach items="#{searchController.columns}" var="column" >
                            <p:column >
                                <h:outputText value="#{report.record[column.name]}" />
                            </p:column>
                      </c:forEach>
           </p:subTable>
            <p:columnGroup type="footer">
                    <p:row>
                          <p:columns var="col" value="#{searchController.columns}" footerText="#{searchController.playerTotals[col.title]}" />
                    </p:row>
            </p:columnGroup>
   </p:dataTable>
```

You can view the actual behaviour below. As you can see, the column header (totalrecords) is appended with subtable header and outputText value.

![screen shot 2016-05-10 at 09 49 03](https://cloud.githubusercontent.com/assets/6390470/15140851/eab2cf6e-1694-11e6-83ea-9cdb8d7828ff.png)

**Comment by Rildlanster** [comment] 2016-11-01 13:50
Annoying bug persisting in Primefaces 6.0. Happens when you use reflow="true". I think subtables are not made to be responsive.

**Comment by melloware** [comment] 2020-06-14 11:59
Yes SubTables were not designed to be responsive.

**Comment by melloware** [comment] 2020-12-15 21:05
Duplicate of https://github.com/primefaces/primefaces/issues/1910 which has a workaround

**Closed as completed by melloware** 2020-12-15 21:05 UTC
Labels: Resolution: Duplicate, new feature
