### ISSUE TITLE
Exporter: Migration guide from PF 12 to 13

### ISSUE THREAD

**Issue by majkers** [primefaces/primefaces#11091] opened 2023-12-08 07:57 UTC
### Describe the bug

PrimeFaces migration guide to version 13 (https://primefaces.github.io/primefaces/13_0_0/#/../migrationguide/13_0_0) is totally missing any info about total code refactor made in https://github.com/primefaces/primefaces/issues/9969 for exporters. This is huge and made a lot of mess in my project.

### PrimeFaces edition

Community

### PrimeFaces version

13.0.3

### Theme

Saga

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

8

**Comment by jepsar** [comment] 2023-12-08 08:16
CC @Rapster

**Comment by melloware** [comment] 2023-12-08 12:43
@majkers interested in submitting a PR updating the migration guide since you just converted?

**Comment by majkers** [comment] 2023-12-10 15:02
Actually I don't think it is the best idea for me to make a change in docs since I am not an author of this refactor. More over I struggle to make my application to work with it for a few days, especially with this register function. BTW I also think it is not the nest solution to open document PDF in createDocument function when exporting dataTable to PDF using default exporter because one won't be able to for example add header and footer in preProcessor. IMHO it shuld be open in exportTable function

**Comment by melloware** [comment] 2023-12-10 15:20
I will let @Rapster respond since he made the changes.

**Comment by Rapster** [comment] 2023-12-10 17:11
Sorry to hear that, indeed docs would have nice, but there are so many changes that I'm not even sure where to start... In theory, TableExporter impl and the new method names should speak for itself but I understand your frustration...  

> More over I struggle to make my application work with it for a few days, especially with this register function. 

How? Please explain

> I also think it is not the best solution to open document PDF in createDocument function when exporting dataTable to PDF using default exporter because one won't be able to for example add header and footer in preProcessor. IMHO it shuld be open in exportTable function

Reproducer?

**Comment by majkers** [comment] 2023-12-11 07:44
Echhh  sorry @Rapster but I do not have time to prepare reproducer every time I have an error. 

About docs. A good place to start is to add a few wrods in migration guide that there was a huge refactor in Exporters so one would be prepared for some extra work.

About register function. You suggest to use _SystemEventListener_ or _ServletContextListener_. Both do not work for me for now. Eg. _ServletContextListener_ :

```
@WebListener
public class PostConstructApplicationEventListener implements ServletContextListener {

	private static final Logger logger = Logger
			.getLogger(PostConstructApplicationEventListener.class.getName());


	@Override
	public void contextDestroyed(ServletContextEvent event) {
	}

	@Override
	public void contextInitialized(ServletContextEvent event) {
		logger.info(
				"Registering PrimeFaces exporters");
		DataExporters.register(DataTable.class, PdfDataExporter.class, "pdf");
		DataExporters.register(DataTable.class, ExcelDataExporter.class, "xls");
		DataExporters.register(DataTable.class, ExcelDataExporter.class, "xlsx");
		DataExporters.register(DataTable.class, XmlDataExporter.class, "xml");
		DataExporters.register(DataTable.class, CsvDataExporter.class, "csv");
	}
}
```

gives NPE in:

![image](https://github.com/primefaces/primefaces/assets/21099773/331113c4-8fc8-4aef-859f-43f64a19a52a)

About openDocument:

when xhtml looks like this:
![image](https://github.com/primefaces/primefaces/assets/21099773/675d7303-15c7-457e-81e3-bb719938ac48)

and method like this:

![image](https://github.com/primefaces/primefaces/assets/21099773/cef9251b-e739-43ad-a0e6-9cf15f7e1c65)

Your PDF file wont have header and foooter on first page.

**Comment by melloware** [comment] 2023-12-11 12:24
> Echhh sorry @Rapster but I do not have time to prepare reproducer every time I have an error.

@majkers I have warned you before about statements like the above.  What you are saying is YOUR time is more important than OUR time.  @Rapster and most of us here are volunteers with **day jobs just like you**.... so please don't disrespect OUR time.

**Comment by majkers** [comment] 2023-12-11 12:29
Every time I submit an error I include screenshots with exact problem and most of the time exact solution how to fix it. By saying 'I don't have to time to prepare a reproducer' as an extra option for above is not a disrespect. You give your free time to fix issues and I give mine to debug sources and prepare screenshots etc. And by that I don't think that my time time is more important that yours. Please stop putting into my mounth words I don't mean.

**Comment by melloware** [comment] 2023-12-11 12:50
But what you said is EXACTLY what you mean "I do not have time to prepare reproducer every time I have an error" is it not?

**Comment by majkers** [comment] 2023-12-11 13:01
You want me to list you my issues with reporoducers? I just said that from time to time I don't have time to prepare reproducer BUT then I enclose screens, logs etc to help developer to fix it. And this is what I did this time.

**Comment by melloware** [comment] 2023-12-22 01:15
Closing. Will reopen if someone volunteers a PR but I upgraded 70 apps without issue so until someone can explain what needs to be documented not worth keeping open

**Comment by majkers** [comment] 2023-12-27 10:46
My app has more or less 800 forms and I did have some problems with it because I have some default exporters overridden. IMHO just a single sentence in migration guide "Exporters API chas changed" and another one with this new register function for custom exporters would be enough. You have to bear in mind that there are companies that have to prepare a budget for their clients before making a migration. And because of the size of an application sometimes they have to rely on something like migration guide. If someone like me sees this kind of sentence he would add some MD.

**Comment by melloware** [comment] 2023-12-27 13:06
Thanks @majkers i will add something today.

**Closed as completed** 2023-12-27 13:10 UTC
Labels: documentation
