### ISSUE TITLE
UIData: Huge memory consumption for facets containing UIInput

### ISSUE THREAD

**Issue by fanste** [primefaces/primefaces#7369] opened 2021-05-28 10:44 UTC
Primefaces: 8.0++

### Description of the bug

Recently our server (WF 10) crashed with OOM exception. The heapdump revelead over 90mio instances of `HashMap#Node` (consuming 4GB of heap space). Nearly 90% of those instances exists because of the state saving mechanism (50% of those nodes are filled with `SavedState` instances).

It looks like that the `facets` (like `filter`) are stored per row-index instead of only one time.

### Steps to reproduce

Reproducer: https://github.com/fanste/primefaces-test/tree/test-7369

1. Add a breakpoint to PF's UIData, line 481
2. Open the index page
3. Each time `setRowIndex` is called, UIData will save it's state, which also iterates over the facets of each column. At some point you will see, that the componentID will contain the rowIndex which makes no sense for some facets.

Effectively it will generate an entry in the hashmap for each column times each row. Imagine you have a datatable with 50 columns and 50000 rows - that was the problem in our case.

I know that it makes no sense to display that many data at once. Therefor we used a datatable with `pagination=true`. It seems that the user visitied each single page. Otherwise the map should not be flooded with `SavedState` instances of each single row.

**Comment by fanste** [comment] 2021-05-28 11:01
Additionally I recognized, that `setRowIndex` is used multiple times in e.g `DataTableRenderer#encodeRows`: line 1152,1157,1160,1164,1168; 1159,1167 (both because of isInSameGroup). I don't measured the performance overhead, but some of them could be removed. And maybe the others should be checked against the currently active `rowIndex` so it does not unnecessarily save and restore the same state. Or is there any reason why it is implemented this way?

**Comment by melloware** [comment] 2021-05-28 11:44
I can't answer the `setRowIndex` question maybe @mertsincan @Rapster @tandraschko can help here.

**Comment by Rapster** [comment] 2021-05-28 12:13
> it looks like that the facets (like filter) are stored per row-index instead of only one time.

Can you ellaborate? What makes you think that?

>  Therefor we used a datatable with pagination=true.

pagination won't change a thing. Ideally, you should use a lazy model for better perf

> (both because of isInSameGroup)

Shouldn't be called if you're not using grouping features

**Comment by fanste** [comment] 2021-05-28 12:37
> > it looks like that the facets (like filter) are stored per row-index instead of only one time.
> 
> Can you ellaborate? What makes you think that?

Because the state map contains the component IDs of the filter's UIInput multiple times - including the rowIndex:
`f:dt:idOfFilter` vs `f:dt:0:idOfFilter`, `f:dt:1:idOfFilter`, ...

`UIData#setRowIndex` > `#setRowIndexWithoutRowStatePreserved` > `#saveDescendantState` > iterates over children (here: column) and calls overloaded `#saveDescendantState` > iterates over facets of that column.

Because of `UIData#saveDescendantState`, the ID of each visited component is resetted. Therefore it also resets the ID of the facet components which than include the rowIndex in its `clientId`.

> > Therefor we used a datatable with pagination=true.
> 
> pagination won't change a thing. Ideally, you should use a lazy model for better perf

It should be better than using a non-paged table which always will render all rows. `lazy` is not possible due to some customer requirements...

> > (both because of isInSameGroup)
> 
> Shouldn't be called if you're not using grouping features

I've just listed all occurences in that method. Detailed example: 1157 calls `setRowIndex`. Maybe a header row is used, than `inSameGroup` in line 1159 will do it again. If `inSameGroup` is not used, 1164 calls `setRowIndex` again.
It has nothing todo with the main problem it was just an additional observation and could be moved to some new optimization issue.

**Comment by Rapster** [comment] 2021-05-28 13:39
Thank you for sharing those details.

> Because the state map contains the component IDs of the filter's UIInput multiple times - including the rowIndex:
f:dt:idOfFilter vs f:dt:0:idOfFilter, f:dt:1:idOfFilter, ...

You sure these indexes are not column indexes? If not, then yeah seems pretty odd

> It should be better than using a non-paged table which always will render all rows

True, after a closer look I didn't expect to work that way

@mertsincan @tandraschko should be better help

**Comment by fanste** [comment] 2021-05-28 14:04
> You sure these indexes are not column indexes? If not, then yeah seems pretty odd

I'm pretty sure, because:

1. The first call to `#setRowIndex` in `UIData` is without any `rowIndex` in the client ID, as no previous `rowIndex` was available.
2. Our heap dump showed numbers greater than 50000, and the table only has a maximum of 50 columns.
3. The number is always equals the previous `rowIndex`

**Comment by tandraschko** [comment] 2021-05-28 14:05
i also remember something weird regarding visiting rows, as on each row visit, each column header and facets/filters were visited. 
Cant find the issue currently.

**Comment by fanste** [comment] 2021-05-28 14:31
The question is, how to fix that behaviour. It is not totally wrong, as facets could be per-row. But most facets like header, footer, filter are not per-row.

Easiest solution would be to check the facet name and only process those "table related" facets for `(curently active**) rowIndex = -1` (or the other way arround: process "row related" facets for `rowIndex > -1`). But is this enough to always get the correct state for those facets? I think yes, as all other states are simply overhead and never used again.

** with "currently active" I mean the rowIndex, that `#getRowIndex` returns. Not the one that was given to `#setRowIndex`

**Comment by melloware** [comment] 2021-05-28 15:07
@tandraschko i believe it's issue #925

**Comment by melloware** [comment] 2021-06-01 19:58
Reproducer from #925: 
[pf-925.zip](https://github.com/primefaces/primefaces/files/6580305/pf-925.zip)

GET the page. Initial rendering yields the expected output: there is no current row in a header, but there is a column.

```
2015-11-30 20:36:50,816 INFO  [stdout] (default task-47) Valid state: row null, col a
2015-11-30 20:36:50,817 INFO  [stdout] (default task-47) Valid state: row null, col a
2015-11-30 20:36:50,817 INFO  [stdout] (default task-47) Valid state: row null, col a
2015-11-30 20:36:50,820 INFO  [stdout] (default task-47) Valid state: row null, col b
2015-11-30 20:36:50,820 INFO  [stdout] (default task-47) Valid state: row null, col b
2015-11-30 20:36:50,821 INFO  [stdout] (default task-47) Valid state: row null, col b
```

Now press the "submit" button. Observe the output:

```
2015-11-30 20:36:57,629 INFO  [stdout] (default task-54) Valid state: row null, col a
2015-11-30 20:36:57,629 INFO  [stdout] (default task-54) Valid state: row null, col a
2015-11-30 20:36:57,630 INFO  [stdout] (default task-54) Valid state: row null, col b
2015-11-30 20:36:57,630 INFO  [stdout] (default task-54) Valid state: row null, col b
2015-11-30 20:36:57,631 ERROR [stderr] (default task-54) Invalid state: row 1, col null
2015-11-30 20:36:57,632 ERROR [stderr] (default task-54) Invalid state: row 1, col null
2015-11-30 20:36:57,633 ERROR [stderr] (default task-54) Invalid state: row 2, col null
2015-11-30 20:36:57,633 ERROR [stderr] (default task-54) Invalid state: row 2, col null
2015-11-30 20:36:57,636 INFO  [stdout] (default task-54) Valid state: row null, col a
2015-11-30 20:36:57,637 INFO  [stdout] (default task-54) Valid state: row null, col b
2015-11-30 20:36:57,639 ERROR [stderr] (default task-54) Invalid state: row 1, col null
2015-11-30 20:36:57,640 ERROR [stderr] (default task-54) Invalid state: row 2, col null
2015-11-30 20:36:57,643 INFO  [stdout] (default task-54) Valid state: row null, col a
2015-11-30 20:36:57,643 INFO  [stdout] (default task-54) Valid state: row null, col a
2015-11-30 20:36:57,644 INFO  [stdout] (default task-54) Valid state: row null, col b
2015-11-30 20:36:57,645 INFO  [stdout] (default task-54) Valid state: row null, col b
2015-11-30 20:36:57,646 ERROR [stderr] (default task-54) Invalid state: row 1, col null
2015-11-30 20:36:57,646 ERROR [stderr] (default task-54) Invalid state: row 1, col null
2015-11-30 20:36:57,649 ERROR [stderr] (default task-54) Invalid state: row 2, col null
2015-11-30 20:36:57,649 ERROR [stderr] (default task-54) Invalid state: row 2, col null
```

**Comment by Rapster** [comment] 2023-03-23 13:36
I think this one should be easy to fix, we should exclude facets from saving/restoring descendant state (that's what JSF impls do also) but we need to know what commit 509184c0f355eb2ddd36727c07f92884536a97e3 fixes

**Comment by fanste** [comment] 2023-03-24 11:18
I digged around in the old Googlecode primefaces repo. But either are those old issues really bad documented or Googlecode limited the access to some features after their move to "archive"... Maybe it was a fix without a reported issue. Then I think we will not be lucky to find out.

**Comment by melloware** [comment] 2023-03-24 11:57
Maybe its worth doing since this is a huge memory hog?  That bug was 10 years ago and it may not even be relevant anymore?

**Comment by jepsar** [comment] 2023-04-12 12:01
IMO this should be pushed to elite, as it can crash your application.

**Comment by tandraschko** [comment] 2023-05-02 09:43
This commit broke a simple case, where you asign a null value to a selectOneMenu
I have a running IT

Will check it now in detail

**Comment by tandraschko** [comment] 2023-05-02 09:50
@jepsar please review

**Comment by jepsar** [comment] 2023-05-02 09:58
I'll pull the changes and give a look

**Comment by tandraschko** [comment] 2023-05-02 12:15
Weird but ok, thats a mojarra issue

**Comment by jepsar** [comment] 2023-05-02 12:26
@tandraschko do you want to keep this open?

**Comment by tandraschko** [comment] 2023-05-02 12:33
if you are ok with my changes, we can close it.

**Closed as completed** 2023-05-02 12:34 UTC
Labels: :lady_beetle: defect, :zap: performance

**Comment by tandraschko** [comment] 2023-05-03 13:25
@jepsar did you check mem usage again with this?
we could introduce a second static instance, one with localValueSet=true, the other with false

**Comment by jepsar** [comment] 2023-05-03 13:46
We've got this patch in production since yesterday. So we don't have much data so far. It is profiled though.

**Comment by Rapster** [comment] 2023-07-09 19:15
Should be simply backport what BalusC is saying here: https://github.com/eclipse-ee4j/mojarra/issues/5229#issuecomment-1616684697 ?

**Comment by melloware** [comment] 2023-07-09 19:33
That was my impression from balusC that we needed to port the mojarra fix. But it wasn't clear

**Comment by Rapster** [comment] 2023-07-09 21:26
@jepsar wanna have a look?

**Comment by jepsar** [comment] 2023-07-10 07:31
Their fix is similar. We could backport the entire class to have it more up to date, but I would do that in 14.

**Comment by melloware** [comment] 2023-07-10 11:26
I opened: https://github.com/primefaces/primefaces/issues/10328 and set it for 14.0.0

**Comment by jepsar** [comment] 2024-01-11 14:51
Just a note to mention that we had no OOM exceptions since this fix. 🔥
