### ISSUE TITLE
AutoComplete: Footer

### ISSUE THREAD

**Issue by anuragnz** [primefaces/primefaces#7213] opened 2021-04-09 09:04 UTC
Can we have a Footer in AutoComplete component.

Use case:
Suppose we display a list of Items in AutoComplete and now we like to add a new Item. 
It will be very useful to add a Command link("Add item") in footer so we can display a dialog and display form etc.

**Comment by melloware** [comment] 2021-04-09 11:12
This sort of already exists...

https://github.com/primefaces/primefaces/issues/5905

**Comment by melloware** [comment] 2021-04-10 11:57
Duplicate of #5905

**Comment by jepsar** [comment] 2021-04-20 12:55
The issue with #5905 is that the option is only shown when there are more items than the ones displayed. If you want to add items it should be always visible when the options are shown. I'll have a look at adding such a feature.

**Comment by anuragnz** [comment] 2021-04-20 20:42
Yes this will be really useful.

**Comment by jepsar** [comment] 2021-04-25 08:38
Any suggestions for the facet name? Currently there is a `header` facet, which is used as the (table) header of custom content. I was thinking of renaming that to `tableHeader` (breaking change) and simply call the new facet `footer`. Or should I leave the `header` facet untouched and go for `suggestionsFooter`? Or simply `header` and `footer`? WDYT?

See also:
https://github.com/primefaces/primefaces/blob/439e3d3b40757bf4983c94a8d792c1dff593896a/src/main/java/org/primefaces/component/selectonemenu/SelectOneMenuRenderer.java#L369-L380

**Comment by melloware** [comment] 2021-04-25 14:22
My vote is `header` and `footer` since they are commons names used throughout many components.

**Comment by anuragnz** [comment] 2021-04-25 17:21
Yes footer facet would make more sense. @jepsar

**Comment by jepsar** [comment] 2021-04-25 17:47
Okay, `footer` it is. However, I find it somewhat confusing as the facet will not be used to render the custom content table footer, while the `header` facet is used to render the custom content table header.

**Comment by melloware** [comment] 2021-04-25 17:58
Hmmm now I am thinking panelFooter.

**Comment by jepsar** [comment] 2021-04-26 17:40
@melloware @tandraschko  Sorry.. the `header` facet is a facet of `p:column`, not of `p:autoComplete`, so `footer` it will be.

https://github.com/primefaces/primefaces/blob/4c4568fb960aa7a3018616d927a8a2218c834a54/src/main/java/org/primefaces/component/autocomplete/AutoCompleteRenderer.java#L509

Updated PR

**Closed as completed** 2021-04-27 07:48 UTC
Labels: enhancement

**Comment by jepsar** [comment] 2021-04-28 07:51
https://github.com/primefaces/primefaces-showcase/pull/354 is still open

**Comment by melloware** [comment] 2021-04-28 11:29
I just merged it. Thanks for the reminder.
