### ISSUE TITLE
TextEditor: nested lists

### ISSUE THREAD

**Issue by fcorneli** [primefaces/primefaces#6693] opened 2020-12-20 16:24 UTC
This issue can be easily demonstrated via the showcase:
https://www.primefaces.org/showcase/ui/input/textEditor.xhtml

When trying to create a list within a list. For example:

- item 1
  - item 1,1
  - item 1,2
- item 2

The HTML value always returns a "flat" list, like:
- item 1
- item 1,1
- item 1,2
- item 2

Affected PrimeFaces versions: 7, 8

**Comment by melloware** [comment] 2020-12-20 16:38
@fcorneli here is the HTML generated:
```html
<ul>
   <li>Item1</li>
   <li class="ql-indent-1">Item2</li>
</ul>
```

Duplicate of: https://github.com/primefaces/primefaces/issues/4486

To fix you need to add this to your page:
```xml
<link href="https://cdn.quilljs.com/1.3.7/quill.snow.css" rel="stylesheet">
```

**Closed as completed by melloware** 2020-12-20 16:38 UTC
Labels: Resolution: Duplicate, Resolution:  Wontfix, workaround

**Comment by fcorneli** [comment] 2020-12-20 16:59
@melloware Thanks for the tip. Adding:
```java
@ResourceDependencies(value = {
    @ResourceDependency(library = "css", name = "quill.snow.css")
})
```
and `class=\"ql-editor\"` to my JSF component fixed the issue.

**Comment by melloware** [comment] 2020-12-20 17:01
Nice work!  Glad I could help and thanks for posting your solution back.

**Comment by fcorneli** [comment] 2020-12-20 17:11
Using
```java
@ResourceDependencies(value = {
    @ResourceDependency(library = "primefaces", name = "texteditor/texteditor.css")
})
```
is actually much cleaner I guess.
