### ISSUE TITLE
Jakarta EE 9 version of PrimeFaces

### ISSUE THREAD

**Issue by arjantijms** [primefaces/primefaces#6580] opened 2020-11-30 17:10 UTC
With the Jakarta EE 9 APIs recently released, and the GlassFish 6.0.0 release imminent, it would be nice to have a Jakarta EE 9 version of PrimeFaces.

**Comment by melloware** [comment] 2020-11-30 17:12
@arjantijms we have a primefaces-9.0-jakarta.jar ready to go whenever PrimeTek releases 9.0 Community it will be released.

**Comment by arjantijms** [comment] 2020-11-30 17:19
@melloware, thanks, sounds good! 

ps. I'm about to release a Jakarta EE 9 demo app with PF. In the meantime I'll use the transformer (https://github.com/eclipse/transformer) on an old version of PF then. As soon as PrimeFaces 9 is there it can switch over.

**Comment by melloware** [comment] 2020-11-30 17:21
You can always grab master SNAPSHOT and run "mvn clean install" it builds the JAKARTA version as well.

**Comment by melloware** [comment] 2020-11-30 17:27
@tandraschko Should we switch to use this Eclipse Transformer plugin vs the io.yupiik.maven we are using?

**Comment by GedMarc** [comment] 2020-11-30 18:05
this is the full list - 

```
	<relocation>
		<pattern>javax.faces</pattern>
		<shadedPattern>jakarta.faces</shadedPattern>
	</relocation>
	
	<relocation>
		<pattern>javax.el</pattern>
		<shadedPattern>jakarta.el</shadedPattern>
	</relocation>
	
	<relocation>
		<pattern>javax.annotation</pattern>
		<shadedPattern>jakarta.annotation</shadedPattern>
	</relocation>
	
	<relocation>
		<pattern>javax.servlet</pattern>
		<shadedPattern>jakarta.servlet</shadedPattern>
	</relocation>
	
	<relocation>
		<pattern>javax.persistence</pattern>
		<shadedPattern>jakarta.persistence</shadedPattern>
	</relocation>
	
	<relocation>
		<pattern>javax.enterprise</pattern>
		<shadedPattern>jakarta.enterprise</shadedPattern>
	</relocation>
	
	<relocation>
		<pattern>javax.xml.bind</pattern>
		<shadedPattern>jakarta.xml.bind</shadedPattern>
	</relocation>
	
	<relocation>
		<pattern>javax.validation</pattern>
		<shadedPattern>jakarta.validation</shadedPattern>
	</relocation>
	
	<relocation>
		<pattern>javax.inject</pattern>
		<shadedPattern>jakarta.inject</shadedPattern>
	</relocation>
	
	<relocation>
		<pattern>javax.activation</pattern>
		<shadedPattern>jakarta.activation</shadedPattern>
	</relocation>
			
	<relocation>
		<pattern>javax.ws.rs</pattern>
		<shadedPattern>jakarta.ws.rs</shadedPattern>
	</relocation>	
	
	<relocation>
		<pattern>javax.jws</pattern>
		<shadedPattern>jakarta.jws</shadedPattern>
	</relocation>

	<relocation>
		<pattern>javax.cache</pattern>
		<shadedPattern>jakarta.cache</shadedPattern>
	</relocation>
	
	<relocation>
		<pattern>javax.xml.ws</pattern>
		<shadedPattern>jakarta.xml.ws</shadedPattern>
	</relocation>
	
	<relocation>
		<pattern>javax.xml.soap</pattern>
		<shadedPattern>jakarta.xml.soap</shadedPattern>
	</relocation>
	
```

**Comment by melloware** [comment] 2020-11-30 18:12
@GedMarc I am working on a PR. However in the MANIFEST.MF for OSGI these packages are still not being converted even with your latest list.
```
javax.imageio
javax.xml.namespace,
javax.xml.parsers,
javax.xml.transform,
javax.xml.transform.dom,
javax.xml.transform.stream,
javax.xml.xpath
```

any thoughts?

**Comment by melloware** [comment] 2020-11-30 18:24
@GedMarc nevermind I found it! 

https://github.com/eclipse-ee4j/jakartaee-platform/blob/master/namespace/unaffected-packages.adoc

Those are not being converted to Jakarta.

**Comment by tandraschko** [comment] 2020-11-30 19:23
Duplicate of https://github.com/primefaces/primefaces/issues/5646

the current way is fine - maven shade plugin replaces usages in java code and the yupiik addon is to enable shade plugin to replace simple strings in e.g. our core.js

**Closed as completed by tandraschko** 2020-11-30 19:23 UTC
Labels: new feature

**Comment by tandraschko** [comment] 2020-11-30 20:50
@melloware does jitpack support classifiers? so @arjantijms could use a jitpack snapshot

**Comment by melloware** [comment] 2020-11-30 20:52
Let me test it right now and see if it works.

**Comment by melloware** [comment] 2020-11-30 21:06
Yep this works!
```xml
<dependency>
    <groupId>com.github.primefaces</groupId>
    <artifactId>primefaces</artifactId>
    <version>master-SNAPSHOT</version>
    <classifier>jakarta</classifier>
</dependency>
```

**Comment by arjantijms** [comment] 2020-12-01 20:27
@melloware @tandraschko Thanks a lot! I'm going to try that one. Always bet on prime ;)

**Comment by melloware** [comment] 2020-12-01 20:32
@arjantijms Just don't forget to at Jitpack to your repos.  It will take a minute to pull down as it builds the latest MASTER snapshot.
```xml 
<repositories>
 	<repository>
 	    <id>jitpack.io</id>
 	    <url>https://jitpack.io</url>
 	</repository>
 </repositories>
```

**Comment by asterisk360-admin** [comment] 2020-12-22 03:06
@melloware @tandraschko...  when the premium themes will be compatible with jakarta 9?

**Comment by tandraschko** [comment] 2020-12-22 12:05
thats up to PrimTek, not us. Better usk in the your premium layout forum per mail.

Nevertheless, 9.0 isnt released yet so Layouts cant switch. And then, normally you can just replace the imports in the layout classes.
