### ISSUE TITLE
Calendar: validation failing if mask="99/99/9999" and pattern="dd/MM/yyyy"

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [primefaces/primefaces#6162] opened 2020-07-19 01:31 UTC
**Describe the defect**
with PrimeFaces 8  the following code works, but in master I get validation errors.
```
	<h:form>
	   <p:messages id="messages" showDetail="true" closable="true">
              <p:autoUpdate />
           </p:messages>
	   <p:calendar mask="99/99/9999" pattern="dd/MM/yyyy" />
	   <p:commandButton></p:commandButton>
	</h:form>
```

edit:
test repository: 
https://github.com/erickdeoliveiraleal/primefaces-test/tree/calendar

**Comment by melloware** [comment] 2020-07-19 12:19
I tried this and it works fine:
```xml
 <p:calendar id="mask" value="#{calendarJava8View.date9}" pattern="dd/MM/yyyy" mask="99/99/9999"  />
```
However if you don't list a pattern...
```xml
 <p:calendar id="mask" value="#{calendarJava8View.date9}" mask="99/99/9999"  />
```
It looks like
![image](https://user-images.githubusercontent.com/4399574/87874504-5ebedc80-c998-11ea-836c-49c9849e9100.png)

This is because of this issue: https://forum.primefaces.org/viewtopic.php?f=3&t=62741

However if would have worked had you said `mask=true`
```xml
 <p:calendar id="mask" value="#{calendarJava8View.date9}" mask="true"  />
```

As that detects the Date Pattern and creates a mask accordingly.

**Comment by melloware** [comment] 2020-07-19 12:35
OK so the code is doing this is pattern is NULL:
```java
if (pattern == null) {
            Locale locale = calculateLocale(getFacesContext());
            return DateTimeFormatterBuilder.getLocalizedDateTimePattern(FormatStyle.SHORT, null, IsoChronology.INSTANCE, locale);
        }
```

its picking the SHORT format for your locale which is dd/mm/yy 2 digit year.   However looking at the JavaDoc for FormatStyle https://docs.oracle.com/javase/8/docs/api/java/time/format/FormatStyle.html the MEDIUM, LONG, and FULL locale defaults do not give us what we want.

@christophs78 looking for some guidance here on a better possible way we could default the date format using local to be a 4 digit year instead of 2 digit?

**Comment by erickdeoliveiraleal** [comment] 2020-07-19 12:37
sorry  for not sending a repository test. it's here: https://github.com/erickdeoliveiraleal/primefaces-test/tree/calendar
if I set pattern the issue persists

**Comment by erickdeoliveiraleal** [comment] 2020-07-19 12:44
@melloware now I setted pattern but the validation is failing again.

**Comment by melloware** [comment] 2020-07-19 13:11
When I run your sample with 9.0-SNAPSHOT and the following it works fine for me?
```xml
<h:form>
    <p:messages id="messages" showDetail="true" closable="true">
        <p:autoUpdate />
    </p:messages>
    <p:calendar mask="99/99/9999" pattern="MM/dd/yyyy" />
    <br/>
    <p:calendar mask="true" pattern="MM/dd/yyyy" />
    <br/>
    <p:commandButton></p:commandButton>
    <br/>
</h:form>
```

Attached is reproducer: 
[pf-6162.zip](https://github.com/primefaces/primefaces/files/4943743/pf-6162.zip)

**Comment by erickdeoliveiraleal** [comment] 2020-07-19 13:55
your example is also failing here, latest master + mojarra 2.2 
![Capturar](https://user-images.githubusercontent.com/3578953/87876393-4c4f9d80-c9ae-11ea-8865-ef2d1e3b40e7.PNG)

**Comment by melloware** [comment] 2020-07-19 13:57
Ahhh I thought you were saying the mask isn't working. Its the validation that's failing.  Let me look.

**Comment by melloware** [comment] 2020-07-19 13:59
OK committed a fix.

**Closed as completed** 2020-07-19 13:59 UTC
Labels: :lady_beetle: defect

**Comment by christophs78** [comment] 2020-07-19 14:07
Just to understand how we introduced this issue. Was it because of the new/updated InputMask-JS?

**Comment by melloware** [comment] 2020-07-19 14:09
Yes the new inputMask has a ton of features the old one did not.  One of them was unmasking the value automatically but for Calendar we don't want it unmasked "10102020" we want to leave it masked "10/10/2020".

**Comment by melloware** [comment] 2020-07-19 14:14
But @christophs78 we still have another looming issue asked in this forum post: https://forum.primefaces.org/viewtopic.php?f=3&t=62741

**Comment by christophs78** [comment] 2020-07-19 14:46
The min-max-issue seems to be related to Java8-DateTimeFormatter.

`BaseCalendarRenderer#convertToJava8DateTimeAPI`
![grafik](https://user-images.githubusercontent.com/10461942/87877505-03640d00-c9df-11ea-90fb-94a356ff6f04.png)

We have to add this to the issue as soon as we have one.
We have to dig into https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html.

But at least this should be something we are able to Unittest. :-)
