### ISSUE TITLE
 Datatable: Lazy Sorting doesn't work when STATE_SAVING_METHOD=client (PF 10.0.0)

### ISSUE THREAD

**Issue by AndrewG10i** [primefaces/primefaces#7160] opened 2021-03-23 14:17 UTC
**Describe the defect**
After switching from PF 8.0.7 to PF 10.0.0 noticed that sorting doesn't work at all (method `load(int first, int pageSize, Map<String, SortMeta> sortMap, Map<String, FilterMeta> filters)` always receives empty sortMap).

It turned out that by changing STATE_SAVING_METHOD from client to server - resolves the issue, and sorting start working properly on the datatable with lazy DS.

**Reproducer**
No particular reproducer provided as of now expecting that it should be easily reproducible on any JSF app by switching `STATE_SAVING_METHOD` to `client`:
```lang-xml
<context-param>
    <param-name>javax.faces.STATE_SAVING_METHOD</param-name>
    <param-value>client</param-value>
</context-param>
```

**Environment:**
 - PF Version: 10.0.0
 - JSF version: Mojarra 2.3.14.payara-p2 (on Payara Server 5.2021.1)

**To Reproduce**
1. In web.xml replace STATE_SAVING_METHOD param from server to client
2. Launch & deploy app
3. Click on databale column header with enabled sorting - no sorting will occurre

**Comment by melloware** [comment] 2021-03-23 14:19
Duplicate of https://github.com/primefaces/primefaces/issues/6987

**Closed as completed by melloware** 2021-03-23 14:19 UTC
Labels: :lady_beetle: defect, Resolution: Duplicate
