### ISSUE TITLE
Filter in Tree Table

### ISSUE THREAD

**Issue by SantoshCCS** [primefaces/primefaces#1377] opened 2016-05-03 08:14 UTC
Filter in Tree Table

**Comment by kukel** [comment] 2016-05-03 15:03
Please add a little more text... This is quite short (although I think I agree with the requirement). Maybe we should create some crowdfunding for this issue

**Comment by melloware** [comment] 2017-04-08 12:24
Duplicate of #1929

**Closed as completed** 2017-04-08 16:08 UTC
Labels: Resolution: Duplicate
