### ISSUE TITLE
multiple datatables with dynamic columns in a page

### ISSUE THREAD

**Issue by xodarapus** [primefaces/primefaces#215] opened 2015-05-01 14:28 UTC
When i render multiple datatables with dynamic columns, after the first datatable, others cannot refresh datatable columns and uses the first ones. 

I found it in org.primefaces.component.datatable.DataTableRenderer.java and patched it. Hope you fix it in later relases. it s on line 789 encodeTbody method. 

```
public void encodeTbody(FacesContext context, DataTable table, boolean dataOnly) throws IOException {
    this.encodeTbody(context, table, dataOnly, 0, table.getColumns().size(), null);
    // TODO : patched here 
    table.setColumns(null);
}
```

if columns are not set to null, it never refreshes for further datatables with dynamic columns in the same view

**Comment by cagataycivici** [comment] 2015-05-02 07:58
Duplicate of #88

**Closed as completed** 2015-05-02 07:58 UTC
