### ISSUE TITLE
JSF1064: Unable to find or serve resource on WildFly

### ISSUE THREAD

**Issue by jsocola** [primefaces/primefaces#6091] opened 2020-06-29 21:28 UTC
**Describe the defect**
When we call in localhost work fine, but when we publish on public with SSL on WildFly20 with jsf-impl-2.3.9.SP10 have problems.
**Environment:**
 - PF Version: _8.0_2
 - JSF + version: _e.g. Mojarra 2.3.9
 - Wildfly 20+
 - Affected browsers: _e.g. Chrome, iOS, ALL_

**To Reproduce**
1. Go to call webpage
2. See error on console

**Expected behavior**
2020-06-29 17:39:13,800 ERROR [io.undertow.request.io] (default I/O-3) UT005090: Unexpected failure: java.lang.NullPointerException
	at io.undertow.server.protocol.framed.AbstractFramedChannel.markReadsBroken(AbstractFramedChannel.java:850)
	at io.undertow.server.protocol.framed.AbstractFramedChannel.receive(AbstractFramedChannel.java:485)
	at io.undertow.server.protocol.http2.Http2ReceiveListener.handleEvent(Http2ReceiveListener.java:107)
	at io.undertow.server.protocol.http2.Http2ReceiveListener.handleEvent(Http2ReceiveListener.java:66)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:952)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:932)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1211)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)

020-06-29 17:39:13,826 WARNING [javax.enterprise.resource.webcontainer.jsf.application] (default task-7) JSF1064: Unable to find or serve resource, components.js, from library, primefaces.
2020-06-29 17:39:13,826 WARNING [javax.enterprise.resource.webcontainer.jsf.application] (default task-7) : java.nio.channels.ClosedChannelException
	at io.undertow.channels.DetachableStreamSinkChannel.write(DetachableStreamSinkChannel.java:238)
	at io.undertow.server.HttpServerExchange$WriteDispatchChannel.write(HttpServerExchange.java:2111)
	at io.undertow.servlet.spec.ServletOutputStreamImpl.writeBufferBlocking(ServletOutputStreamImpl.java:575)
	at io.undertow.servlet.spec.ServletOutputStreamImpl.write(ServletOutputStreamImpl.java:151)
	at java.nio.channels.Channels$WritableByteChannelImpl.write(Channels.java:458)
	at com.sun.faces.application.resource.ResourceHandlerImpl.handleResourceRequest(ResourceHandlerImpl.java:318)
	at javax.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:171)
	at org.primefaces.application.resource.PrimeResourceHandler.handleResourceRequest(PrimeResourceHandler.java:89)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:704)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at com.soco.web.common.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:15)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:52)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:370)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1348)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Julian-B90** [comment] 2020-11-04 12:08
@jsocola do you have solve this problem?

**Comment by jsocola** [comment] 2022-04-16 07:18
the problem still in version wildfly 20,21,22. If we put http2 false works but I think resources location is the problem 

 <http-listener name="default" socket-binding="http" redirect-socket="https" enable-http2="true"/>
 <https-listener name="https" socket-binding="https" security-realm="ApplicationRealm" enable-http2="true"/>

 <http-listener name="default" socket-binding="http" redirect-socket="https" enable-http2="false"/>
<https-listener name="https" socket-binding="https" security-realm="ApplicationRealm" enable-http2="false"/>

**Comment by tandraschko** [comment] 2022-04-16 07:32
If you can provide a reproducer with primefaces-test, WE can Check
But im sure its a mojarra or wildfly thing

**Comment by melloware** [comment] 2022-04-16 11:43
From this forum post: https://forum.primefaces.org/viewtopic.php?t=55581&start=10

It looks like its HTTP2 and Mojarra related as Payara has the same issue with HTTP2.

here was the original issue: https://github.com/eclipse-ee4j/mojarra/issues/4280

BalusC recommends creating this patch:
```java
import java.net.MalformedURLException;

import javax.faces.FacesException;
import javax.faces.application.Resource;
import javax.faces.application.ResourceHandler;

import org.omnifaces.resourcehandler.DefaultResourceHandler;
import org.omnifaces.util.Faces;

/**
 * Patches Mojarra bug of unnecessarily logging as below when it's about to locate a tagfile.
 * "WARNING JSF1064: Unable to find or serve resource from library, kickoff/composites"
 */
public class ResourceHandlerImplPatch extends DefaultResourceHandler {

	public ResourceHandlerImplPatch(ResourceHandler wrapped) {
		super(wrapped);
	}

	@Override
	public String getLibraryName() {
		return "primefaces";  // or "primefaces-<theme>" if needed
	}

	@Override
	public Resource createResourceFromLibrary(String resourceName, String contentType) {
		try {
			if (Faces.getResource("/" + getLibraryName() + "/" + resourceName) != null) {
				return getWrapped().createResource(resourceName, getLibraryName(), contentType);
			}
			else {
				return null; // So ResourceHandlerImpl with its unnecessary logging will be skipped.
			}
		}
		catch (MalformedURLException e) {
			throw new FacesException(e);
		}
	}
}
```

And adding it to `faces-config.xml` 

```xml
<application>
   <resource-handler>org.example.kickoff.view.resourcehandler.ResourceHandlerImplPatch</resource-handler>
</application>
```

This basically suppresses that stack trace.

**Comment by melloware** [comment] 2022-04-16 11:45
I have marked this as "workaround" and "implementation-specific" as its a Mojarra issue and closing it.  @jsocola let us know if this resolves your issue.

**Closed as completed** 2022-04-16 11:46 UTC
Labels: implementation-specific

**Comment by jsocola** [comment] 2022-04-16 19:57
I use primefaces 8.0.16 with mojarra 2.3.14.SP02 no omnifaces and I have created a class ResourceHandlerImplPatch to fix resources url.

The initial page now load with https 2 but when try to navigate it's like entry into infinity loop and server go crazy  with messages in log only said WARNING...

import javax.faces.application.Resource;
import javax.faces.application.ResourceHandler;
import javax.faces.application.ResourceHandlerWrapper;
import javax.faces.context.FacesContext;
public class ResourceHandlerImplPatch extends ResourceHandlerWrapper
{
	private final ResourceHandler wrapped;
	public ResourceHandlerImplPatch(final ResourceHandler wrapped)
	{
		this.wrapped = wrapped;
	}
	@Override
	public ResourceHandler getWrapped()
	{
		return wrapped;
	}
	@Override
	public Resource createResource(final String resourceName, final String libraryName)
	{
		return super.createResource(resourceName, libraryName);
	}
	/**
	 * @see javax.faces.application.ResourceHandlerWrapper#libraryExists(java.lang.String)
	 */
	@Override
	public boolean libraryExists(final String libraryName)
	{
		return super.libraryExists(libraryName);
	}
	/**
	 * @see javax.faces.application.ResourceHandlerWrapper#isResourceRequest(javax.faces.context.FacesContext)
	 */
	@Override
	public boolean isResourceRequest(final FacesContext context)
	{
		return super.isResourceRequest(context);
	}
}
faces-config.xml

<application>
<resource-handler>ResourceHandlerImplPatch</resource-handler>
</application>

Just said the warning
 (default task-36) /mycontext/javax.faces.resource/components.css.xhtml?ln=primefaces
 [javax.enterprise.resource.webcontainer.jsf.application] (default task-55) JSF1064: Unable to find or serve resource, components.css, from library, primefaces.
14:53:40,904 WARNING [javax.enterprise.resource.webcontainer.jsf.application] (default task-55) : java.nio.channels.ClosedChannelException
	at io.undertow.core@2.2.4.Final//io.undertow.server.protocol.framed.AbstractFramedStreamSinkChannel.safeToSend(AbstractFramedStreamSinkChannel.java:457)
	at io.undertow.core@2.2.4.Final//io.undertow.server.protocol.framed.AbstractFramedStreamSinkChannel.write(AbstractFramedStreamSinkChannel.java:411)
	at io.undertow.core@2.2.4.Final//io.undertow.protocols.http2.Http2DataStreamSinkChannel.write(Http2DataStreamSinkChannel.java:312)
	at org.jboss.xnio@3.8.4.Final//org.xnio.conduits.StreamSinkChannelWrappingConduit.write(StreamSinkChannelWrappingConduit.java:57)
	at org.jboss.xnio@3.8.4.Final//org.xnio.conduits.ConduitStreamSinkChannel.write(ConduitStreamSinkChannel.java:150)
	at io.undertow.core@2.2.4.Final//io.undertow.channels.DetachableStreamSinkChannel.write(DetachableStreamSinkChannel.java:240)
	at io.undertow.core@2.2.4.Final//io.undertow.server.HttpServerExchange$WriteDispatchChannel.write(HttpServerExchange.java:2181)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.spec.ServletOutputStreamImpl.writeBufferBlocking(ServletOutputStreamImpl.java:575)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.spec.ServletOutputStreamImpl.write(ServletOutputStreamImpl.java:151)
	at java.base/java.nio.channels.Channels$WritableByteChannelImpl.write(Channels.java:464)
	at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.application.resource.ResourceHandlerImpl.handleResourceRequest(ResourceHandlerImpl.java:318)
	at javax.faces.api@3.0.0.SP04//javax.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:171)
	at deployment.soco-web.war//org.primefaces.application.resource.PrimeResourceHandler.handleResourceRequest(PrimeResourceHandler.java:89)
	at javax.faces.api@3.0.0.SP04//javax.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:171)
	at javax.faces.api@3.0.0.SP04//javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:704)
	at javax.faces.api@3.0.0.SP04//javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at deployment.soco-web.war//com.soco.web.common.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:15)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.opentracing.contrib.opentracing-jaxrs2//io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:52)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at deployment.soco-web.war//com.soco.web.filters.URLFilter.doFilter(URLFilter.java:81)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow@22.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.core@2.2.4.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.2.4.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.2.4.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.core@2.2.4.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.core@2.2.4.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.core@2.2.4.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.core@2.2.4.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@22.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.2.4.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@22.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.core@2.2.4.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@22.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@22.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow@22.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow@22.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow@22.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
	at io.undertow.servlet@2.2.4.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
	at io.undertow.core@2.2.4.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
	at io.undertow.core@2.2.4.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at org.jboss.xnio@3.8.4.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by melloware** [comment] 2022-04-16 20:24
The only reason I don't think you did it right is I don't see your ResourceHandler in the stack trace here:

```
at com.sun.jsf-impl@2.3.14.SP02//com.sun.faces.application.resource.ResourceHandlerImpl.handleResourceRequest(ResourceHandlerImpl.java:318)
at javax.faces.api@3.0.0.SP04//javax.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:171)
at deployment.soco-web.war//org.primefaces.application.resource.PrimeResourceHandler.handleResourceRequest(PrimeResourceHandler.java:89
```

**Comment by jsocola** [comment] 2022-04-16 20:27
Yep a I think the problem is with the primefaces.jar I will change Monday with my friend he has the code in  his machine maybe I need put Resource inside because log said primefaces jQuery and component and they are inside the jar.

**Comment by melloware** [comment] 2022-04-16 20:28
I also have Wildfly on my machine I may try this myself. I have never turned HTTP2 on.

**Comment by melloware** [comment] 2022-04-16 20:42
Also have you tried a JSF app in Wildfly wiht HTTP2 without PrimeFaces?  I am wondering if this is just the first error you are getting.

**Comment by jsocola** [comment] 2022-04-16 20:50
I used with ICEFACES 3.3 and HTTP2 works fine, but is JSF 2.1 no JSF 2.3

**Comment by melloware** [comment] 2022-04-16 21:02
OK here is what I just tested.  I am using the PrimeFaces Showcase WAR file.

Wildfly 18.0.0 with HTTP2 - **works fine**

Wildfly 24.0.1 with HTTP2 - **stacktrace above**

However with Wildfly 24 the app and all its functionality is working just fine its just a bad stack trace in the logs which the above `ResourceHandler` is supposed to disable.  But I am not seeing anything wrong in the Showcase application and in fact its quite fast with HTTP2!

So this all leads to its a Mojarra issue.

**Comment by melloware** [comment] 2022-04-16 21:10
Even more interesting in WildFly 24 I swapped out `jsf-impl-2.3.14.SP04.jar` for official `jakarta.faces-2.3.17.jar` from Mojarra not the Jboss hacked version and there is NO errors in logs and the app is working fine.

So I think the error is even in WildFly's custom Jboss version of Mojarra.

**Comment by melloware** [comment] 2022-04-16 21:20
I stand corrected it is still happening with `2.3.17` but I am still not seeing issues with the application.  I would report this bug to RedHat/Jboss as it seems related to their Mojarra + Undertow combination.

**Comment by melloware** [comment] 2022-04-16 21:24
Its already reported to Wildfly!  I suggest you go upvote this issue.

Issue: https://issues.redhat.com/browse/WFLY-16260

Original Thread: https://developer.jboss.org/thread/279480

**Comment by melloware** [comment] 2022-04-16 21:31
And this thread is not even PrimeFaces related it can't find jsf.js: https://developer.jboss.org/thread/280291

**Comment by jsocola** [comment] 2022-04-17 02:33
You right , I have move to wildly 26.1.0/JDK11/prime 8 works fine with http2. But maybe we can do something with wildfly 20,21,22 I think is the Resources path inside the prime 8 jar.

Thanks for you help!

**Comment by melloware** [comment] 2022-04-17 12:25
Thanks for reporting back.  I really feel like PF is totally fine its an Undertow bug closing the stream which it sounds like they fixed.
