### ISSUE TITLE
Hand icon appearing on entire canvas on primefaces barchart drilldown

### ISSUE THREAD

**Issue by mariaarora** [primefaces/primefaces#2654] opened 2017-08-22 09:50 UTC
# IMPORTANT 
- !!! If you open an issue, fill every item. Otherwise the issue might be closed as invalid. !!!

- Before you open an issue, test it with the current/newest version.
- Try to find an explanation to your problem by yourself, by simply debugging. This will help us to solve your issue 10x faster
- Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.
- Feel free to provide a PR (Primefaces is an open-source project, any fixes or improvements are welcome.)

## 1) Environment
- PrimeFaces version:5.6
- Does it work on the newest released PrimeFaces version? Version?No
- Does it work on the newest sources in GitHub? (Build by source -> No https://github.com/primefaces/primefaces/wiki/Building-From-Source)
- Application server + version:JBoss EAP 7.0
- Affected browsers:Crome,Mozilla

## 2) Expected behavior
Hand Icon should only appear on barchart where drill down is to be made
...

## 3) Actual behavior
Hand Icon appearing on entire page/canvass for barchart drilldown.
..

## 4) Steps to reproduce
1)Drill down a barchart in primefaces and you will see handicon appearing even where there is no drill down.
.. 

## 5) Sample XHTML
<p:chart id="customerScaleChart" type="bar" model="#{bean.customerScaleModel}"
 responsive="true" >
 <p:ajax event="itemSelect" listener="#{bean.getCustomerServicesBasedonIndex}" update="growlvbar" />
 </p:chart>
..

## 6) Sample bean
public String getCustomerServicesBasedonIndex(ItemSelectEvent event){
	try{
			Integer item=event.getItemIndex();
			drillDownvalue=item.toString();
			servicesMap=new TreeMap<>()	;
			customersMap=new TreeMap<>();
			FacesContext facesContext = FacesContext.getCurrentInstance();
			 allServiceFinalList=new ArrayList<>();
			 serviceDStatus=asCustomerList.get(item).getKey();
			 drillDownFilter=languageBundle.getString("customer")+": "+serviceDStatus;	
			 flagRefresh=true;
			int serviceCustomerId=asCustomerList.get(item).getId();
			customersMap.put(serviceDStatus, serviceCustomerId);
		for(VO customer:asCustomerList.get(item).List())
		{
			if(customer.getParentServiceId()==null)
			{
				for(VO serviceVO:VOList ){
					if(serviceVO.getServiceId().intValue()==customer.getServiceId().intValue())
					{
						servicesMap.put(serviceVO.getServiceName(), serviceVO.getServiceId());
						if(serviceVO.getChildServiceList()!=null && serviceVO.getChildServiceList().size()>0){
							getRecursiveServiceChild(serviceVO);
						}
						allServiceFinalList.add(serviceVO);
						break;
					}	
				}
			}
		}
		
}
	return null;
}
..

**Comment by melloware** [comment] 2017-09-25 19:56
I can't reproduce in PF 6.1.  Can you try with the latest code and see if you have the same issue?

I tested on the showcase here:  https://www.primefaces.org/showcase/ui/chart/interactive.xhtml

**Comment by melloware** [comment] 2017-10-16 12:44
@tandraschko I recommend closing this issue as Invalid.

**Closed as completed** 2017-10-16 12:47 UTC
Labels: Resolution: Invalid
