### ISSUE TITLE
auto attibute doesn't work in mode="simple" for p:fileUpload

### ISSUE THREAD

**Issue by JaviRpo** [primefaces/primefaces#1295] opened 2016-04-05 18:29 UTC
I have a p:fileUpload which I want simple mode and auto upload.

I used following libraries:
primefaces-5.3.jar
jsf-api-2.2.10.jar
jsf-impl-2.2.10.jar
JDK 1.8

<p:fileUpload ... mode="simple" skinSimple="true" auto="true" />

**Comment by tandraschko** [comment] 2016-04-05 19:54
use the search next time, it's a duplicate of #1077

**Closed as completed by tandraschko** 2016-04-05 19:54 UTC
Labels: Resolution: Duplicate

**Comment by JaviRpo** [comment] 2016-04-05 19:56
sorry, i will search next time
