### ISSUE TITLE
Push not working in 5.3.RC2: No bean is eligible for injection of EventBus injection point

### ISSUE THREAD

**Issue by Gummi** [primefaces/primefaces#797] opened 2015-10-15 17:33 UTC
Tested on TomEE 1.7.2 with atmosphere-runtime versions 2.3.5, 2.3.0-RC6 (as suggested in the userguide for PF 5.2) and the most resent 2.4.0-RC6, and with PF versions 5.2 and 5.3.RC2. Does not work since no eligible bean is found for injection of EventBus injection points.

The old approach, "EventBus eventBus = EventBusFactory.getDefault().eventBus();", gives NullPointerException in a code that works perfectly on PF version 5.1 and atmosphere-runtime 2.2.2.

Hopefully this can be fixed before the final release of PF 5.3 since 5.1 is the last usable version of Push, it seems.

**Comment by tandraschko** [comment] 2015-10-15 18:50
@jfarcand Could you please take a look at it?

**Comment by jfarcand** [comment] 2015-10-15 18:59
@Gummi Need to share a test case, as PF 5.2 wors fine .... can you reproduce with a the `shwocase`? `EventBus.getDefault()` is deprecated in 5.3 and removed.

**Comment by jfarcand** [comment] 2015-10-15 19:03
@Gummi Also use latest version of 5.2

**Comment by jfarcand** [comment] 2015-10-15 19:31
@Gummi Also read #300 in case that's how you use it.

**Comment by Gummi** [comment] 2015-10-15 20:45
@jfarcand  Since I am just preparing for using Push in my project for the first time I was trying to run a copy of the Push showcase called ViewParam within my project.  I was able to run it successfully on version 5.1, but not on 5.2 or 5.3.RC2 and I don't have access to any of the 5.2.x versions yet.  I altered the showcase copy to use injection for the PF 5.2+ tests.

What I have found out now is that I can make 5.3.RC2 work by accessing EventBus the old way, i.e. `EventBusFactory.getDefault().eventBus()`, if I use atmosphere-runtime 2.4.0-RC6.  Still it does not work with version 2.3.5 but that is ok.  Also, injection always fails regardless of versions but that might be related to some TomEE configuration since I have found out that I am not able to inject any of the Atmosphere beans either, from the list at https://github.com/Atmosphere/atmosphere/wiki/Injecting-Atmosphere-components-and-factories-using-the-javax.inject.Inject , although I am using CDI successfully for many other things in my project.

I was going to suggest that my workaround would be to use atmosphere-runtime 2.4+ and create my own EventBusProducer that would accesses the EventBus the old way and makes it available in CDI.  However, the producer seems to return null for some reason, even though it uses the exact same code that returns an EventBus object when used directly in my `@Named` annotated ViewParamPush bean, i.e. `EventBusFactory.getDefault().eventBus()`.

Nevertheless, I got this to work and will therefore be able to use PF 5.3, so thank you for your help :)

**Comment by jfarcand** [comment] 2015-10-15 21:08
@Gummi My apologie sit shouldn't be that complicated. For CDI I think @Producers implementation is missing. Can you file another issue saying CDI doesn't work? I will fix it once I have a chance. Thanks!!!

**Comment by Gummi** [comment] 2015-10-16 16:10
@jfarcand  For the record, there is one more key to getting Push to work with PF 5.3.RC2 and atmosphere-runtime 2.4.0-RC6. One needs to add `<load-on-startup>1</load-on-startup>`  to the servlet configuration given in the 5.2 user guide:

```
<servlet>
    <servlet-name>Push Servlet</servlet-name>
    <servlet-class>org.primefaces.push.PushServlet</servlet-class>
    <load-on-startup>1</load-on-startup>
    <async-supported>true</async-supported>
</servlet>
<servlet-mapping>
    <servlet-name>Push Servlet</servlet-name>
    <url-pattern>/primepush/*</url-pattern>
</servlet-mapping>
```

And also, the EventBusProducer workaround actually works as expected now.  I must have made some mistake while testing when it did not work before.

**Comment by tandraschko** [comment] 2017-01-24 13:23
Looks like this has been fixed in atmosphere directly.

**Closed as completed by tandraschko** 2017-01-24 13:23 UTC
