### ISSUE TITLE
DataTable: Custom content in paginator duplicate ID breaks ajax

### ISSUE THREAD

**Issue by djmj** [primefaces/primefaces#751] opened 2015-10-04 22:32 UTC
Using a paginator that is rendered at top and bottom and custom content contains an element with an ID this ID is duplicated in the final DOM.

Once for the top paginator and once for the bottom paginator.

Ajax is only working for the top component and view jumps to bottom one after update.

Changin value in bottom menu invokes the ajax but on update the old value is selected again.

```
<f:facet name="{PagContent}">
    <h:selectOneMenu id="sortCriterion" value="#{bean.sortCriterion}" style="float: right;" >
        <p:ajax update=":mainForm:pnlHotels"/>
        <f:selectItem itemLabel="Relevance" itemValue="#{null}"/>
        <f:selectItems var="varSortCriterion" value="#{bean.sortCriteria}" itemLabel="#{varSortCriterion}" itemValue="#{varSortCriterion}"/>
    </h:selectOneMenu>
</f:facet>
```

Maybe this is also the reason why <p:selectOneMenu> is not working as custom content in paginator?!

Forum url: http://forum.primefaces.org/viewtopic.php?f=3&t=43082

**Comment by sudheerj** [comment] 2016-01-19 18:42
If separate paginator component takes more time then it is good to have header and footer facet for custom paginator to avoid duplicate ID issue.

**Comment by tandraschko** [comment] 2017-10-19 08:45
Duplicate of #2650

**Closed as completed by tandraschko** 2017-10-19 08:45 UTC
Labels: Resolution: Duplicate
