### ISSUE TITLE
SelectOneMenu: CSV requiredMessage not showing

### ISSUE THREAD

**Issue by nixonyeung** [primefaces/primefaces#8311] opened 2022-01-21 00:58 UTC
I have a form includes an inputtext and a selectonemenu. validateClient is set to true to verify the values are input and selected. But for the selectonemenu if I haven't on focus the element, the requiredMessage "Magistracy is required" will not show up when I clicking the Submit button. Please have a look, thanks.

```xml
<h:form id="detail-form">
			<p:dialog header="Departmental Summons" widgetVar="DetailDialog" width="80%" modal="true" fitViewport="true" closeOnEscape="false" position="top" blockScroll="true">
				<p:outputPanel id="detail-content">
					<div class="grid  ">
						<div class="col-12 text-right pt-3">
							<span style="color: red;">*</span> Required Field
						</div>
					</div>
					<div class="grid ui-fluid ai-b">
						<div class="col-3 ">
							<p:outputLabel value="Departmental Reference No." />
							<span style="color: red;">*</span>
						</div>
						<div class="col-9">
							<p:inputText value="#{departmentalSummonsBean.detailRecord.emailTmplFuncName}" required="true" requiredMessage="Departmental Reference No. is required" />
							<p:message for="@previous" />
						</div>
						<div class="col-3 ">
							<p:outputLabel value="Magistracy" />
							<span style="color: red;">*</span>
						</div>
						<div class="col-3">
							<p:selectOneMenu autoWidth="false" value="#{departmentalSummonsBean.detailRecord.emailTmplId}" required="true" requiredMessage="Magistracy is required">
								<f:selectItem itemLabel="" itemValue="" />
								<f:selectItem itemLabel="ES - Mag. Courts" itemValue="ES" />
								<f:selectItem itemLabel="FL - Mag. Courts" itemValue="FL" />
							</p:selectOneMenu>
							<p:message for="@previous" />
						</div>
					</div>
				</p:outputPanel>
				<f:facet name="footer">
					<div class="grid">
						<div class="col-6"></div>
						<div class="col-6" align="right">
							<p:commandButton value="Submit" resetValues="true" validateClient="true" ajax="false" icon="pi pi-save" class="mr-2" update="detail-form  " />
							<p:commandButton type="button" value="Cancel" icon="pi pi-times" styleClass="ui-button-secondary" onclick="PF('DetailDialog').hide();" />
						</div>
					</div>
				</f:facet>
			</p:dialog>
		</h:form>
```

**Environment:**
 - PF Version: _11.0_
 - JSF + version: _JAVAServer Face 2.2
 - Affected browsers: _ALL_

**Comment by melloware** [comment] 2022-01-21 13:02
I think this is a duplicate of this ticket: https://github.com/primefaces/primefaces/issues/8308

Can you add this script to your JS and tell me if it is fixed?

```javascript
PrimeFaces.widget.SelectOneMenu.prototype.handleEnterKey = function(event) {
    if (this.panel.is(':visible')) {
        this.selectItem(this.getActiveItem());
        event.stopPropagation();
    }

    event.preventDefault();
};
```

Just add that script your your application JS file that loads after PF.

**Comment by melloware** [comment] 2022-01-21 13:11
It is working fine for me. Attached is reproducer run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

![image](https://user-images.githubusercontent.com/4399574/150532704-38bec38f-bee7-48ff-a13e-5d84401f17a7.png)

Reproducer:  [pf-8311.zip](https://github.com/primefaces/primefaces/files/7913862/pf-8311.zip)

**Comment by melloware** [comment] 2022-01-24 12:38
Closing for now unless OP comes back with more info.

**Comment by nixonyeung** [comment] 2022-01-25 02:05
> It is working fine for me. Attached is reproducer run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/
> 
> ![image](https://user-images.githubusercontent.com/4399574/150532704-38bec38f-bee7-48ff-a13e-5d84401f17a7.png)
> 
> Reproducer: [pf-8311.zip](https://github.com/primefaces/primefaces/files/7913862/pf-8311.zip)

I have tried the reproducer and found that the problem occurs if I added primefaces.CLIENT_SIDE_VALIDATION = true in web.xml

Attached the modified web.xml and screen capture

[web.zip](https://github.com/primefaces/primefaces/files/7930061/web.zip)
![image](https://user-images.githubusercontent.com/41794209/150897238-85afca95-2bf8-4972-94aa-33cfa295117c.png)

**Comment by melloware** [comment] 2022-01-25 17:03
OK I submitted a PR to fix it.

**Closed as completed** 2022-01-26 08:14 UTC
Labels: :lady_beetle: defect
