### ISSUE TITLE
Breadcrumbs are not responsive

### ISSUE THREAD

**Issue by githubuser100007** [primefaces/primefaces#8176] opened 2021-12-16 16:18 UTC
Not sure if this is a defect generally, but in the RAIN template, the breadcrumb breaks our responsive site.

**Reproducer**
Add breadcrumbs as you would normally.

In the RAIN template, I use:

```
    <ui:define name="viewname">
		<li><h:outputLink value="/page.htm">Link Text</h:outputLink></li>
        <li><i class="pi pi-chevron-right"></i></li>
		<li><h:outputLink value="/page.htm">Link Text</h:outputLink></li>
        <li><i class="pi pi-chevron-right"></i></li>
		<li><h:outputLink value="/page.htm">Link Text</h:outputLink></li>
        <li><i class="pi pi-chevron-right"></i></li>
		<li><h:outputLink value="/page.htm">Link Text</h:outputLink></li>
        <li><i class="pi pi-chevron-right"></i></li>
		<li><h:outputLink value="/page.htm">Link Text</h:outputLink></li>
        <li><i class="pi pi-chevron-right"></i></li>
		<li><h:outputLink value="/page.htm">Link Text</h:outputLink></li>
        <li><i class="pi pi-chevron-right"></i></li>
		<li><h:outputLink value="/page.htm">Link Text</h:outputLink></li>
        <li><i class="pi pi-chevron-right"></i></li>
	</ui:define>
```

An example of a list working responsively that I found:
https://codepen.io/danield770/pen/nmBKr

**Environment:**
 - PF Version: 11
 - JSF + version: MyFaces 2.3.9
 - Affected browsers: ALL

**Comment by tandraschko** [comment] 2021-12-16 16:20
i cant see any p:breadcrumb? please write better tickets

**Comment by jepsar** [comment] 2021-12-16 16:36
Possible duplicate of #6480

**Comment by githubuser100007** [comment] 2021-12-16 16:39
I'm just following the RAIN template that we purchased. We define the viewname section just like in the demo. It doesn't wrap and breaks mobile layouts.

**Comment by tandraschko** [comment] 2021-12-16 16:49
then please use the RAIN forum - this issue tracker is for PrimeFaces Core only

**Closed as completed by tandraschko** 2021-12-16 16:49 UTC
Labels: :lady_beetle: defect, Resolution: Invalid
