### ISSUE TITLE
When using DataTable and RowEditor there is a LineBreak in the Column. How to remove ?

### ISSUE THREAD

**Issue by omerzimeri1** [primefaces/primefaces#2268] opened 2017-04-12 11:54 UTC
## 1) Environment
- PrimeFaces version: 6.0

## 2) Actual behavior

I am using a DataTable und RowEditor. But when i use Celleditor in a Column where a inputText and a OutputText is, then there is a automatically a LINEBREAK added.

## 3) Expected behavior

NO LINEBREAK when using RowEditor in DataTable!

## 4) Sample XHTML

```html
<p:dataTable editMode="row" id="schuelernotenTable" 
                             editable="true" 
                             value="#{conNotenEinzeln.notenSchueler}"
                             var="item" >

                    <p:ajax event="rowEdit" listener="#{conNotenEinzeln.updateLaufendeNote}" update=":showNotenForm:messageShowNoten" />

                    <p:column width="10%" headerText="Datum">
                        <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{item.laufTimestamp}"><f:convertDateTime pattern="dd.MM.yyyy" locale="de" timeZone="Europe/Berlin"/></h:outputText></f:facet>
                            <f:facet name="input">
                                <p:calendar value="#{item.laufTimestamp}"
                                            id="timestampedit"
                                            locale="de"
                                            pattern="dd.MM.yyyy"
                                            timeZone="Europe/Berlin"
                                            readonly="true"
                                            required="true" 
                                            requiredMessage="Bitte geben Sie ein Datum ein!">       
                                </p:calendar>
                            </f:facet>
                        </p:cellEditor>
                    </p:column>

                    <p:column width="22%" headerText="Öffentliche Bemerkung">
                         <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{item.laufBemerkung}"/></f:facet>
                            <f:facet name="input"><h:inputText value="#{item.laufBemerkung}" style="width:100%"/></f:facet>
                        </p:cellEditor>  
                    </p:column>

                    <p:column width="23%" headerText="Private Bemerkung">
                         <p:cellEditor>
                            <f:facet name="output"><h:outputText value="#{item.laufSecretBemerkung}"/></f:facet>
                            <f:facet name="input">
                                <h:inputText id="editSBemerkung" value="#{item.laufSecretBemerkung}" style="width:100%"/>
                            </f:facet>
                        </p:cellEditor>
                    </p:column>
         
                    <p:column width="4%">
                        <p:rowEditor />
                    </p:column>
</p:dataTable>
```

## 5) RENDERED HTML EXAMPLE

```html
<td role="gridcell" class="ui-editable-column">
                        &nbsp;
  <div id="showNotenForm:schuelernotenTable:0:j_idt87" class="ui-cell-editor">
      <div class="ui-cell-editor-output" style="display: none;">d</div>
      <div class="ui-cell-editor-input">
    		<input type="text" name="showNotenForm:schuelernotenTable:0:j_idt90" value="d" 		                    style="width:100%">		   
      </div>
  </div>
</td>
```

## 6) OUTPUT RENDERED HTML

You can see in the second and in the third column the editor and that there is a LineBreak before the INPUTTEXT
![Example image](https://github.com/omerzimeri1/markdown-image/raw/master/example.JPG "image")

**Comment by melloware** [comment] 2017-04-12 15:07
Just to clarify... Do you mean a line break "BR" or space "nbsp;"?

**Comment by omerzimeri1** [comment] 2017-04-12 15:19
It's a "&nbsp;" 
Look at the picture how it is renderee in Datatable

**Comment by omerzimeri1** [comment] 2017-04-12 15:20
It's a "& nbsp;"

**Comment by melloware** [comment] 2017-04-13 12:57
Hmm I am not seeing this behavior on the latest showcase is it possible this is already fixed?

https://www.primefaces.org/showcase/ui/data/datatable/edit.xhtml

**Comment by omerzimeri1** [comment] 2017-04-13 13:23
Yeah but the showcase runs in the version PrimeFaces-6.1-SNAPSHOT.

I'm using the version 6.0.

Is the PrimeFaces-6.1-SNAPSHOT - Version free for usage ?

**Comment by melloware** [comment] 2017-04-13 13:27
Yes 6.1.RC2 is free for download read here:

https://www.primefaces.org/primefaces-6-1-rc2-released/

If you discover it is fixed after trying this version please Close this defect.

**Comment by kukel** [comment] 2017-04-14 11:07
Sure you did not add a 'nbsp' yourself somewhere by pressing ctrl-space or something?

**Comment by melloware** [comment] 2017-04-17 11:32
@omerzimeri1 Were you able to test 6.1RC3 and verify?

**Comment by omerzimeri1** [comment] 2017-04-17 13:55
i have tested 6.1.RC3, but it is not working
I have the same problem as in 6.0
The Linebreak ist not removing

**Comment by melloware** [comment] 2017-04-17 13:57
OK my next suggestion then is to make a reproducible example for us to debug.   Because I can't reproduce your issue using the showcase.  To reproduce use this template...

Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.

**Comment by omerzimeri1** [comment] 2017-04-17 15:37
ok here is the result with primefaces-test.git

## 1) Model:

```java

public class Car {
    private String brand;
    private String color;
    private static final List<Car> cars;
    
     static { 
         cars = new ArrayList<Car>();
         
         cars.add(new Car("BMW", "red"));
         cars.add(new Car("Mercedes Benz", "blue"));
         cars.add(new Car("Audi", "yellow"));
         cars.add(new Car("Bugatti", "chrome"));
         cars.add(new Car("Porsche", "white"));
     }
     
    public Car() {
        this("","black");
    }

    public Car(String brand, String color) {
        this.brand = brand;
        this.color = color;
    }
  
    // Getter, Setter, ToString, Hashcode, Equals    
}
```

## 2) Controller:

```java
@ManagedBean(name = "testView")
@ViewScoped
public class TestView implements Serializable {

    private List<Car> cars1;
              
    @PostConstruct
    public void init() {
        cars1 = new ArrayList(Car.getCars());
    }
 
    public List<Car> getCars1() {
        return cars1;
    }
 
     
    public void onRowEdit(RowEditEvent event) {
        FacesMessage msg = new FacesMessage("Car Edited", ((Car) event.getObject()).getBrand());
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }
     
    public void onRowCancel(RowEditEvent event) {
        FacesMessage msg = new FacesMessage("Edit Cancelled", ((Car) event.getObject()).getBrand());
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }
}
```

## 3) View:

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html">

    <h:head>   
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>

        <h:form id="form">
            <p:growl id="msgs" showDetail="true"/>
                            
            <p:dataTable editMode="row" id="schuelernotenTable" 
                         editable="true" 
                         value="#{testView.cars1}"
                         var="car" 
                         emptyMessage="Keine Datensätze vorhanden..."
                         resizableColumns="true" liveResize="true">

                <p:ajax event="rowEdit" listener="#{testView.onRowEdit}" update=":form:msgs" />
                <p:ajax event="rowEditCancel" listener="#{testView.onRowCancel}" update=":form:msgs" />
 

                <p:column width="22%" headerText="Brand">
                     <p:cellEditor>
                        <f:facet name="output"><h:outputText value="#{car.brand}"/></f:facet>
                        <f:facet name="input"><h:inputText value="#{car.brand}" style="width:100%"/></f:facet>
                    </p:cellEditor>  
                </p:column>
                <p:column width="23%" headerText="Private Bemerkung">
                     <p:cellEditor>
                        <f:facet name="output"><h:outputText value="#{car.color}"/></f:facet>
                        <f:facet name="input">
                            <h:inputText id="editSBemerkung" value="#{car.color}" style="width:100%"/>
                        </f:facet>
                    </p:cellEditor>
                </p:column>
                <p:column width="4%">
                    <p:rowEditor />
                </p:column>
            </p:dataTable>
        </h:form>
    </h:body>
</html>
```

## 4) OUTPUT RENDERED HTML

You can see that there is a LineBreak ("& nbsp;") above the INPUTTEXT and the text-alignment ist not in the middle. In primefaces-showcases isn't a LineBreak!

![Example image](https://github.com/omerzimeri1/markdown-image/raw/master/test.JPG "image")

**Comment by melloware** [comment] 2017-04-17 17:09
Can you zip up the project and attach here as a .gz or some other way?  That way I can run it myself.

**Comment by omerzimeri1** [comment] 2017-04-17 17:18
[primefaces-test.zip](https://github.com/primefaces/primefaces/files/926156/primefaces-test.zip)

**Comment by melloware** [comment] 2017-04-17 18:02
Found your issue.  Look at my screenshot my editor is showing a garbage unicode character "A" in the file right before <p:cellEditor>.  As soon as I remove those two invalid characters your table renders correctly.

![image](https://cloud.githubusercontent.com/assets/4399574/25098401/61fb47c4-2376-11e7-9d42-b3bd6992ff69.png)

**Comment by omerzimeri1** [comment] 2017-04-17 18:43
Thats weird. I used netbeans so i couldn't see that there is a unicode character "A".

**Comment by melloware** [comment] 2017-04-17 19:18
I could not see it in Eclipse either!   So I finally used my hex editor to see if there was anything in there and sure enough.  So I think its safe to close this ticket.

**Closed as completed** 2017-04-17 19:20 UTC
