### ISSUE TITLE
DataTable+ RowToggler + Column selectionMode=multiple+ RowExpansion + TextArea  : can't use space in textArea

### ISSUE THREAD

**Issue by AlexChaplygin** [primefaces/primefaces#7317] opened 2021-05-14 11:24 UTC
**I have dataTable**

`
<p:dataTable widgetVar="..." id="..." value="#{...}"
   reflow="true" styleClass="..."
   sortBy="#{...}" sortOrder="descending" rowIndexVar="rowIndex"
   var="..."
   paginator="true" rows="100" paginatorPosition="bottom"
   paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink}                                                                         {LastPageLink} {RowsPerPageDropdown} {DateFormat}"
   currentPageReportTemplate="Total {totalRecords} ({currentPage} of {totalPages})"
   rowsPerPageTemplate="5,10,20,50,100"
   rowKey="#{...}" selection="#{...}"
   rowExpandMode="single" filteredValue="#{...}">`
   
   
`
<p:column selectionMode="multiple" style="width: 35px;" styleClass="text-center"/>
`

`
<p:column style="width: 30px; text-align: center">
   <p:rowToggler/>
</p:column>
`

inside p:rowExpansion I have: 
`
<p:inputTextarea value="#{...}"
   counter="counter" maxlength="1000" rows="10"
   autoResize="false"
   counterTemplate="..."
   style="width: 100%; height: 100px; max-height: 100px;"/>
`

When I editing inputTextArea I want to add space. 

When I am trying to click the toggler button, all good I can use spaces in textArea.
When I click just checkbox, all good I can use spaces in textArea.
When I click a row, I can't use spaces in textArea.
If I click a row, after that uncheck checkbox and use space in textArea, checkbox become checked.

**Environment**
 - PF Version: 6.2
 - org.glassfish javax.faces 2.2.14
 - Affected browsers: ALL

**Expected behavior**
I can use spaces in textArea

Thank you
![test1](https://user-images.githubusercontent.com/29481251/118263967-aaaab700-b4bf-11eb-9b3f-0e2a9affb5c0.jpeg)

**Comment by melloware** [comment] 2021-05-14 13:08
if this is for 6.2 we won't be fixing it as its more than 2 major versions behind.  We would need a reproducer showing its still a problem in PF10.

Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by melloware** [comment] 2021-05-18 11:46
Closing until a reproducer is provided

**Closed as completed by melloware** 2021-05-18 11:46 UTC
Labels: needs further work

**Comment by AlexChaplygin** [comment] 2021-05-23 20:24
https://github.com/AlexChaplygin/primefacesbug

I reproduced it on 7.0 version but if I change version to 8.0 everything is ok. Do you have any thoughts about it? Some workarounds?

**Comment by melloware** [comment] 2021-05-24 12:10
@AlexChaplygin Looks like about 500 GitHub issues were closed between 7.0 and 8.0 so its hard to speculate what fixed it.  I doubt you will get much support on 7.0 now that 8.0 and 10.0 are the latest two major versions.  I would say your best best is to upgrade to 8.0 or 10.0
