### ISSUE TITLE
Schedule: The integrated tooltip is using the coordinates for the schedule component instead of the parent window.

### ISSUE THREAD

**Issue by lemmondg** [primefaces/primefaces#4497] opened 2019-02-04 23:44 UTC
## 1) Environment
- PrimeFaces version: 6.2.8
**- Does it work on the newest released PrimeFaces version?**    No, It is still a problem on version 6.2.8
**- Does it work on the newest sources in GitHub?**    I haven't tried it but the source code in question has not changed.  
**- Application server + version:**               Tomcat 8
**- Affected browsers:**                               All browsers are affected.

**## 2) Expected behavior:** 
The schedule tooltip is expected to appear right below a schedule component event object, lined up with the left side.

**## 3) Actual behavior**
The schedule component integrated tooltip appears too far down and to the left when it does not take up the entire window.  Please refer to attached image for example.
![2-4-2019 3-48-52 pm](https://user-images.githubusercontent.com/16196835/52244507-2ce8b180-289b-11e9-9829-acd9ec6013b6.jpg)

## 4) Steps to reproduce

- Add a titlebar, and a Tabs set the height of both to be 20px.
- Inside the table add a left panel that is about 45px wide
- Add a scheduler to the right of the empty panel and set the toolbar property to true
- Add supporting code and run 
- move mouse over an event with text in the description.  The tooltip will apear 45px too far to the right and 40px below where it should be.
Please see attached image for example:
![2-4-2019 3-48-52 pm](https://user-images.githubusercontent.com/16196835/52244507-2ce8b180-289b-11e9-9829-acd9ec6013b6.jpg)

## 5) Possible solution using 6.2.8 code:

[schedule.js.txt](https://github.com/primefaces/primefaces/files/2830212/schedule.js.txt)

**Comment by melloware** [comment] 2019-02-05 00:34
@OBreidenbach do you mind reviewing this?

**Comment by OBreidenbach** [comment] 2019-02-05 07:55
@melloware, Sorry, but I am short on time at the moment.
@lemmondg, may be you can provide a running example? You can use the sample project. https://github.com/primefaces/primefaces-test
If you already have a solution, can you please provide a pull request?
Thanks

**Comment by melloware** [comment] 2019-02-06 12:48
Can you try it with PF 7.0.RC2?  I can't reproduce your issue as the tooltip is always near the event.

![image](https://user-images.githubusercontent.com/4399574/52342417-5a407700-29e3-11e9-809a-edd412aab2f5.png)

And debugging its the "jsEvent" that its using the coordinates for event on the screen which all seems correct to me.  Maybe this was fixed as part of the Full Calendar JS update for 7.0 https://github.com/primefaces/primefaces/issues/1817

**Comment by melloware** [comment] 2019-02-17 13:30
@lemmondg any chance you had time to verify this with 7.0.RC3 so we can close this issue?

**Comment by tandraschko** [comment] 2019-03-20 10:44
No example, no response -> invalid

**Closed as completed by tandraschko** 2019-03-20 10:44 UTC
Labels: Resolution: Invalid
