### ISSUE TITLE
Tree Drag and Drop not working

### ISSUE THREAD

**Issue by shelcomite** [primefaces/primefaces#8223] opened 2022-01-03 18:46 UTC
Describe the defect
The drag and drop tree example in the showcase does not work. 

Reproducer
Go to
https://www.primefaces.org/showcase/ui/data/tree/dragdrop.xhtml
and drag/drop any node

Environment:

PF Version: 11.0.0
JSF + version:
Affected browsers: Chrome, Firefox,...

**Comment by FlipWarthog** [comment] 2022-01-03 18:52
@melloware You can assign this to me and I'll investigate.

**Comment by jepsar** [comment] 2022-01-03 18:53
Works for me

**Comment by melloware** [comment] 2022-01-03 18:53
@jepsar  I am using Chrome on Windows and it won't let me drag between the trees.  I can only drop nodes on the same tree at the same level.

**Comment by FlipWarthog** [comment] 2022-01-03 19:08
@melloware @jepsar It's the dropzones; they're super tiny so it has to be right on the mark and you'll see it highlight. 

![image](https://user-images.githubusercontent.com/83613837/147969647-a332d9bb-0c26-4d11-8584-6b68cc14e6a8.png)

**Comment by melloware** [comment] 2022-01-03 19:31
Ahh so its just a showcase issue?

**Comment by FlipWarthog** [comment] 2022-01-03 19:57
> Ahh so its just a showcase issue?

That, I haven't gotten to yet. I need to set up a reproducer in primefaces-test to see if it behaves the same.

**Comment by FlipWarthog** [comment] 2022-01-04 01:42
Correction to my previous statement, the drop zones for putting a node between two other nodes (reordering) is working. The drop zones for adding a node as a child of another node is not working. I'm about to submit a PR with the fix but I also want to provide a MonkeyPatch for anyone seeing this issue in their own application on PF11 (or possibly PF10):

```javascript
if (PrimeFaces.widget.VerticalTree) {
    PrimeFaces.widget.VerticalTree.prototype.initDroppable = function() {
        this.makeDropPoints(this.jq.find('li.ui-tree-droppoint'));
        this.makeDropNodes(this.jq.find('.ui-treenode-droppable'));
        this.initDropScrollers();
    }
    PrimeFaces.widget.VerticalTree.prototype.makeParent = function(node) {
        node.removeClass('ui-treenode-leaf').addClass('ui-treenode-parent');
        node.find('> .ui-treenode-content > span.ui-treenode-leaf-icon').removeClass('ui-treenode-leaf-icon').addClass('ui-tree-toggler ui-icon ui-icon-triangle-1-e');
        node.children('.ui-treenode-children').append('<li class="ui-tree-droppoint ui-droppable"></li>');

        this.makeDropPoints(node.find('> ul.ui-treenode-children > li.ui-tree-droppoint'));
    }
}
```

**Closed as completed** 2022-01-04 08:19 UTC
Labels: :lady_beetle: defect, workaround, 11.0.4, 10.0.12

**Comment by melloware** [comment] 2022-01-04 13:26
If you need this fix right now here is a Monkeypatch:

```javascript
if (PrimeFaces.widget.VerticalTree) {
    PrimeFaces.widget.VerticalTree.prototype.initDroppable = function() {
        this.makeDropPoints(this.jq.find('li.ui-tree-droppoint'));
        this.makeDropNodes(this.jq.find('span.ui-treenode-droppable'));
        this.makeDropNodes(this.jq.find('.ui-treenode-droppable'));
        this.initDropScrollers();
    }
};
```

**Comment by FlipWarthog** [comment] 2022-01-04 17:04
@melloware You need both function fixes for it to work fully (see above). Otherwise the drop will work, but the node accepting the drop won't become a parent (if needed) and it'll cause the dropped node to disappear.

**Comment by melloware** [comment] 2022-01-04 17:11
Ahhh I see now.
