### ISSUE TITLE
Jakarta Build: XSD References

### ISSUE THREAD

**Issue by GedMarc** [primefaces/primefaces#7087] opened 2021-03-08 12:47 UTC
**Describe the defect**

When using the Jakarta artefacts the tag libs are not resolved due to the facelet definition, 
To autodetect (with specifying taglibraries in servlet) the tag library needs to be in jakarta namespace as well

**Required** 
```
<facelet-taglib xmlns="https://jakarta.ee/xml/ns/jakartaee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-facelettaglibrary_3_0.xsd"
    version="3.0">
```

**Current** 
```
<facelet-taglib xmlns="http://java.sun.com/xml/ns/javaee" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-facelettaglibrary_2_0.xsd" 
version="2.0">
```

EE9 XSD: https://jakarta.ee/xml/ns/jakartaee/#9

- [ ]  web-fragment.xml
- [ ]  faces-config.xml
- [ ]  primefaces-p.taglib.xml

**Comment by GedMarc** [comment] 2021-03-08 13:28
Solved in a shade

**Comment by melloware** [comment] 2021-03-08 13:47
@GedMarc is this something we need to do in PF shade in the pom.xml?

**Comment by melloware** [comment] 2021-03-09 16:47
Ping @GedMarc

**Comment by GedMarc** [comment] 2021-03-10 08:07
Sorry, I have to roll it back, i gave it a good 'ol college try but It's not deploying to my artifactory as a complete with everything release

**Comment by melloware** [comment] 2021-03-21 15:42
I think we need to solve this and add the proper schemas in the Jakarta version of the PF Jar for these 3 XML files.

https://jakarta.ee/xml/ns/jakartaee/#9

- [ ] web-fragment.xml
- [ ] faces-config.xml
- [ ] primefaces-p.taglib.xml

**Comment by melloware** [comment] 2021-03-22 15:25
@GedMarc I think the problem is you can't just change the header.  I think it might be that the XML needs to be changed to conform to the stricter schema.  I know in IntelliJ I get errors when I just change the XSD.

**Comment by GedMarc** [comment] 2021-03-22 15:32
I've created a release on 10.0 with the change that's' working nicely - picks up runs and everything (Mojarra), as my base is jakarta namespaced i dont really need to worry about the backwards compatibility ;)

https://mvnrepository.com/artifact/com.guicedee.services/primefaces/1.1.1.2-jre15

IntelliJ and Eclipse pick up nicely, haven't found any issues so far (besides for jstl not being read at all) - releasing it to the dev team tomorrow morning to see what happens

**Comment by GedMarc** [comment] 2021-03-22 15:35
ref to wait for the jsp/jstl namespace finalization decision - https://github.com/eclipse-ee4j/jstl-api/issues/144

**Comment by christophs78** [comment] 2021-04-06 12:21
> ref to wait for the jsp/jstl namespace finalization decision - [eclipse-ee4j/jstl-api#144](https://github.com/eclipse-ee4j/jstl-api/issues/144)

Maybe we need to provide a JAR for JSF3 und one for JSF4, because they have different namespaces.

**Comment by GedMarc** [comment] 2021-04-08 01:55
ok looks like i've got something on the jakarta shade that works with updates, just doing some final checks

**Comment by melloware** [comment] 2021-04-08 11:32
@GedMarc that is great news. Looking forward to reviewing it.

**Comment by GedMarc** [comment] 2021-04-12 07:08
JSP and JSTL removed from Mojarra in v4 - that explains my issues sigh

https://github.com/eclipse-ee4j/mojarra/releases/tag/4.0.0-M1-RELEASE

**Comment by tandraschko** [comment] 2021-04-12 07:23
JSTL is still there

**Comment by GedMarc** [comment] 2021-04-12 07:28
Mmm weird.. the JSTL's have moved into the faces URN, 

![image](https://user-images.githubusercontent.com/5367513/114356875-5f745000-9b71-11eb-8b36-c4f7f848b2dc.png)

**Comment by GedMarc** [comment] 2021-04-12 07:31
yeah ok, i'll make the updates

![image](https://user-images.githubusercontent.com/5367513/114357191-bed26000-9b71-11eb-86fa-1f41ffcbba59.png)

**Comment by tandraschko** [comment] 2021-05-25 09:12
@GedMarc can we close it? or is there anything we need to do?

**Comment by GedMarc** [comment] 2021-05-25 09:18
its been open for a really long time I think its safe to close - 
We need to wait for other teams and central deploys first as well either way, i think when that happens and we know what to do we can pick this up again?

**Comment by tandraschko** [comment] 2021-05-25 09:20
yep

**Closed as completed by tandraschko** 2021-05-25 09:20 UTC
Labels: :lady_beetle: defect
