### ISSUE TITLE
DataTable: reset-method does not reset rows-(per-page-)attribute

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#5465] opened 2019-12-21 08:43 UTC
Think reset should call resetRows which was added with https://github.com/primefaces/primefaces/issues/4573

**Comment by christophs78** [comment] 2019-12-21 08:48
... seems to be a bit more complicated

**Comment by Rapster** [comment] 2019-12-21 14:13
Please follow issue template

**Comment by christophs78** [comment] 2019-12-21 15:45
## 1) Environment
- PrimeFaces version: 8.0-SNAPSHOT
Not related to Browser or Application-Server

## 2) Expected behavior
DataTable#reset should reset the row´s per page to the value provided via XHTML-attribute
`<p:dataTable id="tableStateDT" var="car" value="#{dtTableStateView.cars}" widgetVar="carsTable" multiViewState="true" rows="10" paginator="true" `

## 3) Actual behavior
DataTable#reset keeps the row´s per page as selected by the user. It does not reset rows (per page).

```
public void reset() {
	resetValue();
	setFirst(0);
	reset = true;
	setValueExpression("sortBy", getDefaultSortByVE());
	setSortFunction(getDefaultSortFunction());
	setSortOrder(getDefaultSortOrder());
	setSortByVE(null);
	setSortColumn(null);
	setSortField(null);
	setDefaultSort(true);
	setSortMeta(null);
}
```

## 4) Steps to reproduce

1. http://localhost:8080/showcase/ui/data/datatable/tableState.xhtml
with applied PR https://github.com/primefaces/showcase-facelift/pull/99
2. Change the rows per page via DropDown
3. Push "Clear table state"

**Comment by Rapster** [comment] 2019-12-23 21:30
Is this ticket a duplicate of #5463 or does it give a clue why it's not working in #5463? I'm confused

**Comment by christophs78** [comment] 2019-12-24 06:29
#5463 and #5465 are both related to DataTable. But this issue is not related to multiViewState. This issue simple says the rows (per page) - attribute ist not reset by the reset-method.
(I simply noted this issue during testing #5463, so i opened a separate issue for this.)

**Comment by melloware** [comment] 2020-09-09 15:33
Any update on this ticket?

**Comment by christophs78** [comment] 2020-09-10 11:07
What do we expect from DataTable#reset?
It clears filtering and sorting, jump´s back to the first page, ... But currently it does not reset rows-per-page.
You should see this in the linked integration-test-PR.

**Comment by melloware** [comment] 2020-09-10 11:30
I would think it would reset rows per page by re-evaluating the EL expression.

**Comment by christophs78** [comment] 2020-09-10 17:58
Current UIData-code
```
@Override
public void setRows(int rows) {
	if (rows < 0) {
		throw new IllegalArgumentException(String.valueOf(rows));
	}
	ELContext elContext = getFacesContext().getELContext();
	ValueExpression rowsVe = ValueExpressionAnalyzer.getExpression(
			elContext, getValueExpression(PropertyKeys.rows.name()));
	if (isWriteable(elContext, rowsVe)) {
		rowsVe.setValue(elContext, rows);
	}
	else {
		getStateHelper().put(UIData.PropertyKeys.rows, rows);
	}
}
```

By selecting another rows-per-page-amount the inital value is overwritten a) in state-helper or b) the bound value.

One solution would be to store the original value via StateHelper as eg rowsInitialValue and restore this as part of DataTable#reset.

**Comment by melloware** [comment] 2020-09-10 18:01
Correct, I think you would have to store off the initial value to be able to reset it.

**Closed as completed** 2020-10-12 13:29 UTC
Labels: enhancement
