### ISSUE TITLE
TimeLine: Cannot add the same component twice

### ISSUE THREAD

**Issue by gasparbarancelli** [primefaces/primefaces#2278] opened 2017-04-17 17:31 UTC
**1) Environment**

- **PrimeFaces version**: All version above 6.0.12 
- **Application server + version**: GlassFish Server Open Source Edition 4.1 (build 13) / Payara Server 4.1.1.163 #badassfish (build 215)
- **Affected browsers**: All

**2) Expected behavior**

Update component timeline.

**3) Actual behavior**

The screen only renders on first access.

**4) Steps to reproduce**

I used the same showcase code from primefaces on the timeline component

**5) Follows the error print on the console** 

```
javax.faces.FacesException: Cannot add the same component twice: form:tabView2:timeline
	at com.sun.faces.context.StateContext$DynamicAddRemoveListener.handleAddRemoveWithAutoPrune(StateContext.java:751)
	at com.sun.faces.context.StateContext$DynamicAddRemoveListener.handleAdd(StateContext.java:678)
	at com.sun.faces.context.StateContext$AddRemoveListener.processEvent(StateContext.java:352)
	at com.sun.faces.context.StateContext$DynamicAddRemoveListener.processEvent(StateContext.java:568)
	at javax.faces.event.SystemEvent.processListener(SystemEvent.java:108)
	at javax.faces.event.ComponentSystemEvent.processListener(ComponentSystemEvent.java:118)
	at com.sun.faces.application.ApplicationImpl.processListenersAccountingForAdds(ApplicationImpl.java:2236)
	at com.sun.faces.application.ApplicationImpl.invokeViewListenersFor(ApplicationImpl.java:2057)
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:292)
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:247)
	at javax.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:726)
	at javax.faces.component.UIComponentBase.publishAfterViewEvents(UIComponentBase.java:2246)
	at javax.faces.component.UIComponentBase.doPostAddProcessing(UIComponentBase.java:1927)
	at javax.faces.component.UIComponentBase.setParent(UIComponentBase.java:447)
	at org.primefaces.component.timeline.Timeline.getClientId(Timeline.java:735)
	at org.primefaces.component.timeline.TimelineRenderer.encodeMarkup(TimelineRenderer.java:53)
	at org.primefaces.component.timeline.TimelineRenderer.encodeEnd(TimelineRenderer.java:47)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at org.primefaces.component.tabview.TabViewRenderer.encodeTabContent(TabViewRenderer.java:313)
	at org.primefaces.component.tabview.TabViewRenderer.encodeContents(TabViewRenderer.java:271)
	at org.primefaces.component.tabview.TabViewRenderer.encodeMarkup(TabViewRenderer.java:132)
	at org.primefaces.component.tabview.TabViewRenderer.encodeEnd(TabViewRenderer.java:71)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
	at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:89)
	at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:72)
	at org.primefaces.component.panel.PanelRenderer.encodeContent(PanelRenderer.java:206)
	at org.primefaces.component.panel.PanelRenderer.encodeMarkup(PanelRenderer.java:123)
	at org.primefaces.component.panel.PanelRenderer.encodeEnd(PanelRenderer.java:58)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:889)
	at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:85)
	at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:72)
	at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:87)
	at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:72)
	at org.primefaces.component.layout.LayoutUnitRenderer.encodeEnd(LayoutUnitRenderer.java:49)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:133)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:78)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:178)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
]]

[2017-04-17T14:15:15.275-0300] [glassfish 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=30 _ThreadName=http-listener-1(1)] [timeMillis: 1492449315275] [levelValue: 900] [[
  StandardWrapperValve[Faces Servlet]: Servlet.service() for servlet Faces Servlet threw exception
javax.faces.FacesException: Cannot add the same component twice: form:tabView2:timeline
	at com.sun.faces.context.StateContext$DynamicAddRemoveListener.handleAddRemoveWithAutoPrune(StateContext.java:751)
	at com.sun.faces.context.StateContext$DynamicAddRemoveListener.handleAdd(StateContext.java:678)
	at com.sun.faces.context.StateContext$AddRemoveListener.processEvent(StateContext.java:352)
	at com.sun.faces.context.StateContext$DynamicAddRemoveListener.processEvent(StateContext.java:568)
	at javax.faces.event.SystemEvent.processListener(SystemEvent.java:108)
	at javax.faces.event.ComponentSystemEvent.processListener(ComponentSystemEvent.java:118)
	at com.sun.faces.application.ApplicationImpl.processListenersAccountingForAdds(ApplicationImpl.java:2236)
	at com.sun.faces.application.ApplicationImpl.invokeViewListenersFor(ApplicationImpl.java:2057)
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:292)
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:247)
	at javax.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:726)
	at javax.faces.component.UIComponentBase.publishAfterViewEvents(UIComponentBase.java:2246)
	at javax.faces.component.UIComponentBase.doPostAddProcessing(UIComponentBase.java:1927)
	at javax.faces.component.UIComponentBase.setParent(UIComponentBase.java:447)
	at org.primefaces.component.timeline.Timeline.getClientId(Timeline.java:735)
	at org.primefaces.component.timeline.TimelineRenderer.encodeMarkup(TimelineRenderer.java:53)
	at org.primefaces.component.timeline.TimelineRenderer.encodeEnd(TimelineRenderer.java:47)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at org.primefaces.component.tabview.TabViewRenderer.encodeTabContent(TabViewRenderer.java:313)
	at org.primefaces.component.tabview.TabViewRenderer.encodeContents(TabViewRenderer.java:271)
	at org.primefaces.component.tabview.TabViewRenderer.encodeMarkup(TabViewRenderer.java:132)
	at org.primefaces.component.tabview.TabViewRenderer.encodeEnd(TabViewRenderer.java:71)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
	at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:89)
	at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:72)
	at org.primefaces.component.panel.PanelRenderer.encodeContent(PanelRenderer.java:206)
	at org.primefaces.component.panel.PanelRenderer.encodeMarkup(PanelRenderer.java:123)
	at org.primefaces.component.panel.PanelRenderer.encodeEnd(PanelRenderer.java:58)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:889)
	at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:85)
	at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:72)
	at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:87)
	at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:72)
	at org.primefaces.component.layout.LayoutUnitRenderer.encodeEnd(LayoutUnitRenderer.java:49)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:133)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:344)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:78)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:178)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:316)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
]]


```

**Comment by tandraschko** [comment] 2017-04-17 17:41
does it work with newer mojarra versions? As it works fine in the showcase with both mojarra and myfaces, it think its a mojarra bug in the version used by glassfish.

**Comment by tandraschko** [comment] 2017-04-17 17:43
also make sure that the deployed WAR doesn't contain a jsf-api/jsf-impl.

**Comment by gasparbarancelli** [comment] 2017-04-17 20:04
Our system is very broad, has more than 400 controllers, we use JSF with Primefaces in all views, but only in versions above 6.0.12 with the timeline component this error occurs.

**Comment by tandraschko** [comment] 2017-04-18 13:29
You didn't answer my questsions ;)
Feel free to analyze the changes between 6.0 and 6.1 and provide a PR.

**Comment by gasparbarancelli** [comment] 2017-04-18 13:36
I have not declared any dependencies in jsf-api / jsf-impl in my pom.xml, dependencies are provided by Glassfish and Payara servers.

Yesterday test with the latest version of Payara and the error still occurs.

Everything happens as expected in the versions of primefaces below 6.0.12.

**Comment by jxmai** [comment] 2017-04-18 14:33
@gasparbarancelli Please take a look at this changelog (https://github.com/primefaces/primefaces/issues?q=is%3Aissue+is%3Aclosed+label%3A6.0.13) to find out if anything you need. There was indeed a change on timeline during 6.0.13 (https://github.com/primefaces/primefaces/commit/92781482b4bedc8edb7041e3b8a368e81fb6aa2e). You can checkout the commit before and after to build PF from source in order to debug this ticket.

**Comment by gasparbarancelli** [comment] 2017-04-18 18:12
Exactly it was a commit of version 6.0.13 that caused this problem to occur, the getClientId method of the Timeline class was changed, more precisely in the call of the method this.setParent(this.parentComponent);

https://github.com/primefaces/primefaces/commit/92781482b4bedc8edb7041e3b8a368e81fb6aa2e

**Comment by jxmai** [comment] 2017-04-18 19:00
@gasparbarancelli Since there is no sample code attached so it is hard for others to verify whether or not your use case is valid.  I looked at your stacktrace, you are using timeline inside a tabview. could you take the timeline out of the tabview container and test again ?

> javax.faces.FacesException: Cannot add the same component twice: form:tabView2:timeline

---

Looking at the source, the changes seem OK:

- if no parent component defined and the parent is not a form - > add parent component
- if no naming container: use whatever id as client ID
- If there is a naming container: append id to naming container to generate client ID

Quote:

>  the getClientId method of the Timeline class was changed, more precisely in the call of the method this.setParent(this.parentComponent)

Not really, the clientId would be the same as before if no naming container. The method only set the parent but has nothing to do with clientID.

I think this line might affect you if client Id is a problem for you.

https://github.com/primefaces/primefaces/commit/92781482b4bedc8edb7041e3b8a368e81fb6aa2e#diff-9cfb50aa4e771a4ca0ba0d5fd87eb631R277

---

If you can analyse the problem and can figure out the cause, please provide a pull request.

**Comment by gasparbarancelli** [comment] 2017-04-18 19:42
@jxmai 
The problem really only occurs if the timeline component is inside a tab component.
I just added the timeline component inside a form and the component was rendered successfully.

If I set the value false to the prependId property of the tabview component the component is rendered successfully.

**Comment by jxmai** [comment] 2017-04-18 19:55
> The problem really only occurs if the timeline component is inside a tab component.

Yes, this is what I expected :smile: 

> If I set the value false to the prependId property of the tabview component the component is rendered successfully.

Yes, you can define `prepend ID to false` for your case (`default is true`), so the naming container id won't be part of the client id. The old code achieved somewhat like prepend ID to false unintentionally I guess.

---

@gasparbarancelli  If nothing else, you can close this ticket :)

**Comment by gasparbarancelli** [comment] 2017-04-19 12:11
I solved my problem but this is a primefaces bug, I would have to solve this.

**Comment by jxmai** [comment] 2017-04-19 18:33
Hmm, I don't think it is a bug since no duplicate ids are allowed in JSF application. As I said, you haven't provided any working sample so we have to guess what your problem based on a stacktrace.  If you can provide a full sample replicated using https://github.com/primefaces/primefaces-test, please do. Otherwise, this ticket is likely done.

**Comment by tandraschko** [comment] 2017-04-19 18:42
just my 0.02$: the change was done because of a another bug because of a "null" clientId, which appeared in same cases. I think the getClientId() was called to early sometimes (maybe it the taghandler?)
I would try to check why the "hacky" fix for https://github.com/primefaces/primefaces/issues/1946 was required and maybe revert it.
But to be honest, i don't have time to invest some hours for a component, which i have never used.

**Comment by jxmai** [comment] 2017-04-19 18:51
I am not a timeline user yet either... so I might miss some background info. If the problem was on #1946 itself, I cannot tell why the fix is needed.

**Comment by gasparbarancelli** [comment] 2017-04-20 14:32
If the timeline component is just inside a form in the first rendering everything happens perfectly, but when I do an update on the form the same error occurs "javax.faces.FacesException: Can not add the same component twice: form: timeline"

**Comment by melloware** [comment] 2017-04-22 00:08
Can you produce a TEst project that demonstrates the example for us to run?  Clone this repository https://github.com/primefaces/primefaces-test.git in order to reproduce your problem, you'll have better chance to receive an answer and a solution.

**Comment by tandraschko** [comment] 2017-05-03 09:28
If you don't provide a example project like described by @melloware, i will close it was invalid.

**Closed as completed** 2017-05-11 17:32 UTC

**Comment by TheodorRichard** [comment] 2017-06-04 13:32
I also observed this behavior when placing a timeline inside a h:dataTable. It works with PF 6.0. In PF 6.1, I get the above exception, even when there is only a single timeline object inside the table.

Can we reopen this ticket @tandraschko ?

**Comment by jxmai** [comment] 2017-06-08 21:58
relate to #2425. It should be a regression causing by https://github.com/primefaces/primefaces/commit/92781482b4bedc8edb7041e3b8a368e81fb6aa2e

**Comment by tandraschko** [comment] 2017-06-12 12:56
Could be fixed, so please try a trunk build!

**Comment by stefanwendelmann** [comment] 2017-09-25 12:03
Same issue for me with PF 6.1. When i use PF 6.0 its working fine.
The exact eample can be found here: https://gist.github.com/60cd4e4f7bda0d75eee013523b7dbe9c.git

**Comment by jxmai** [comment] 2017-09-25 14:01
@stefanwendelmann This bug is in PF6.1, so you need to build the source by yourself, wait for PF6.2 or use an elite version.

**Comment by markusg80** [comment] 2017-11-16 14:48
Still same issue for me also with Primefaces Elite 6.1.8. Is there now a fix?

**Comment by melloware** [comment] 2017-11-16 14:58
Yes and @mertsincan would have to backport it from 6.2 to 6.1.9.   If you are a PRO user you can simply submit the request under your PRO account or if not a PRO user just hope and pray @mertsincan decides to backport this.  Or wait for 6.2 next month.
