### ISSUE TITLE
There are some problems on the frozen column data table at a special case

### ISSUE THREAD

**Issue by supergamestone** [primefaces/primefaces#1855] opened 2016-10-21 06:22 UTC
1) Environment
- PrimeFaces version: 
  -- 5.3   6.0
- Does it work on the newest PrimeFaces version?
  -- No
- Application server + version:
  -- WebLogic Server 12.1.2.0.0
- Affected browsers:
  -- Google Chorme
![image](https://cloud.githubusercontent.com/assets/17096860/20255892/8bb162d6-aa83-11e6-8f16-d2bb08b37258.png)
![image](https://cloud.githubusercontent.com/assets/17096860/20255942/d4b4acd6-aa83-11e6-9c47-9a4bb37d87b9.png)

2) Expected behavior
When the bottom border of the last bottom row is at between the top border and the bottom border of horizontal scroll bar:
1. the frozen part’s rows don't shift position from the scroll part’s rows on the data table, if the vertical scroll to the best bottom.
2. the header don't shift position from the scroll part’s columns on the data table, if the horizontal scroll to the best right.

3) Actual behavior
When the bottom border of the last bottom row is at between the top border and the bottom border of horizontal scroll bar:
1. the frozen part’s rows shift position from the scroll part’s rows on the data table, if the vertical scroll to the best bottom.
2. the header shift position from the scroll part’s columns on the data table, if the horizontal scroll to the best right.

4) Steps to reproduce
a. frozen columns data table is shown
b. let the vertical scroll bar to the best bottom
c. let the horizontal scroll bar to the best right

5) Sample XHTML

```
<h:form id="frm">
    <p:commandButton value="Search" actionListener="#{dtFilterView.search}" update=":frm" oncomplete="PF('carsTable').clearFilters();"  />

    <p:dataTable var="car" value="#{dtFilterView.cars}" widgetVar="carsTable"
                 emptyMessage="No cars found with given criteria"
                 filteredValue="#{dtFilterView.filteredCars}"
                 scrollable="true"
                 scrollWidth="650" scrollHeight="305"
                 paginator="true"
                 rows="10" 
                 paginatorPosition="bottom"
                 frozenColumns="2"
                 liveResize="false"
                 style="width: 900dx;"
                 >


        <p:column width="120" filterBy="#{car.id}" headerText="Id" filterMatchMode="contains">
            <h:outputText value="#{car.id}" />
        </p:column>

        <p:column width="150" headerText="Year">
            <h:outputText value="#{car.year}" />
        </p:column>

        <p:column width="150" filterBy="#{car.brand}" headerText="Brand" filterMatchMode="exact">
            <f:facet name="filter">
                <p:selectOneMenu onchange="PF('carsTable').filter()" >
                    <f:selectItem itemLabel="Select One" itemValue="#{null}" noSelectionOption="true" />
                    <f:selectItems value="#{dtFilterView.brands}" />
                </p:selectOneMenu>
            </f:facet>
            <h:outputText value="#{car.brand}" />
        </p:column>

        <p:column width="150" filterBy="#{car.color}" headerText="Color" filterMatchMode="in">
            <f:facet name="filter">
                <p:selectCheckboxMenu label="Colors" onchange="PF('carsTable').filter()" panelStyle="width:125px" scrollHeight="150">
                    <f:selectItems value="#{dtFilterView.colors}" />
                </p:selectCheckboxMenu>
            </f:facet>
            <h:outputText value="#{car.color}" />
        </p:column>

        <p:column width="150" filterBy="#{car.price}" headerText="Price" filterFunction="#{dtFilterView.filterByPrice}">
            <h:outputText value="#{car.price}">
                <f:convertNumber currencySymbol="$" type="currency"/>
            </h:outputText>
        </p:column>

        <p:column width="150" filterBy="#{car.price}" headerText="Price1" filterFunction="#{dtFilterView.filterByPrice}">
            <h:outputText value="#{car.price}">
                <f:convertNumber currencySymbol="$" type="currency"/>
            </h:outputText>
        </p:column>

        <p:column width="150" filterBy="#{car.price}" headerText="Price2" filterFunction="#{dtFilterView.filterByPrice}">
            <h:outputText value="#{car.price}">
                <f:convertNumber currencySymbol="$" type="currency"/>
            </h:outputText>
        </p:column>

        <p:column width="150" filterBy="#{car.price}" headerText="Price3" filterFunction="#{dtFilterView.filterByPrice}">
            <h:outputText value="#{car.price}">
                <f:convertNumber currencySymbol="$" type="currency"/>
            </h:outputText>
        </p:column>

        <p:column width="150" filterBy="#{car.price}" headerText="Price4" filterFunction="#{dtFilterView.filterByPrice}">
            <h:outputText value="#{car.price}">
                <f:convertNumber currencySymbol="$" type="currency"/>
            </h:outputText>
        </p:column>
    </p:dataTable>
</h:form>

```

6) Sample bean
FilterView.java

```
package org.primefaces.showcase.view.data.datatable;

import java.io.Serializable;
import java.util.List;
import java.util.Locale;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import org.primefaces.showcase.domain.Car;
import org.primefaces.showcase.service.CarService;

@ManagedBean(name="dtFilterView")
@ViewScoped
public class FilterView implements Serializable {

    private List<Car> cars;

    private List<Car> filteredCars;

    @ManagedProperty("#{carService}")
    private CarService service;

    @PostConstruct
    public void init() {
        cars = service.createCars(100);
    }

    public boolean filterByPrice(Object value, Object filter, Locale locale) {
        String filterText = (filter == null) ? null : filter.toString().trim();
        if(filterText == null||filterText.equals("")) {
            return true;
        }

        if(value == null) {
            return false;
        }

        return ((Comparable) value).compareTo(Integer.valueOf(filterText)) > 0;
    }

    public void search() {
        cars = service.createCars(500);
    }

    public List<String> getBrands() {
        return service.getBrands();
    }

    public List<String> getColors() {
        return service.getColors();
    }

    public List<Car> getCars() {
        return cars;
    }

    public List<Car> getFilteredCars() {
        return filteredCars;
    }

    public void setFilteredCars(List<Car> filteredCars) {
        this.filteredCars = filteredCars;
    }

    public void setService(CarService service) {
        this.service = service;
    }
}
```

CarService.java

```
package org.primefaces.showcase.service;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import org.primefaces.showcase.domain.Car;

@ManagedBean(name = "carService")
@ApplicationScoped
public class CarService {

    private final static String[] colors;

    private final static String[] brands;

    static {
        colors = new String[10];
        colors[0] = "Black";
        colors[1] = "White";
        colors[2] = "Green";
        colors[3] = "Red";
        colors[4] = "Blue";
        colors[5] = "Orange";
        colors[6] = "Silver";
        colors[7] = "Yellow";
        colors[8] = "Brown";
        colors[9] = "Maroon";

        brands = new String[10];
        brands[0] = "BMW";
        brands[1] = "Mercedes";
        brands[2] = "Volvo";
        brands[3] = "Audi";
        brands[4] = "Renault";
        brands[5] = "Fiat";
        brands[6] = "Volkswagen";
        brands[7] = "Honda";
        brands[8] = "Jaguar";
        brands[9] = "Ford";
    }

    public List<Car> createCars(int size) {
        List<Car> list = new ArrayList<Car>();
        for(int i = 0 ; i < size ; i++) {
            list.add(new Car(getRandomId(), getRandomBrand(), getRandomYear(), getRandomColor(), getRandomPrice(), getRandomSoldState()));
        }

        return list;
    }

    private String getRandomId() {
        return UUID.randomUUID().toString().substring(0, 8);
    }

    private int getRandomYear() {
        return (int) (Math.random() * 50 + 1960);
    }

    private String getRandomColor() {
        return colors[(int) (Math.random() * 10)];
    }

    private String getRandomBrand() {
        return brands[(int) (Math.random() * 10)];
    }

    public int getRandomPrice() {
        return (int) (Math.random() * 100000);
    }

    public boolean getRandomSoldState() {
        return (Math.random() > 0.5) ? true: false;
    }

    public List<String> getColors() {
        return Arrays.asList(colors);
    }

    public List<String> getBrands() {
        return Arrays.asList(brands);
    }
}

```

Car.java

```
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.primefaces.showcase.domain;

/**
 *
 * @author Administrator
 */
public class Car {

    private String id;

    private String brand;

    private int year;

    private String color;

    private int price;

    private boolean sold;

    public Car(String id, String brand, int year, String color, int price, boolean soldState) {
        this.id = id;
        this.brand = brand;
        this.year = year;
        this.color = color;
        this.price = price;
        this.sold = soldState;

    }

    /**
     * @return the id
     */
    public String getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * @return the brand
     */
    public String getBrand() {
        return brand;
    }

    /**
     * @param brand the brand to set
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * @return the year
     */
    public int getYear() {
        return year;
    }

    /**
     * @param year the year to set
     */
    public void setYear(int year) {
        this.year = year;
    }

    /**
     * @return the color
     */
    public String getColor() {
        return color;
    }

    /**
     * @param color the color to set
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * @return the price
     */
    public int getPrice() {
        return price;
    }

    /**
     * @param price the price to set
     */
    public void setPrice(int price) {
        this.price = price;
    }

    /**
     * @return the soldState
     */
    public boolean isSold() {
        return sold;
    }

    /**
     * @param soldState the soldState to set
     */
    public void setSold(boolean soldState) {
        this.sold = soldState;
    }

}

```

**Comment by kukel** [comment] 2016-11-11 15:18
> PrimeFaces version:
> -- 6.0
> Does it work on the newest PrimeFaces version?
> -- Yes

On what version does it work without errors then? Which 6.0.x?  And why do you report an issue if it works on the newest PF version?

**Comment by supergamestone** [comment] 2016-11-14 06:36
1. This is a wrong comment. I can not understand the question. I have fixed the wrong on the top comment as here.
   - Does it work on the newest PrimeFaces version?
   - -- No
2. The issue is found on the version of 5.3 and 6.0.
3. The the newest free PF version is 6.0. The 6.0.x is only for ELITE and PRO users that is not free version.
   ![image](https://cloud.githubusercontent.com/assets/17096860/20255966/ec596c0a-aa83-11e6-99c4-a37e2acf0342.png)

**Comment by schlebe** [comment] 2017-05-23 12:42
I have the same issue with simple DataTable and I can explain Why ? 

On an existing DataTable, I have added the following line of HTML Primefaces code

frozenColumns="1"

When the table is displayed, the rows of the first column are not more aligned with the row of the rest of the table.

The problem happens because the presence of icon in second part of table make that the rows in right part of table are higher that the row of frozen part of table.

This issue seems to be identical to [https://github.com/primefaces/primefaces/issues/1155](https://github.com/primefaces/primefaces/issues/1155) issue.

**Comment by melloware** [comment] 2018-03-12 13:45
@schlebe and company.  A clever trick i found out was due to the icon in the frozen or non frozen rows causes the height to be off.  Simply add this hidden column in the other side from where your icon is and it makes the row heights line up.

```xml
<p:column id="colHidden" exportable="false" toggleable="false" style="width:1px;padding: 0 0 0 1px !important;">
	<!-- Trick Primefaces into a button sized row -->
	<p:commandButton type="button" icon="fa fa-print" style="visibility:hidden"/>
</p:column>
```

**Comment by melloware** [comment] 2020-09-05 22:21
Duplicate of #1155

**Closed as completed by melloware** 2020-09-05 22:21 UTC
Labels: :lady_beetle: defect, workaround
