### ISSUE TITLE
PositionType absolute option for Dialog Framework

### ISSUE THREAD

**Issue by claudineij** [primefaces/primefaces#210] opened 2015-04-30 20:48 UTC
Like issue #6 it will be great if we have the same functionality for Dialog Framework, for example:

``` java
options.put("positionType", "absolute")
```

**Comment by arunvc1** [comment] 2016-03-22 09:52
It would be nice to have top in options
eg top: '5px'

http://forum.primefaces.org/viewtopic.php?f=3&t=40364&p=127615&hilit=dialog+framework+top#p127615

**Comment by tandraschko** [comment] 2017-10-17 14:00
Duplicate of #495

**Closed as completed by tandraschko** 2017-10-17 14:00 UTC
Labels: Resolution: Duplicate
