### ISSUE TITLE
Columns: NumberFormatException updating buttons inside facet header of p:columns

### ISSUE THREAD

**Issue by HKM-CIA** [primefaces/primefaces#9245] opened 2022-09-28 12:14 UTC
### Describe the bug

We have a dataTable with buttons inside the facet header of a **p:columns** component.

```
<h:form id="frmTest">
	<p:dataTable id="dataTable" var="row" value="#{testView.rows}" rowKey="#{row.id}" selectionMode="multiple"
		selection="#{testView.selectedRows}">

		<p:ajax event="rowSelect" listener="#{testView.onRowSelect()}" update="frmTest:messages" />
		
		<p:column style="width:40px">
			<f:facet name="header">
				<h:outputText value="id" />
				<ui:fragment>
					<br />
				</ui:fragment>
				<p:commandButton id="commandButtonId" value="OK" disabled="#{testView.buttonDisabled}" style="font-size:small;">
				</p:commandButton>
			</f:facet>
			<h:outputText style="float:right;" value="#{row.id}" />
		</p:column>

		<p:columns id="dailyValues" columnIndexVar="columnIndex" value="#{testView.getDailyValues(row)}" var="dailyValue"
			style="width:40px">
			<f:facet name="header">
				<h:outputText value="#{columnIndex+1}" />
				<ui:fragment>
					<br />
				</ui:fragment>
				<p:commandButton id="commandButton" value="OK" disabled="#{testView.buttonDisabled}" style="font-size:small;">
				</p:commandButton>
			</f:facet>
			<h:outputText id="dailyValue" style="float:right;" value="#{dailyValue}" />
		</p:columns>
	</p:dataTable>
</form>
```

The resulting button ids are "frmTest:dataTable:dailyValues:i:commandButton" with 'i' from 0 to number of columns - 1.

On rowSelect event the buttons are updated  and get enabled or disabled.

With primefaces 6.2.30 everything works fine.
Using any version greater than 6.x, this leads to the following exception:
`Caused by: java.lang.NumberFormatException: Trying to extract rowIndex from clientId 'frmTest:dataTable:dailyValues:0:commandButton' For input string: "dailyValues"`

However, updating a button inside the facet header of a **p:column** component works with any version.

```
public class TestView implements Serializable {
.
public void onRowSelect() {
	buttonsDisabled = !buttonsDisabled;

	try {
		// update for buttons in header of p:column works for all versions
		PrimeFaces.current().ajax().update(columnButtonIds);

		FacesContext.getCurrentInstance().addMessage(null,
				new FacesMessage(FacesMessage.SEVERITY_INFO, "update buttons in header of p:column", "successful"));
	} catch (Exception e) {
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL,
				"update buttons in header of p:column", e.getMessage()));
		e.printStackTrace();
	}

	try {
		// update for buttons in header of p:columns works only for versions < 7.x
		PrimeFaces.current().ajax().update(dynamicColumnsButtonIds);

		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO,
				"update buttons in header of p:columns", "successful"));
	} catch (Exception e) {
		FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL,
				"update buttons in header of p:columns", e.getMessage()));
		e.printStackTrace();
	}
}
```
in pom.xml you can switch between primefaces 11.0.8 and 6.2.30.

[primefaces-test.zip](https://github.com/primefaces/primefaces/files/9664695/primefaces-test.zip)

 see also:https://forum.primefaces.org/viewtopic.php?f=3&t=75917

### Expected behavior

on rowSelect buttons in facet header of p:columns component should be enabled or disabled

### PrimeFaces edition

Elite

### PrimeFaces version

11.0.8

### Theme

none

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

1.8.x

### Browser(s)

firefox

**Comment by melloware** [comment] 2022-09-28 12:16
Wonder if its related to this too: https://github.com/primefaces/primefaces/issues/7369

**Comment by tandraschko** [comment] 2022-09-28 13:22
works fine in MyFaces (at least without exception) and the stacktrace is from Mojarra

**Comment by melloware** [comment] 2022-09-29 11:28
Yep fails on Mojarra works on MyFaces.

`mvn clean jetty:run -Pmyfaces23` - WORKS!

`mvn clean jetty:run -Pmojarra23` - FAILS.

So I would report this to the Mojarra team including your reproducer: https://github.com/eclipse-ee4j/mojarra/issues

**Comment by HKM-CIA** [comment] 2022-10-04 07:07
Sorry, just one question.
Why does it work with primefaces 6.2.30 ?
Am i missing something, i thought that the primefaces-test projects uses the same mojarra version for 6.2.30 and 11.0.8.

**Comment by melloware** [comment] 2022-10-04 11:38
@HKM-CIA Between 6.2 and 11.0 there have been over 1000+ bugs fixes and feature enhancements over 4 years.  Most likely some bug or gap we closed is now causing this issue on Mojarra but not on MyFaces.

**Comment by HKM-CIA** [comment] 2022-10-05 08:14
@melloware, @tandraschko
thanks for your quick replies and good support

**Comment by melloware** [comment] 2022-10-07 10:58
Thanks for opening the Mojarra ticket will close this one.

**Closed as completed by melloware** 2022-10-07 10:58 UTC
Labels: third-party

**Comment by fanste** [comment] 2024-05-21 12:18
I know that this issue is quite old, but while debugging an error on mojarra I stumpled upon this issue. Therefore some notes on this issue - just for the sake of completeness (any my own history, if I ever stumple upon this again..):

- It works on 6.x most likely because the test project runs with `PROJECT_STAGE=Production` and the passed clientId is simply forwarded without any validation. This changed in 7.x to the currently still used logic.
- Mojarra faile because of - well, have a look on that specific issue ;) But that issue won't do it completely. This is revised in https://github.com/eclipse-ee4j/mojarra/pull/5446
- Myfaces fails too, but due to a tiny little difference in the implementation, MyFaces won't fail hard but falls back to the [workaround ](https://github.com/primefaces/primefaces/blob/master/primefaces/src/main/java/org/primefaces/PrimeFaces.java#L363) implemented in Primefaces.

As my MyFaces jira account is pending: The [check on `UIColumn`](https://github.com/apache/myfaces/blob/1b8695232fdf601cad043e45be570da89a4e65b3/api/src/main/java/jakarta/faces/component/UIData.java#L414) might also be the reason - as in Mojarra. I will sent a issue to myfaces asap (@tandraschko).

**Comment by melloware** [comment] 2024-05-21 12:35
@fanste i approved your MyFaces account request.

**Comment by fanste** [comment] 2024-05-21 13:12
Related MyFaces issue: https://issues.apache.org/jira/browse/MYFACES-4667
