### ISSUE TITLE
TabView: duplicate ID error with same id on two tabs

### ISSUE THREAD

**Issue by Jens-dojo** [primefaces/primefaces#12469] opened 2024-08-14 01:59 UTC
### Describe the bug

I updated from PF 13.x to 14.0.3.   [EDIT: I am unsure if I used 13.x before. Might also have been an older version...]

<p:tabview

The elements of a <p:tab do no longer inherit the id of the <p:tab
All tab panel elements now have only the tabview id as parent.
Is this intentional or a bug?

Sample:
```
	<p:tabView id="tab_id">
	
		<p:tab id="tab" title="Tab 1">

			<h:outputText id="output"  value="Test 1" />
		</p:tab>
	</p:tabView>
```

Check the screenshot of the produced html tree.

in former versions, the id of the outputtext was 
"tab_id:tab:output"

Now it is
"tab_id:output"

Seems like a bug to me ?
![tab](https://github.com/user-attachments/assets/d153935e-622a-406e-bb50-ecde50bdfc76)

### PrimeFaces edition

None

### PrimeFaces version

14.0.3

### JSF implementation

Mojarra

### JSF version

2.3

### Java version

17

**Comment by Jens-dojo** [comment] 2024-08-14 02:06
PS: And if I have two tabs with identical sub-element Ids, I even got identical complete Ids in the html tree:
```
<p:tabView` id="tab_id">	
		<p:tab id="tab1" title="Tab 1">
			<h:outputText id="output"  value="Test 1" />
		</p:tab>
		<p:tab id="tab2" title="Tab 2">
			<h:outputText id="output"  value="Test 2" />
		</p:tab>
	</p:tabView>
```


Any workaround or quick fix?
My <p:ajax update="element">  is broken as the Ids do no longer match.....

![image](https://github.com/user-attachments/assets/66b2db79-1274-447d-9a85-8ad30f019b38)

**Comment by melloware** [comment] 2024-08-14 12:13
yeah this feels like a bug we should try and never have duplicate ID's in the DOM.

**Comment by melloware** [comment] 2024-08-14 13:20
Reproducer actually throws an error:
[pf-12469.zip](https://github.com/user-attachments/files/16613643/pf-12469.zip)

```
javax.servlet.ServletException: javax.servlet.ServletException: Component ID frmTest:tab_id:output has already been found in the view. 
```

**Comment by melloware** [comment] 2024-08-14 13:22
@Jens-dojo are you sure this changed between 13 and 14 as I get the same error with 13.0.0

```
javax.servlet.ServletException: javax.servlet.ServletException: 
Component ID frmTest:tab_id:output has already been found in the view. 
```

**Comment by Jens-dojo** [comment] 2024-08-14 14:10
Dear Melloware,

hm, now as you ask it... I am not sure any longer. Maybe I used a 12.x version before. It may sound crazy, but I don have a backup that is old enough to see what version I used before.
In any case, I was surprised that no-one noticed that bug before. ;-)

thank you, once again.
Jens

**Comment by melloware** [comment] 2024-08-14 15:18
let me try 12.0.0

**Comment by melloware** [comment] 2024-08-14 15:19
Nope 12.0.0 has the same issue.

**Comment by melloware** [comment] 2024-08-14 15:23
OK tested the following:

8.0 - same issue
10.0.0 - same issue
11.0.0 - same issue
12.0.0 - same issue
13.0.0 - same issue
14.0.0 - same issue
15.0.0 - same issue


So I am not going back any futher than 8.0 but this issue looks like it has worked like this for at least 5 years.

**Comment by Jens-dojo** [comment] 2024-08-14 15:43
That really puzzles me. I am sure that I used a PF version above 8.
And the only reason why I noticed the bug, was that after the upgrade my <p:ajax update"ID"> did not work any longer.
And my css did not work any longer.
BTW: I am using JavaEE Jakarta and Tomee 9.
 Strange, very strange...
 But thanks for all your work....

**Comment by melloware** [comment] 2024-08-14 16:25
Oh I know why.  If PF14 we cut out all our custom Search Expressions so say you had "tabview:tabPanel:id" that works in PF13 and below but now we just rely on JSF 2.3 core Search Expressions andthat middle expression which used to be ignored is now not valid.

So the search expression is now "tabview:id"` as TabPanel is not a UINamingContainer.

**Comment by melloware** [comment] 2024-08-14 19:20
@Rapster @tandraschko i am inclined to say this is won't fix since TabView is the naming container and not the individual Tab Panels so really its a duplicate ID in the same component as if you had done it in `<p:panel>`

**Comment by tandraschko** [comment] 2024-08-14 20:06
Its there since ever, so either new feature and/or wont fix

**Closed as not planned** 2024-08-15 12:40 UTC
Labels: Resolution:  Wontfix
