### ISSUE TITLE
PF8 bug, regression or incomplete migration guide

### ISSUE THREAD

**Issue by jopen-ux** [primefaces/primefaces#5801] opened 2020-04-16 12:55 UTC
Migrating from PF7 to PF8 we notice a very important (blocking) issue on plenty of our  pages.
When opening on many of them (not all, some are still working fine)  a dialog or a confirm Dialog , all the page including the modal dialog) are now UI blocked, leading to a non usable UI of course.

This seems to appear where dialog is inside tabView or accordionPanel

**Comment by tandraschko** [comment] 2020-04-16 12:59
Please provide a example as mentioned in the issue Template
Otherwise we cant help

**Comment by melloware** [comment] 2020-04-16 13:06
This is your issue I bet: https://github.com/primefaces/primefaces/issues/5675

Read the whole ticket.

**Comment by melloware** [comment] 2020-04-16 13:07
duplicate of https://github.com/primefaces/primefaces/issues/5675

**Closed as completed** 2020-04-16 13:08 UTC
Labels: Resolution: Duplicate, 8.0.2

**Comment by jopen-ux** [comment] 2020-04-16 13:32
ok. I was ready to upload a very simple example code extracted from our app. Can still do it if needed

**Comment by melloware** [comment] 2020-04-16 13:34
Nope just read that ticket for existing examples, a better way to do what you are doing or a simple solution of `@(body)`  but my solution at the bottom of the ticket to me is the "correct" way of doing it.

**Comment by melloware** [comment] 2020-04-21 11:44
Fixed in Elite 8.0.2

**Comment by jopen-ux** [comment] 2020-04-22 13:38
So , for the community edition we have to stay in 7.0 and wait for 9.0 ?

**Comment by melloware** [comment] 2020-04-22 13:47
Yes or subscribe to Elite which is half off right now and be able to download 8.0.2 8.03 etc.

Or take a risk an patch your 8.0 youself with my PR fixes.
